import type { Efemeride } from '../../core/data/db'
import type { Idioma } from '../../core/state/ajustesStore'
import { diaDelAnio } from '../../core/fechaLocal'
import { enIdioma, type PorIdioma } from '../../core/i18n/porIdioma'
import { resumenWikipedia } from './catalogo'

/**
 * Catálogo de la especie del día: rota por día del año. La ficha (foto y
 * párrafo) se pide a Wikipedia usando el NOMBRE CIENTÍFICO como título, que
 * existe en todos los idiomas y redirige al artículo local ("Vulpes lagopus" →
 * "Arctic fox"). El dato curado sirve de gancho y de respaldo sin red.
 */
interface Especie extends PorIdioma<string> {
  /** Nombre científico: también es el título del artículo en Wikipedia. */
  cientifico: string
  /** El gancho curado, aparte porque es una segunda cadena localizable. */
  dato: PorIdioma<string>
}

const ESPECIES: Especie[] = [
  {
    cientifico: 'Vulpes lagopus',
    es: 'Zorro ártico',
    en: 'Arctic fox',
    pt: 'Raposa-do-ártico',
    fr: 'Renard polaire',
    de: 'Polarfuchs',
    it: 'Volpe artica',
    ja: 'ホッキョクギツネ',
    zh: '北极狐',
    ko: '북극여우',
    ru: 'Песец',
    hi: 'आर्कटिक लोमड़ी',
    tr: 'Kutup tilkisi',
    id: 'Rubah arktik',
    pl: 'Lis polarny',
    nl: 'Poolvos',
    ar: 'الثعلب القطبي',
    dato: {
      es: 'Cambia su pelaje de blanco invernal a marrón en verano y aguanta hasta 50 grados bajo cero sin temblar.',
      en: 'It swaps its white winter coat for a brown one in summer and endures −50 °C without shivering.',
      pt: 'Troca a pelagem branca do inverno por outra marrom no verão e aguenta 50 graus negativos sem tremer.',
      fr: 'Il troque son pelage blanc d’hiver contre un pelage brun en été et supporte −50 °C sans frissonner.',
      de: 'Er tauscht sein weißes Winterfell im Sommer gegen ein braunes und hält −50 °C aus, ohne zu zittern.',
      it: 'Cambia il manto bianco invernale con uno bruno in estate e resiste a −50 °C senza tremare.',
      ja: '冬の白い毛を夏には茶色に替え、氷点下50度でも震えません。',
      zh: '冬天的白毛到夏天换成褐色，零下50度也不发抖。',
      ko: '겨울의 흰 털을 여름엔 갈색으로 바꾸고, 영하 50도에도 떨지 않아요.',
      ru: 'Меняет белую зимнюю шубу на бурую летнюю и не дрожит даже при −50 °C.',
      hi: 'सर्दियों का सफ़ेद फर गर्मियों में भूरा हो जाता है, और −50 °C में भी यह नहीं कांपती।',
      tr: 'Kışın beyaz olan tüyü yazın kahverengiye döner ve −50 °C’de bile titremez.',
      id: 'Bulu putihnya di musim dingin berubah cokelat saat musim panas, dan ia tahan −50 °C tanpa menggigil.',
      pl: 'Białe zimowe futro zmienia latem na brązowe i wytrzymuje −50 °C, nawet nie drżąc.',
      nl: 'Hij ruilt zijn witte wintervacht in de zomer voor een bruine en verdraagt −50 °C zonder te rillen.',
      ar: 'يبدّل فروه الأبيض الشتوي بآخر بنّي في الصيف، ويحتمل −50 °C دون أن يرتجف.',
    },
  },
  {
    cientifico: 'Panthera tigris',
    es: 'Tigre',
    en: 'Tiger',
    pt: 'Tigre',
    fr: 'Tigre',
    de: 'Tiger',
    it: 'Tigre',
    ja: 'トラ',
    zh: '老虎',
    ko: '호랑이',
    ru: 'Тигр',
    hi: 'बाघ',
    tr: 'Kaplan',
    id: 'Harimau',
    pl: 'Tygrys',
    nl: 'Tijger',
    ar: 'الببر',
    dato: {
      es: 'Sus rayas son únicas como una huella dactilar y siguen dibujadas en la piel, no solo en el pelo.',
      en: 'Its stripes are as unique as a fingerprint, and they are printed on the skin, not just the fur.',
      pt: 'Suas listras são únicas como uma impressão digital e continuam desenhadas na pele, não só no pelo.',
      fr: 'Ses rayures sont uniques comme une empreinte digitale et marquent aussi la peau, pas que le pelage.',
      de: 'Seine Streifen sind einzigartig wie ein Fingerabdruck und sitzen auch auf der Haut, nicht nur im Fell.',
      it: 'Le sue striature sono uniche come un’impronta digitale e segnano anche la pelle, non solo il pelo.',
      ja: '縞模様は指紋のように一頭ごとに違い、毛だけでなく皮膚にも刻まれています。',
      zh: '每一道条纹都像指纹一样独一无二，连皮肤上都印着同样的花纹。',
      ko: '줄무늬는 지문처럼 개체마다 다르고, 털뿐 아니라 피부에도 새겨져 있어요.',
      ru: 'Полосы уникальны, как отпечаток пальца, и отпечатаны не только на шерсти, но и на коже.',
      hi: 'इसकी धारियां उंगलियों के निशान जैसी अनोखी होती हैं और सिर्फ़ फर पर नहीं, खाल पर भी बनी रहती हैं।',
      tr: 'Çizgileri parmak izi gibi tektir ve yalnızca tüyünde değil, derisinde de çizilidir.',
      id: 'Corengnya seunik sidik jari dan tercetak sampai ke kulitnya, bukan cuma di bulunya.',
      pl: 'Jego pasy są niepowtarzalne jak odcisk palca i odbijają się nie tylko na sierści, ale i na skórze.',
      nl: 'Zijn strepen zijn zo uniek als een vingerafdruk en zitten ook op de huid, niet alleen in de vacht.',
      ar: 'خطوطه فريدة كبصمة الإصبع، وهي مرسومة على جلده لا على فروه وحده.',
    },
  },
  {
    cientifico: 'Ailuropoda melanoleuca',
    es: 'Panda gigante',
    en: 'Giant panda',
    pt: 'Panda-gigante',
    fr: 'Panda géant',
    de: 'Großer Panda',
    it: 'Panda gigante',
    ja: 'ジャイアントパンダ',
    zh: '大熊猫',
    ko: '자이언트판다',
    ru: 'Большая панда',
    hi: 'विशाल पांडा',
    tr: 'Dev panda',
    id: 'Panda raksasa',
    pl: 'Panda wielka',
    nl: 'Reuzenpanda',
    ar: 'الباندا العملاقة',
    dato: {
      es: 'Es un carnívoro que come bambú catorce horas al día y tiene un "sexto dedo" para sujetar los tallos.',
      en: 'A carnivore that eats bamboo fourteen hours a day, using a "sixth finger" to grip the stalks.',
      pt: 'É um carnívoro que come bambu catorze horas por dia e tem um "sexto dedo" para segurar os talos.',
      fr: 'Un carnivore qui mange du bambou quatorze heures par jour, avec un "sixième doigt" pour tenir les tiges.',
      de: 'Ein Raubtier, das vierzehn Stunden am Tag Bambus frisst und die Halme mit einem "sechsten Finger" hält.',
      it: 'Un carnivoro che mangia bambù quattordici ore al giorno e stringe i fusti con un "sesto dito".',
      ja: '一日十四時間も竹を食べる肉食動物で、茎をつかむための「六本目の指」を持っています。',
      zh: '它是食肉动物，却每天吃十四个小时的竹子，还长着抓竹竿的“第六根手指”。',
      ko: '하루 열네 시간 대나무를 먹는 육식동물이고, 줄기를 쥐는 "여섯 번째 손가락"이 있어요.',
      ru: 'Хищник, который ест бамбук по четырнадцать часов в день и держит стебли «шестым пальцем».',
      hi: 'यह मांसाहारी है जो दिन में चौदह घंटे बांस खाता है और तनों को पकड़ने के लिए इसके पास "छठी उंगली" होती है।',
      tr: 'Günde on dört saat bambu yiyen bir etçil; sapları tutmak için "altıncı bir parmağı" var.',
      id: 'Ia karnivora yang makan bambu empat belas jam sehari dan punya "jari keenam" untuk memegang batangnya.',
      pl: 'To drapieżnik, który je bambus czternaście godzin dziennie i chwyta łodygi "szóstym palcem".',
      nl: 'Een carnivoor die veertien uur per dag bamboe eet en de stengels vasthoudt met een "zesde vinger".',
      ar: 'حيوان لاحم يأكل الخيزران أربع عشرة ساعة يوميًا، ويمسك السيقان بـ"إصبع سادس".',
    },
  },
  {
    cientifico: 'Octopus vulgaris',
    es: 'Pulpo común',
    en: 'Common octopus',
    pt: 'Polvo-comum',
    fr: 'Pieuvre commune',
    de: 'Gewöhnlicher Krake',
    it: 'Polpo comune',
    ja: 'マダコ',
    zh: '普通章鱼',
    ko: '참문어',
    ru: 'Обыкновенный осьминог',
    hi: 'आम ऑक्टोपस',
    tr: 'Ahtapot',
    id: 'Gurita biasa',
    pl: 'Ośmiornica zwyczajna',
    nl: 'Europese achtarm',
    ar: 'الأخطبوط الشائع',
    dato: {
      es: 'Tiene tres corazones, sangre azul y dos tercios de sus neuronas repartidas por los brazos.',
      en: 'It has three hearts, blue blood, and two thirds of its neurons spread across its arms.',
      pt: 'Tem três corações, sangue azul e dois terços dos neurônios espalhados pelos braços.',
      fr: 'Elle a trois cœurs, du sang bleu et deux tiers de ses neurones répartis dans les bras.',
      de: 'Er hat drei Herzen, blaues Blut und zwei Drittel seiner Neuronen in den Armen verteilt.',
      it: 'Ha tre cuori, sangue blu e due terzi dei suoi neuroni distribuiti nelle braccia.',
      ja: '心臓が三つ、血は青く、神経細胞の三分の二は八本の腕に散らばっています。',
      zh: '它有三颗心脏、蓝色的血液，三分之二的神经元分布在腕足上。',
      ko: '심장이 셋, 피는 파랗고, 신경세포의 3분의 2가 다리에 흩어져 있어요.',
      ru: 'У него три сердца, голубая кровь и две трети нейронов — в щупальцах.',
      hi: 'इसके तीन दिल होते हैं, ख़ून नीला होता है और दो-तिहाई न्यूरॉन भुजाओं में बंटे रहते हैं।',
      tr: 'Üç kalbi ve mavi kanı var; nöronlarının üçte ikisi kollarına dağılmış durumda.',
      id: 'Ia punya tiga jantung, darah biru, dan dua pertiga neuronnya tersebar di lengan-lengannya.',
      pl: 'Ma trzy serca, błękitną krew, a dwie trzecie neuronów rozsiane po ramionach.',
      nl: 'Hij heeft drie harten, blauw bloed en twee derde van zijn neuronen zit in zijn armen.',
      ar: 'له ثلاثة قلوب ودم أزرق، وثلثا خلاياه العصبية موزّعة في أذرعه.',
    },
  },
  {
    cientifico: 'Danaus plexippus',
    es: 'Mariposa monarca',
    en: 'Monarch butterfly',
    pt: 'Borboleta-monarca',
    fr: 'Monarque',
    de: 'Monarchfalter',
    it: 'Farfalla monarca',
    ja: 'オオカバマダラ',
    zh: '帝王蝶',
    ko: '제왕나비',
    ru: 'Бабочка-монарх',
    hi: 'मोनार्क तितली',
    tr: 'Kral kelebeği',
    id: 'Kupu-kupu raja',
    pl: 'Monarcha',
    nl: 'Monarchvlinder',
    ar: 'الفراشة الملكية',
    dato: {
      es: 'Vuela hasta 4.000 km hasta los bosques de Michoacán, un viaje que ningún individuo hace dos veces.',
      en: 'It flies up to 4,000 km to the forests of Michoacán, a journey no single butterfly makes twice.',
      pt: 'Voa até 4.000 km até as florestas de Michoacán, uma viagem que nenhum indivíduo faz duas vezes.',
      fr: 'Il vole jusqu’à 4 000 km vers les forêts du Michoacán, un voyage qu’aucun individu ne fait deux fois.',
      de: 'Er fliegt bis zu 4.000 km zu den Wäldern von Michoacán, eine Reise, die kein Tier zweimal macht.',
      it: 'Vola fino a 4.000 km verso le foreste del Michoacán, un viaggio che nessun individuo fa due volte.',
      ja: 'ミチョアカンの森まで4,000キロを飛び、その旅を二度する個体はいません。',
      zh: '它要飞四千公里抵达米却肯的森林，而没有一只蝴蝶能飞完两趟。',
      ko: '미초아칸의 숲까지 4,000km를 날아가는데, 같은 개체가 두 번 하는 여행은 아니에요.',
      ru: 'Пролетает до 4 000 км до лесов Мичоакана — путь, который ни одна особь не повторяет дважды.',
      hi: 'यह मिचोआकान के जंगलों तक 4,000 किमी उड़ती है, और यह सफ़र कोई तितली दो बार नहीं करती।',
      tr: 'Michoacán ormanlarına dek 4.000 kilometre uçar; bu yolculuğu hiçbir kelebek iki kez yapmaz.',
      id: 'Ia terbang sampai 4.000 km ke hutan-hutan Michoacán, perjalanan yang tak pernah ditempuh dua kali oleh seekor pun.',
      pl: 'Leci nawet 4000 km do lasów Michoacán — trasy, której żaden motyl nie pokonuje dwa razy.',
      nl: 'Ze vliegt tot 4.000 km naar de bossen van Michoacán, een reis die geen enkel dier twee keer maakt.',
      ar: 'تطير حتى 4000 كيلومتر إلى غابات ميتشواكان، رحلةٌ لا تقطعها فراشة واحدة مرّتين.',
    },
  },
  {
    cientifico: 'Physeter macrocephalus',
    es: 'Cachalote',
    en: 'Sperm whale',
    pt: 'Cachalote',
    fr: 'Cachalot',
    de: 'Pottwal',
    it: 'Capodoglio',
    ja: 'マッコウクジラ',
    zh: '抹香鲸',
    ko: '향유고래',
    ru: 'Кашалот',
    hi: 'स्पर्म व्हेल',
    tr: 'İspermeçet balinası',
    id: 'Paus sperma',
    pl: 'Kaszalot',
    nl: 'Potvis',
    ar: 'حوت العنبر',
    dato: {
      es: 'Tiene el cerebro más grande del planeta y bucea dos kilómetros para cazar calamares en la oscuridad.',
      en: 'It has the largest brain on the planet and dives two kilometres to hunt squid in the dark.',
      pt: 'Tem o maior cérebro do planeta e mergulha dois quilômetros para caçar lulas no escuro.',
      fr: 'Il a le plus gros cerveau de la planète et plonge à deux kilomètres pour chasser le calmar dans le noir.',
      de: 'Er hat das größte Gehirn der Erde und taucht zwei Kilometer tief, um im Dunkeln Kalmare zu jagen.',
      it: 'Ha il cervello più grande del pianeta e si immerge per due chilometri a caccia di calamari al buio.',
      ja: '地球でいちばん大きな脳を持ち、暗闇でイカを狩るために二千メートルまで潜ります。',
      zh: '它拥有地球上最大的大脑，能下潜两千米，在黑暗里捕食乌贼。',
      ko: '지구에서 가장 큰 뇌를 가졌고, 어둠 속에서 오징어를 사냥하러 2km까지 잠수해요.',
      ru: 'У него самый большой мозг на планете, и он ныряет на два километра за кальмарами в темноте.',
      hi: 'इसका दिमाग़ धरती पर सबसे बड़ा है और यह अंधेरे में स्क्विड का शिकार करने दो किलोमीटर गहरे गोता लगाती है।',
      tr: 'Gezegenin en büyük beynine sahip; karanlıkta kalamar avlamak için iki kilometre derine dalar.',
      id: 'Otaknya terbesar di planet ini, dan ia menyelam dua kilometer untuk berburu cumi dalam gelap.',
      pl: 'Ma największy mózg na planecie i nurkuje na dwa kilometry, by polować na kalmary w ciemności.',
      nl: 'Hij heeft het grootste brein op aarde en duikt twee kilometer diep om in het donker op inktvis te jagen.',
      ar: 'يملك أكبر دماغ على الكوكب، ويغوص كيلومترين ليصطاد الحبّار في الظلام.',
    },
  },
  {
    cientifico: 'Phoenicopterus roseus',
    es: 'Flamenco común',
    en: 'Greater flamingo',
    pt: 'Flamingo-comum',
    fr: 'Flamant rose',
    de: 'Rosaflamingo',
    it: 'Fenicottero rosa',
    ja: 'オオフラミンゴ',
    zh: '大红鹳',
    ko: '큰홍학',
    ru: 'Обыкновенный фламинго',
    hi: 'बड़ा राजहंस',
    tr: 'Büyük flamingo',
    id: 'Flamingo besar',
    pl: 'Flaming różowy',
    nl: 'Flamingo',
    ar: 'النحام الأكبر',
    dato: {
      es: 'Nace gris: el rosa se lo dan los pigmentos de los crustáceos y las algas que filtra del agua.',
      en: 'It hatches grey: the pink comes from pigments in the crustaceans and algae it filters from the water.',
      pt: 'Nasce cinza: o rosa vem dos pigmentos dos crustáceos e das algas que ele filtra da água.',
      fr: 'Il naît gris : le rose vient des pigments des crustacés et des algues qu’il filtre dans l’eau.',
      de: 'Er schlüpft grau: Das Rosa stammt von den Pigmenten der Krebse und Algen, die er filtert.',
      it: 'Nasce grigio: il rosa arriva dai pigmenti dei crostacei e delle alghe che filtra dall’acqua.',
      ja: '生まれたときは灰色で、ピンクは水から濾しとる甲殻類や藻の色素によるものです。',
      zh: '它出生时是灰色的，粉红来自它从水里滤食的甲壳类和藻类色素。',
      ko: '태어날 땐 회색이고, 분홍빛은 물에서 걸러 먹는 갑각류와 조류의 색소에서 와요.',
      ru: 'Птенцы серые: розовый цвет дают пигменты рачков и водорослей, которые птица цедит из воды.',
      hi: 'यह स्लेटी पैदा होता है; गुलाबी रंग उन झींगों और शैवाल से आता है जिन्हें यह पानी से छानकर खाता है।',
      tr: 'Gri doğar: pembeliği, sudan süzdüğü kabukluların ve yosunların renk maddelerinden gelir.',
      id: 'Ia lahir kelabu: warna merah mudanya datang dari pigmen udang kecil dan alga yang ia saring dari air.',
      pl: 'Rodzi się szary — róż zawdzięcza barwnikom skorupiaków i glonów, które odcedza z wody.',
      nl: 'Hij wordt grijs geboren: het roze komt van pigmenten uit kreeftjes en algen die hij uit het water zeeft.',
      ar: 'يولد رماديًا؛ ولونه الوردي يأتي من أصبغة القشريات والطحالب التي يرشّحها من الماء.',
    },
  },
  {
    cientifico: 'Chrysocyon brachyurus',
    es: 'Aguará guazú',
    en: 'Maned wolf',
    pt: 'Lobo-guará',
    fr: 'Loup à crinière',
    de: 'Mähnenwolf',
    it: 'Lupo dalla criniera',
    ja: 'タテガミオオカミ',
    zh: '鬃狼',
    ko: '갈기늑대',
    ru: 'Гривистый волк',
    hi: 'अयाल वाला भेड़िया',
    tr: 'Yeleli kurt',
    id: 'Serigala bersurai',
    pl: 'Pampasowiec grzywiasty',
    nl: 'Manenwolf',
    ar: 'الذئب ذو العرف',
    dato: {
      es: 'Ni lobo ni zorro: un cánido de patas larguísimas que camina la pampa comiendo fruta.',
      en: 'Neither wolf nor fox: a stilt-legged canid that walks the pampas eating fruit.',
      pt: 'Nem lobo nem raposa: um canídeo de pernas altíssimas que caminha pela pampa comendo frutas.',
      fr: 'Ni loup ni renard : un canidé aux pattes immenses qui arpente la pampa en mangeant des fruits.',
      de: 'Weder Wolf noch Fuchs: ein Hundeartiger auf Stelzenbeinen, der Früchte fressend die Pampa durchstreift.',
      it: 'Né lupo né volpe: un canide dalle zampe lunghissime che attraversa la pampa mangiando frutta.',
      ja: 'オオカミでもキツネでもなく、長い脚で草原を歩き、果実を食べるイヌ科の動物です。',
      zh: '它既不是狼也不是狐狸，而是一种长腿犬科动物，边走过草原边吃果子。',
      ko: '늑대도 여우도 아닌, 아주 긴 다리로 초원을 걸으며 과일을 먹는 개과 동물이에요.',
      ru: 'Ни волк, ни лиса: длинноногий представитель псовых, который бродит по пампе и ест фрукты.',
      hi: 'न भेड़िया, न लोमड़ी: यह बेहद लंबी टांगों वाला श्वान-कुल का जानवर है जो घास के मैदानों में फल खाता चलता है।',
      tr: 'Ne kurt ne tilki: upuzun bacaklarıyla pampada meyve yiyerek dolaşan bir köpekgil.',
      id: 'Bukan serigala, bukan pula rubah: anjing liar berkaki jenjang yang menjelajah padang sambil makan buah.',
      pl: 'Ani wilk, ani lis: psowaty na bardzo długich nogach, który przemierza pampę, jedząc owoce.',
      nl: 'Geen wolf en geen vos: een hondachtige op torenhoge poten die de pampa afstruint en fruit eet.',
      ar: 'لا ذئب ولا ثعلب: من فصيلة الكلبيات، بقوائم بالغة الطول، يجوب السهول آكلًا الفاكهة.',
    },
  },
  {
    cientifico: 'Ara macao',
    es: 'Guacamayo rojo',
    en: 'Scarlet macaw',
    pt: 'Araracanga',
    fr: 'Ara rouge',
    de: 'Hellroter Ara',
    it: 'Ara scarlatta',
    ja: 'コンゴウインコ',
    zh: '绯红金刚鹦鹉',
    ko: '금강앵무',
    ru: 'Красный ара',
    hi: 'लाल मकाओ',
    tr: 'Kızıl papağan',
    id: 'Makaw merah',
    pl: 'Ara żółtoskrzydła',
    nl: 'Geelvleugelara',
    ar: 'المقو القرمزي',
    dato: {
      es: 'Forma parejas de por vida y come arcilla de los barrancos para neutralizar las semillas tóxicas.',
      en: 'It mates for life and eats clay from riverbanks to neutralise the toxic seeds in its diet.',
      pt: 'Forma casais para a vida toda e come argila dos barrancos para neutralizar as sementes tóxicas.',
      fr: 'Il s’unit pour la vie et mange l’argile des berges pour neutraliser les graines toxiques.',
      de: 'Er bleibt lebenslang beim selben Partner und frisst Lehm, um giftige Samen zu neutralisieren.',
      it: 'Forma coppie per tutta la vita e mangia argilla dalle scarpate per neutralizzare i semi tossici.',
      ja: '一生同じ相手と連れ添い、毒のある種を中和するために崖の粘土をなめます。',
      zh: '它一生只结一对伴侣，还会啄食河岸的黏土来中和有毒的种子。',
      ko: '평생 같은 짝과 지내고, 독이 있는 씨앗을 중화하려고 절벽의 점토를 먹어요.',
      ru: 'Держится одной пары всю жизнь и ест глину с обрывов, чтобы нейтрализовать ядовитые семена.',
      hi: 'यह जीवन भर एक ही जोड़ा बनाता है और ज़हरीले बीजों का असर काटने के लिए किनारों की मिट्टी खाता है।',
      tr: 'Ömür boyu tek eşle yaşar ve zehirli tohumların etkisini kırmak için yamaçlardan kil yer.',
      id: 'Ia berpasangan seumur hidup dan memakan tanah liat di tebing untuk menawarkan racun biji-bijian.',
      pl: 'Łączy się w pary na całe życie i zjada glinę ze skarp, by zneutralizować trujące nasiona.',
      nl: 'Hij blijft levenslang bij één partner en eet klei uit de oevers om giftige zaden onschadelijk te maken.',
      ar: 'يرتبط بشريكه مدى الحياة، ويأكل الطين من المنحدرات ليبطل سمّ البذور.',
    },
  },
  {
    cientifico: 'Ambystoma mexicanum',
    es: 'Ajolote',
    en: 'Axolotl',
    pt: 'Axolote',
    fr: 'Axolotl',
    de: 'Axolotl',
    it: 'Axolotl',
    ja: 'ウーパールーパー',
    zh: '美西螈',
    ko: '아홀로틀',
    ru: 'Аксолотль',
    hi: 'एक्सोलोटल',
    tr: 'Aksolotl',
    id: 'Aksolotl',
    pl: 'Aksolotl',
    nl: 'Axolotl',
    ar: 'عفريت الماء',
    dato: {
      es: 'Nunca completa la metamorfosis y regenera patas, corazón y hasta partes del cerebro.',
      en: 'It never completes metamorphosis and can regrow limbs, heart tissue and even parts of its brain.',
      pt: 'Nunca completa a metamorfose e regenera patas, coração e até partes do cérebro.',
      fr: 'Il n’achève jamais sa métamorphose et régénère pattes, cœur et même des parties de son cerveau.',
      de: 'Er schließt die Metamorphose nie ab und regeneriert Beine, Herz und sogar Teile des Gehirns.',
      it: 'Non completa mai la metamorfosi e rigenera zampe, cuore e perfino parti del cervello.',
      ja: '変態を終えないまま大人になり、脚も心臓も、脳の一部さえ再生します。',
      zh: '它一辈子不完成变态，却能再生四肢、心脏，甚至部分大脑。',
      ko: '변태를 끝내지 않은 채 어른이 되고, 다리와 심장은 물론 뇌 일부까지 재생해요.',
      ru: 'Он никогда не завершает метаморфоз и отращивает заново лапы, сердце и даже части мозга.',
      hi: 'यह कभी कायांतरण पूरा नहीं करता और टांगें, दिल और दिमाग़ के हिस्से तक दोबारा उगा लेता है।',
      tr: 'Başkalaşımını hiç tamamlamaz; bacaklarını, kalbini, hatta beyninin bir kısmını yeniden büyütür.',
      id: 'Ia tak pernah menuntaskan metamorfosis dan bisa menumbuhkan lagi kaki, jantung, bahkan bagian otaknya.',
      pl: 'Nigdy nie kończy przeobrażenia i odtwarza nogi, serce, a nawet fragmenty mózgu.',
      nl: 'Hij maakt zijn gedaanteverwisseling nooit af en laat poten, hart en zelfs stukken hersenen weer aangroeien.',
      ar: 'لا يُتمّ تحوّله أبدًا، ويعيد إنبات أطرافه وقلبه بل وأجزاء من دماغه.',
    },
  },
  {
    cientifico: 'Tursiops truncatus',
    es: 'Delfín mular',
    en: 'Bottlenose dolphin',
    pt: 'Golfinho-nariz-de-garrafa',
    fr: 'Grand dauphin',
    de: 'Großer Tümmler',
    it: 'Tursiope',
    ja: 'ハンドウイルカ',
    zh: '宽吻海豚',
    ko: '큰돌고래',
    ru: 'Афалина',
    hi: 'बॉटलनोज़ डॉल्फ़िन',
    tr: 'Afalina',
    id: 'Lumba-lumba hidung botol',
    pl: 'Butlonos',
    nl: 'Tuimelaar',
    ar: 'الدلفين قاروري الأنف',
    dato: {
      es: 'Cada individuo inventa un silbido propio que funciona como su nombre y otros usan para llamarlo.',
      en: 'Each one invents a signature whistle that works as its name, and others use it to call them.',
      pt: 'Cada indivíduo inventa um assobio próprio que funciona como nome e os outros usam para chamá-lo.',
      fr: 'Chacun invente un sifflement qui lui sert de nom et que les autres utilisent pour l’appeler.',
      de: 'Jeder erfindet einen eigenen Pfiff, der als Name dient und mit dem die anderen ihn rufen.',
      it: 'Ogni individuo inventa un fischio personale che fa da nome e che gli altri usano per chiamarlo.',
      ja: '一頭ずつ自分だけの口笛をつくり、それが名前になって仲間が呼びかけます。',
      zh: '每只都会发明专属自己的哨声当作名字，同伴就用它来呼唤。',
      ko: '저마다 자기만의 휘파람을 만들어 이름처럼 쓰고, 동료들이 그 소리로 불러요.',
      ru: 'Каждый придумывает собственный свист — он служит именем, и другие зовут его так же.',
      hi: 'हर डॉल्फ़िन अपनी एक ख़ास सीटी गढ़ती है जो उसका नाम बन जाती है और बाक़ी उसी से उसे बुलाते हैं।',
      tr: 'Her birey kendine bir ıslık uydurur; o ıslık adı olur ve ötekiler onu böyle çağırır.',
      id: 'Tiap ekor menciptakan siulan khasnya sendiri yang berfungsi sebagai nama, dan yang lain memakainya untuk memanggil.',
      pl: 'Każdy osobnik wymyśla własny gwizd, który działa jak imię — inne wołają go właśnie nim.',
      nl: 'Elk dier verzint een eigen fluittoon die als naam dient; de anderen roepen hem daarmee.',
      ar: 'يبتكر كل فرد صفيرًا خاصًا به يقوم مقام اسمه، وينادونه به.',
    },
  },
  {
    cientifico: 'Aptenodytes forsteri',
    es: 'Pingüino emperador',
    en: 'Emperor penguin',
    pt: 'Pinguim-imperador',
    fr: 'Manchot empereur',
    de: 'Kaiserpinguin',
    it: 'Pinguino imperatore',
    ja: 'コウテイペンギン',
    zh: '帝企鹅',
    ko: '황제펭귄',
    ru: 'Императорский пингвин',
    hi: 'सम्राट पेंगुइन',
    tr: 'İmparator penguen',
    id: 'Penguin kaisar',
    pl: 'Pingwin cesarski',
    nl: 'Keizerspinguïn',
    ar: 'بطريق الإمبراطور',
    dato: {
      es: 'El macho incuba el huevo sobre sus patas durante dos meses de noche polar sin comer nada.',
      en: 'The male incubates the egg on his feet through two months of polar night without eating.',
      pt: 'O macho choca o ovo sobre as patas durante dois meses de noite polar sem comer nada.',
      fr: 'Le mâle couve l’œuf sur ses pattes pendant deux mois de nuit polaire, sans rien manger.',
      de: 'Das Männchen brütet das Ei zwei Monate lang auf den Füßen aus, ohne etwas zu fressen.',
      it: 'Il maschio cova l’uovo sulle zampe per due mesi di notte polare senza mangiare nulla.',
      ja: '極夜の二か月、オスは足の上に卵をのせ、何も食べずに温めつづけます。',
      zh: '雄鸟把蛋放在脚背上，在两个月的极夜里滴食不进地孵着。',
      ko: '수컷은 두 달의 극야 동안 아무것도 먹지 않고 발등 위에서 알을 품어요.',
      ru: 'Самец два месяца полярной ночи держит яйцо на лапах и всё это время не ест.',
      hi: 'नर दो महीने की ध्रुवीय रात में बिना कुछ खाए अंडे को अपने पंजों पर सेता है।',
      tr: 'Erkek, iki ay süren kutup gecesi boyunca hiçbir şey yemeden yumurtayı ayaklarının üstünde kuluçkaya yatırır.',
      id: 'Sang jantan mengerami telur di atas kakinya selama dua bulan malam kutub tanpa makan sedikit pun.',
      pl: 'Samiec wysiaduje jajo na własnych stopach przez dwa miesiące polarnej nocy, nie jedząc nic.',
      nl: 'Het mannetje broedt het ei twee maanden lang op zijn poten uit in de poolnacht, zonder iets te eten.',
      ar: 'يحضن الذكر البيضة فوق قدميه شهرين من الليل القطبي دون أن يأكل شيئًا.',
    },
  },
  {
    cientifico: 'Apis mellifera',
    es: 'Abeja melífera',
    en: 'Western honey bee',
    pt: 'Abelha-europeia',
    fr: 'Abeille domestique',
    de: 'Westliche Honigbiene',
    it: 'Ape occidentale',
    ja: 'セイヨウミツバチ',
    zh: '西方蜜蜂',
    ko: '서양꿀벌',
    ru: 'Медоносная пчела',
    hi: 'यूरोपीय मधुमक्खी',
    tr: 'Bal arısı',
    id: 'Lebah madu',
    pl: 'Pszczoła miodna',
    nl: 'Honingbij',
    ar: 'نحلة العسل',
    dato: {
      es: 'Baila en ocho para indicar a sus compañeras la dirección y la distancia exactas de las flores.',
      en: 'It dances a figure of eight to tell the hive the exact direction and distance of the flowers.',
      pt: 'Dança em forma de oito para indicar às companheiras a direção e a distância exatas das flores.',
      fr: 'Elle danse en huit pour indiquer à la ruche la direction et la distance exactes des fleurs.',
      de: 'Sie tanzt eine Acht, um dem Stock Richtung und Entfernung der Blüten genau mitzuteilen.',
      it: 'Danza a forma di otto per indicare alle compagne la direzione e la distanza esatte dei fiori.',
      ja: '八の字に踊って、花の方角と距離を仲間に正確に伝えます。',
      zh: '它跳“8”字舞，把花丛的方向和距离准确告诉同伴。',
      ko: '8자를 그리며 춤춰서 꽃이 있는 방향과 거리를 동료들에게 정확히 알려줘요.',
      ru: 'Танцует восьмёрку, точно указывая улью направление и расстояние до цветов.',
      hi: 'यह आठ के आकार में नाचकर साथियों को फूलों की सही दिशा और दूरी बताती है।',
      tr: 'Sekiz çizerek dans eder ve arkadaşlarına çiçeklerin tam yönünü ve uzaklığını böyle söyler.',
      id: 'Ia menari membentuk angka delapan untuk memberi tahu kawanannya arah dan jarak bunga secara persis.',
      pl: 'Tańczy ósemkę, by wskazać towarzyszkom dokładny kierunek i odległość kwiatów.',
      nl: 'Ze danst een achtje om haar zusters de precieze richting en afstand van de bloemen door te geven.',
      ar: 'ترقص على شكل الرقم ثمانية لتدلّ رفيقاتها على اتجاه الأزهار ومسافتها بالضبط.',
    },
  },
  {
    cientifico: 'Panthera onca',
    es: 'Jaguar',
    en: 'Jaguar',
    pt: 'Onça-pintada',
    fr: 'Jaguar',
    de: 'Jaguar',
    it: 'Giaguaro',
    ja: 'ジャガー',
    zh: '美洲豹',
    ko: '재규어',
    ru: 'Ягуар',
    hi: 'जगुआर',
    tr: 'Jaguar',
    id: 'Jaguar',
    pl: 'Jaguar',
    nl: 'Jaguar',
    ar: 'اليغور',
    dato: {
      es: 'Tiene la mordida más potente de los felinos: mata perforando el cráneo de su presa.',
      en: 'It has the strongest bite of any big cat, killing by piercing its prey’s skull.',
      pt: 'Tem a mordida mais potente entre os felinos: mata perfurando o crânio da presa.',
      fr: 'Il a la morsure la plus puissante des félins : il tue en perforant le crâne de sa proie.',
      de: 'Er hat den stärksten Biss aller Katzen: Er tötet, indem er den Schädel der Beute durchbohrt.',
      it: 'Ha il morso più potente tra i felini: uccide perforando il cranio della preda.',
      ja: 'ネコ科でいちばん強い顎を持ち、獲物の頭骨を噛み砕いて仕留めます。',
      zh: '它是猫科里咬合力最强的，直接咬穿猎物的头骨。',
      ko: '고양잇과에서 무는 힘이 가장 세고, 사냥감의 두개골을 뚫어 사냥해요.',
      ru: 'У него самый мощный укус среди кошачьих: он убивает, пробивая череп добычи.',
      hi: 'बिल्ली-कुल में इसका काटना सबसे ताक़तवर है: यह शिकार की खोपड़ी भेदकर मारता है।',
      tr: 'Kedigillerin en güçlü ısırığı ondadır: avını kafatasını delerek öldürür.',
      id: 'Gigitannya terkuat di antara kucing besar: ia membunuh dengan menembus tengkorak mangsanya.',
      pl: 'Ma najsilniejszy zgryz wśród kotów: zabija, przebijając czaszkę ofiary.',
      nl: 'Hij heeft de krachtigste beet van alle katachtigen: hij doodt door de schedel van zijn prooi te doorboren.',
      ar: 'أقوى عضّة بين السنّوريات: يقتل فريسته باختراق جمجمتها.',
    },
  },
  {
    cientifico: 'Loxodonta africana',
    es: 'Elefante africano',
    en: 'African bush elephant',
    pt: 'Elefante-africano',
    fr: 'Éléphant de savane d’Afrique',
    de: 'Afrikanischer Elefant',
    it: 'Elefante africano',
    ja: 'アフリカゾウ',
    zh: '非洲草原象',
    ko: '아프리카코끼리',
    ru: 'Африканский слон',
    hi: 'अफ़्रीकी हाथी',
    tr: 'Afrika fili',
    id: 'Gajah afrika',
    pl: 'Słoń afrykański',
    nl: 'Savanneolifant',
    ar: 'الفيل الإفريقي',
    dato: {
      es: 'Se comunica con infrasonidos que viajan kilómetros y detecta con las patas las vibraciones del suelo.',
      en: 'It talks in infrasound that travels for kilometres and feels ground vibrations through its feet.',
      pt: 'Comunica-se por infrassons que viajam quilômetros e sente com as patas as vibrações do solo.',
      fr: 'Il communique par infrasons qui portent sur des kilomètres et sent les vibrations du sol.',
      de: 'Er spricht in Infraschall, der kilometerweit trägt, und spürt Bodenvibrationen mit den Füßen.',
      it: 'Comunica con infrasuoni che viaggiano per chilometri e sente col piede le vibrazioni del terreno.',
      ja: '何キロも届く低周波で会話し、地面の震えを足の裏で感じ取ります。',
      zh: '它用能传出几公里的次声波交谈，还用脚掌感知地面的震动。',
      ko: '몇 킬로미터를 가는 초저주파로 대화하고, 발바닥으로 땅의 진동을 느껴요.',
      ru: 'Общается инфразвуком, который слышен за километры, и ловит дрожь земли ступнями.',
      hi: 'यह कई किलोमीटर तक जाने वाली अवध्वनि से बात करता है और ज़मीन की कंपन पैरों से भांप लेता है।',
      tr: 'Kilometrelerce yol alan ses altı dalgalarla konuşur ve yerdeki titreşimleri ayaklarıyla sezer.',
      id: 'Ia berkomunikasi lewat infrasonik yang merambat berkilo-kilometer dan merasakan getaran tanah dengan kakinya.',
      pl: 'Porozumiewa się infradźwiękami niosącymi się kilometrami i wyczuwa stopami drgania gruntu.',
      nl: 'Hij praat met infrageluid dat kilometers ver draagt en voelt trillingen in de bodem met zijn poten.',
      ar: 'يتخاطب بموجات دون سمعية تقطع كيلومترات، ويلتقط اهتزازات الأرض بقوائمه.',
    },
  },
  {
    cientifico: 'Ursus maritimus',
    es: 'Oso polar',
    en: 'Polar bear',
    pt: 'Urso-polar',
    fr: 'Ours polaire',
    de: 'Eisbär',
    it: 'Orso polare',
    ja: 'ホッキョクグマ',
    zh: '北极熊',
    ko: '북극곰',
    ru: 'Белый медведь',
    hi: 'ध्रुवीय भालू',
    tr: 'Kutup ayısı',
    id: 'Beruang kutub',
    pl: 'Niedźwiedź polarny',
    nl: 'IJsbeer',
    ar: 'الدب القطبي',
    dato: {
      es: 'Su piel es negra y su pelo transparente y hueco: no es blanco, solo lo parece.',
      en: 'Its skin is black and its fur transparent and hollow: it is not white, it only looks it.',
      pt: 'A pele dele é preta e o pelo é transparente e oco: não é branco, só parece.',
      fr: 'Sa peau est noire et son poil transparent et creux : il n’est pas blanc, il en a l’air.',
      de: 'Seine Haut ist schwarz und sein Haar durchsichtig und hohl: Er sieht nur weiß aus.',
      it: 'La sua pelle è nera e il pelo trasparente e cavo: non è bianco, lo sembra soltanto.',
      ja: '皮膚は黒く、毛は透明で中は空洞。白いのではなく、白く見えるだけです。',
      zh: '它的皮肤是黑的，毛是透明中空的：它并不白，只是看起来白。',
      ko: '피부는 검고 털은 투명한 빈 관이에요. 하얀 게 아니라 하얗게 보일 뿐이죠.',
      ru: 'Кожа у него чёрная, а шерсть прозрачная и полая: он не белый, он только кажется белым.',
      hi: 'इसकी खाल काली है और बाल पारदर्शी व खोखले: यह सफ़ेद है नहीं, बस दिखता है।',
      tr: 'Derisi siyah, kılları saydam ve içi boştur: beyaz değildir, yalnızca öyle görünür.',
      id: 'Kulitnya hitam dan bulunya bening serta berongga: ia tidak putih, hanya tampak putih.',
      pl: 'Skórę ma czarną, a włosy przezroczyste i puste w środku: nie jest biały, tylko tak wygląda.',
      nl: 'Zijn huid is zwart en zijn haren zijn doorzichtig en hol: hij is niet wit, hij lijkt het maar.',
      ar: 'جلده أسود وشعره شفاف مجوّف: فهو ليس أبيض، بل يبدو كذلك.',
    },
  },
  {
    cientifico: 'Falco peregrinus',
    es: 'Halcón peregrino',
    en: 'Peregrine falcon',
    pt: 'Falcão-peregrino',
    fr: 'Faucon pèlerin',
    de: 'Wanderfalke',
    it: 'Falco pellegrino',
    ja: 'ハヤブサ',
    zh: '游隼',
    ko: '송골매',
    ru: 'Сапсан',
    hi: 'शाहीन',
    tr: 'Gökdoğan',
    id: 'Alap-alap kawah',
    pl: 'Sokół wędrowny',
    nl: 'Slechtvalk',
    ar: 'الشاهين',
    dato: {
      es: 'Es el animal más rápido del mundo: supera los 350 km/h en picado sobre sus presas.',
      en: 'The fastest animal alive: it tops 350 km/h when it stoops onto its prey.',
      pt: 'É o animal mais rápido do mundo: passa dos 350 km/h no mergulho sobre a presa.',
      fr: 'C’est l’animal le plus rapide du monde : il dépasse 350 km/h en piqué sur ses proies.',
      de: 'Das schnellste Tier der Welt: Im Sturzflug auf die Beute überschreitet er 350 km/h.',
      it: 'È l’animale più veloce del mondo: supera i 350 km/h in picchiata sulle prede.',
      ja: '世界でいちばん速い動物で、獲物めがけた急降下は時速350キロを超えます。',
      zh: '它是世界上最快的动物，俯冲扑向猎物时超过每小时350公里。',
      ko: '세상에서 가장 빠른 동물로, 먹이를 향해 급강하할 때 시속 350km를 넘겨요.',
      ru: 'Самое быстрое животное на свете: в пикировании на добычу разгоняется больше 350 км/ч.',
      hi: 'यह दुनिया का सबसे तेज़ जानवर है: शिकार पर झपट्टा मारते हुए 350 किमी/घंटा पार कर जाता है।',
      tr: 'Dünyanın en hızlı hayvanı: avının üstüne dalışta saatte 350 kilometreyi geçer.',
      id: 'Hewan tercepat di dunia: saat menukik ke arah mangsanya ia melewati 350 km/jam.',
      pl: 'Najszybsze zwierzę świata: w locie nurkowym na zdobycz przekracza 350 km/h.',
      nl: 'Het snelste dier ter wereld: in duikvlucht op zijn prooi haalt hij meer dan 350 km/u.',
      ar: 'أسرع حيوان في العالم: يتجاوز 350 كم/س وهو ينقضّ على فريسته.',
    },
  },
  {
    cientifico: 'Chelonia mydas',
    es: 'Tortuga verde',
    en: 'Green sea turtle',
    pt: 'Tartaruga-verde',
    fr: 'Tortue verte',
    de: 'Grüne Meeresschildkröte',
    it: 'Tartaruga verde',
    ja: 'アオウミガメ',
    zh: '绿海龟',
    ko: '푸른바다거북',
    ru: 'Зелёная черепаха',
    hi: 'हरा समुद्री कछुआ',
    tr: 'Yeşil deniz kaplumbağası',
    id: 'Penyu hijau',
    pl: 'Żółw zielony',
    nl: 'Soepschildpad',
    ar: 'اللجأة الخضراء',
    dato: {
      es: 'Vuelve a desovar a la misma playa donde nació décadas antes, guiándose por el campo magnético.',
      en: 'It returns to nest on the very beach where it hatched decades earlier, guided by magnetic fields.',
      pt: 'Volta a desovar na mesma praia onde nasceu décadas antes, guiando-se pelo campo magnético.',
      fr: 'Elle revient pondre sur la plage même où elle est née, guidée par le champ magnétique.',
      de: 'Sie legt ihre Eier an dem Strand ab, an dem sie Jahrzehnte zuvor schlüpfte, geführt vom Magnetfeld.',
      it: 'Torna a deporre sulla stessa spiaggia dove è nata decenni prima, guidata dal campo magnetico.',
      ja: '地磁気をたよりに、何十年も前に自分が生まれた砂浜へ産卵に戻ります。',
      zh: '它靠地磁场导航，回到几十年前自己出生的那片沙滩产卵。',
      ko: '지구 자기장을 길잡이 삼아, 수십 년 전 자기가 태어난 바로 그 해변으로 알을 낳으러 돌아와요.',
      ru: 'Она возвращается откладывать яйца на тот самый пляж, где вылупилась десятки лет назад, по магнитному полю.',
      hi: 'यह चुंबकीय क्षेत्र के सहारे उसी समुद्र तट पर अंडे देने लौटता है जहां दशकों पहले पैदा हुआ था।',
      tr: 'Manyetik alanı pusula gibi kullanıp onlarca yıl önce doğduğu kumsala yumurtlamaya döner.',
      id: 'Ia kembali bertelur ke pantai tempatnya menetas puluhan tahun sebelumnya, berpandu medan magnet bumi.',
      pl: 'Wraca składać jaja na tę samą plażę, na której wykluł się dekady wcześniej, kierując się polem magnetycznym.',
      nl: 'Ze keert terug om eieren te leggen op precies het strand waar ze decennia eerder uitkwam, geleid door het magneetveld.',
      ar: 'تعود لتضع بيضها على الشاطئ نفسه الذي فقست فيه قبل عقود، مهتديةً بالمجال المغناطيسي.',
    },
  },
  {
    cientifico: 'Myrmecophaga tridactyla',
    es: 'Oso hormiguero gigante',
    en: 'Giant anteater',
    pt: 'Tamanduá-bandeira',
    fr: 'Grand fourmilier',
    de: 'Großer Ameisenbär',
    it: 'Formichiere gigante',
    ja: 'オオアリクイ',
    zh: '大食蚁兽',
    ko: '큰개미핥기',
    ru: 'Гигантский муравьед',
    hi: 'विशाल चींटीखोर',
    tr: 'Dev karıncayiyen',
    id: 'Pemakan semut raksasa',
    pl: 'Mrówkojad wielki',
    nl: 'Reuzenmiereneter',
    ar: 'آكل النمل العملاق',
    dato: {
      es: 'No tiene dientes: su lengua de 60 cm entra y sale 150 veces por minuto en un hormiguero.',
      en: 'It has no teeth: its 60 cm tongue flicks in and out 150 times a minute inside an anthill.',
      pt: 'Não tem dentes: a língua de 60 cm entra e sai 150 vezes por minuto dentro do formigueiro.',
      fr: 'Il n’a pas de dents : sa langue de 60 cm entre et sort 150 fois par minute dans la fourmilière.',
      de: 'Er hat keine Zähne: Seine 60 cm lange Zunge schnellt 150-mal pro Minute in den Ameisenbau.',
      it: 'Non ha denti: la sua lingua di 60 cm entra ed esce 150 volte al minuto in un formicaio.',
      ja: '歯が一本もなく、60センチの舌が一分間に150回も蟻塚を出入りします。',
      zh: '它没有牙齿：60厘米长的舌头每分钟在蚁巢里进出150次。',
      ko: '이빨이 하나도 없고, 60cm 혀가 개미집을 1분에 150번 드나들어요.',
      ru: 'У него нет зубов: язык длиной 60 см ныряет в муравейник 150 раз в минуту.',
      hi: 'इसके दांत नहीं होते: 60 सेंटीमीटर लंबी जीभ बांबी में मिनट में 150 बार आती-जाती है।',
      tr: 'Hiç dişi yok: 60 santimlik dili bir karınca yuvasına dakikada 150 kez girip çıkar.',
      id: 'Ia tak bergigi: lidahnya yang 60 cm keluar-masuk sarang semut 150 kali per menit.',
      pl: 'Nie ma zębów: jego 60-centymetrowy język wsuwa się do mrowiska 150 razy na minutę.',
      nl: 'Hij heeft geen tanden: zijn tong van 60 cm gaat 150 keer per minuut een mierennest in en uit.',
      ar: 'لا أسنان له: لسانه البالغ 60 سنتيمترًا يدخل بيت النمل ويخرج منه 150 مرة في الدقيقة.',
    },
  },
  {
    cientifico: 'Vombatus ursinus',
    es: 'Wómbat',
    en: 'Common wombat',
    pt: 'Vombate',
    fr: 'Wombat commun',
    de: 'Nacktnasenwombat',
    it: 'Vombato comune',
    ja: 'ウォンバット',
    zh: '袋熊',
    ko: '웜뱃',
    ru: 'Вомбат',
    hi: 'वॉम्बैट',
    tr: 'Vombat',
    id: 'Wombat biasa',
    pl: 'Wombat tasmański',
    nl: 'Wombat',
    ar: 'الومبت',
    dato: {
      es: 'Es el único animal que hace excrementos cúbicos, y los usa para marcar el territorio sin que rueden.',
      en: 'The only animal that produces cube-shaped droppings, which mark territory without rolling away.',
      pt: 'É o único animal que faz fezes cúbicas, e as usa para marcar o território sem que rolem.',
      fr: 'Le seul animal à produire des crottes cubiques, qui marquent son territoire sans rouler.',
      de: 'Das einzige Tier mit würfelförmigem Kot, der sein Revier markiert, ohne wegzurollen.',
      it: 'È l’unico animale a produrre escrementi cubici, che marcano il territorio senza rotolare via.',
      ja: '立方体のフンをする唯一の動物で、転がらないので縄張りの目印になります。',
      zh: '它是唯一会拉出方块粪便的动物，用来标记地盘还不会滚走。',
      ko: '네모난 똥을 누는 유일한 동물이라, 굴러가지 않는 그 똥으로 영역을 표시해요.',
      ru: 'Единственное животное с кубическим помётом: он метит участок и не скатывается.',
      hi: 'यह इकलौता जानवर है जिसकी लीद घनाकार होती है, जो लुढ़के बिना इलाक़ा चिह्नित कर देती है।',
      tr: 'Küp şeklinde dışkı bırakan tek hayvan; böylece işaretleri yuvarlanmadan yerinde durur.',
      id: 'Satu-satunya hewan yang kotorannya berbentuk kubus, dipakai menandai wilayah agar tidak menggelinding.',
      pl: 'Jedyne zwierzę o sześciennych odchodach — znaczy nimi teren, a one się nie staczają.',
      nl: 'Het enige dier met kubusvormige keutels: daarmee markeert hij zijn terrein zonder dat ze wegrollen.',
      ar: 'الحيوان الوحيد الذي تخرج فضلاته مكعّبة، فيعلّم بها أرضه دون أن تتدحرج.',
    },
  },
  {
    cientifico: 'Lemur catta',
    es: 'Lémur de cola anillada',
    en: 'Ring-tailed lemur',
    pt: 'Lêmure-de-cauda-anelada',
    fr: 'Maki catta',
    de: 'Katta',
    it: 'Lemure catta',
    ja: 'ワオキツネザル',
    zh: '环尾狐猴',
    ko: '알락꼬리여우원숭이',
    ru: 'Кошачий лемур',
    hi: 'छल्लेदार पूंछ वाला लीमर',
    tr: 'Halka kuyruklu maki',
    id: 'Lemur ekor cincin',
    pl: 'Lemur katta',
    nl: 'Ringstaartmaki',
    ar: 'الليمور حلقي الذيل',
    dato: {
      es: 'Los machos libran "peleas apestosas": frotan la cola con su perfume y la agitan contra el rival.',
      en: 'Males hold "stink fights": they rub their tail with scent and waft it at their rival.',
      pt: 'Os machos travam "brigas fedorentas": esfregam o cheiro na cauda e a sacodem contra o rival.',
      fr: 'Les mâles se livrent à des "combats puants" : ils parfument leur queue et l’agitent vers le rival.',
      de: 'Die Männchen tragen "Stinkkämpfe" aus: Sie reiben Duft in den Schwanz und wedeln damit.',
      it: 'I maschi si sfidano a "battaglie puzzolenti": profumano la coda e la agitano contro il rivale.',
      ja: 'オスは「におい合戦」をします。しっぽに自分のにおいをこすりつけ、相手に振りかざすのです。',
      zh: '雄性会打“臭味仗”：把气味蹭到尾巴上，再朝对手挥舞。',
      ko: '수컷들은 "냄새 싸움"을 벌여요. 꼬리에 자기 냄새를 문질러 상대에게 흔들죠.',
      ru: 'Самцы устраивают «вонючие дуэли»: натирают хвост пахучим секретом и машут им в сторону соперника.',
      hi: 'नर "बदबू की लड़ाई" लड़ते हैं: वे अपनी गंध पूंछ पर रगड़कर उसे प्रतिद्वंद्वी की ओर लहराते हैं।',
      tr: 'Erkekler "kokulu düellolar" yapar: kuyruklarını kendi kokularına bulayıp rakibe doğru sallarlar.',
      id: 'Para jantan menggelar "duel bau": mereka melumuri ekor dengan aromanya lalu mengibaskannya ke lawan.',
      pl: 'Samce toczą "śmierdzące pojedynki": nacierają ogon własnym zapachem i machają nim rywalowi przed nosem.',
      nl: 'De mannetjes houden "stinkgevechten": ze wrijven hun geur in hun staart en zwaaien die naar de rivaal.',
      ar: 'يخوض الذكور "نزالات نتنة": يمسحون أذيالهم برائحتهم ثم يلوّحون بها في وجه الخصم.',
    },
  },
  {
    cientifico: 'Bubo scandiacus',
    es: 'Búho nival',
    en: 'Snowy owl',
    pt: 'Coruja-das-neves',
    fr: 'Harfang des neiges',
    de: 'Schnee-Eule',
    it: 'Civetta delle nevi',
    ja: 'シロフクロウ',
    zh: '雪鸮',
    ko: '흰올빼미',
    ru: 'Полярная сова',
    hi: 'बर्फ़ीला उल्लू',
    tr: 'Kar baykuşu',
    id: 'Burung hantu salju',
    pl: 'Puchacz śnieżny',
    nl: 'Sneeuwuil',
    ar: 'البومة الثلجية',
    dato: {
      es: 'Caza a plena luz del día ártico y oye un roedor moviéndose bajo medio metro de nieve.',
      en: 'It hunts in full Arctic daylight and hears a rodent moving under half a metre of snow.',
      pt: 'Caça em plena luz do dia ártico e ouve um roedor se mexendo sob meio metro de neve.',
      fr: 'Il chasse en plein jour arctique et entend un rongeur bouger sous un demi-mètre de neige.',
      de: 'Sie jagt im hellen arktischen Tag und hört ein Nagetier unter einem halben Meter Schnee.',
      it: 'Caccia in piena luce del giorno artico e sente un roditore muoversi sotto mezzo metro di neve.',
      ja: '明るい北極の昼に狩りをし、50センチの雪の下を動くネズミの音も聞き分けます。',
      zh: '它在北极的白昼里捕猎，能听见半米积雪下老鼠的动静。',
      ko: '환한 북극의 낮에 사냥하고, 눈 50cm 아래에서 움직이는 설치류 소리까지 들어요.',
      ru: 'Она охотится при ярком арктическом свете и слышит грызуна под полуметром снега.',
      hi: 'यह आर्कटिक के भरे उजाले में शिकार करता है और आधा मीटर बर्फ़ के नीचे हिलते चूहे को सुन लेता है।',
      tr: 'Kutbun apaydınlık gününde avlanır ve yarım metre karın altında kımıldayan bir kemirgeni duyar.',
      id: 'Ia berburu di terang benderang siang Arktik dan mendengar tikus bergerak di bawah setengah meter salju.',
      pl: 'Poluje w pełnym świetle arktycznego dnia i słyszy gryzonia poruszającego się pod półmetrową warstwą śniegu.',
      nl: 'Hij jaagt in het volle licht van de poolzomer en hoort een knaagdier bewegen onder een halve meter sneeuw.',
      ar: 'يصطاد في وضح نهار القطب، ويسمع قارضًا يتحرك تحت نصف متر من الثلج.',
    },
  },
  {
    cientifico: 'Giraffa camelopardalis',
    es: 'Jirafa',
    en: 'Giraffe',
    pt: 'Girafa',
    fr: 'Girafe',
    de: 'Giraffe',
    it: 'Giraffa',
    ja: 'キリン',
    zh: '长颈鹿',
    ko: '기린',
    ru: 'Жираф',
    hi: 'जिराफ़',
    tr: 'Zürafa',
    id: 'Jerapah',
    pl: 'Żyrafa',
    nl: 'Giraffe',
    ar: 'الزرافة',
    dato: {
      es: 'Su cuello de dos metros tiene solo siete vértebras, las mismas que el de un ratón.',
      en: 'Its two-metre neck holds just seven vertebrae, the same number as a mouse’s.',
      pt: 'Seu pescoço de dois metros tem apenas sete vértebras, as mesmas que o de um rato.',
      fr: 'Son cou de deux mètres ne compte que sept vertèbres, autant que celui d’une souris.',
      de: 'Ihr zwei Meter langer Hals hat nur sieben Wirbel, genauso viele wie der einer Maus.',
      it: 'Il suo collo di due metri ha solo sette vertebre, le stesse di quello di un topo.',
      ja: '二メートルの首にある骨は七つだけ。ネズミの首と同じ数です。',
      zh: '两米长的脖子里只有七块颈椎，和老鼠一样多。',
      ko: '2미터짜리 목에 목뼈는 일곱 개뿐, 쥐와 똑같아요.',
      ru: 'В её двухметровой шее всего семь позвонков — столько же, сколько у мыши.',
      hi: 'इसकी दो मीटर लंबी गर्दन में सिर्फ़ सात कशेरुकाएं होती हैं, उतनी ही जितनी चूहे की गर्दन में।',
      tr: 'İki metrelik boynunda yalnızca yedi omur var; farenin boynundakiyle aynı sayıda.',
      id: 'Lehernya yang dua meter hanya punya tujuh ruas tulang, sama banyaknya dengan leher tikus.',
      pl: 'W jej dwumetrowej szyi jest tylko siedem kręgów — dokładnie tyle, co u myszy.',
      nl: 'In haar nek van twee meter zitten maar zeven wervels, net zoveel als in die van een muis.',
      ar: 'في عنقها الذي يبلغ مترين سبع فقرات فقط، تمامًا كعنق الفأر.',
    },
  },
  {
    cientifico: 'Hydrochoerus hydrochaeris',
    es: 'Carpincho',
    en: 'Capybara',
    pt: 'Capivara',
    fr: 'Capybara',
    de: 'Wasserschwein',
    it: 'Capibara',
    ja: 'カピバラ',
    zh: '水豚',
    ko: '카피바라',
    ru: 'Капибара',
    hi: 'कैपिबारा',
    tr: 'Kapibara',
    id: 'Kapibara',
    pl: 'Kapibara',
    nl: 'Capibara',
    ar: 'خنزير الماء',
    dato: {
      es: 'El roedor más grande del mundo: pasta como un caballo y duerme dentro del agua.',
      en: 'The world’s largest rodent: it grazes like a horse and naps in the water.',
      pt: 'O maior roedor do mundo: pasta como um cavalo e cochila dentro da água.',
      fr: 'Le plus grand rongeur du monde : il broute comme un cheval et fait la sieste dans l’eau.',
      de: 'Das größte Nagetier der Welt: Es grast wie ein Pferd und döst im Wasser.',
      it: 'Il roditore più grande del mondo: bruca come un cavallo e sonnecchia in acqua.',
      ja: '世界最大のげっ歯類で、馬のように草を食み、水につかったまま眠ります。',
      zh: '世界上最大的啮齿动物：像马一样吃草，还泡在水里打盹。',
      ko: '세계에서 가장 큰 설치류로, 말처럼 풀을 뜯고 물속에서 잠을 자요.',
      ru: 'Самый крупный грызун в мире: пасётся, как лошадь, и дремлет прямо в воде.',
      hi: 'दुनिया का सबसे बड़ा कुतरने वाला जानवर: घोड़े की तरह घास चरता है और पानी में ही सो जाता है।',
      tr: 'Dünyanın en büyük kemirgeni: at gibi otlar ve suyun içinde uyur.',
      id: 'Hewan pengerat terbesar di dunia: ia merumput seperti kuda dan tidur di dalam air.',
      pl: 'Największy gryzoń świata: pasie się jak koń i śpi zanurzony w wodzie.',
      nl: 'Het grootste knaagdier ter wereld: het graast als een paard en slaapt in het water.',
      ar: 'أكبر القوارض في العالم: يرعى كالحصان وينام داخل الماء.',
    },
  },
  {
    cientifico: 'Ornithorhynchus anatinus',
    es: 'Ornitorrinco',
    en: 'Platypus',
    pt: 'Ornitorrinco',
    fr: 'Ornithorynque',
    de: 'Schnabeltier',
    it: 'Ornitorinco',
    ja: 'カモノハシ',
    zh: '鸭嘴兽',
    ko: '오리너구리',
    ru: 'Утконос',
    hi: 'प्लैटिपस',
    tr: 'Ornitorenk',
    id: 'Platipus',
    pl: 'Dziobak',
    nl: 'Vogelbekdier',
    ar: 'خلد الماء',
    dato: {
      es: 'Un mamífero que pone huevos, detecta electricidad con el pico y tiene veneno en los tobillos.',
      en: 'A mammal that lays eggs, senses electricity with its bill and carries venom in its ankles.',
      pt: 'Um mamífero que põe ovos, detecta eletricidade com o bico e tem veneno nos tornozelos.',
      fr: 'Un mammifère qui pond des œufs, détecte l’électricité avec son bec et a du venin aux chevilles.',
      de: 'Ein Säugetier, das Eier legt, mit dem Schnabel Strom spürt und Gift an den Fersen trägt.',
      it: 'Un mammifero che depone uova, percepisce l’elettricità col becco e ha veleno alle caviglie.',
      ja: '卵を産む哺乳類で、くちばしで電気を感じ、後ろ足には毒を持っています。',
      zh: '一种会下蛋的哺乳动物，用嘴喙感知电流，脚踝上还带着毒刺。',
      ko: '알을 낳는 포유류로, 부리로 전기를 느끼고 발목에는 독이 있어요.',
      ru: 'Млекопитающее, которое откладывает яйца, чует электричество клювом и носит яд на шпорах.',
      hi: 'यह अंडे देने वाला स्तनपायी है, चोंच से बिजली भांपता है और टख़नों में ज़हर रखता है।',
      tr: 'Yumurtlayan bir memeli: gagasıyla elektrik sezer ve bileklerinde zehir taşır.',
      id: 'Mamalia yang bertelur, mendeteksi listrik lewat paruhnya, dan menyimpan bisa di pergelangan kakinya.',
      pl: 'Ssak, który składa jaja, wyczuwa dziobem prąd i ma jad w kostkach tylnych łap.',
      nl: 'Een zoogdier dat eieren legt, met zijn bek elektriciteit opspoort en gif in zijn enkels draagt.',
      ar: 'ثديي يبيض، ويستشعر الكهرباء بمنقاره، ويحمل سمًّا في كاحليه.',
    },
  },
  {
    cientifico: 'Rhincodon typus',
    es: 'Tiburón ballena',
    en: 'Whale shark',
    pt: 'Tubarão-baleia',
    fr: 'Requin-baleine',
    de: 'Walhai',
    it: 'Squalo balena',
    ja: 'ジンベエザメ',
    zh: '鲸鲨',
    ko: '고래상어',
    ru: 'Китовая акула',
    hi: 'व्हेल शार्क',
    tr: 'Balina köpek balığı',
    id: 'Hiu paus',
    pl: 'Rekin wielorybi',
    nl: 'Walvishaai',
    ar: 'القرش الحوتي',
    dato: {
      es: 'El pez más grande del planeta filtra plancton con una boca de metro y medio y no muerde.',
      en: 'The largest fish alive filters plankton through a metre-and-a-half mouth and never bites.',
      pt: 'O maior peixe do planeta filtra plâncton com uma boca de metro e meio e não morde.',
      fr: 'Le plus grand poisson filtre le plancton avec une bouche d’un mètre cinquante et ne mord pas.',
      de: 'Der größte Fisch der Erde filtert Plankton durch ein anderthalb Meter breites Maul und beißt nie.',
      it: 'Il pesce più grande del pianeta filtra plancton con una bocca di un metro e mezzo e non morde.',
      ja: '地球でいちばん大きな魚は、1.5メートルの口でプランクトンを濾しとり、噛みつきません。',
      zh: '地球上最大的鱼用一米半宽的嘴滤食浮游生物，从不咬人。',
      ko: '지구에서 가장 큰 물고기는 1.5미터 입으로 플랑크톤을 걸러 먹고, 물지 않아요.',
      ru: 'Самая большая рыба планеты цедит планктон полутораметровым ртом и никогда не кусает.',
      hi: 'धरती की सबसे बड़ी मछली डेढ़ मीटर चौड़े मुंह से प्लवक छानती है और काटती नहीं।',
      tr: 'Gezegenin en büyük balığı, bir buçuk metrelik ağzıyla planktonu süzer ve ısırmaz.',
      id: 'Ikan terbesar di planet ini menyaring plankton dengan mulut selebar satu setengah meter dan tidak menggigit.',
      pl: 'Największa ryba na planecie odcedza plankton pyskiem szerokim na półtora metra i nie gryzie.',
      nl: 'De grootste vis op aarde zeeft plankton met een bek van anderhalve meter en bijt niet.',
      ar: 'أكبر سمكة على الكوكب ترشّح العوالق بفمٍ عرضه متر ونصف، ولا تعضّ.',
    },
  },
  {
    cientifico: 'Panthera leo',
    es: 'León',
    en: 'Lion',
    pt: 'Leão',
    fr: 'Lion',
    de: 'Löwe',
    it: 'Leone',
    ja: 'ライオン',
    zh: '狮子',
    ko: '사자',
    ru: 'Лев',
    hi: 'शेर',
    tr: 'Aslan',
    id: 'Singa',
    pl: 'Lew',
    nl: 'Leeuw',
    ar: 'الأسد',
    dato: {
      es: 'El único felino que vive en grupo: cazan las hembras y su rugido se oye a ocho kilómetros.',
      en: 'The only cat that lives in groups: the females hunt, and its roar carries eight kilometres.',
      pt: 'O único felino que vive em grupo: quem caça são as fêmeas e o rugido se ouve a oito quilômetros.',
      fr: 'Le seul félin qui vit en groupe : les femelles chassent et son rugissement porte à huit kilomètres.',
      de: 'Die einzige Katze, die in Gruppen lebt: Die Weibchen jagen, sein Brüllen trägt acht Kilometer.',
      it: 'L’unico felino che vive in gruppo: cacciano le femmine e il suo ruggito si sente a otto chilometri.',
      ja: '群れで暮らす唯一のネコ科で、狩りをするのはメス。吠え声は八キロ先まで届きます。',
      zh: '唯一群居的猫科动物：狩猎的是母狮，吼声能传到八公里外。',
      ko: '무리를 이루는 유일한 고양잇과로, 사냥은 암컷이 하고 포효는 8km 밖까지 들려요.',
      ru: 'Единственная кошка, которая живёт прайдом: охотятся львицы, а рык слышен за восемь километров.',
      hi: 'बिल्ली-कुल का इकलौता जानवर जो झुंड में रहता है: शिकार मादाएं करती हैं और दहाड़ आठ किलोमीटर दूर तक जाती है।',
      tr: 'Sürü hâlinde yaşayan tek kedigil: avı dişiler yapar, kükremesi sekiz kilometreden duyulur.',
      id: 'Satu-satunya kucing besar yang hidup berkelompok: betinanya yang berburu, dan aumannya terdengar sampai delapan kilometer.',
      pl: 'Jedyny kot żyjący w grupie: polują samice, a ryk słychać na osiem kilometrów.',
      nl: 'De enige katachtige die in groep leeft: de vrouwtjes jagen en zijn gebrul draagt acht kilometer ver.',
      ar: 'السنّوري الوحيد الذي يعيش في جماعة: الإناث هنّ من يصطدن، وزئيره يُسمع من ثمانية كيلومترات.',
    },
  },
  {
    cientifico: 'Canis lupus',
    es: 'Lobo',
    en: 'Wolf',
    pt: 'Lobo-cinzento',
    fr: 'Loup gris',
    de: 'Wolf',
    it: 'Lupo',
    ja: 'オオカミ',
    zh: '灰狼',
    ko: '늑대',
    ru: 'Волк',
    hi: 'भेड़िया',
    tr: 'Kurt',
    id: 'Serigala',
    pl: 'Wilk',
    nl: 'Wolf',
    ar: 'الذئب الرمادي',
    dato: {
      es: 'Aúlla para reunir a la manada y reconoce a cada miembro por la voz a kilómetros de distancia.',
      en: 'It howls to gather the pack and recognises each member by voice from kilometres away.',
      pt: 'Uiva para reunir a alcateia e reconhece cada membro pela voz a quilômetros de distância.',
      fr: 'Il hurle pour rassembler la meute et reconnaît chaque membre à la voix, à des kilomètres.',
      de: 'Er heult, um das Rudel zu sammeln, und erkennt jedes Mitglied kilometerweit an der Stimme.',
      it: 'Ulula per radunare il branco e riconosce ogni membro dalla voce a chilometri di distanza.',
      ja: '遠吠えで群れを呼び集め、何キロ離れていても一頭ずつ声で聞き分けます。',
      zh: '它用嚎叫召集狼群，隔着好几公里也能听声辨认每一个成员。',
      ko: '울음으로 무리를 불러 모으고, 몇 킬로미터 떨어져도 목소리로 서로를 알아봐요.',
      ru: 'Он воет, чтобы собрать стаю, и за километры узнаёт каждого сородича по голосу.',
      hi: 'यह हुंकार भरकर झुंड को इकट्ठा करता है और किलोमीटरों दूर से हर साथी को आवाज़ से पहचान लेता है।',
      tr: 'Sürüyü toplamak için ulur ve her üyeyi kilometrelerce öteden sesinden tanır.',
      id: 'Ia melolong untuk mengumpulkan kawanan dan mengenali tiap anggotanya dari suara sejauh berkilo-kilometer.',
      pl: 'Wyje, żeby zebrać watahę, i rozpoznaje każdego jej członka po głosie z odległości kilometrów.',
      nl: 'Hij huilt om de roedel te verzamelen en herkent elk lid kilometers ver aan de stem.',
      ar: 'يعوي ليجمع القطيع، ويميّز كل فرد فيه بصوته من على بُعد كيلومترات.',
    },
  },
  {
    cientifico: 'Pan troglodytes',
    es: 'Chimpancé',
    en: 'Chimpanzee',
    pt: 'Chimpanzé',
    fr: 'Chimpanzé',
    de: 'Schimpanse',
    it: 'Scimpanzé',
    ja: 'チンパンジー',
    zh: '黑猩猩',
    ko: '침팬지',
    ru: 'Шимпанзе',
    hi: 'चिंपैंज़ी',
    tr: 'Şempanze',
    id: 'Simpanse',
    pl: 'Szympans',
    nl: 'Chimpansee',
    ar: 'الشمبانزي',
    dato: {
      es: 'Fabrica herramientas, se cura con plantas y comparte con nosotros casi el 99 % del ADN.',
      en: 'It makes tools, self-medicates with plants and shares almost 99% of our DNA.',
      pt: 'Fabrica ferramentas, trata-se com plantas e compartilha conosco quase 99 % do DNA.',
      fr: 'Il fabrique des outils, se soigne avec des plantes et partage près de 99 % de notre ADN.',
      de: 'Er baut Werkzeuge, kuriert sich mit Pflanzen und teilt fast 99 % seiner DNA mit uns.',
      it: 'Fabbrica utensili, si cura con le piante e condivide con noi quasi il 99 % del DNA.',
      ja: '道具をつくり、植物で手当てをし、DNAの99パーセント近くを人と共有しています。',
      zh: '它会制作工具、用植物自我医治，和我们共享将近99%的DNA。',
      ko: '도구를 만들고 식물로 스스로를 치료하며, 우리와 DNA의 99%가량을 공유해요.',
      ru: 'Он мастерит орудия, лечится растениями и делит с нами почти 99 % ДНК.',
      hi: 'यह औज़ार बनाता है, पौधों से अपना इलाज करता है और हमारे साथ लगभग 99 % डीएनए साझा करता है।',
      tr: 'Alet yapar, bitkilerle kendini iyileştirir ve DNA’sının neredeyse %99’unu bizimle paylaşır.',
      id: 'Ia membuat perkakas, mengobati diri dengan tumbuhan, dan berbagi hampir 99 % DNA dengan kita.',
      pl: 'Wytwarza narzędzia, leczy się roślinami i dzieli z nami niemal 99 % DNA.',
      nl: 'Hij maakt gereedschap, geneest zichzelf met planten en deelt bijna 99 % van zijn DNA met ons.',
      ar: 'يصنع أدوات، ويداوي نفسه بالنباتات، ويشاركنا نحو 99 % من حمضه النووي.',
    },
  },
  {
    cientifico: 'Macropus rufus',
    es: 'Canguro rojo',
    en: 'Red kangaroo',
    pt: 'Canguru-vermelho',
    fr: 'Kangourou roux',
    de: 'Rotes Riesenkänguru',
    it: 'Canguro rosso',
    ja: 'アカカンガルー',
    zh: '红大袋鼠',
    ko: '붉은캥거루',
    ru: 'Большой рыжий кенгуру',
    hi: 'लाल कंगारू',
    tr: 'Kızıl kanguru',
    id: 'Kanguru merah',
    pl: 'Kangur rudy',
    nl: 'Rode reuzenkangoeroe',
    ar: 'الكنغر الأحمر',
    dato: {
      es: 'Salta nueve metros de un brinco y usa la cola como quinta pata para caminar despacio.',
      en: 'It leaps nine metres in one bound and uses its tail as a fifth leg when walking slowly.',
      pt: 'Salta nove metros de uma vez e usa a cauda como quinta pata para andar devagar.',
      fr: 'Il saute neuf mètres d’un bond et se sert de sa queue comme cinquième patte pour marcher.',
      de: 'Es springt neun Meter weit und nutzt den Schwanz als fünftes Bein, wenn es langsam geht.',
      it: 'Salta nove metri con un balzo e usa la coda come quinta zampa per camminare piano.',
      ja: '一跳びで九メートル進み、ゆっくり歩くときはしっぽを五本目の脚にします。',
      zh: '它一跃就是九米，慢慢走路时把尾巴当作第五条腿。',
      ko: '한 번에 9미터를 뛰고, 천천히 걸을 땐 꼬리를 다섯 번째 다리처럼 써요.',
      ru: 'Он прыгает на девять метров и, когда идёт шагом, опирается на хвост как на пятую ногу.',
      hi: 'यह एक ही छलांग में नौ मीटर कूदता है और धीरे चलते वक़्त पूंछ को पांचवें पैर की तरह इस्तेमाल करता है।',
      tr: 'Tek sıçrayışta dokuz metre gider ve ağır yürürken kuyruğunu beşinci ayak gibi kullanır.',
      id: 'Sekali lompat ia melesat sembilan meter, dan saat berjalan pelan ekornya jadi kaki kelima.',
      pl: 'Jednym susem pokonuje dziewięć metrów, a idąc wolno, używa ogona jak piątej nogi.',
      nl: 'Hij springt negen meter in één sprong en gebruikt zijn staart als vijfde poot om langzaam te lopen.',
      ar: 'يقفز تسعة أمتار في وثبة واحدة، ويتّخذ ذيله قائمةً خامسة حين يمشي متمهّلًا.',
    },
  },
  {
    cientifico: 'Iguana iguana',
    es: 'Iguana verde',
    en: 'Green iguana',
    pt: 'Iguana-verde',
    fr: 'Iguane vert',
    de: 'Grüner Leguan',
    it: 'Iguana verde',
    ja: 'グリーンイグアナ',
    zh: '绿鬣蜥',
    ko: '그린이구아나',
    ru: 'Зелёная игуана',
    hi: 'हरा इगुआना',
    tr: 'Yeşil iguana',
    id: 'Iguana hijau',
    pl: 'Legwan zielony',
    nl: 'Groene leguaan',
    ar: 'الإغوانة الخضراء',
    dato: {
      es: 'Tiene un "tercer ojo" en la cabeza que no ve formas, pero detecta sombras desde arriba.',
      en: 'It has a "third eye" on its head that sees no shapes but detects shadows from above.',
      pt: 'Tem um "terceiro olho" na cabeça que não vê formas, mas detecta sombras vindas de cima.',
      fr: 'Il a un "troisième œil" sur la tête : il ne voit pas les formes, mais repère les ombres d’en haut.',
      de: 'Er hat ein "drittes Auge" am Kopf: Es sieht keine Formen, erkennt aber Schatten von oben.',
      it: 'Ha un "terzo occhio" sulla testa che non vede le forme, ma percepisce le ombre dall’alto.',
      ja: '頭のてっぺんに「第三の目」があり、形は見えませんが上から来る影を感じ取ります。',
      zh: '它头顶有一只“第三只眼”，看不清形状，却能察觉从上方掠过的阴影。',
      ko: '머리에 "제3의 눈"이 있어서, 형태는 못 보지만 위에서 오는 그림자는 알아채요.',
      ru: 'На темени у неё «третий глаз»: форм он не различает, но замечает тень сверху.',
      hi: 'इसके सिर पर एक "तीसरी आंख" होती है जो आकार तो नहीं देखती, पर ऊपर से आती परछाईं भांप लेती है।',
      tr: 'Başında bir "üçüncü göz" taşır: biçimleri görmez ama yukarıdan gelen gölgeyi fark eder.',
      id: 'Di kepalanya ada "mata ketiga" yang tak melihat bentuk, tapi menangkap bayangan dari atas.',
      pl: 'Ma na głowie "trzecie oko": nie widzi nim kształtów, ale wychwytuje cienie z góry.',
      nl: 'Hij heeft een "derde oog" op zijn kop dat geen vormen ziet, maar wel schaduwen van boven opmerkt.',
      ar: 'في رأسها "عين ثالثة" لا ترى الأشكال، لكنها تلتقط الظلال القادمة من الأعلى.',
    },
  },
  {
    cientifico: 'Dendrobates tinctorius',
    es: 'Rana dardo',
    en: 'Dyeing poison dart frog',
    pt: 'Rã-de-flecha-envenenada',
    fr: 'Dendrobate teinturier',
    de: 'Färberfrosch',
    it: 'Rana freccia',
    ja: 'アイゾメヤドクガエル',
    zh: '染色箭毒蛙',
    ko: '염색독화살개구리',
    ru: 'Красящий древолаз',
    hi: 'ज़हरीला डार्ट मेंढक',
    tr: 'Zehirli ok kurbağası',
    id: 'Katak panah beracun',
    pl: 'Drzewołaz niebieski',
    nl: 'Pijlgifkikker',
    ar: 'ضفدع السهم السام',
    dato: {
      es: 'Su veneno viene de las hormigas que come: criada en cautiverio es completamente inofensiva.',
      en: 'Its poison comes from the ants it eats: raised in captivity it is completely harmless.',
      pt: 'O veneno vem das formigas que ela come: criada em cativeiro é completamente inofensiva.',
      fr: 'Son poison vient des fourmis qu’elle mange : élevée en captivité, elle est inoffensive.',
      de: 'Ihr Gift stammt von den Ameisen, die sie frisst: In Gefangenschaft ist sie völlig harmlos.',
      it: 'Il suo veleno viene dalle formiche che mangia: allevata in cattività è del tutto innocua.',
      ja: '毒は食べるアリに由来するので、飼育下で育つとまったく無毒です。',
      zh: '它的毒来自吃下的蚂蚁：人工饲养长大的完全无害。',
      ko: '독은 먹이인 개미에서 오기 때문에, 사육장에서 자라면 전혀 해가 없어요.',
      ru: 'Яд достаётся ей от съеденных муравьёв: выращенная в неволе, она совершенно безобидна.',
      hi: 'इसका ज़हर उन चींटियों से आता है जो यह खाता है: क़ैद में पला हो तो बिलकुल बेज़रर होता है।',
      tr: 'Zehri yediği karıncalardan gelir: esarette büyütülürse tamamen zararsızdır.',
      id: 'Racunnya berasal dari semut yang ia makan: kalau dibesarkan di penangkaran, ia sama sekali tak berbahaya.',
      pl: 'Truciznę bierze z mrówek, które zjada: hodowany w niewoli jest zupełnie nieszkodliwy.',
      nl: 'Zijn gif komt van de mieren die hij eet: in gevangenschap gekweekt is hij volstrekt ongevaarlijk.',
      ar: 'سمّه يأتي من النمل الذي يأكله: فإن رُبّي في الأسر كان غير مؤذٍ البتّة.',
    },
  },
  {
    cientifico: 'Architeuthis',
    es: 'Calamar gigante',
    en: 'Giant squid',
    pt: 'Lula-gigante',
    fr: 'Calmar géant',
    de: 'Riesenkalmar',
    it: 'Calamaro gigante',
    ja: 'ダイオウイカ',
    zh: '大王乌贼',
    ko: '대왕오징어',
    ru: 'Гигантский кальмар',
    hi: 'विशाल स्क्विड',
    tr: 'Dev kalamar',
    id: 'Cumi-cumi raksasa',
    pl: 'Kałamarnica olbrzymia',
    nl: 'Reuzeninktvis',
    ar: 'السبيدج العملاق',
    dato: {
      es: 'Tiene el ojo más grande del reino animal, del tamaño de un plato, y no se fotografió vivo hasta 2004.',
      en: 'It has the largest eye in the animal kingdom, plate-sized, and was not photographed alive until 2004.',
      pt: 'Tem o maior olho do reino animal, do tamanho de um prato, e só foi fotografada viva em 2004.',
      fr: 'Il a le plus grand œil du règne animal, grand comme une assiette, et fut photographié vivant en 2004.',
      de: 'Er hat das größte Auge des Tierreichs, tellergroß, und wurde erst 2004 lebend fotografiert.',
      it: 'Ha l’occhio più grande del regno animale, grande come un piatto, e fu fotografato vivo nel 2004.',
      ja: '動物界でいちばん大きな、皿ほどの目を持ち、生きた姿が撮影されたのは2004年でした。',
      zh: '它有动物界最大的眼睛，像盘子那么大，直到2004年才被拍到活体。',
      ko: '동물계에서 가장 큰, 접시만 한 눈을 가졌고 살아 있는 모습은 2004년에야 찍혔어요.',
      ru: 'У него самый большой глаз в животном мире, размером с тарелку, а живым его сняли лишь в 2004 году.',
      hi: 'इसकी आंख जानवरों में सबसे बड़ी, तश्तरी जितनी होती है, और ज़िंदा यह पहली बार 2004 में कैमरे में आया।',
      tr: 'Hayvanlar âleminin en büyük gözü ondadır, bir tabak kadar; canlı hâli ilk kez 2004’te fotoğraflandı.',
      id: 'Matanya terbesar di dunia hewan, sebesar piring, dan baru pada 2004 ia terpotret hidup-hidup.',
      pl: 'Ma największe oko w królestwie zwierząt, wielkości talerza, a żywa została sfotografowana dopiero w 2004 roku.',
      nl: 'Hij heeft het grootste oog van het dierenrijk, zo groot als een bord, en werd pas in 2004 levend gefotografeerd.',
      ar: 'له أكبر عين في مملكة الحيوان، بحجم الطبق، ولم يُصوَّر حيًّا حتى عام 2004.',
    },
  },
  {
    cientifico: 'Amphiprion ocellaris',
    es: 'Pez payaso',
    en: 'Ocellaris clownfish',
    pt: 'Peixe-palhaço',
    fr: 'Poisson-clown à trois bandes',
    de: 'Falscher Clownfisch',
    it: 'Pesce pagliaccio',
    ja: 'カクレクマノミ',
    zh: '眼斑小丑鱼',
    ko: '흰동가리',
    ru: 'Рыба-клоун',
    hi: 'क्लाउनफ़िश',
    tr: 'Palyaço balığı',
    id: 'Ikan badut',
    pl: 'Błazenek',
    nl: 'Clownvis',
    ar: 'سمكة المهرج',
    dato: {
      es: 'Vive inmune entre los tentáculos de una anémona y todos nacen machos: el dominante se vuelve hembra.',
      en: 'It lives immune among anemone tentacles, and all are born male: the dominant one turns female.',
      pt: 'Vive imune entre os tentáculos de uma anêmona e todos nascem machos: o dominante vira fêmea.',
      fr: 'Il vit immunisé entre les tentacules d’une anémone, et tous naissent mâles : le chef devient femelle.',
      de: 'Er lebt immun zwischen den Tentakeln einer Anemone, und alle sind erst männlich: Der Chef wird weiblich.',
      it: 'Vive immune tra i tentacoli di un’anemone e nascono tutti maschi: il dominante diventa femmina.',
      ja: 'イソギンチャクの触手の中で刺されずに暮らし、みなオスとして生まれ、いちばん強い個体がメスになります。',
      zh: '它在海葵的触手间安然无恙，而且全都生为雄性：最强的那条会变成雌性。',
      ko: '말미잘 촉수 사이에서 쏘이지 않고 살고, 모두 수컷으로 태어나 우두머리가 암컷이 돼요.',
      ru: 'Он живёт неуязвимым среди щупалец актинии, и все рождаются самцами: главный превращается в самку.',
      hi: 'यह एनीमोन के डंकों के बीच बेअसर रहकर जीती है और सब नर पैदा होते हैं: उनमें दबंग मादा बन जाता है।',
      tr: 'Bir denizşakayığının dokunaçları arasında bağışık yaşar; hepsi erkek doğar, baskın olan dişiye döner.',
      id: 'Ia hidup kebal di antara tentakel anemon, dan semuanya lahir jantan: yang dominan berubah jadi betina.',
      pl: 'Żyje bezpiecznie wśród parzydełek ukwiała; wszystkie rodzą się samcami, a dominujący zmienia się w samicę.',
      nl: 'Hij leeft immuun tussen de tentakels van een anemoon en ze worden allemaal als mannetje geboren: de dominante wordt vrouwtje.',
      ar: 'تعيش محصّنة بين لوامس شقائق البحر، وتولد كلها ذكورًا: ثم يتحوّل المهيمن إلى أنثى.',
    },
  },
  {
    cientifico: 'Struthio camelus',
    es: 'Avestruz',
    en: 'Common ostrich',
    pt: 'Avestruz',
    fr: 'Autruche d’Afrique',
    de: 'Afrikanischer Strauß',
    it: 'Struzzo',
    ja: 'ダチョウ',
    zh: '鸵鸟',
    ko: '타조',
    ru: 'Страус',
    hi: 'शुतुरमुर्ग',
    tr: 'Devekuşu',
    id: 'Burung unta',
    pl: 'Struś',
    nl: 'Struisvogel',
    ar: 'النعامة',
    dato: {
      es: 'El ave más grande no vuela, pero corre a 70 km/h y su ojo es mayor que su cerebro.',
      en: 'The largest bird cannot fly, but runs at 70 km/h, and its eye is bigger than its brain.',
      pt: 'A maior ave não voa, mas corre a 70 km/h e tem o olho maior que o cérebro.',
      fr: 'Le plus grand oiseau ne vole pas, mais court à 70 km/h et son œil est plus gros que son cerveau.',
      de: 'Der größte Vogel fliegt nicht, rennt aber 70 km/h, und sein Auge ist größer als sein Gehirn.',
      it: 'L’uccello più grande non vola, ma corre a 70 km/h e ha l’occhio più grande del cervello.',
      ja: 'いちばん大きな鳥は飛べませんが、時速70キロで走り、目は脳より大きいのです。',
      zh: '最大的鸟不会飞，却能以每小时70公里奔跑，眼睛比大脑还大。',
      ko: '가장 큰 새는 날지 못하지만 시속 70km로 달리고, 눈이 뇌보다 커요.',
      ru: 'Самая крупная птица не летает, зато бегает со скоростью 70 км/ч, а глаз у неё больше мозга.',
      hi: 'सबसे बड़ा पक्षी उड़ता नहीं, पर 70 किमी/घंटा दौड़ता है और इसकी आंख दिमाग़ से बड़ी होती है।',
      tr: 'En büyük kuş uçamaz ama saatte 70 kilometre koşar ve gözü beyninden büyüktür.',
      id: 'Burung terbesar ini tak bisa terbang, tapi berlari 70 km/jam, dan matanya lebih besar daripada otaknya.',
      pl: 'Największy ptak nie lata, ale biega 70 km/h, a jego oko jest większe niż mózg.',
      nl: 'De grootste vogel vliegt niet, maar rent 70 km/u en zijn oog is groter dan zijn hersenen.',
      ar: 'أكبر الطيور لا يطير، لكنه يعدو 70 كم/س، وعينه أكبر من دماغه.',
    },
  },
  {
    cientifico: 'Cervus elaphus',
    es: 'Ciervo rojo',
    en: 'Red deer',
    pt: 'Veado-vermelho',
    fr: 'Cerf élaphe',
    de: 'Rothirsch',
    it: 'Cervo nobile',
    ja: 'アカシカ',
    zh: '马鹿',
    ko: '붉은사슴',
    ru: 'Благородный олень',
    hi: 'लाल हिरन',
    tr: 'Kızıl geyik',
    id: 'Rusa merah',
    pl: 'Jeleń szlachetny',
    nl: 'Edelhert',
    ar: 'الأيل الأحمر',
    dato: {
      es: 'Renueva su cornamenta cada año: es el tejido de crecimiento más rápido de los mamíferos.',
      en: 'It regrows its antlers every year, the fastest-growing tissue of any mammal.',
      pt: 'Renova a galhada todo ano: é o tecido de crescimento mais rápido entre os mamíferos.',
      fr: 'Il refait ses bois chaque année : le tissu à la croissance la plus rapide des mammifères.',
      de: 'Er wirft sein Geweih jedes Jahr neu: das am schnellsten wachsende Gewebe aller Säugetiere.',
      it: 'Rifà i palchi ogni anno: è il tessuto a crescita più rapida di tutti i mammiferi.',
      ja: '角は毎年生えかわり、哺乳類でもっとも速く育つ組織です。',
      zh: '它每年重新长出鹿角，那是哺乳动物里生长最快的组织。',
      ko: '해마다 뿔을 새로 기르는데, 포유류 중 가장 빨리 자라는 조직이에요.',
      ru: 'Он каждый год меняет рога — это самая быстрорастущая ткань у млекопитающих.',
      hi: 'यह हर साल अपने सींग नए उगाता है: स्तनपायियों में सबसे तेज़ बढ़ने वाला ऊतक यही है।',
      tr: 'Boynuzlarını her yıl yeniler: memelilerde en hızlı büyüyen doku budur.',
      id: 'Ia menumbuhkan rangga baru tiap tahun: jaringan tercepat tumbuh di antara semua mamalia.',
      pl: 'Co roku zrzuca i odbudowuje poroże — to najszybciej rosnąca tkanka wśród ssaków.',
      nl: 'Hij vernieuwt zijn gewei elk jaar: het snelst groeiende weefsel van alle zoogdieren.',
      ar: 'يجدّد قرونه كل عام: وهي أسرع نسيج نموًّا بين الثدييات.',
    },
  },
  {
    cientifico: 'Erinaceus europaeus',
    es: 'Erizo europeo',
    en: 'European hedgehog',
    pt: 'Ouriço-cacheiro',
    fr: 'Hérisson d’Europe',
    de: 'Braunbrustigel',
    it: 'Riccio europeo',
    ja: 'ヨーロッパハリネズミ',
    zh: '西欧刺猬',
    ko: '유럽고슴도치',
    ru: 'Обыкновенный ёж',
    hi: 'यूरोपीय हेजहॉग',
    tr: 'Avrupa kirpisi',
    id: 'Landak eropa',
    pl: 'Jeż zachodni',
    nl: 'Egel',
    ar: 'القنفذ الأوروبي',
    dato: {
      es: 'Lleva 6.000 púas y en hibernación baja su corazón de 190 a 20 latidos por minuto.',
      en: 'It carries 6,000 spines and in hibernation drops its heart from 190 to 20 beats a minute.',
      pt: 'Carrega 6.000 espinhos e, na hibernação, baixa o coração de 190 para 20 batidas por minuto.',
      fr: 'Il porte 6 000 piquants et, en hibernation, son cœur passe de 190 à 20 battements par minute.',
      de: 'Er trägt 6.000 Stacheln und senkt im Winterschlaf sein Herz von 190 auf 20 Schläge.',
      it: 'Ha 6.000 aculei e in letargo porta il cuore da 190 a 20 battiti al minuto.',
      ja: '6,000本の針をまとい、冬眠中は心拍を毎分190から20まで落とします。',
      zh: '它身上有六千根刺，冬眠时心跳从每分钟190次降到20次。',
      ko: '가시가 6,000개나 되고, 겨울잠에 들면 심장이 분당 190회에서 20회로 떨어져요.',
      ru: 'На нём 6 000 иголок, а в спячке сердце замедляется со 190 до 20 ударов в минуту.',
      hi: 'इस पर 6,000 कांटे होते हैं और शीतनिद्रा में इसका दिल 190 से घटकर 20 धड़कन प्रति मिनट रह जाता है।',
      tr: 'Üstünde 6.000 diken taşır; kış uykusunda kalbi dakikada 190 atıştan 20’ye iner.',
      id: 'Ia membawa 6.000 duri, dan saat hibernasi denyut jantungnya turun dari 190 menjadi 20 per menit.',
      pl: 'Nosi 6000 kolców, a w czasie snu zimowego jego serce zwalnia ze 190 do 20 uderzeń na minutę.',
      nl: 'Hij draagt 6.000 stekels en in winterslaap zakt zijn hart van 190 naar 20 slagen per minuut.',
      ar: 'يحمل 6000 شوكة، وفي بياته الشتوي يهبط قلبه من 190 نبضة في الدقيقة إلى 20.',
    },
  },
  {
    cientifico: 'Lynx pardinus',
    es: 'Lince ibérico',
    en: 'Iberian lynx',
    pt: 'Lince-ibérico',
    fr: 'Lynx ibérique',
    de: 'Iberischer Luchs',
    it: 'Lince iberica',
    ja: 'イベリアオオヤマネコ',
    zh: '伊比利亚猞猁',
    ko: '이베리아스라소니',
    ru: 'Иберийская рысь',
    hi: 'इबेरियन लिंक्स',
    tr: 'İber vaşağı',
    id: 'Lynx Iberia',
    pl: 'Ryś iberyjski',
    nl: 'Pardellynx',
    ar: 'الوشق الأيبيري',
    dato: {
      es: 'Pasó de 94 ejemplares en 2002 a más de 2.000: el mayor rescate de un felino de la historia.',
      en: 'It went from 94 animals in 2002 to over 2,000: the greatest rescue of a cat in history.',
      pt: 'Passou de 94 indivíduos em 2002 para mais de 2.000: o maior resgate de um felino da história.',
      fr: 'Il est passé de 94 individus en 2002 à plus de 2 000 : le plus grand sauvetage d’un félin.',
      de: 'Von 94 Tieren im Jahr 2002 auf über 2.000: die größte Rettung einer Katze der Geschichte.',
      it: 'È passata da 94 esemplari nel 2002 a oltre 2.000: il più grande salvataggio di un felino.',
      ja: '2002年の94頭から2,000頭以上に増え、ネコ科の保護としては史上最大の成功です。',
      zh: '从2002年的94只增加到两千多只，这是史上最成功的猫科动物拯救。',
      ko: '2002년 94마리에서 2,000마리 넘게 늘어난, 역사상 가장 큰 고양잇과 구조예요.',
      ru: 'С 94 особей в 2002 году до более чем 2 000: крупнейшее спасение кошачьих в истории.',
      hi: '2002 में 94 से बढ़कर 2,000 से ऊपर: इतिहास में किसी बिल्ली-प्रजाति का सबसे बड़ा बचाव।',
      tr: '2002’de 94 bireyken bugün 2.000’i aştı: tarihteki en büyük kedigil kurtarma öyküsü.',
      id: 'Dari 94 ekor pada 2002 kini lebih dari 2.000: penyelamatan kucing liar terbesar sepanjang sejarah.',
      pl: 'Z 94 osobników w 2002 roku urósł do ponad 2000 — to największy ratunek kota w historii.',
      nl: 'Van 94 dieren in 2002 naar meer dan 2.000: de grootste redding van een katachtige ooit.',
      ar: 'ارتفع من 94 فردًا عام 2002 إلى أكثر من 2000: أكبر عملية إنقاذ لسنّوري في التاريخ.',
    },
  },
  {
    cientifico: 'Acinonyx jubatus',
    es: 'Guepardo',
    en: 'Cheetah',
    pt: 'Guepardo',
    fr: 'Guépard',
    de: 'Gepard',
    it: 'Ghepardo',
    ja: 'チーター',
    zh: '猎豹',
    ko: '치타',
    ru: 'Гепард',
    hi: 'चीता',
    tr: 'Çita',
    id: 'Citah',
    pl: 'Gepard',
    nl: 'Jachtluipaard',
    ar: 'الفهد',
    dato: {
      es: 'Acelera de 0 a 100 km/h en tres segundos, pero solo aguanta el sprint medio minuto.',
      en: 'It goes from 0 to 100 km/h in three seconds, but can only sustain the sprint for half a minute.',
      pt: 'Acelera de 0 a 100 km/h em três segundos, mas só aguenta o sprint por meio minuto.',
      fr: 'Il passe de 0 à 100 km/h en trois secondes, mais ne tient le sprint qu’une demi-minute.',
      de: 'Er beschleunigt in drei Sekunden von 0 auf 100 km/h, hält den Sprint aber nur eine halbe Minute.',
      it: 'Passa da 0 a 100 km/h in tre secondi, ma regge lo scatto solo per mezzo minuto.',
      ja: '三秒で時速100キロに達しますが、その全力疾走は三十秒ほどしか続きません。',
      zh: '它三秒就从静止加速到每小时100公里，但全力冲刺只能撑半分钟。',
      ko: '3초 만에 시속 100km까지 올리지만, 전력 질주는 30초밖에 못 버텨요.',
      ru: 'Разгоняется с нуля до 100 км/ч за три секунды, но держит спринт всего полминуты.',
      hi: 'यह तीन सेकंड में 0 से 100 किमी/घंटा पकड़ लेता है, पर पूरी रफ़्तार आधे मिनट ही टिकती है।',
      tr: 'Üç saniyede 0’dan 100 kilometreye çıkar ama bu hızı ancak yarım dakika taşıyabilir.',
      id: 'Ia menembus 0 sampai 100 km/jam dalam tiga detik, tapi hanya sanggup berlari kencang setengah menit.',
      pl: 'Rozpędza się od 0 do 100 km/h w trzy sekundy, ale sprint wytrzymuje tylko pół minuty.',
      nl: 'Hij gaat in drie seconden van 0 naar 100 km/u, maar houdt de sprint maar een halve minuut vol.',
      ar: 'ينطلق من صفر إلى 100 كم/س في ثلاث ثوانٍ، لكنه لا يحتمل هذه السرعة سوى نصف دقيقة.',
    },
  },
  {
    cientifico: 'Balaenoptera musculus',
    es: 'Ballena azul',
    en: 'Blue whale',
    pt: 'Baleia-azul',
    fr: 'Baleine bleue',
    de: 'Blauwal',
    it: 'Balenottera azzurra',
    ja: 'シロナガスクジラ',
    zh: '蓝鲸',
    ko: '흰긴수염고래',
    ru: 'Синий кит',
    hi: 'नीली व्हेल',
    tr: 'Mavi balina',
    id: 'Paus biru',
    pl: 'Płetwal błękitny',
    nl: 'Blauwe vinvis',
    ar: 'الحوت الأزرق',
    dato: {
      es: 'El animal más grande que ha existido: su corazón pesa como un coche pequeño.',
      en: 'The largest animal that has ever lived: its heart weighs as much as a small car.',
      pt: 'O maior animal que já existiu: o coração dela pesa como um carro pequeno.',
      fr: 'Le plus grand animal ayant jamais existé : son cœur pèse autant qu’une petite voiture.',
      de: 'Das größte Tier, das je gelebt hat: Sein Herz wiegt so viel wie ein Kleinwagen.',
      it: 'L’animale più grande mai esistito: il suo cuore pesa quanto un’auto piccola.',
      ja: 'これまで生きた中で最大の動物で、心臓の重さは小型車ほどあります。',
      zh: '有史以来最大的动物：它的心脏重得像一辆小汽车。',
      ko: '지금껏 존재한 가장 큰 동물로, 심장 무게가 소형차만 해요.',
      ru: 'Самое большое животное за всю историю: сердце весит как небольшой автомобиль.',
      hi: 'अब तक का सबसे बड़ा जानवर: इसका दिल एक छोटी कार जितना भारी होता है।',
      tr: 'Yaşamış en büyük hayvan: kalbi küçük bir araba ağırlığında.',
      id: 'Hewan terbesar yang pernah ada: jantungnya seberat mobil kecil.',
      pl: 'Największe zwierzę, jakie kiedykolwiek istniało: jego serce waży tyle co małe auto.',
      nl: 'Het grootste dier dat ooit heeft geleefd: zijn hart weegt zoveel als een kleine auto.',
      ar: 'أضخم كائن وُجد على الإطلاق: قلبه يزن كسيارة صغيرة.',
    },
  },
  {
    cientifico: 'Chamaeleo chamaeleon',
    es: 'Camaleón común',
    en: 'Common chameleon',
    pt: 'Camaleão-comum',
    fr: 'Caméléon commun',
    de: 'Gewöhnliches Chamäleon',
    it: 'Camaleonte comune',
    ja: 'ヨーロッパカメレオン',
    zh: '普通变色龙',
    ko: '유럽카멜레온',
    ru: 'Обыкновенный хамелеон',
    hi: 'आम गिरगिट',
    tr: 'Akdeniz bukalemunu',
    id: 'Bunglon biasa',
    pl: 'Kameleon pospolity',
    nl: 'Gewone kameleon',
    ar: 'الحرباء الشائعة',
    dato: {
      es: 'No cambia de color para camuflarse, sino para regular su temperatura y comunicar su humor.',
      en: 'It changes colour not to hide but to regulate temperature and signal its mood.',
      pt: 'Não muda de cor para se camuflar, e sim para regular a temperatura e mostrar o humor.',
      fr: 'Il change de couleur non pour se cacher, mais pour régler sa température et dire son humeur.',
      de: 'Es wechselt die Farbe nicht zum Tarnen, sondern um Temperatur und Stimmung zu zeigen.',
      it: 'Cambia colore non per mimetizzarsi, ma per regolare la temperatura e mostrare l’umore.',
      ja: '色を変えるのは隠れるためではなく、体温を調節し、気分を伝えるためです。',
      zh: '它变色不是为了隐身，而是为了调节体温和表达情绪。',
      ko: '색을 바꾸는 건 숨기 위해서가 아니라 체온을 맞추고 기분을 알리기 위해서예요.',
      ru: 'Цвет он меняет не ради маскировки, а чтобы согреться и показать настроение.',
      hi: 'यह रंग छिपने के लिए नहीं, बल्कि तापमान संभालने और अपना मिज़ाज बताने के लिए बदलता है।',
      tr: 'Rengini gizlenmek için değil, sıcaklığını ayarlamak ve keyfini anlatmak için değiştirir.',
      id: 'Ia berganti warna bukan untuk menyamar, melainkan untuk mengatur suhu tubuh dan menyampaikan suasana hatinya.',
      pl: 'Zmienia barwę nie po to, by się kamuflować, lecz by regulować temperaturę i pokazywać nastrój.',
      nl: 'Hij verkleurt niet om zich te camoufleren, maar om zijn temperatuur te regelen en zijn stemming te tonen.',
      ar: 'لا تبدّل لونها للتخفّي، بل لتضبط حرارتها وتُفصح عن مزاجها.',
    },
  },
  {
    cientifico: 'Aquila chrysaetos',
    es: 'Águila real',
    en: 'Golden eagle',
    pt: 'Águia-real',
    fr: 'Aigle royal',
    de: 'Steinadler',
    it: 'Aquila reale',
    ja: 'イヌワシ',
    zh: '金雕',
    ko: '검독수리',
    ru: 'Беркут',
    hi: 'सुनहरा उकाब',
    tr: 'Kaya kartalı',
    id: 'Elang emas',
    pl: 'Orzeł przedni',
    nl: 'Steenarend',
    ar: 'العقاب الذهبية',
    dato: {
      es: 'Ve a una liebre a tres kilómetros: su vista tiene el doble de resolución que la humana.',
      en: 'It spots a hare three kilometres away: its eyesight has twice the resolution of ours.',
      pt: 'Enxerga uma lebre a três quilômetros: a visão dela tem o dobro da resolução da nossa.',
      fr: 'Il repère un lièvre à trois kilomètres : sa vue a deux fois la résolution de la nôtre.',
      de: 'Er sieht einen Hasen auf drei Kilometer: Sein Blick löst doppelt so fein auf wie unserer.',
      it: 'Vede una lepre a tre chilometri: la sua vista ha il doppio della risoluzione della nostra.',
      ja: '三キロ先のノウサギを見つけ、その視力は人の倍の解像度を持ちます。',
      zh: '它能看见三公里外的野兔，视力分辨率是人的两倍。',
      ko: '3km 밖의 산토끼를 알아보고, 시력의 해상도가 사람의 두 배예요.',
      ru: 'Он видит зайца за три километра: его зрение вдвое чётче человеческого.',
      hi: 'यह तीन किलोमीटर दूर ख़रगोश देख लेता है: इसकी नज़र इंसान से दोगुनी बारीक है।',
      tr: 'Üç kilometre öteden bir tavşanı görür: gözü insanınkinin iki katı çözünürlükte.',
      id: 'Ia melihat kelinci dari tiga kilometer: ketajaman matanya dua kali lipat mata manusia.',
      pl: 'Dostrzega zająca z trzech kilometrów: jego wzrok ma dwukrotnie większą rozdzielczość niż ludzki.',
      nl: 'Hij ziet een haas op drie kilometer: zijn ogen hebben twee keer de resolutie van de onze.',
      ar: 'يرى أرنبًا من ثلاثة كيلومترات: فحدّة بصره ضعف حدّة بصر الإنسان.',
    },
  },
  {
    cientifico: 'Tyto alba',
    es: 'Lechuza común',
    en: 'Barn owl',
    pt: 'Coruja-das-torres',
    fr: 'Effraie des clochers',
    de: 'Schleiereule',
    it: 'Barbagianni',
    ja: 'メンフクロウ',
    zh: '仓鸮',
    ko: '원숭이올빼미',
    ru: 'Сипуха',
    hi: 'खलिहान उल्लू',
    tr: 'Peçeli baykuş',
    id: 'Burung hantu lumbung',
    pl: 'Płomykówka',
    nl: 'Kerkuil',
    ar: 'البومة البيضاء',
    dato: {
      es: 'Su cara en forma de corazón es una antena: caza en oscuridad total guiándose solo por el oído.',
      en: 'Its heart-shaped face is an antenna: it hunts in total darkness guided by hearing alone.',
      pt: 'A cara em forma de coração é uma antena: caça no escuro total guiando-se só pela audição.',
      fr: 'Sa face en cœur est une antenne : elle chasse dans le noir total en se guidant à l’oreille.',
      de: 'Ihr herzförmiges Gesicht ist eine Antenne: Sie jagt in völliger Dunkelheit nur nach Gehör.',
      it: 'Il muso a forma di cuore è un’antenna: caccia nel buio totale guidandosi solo con l’udito.',
      ja: 'ハート形の顔は音を集めるアンテナ。真っ暗闇でも耳だけで狩りをします。',
      zh: '它心形的脸就是一面天线：在全然的黑暗里，仅凭听觉捕猎。',
      ko: '하트 모양 얼굴이 안테나예요. 완전한 어둠 속에서도 귀만으로 사냥해요.',
      ru: 'Её сердцевидное лицо — антенна: в полной темноте она охотится на одном слухе.',
      hi: 'इसका दिल जैसा चेहरा एंटीना है: यह पूरे अंधेरे में सिर्फ़ कानों के भरोसे शिकार करता है।',
      tr: 'Kalp biçimli yüzü bir anten gibidir: zifiri karanlıkta yalnızca kulağıyla avlanır.',
      id: 'Wajahnya yang berbentuk hati adalah antena: ia berburu dalam gelap total hanya berbekal pendengaran.',
      pl: 'Jej serduszkowata twarz to antena: poluje w zupełnej ciemności, kierując się wyłącznie słuchem.',
      nl: 'Zijn hartvormige gezicht is een antenne: hij jaagt in volslagen duisternis, enkel op zijn gehoor.',
      ar: 'وجهها القلبي الشكل هوائيّ لاقط: تصطاد في ظلام دامس معتمدةً على سمعها وحده.',
    },
  },
  {
    cientifico: 'Hippocampus hippocampus',
    es: 'Caballito de mar',
    en: 'Short-snouted seahorse',
    pt: 'Cavalo-marinho-de-focinho-curto',
    fr: 'Hippocampe à museau court',
    de: 'Kurzschnäuziges Seepferdchen',
    it: 'Cavalluccio marino camuso',
    ja: 'タツノオトシゴ',
    zh: '短吻海马',
    ko: '짧은주둥이해마',
    ru: 'Морской конёк',
    hi: 'समुद्री घोड़ा',
    tr: 'Denizatı',
    id: 'Kuda laut',
    pl: 'Konik morski',
    nl: 'Kortsnuitzeepaardje',
    ar: 'فرس البحر',
    dato: {
      es: 'Es el macho quien se embaraza: incuba los huevos en una bolsa y pare las crías.',
      en: 'Here it is the male that gets pregnant: he incubates the eggs in a pouch and gives birth.',
      pt: 'É o macho que engravida: ele choca os ovos numa bolsa e dá à luz os filhotes.',
      fr: 'Ici c’est le mâle qui porte les petits : il couve les œufs dans une poche et accouche.',
      de: 'Hier wird das Männchen schwanger: Es brütet die Eier in einer Tasche aus und gebiert.',
      it: 'È il maschio a restare incinto: cova le uova in una tasca e partorisce i piccoli.',
      ja: '身ごもるのはオスのほうで、袋の中で卵を育て、子を産み出します。',
      zh: '怀孕的是雄性：它把卵放在育儿袋里孵化，再把小海马生出来。',
      ko: '임신하는 쪽은 수컷이에요. 주머니에 알을 품었다가 새끼를 낳죠.',
      ru: 'Беременеет здесь самец: он вынашивает икру в сумке и рожает мальков.',
      hi: 'यहां गर्भ नर धारण करता है: वह अंडों को थैली में सेता है और बच्चों को जन्म देता है।',
      tr: 'Gebe kalan erkektir: yumurtaları kesesinde taşır ve yavruları o doğurur.',
      id: 'Yang hamil justru sang jantan: ia mengerami telur di kantungnya dan melahirkan anak-anaknya.',
      pl: 'To samiec zachodzi w ciążę: nosi jaja w torbie i rodzi młode.',
      nl: 'Het is het mannetje dat zwanger raakt: hij draagt de eieren in een buidel en baart de jongen.',
      ar: 'الذكر هو من يحمل: يحضن البيض في جرابه ثم يلد الصغار.',
    },
  },
  {
    cientifico: 'Equus quagga',
    es: 'Cebra común',
    en: 'Plains zebra',
    pt: 'Zebra-das-planícies',
    fr: 'Zèbre des plaines',
    de: 'Steppenzebra',
    it: 'Zebra delle pianure',
    ja: 'サバンナシマウマ',
    zh: '平原斑马',
    ko: '사바나얼룩말',
    ru: 'Саванная зебра',
    hi: 'मैदानी ज़ेबरा',
    tr: 'Ova zebrası',
    id: 'Zebra dataran',
    pl: 'Zebra stepowa',
    nl: 'Steppezebra',
    ar: 'حمار الزرد السهلي',
    dato: {
      es: 'Sus rayas espantan a las moscas: los tábanos no consiguen aterrizar sobre el patrón.',
      en: 'Its stripes repel flies: horseflies cannot manage to land on the pattern.',
      pt: 'As listras espantam as moscas: as mutucas não conseguem pousar sobre o padrão.',
      fr: 'Ses rayures font fuir les mouches : les taons n’arrivent pas à se poser sur le motif.',
      de: 'Ihre Streifen vertreiben Fliegen: Bremsen schaffen es nicht, auf dem Muster zu landen.',
      it: 'Le sue strisce scacciano le mosche: i tafani non riescono ad atterrare sul motivo.',
      ja: '縞模様はハエよけです。アブは縞の上にうまく着地できません。',
      zh: '它的条纹能赶走苍蝇：牛虻没法在这种花纹上落脚。',
      ko: '줄무늬가 파리를 쫓아요. 말파리는 그 무늬 위에 제대로 앉지 못하거든요.',
      ru: 'Полосы отпугивают мух: слепни не могут сесть на такой рисунок.',
      hi: 'इसकी धारियां मक्खियों को भगाती हैं: घोड़ा-मक्खियां इस पैटर्न पर उतर ही नहीं पातीं।',
      tr: 'Çizgileri sinekleri kaçırır: at sinekleri bu desenin üstüne konmayı beceremez.',
      id: 'Belangnya mengusir lalat: pikat tak berhasil mendarat di atas pola itu.',
      pl: 'Jej pasy odstraszają muchy: bąki nie potrafią wylądować na tym wzorze.',
      nl: 'Haar strepen jagen vliegen weg: dazen slagen er niet in om op het patroon te landen.',
      ar: 'خطوطه تطرد الذباب: فذبابة الخيل لا تفلح في الحطّ على هذا النقش.',
    },
  },
  {
    cientifico: 'Suricata suricatta',
    es: 'Suricata',
    en: 'Meerkat',
    pt: 'Suricato',
    fr: 'Suricate',
    de: 'Erdmännchen',
    it: 'Suricato',
    ja: 'ミーアキャット',
    zh: '狐獴',
    ko: '미어캣',
    ru: 'Сурикат',
    hi: 'मीरकैट',
    tr: 'Mirket',
    id: 'Mirkat',
    pl: 'Surykatka',
    nl: 'Stokstaartje',
    ar: 'السرقاط',
    dato: {
      es: 'Se turnan de centinela: uno vigila erguido mientras el resto del clan excava y come.',
      en: 'They take turns on sentry duty: one stands guard while the rest of the clan digs and feeds.',
      pt: 'Revezam a sentinela: um vigia em pé enquanto o resto do clã cava e come.',
      fr: 'Ils se relaient au guet : l’un veille debout pendant que le reste du clan creuse et mange.',
      de: 'Sie wechseln sich als Wache ab: Einer steht Posten, während der Rest des Clans gräbt.',
      it: 'Si danno il cambio come sentinelle: uno vigila eretto mentre il clan scava e mangia.',
      ja: '見張りは交代制で、一頭が立って警戒するあいだ、仲間は穴を掘って食べます。',
      zh: '它们轮流放哨：一只直立警戒，其余的成员照常挖洞觅食。',
      ko: '보초를 번갈아 서요. 한 마리가 꼿꼿이 망을 보는 동안 나머지는 굴을 파고 먹죠.',
      ru: 'Дозор они несут по очереди: один стоит столбиком, пока остальные копают и едят.',
      hi: 'ये बारी-बारी पहरा देते हैं: एक सीधा खड़ा होकर निगरानी करता है और बाक़ी झुंड खोदता-खाता रहता है।',
      tr: 'Nöbeti sırayla tutarlar: biri dikilip gözcülük ederken sürünün geri kalanı kazar ve yer.',
      id: 'Mereka bergiliran jaga: satu berdiri tegak mengawasi sementara sisanya menggali dan makan.',
      pl: 'Zmieniają się na warcie: jedna stoi na baczności, gdy reszta klanu kopie i je.',
      nl: 'Ze wisselen elkaar af als wachtpost: één staat rechtop op uitkijk terwijl de rest graaft en eet.',
      ar: 'يتناوبون الحراسة: يقف أحدهم منتصبًا يرقب بينما يحفر بقية العشيرة ويأكل.',
    },
  },
  {
    cientifico: 'Bradypus variegatus',
    es: 'Perezoso',
    en: 'Brown-throated sloth',
    pt: 'Preguiça-comum',
    fr: 'Paresseux à gorge brune',
    de: 'Braunkehl-Faultier',
    it: 'Bradipo dalla gola bruna',
    ja: 'ナマケモノ',
    zh: '树懒',
    ko: '나무늘보',
    ru: 'Ленивец',
    hi: 'स्लॉथ',
    tr: 'Tembel hayvan',
    id: 'Kungkang',
    pl: 'Leniwiec pstry',
    nl: 'Kapucijnluiaard',
    ar: 'الكسلان',
    dato: {
      es: 'Se mueve tan despacio que le crecen algas en el pelo, y baja del árbol solo una vez por semana.',
      en: 'It moves so slowly that algae grow in its fur, and it climbs down only once a week.',
      pt: 'Move-se tão devagar que criam algas no pelo, e desce da árvore só uma vez por semana.',
      fr: 'Il bouge si lentement que des algues poussent dans son pelage, et il ne descend qu’une fois par semaine.',
      de: 'Es bewegt sich so langsam, dass Algen im Fell wachsen, und klettert nur einmal pro Woche herab.',
      it: 'Si muove così piano che nel pelo gli crescono alghe, e scende dall’albero una volta a settimana.',
      ja: 'あまりにゆっくり動くので毛に藻が生え、木を下りるのは週に一度だけです。',
      zh: '它慢到毛里都长出藻类，一周才从树上下来一次。',
      ko: '너무 느리게 움직여 털에 조류가 자라고, 나무에서는 일주일에 한 번만 내려와요.',
      ru: 'Он движется так медленно, что в шерсти заводятся водоросли, а с дерева спускается раз в неделю.',
      hi: 'यह इतना धीरे चलता है कि इसके बालों में शैवाल उग आते हैं, और पेड़ से हफ़्ते में सिर्फ़ एक बार उतरता है।',
      tr: 'O kadar yavaş kımıldar ki tüylerinde yosun biter; ağaçtan yalnızca haftada bir kez iner.',
      id: 'Geraknya begitu lambat sampai alga tumbuh di bulunya, dan ia turun dari pohon cuma sekali seminggu.',
      pl: 'Porusza się tak wolno, że w sierści rosną mu glony, a z drzewa schodzi raz na tydzień.',
      nl: 'Hij beweegt zo traag dat er algen in zijn vacht groeien, en hij komt maar één keer per week uit de boom.',
      ar: 'يتحرك ببطء شديد حتى تنبت الطحالب في فروه، ولا ينزل من الشجرة إلا مرة في الأسبوع.',
    },
  },
  {
    cientifico: 'Carcharodon carcharias',
    es: 'Tiburón blanco',
    en: 'Great white shark',
    pt: 'Tubarão-branco',
    fr: 'Grand requin blanc',
    de: 'Weißer Hai',
    it: 'Squalo bianco',
    ja: 'ホホジロザメ',
    zh: '大白鲨',
    ko: '백상아리',
    ru: 'Белая акула',
    hi: 'सफ़ेद शार्क',
    tr: 'Büyük beyaz köpek balığı',
    id: 'Hiu putih besar',
    pl: 'Żarłacz biały',
    nl: 'Witte haai',
    ar: 'القرش الأبيض الكبير',
    dato: {
      es: 'Detecta el campo eléctrico de un corazón latiendo y renueva sus dientes toda la vida.',
      en: 'It senses the electric field of a beating heart and replaces its teeth for life.',
      pt: 'Detecta o campo elétrico de um coração batendo e troca os dentes a vida inteira.',
      fr: 'Il détecte le champ électrique d’un cœur qui bat et renouvelle ses dents toute sa vie.',
      de: 'Er spürt das elektrische Feld eines schlagenden Herzens und ersetzt seine Zähne lebenslang.',
      it: 'Percepisce il campo elettrico di un cuore che batte e rinnova i denti per tutta la vita.',
      ja: '鼓動する心臓の電場を感じ取り、歯は一生のあいだ生えかわり続けます。',
      zh: '它能察觉一颗跳动心脏的电场，牙齿一辈子换个不停。',
      ko: '뛰는 심장의 전기장을 감지하고, 이빨은 평생 새로 나요.',
      ru: 'Она чует электрическое поле бьющегося сердца и всю жизнь меняет зубы.',
      hi: 'यह धड़कते दिल का विद्युत क्षेत्र भांप लेती है और ज़िंदगी भर दांत बदलती रहती है।',
      tr: 'Atan bir kalbin elektrik alanını sezer ve dişlerini ömrü boyunca yeniler.',
      id: 'Ia menangkap medan listrik dari jantung yang berdetak dan mengganti giginya seumur hidup.',
      pl: 'Wyczuwa pole elektryczne bijącego serca i przez całe życie wymienia zęby.',
      nl: 'Hij voelt het elektrische veld van een kloppend hart en vervangt zijn tanden zijn leven lang.',
      ar: 'يلتقط المجال الكهربائي لقلبٍ ينبض، ويجدّد أسنانه طوال حياته.',
    },
  },
  {
    cientifico: 'Mobula birostris',
    es: 'Manta gigante',
    en: 'Giant oceanic manta ray',
    pt: 'Manta-gigante',
    fr: 'Raie manta géante',
    de: 'Riesenmanta',
    it: 'Manta gigante',
    ja: 'オニイトマキエイ',
    zh: '巨型蝠鲼',
    ko: '대왕쥐가오리',
    ru: 'Гигантский морской дьявол',
    hi: 'विशाल मंटा रे',
    tr: 'Dev manta vatozu',
    id: 'Pari manta raksasa',
    pl: 'Manta olbrzymia',
    nl: 'Reuzenmanta',
    ar: 'شيطان البحر العملاق',
    dato: {
      es: 'Con siete metros de envergadura, tiene el cerebro más grande de todos los peces y se reconoce en un espejo.',
      en: 'With a seven-metre wingspan, it has the largest brain of any fish and recognises itself in a mirror.',
      pt: 'Com sete metros de envergadura, tem o maior cérebro entre os peixes e se reconhece no espelho.',
      fr: 'Avec sept mètres d’envergure, elle a le plus gros cerveau des poissons et se reconnaît au miroir.',
      de: 'Mit sieben Metern Spannweite hat sie das größte Gehirn aller Fische und erkennt sich im Spiegel.',
      it: 'Con sette metri di apertura, ha il cervello più grande di tutti i pesci e si riconosce allo specchio.',
      ja: '七メートルの体幅を持ち、魚類でいちばん大きな脳で、鏡の中の自分を自分だと分かります。',
      zh: '它有七米宽的“翼展”，脑子是所有鱼里最大的，还能在镜子里认出自己。',
      ko: '폭이 7미터에 이르고, 물고기 중 뇌가 가장 커서 거울 속 자신을 알아봐요.',
      ru: 'При семиметровом размахе «крыльев» у неё самый большой мозг среди рыб, и она узнаёт себя в зеркале.',
      hi: 'सात मीटर के फैलाव वाली यह मछली सभी मछलियों में सबसे बड़ा दिमाग़ रखती है और आईने में ख़ुद को पहचान लेती है।',
      tr: 'Yedi metrelik kanat açıklığıyla balıkların en büyük beynine sahiptir ve aynada kendini tanır.',
      id: 'Dengan bentangan tujuh meter, ia punya otak terbesar di antara semua ikan dan mengenali dirinya di cermin.',
      pl: 'Przy siedmiu metrach rozpiętości ma największy mózg ze wszystkich ryb i rozpoznaje się w lustrze.',
      nl: 'Met zeven meter spanwijdte heeft ze het grootste brein van alle vissen en herkent ze zichzelf in de spiegel.',
      ar: 'بامتداد سبعة أمتار، يملك أكبر دماغ بين الأسماك جميعًا، ويتعرّف على نفسه في المرآة.',
    },
  },
  {
    cientifico: 'Papilio machaon',
    es: 'Macaón',
    en: 'Old World swallowtail',
    pt: 'Borboleta-rabo-de-andorinha',
    fr: 'Machaon',
    de: 'Schwalbenschwanz',
    it: 'Macaone',
    ja: 'キアゲハ',
    zh: '金凤蝶',
    ko: '산호랑나비',
    ru: 'Махаон',
    hi: 'स्वालोटेल तितली',
    tr: 'Kırlangıçkuyruk',
    id: 'Kupu-kupu ekor walet',
    pl: 'Paź królowej',
    nl: 'Koninginnenpage',
    ar: 'فراشة ذيل السنونو',
    dato: {
      es: 'Su oruga saca del cuello una horquilla naranja que apesta para espantar a los depredadores.',
      en: 'Its caterpillar everts a foul-smelling orange fork from its neck to scare off predators.',
      pt: 'A lagarta dela projeta do pescoço uma forquilha laranja fedorenta para espantar predadores.',
      fr: 'Sa chenille sort de son cou une fourche orange nauséabonde pour faire fuir les prédateurs.',
      de: 'Ihre Raupe stülpt eine stinkende orange Gabel aus dem Nacken, um Fressfeinde zu vertreiben.',
      it: 'Il suo bruco estroflette dal collo una forcella arancione puzzolente per spaventare i predatori.',
      ja: '幼虫は首から橙色の臭角を突き出し、強いにおいで天敵を追いはらいます。',
      zh: '它的幼虫会从颈后伸出一根橙色的臭角，用气味吓退天敌。',
      ko: '애벌레는 목에서 주황색 냄새뿔을 내밀어 지독한 냄새로 천적을 쫓아요.',
      ru: 'Её гусеница выбрасывает из-за головы оранжевую вилку, которая отпугивает врагов вонью.',
      hi: 'इसकी इल्ली गर्दन से नारंगी कांटेदार अंग निकालकर बदबू से शिकारियों को भगाती है।',
      tr: 'Tırtılı, avcıları kaçırmak için ensesinden pis kokan turuncu bir çatal çıkarır.',
      id: 'Ulatnya menjulurkan garpu oranye berbau busuk dari tengkuknya untuk mengusir pemangsa.',
      pl: 'Jej gąsienica wysuwa z karku pomarańczowe widełki, które cuchną tak, że odstraszają drapieżniki.',
      nl: 'Zijn rups steekt een oranje vork uit zijn nek die zo stinkt dat rovers afdruipen.',
      ar: 'تُخرج يرقتها من عنقها شوكةً برتقالية نتنة الرائحة لتطرد المفترسات.',
    },
  },
]

/** La especie del día (rota por día del año), con ficha de Wikipedia. */
export async function especieDelDia(fecha: string, idioma: Idioma): Promise<Efemeride> {
  const e = ESPECIES[diaDelAnio(fecha) % ESPECIES.length]
  const wiki = await resumenWikipedia(e.cientifico, idioma)
  return {
    tipo: 'especie',
    titulo: enIdioma(e, idioma),
    subtitulo: e.cientifico,
    texto: [enIdioma(e.dato, idioma), wiki.extract].filter(Boolean).join('\n\n'),
    imagen: wiki.imagen,
  }
}
