// Generado por `npm run ejemplos:texto` — no lo edites a mano.
// Contenido del ejemplo de fábrica de jardin, en los dos idiomas. Vive aparte
// de `dict.ts` a propósito: en cuanto se crea es dato del usuario, no interfaz.

export const TEXTOS_JARDIN = {
  es: {
    sesionManana: '8 min en la mesa de la cocina, con el café enfriándose',
    sesionRespiracion: '4-7-8 en el coche antes de entrar a la reunión',
    sesionNoche: 'Body scan en la cama; me dormí antes del final',
    graciasA1: 'El pan caliente de la panadería de abajo',
    graciasA2: 'Mi hermana me devolvió la llamada',
    graciasA3: 'Una ducha caliente después de la lluvia',
    graciasB1: 'El gato dormido en el sofá al llegar a casa',
    graciasB2: 'El bus llegó justo cuando pisé la parada',
    graciasB3: 'Cenar tortilla con las ventanas abiertas',
  },
  en: {
    sesionManana: '8 quiet minutes at the kitchen table, coffee cooling',
    sesionRespiracion: '4-7-8 breathing in the car before the team meeting',
    sesionNoche: 'Body scan in bed, asleep before the end',
    graciasA1: 'Warm bread from the bakery downstairs',
    graciasA2: 'My sister called me back',
    graciasA3: 'A hot shower after getting rained on',
    graciasB1: 'The cat asleep on the couch when I got in',
    graciasB2: 'Bus pulled up right as I reached the stop',
    graciasB3: 'Scrambled eggs for dinner, windows open',
  },
  pt: {
    sesionManana: '8 min na mesa da cozinha, com o café esfriando',
    sesionRespiracion: '4-7-8 no carro antes de entrar na reunião',
    sesionNoche: 'Body scan na cama; dormi antes do final',
    graciasA1: 'O pão quentinho da padaria lá embaixo',
    graciasA2: 'Minha irmã retornou minha ligação',
    graciasA3: 'Um banho quente depois da chuva',
    graciasB1: 'O gato dormindo no sofá quando cheguei em casa',
    graciasB2: 'O ônibus chegou bem na hora que pisei no ponto',
    graciasB3: 'Jantar omelete com as janelas abertas',
  },
  fr: {
    sesionManana: '8 min à la table de la cuisine, avec le café qui refroidit',
    sesionRespiracion: '4-7-8 dans la voiture avant d\'entrer en réunion',
    sesionNoche: 'Scan corporel au lit; endormie avant la fin',
    graciasA1: 'Le pain chaud de la boulangerie d\'en bas',
    graciasA2: 'Ma sœur m\'a rappelée',
    graciasA3: 'Une douche chaude après la pluie',
    graciasB1: 'Le chat endormi sur le canapé en rentrant',
    graciasB2: 'Le bus est arrivé pile quand j\'atteignais l\'arrêt',
    graciasB3: 'Dîner d\'omelette, fenêtres ouvertes',
  },
  de: {
    sesionManana: '8 Min. am Küchentisch, während der Kaffee kalt wird',
    sesionRespiracion: '4-7-8-Atmung im Auto vor dem Meeting',
    sesionNoche: 'Body-Scan im Bett; vor dem Ende eingeschlafen',
    graciasA1: 'Das warme Brot vom Bäcker unten',
    graciasA2: 'Meine Schwester hat zurückgerufen',
    graciasA3: 'Eine heiße Dusche nach dem Regen',
    graciasB1: 'Die Katze schlief auf dem Sofa, als ich heimkam',
    graciasB2: 'Der Bus kam genau, als ich an der Haltestelle ankam',
    graciasB3: 'Omelett zum Abendessen bei offenen Fenstern',
  },
  it: {
    sesionManana: '8 min al tavolo della cucina, col caffè che si raffredda',
    sesionRespiracion: '4-7-8 in macchina prima di entrare in riunione',
    sesionNoche: 'Body scan a letto; mi sono addormentata prima della fine',
    graciasA1: 'Il pane caldo del forno qui sotto',
    graciasA2: 'Mia sorella mi ha richiamata',
    graciasA3: 'Una doccia calda dopo la pioggia',
    graciasB1: 'Il gatto addormentato sul divano al rientro',
    graciasB2: 'L\'autobus è arrivato proprio mentre arrivavo alla fermata',
    graciasB3: 'Frittata a cena con le finestre aperte',
  },
  ja: {
    sesionManana: '台所のテーブルで8分、コーヒーが冷めていくのを感じながら',
    sesionRespiracion: '会議に入る前、車の中で4-7-8呼吸法',
    sesionNoche: 'ベッドでボディスキャン。最後まで行かずに眠ってしまいました',
    graciasA1: '下のパン屋の温かいパン',
    graciasA2: '妹から折り返しの電話がありました',
    graciasA3: '雨上がりの熱いシャワー',
    graciasB1: '帰宅したらソファで猫が眠っていたこと',
    graciasB2: 'バス停に着いたちょうどそのときにバスが来たこと',
    graciasB3: '窓を開けたままトルティージャを食べた夕食',
  },
  zh: {
    sesionManana: '厨房餐桌前的8分钟,咖啡渐渐凉了',
    sesionRespiracion: '开会前在车里做4-7-8呼吸',
    sesionNoche: '床上做身体扫描,还没听完就睡着了',
    graciasA1: '楼下面包店热乎乎的面包',
    graciasA2: '妹妹回了电话',
    graciasA3: '淋雨之后的一场热水澡',
    graciasB1: '到家时猫正睡在沙发上',
    graciasB2: '刚走到车站公交车就来了',
    graciasB3: '开着窗吃西班牙烘蛋当晚饭',
  },
  ko: {
    sesionManana: '부엌 식탁에서 8분, 커피가 식어가는 동안',
    sesionRespiracion: '회의 들어가기 전 차 안에서 4-7-8 호흡',
    sesionNoche: '침대에서 바디스캔, 끝나기 전에 잠들었어요',
    graciasA1: '아래층 빵집의 따끈한 빵',
    graciasA2: '여동생이 전화를 다시 걸어줬어요',
    graciasA3: '비 맞은 뒤의 따뜻한 샤워',
    graciasB1: '집에 왔을 때 소파에서 자고 있던 고양이',
    graciasB2: '정류장에 도착하자마자 온 버스',
    graciasB3: '창문 열고 먹은 토르티야 저녁',
  },
  ru: {
    sesionManana: '8 минут за кухонным столом, пока остывает кофе',
    sesionRespiracion: 'Дыхание 4-7-8 в машине перед совещанием',
    sesionNoche: 'Сканирование тела в постели; уснулось раньше конца',
    graciasA1: 'Тёплый хлеб из пекарни на первом этаже',
    graciasA2: 'Сестра перезвонила',
    graciasA3: 'Горячий душ после дождя',
    graciasB1: 'Кот спал на диване, когда вернулись домой',
    graciasB2: 'Автобус подошёл ровно в тот момент, когда дошли до остановки',
    graciasB3: 'Ужин из тортильи с открытыми окнами',
  },
  hi: {
    sesionManana: 'रसोई की मेज़ पर 8 मिनट, कॉफ़ी ठंडी होते-होते',
    sesionRespiracion: 'मीटिंग में जाने से पहले गाड़ी में 4-7-8 साँस तकनीक',
    sesionNoche: 'बिस्तर पर बॉडी स्कैन; खत्म होने से पहले नींद आ गई',
    graciasA1: 'नीचे वाली बेकरी की गरम रोटी',
    graciasA2: 'बहन का कॉल-बैक आया',
    graciasA3: 'बारिश के बाद गरम शावर',
    graciasB1: 'घर पहुँचने पर सोफ़े पर सोई हुई बिल्ली',
    graciasB2: 'स्टॉप पर पैर रखते ही बस आ गई',
    graciasB3: 'खिड़कियाँ खुली रखकर टॉर्टिया वाला डिनर',
  },
  tr: {
    sesionManana: 'Mutfak masasında 8 dakika, kahve soğurken',
    sesionRespiracion: 'Toplantıya girmeden önce arabada 4-7-8 nefes tekniği',
    sesionNoche: 'Yatakta beden taraması; final gelmeden uyudum',
    graciasA1: 'Alt kattaki fırının sıcak ekmeği',
    graciasA2: 'Kız kardeşim aramamı geri döndü',
    graciasA3: 'Yağmurdan sonra sıcak bir duş',
    graciasB1: 'Eve geldiğimde kanepede uyuyan kedi',
    graciasB2: 'Durağa tam bastığım anda gelen otobüs',
    graciasB3: 'Pencereler açıkken omlet yemek',
  },
  id: {
    sesionManana: '8 menit di meja dapur, sambil kopi mendingin',
    sesionRespiracion: 'Teknik napas 4-7-8 di mobil sebelum masuk rapat',
    sesionNoche: 'Body scan di tempat tidur; ketiduran sebelum selesai',
    graciasA1: 'Roti hangat dari toko roti di bawah',
    graciasA2: 'Kakak perempuan menelepon balik',
    graciasA3: 'Mandi air hangat setelah kehujanan',
    graciasB1: 'Kucing tidur di sofa waktu pulang ke rumah',
    graciasB2: 'Bus datang tepat saat sampai di halte',
    graciasB3: 'Makan malam telur dadar dengan jendela terbuka',
  },
  pl: {
    sesionManana: '8 minut przy stole w kuchni, kawa stygnie',
    sesionRespiracion: 'Oddech 4-7-8 w samochodzie przed spotkaniem',
    sesionNoche: 'Skan ciała w łóżku; sen przyszedł przed końcem',
    graciasA1: 'Ciepły chleb z piekarni na dole',
    graciasA2: 'Siostra oddzwoniła',
    graciasA3: 'Gorący prysznic po deszczu',
    graciasB1: 'Kot śpiący na kanapie po powrocie do domu',
    graciasB2: 'Autobus przyjechał dokładnie w momencie dojścia do przystanku',
    graciasB3: 'Omlet na kolację przy otwartych oknach',
  },
  ar: {
    sesionManana: '8 دقائق على طاولة المطبخ، والقهوة تبرد',
    sesionRespiracion: 'تقنية 4-7-8 في السيارة قبل دخول الاجتماع',
    sesionNoche: 'مسح الجسد في السرير؛ غلبني النوم قبل النهاية',
    graciasA1: 'خبز دافئ من المخبز في الطابق السفلي',
    graciasA2: 'أختي ردّت على اتصالي',
    graciasA3: 'دُش دافئ بعد المطر',
    graciasB1: 'القطة نائمة على الأريكة عند الوصول إلى المنزل',
    graciasB2: 'وصلت الحافلة بالضبط عند الوصول إلى الموقف',
    graciasB3: 'عشاء التورتيا والنوافذ مفتوحة',
  },
  nl: {
    sesionManana: '8 minuten aan de keukentafel, terwijl de koffie afkoelt',
    sesionRespiracion: '4-7-8-ademhaling in de auto voor de vergadering',
    sesionNoche: 'Bodyscan in bed; in slaap gevallen voor het einde',
    graciasA1: 'Het warme brood van de bakker beneden',
    graciasA2: 'Mijn zus belde terug',
    graciasA3: 'Een warme douche na de regen',
    graciasB1: 'De kat die op de bank lag te slapen toen ik thuiskwam',
    graciasB2: 'De bus kwam precies aan toen ik bij de halte stapte',
    graciasB3: 'Omelet eten met de ramen open',
  },
}
