// Contenido del ejemplo de fábrica de escritura, por idioma. Vive aparte de
// `dict.ts` a propósito: en cuanto se crea es dato del usuario, no interfaz.
// El texto es PLANO: el HTML (los `<h2>` de cada carpeta y los párrafos) lo
// arma `ejemplos.ts`, así la traducción nunca ve etiquetas.

export const TEXTOS_ESCRITURA = {
  es: {
    libroTitulo: 'El invierno del faro',
    libroResumen:
      'Una restauradora vuelve al pueblo donde creció para arreglar la lámpara del faro y acaba entendiendo por qué su padre dejó de subir.',

    cap1Titulo: 'La lámpara que nadie enciende',
    cap1Texto:
      'El autobús la dejó en la curva, donde el asfalto se vuelve grava y el aire empieza a saber a sal. Nadie había ido a buscarla, y eso también era una respuesta.\n\nEl faro seguía ahí, más pequeño de lo que recordaba, con la pintura levantada como corteza. Idoia dejó la maleta en la hierba y contó las ventanas hasta arriba: seis, igual que cuando tenía nueve años y su padre la dejaba subir los domingos.',
    cap2Titulo: 'Lo que Bruno no contó',
    cap2Texto:
      'Bruno tardó en abrir. Cuando lo hizo, no preguntó qué hacía allí: se apartó de la puerta como quien lleva veinte años ensayando ese gesto.\n\nSobre la mesa había dos tazas puestas. Idoia no dijo nada, pero las miró el tiempo suficiente para que él las viera mirar.',

    persAnaTitulo: 'Idoia Sáenz',
    persAnaApariencia:
      'Cuarenta y pocos, manos de trabajar con vidrio: cortes finos que ya no se cura. Lleva el pelo recogido con lo primero que encuentra, casi siempre un lápiz.',
    persAnaPersonalidad:
      'Paciente con los objetos e impaciente con las personas. Pregunta poco porque está segura de que si espera lo suficiente, todo el mundo acaba contándolo.',
    persAnaQuiere:
      'Cree que viene a arreglar una lámpara. En realidad quiere que alguien le diga que su padre no se fue por su culpa.',
    persAnaHistoria:
      'Se marchó del pueblo a los diecinueve, el mismo verano en que el faro se apagó. Desde entonces restaura vidrieras de iglesias que no pisa.',

    persBrunoTitulo: 'Bruno Elorza',
    persBrunoApariencia:
      'Setenta y ocho años y la espalda de quien ha subido esa escalera cuarenta mil veces. Huele a tabaco de pipa aunque dejó de fumar en 2003.',
    persBrunoPersonalidad:
      'Habla como si le cobraran por palabra. Es amable de una forma que nunca se anuncia: aparece la leña cortada y él no estaba.',
    persBrunoQuiere:
      'Que la lámpara vuelva a encenderse antes de morirse. Y no tener que explicar por qué se apagó.',
    persBrunoHistoria:
      'Fue farero treinta y un años, los últimos nueve junto al padre de Idoia. Firmó el parte de aquella noche sin leerlo.',

    lugarTitulo: 'El faro de Punta Grieta',
    lugarDescripcion:
      'Torre de mampostería de dieciocho metros, encalada por fuera y de ladrillo visto en la escalera. La linterna conserva la óptica original: veintiocho lentes de vidrio tallado, tres rotas.',
    lugarAtmosfera:
      'De día huele a humedad y a metal frío. De noche el viento entra por la grieta del sur y hace un sonido largo que en el pueblo llaman «el ronquido».',
    lugarOcurre:
      'Aquí se ven por primera vez en veinte años, aquí discuten y aquí, en el último capítulo, alguien decide encenderla.',

    actoTitulo: 'Acto I · Volver',
    actoResumen:
      'Idoia llega al pueblo, se topa con Bruno y descubre que el encargo de restauración lo firmó él, no el ayuntamiento.',
    actoEscenas:
      'La parada del autobús. La primera subida al faro. El café con dos tazas. La caja de partes en el sótano.',

    tramaTitulo: 'La deuda del padre',
    tramaPlanteamiento:
      'La lámpara se apagó una noche de temporal y el pueblo culpó al padre de Idoia, que se fue sin defenderse.',
    tramaNudo:
      'Los partes del sótano están firmados por Bruno, pero la letra del último es de otra persona.',
    tramaDesenlace:
      'Bruno cuenta que aquella noche estaba borracho y que el padre de Idoia cargó con la culpa para dejarle la jubilación intacta.',

    relacionTexto: 'se deben una verdad',
    relacionNota:
      'Se conocen desde que ella tenía seis años. Él le enseñó a limpiar el bronce; ella le enseñó a discutir. Ninguno de los dos nombra al padre en voz alta hasta el capítulo cuatro.',
  },
  en: {
    libroTitulo: 'The Winter Light',
    libroResumen:
      'A glass restorer goes back to the village she grew up in to fix the lighthouse lamp, and works out why her father stopped climbing it.',

    cap1Titulo: 'The lamp nobody lights',
    cap1Texto:
      'The bus dropped her at the bend, where the tarmac turns to gravel and the air starts tasting of salt. Nobody had come to meet her, and that was an answer too.\n\nThe lighthouse was still there, smaller than she remembered, its paint lifting like bark. Nell set the case down in the grass and counted the windows to the top: six, same as when she was nine and her father let her climb up on Sundays.',
    cap2Titulo: 'What Bruno left out',
    cap2Texto:
      'Bruno took his time opening the door. When he did, he never asked what she was doing there: he just stepped aside, like a man who has been rehearsing that move for twenty years.\n\nThere were two mugs out on the table. Nell said nothing, but she looked at them long enough for him to see her looking.',

    persAnaTitulo: 'Nell Carrow',
    persAnaApariencia:
      'Early forties, hands that work with glass: thin cuts she no longer bothers to dress. Hair pinned up with whatever is nearest, usually a pencil.',
    persAnaPersonalidad:
      'Patient with objects, impatient with people. She asks very little, certain that if she waits long enough everyone tells her anyway.',
    persAnaQuiere:
      'She thinks she came to fix a lamp. What she wants is for somebody to tell her that her father didn\'t leave because of her.',
    persAnaHistoria:
      'She left the village at nineteen, the same summer the light went out. She has restored church windows ever since, in churches she never sets foot in.',

    persBrunoTitulo: 'Bruno Hale',
    persBrunoApariencia:
      'Seventy-eight, with the back of a man who has climbed those stairs forty thousand times. Still smells of pipe tobacco although he stopped in 2003.',
    persBrunoPersonalidad:
      'Talks like he is charged by the word. Kind in a way he never announces: the logs turn up split and he was never there.',
    persBrunoQuiere:
      'To see the lamp lit again before he dies. And to never have to explain why it went out.',
    persBrunoHistoria:
      'Keeper for thirty-one years, the last nine of them alongside Nell\'s father. He signed the report from that night without reading it.',

    lugarTitulo: 'Gullrock lighthouse',
    lugarDescripcion:
      'Eighteen metres of rubble masonry, whitewashed outside, bare brick up the stair. The lantern still holds its original optic: twenty-eight cut glass lenses, three of them cracked.',
    lugarAtmosfera:
      'By day it smells of damp and cold metal. At night the wind comes through the crack on the south side and makes a long sound the village calls the snore.',
    lugarOcurre:
      'They meet here for the first time in twenty years, they row here, and here, in the last chapter, somebody decides to light it.',

    actoTitulo: 'Act I · Coming back',
    actoResumen:
      'Nell arrives in the village, runs into Bruno, and finds out the restoration was commissioned by him, not by the council.',
    actoEscenas:
      'The bus stop. The first climb. Coffee with two mugs. The box of reports in the cellar.',

    tramaTitulo: 'Her father\'s debt',
    tramaPlanteamiento:
      'The lamp went out on the night of a storm and the village blamed Nell\'s father, who left without defending himself.',
    tramaNudo:
      'The reports in the cellar are signed by Bruno, but the handwriting on the last one belongs to somebody else.',
    tramaDesenlace:
      'Bruno admits he was drunk that night, and that Nell\'s father took the blame so his pension would come through untouched.',

    relacionTexto: 'they owe each other the truth',
    relacionNota:
      'They have known each other since she was six. He taught her to clean brass; she taught him to argue. Neither of them says her father\'s name out loud until chapter four.',
  },
  pt: {
    libroTitulo: 'O inverno do farol',
    libroResumen: 'Uma restauradora volta à vila onde cresceu para consertar a lâmpada do farol e acaba entendendo por que seu pai parou de subir lá.',
    cap1Titulo: 'A lâmpada que ninguém acende',
    cap1Texto: 'O ônibus a deixou na curva, onde o asfalto vira cascalho e o ar começa a ter gosto de sal. Ninguém tinha ido buscá-la, e isso também era uma resposta.\n\nO farol continuava ali, menor do que ela lembrava, com a tinta descascando como casca de árvore. Marina deixou a mala na grama e contou as janelas até o topo: seis, como quando tinha nove anos e o pai a deixava subir aos domingos.',
    cap2Titulo: 'O que Bruno não contou',
    cap2Texto: 'Bruno demorou para abrir a porta. Quando abriu, não perguntou o que ela fazia ali: afastou-se da entrada como quem ensaia esse gesto há vinte anos.\n\nNa mesa havia duas xícaras postas. Marina não disse nada, mas olhou para elas o tempo suficiente para que ele visse que ela tinha olhado.',
    persAnaTitulo: 'Marina Aguiar',
    persAnaApariencia: 'Pouco mais de quarenta anos, mãos de quem trabalha com vidro: cortes finos que ela já nem cuida mais. Prende o cabelo com o que encontra primeiro, quase sempre um lápis.',
    persAnaPersonalidad: 'Paciente com os objetos e impaciente com as pessoas. Pergunta pouco porque tem certeza de que, se esperar o suficiente, todo mundo acaba contando.',
    persAnaQuiere: 'Acha que veio consertar uma lâmpada. No fundo quer que alguém diga que o pai não foi embora por culpa dela.',
    persAnaHistoria: 'Saiu da vila aos dezenove anos, no mesmo verão em que o farol se apagou. Desde então restaura vitrais de igrejas onde nunca entra.',
    persBrunoTitulo: 'Bruno Andrade',
    persBrunoApariencia: 'Setenta e oito anos e as costas de quem já subiu essa escada quarenta mil vezes. Tem cheiro de fumo de cachimbo, embora tenha parado de fumar em 2003.',
    persBrunoPersonalidad: 'Fala como se cobrassem por palavra. É gentil de um jeito que nunca se anuncia: a lenha aparece cortada e ele não estava por perto.',
    persBrunoQuiere: 'Que a lâmpada volte a acender antes que ele morra. E não precisar explicar por que ela se apagou.',
    persBrunoHistoria: 'Foi faroleiro por trinta e um anos, os últimos nove ao lado do pai de Marina. Assinou o boletim daquela noite sem lê-lo.',
    lugarTitulo: 'O farol da Ponta da Fenda',
    lugarDescripcion: 'Torre de alvenaria com dezoito metros, caiada por fora e de tijolo aparente na escada. A lanterna conserva a óptica original: vinte e oito lentes de vidro lapidado, três delas rachadas.',
    lugarAtmosfera: 'De dia cheira a umidade e a metal frio. À noite o vento entra pela fenda do lado sul e faz um som longo que na vila chamam de ronco.',
    lugarOcurre: 'Aqui eles se veem pela primeira vez em vinte anos, aqui discutem, e aqui, no último capítulo, alguém decide acender a lâmpada.',
    actoTitulo: 'Ato I · Voltar',
    actoResumen: 'Marina chega à vila, encontra Bruno e descobre que foi ele, não a prefeitura, quem contratou o restauro.',
    actoEscenas: 'O ponto de ônibus. A primeira subida ao farol. O café com duas xícaras. A caixa de boletins no porão.',
    tramaTitulo: 'A dívida do pai',
    tramaPlanteamiento: 'A lâmpada se apagou numa noite de temporal e a vila culpou o pai de Marina, que foi embora sem se defender.',
    tramaNudo: 'Os boletins do porão estão assinados por Bruno, mas a letra do último é de outra pessoa.',
    tramaDesenlace: 'Bruno conta que naquela noite estava bêbado e que o pai de Marina assumiu a culpa para que a aposentadoria dele ficasse intacta.',
    relacionTexto: 'se devem uma verdade',
    relacionNota: 'Conhecem-se desde que ela tinha seis anos. Ele lhe ensinou a limpar o bronze; ela lhe ensinou a discutir. Nenhum dos dois diz o nome do pai em voz alta até o capítulo quatro.',
  },
  fr: {
    libroTitulo: 'L’hiver du phare',
    libroResumen: 'Une restauratrice retourne au village où elle a grandi pour réparer la lampe du phare, et finit par comprendre pourquoi son père a cessé d’y monter.',
    cap1Titulo: 'La lampe que personne n’allume',
    cap1Texto: 'Le car l’a déposée au virage, là où le bitume devient gravier et où l’air commence à avoir un goût de sel. Personne n’était venu la chercher, et c’était une réponse aussi.\n\nLe phare était toujours là, plus petit que dans son souvenir, la peinture soulevée comme une écorce. Maiwenn a posé sa valise dans l’herbe et compté les fenêtres jusqu’en haut : six, comme quand elle avait neuf ans et que son père la laissait monter le dimanche.',
    cap2Titulo: 'Ce que Bruno n’a pas dit',
    cap2Texto: 'Bruno a mis du temps à ouvrir. Quand il l’a fait, il n’a pas demandé ce qu’elle faisait là : il s’est effacé de la porte comme quelqu’un qui répète ce geste depuis vingt ans.\n\nDeux tasses étaient posées sur la table. Maiwenn n’a rien dit, mais elle les a regardées assez longtemps pour qu’il la voie regarder.',
    persAnaTitulo: 'Maiwenn Le Goff',
    persAnaApariencia: 'Un peu plus de quarante ans, des mains habituées au verre : des coupures fines qu’elle ne soigne plus. Elle attache ses cheveux avec ce qui lui tombe sous la main, presque toujours un crayon.',
    persAnaPersonalidad: 'Patiente avec les objets, impatiente avec les gens. Elle demande peu, sûre que si elle attend assez longtemps, tout le monde finit par raconter.',
    persAnaQuiere: 'Elle croit venir réparer une lampe. Ce qu’elle veut, c’est qu’on lui dise que son père n’est pas parti par sa faute.',
    persAnaHistoria: 'Elle a quitté le village à dix-neuf ans, l’été où le phare s’est éteint. Depuis, elle restaure des vitraux d’églises où elle ne met jamais les pieds.',
    persBrunoTitulo: 'Bruno Le Bris',
    persBrunoApariencia: 'Soixante-dix-huit ans et le dos de quelqu’un qui a monté cet escalier quarante mille fois. Il sent encore le tabac de pipe, alors qu’il a arrêté de fumer en 2003.',
    persBrunoPersonalidad: 'Il parle comme s’il était payé au mot. Gentil d’une façon qui ne s’annonce jamais : le bois se retrouve fendu et il n’était pas là.',
    persBrunoQuiere: 'Que la lampe s’allume à nouveau avant qu’il meure. Et ne jamais avoir à expliquer pourquoi elle s’est éteinte.',
    persBrunoHistoria: 'Gardien de phare pendant trente et un ans, les neuf derniers aux côtés du père de Maiwenn. Il a signé le rapport de cette nuit-là sans le lire.',
    lugarTitulo: 'Le phare de la Pointe de la Faille',
    lugarDescripcion: 'Tour en pierre de dix-huit mètres, chaulée à l’extérieur, en brique nue dans l’escalier. La lanterne garde son optique d’origine : vingt-huit lentilles de verre taillé, trois d’entre elles fêlées.',
    lugarAtmosfera: 'Le jour, ça sent l’humidité et le métal froid. La nuit, le vent s’engouffre par la faille côté sud et fait un long bruit que le village appelle le ronflement.',
    lugarOcurre: 'C’est ici qu’ils se retrouvent pour la première fois en vingt ans, ici qu’ils se disputent, et ici, au dernier chapitre, que quelqu’un décide d’allumer la lampe.',
    actoTitulo: 'Acte I · Revenir',
    actoResumen: 'Maiwenn arrive au village, tombe sur Bruno et découvre que c’est lui, et non la mairie, qui a commandé la restauration.',
    actoEscenas: 'L’arrêt de car. La première montée au phare. Le café avec deux tasses. La boîte de rapports dans la cave.',
    tramaTitulo: 'La dette du père',
    tramaPlanteamiento: 'La lampe s’est éteinte une nuit de tempête et le village a accusé le père de Maiwenn, qui est parti sans se défendre.',
    tramaNudo: 'Les rapports de la cave sont signés par Bruno, mais l’écriture du dernier appartient à quelqu’un d’autre.',
    tramaDesenlace: 'Bruno raconte qu’il était ivre cette nuit-là, et que le père de Maiwenn a pris la faute pour que sa retraite reste intacte.',
    relacionTexto: 'se doivent une vérité',
    relacionNota: 'Ils se connaissent depuis qu’elle a six ans. Il lui a appris à nettoyer le bronze ; elle lui a appris à se disputer. Aucun des deux ne prononce le nom du père à voix haute avant le chapitre quatre.',
  },
  de: {
    libroTitulo: 'Das Winterlicht',
    libroResumen: 'Eine Restauratorin kehrt in das Dorf zurück, in dem sie aufgewachsen ist, um die Lampe des Leuchtturms zu reparieren, und begreift am Ende, warum ihr Vater aufgehört hat hinaufzusteigen.',
    cap1Titulo: 'Die Lampe, die niemand anzündet',
    cap1Texto: 'Der Bus setzte sie an der Kurve ab, dort, wo der Asphalt zu Schotter wird und die Luft anfängt, nach Salz zu schmecken. Niemand war gekommen, um sie abzuholen, und auch das war eine Antwort.\n\nDer Leuchtturm stand noch da, kleiner als sie ihn in Erinnerung hatte, die Farbe abgeblättert wie Baumrinde. Insa stellte den Koffer ins Gras und zählte die Fenster bis nach oben: sechs, genauso wie mit neun Jahren, als ihr Vater sie sonntags hinaufsteigen ließ.',
    cap2Titulo: 'Was Bruno verschwieg',
    cap2Texto: 'Bruno ließ sich Zeit, die Tür zu öffnen. Als er es tat, fragte er nicht, was sie dort wollte: Er trat von der Tür zurück, wie jemand, der diese Geste seit zwanzig Jahren einübt.\n\nAuf dem Tisch standen zwei Tassen bereit. Insa sagte nichts, aber sie betrachtete sie lange genug, dass er merkte, wie sie hinsah.',
    persAnaTitulo: 'Insa Voss',
    persAnaApariencia: 'Anfang vierzig, Hände von der Arbeit mit Glas: feine Schnitte, die sie längst nicht mehr versorgt. Die Haare steckt sie mit dem hoch, was ihr gerade in die Finger kommt, meistens ein Bleistift.',
    persAnaPersonalidad: 'Geduldig mit Gegenständen, ungeduldig mit Menschen. Sie fragt wenig, denn sie ist sicher: Wer lange genug wartet, dem erzählt am Ende jeder alles.',
    persAnaQuiere: 'Sie glaubt, dass sie gekommen ist, um eine Lampe zu reparieren. In Wirklichkeit will sie, dass ihr jemand sagt, ihr Vater sei nicht ihretwegen gegangen.',
    persAnaHistoria: 'Sie verließ das Dorf mit neunzehn, in demselben Sommer, in dem der Leuchtturm erlosch. Seither restauriert sie Kirchenfenster in Kirchen, die sie nie betritt.',
    persBrunoTitulo: 'Bruno Reimers',
    persBrunoApariencia: 'Achtundsiebzig Jahre alt, mit dem Rücken eines Mannes, der diese Treppe vierzigtausend Mal hinaufgestiegen ist. Riecht nach Pfeifentabak, obwohl er 2003 mit dem Rauchen aufgehört hat.',
    persBrunoPersonalidad: 'Redet, als würde man ihn pro Wort bezahlen. Freundlich auf eine Art, die sich nie ankündigt: Das Brennholz liegt gespalten bereit, und er war nirgends zu sehen.',
    persBrunoQuiere: 'Dass die Lampe noch einmal brennt, bevor er stirbt. Und nicht erklären zu müssen, warum sie erloschen ist.',
    persBrunoHistoria: 'Einunddreißig Jahre lang war er Leuchtturmwärter, die letzten neun davon zusammen mit Insas Vater. Den Bericht jener Nacht unterschrieb er, ohne ihn zu lesen.',
    lugarTitulo: 'Der Leuchtturm von Rissklippe',
    lugarDescripcion: 'Ein achtzehn Meter hoher Turm aus Bruchstein, außen getüncht, im Treppenhaus offenes Mauerwerk. Die Laterne bewahrt noch die ursprüngliche Optik: achtundzwanzig geschliffene Glaslinsen, drei davon gesprungen.',
    lugarAtmosfera: 'Tagsüber riecht es nach Feuchtigkeit und kaltem Metall. Nachts dringt der Wind durch den Riss auf der Südseite und erzeugt einen langen Ton, den man im Dorf das Schnarchen nennt.',
    lugarOcurre: 'Hier sehen sie sich zum ersten Mal seit zwanzig Jahren wieder, hier streiten sie, und hier beschließt im letzten Kapitel jemand, sie anzuzünden.',
    actoTitulo: 'Akt I · Rückkehr',
    actoResumen: 'Insa kommt im Dorf an, trifft auf Bruno und entdeckt, dass er den Restaurierungsauftrag unterschrieben hat, nicht die Gemeinde.',
    actoEscenas: 'Die Bushaltestelle. Der erste Aufstieg zum Leuchtturm. Der Kaffee mit den zwei Tassen. Die Kiste mit den Berichten im Keller.',
    tramaTitulo: 'Die Schuld des Vaters',
    tramaPlanteamiento: 'Die Lampe erlosch in einer Sturmnacht, und das Dorf gab Insas Vater die Schuld, der ging, ohne sich zu verteidigen.',
    tramaNudo: 'Die Berichte im Keller sind von Bruno unterschrieben, aber die Handschrift des letzten stammt von jemand anderem.',
    tramaDesenlace: 'Bruno erzählt, dass er in jener Nacht betrunken war und dass Insas Vater die Schuld auf sich nahm, damit seine Rente unangetastet blieb.',
    relacionTexto: 'schulden sich eine wahrheit',
    relacionNota: 'Sie kennen sich, seit sie sechs war. Er brachte ihr bei, Bronze zu putzen; sie brachte ihm bei zu streiten. Keiner von beiden nennt Insas Vater laut beim Namen, bis Kapitel vier.',
  },
  it: {
    libroTitulo: 'L’inverno del faro',
    libroResumen: 'Una restauratrice torna al paese dove è cresciuta per riparare la lampada del faro e finisce per capire perché suo padre smise di salirci.',
    cap1Titulo: 'La lampada che nessuno accende',
    cap1Texto: 'L’autobus la lasciò alla curva, dove l’asfalto diventa ghiaia e l’aria comincia a sapere di sale. Nessuno era andato a prenderla, e anche quello era una risposta.\n\nIl faro era ancora lì, più piccolo di come lo ricordava, con la vernice sollevata come corteccia. Elena posò la valigia sull’erba e contò le finestre fino in cima: sei, come quando aveva nove anni e suo padre la lasciava salire la domenica.',
    cap2Titulo: 'Quello che Bruno non disse',
    cap2Texto: 'Bruno ci mise tempo ad aprire. Quando lo fece, non chiese cosa ci facesse lì: si scostò dalla porta come chi prova quel gesto da vent’anni.\n\nSul tavolo c’erano due tazze appoggiate. Elena non disse nulla, ma le guardò abbastanza a lungo perché lui la vedesse guardarle.',
    persAnaTitulo: 'Elena Deiana',
    persAnaApariencia: 'Poco più di quarant’anni, mani che lavorano il vetro: tagli sottili che ormai non cura più. Si raccoglie i capelli con il primo oggetto che trova, quasi sempre una matita.',
    persAnaPersonalidad: 'Paziente con gli oggetti e impaziente con le persone. Chiede poco perché è sicura che, se aspetta abbastanza, tutti finiscono per raccontare.',
    persAnaQuiere: 'Crede di essere venuta a riparare una lampada. In realtà vuole che qualcuno le dica che suo padre non se n’è andato per colpa sua.',
    persAnaHistoria: 'Lasciò il paese a diciannove anni, la stessa estate in cui il faro si spense. Da allora restaura vetrate di chiese in cui non mette piede.',
    persBrunoTitulo: 'Bruno Manca',
    persBrunoApariencia: 'Settantotto anni e la schiena di chi ha salito quella scala quarantamila volte. Odora ancora di tabacco da pipa, anche se smise di fumare nel 2003.',
    persBrunoPersonalidad: 'Parla come se lo pagassero a parola. È gentile in un modo che non si annuncia mai: la legna arriva tagliata e lui non c’era.',
    persBrunoQuiere: 'Che la lampada torni ad accendersi prima che muoia. E non dover mai spiegare perché si è spenta.',
    persBrunoHistoria: 'Fu guardiano del faro per trentun anni, gli ultimi nove insieme al padre di Elena. Firmò il rapporto di quella notte senza leggerlo.',
    lugarTitulo: 'Il faro di Punta Spaccata',
    lugarDescripcion: 'Torre in muratura di diciotto metri, imbiancata a calce fuori e in mattoni a vista lungo la scala. La lanterna conserva l’ottica originale: ventotto lenti di vetro tagliato, tre delle quali incrinate.',
    lugarAtmosfera: 'Di giorno sa di umidità e di metallo freddo. Di notte il vento entra dalla fenditura sul lato sud e fa un suono lungo che in paese chiamano il russare.',
    lugarOcurre: 'Qui si vedono per la prima volta in vent’anni, qui litigano e qui, nell’ultimo capitolo, qualcuno decide di accendere la lampada.',
    actoTitulo: 'Atto I · Tornare',
    actoResumen: 'Elena arriva al paese, incontra Bruno e scopre che è stato lui, non il comune, a commissionare il restauro.',
    actoEscenas: 'La fermata dell’autobus. La prima salita al faro. Il caffè con due tazze. La scatola dei rapporti in cantina.',
    tramaTitulo: 'Il debito del padre',
    tramaPlanteamiento: 'La lampada si spense una notte di tempesta e il paese diede la colpa al padre di Elena, che se ne andò senza difendersi.',
    tramaNudo: 'I rapporti in cantina sono firmati da Bruno, ma la calligrafia dell’ultimo è di un’altra persona.',
    tramaDesenlace: 'Bruno racconta che quella notte era ubriaco e che il padre di Elena si prese la colpa per lasciargli la pensione intatta.',
    relacionTexto: 'si devono una verità',
    relacionNota: 'Si conoscono da quando lei aveva sei anni. Lui le insegnò a pulire il bronzo; lei gli insegnò a discutere. Nessuno dei due pronuncia il nome del padre ad alta voce fino al capitolo quattro.',
  },
  ja: {
    libroTitulo: '灯台の冬',
    libroResumen: 'ガラス修復士が育った村に戻り、灯台のランプを直すうちに、父がなぜ昇るのをやめたのかを知ることになる。',
    cap1Titulo: '誰も灯さないランプ',
    cap1Texto: 'バスは彼女をカーブで降ろした。舗装が砂利に変わり、空気が塩の味を帯び始める場所だ。誰も迎えに来ていなかった。それもまた、ひとつの答えだった。\n\n灯台はまだそこにあった。記憶より小さく、塗装は樹皮のようにめくれている。灯里は鞄を草の上に置き、上までの窓を数えた。六つ。九歳のころ、日曜日ごとに父が上らせてくれた時と同じ数だった。',
    cap2Titulo: '岩田が語らなかったこと',
    cap2Texto: '岩田はなかなか戸を開けなかった。開けても、なぜここに来たのかとは聞かなかった。ただ、二十年もその仕草を練習してきたかのように、戸口から身を引いた。\n\n卓の上には湯呑がふたつ置かれていた。灯里は何も言わなかったが、彼がその視線に気づくまで、じっとそれを見ていた。',
    persAnaTitulo: '汐崎灯里',
    persAnaApariencia: '四十をいくつか過ぎた歳。ガラスを扱う手には、もう手当てもしない細かな切り傷がいくつも残る。髪はそのとき手近にあるもので結い上げる。たいていは鉛筆だ。',
    persAnaPersonalidad: '物には辛抱強く、人には短気だ。あまり尋ねない。十分に待てば、誰もがいずれ自分から話し出すと知っているからだ。',
    persAnaQuiere: '本人はランプを直しに来たつもりでいる。だが本当は、父が去ったのは自分のせいではないと、誰かに言ってほしいだけだ。',
    persAnaHistoria: '十九歳の夏、灯台の灯が消えたのと同じ夏に村を出た。それ以来、自分では足を踏み入れない教会のステンドグラスばかりを修復している。',
    persBrunoTitulo: '岩田修一',
    persBrunoApariencia: '七十八歳。あの階段を四万回昇った者の背中をしている。二〇〇三年に煙草はやめたはずなのに、いまもパイプの匂いがする。',
    persBrunoPersonalidad: '言葉ひとつに金でも取られるかのように話す。優しさは決して名乗らない形でやってくる。気づけば薪が割られていて、そこに彼の姿はない。',
    persBrunoQuiere: '死ぬ前にもう一度ランプを灯したい。そして、なぜそれが消えたのかは説明せずに済ませたい。',
    persBrunoHistoria: '三十一年、灯台守を務めた。最後の九年は灯里の父とともにだった。あの夜の報告書には、読みもせずに署名した。',
    lugarTitulo: '裂け岬灯台',
    lugarDescripcion: '石積みの塔で高さ十八メートル。外壁は白く塗られ、階段はむき出しの煉瓦のままだ。灯室には創建当時の光学系が今も残る。切子ガラスのレンズ二十八枚、うち三枚は割れている。',
    lugarAtmosfera: '昼は湿気と冷えた金属の匂いがする。夜になると南側の裂け目から風が入り込み、村でいびきと呼ぶ長い音を立てる。',
    lugarOcurre: 'ここで二人は二十年ぶりに顔を合わせ、ここで言い争い、そして最終章では、ここで誰かが灯をともす決意をする。',
    actoTitulo: '第一幕 · 帰郷',
    actoResumen: '灯里が村に着き、岩田と鉢合わせる。そして、修復の依頼を出したのは村役場ではなく岩田自身だったと知る。',
    actoEscenas: 'バス停。灯台への最初の昇り。湯呑ふたつのお茶。地下室の報告書の箱。',
    tramaTitulo: '父の負い目',
    tramaPlanteamiento: '嵐の夜、灯りは消えた。村は灯里の父を責め、彼は弁明もせずに村を去った。',
    tramaNudo: '地下室の報告書はすべて岩田の署名だ。だが最後の一枚だけ、筆跡が違う。',
    tramaDesenlace: '岩田が明かす。あの夜、自分は酔っていた。灯里の父はそれを黙って被り、岩田の年金を守ってくれたのだと。',
    relacionTexto: '真実の貸し借り',
    relacionNota: '灯里が六歳のころからの付き合いだ。彼は真鍮の磨き方を教え、彼女は口答えの仕方を教えた。父の名を声に出すのは、二人とも第四章まで避け続ける。',
  },
  zh: {
    libroTitulo: '灯塔的冬天',
    libroResumen: '一位玻璃修复师回到她长大的村子,想把灯塔的灯修好,却渐渐弄明白了父亲为什么不再上灯塔。',
    cap1Titulo: '没人点亮的灯',
    cap1Texto: '汽车把她放在那个弯道,柏油路在这里变成碎石,空气开始带着咸味。没有人来接她,这本身也是一种回答。\n\n灯塔还在那儿,比记忆中矮小,漆皮像树皮一样翘起。晚汐把箱子放在草地上,数着一直到塔顶的窗户:六扇,跟她九岁那年一样——那时父亲每逢星期天都让她爬上去。',
    cap2Titulo: '顾长明没说的事',
    cap2Texto: '顾长明过了很久才开门。开了门,他没问她来做什么,只是让开一步,像是这个动作已经练了二十年。\n\n桌上摆着两只茶杯。晚汐什么也没说,只是盯着看了很久,久到他也看见了她在看。',
    persAnaTitulo: '林晚汐',
    persAnaApariencia: '四十出头,一双常年碰玻璃的手,细小的划痕早已懒得包扎。头发随手一挽,通常用一支铅笔固定。',
    persAnaPersonalidad: '对物件有耐心,对人却没有。她很少发问,因为她清楚,只要等得够久,所有人最终都会自己说出来。',
    persAnaQuiere: '她以为自己是来修灯的。其实她想要的,是有人告诉她——父亲的离开不是因为她。',
    persAnaHistoria: '她十九岁离开村子,正是灯塔熄灭的那年夏天。从那以后,她修复的都是自己从不踏进的教堂的花窗玻璃。',
    persBrunoTitulo: '顾长明',
    persBrunoApariencia: '七十八岁,背影像是把那道楼梯爬过四万遍的人。虽然他二零零三年就戒了烟,身上还是有烟斗的味道。',
    persBrunoPersonalidad: '说话像是按字算钱。他的好从不声张:柴总是劈好了堆在那儿,而他人早就不见了。',
    persBrunoQuiere: '想在死前再看一次灯亮起来,也不想解释它当初为什么熄灭。',
    persBrunoHistoria: '他当了三十一年守塔人,最后九年和晚汐的父亲一起。那晚的报告,他看都没看就签了字。',
    lugarTitulo: '裂礁嘴灯塔',
    lugarDescripcion: '石砌的塔身高十八米,外墙刷白,楼梯里是裸露的红砖。灯室还保留着最初的光学镜组:二十八片雕花玻璃透镜,三片已经裂了。',
    lugarAtmosfera: '白天有潮湿和冷金属的气味。入夜后,风从南面的裂缝灌进来,发出一种长长的声音——村里人叫它鼾声。',
    lugarOcurre: '二十年来他们第一次在这里重逢,在这里争执,而在最后一章,也是在这里,有人决定把灯重新点亮。',
    actoTitulo: '第一幕 · 归来',
    actoResumen: '晚汐回到村子,撞见顾长明,发现修复的委托竟是他本人签的,而不是村委会。',
    actoEscenas: '汽车站。第一次爬上灯塔。两杯茶。地下室里的报告箱。',
    tramaTitulo: '父亲的亏欠',
    tramaPlanteamiento: '灯是在一个风暴夜熄灭的,村里人怪罪晚汐的父亲,他没有辩解,就此离开。',
    tramaNudo: '地下室里的报告都是顾长明签的名,但最后一份的笔迹,是另一个人的。',
    tramaDesenlace: '顾长明说出真相:那晚他喝醉了,晚汐的父亲替他扛下了责任,好让他的退休金保住。',
    relacionTexto: '互欠真相',
    relacionNota: '两人从她六岁起就认识。他教她擦黄铜,她教他顶嘴。直到第四章,两人才第一次把父亲的名字说出口。',
  },
  ko: {
    libroTitulo: '등대의 겨울',
    libroResumen: '유리 복원가가 나고 자란 마을로 돌아가 등대 램프를 고치다가, 아버지가 왜 더 이상 등대에 오르지 않았는지 알게 된다.',
    cap1Titulo: '아무도 켜지 않는 등불',
    cap1Texto: '버스는 그녀를 그 커브 길에 내려놓았다. 아스팔트가 자갈로 바뀌고 공기에서 소금 냄새가 나기 시작하는 곳이었다. 마중 나온 사람은 없었고, 그것 역시 하나의 대답이었다.\n\n등대는 여전히 그 자리에 있었다. 기억보다 작았고, 페인트는 나무껍질처럼 들떠 있었다. 서인은 가방을 풀밭에 내려놓고 꼭대기까지 창문을 세어보았다. 여섯 개. 아홉 살 때 일요일마다 아버지가 올려 보내주던 그때와 같은 숫자였다.',
    cap2Titulo: '고인석이 말하지 않은 것',
    cap2Texto: '고인석은 한참 만에 문을 열었다. 문을 열고도 왜 왔느냐고 묻지 않았다. 그저 문 앞에서 비켜섰다. 이십 년 동안 그 동작을 연습해 온 사람처럼.\n\n탁자 위에는 찻잔 두 개가 놓여 있었다. 서인은 아무 말도 하지 않았지만, 그가 자신의 시선을 알아챌 만큼 오래 그것을 바라보았다.',
    persAnaTitulo: '양서인',
    persAnaApariencia: '마흔을 갓 넘긴 나이, 유리를 다루는 손에는 이제 돌보지 않는 잔 흠집들이 남아 있다. 머리는 손에 잡히는 대로 아무렇게나 묶는데, 대개는 연필이다.',
    persAnaPersonalidad: '물건에는 참을성이 있지만 사람에게는 그렇지 않다. 질문을 잘 하지 않는다. 충분히 기다리면 누구나 결국 스스로 털어놓는다는 걸 알기 때문이다.',
    persAnaQuiere: '자신은 램프를 고치러 왔다고 믿는다. 사실은 누군가 아버지가 자기 때문에 떠난 게 아니라고 말해주기를 바랄 뿐이다.',
    persAnaHistoria: '열아홉에 마을을 떠났다. 등대의 불이 꺼진 바로 그해 여름이었다. 그 뒤로 자신은 발 들이지 않는 성당들의 스테인드글라스만 복원해 왔다.',
    persBrunoTitulo: '고인석',
    persBrunoApariencia: '일흔여덟, 그 계단을 사만 번은 오른 사람의 등을 하고 있다. 2003년에 담배를 끊었다는데도 여전히 파이프 담배 냄새가 난다.',
    persBrunoPersonalidad: '말 한마디에 값을 매기듯 아낀다. 그의 다정함은 결코 스스로를 알리지 않는다. 어느새 장작이 패여 있고, 그는 이미 그 자리에 없다.',
    persBrunoQuiere: '죽기 전에 램프가 다시 켜지는 걸 보고 싶다. 그리고 그것이 왜 꺼졌는지는 설명하지 않고 넘어가고 싶다.',
    persBrunoHistoria: '삼십일 년을 등대지기로 살았다. 마지막 구 년은 서인의 아버지와 함께였다. 그날 밤의 보고서에는 읽어보지도 않고 서명했다.',
    lugarTitulo: '갈라진곶 등대',
    lugarDescripcion: '높이 십팔 미터의 석조 탑으로, 바깥은 회칠을 했고 계단은 벽돌이 그대로 드러나 있다. 등실에는 처음 설치된 광학 장치가 그대로 남아 있다. 조각 유리 렌즈 스물여덟 장, 그중 세 장은 깨져 있다.',
    lugarAtmosfera: '낮에는 습기와 차가운 금속 냄새가 난다. 밤이 되면 남쪽 틈으로 바람이 들어와 마을에서 코 고는 소리라 부르는 길고 낮은 소리를 낸다.',
    lugarOcurre: '이십 년 만에 두 사람이 처음 마주치는 곳도, 다투는 곳도 여기다. 그리고 마지막 장에서, 누군가 불을 밝히기로 마음먹는 곳도 바로 여기다.',
    actoTitulo: '제1막 · 귀향',
    actoResumen: '서인이 마을에 도착해 고인석과 마주치고, 복원 의뢰를 낸 사람이 마을 사무소가 아니라 그였다는 사실을 알게 된다.',
    actoEscenas: '버스 정류장. 등대에 처음 오르던 순간. 찻잔 두 개. 지하실의 보고서 상자.',
    tramaTitulo: '아버지의 빚',
    tramaPlanteamiento: '폭풍이 몰아치던 어느 밤 램프가 꺼졌고, 마을은 서인의 아버지를 탓했다. 그는 변명 한마디 없이 마을을 떠났다.',
    tramaNudo: '지하실의 보고서들은 모두 고인석의 서명이 담겨 있다. 하지만 마지막 한 장만은 필체가 다르다.',
    tramaDesenlace: '고인석이 그날 밤 자신이 취해 있었다고, 서인의 아버지가 자신의 연금을 지키려 그 죄를 대신 짊어졌다고 털어놓는다.',
    relacionTexto: '서로에게 진실을 빚졌다',
    relacionNota: '서인이 여섯 살 때부터 알던 사이다. 그는 그녀에게 놋쇠 닦는 법을 가르쳤고, 그녀는 그에게 말대꾸하는 법을 가르쳤다. 둘 다 4장에 이르러서야 처음으로 아버지의 이름을 소리 내어 말한다.',
  },
  ru: {
    libroTitulo: 'Зимний свет',
    libroResumen: 'Реставратор витражей возвращается в посёлок, где выросла, чтобы починить лампу маяка, и в конце концов понимает, почему отец перестал туда подниматься.',
    cap1Titulo: 'Лампа, которую никто не зажигает',
    cap1Texto: 'Автобус высадил её на повороте, там, где асфальт переходит в гравий, а воздух начинает отдавать солью. Никто не пришёл её встретить, и это тоже был ответ.\n\nМаяк всё ещё стоял на месте — меньше, чем ей помнилось, с краской, вздувшейся, будто кора. Марина поставила чемодан в траву и пересчитала окна снизу доверху: шесть, как и в девять лет, когда отец по воскресеньям брал её с собой наверх.',
    cap2Titulo: 'О чём Фёдор промолчал',
    cap2Texto: 'Фёдор долго не открывал. А когда открыл, не спросил, зачем она приехала: просто отступил от двери, как человек, двадцать лет репетировавший это движение.\n\nНа столе стояли две чашки. Марина ничего не сказала, но смотрела на них достаточно долго, чтобы он заметил её взгляд.',
    persAnaTitulo: 'Марина Ветрова',
    persAnaApariencia: 'Чуть за сорок, руки — как у человека, работающего со стеклом: тонкие порезы, которые она уже не лечит. Волосы закалывает первым, что попадётся под руку, чаще всего карандашом.',
    persAnaPersonalidad: 'Терпелива с вещами и нетерпелива с людьми. Спрашивает мало — уверена, что, если подождать достаточно долго, каждый рано или поздно расскажет сам.',
    persAnaQuiere: 'Ей кажется, что она приехала чинить лампу. На самом деле она хочет, чтобы кто-нибудь сказал ей: отец ушёл не по её вине.',
    persAnaHistoria: 'Она уехала из посёлка в девятнадцать лет, тем же летом, когда погас маяк. С тех пор реставрирует церковные витражи в храмах, куда сама не заходит.',
    persBrunoTitulo: 'Фёдор Меркулов',
    persBrunoApariencia: 'Семьдесят восемь лет и спина человека, поднимавшегося по этой лестнице сорок тысяч раз. Пахнет трубочным табаком, хотя бросил курить ещё в 2003-м.',
    persBrunoPersonalidad: 'Говорит так, будто платит за каждое слово. Добр незаметно: дрова оказываются наколоты, а его самого рядом уже нет.',
    persBrunoQuiere: 'Чтобы лампа снова загорелась, пока он ещё жив. И чтобы не пришлось объяснять, почему она погасла.',
    persBrunoHistoria: 'Тридцать один год был смотрителем маяка, последние девять — вместе с отцом Марины. Подписал рапорт о той ночи, не читая.',
    lugarTitulo: 'Маяк на мысе Щелья',
    lugarDescripcion: 'Каменная башня высотой восемнадцать метров: снаружи побелена, а на лестнице — открытая кирпичная кладка. Фонарь сохранил подлинную оптику: двадцать восемь линз гранёного стекла, три из них треснувшие.',
    lugarAtmosfera: 'Днём пахнет сыростью и холодным металлом. Ночью ветер проникает сквозь трещину на южной стороне и тянет протяжный звук, который в посёлке зовут храпом.',
    lugarOcurre: 'Здесь они впервые за двадцать лет видятся, здесь спорят, и здесь же, в последней главе, кто-то решается зажечь лампу.',
    actoTitulo: 'Акт I · Возвращение',
    actoResumen: 'Марина приезжает в посёлок, сталкивается с Фёдором и узнаёт, что заказ на реставрацию оформил он сам, а не сельсовет.',
    actoEscenas: 'Автобусная остановка. Первый подъём на маяк. Кофе на две чашки. Коробка с рапортами в подвале.',
    tramaTitulo: 'Долг отца',
    tramaPlanteamiento: 'Лампа погасла штормовой ночью, и посёлок обвинил отца Марины, а он уехал, не пытаясь оправдаться.',
    tramaNudo: 'Рапорты в подвале подписаны Фёдором, но почерк в последнем — чужой.',
    tramaDesenlace: 'Фёдор признаётся, что в ту ночь был пьян и что отец Марины взял вину на себя, чтобы сохранить ему пенсию.',
    relacionTexto: 'должны друг другу правду',
    relacionNota: 'Они знакомы с тех пор, как ей было шесть лет. Он научил её чистить бронзу; она научила его спорить. Ни один из них не упоминает отца вслух до четвёртой главы.',
  },
  hi: {
    libroTitulo: 'प्रकाशस्तंभ की सर्दी',
    libroResumen: 'एक मरम्मतकार अपने बचपन के गाँव लौटती है ताकि प्रकाशस्तंभ का दीपक ठीक कर सके, और अंततः समझ जाती है कि उसके पिता ने वहाँ चढ़ना क्यों छोड़ दिया था।',
    cap1Titulo: 'वह दीपक जिसे कोई नहीं जलाता',
    cap1Texto: 'बस ने उसे मोड़ पर उतार दिया, जहाँ डामर बजरी में बदल जाता है और हवा में नमक की गंध आने लगती है। कोई उसे लेने नहीं आया था, और यह भी एक जवाब था।\n\nप्रकाशस्तंभ अब भी वहीं खड़ा था, याद से कहीं छोटा, उसका रंग छाल की तरह उखड़ा हुआ। मीरा ने बैग घास पर रख दिया और खिड़कियाँ ऊपर तक गिनीं: छह, ठीक वैसे ही जैसे तब जब वह नौ साल की थी और पिता उसे रविवार को ऊपर चढ़ने देते थे।',
    cap2Titulo: 'जो भानु ने नहीं बताया',
    cap2Texto: 'भानु ने दरवाज़ा खोलने में देर लगाई। जब खोला, तो उसने नहीं पूछा कि वह वहाँ क्या कर रही है: वह दरवाज़े से यूँ हट गया जैसे बीस सालों से यही हरकत दोहराता आ रहा हो।\n\nमेज़ पर दो प्याले रखे थे। मीरा कुछ नहीं बोली, पर उन्हें इतनी देर तक देखती रही कि भानु ने उसे देखते हुए देख लिया।',
    persAnaTitulo: 'मीरा सोलंकी',
    persAnaApariencia: 'चालीस के शुरुआती साल, काँच के साथ काम करने वाले हाथ: महीन कटने के निशान, जिन्हें अब वह पट्टी नहीं बाँधती। बाल जो भी पास मिले उससे बाँध लेती है, अक्सर एक पेंसिल से।',
    persAnaPersonalidad: 'चीज़ों के साथ धैर्यवान, लोगों के साथ अधीर। वह कम पूछती है, उसे यकीन है कि अगर वह काफ़ी देर रुके, तो हर कोई आख़िरकार खुद ही बता देता है।',
    persAnaQuiere: 'उसे लगता है कि वह एक दीपक ठीक करने आई है। असल में वह चाहती है कि कोई उससे कहे कि उसके पिता उसकी वजह से नहीं गए थे।',
    persAnaHistoria: 'वह उन्नीस साल की उम्र में गाँव छोड़ गई थी, उसी गर्मी में जब प्रकाशस्तंभ बुझ गया था। तब से वह गिरजाघरों की रंगीन खिड़कियाँ ठीक करती है, ऐसे गिरजाघरों की जहाँ वह कभी पैर नहीं रखती।',
    persBrunoTitulo: 'भानु ठाकोर',
    persBrunoApariencia: 'अठहत्तर साल, पीठ ऐसी जैसे उन सीढ़ियों पर चालीस हज़ार बार चढ़ा हो। 2003 में छोड़ने के बावजूद अब भी पाइप के तंबाकू की गंध आती है।',
    persBrunoPersonalidad: 'ऐसे बोलता है जैसे हर शब्द का पैसा देना पड़े। उसकी दयालुता कभी ख़ुद को नहीं जताती: लकड़ी कटी हुई मिल जाती है, और वह कहीं आसपास नहीं था।',
    persBrunoQuiere: 'मरने से पहले दीपक को फिर से जलता देखना चाहता है। और यह कभी न समझाना पड़े कि वह क्यों बुझा था।',
    persBrunoHistoria: 'इकतीस साल तक प्रकाशस्तंभ का रखवाला रहा, आख़िरी नौ साल मीरा के पिता के साथ। उस रात की रिपोर्ट बिना पढ़े ही उसने दस्तख़त कर दिए थे।',
    lugarTitulo: 'काली दरार का प्रकाशस्तंभ',
    lugarDescripcion: 'अठारह मीटर ऊँचा पत्थर का मीनार, बाहर से सफ़ेदी की हुई, सीढ़ियों में नंगी ईंट। लालटेन अब भी अपना मूल प्रकाशिकी संभाले है: अट्ठाईस तराशे हुए काँच के लेंस, जिनमें से तीन टूटे हैं।',
    lugarAtmosfera: 'दिन में सीलन और ठंडी धातु की गंध आती है। रात को हवा दक्षिण की दरार से भीतर आती है और एक लंबी आवाज़ बनाती है, जिसे गाँव वाले खर्राटा कहते हैं।',
    lugarOcurre: 'यहीं वे बीस साल बाद पहली बार मिलते हैं, यहीं झगड़ते हैं, और यहीं, आख़िरी अध्याय में, कोई इसे जलाने का फ़ैसला करता है।',
    actoTitulo: 'प्रथम अंक · वापसी',
    actoResumen: 'मीरा गाँव पहुँचती है, भानु से उसकी मुठभेड़ होती है, और उसे पता चलता है कि मरम्मत का ठेका पंचायत ने नहीं, बल्कि भानु ने ख़ुद दिया था।',
    actoEscenas: 'बस स्टॉप। प्रकाशस्तंभ की पहली चढ़ाई। दो प्यालों वाली चाय। तहख़ाने में रिपोर्टों का बक्सा।',
    tramaTitulo: 'पिता का कर्ज़',
    tramaPlanteamiento: 'तूफ़ान की एक रात दीपक बुझ गया, और गाँव ने मीरा के पिता को दोषी ठहराया, जो बिना खुद का बचाव किए चले गए।',
    tramaNudo: 'तहख़ाने की रिपोर्टों पर भानु के दस्तख़त हैं, पर आख़िरी वाली की लिखावट किसी और की है।',
    tramaDesenlace: 'भानु बताता है कि वह उस रात नशे में था, और मीरा के पिता ने उसकी पेंशन बचाने के लिए ख़ुद पर दोष ले लिया था।',
    relacionTexto: 'एक-दूसरे के सच के क़र्ज़दार',
    relacionNota: 'वे एक-दूसरे को तब से जानते हैं जब मीरा छह साल की थी। उसने उसे कांस्य चमकाना सिखाया; मीरा ने उसे बहस करना सिखाया। दोनों में से कोई भी चौथे अध्याय तक पिता का नाम ज़ोर से नहीं लेता।',
  },
  tr: {
    libroTitulo: 'Fenerin Kışı',
    libroResumen: 'Bir restoratör, büyüdüğü köye fenerin lambasını onarmaya döner ve babasının oraya çıkmayı neden bıraktığını orada anlar.',
    cap1Titulo: 'Kimsenin yakmadığı lamba',
    cap1Texto: 'Otobüs onu virajda indirdi, asfaltın çakıla dönüştüğü, havanın tuz kokmaya başladığı yerde. Kimse onu almaya gelmemişti; bu da bir cevaptı.\n\nFener hâlâ oradaydı, hatırladığından daha küçük, boyası kabuk gibi kabarmış. Zeynep bavulu otların üstüne bıraktı ve pencereleri yukarı doğru saydı: altı, tıpkı dokuz yaşındayken, babasının onu pazar günleri çıkarttığı zamanki gibi.',
    cap2Titulo: 'Hasan\'ın anlatmadığı',
    cap2Texto: 'Hasan kapıyı açmakta gecikti. Açtığında orada ne aradığını sormadı; yirmi yıldır o hareketi prova eden biri gibi kapıdan çekildi.\n\nMasanın üstünde iki fincan duruyordu. Zeynep bir şey demedi, ama onlara onun da baktığını görecek kadar uzun baktı.',
    persAnaTitulo: 'Zeynep Acar',
    persAnaApariencia: 'Kırklı yaşların başında, camla çalışmaktan gelen eller: artık pansuman yapmadığı ince kesikler. Saçını eline ne geçerse onunla toplar, çoğunlukla bir kalemle.',
    persAnaPersonalidad: 'Nesnelere karşı sabırlı, insanlara karşı sabırsız. Az soru sorar; yeterince beklerse herkesin er geç anlatacağından emindir.',
    persAnaQuiere: 'Buraya bir lambayı onarmaya geldiğini sanıyor. Aslında istediği, birinin ona babasının onun yüzünden gitmediğini söylemesi.',
    persAnaHistoria: 'Köyden on dokuz yaşında ayrıldı, fenerin söndüğü aynı yaz. O günden beri hiç ayak basmadığı kiliselerin vitraylarını onarıyor.',
    persBrunoTitulo: 'Hasan Demirci',
    persBrunoApariencia: 'Yetmiş sekiz yaşında, o merdiveni kırk bin kez çıkmış birinin sırtı. 2003\'te bırakmış olsa da hâlâ pipo tütünü kokuyor.',
    persBrunoPersonalidad: 'Sanki kelime başına para ödüyormuş gibi konuşur. Kendini hiç göstermeyen bir nezaketi vardır: odun kesilmiş bulunur, o ise orada değildir.',
    persBrunoQuiere: 'Ölmeden önce lambanın yeniden yanmasını istiyor. Bir de neden söndüğünü açıklamak zorunda kalmamayı.',
    persBrunoHistoria: 'Otuz bir yıl fener bekçiliği yaptı, son dokuz yılını Zeynep\'in babasıyla birlikte. O gecenin raporunu okumadan imzaladı.',
    lugarTitulo: 'Yarıkburun Feneri',
    lugarDescripcion: 'On sekiz metrelik taş bir kule, dışı kireçle badanalı, merdiveni çıplak tuğla. Fener kulesi özgün optiğini koruyor: yirmi sekiz işlemeli cam mercek, üçü kırık.',
    lugarAtmosfera: 'Gündüzleri nem ve soğuk metal kokar. Geceleri rüzgâr güneydeki yarıktan girer ve köyde horlama dedikleri uzun bir ses çıkarır.',
    lugarOcurre: 'Burada yirmi yıl sonra ilk kez karşılaşırlar, burada tartışırlar ve burada, son bölümde, biri onu yakmaya karar verir.',
    actoTitulo: 'Perde I · Dönüş',
    actoResumen: 'Zeynep köye varır, Hasan\'la karşılaşır ve restorasyon işini belediyenin değil, onun üstlendiğini öğrenir.',
    actoEscenas: 'Otobüs durağı. Fenere ilk çıkış. İki fincanlık kahve. Bodrumdaki rapor kutusu.',
    tramaTitulo: 'Babanın borcu',
    tramaPlanteamiento: 'Lamba bir fırtına gecesi söndü ve köy, kendini savunmadan giden Zeynep\'in babasını suçladı.',
    tramaNudo: 'Bodrumdaki raporları Hasan imzalamış, ama sonuncusunun el yazısı başka birine ait.',
    tramaDesenlace: 'Hasan o gece sarhoş olduğunu ve Zeynep\'in babasının emekliliğini bozmamak için suçu üstlendiğini anlatır.',
    relacionTexto: 'birbirlerine bir gerçek borçlular',
    relacionNota: 'Birbirlerini o altı yaşındayken tanıdılar. O, Zeynep\'e bronzu temizlemeyi öğretti; Zeynep de ona tartışmayı öğretti. İkisi de babanın adını dördüncü bölüme kadar yüksek sesle anmaz.',
  },
  id: {
    libroTitulo: 'Cahaya yang Padam',
    libroResumen: 'Seorang perestorasi kaca kembali ke kampung tempatnya dibesarkan untuk memperbaiki lampu mercusuar, dan akhirnya memahami mengapa ayahnya berhenti menaikinya.',
    cap1Titulo: 'Lampu yang Tak Pernah Dinyalakan',
    cap1Texto: 'Bus menurunkannya di tikungan, tempat aspal berubah jadi kerikil dan udara mulai terasa asin. Tak ada yang datang menjemputnya, dan itu juga sebuah jawaban.\n\nMercusuar itu masih di sana, lebih kecil dari yang diingatnya, catnya mengelupas seperti kulit kayu. Rani meletakkan kopernya di rumput dan menghitung jendela sampai ke atas: enam, sama seperti waktu dia berusia sembilan tahun dan ayahnya mengizinkannya naik setiap hari Minggu.',
    cap2Titulo: 'Yang Tak Diceritakan Darmawan',
    cap2Texto: 'Darmawan lama membuka pintu. Ketika akhirnya membuka, dia tak bertanya sedang apa Rani di sana: dia menyingkir dari pintu seperti orang yang sudah dua puluh tahun berlatih gerakan itu.\n\nDi atas meja ada dua cangkir tersaji. Rani tak berkata apa-apa, tapi menatapnya cukup lama sampai Darmawan melihat dia menatap.',
    persAnaTitulo: 'Rani Wijaya',
    persAnaApariencia: 'Awal empat puluhan, tangan yang terbiasa bekerja dengan kaca: luka-luka tipis yang tak lagi dia obati. Rambutnya disanggul dengan apa saja yang ada di dekatnya, biasanya sebatang pensil.',
    persAnaPersonalidad: 'Sabar pada benda, tak sabar pada orang. Dia jarang bertanya, yakin bahwa jika menunggu cukup lama, semua orang akhirnya akan bercerita sendiri.',
    persAnaQuiere: 'Dia pikir dia datang untuk memperbaiki lampu. Yang sebenarnya dia inginkan adalah seseorang mengatakan bahwa ayahnya tidak pergi karena dirinya.',
    persAnaHistoria: 'Dia meninggalkan kampung pada usia sembilan belas, musim yang sama ketika cahaya mercusuar padam. Sejak itu dia merestorasi jendela kaca gereja, gereja-gereja yang tak pernah dia masuki.',
    persBrunoTitulo: 'Darmawan Salim',
    persBrunoApariencia: 'Tujuh puluh delapan tahun, dengan punggung seorang lelaki yang telah menaiki tangga itu empat puluh ribu kali. Masih berbau tembakau pipa meski dia berhenti merokok sejak 2003.',
    persBrunoPersonalidad: 'Bicaranya seperti dihitung per kata. Kebaikannya tak pernah diumumkan: kayu bakar tiba-tiba sudah terbelah dan dia tak pernah kelihatan melakukannya.',
    persBrunoQuiere: 'Ingin melihat lampu itu menyala lagi sebelum dia mati. Dan tak pernah harus menjelaskan mengapa lampu itu padam.',
    persBrunoHistoria: 'Menjadi penjaga mercusuar selama tiga puluh satu tahun, sembilan tahun terakhir bersama ayah Rani. Dia menandatangani laporan malam itu tanpa membacanya.',
    lugarTitulo: 'Mercusuar Tanjung Retak',
    lugarDescripcion: 'Menara batu setinggi delapan belas meter, dikapur putih di luar dan bata terbuka di tangga. Lentera mercusuar masih menyimpan optik aslinya: dua puluh delapan lensa kaca berukir, tiga di antaranya retak.',
    lugarAtmosfera: 'Di siang hari baunya lembap dan logam dingin. Di malam hari angin masuk lewat retakan di sisi selatan dan menimbulkan suara panjang yang oleh warga kampung disebut dengkuran.',
    lugarOcurre: 'Di sinilah mereka bertemu untuk pertama kalinya dalam dua puluh tahun, di sini mereka bertengkar, dan di sini, di bab terakhir, seseorang memutuskan untuk menyalakannya.',
    actoTitulo: 'Babak I · Kembali',
    actoResumen: 'Rani tiba di kampung, bertemu Darmawan, dan mengetahui bahwa dialah yang memesan restorasi itu, bukan pemerintah desa.',
    actoEscenas: 'Halte bus. Pendakian pertama ke mercusuar. Kopi dengan dua cangkir. Kotak laporan di ruang bawah tanah.',
    tramaTitulo: 'Utang Sang Ayah',
    tramaPlanteamiento: 'Lampu padam pada malam badai, dan kampung menyalahkan ayah Rani, yang pergi tanpa membela diri.',
    tramaNudo: 'Laporan-laporan di ruang bawah tanah ditandatangani Darmawan, tapi tulisan tangan pada laporan terakhir milik orang lain.',
    tramaDesenlace: 'Darmawan mengakui dia mabuk malam itu, dan ayah Rani menanggung kesalahan itu agar pensiunnya tetap utuh.',
    relacionTexto: 'berutang kebenaran satu sama lain',
    relacionNota: 'Mereka saling mengenal sejak Rani berusia enam tahun. Darmawan mengajarinya membersihkan perunggu; Rani mengajarinya berdebat. Tak satu pun dari mereka menyebut nama sang ayah dengan suara keras sampai bab empat.',
  },
  pl: {
    libroTitulo: 'Zimowe światło',
    libroResumen: 'Konserwatorka witraży wraca do miasteczka, w którym dorastała, żeby naprawić lampę latarni morskiej, i w końcu rozumie, dlaczego jej ojciec przestał na nią wchodzić.',
    cap1Titulo: 'Lampa, której nikt nie zapala',
    cap1Texto: 'Autobus wysadził ją na zakręcie, tam, gdzie asfalt zamienia się w żwir, a powietrze zaczyna smakować solą. Nikt po nią nie przyszedł, i to też było odpowiedzią.\n\nLatarnia wciąż tam stała, mniejsza, niż zapamiętała, z farbą łuszczącą się jak kora. Zofia postawiła walizkę w trawie i policzyła okna od dołu do góry: sześć, tyle samo co wtedy, gdy miała dziewięć lat, a ojciec pozwalał jej wchodzić na górę w niedziele.',
    cap2Titulo: 'Czego Bruno nie powiedział',
    cap2Texto: 'Bruno długo nie otwierał. Kiedy w końcu to zrobił, nie zapytał, po co przyjechała: po prostu odsunął się od drzwi, jak ktoś, kto od dwudziestu lat ćwiczy ten gest.\n\nNa stole stały dwa kubki. Zofia nic nie powiedziała, ale patrzyła na nie wystarczająco długo, żeby zobaczył, że patrzy.',
    persAnaTitulo: 'Zofia Wichura',
    persAnaApariencia: 'Nieco po czterdziestce, ręce jak u kogoś, kto pracuje ze szkłem: drobne skaleczenia, których już nie opatruje. Włosy spina pierwszą rzeczą, jaka jest pod ręką, zwykle ołówkiem.',
    persAnaPersonalidad: 'Cierpliwa wobec przedmiotów, niecierpliwa wobec ludzi. Pyta niewiele, bo jest pewna, że jeśli poczeka dość długo, każdy w końcu sam wszystko powie.',
    persAnaQuiere: 'Wydaje jej się, że przyjechała naprawić lampę. Naprawdę chce, żeby ktoś powiedział jej, że ojciec nie odszedł z jej winy.',
    persAnaHistoria: 'Wyjechała z miasteczka w wieku dziewiętnastu lat, tego samego lata, gdy zgasła latarnia. Od tamtej pory konserwuje kościelne witraże w świątyniach, do których sama nie wchodzi.',
    persBrunoTitulo: 'Bruno Zalewski',
    persBrunoApariencia: 'Siedemdziesiąt osiem lat i plecy kogoś, kto wchodził po tych schodach czterdzieści tysięcy razy. Pachnie tytoniem fajkowym, choć rzucił palenie w 2003 roku.',
    persBrunoPersonalidad: 'Mówi tak, jakby płacił za każde słowo. Jest dobry w sposób, który nigdy się nie zapowiada: drewno okazuje się porąbane, a jego akurat nie było w pobliżu.',
    persBrunoQuiere: 'Żeby lampa znów zapłonęła, zanim umrze. I żeby nie musieć tłumaczyć, dlaczego zgasła.',
    persBrunoHistoria: 'Był latarnikiem przez trzydzieści jeden lat, ostatnie dziewięć razem z ojcem Zofii. Podpisał raport z tamtej nocy, nie czytając go.',
    lugarTitulo: 'Latarnia na Przylądku Szczelina',
    lugarDescripcion: 'Murowana wieża o wysokości osiemnastu metrów, otynkowana na biało na zewnątrz, z surową cegłą na klatce schodowej. Latarnia zachowała oryginalną optykę: dwadzieścia osiem szlifowanych szklanych soczewek, trzy z nich pęknięte.',
    lugarAtmosfera: 'W dzień pachnie wilgocią i zimnym metalem. W nocy wiatr wdziera się przez szczelinę po południowej stronie i wydaje długi dźwięk, który w miasteczku nazywają chrapaniem.',
    lugarOcurre: 'Tutaj widzą się pierwszy raz od dwudziestu lat, tutaj się kłócą i tutaj, w ostatnim rozdziale, ktoś postanawia ją zapalić.',
    actoTitulo: 'Akt I · Powrót',
    actoResumen: 'Zofia przyjeżdża do miasteczka, natyka się na Bruna i odkrywa, że zlecenie renowacji podpisał on, a nie urząd gminy.',
    actoEscenas: 'Przystanek autobusowy. Pierwsze wejście na latarnię. Kawa w dwóch kubkach. Pudełko z raportami w piwnicy.',
    tramaTitulo: 'Dług ojca',
    tramaPlanteamiento: 'Lampa zgasła pewnej sztormowej nocy, a miasteczko obwiniło ojca Zofii, który wyjechał, nawet się nie broniąc.',
    tramaNudo: 'Raporty z piwnicy są podpisane przez Bruna, ale pismo na ostatnim należy do kogoś innego.',
    tramaDesenlace: 'Bruno przyznaje, że tamtej nocy był pijany i że ojciec Zofii wziął winę na siebie, żeby ocalić mu emeryturę.',
    relacionTexto: 'są sobie winni prawdę',
    relacionNota: 'Znają się, odkąd miała sześć lat. On nauczył ją czyścić brąz; ona nauczyła go kłócić się. Żadne z nich nie wspomina głośno o ojcu aż do czwartego rozdziału.',
  },
  ar: {
    libroTitulo: 'شتاء المنارة',
    libroResumen: 'ترجع مرمّمة زجاج إلى القرية التي كبرت فيها لتصلح مصباح المنارة، فتفهم أخيرًا لماذا توقف والدها عن الصعود إليه.',
    cap1Titulo: 'المصباح الذي لا يشعله أحد',
    cap1Texto: 'تركتها الحافلة عند المنعطف، حيث يتحول الإسفلت إلى حصى ويبدأ الهواء بطعم الملح. لم يأتِ أحد لاستقبالها، وكان ذلك أيضًا جوابًا.\n\nكانت المنارة ما تزال هناك، أصغر مما تذكرت، وطلاؤها متقشر كلحاء الشجر. تركت نورة حقيبتها فوق العشب وعدّت النوافذ حتى الأعلى: ستة، تمامًا كما في التاسعة من عمرها حين كان والدها يدعها تصعد أيام الآحاد.',
    cap2Titulo: 'ما لم يخبر به سالم',
    cap2Texto: 'تأخر سالم في فتح الباب. وحين فتحه، لم يسألها عمّا تفعله هناك: ابتعد عن الباب كمن يتمرّن على تلك الحركة منذ عشرين عامًا.\n\nكان هناك كوبان على الطاولة. لم تقل نورة شيئًا، لكنها نظرت إليهما وقتًا كافيًا ليراها تنظر.',
    persAnaTitulo: 'نورة الحارثي',
    persAnaApariencia: 'في مطلع الأربعينيات، بيدين تحملان أثر العمل بالزجاج: جروح رفيعة لم تعد تضمّدها. تجمع شعرها بأول ما يقع تحت يدها، غالبًا قلم رصاص.',
    persAnaPersonalidad: 'صبورة مع الأشياء، نافدة الصبر مع الناس. تسأل قليلًا، واثقة أنها إن انتظرت بما يكفي فسيخبرها الجميع في النهاية.',
    persAnaQuiere: 'تظن أنها أتت لتصلح مصباحًا. ما تريده حقًا أن يقول لها أحد إن والدها لم يرحل بسببها.',
    persAnaHistoria: 'غادرت القرية في التاسعة عشرة، في الصيف نفسه الذي انطفأت فيه المنارة. ومنذ ذلك الحين ترمّم نوافذ الكنائس الزجاجية، كنائس لا تطأ عتبتها أبدًا.',
    persBrunoTitulo: 'سالم الفارسي',
    persBrunoApariencia: 'ثمانية وسبعون عامًا، وظهر من صعد ذلك الدرج أربعين ألف مرة. ما تزال رائحة تبغ الغليون تفوح منه رغم أنه توقف عن التدخين سنة 2003.',
    persBrunoPersonalidad: 'يتحدث كأنه يدفع ثمن كل كلمة. طيّب بطريقة لا تُعلن عن نفسها: يظهر الحطب مقطوعًا ولم يكن هو هناك.',
    persBrunoQuiere: 'أن يرى المصباح مضاءً من جديد قبل أن يموت. وألا يضطر أبدًا لتفسير سبب انطفائه.',
    persBrunoHistoria: 'عمل حارسًا للمنارة واحدًا وثلاثين عامًا، آخر تسعة منها إلى جانب والد نورة. وقّع تقرير تلك الليلة دون أن يقرأه.',
    lugarTitulo: 'منارة رأس الصدع',
    lugarDescripcion: 'برج من الحجارة ارتفاعه ثمانية عشر مترًا، مطلي بالجير من الخارج والدرج من الطوب العاري. ما تزال قمرة الإضاءة تحتفظ بمنظومتها البصرية الأصلية: ثمانية وعشرون عدسة زجاجية مصقولة، ثلاث منها مكسورة.',
    lugarAtmosfera: 'نهارًا تفوح منها رائحة الرطوبة والمعدن البارد. وليلًا تدخل الريح من الصدع في الجهة الجنوبية فتُصدر صوتًا طويلًا يسميه أهل القرية الشخير.',
    lugarOcurre: 'هنا يلتقيان لأول مرة منذ عشرين عامًا، وهنا يتجادلان، وهنا، في الفصل الأخير، يقرر أحدهما إشعالها.',
    actoTitulo: 'الجزء الأول · العودة',
    actoResumen: 'تصل نورة إلى القرية، فتصادف سالم، وتكتشف أن طلب الترميم كان منه هو، لا من البلدية.',
    actoEscenas: 'موقف الحافلة. الصعود الأول إلى المنارة. القهوة بكوبين. صندوق التقارير في القبو.',
    tramaTitulo: 'دَين الأب',
    tramaPlanteamiento: 'انطفأ المصباح في ليلة عاصفة، فحمّلت القرية والد نورة المسؤولية، فرحل دون أن يدافع عن نفسه.',
    tramaNudo: 'التقارير في القبو موقعة من سالم، لكن خط اليد في آخرها يعود لشخص آخر.',
    tramaDesenlace: 'يعترف سالم بأنه كان ثملًا تلك الليلة، وأن والد نورة تحمّل اللوم كي يبقى راتبه التقاعدي سليمًا.',
    relacionTexto: 'مدينان لبعضهما بالحقيقة',
    relacionNota: 'يعرف أحدهما الآخر منذ أن كانت نورة في السادسة. علّمها تلميع البرونز؛ وعلّمته هي الجدال. لا أحد منهما يذكر اسم الأب بصوت عالٍ حتى الفصل الرابع.',
  },
  nl: {
    libroTitulo: 'Het winterlicht',
    libroResumen: 'Een glasrestaurateur keert terug naar het dorp waar ze opgroeide om de lamp van de vuurtoren te repareren, en komt erachter waarom haar vader ophield met naar boven klimmen.',
    cap1Titulo: 'De lamp die niemand aansteekt',
    cap1Texto: 'De bus zette haar af bij de bocht, waar het asfalt overgaat in grind en de lucht naar zout begint te smaken. Niemand was haar komen ophalen, en ook dat was een antwoord.\n\nDe vuurtoren stond er nog, kleiner dan ze zich herinnerde, de verf bladderend als schors. Marit zette de koffer in het gras en telde de ramen tot boven: zes, net als toen ze negen was en haar vader haar \'s zondags liet klimmen.',
    cap2Titulo: 'Wat Bruno verzweeg',
    cap2Texto: 'Bruno deed er lang over om open te doen. Toen hij dat deed, vroeg hij niet wat ze daar kwam doen: hij stapte opzij, als iemand die dat gebaar al twintig jaar oefent.\n\nOp tafel stonden twee kopjes klaar. Marit zei niets, maar keek er lang genoeg naar om hem te laten merken dat ze keek.',
    persAnaTitulo: 'Marit Dekker',
    persAnaApariencia: 'Begin veertig, handen die met glas werken: dunne sneetjes die ze allang niet meer verzorgt. De haren houdt ze bijeen met wat ze het eerst te pakken krijgt, meestal een potlood.',
    persAnaPersonalidad: 'Geduldig met voorwerpen, ongeduldig met mensen. Ze vraagt weinig, want ze weet zeker dat wie lang genoeg wacht, uiteindelijk alles verteld krijgt.',
    persAnaQuiere: 'Ze denkt dat ze gekomen is om een lamp te repareren. Wat ze eigenlijk wil is dat iemand haar zegt dat haar vader niet vanwege haar is vertrokken.',
    persAnaHistoria: 'Ze vertrok uit het dorp op haar negentiende, dezelfde zomer dat het licht doofde. Sindsdien restaureert ze glas-in-loodramen van kerken waar ze zelf nooit binnengaat.',
    persBrunoTitulo: 'Bruno Visser',
    persBrunoApariencia: 'Achtenzeventig jaar, met de rug van iemand die die trap veertigduizend keer beklommen heeft. Ruikt naar pijptabak, ook al is hij in 2003 gestopt met roken.',
    persBrunoPersonalidad: 'Praat alsof hij per woord betaald wordt. Vriendelijk op een manier die zich nooit aankondigt: het brandhout ligt gekloofd klaar, en hij was nergens te bekennen.',
    persBrunoQuiere: 'Dat de lamp nog eens brandt voordat hij sterft. En nooit te hoeven uitleggen waarom hij doofde.',
    persBrunoHistoria: 'Eenendertig jaar was hij vuurtorenwachter, de laatste negen samen met Marits vader. Het rapport van die nacht ondertekende hij zonder het te lezen.',
    lugarTitulo: 'De vuurtoren van Kloofpunt',
    lugarDescripcion: 'Achttien meter metselwerk, van buiten gewit, met onbepleisterde muren in het trapportaal. De lantaarn heeft nog de oorspronkelijke optiek: achtentwintig geslepen glazen lenzen, drie ervan gebarsten.',
    lugarAtmosfera: 'Overdag ruikt het naar vocht en koud metaal. \'s Nachts komt de wind door de kloof aan de zuidkant naar binnen en maakt een lang geluid dat men in het dorp het gesnurk noemt.',
    lugarOcurre: 'Hier zien ze elkaar voor het eerst in twintig jaar terug, hier maken ze ruzie, en hier besluit iemand, in het laatste hoofdstuk, hem aan te steken.',
    actoTitulo: 'Bedrijf I · Terugkeer',
    actoResumen: 'Marit komt aan in het dorp, loopt Bruno tegen het lijf en ontdekt dat hij de restauratieopdracht heeft ondertekend, niet de gemeente.',
    actoEscenas: 'De bushalte. De eerste beklimming van de vuurtoren. De koffie met twee kopjes. De doos met rapporten in de kelder.',
    tramaTitulo: 'De schuld van de vader',
    tramaPlanteamiento: 'De lamp doofde op een nacht van storm en het dorp gaf de schuld aan Marits vader, die vertrok zonder zich te verdedigen.',
    tramaNudo: 'De rapporten in de kelder zijn door Bruno ondertekend, maar het handschrift van het laatste is van iemand anders.',
    tramaDesenlace: 'Bruno vertelt dat hij die nacht dronken was en dat Marits vader de schuld op zich nam zodat zijn pensioen onaangetast bleef.',
    relacionTexto: 'zijn elkaar een waarheid verschuldigd',
    relacionNota: 'Ze kennen elkaar sinds ze zes was. Hij leerde haar brons poetsen; zij leerde hem ruziemaken. Geen van beiden zegt de naam van Marits vader hardop, tot hoofdstuk vier.',
  },
}
