import type { PorIdioma } from '../../core/i18n/porIdioma'

// Contenido del ejemplo de fábrica de Metas, en los 16 idiomas. Vive aparte de
// `dict.ts` a propósito: en cuanto se crea es dato del usuario, no interfaz.
// Las fases del plan y las sub-metas que nacieron de él comparten clave: se
// emparejan por nombre (ver `espejoDePlan`), así que se traducen a la par.

const es = {
  correr: 'Correr 5 km sin parar',
  notaCorrer: 'Tres salidas por semana, sin prisa: primero aguantar, después alargar.',
  fase1: 'Alternar caminata y trote',
  fase2: 'Trotar 20 minutos seguidos',
  fase3: 'Completar los 5 km',
  resumenCorrer:
    'Ocho semanas en tres fases: alternar caminata y trote hasta que no cueste, sostener el trote veinte minutos y, al final, estirar la distancia hasta los 5 km.',
  leer: 'Leer 6 libros este semestre',
  pasoLeer1: 'Elegir los seis libros',
  pasoLeer2: 'Apartar 20 minutos antes de dormir',
  leerFase1: 'Tomar ritmo con dos libros cortos',
  leerSub1: 'Una novela corta para empezar',
  leerSub2: 'Un ensayo breve',
  leerFase2: 'Dos libros pendientes desde hace tiempo',
  leerFase3: 'Cerrar con los dos más largos',
  resumenLeer:
    'Veintiséis semanas, un libro al mes: dos cortos para tomar ritmo, dos de los que llevan tiempo esperando y los dos más largos al final, cuando la costumbre ya esté hecha.',
  refresco: 'Dejar el refresco entre semana',
  pasoRefresco1: 'Cambiarlo por agua con limón',
  pasoRefresco2: 'Aguantar 30 días seguidos',
  notaRefresco: 'Cumplida: ahora solo el fin de semana, y ni se extraña.',
  planA: 'Plan A',
}

export const TEXTOS_METAS: PorIdioma<typeof es> = {
  es,
  en: {
    correr: 'Run 5 km without stopping',
    notaCorrer: 'Three runs a week, no rush: first endurance, then distance.',
    fase1: 'Alternate walking and jogging',
    fase2: 'Jog 20 minutes straight',
    fase3: 'Complete the full 5 km',
    resumenCorrer:
      'Eight weeks in three phases: alternate walking and jogging until it feels easy, hold a 20-minute jog, and finally stretch the distance to 5 km.',
    leer: 'Read 6 books this semester',
    pasoLeer1: 'Pick the six books',
    pasoLeer2: 'Set aside 20 minutes before bed',
    leerFase1: 'Find a rhythm with two short books',
    leerSub1: 'A short novel to start',
    leerSub2: 'A short essay',
    leerFase2: 'Two books that have waited too long',
    leerFase3: 'Finish with the two longest',
    resumenLeer:
      'Twenty-six weeks, one book a month: two short ones to find a rhythm, two that have been waiting on the shelf, and the two longest at the end, once the habit has stuck.',
    refresco: 'Quit soda on weekdays',
    pasoRefresco1: 'Swap it for water with lemon',
    pasoRefresco2: 'Hold out for 30 days in a row',
    notaRefresco: "Done: now only on weekends, and it isn't even missed.",
    planA: 'Plan A',
  },
  pt: {
    correr: 'Correr 5 km sem parar',
    notaCorrer: 'Três saídas por semana, sem pressa: primeiro aguentar, depois aumentar.',
    fase1: 'Alternar caminhada e trote',
    fase2: 'Trotar 20 minutos seguidos',
    fase3: 'Completar os 5 km',
    resumenCorrer:
      'Oito semanas em três fases: alternar caminhada e trote até ficar fácil, sustentar o trote por vinte minutos e, no fim, aumentar a distância até os 5 km.',
    leer: 'Ler 6 livros neste semestre',
    pasoLeer1: 'Escolher os seis livros',
    pasoLeer2: 'Separar 20 minutos antes de dormir',
    leerFase1: 'Pegar o ritmo com dois livros curtos',
    leerSub1: 'Um romance curto para começar',
    leerSub2: 'Um ensaio breve',
    leerFase2: 'Dois livros pendentes há muito tempo',
    leerFase3: 'Fechar com os dois mais longos',
    resumenLeer:
      'Vinte e seis semanas, um livro por mês: dois curtos para pegar o ritmo, dois dos que esperam há tempos e os dois mais longos no final, quando o hábito já estiver formado.',
    refresco: 'Largar o refrigerante durante a semana',
    pasoRefresco1: 'Trocar por água com limão',
    pasoRefresco2: 'Aguentar 30 dias seguidos',
    notaRefresco: 'Cumprida: agora só no fim de semana, e nem faz falta.',
    planA: 'Plano A',
  },
  fr: {
    correr: 'Courir 5 km sans s\'arrêter',
    notaCorrer: 'Trois sorties par semaine, sans se presser : d\'abord tenir, ensuite allonger.',
    fase1: 'Alterner marche et footing',
    fase2: 'Courir 20 minutes d\'affilée',
    fase3: 'Boucler les 5 km',
    resumenCorrer:
      'Huit semaines en trois phases : alterner marche et footing jusqu\'à ce que ce soit facile, tenir vingt minutes de course, puis allonger la distance jusqu\'aux 5 km.',
    leer: 'Lire 6 livres ce semestre',
    pasoLeer1: 'Choisir les six livres',
    pasoLeer2: 'Réserver 20 minutes avant de dormir',
    leerFase1: 'Prendre le rythme avec deux livres courts',
    leerSub1: 'Un court roman pour commencer',
    leerSub2: 'Un essai bref',
    leerFase2: 'Deux livres qui attendent depuis longtemps',
    leerFase3: 'Finir avec les deux plus longs',
    resumenLeer:
      'Vingt-six semaines, un livre par mois : deux courts pour prendre le rythme, deux qui attendent depuis longtemps, et les deux plus longs à la fin, quand l\'habitude sera prise.',
    refresco: 'Arrêter les sodas en semaine',
    pasoRefresco1: 'Les remplacer par de l\'eau citronnée',
    pasoRefresco2: 'Tenir 30 jours d\'affilée',
    notaRefresco: 'Objectif atteint : maintenant seulement le week-end, et ça ne manque même pas.',
    planA: 'Plan A',
  },
  de: {
    correr: '5 km am Stück laufen',
    notaCorrer: 'Drei Läufe pro Woche, ohne Eile: erst durchhalten, dann verlängern.',
    fase1: 'Gehen und Joggen abwechseln',
    fase2: '20 Minuten am Stück joggen',
    fase3: 'Die vollen 5 km schaffen',
    resumenCorrer:
      'Acht Wochen in drei Phasen: Gehen und Joggen abwechseln, bis es leichtfällt, zwanzig Minuten durchjoggen und zum Schluss die Strecke auf 5 km verlängern.',
    leer: 'Dieses Semester 6 Bücher lesen',
    pasoLeer1: 'Die sechs Bücher auswählen',
    pasoLeer2: '20 Minuten vor dem Schlafen einplanen',
    leerFase1: 'Mit zwei kurzen Büchern in den Rhythmus kommen',
    leerSub1: 'Ein kurzer Roman zum Einstieg',
    leerSub2: 'Ein knapper Essay',
    leerFase2: 'Zwei Bücher, die schon lange warten',
    leerFase3: 'Mit den zwei längsten abschließen',
    resumenLeer:
      'Sechsundzwanzig Wochen, ein Buch pro Monat: zwei kurze, um in den Rhythmus zu kommen, zwei, die schon lange warten, und die zwei längsten am Ende, wenn die Gewohnheit sitzt.',
    refresco: 'Unter der Woche auf Limo verzichten',
    pasoRefresco1: 'Durch Wasser mit Zitrone ersetzen',
    pasoRefresco2: '30 Tage am Stück durchhalten',
    notaRefresco: 'Geschafft: jetzt nur noch am Wochenende, und sie fehlt nicht einmal.',
    planA: 'Plan A',
  },
  it: {
    correr: 'Correre 5 km senza fermarsi',
    notaCorrer: 'Tre uscite a settimana, senza fretta: prima resistere, poi allungare.',
    fase1: 'Alternare camminata e corsa leggera',
    fase2: 'Correre 20 minuti di fila',
    fase3: 'Completare i 5 km',
    resumenCorrer:
      'Otto settimane in tre fasi: alternare camminata e corsa leggera finché non diventa facile, reggere venti minuti di corsa e, alla fine, allungare la distanza fino ai 5 km.',
    leer: 'Leggere 6 libri questo semestre',
    pasoLeer1: 'Scegliere i sei libri',
    pasoLeer2: 'Ritagliarsi 20 minuti prima di dormire',
    leerFase1: 'Prendere il ritmo con due libri brevi',
    leerSub1: 'Un romanzo breve per iniziare',
    leerSub2: 'Un saggio breve',
    leerFase2: 'Due libri in attesa da tempo',
    leerFase3: 'Chiudere con i due più lunghi',
    resumenLeer:
      'Ventisei settimane, un libro al mese: due brevi per prendere il ritmo, due di quelli che aspettano da tempo e i due più lunghi alla fine, quando l\'abitudine sarà ormai presa.',
    refresco: 'Niente bibite gassate in settimana',
    pasoRefresco1: 'Sostituirle con acqua e limone',
    pasoRefresco2: 'Resistere 30 giorni di fila',
    notaRefresco: 'Obiettivo raggiunto: ora solo nel fine settimana, e non mancano nemmeno.',
    planA: 'Piano A',
  },
  nl: {
    correr: '5 km hardlopen zonder te stoppen',
    notaCorrer: 'Drie keer per week, zonder haast: eerst volhouden, dan verlengen.',
    fase1: 'Wandelen en joggen afwisselen',
    fase2: '20 minuten aan één stuk joggen',
    fase3: 'De volle 5 km halen',
    resumenCorrer:
      'Acht weken in drie fases: wandelen en joggen afwisselen tot het makkelijk gaat, twintig minuten doorjoggen en tot slot de afstand opbouwen tot 5 km.',
    leer: 'Dit semester 6 boeken lezen',
    pasoLeer1: 'De zes boeken kiezen',
    pasoLeer2: '20 minuten vrijmaken voor het slapengaan',
    leerFase1: 'In het ritme komen met twee korte boeken',
    leerSub1: 'Een korte roman om mee te beginnen',
    leerSub2: 'Een beknopt essay',
    leerFase2: 'Twee boeken die al lang liggen te wachten',
    leerFase3: 'Afsluiten met de twee dikste',
    resumenLeer:
      'Zesentwintig weken, één boek per maand: twee korte om in het ritme te komen, twee die al lang liggen te wachten en de twee dikste aan het eind, als de gewoonte er eenmaal in zit.',
    refresco: 'Doordeweeks geen frisdrank',
    pasoRefresco1: 'Vervangen door water met citroen',
    pasoRefresco2: '30 dagen achter elkaar volhouden',
    notaRefresco: 'Gelukt: nu alleen nog in het weekend, en het wordt niet eens gemist.',
    planA: 'Plan A',
  },
  pl: {
    correr: 'Przebiec 5 km bez zatrzymywania się',
    notaCorrer: 'Trzy wyjścia w tygodniu, bez pośpiechu: najpierw wytrzymałość, potem dystans.',
    fase1: 'Przeplatać marsz i trucht',
    fase2: 'Truchtać 20 minut bez przerwy',
    fase3: 'Pokonać pełne 5 km',
    resumenCorrer:
      'Osiem tygodni w trzech etapach: przeplatać marsz i trucht, aż przestanie być ciężko, utrzymać dwudziestominutowy trucht, a na koniec wydłużyć dystans do 5 km.',
    leer: 'Przeczytać 6 książek w tym semestrze',
    pasoLeer1: 'Wybrać sześć książek',
    pasoLeer2: 'Zarezerwować 20 minut przed snem',
    leerFase1: 'Złapać rytm na dwóch krótkich książkach',
    leerSub1: 'Krótka powieść na początek',
    leerSub2: 'Krótki esej',
    leerFase2: 'Dwie książki, które długo czekają',
    leerFase3: 'Zakończyć dwiema najdłuższymi',
    resumenLeer:
      'Dwadzieścia sześć tygodni, jedna książka na miesiąc: dwie krótkie na złapanie rytmu, dwie z tych, które długo czekają, i dwie najdłuższe na koniec, gdy nawyk będzie już utrwalony.',
    refresco: 'Rzucić napoje gazowane w tygodniu',
    pasoRefresco1: 'Zastąpić je wodą z cytryną',
    pasoRefresco2: 'Wytrwać 30 dni z rzędu',
    notaRefresco: 'Cel osiągnięty: teraz tylko w weekendy i wcale ich nie brakuje.',
    planA: 'Plan A',
  },
  tr: {
    correr: 'Durmadan 5 km koşmak',
    notaCorrer: 'Haftada üç koşu, acele etmeden: önce dayanıklılık, sonra mesafe.',
    fase1: 'Yürüyüş ve hafif koşuyu dönüşümlü yapmak',
    fase2: '20 dakika aralıksız koşmak',
    fase3: '5 km\'yi tamamlamak',
    resumenCorrer:
      'Üç aşamada sekiz hafta: zorlanmayana kadar yürüyüş ve hafif koşuyu dönüşümlü yapmak, yirmi dakika aralıksız koşabilmek ve son olarak mesafeyi 5 km\'ye çıkarmak.',
    leer: 'Bu dönem 6 kitap okumak',
    pasoLeer1: 'Altı kitabı seçmek',
    pasoLeer2: 'Uyumadan önce 20 dakika ayırmak',
    leerFase1: 'İki kısa kitapla ritim yakalamak',
    leerSub1: 'Başlangıç için kısa bir roman',
    leerSub2: 'Kısa bir deneme',
    leerFase2: 'Uzun süredir bekleyen iki kitap',
    leerFase3: 'En uzun ikisiyle bitirmek',
    resumenLeer:
      'Yirmi altı hafta, ayda bir kitap: ritim yakalamak için iki kısa kitap, uzun süredir bekleyen iki kitap ve alışkanlık oturduğunda en sona en uzun iki kitap.',
    refresco: 'Hafta içi gazlı içeceği bırakmak',
    pasoRefresco1: 'Yerine limonlu su içmek',
    pasoRefresco2: '30 gün üst üste dayanmak',
    notaRefresco: 'Tamamlandı: artık sadece hafta sonları, üstelik hiç aranmıyor.',
    planA: 'Plan A',
  },
  id: {
    correr: 'Lari 5 km tanpa berhenti',
    notaCorrer: 'Tiga kali lari seminggu, tanpa terburu-buru: tahan dulu, baru tambah jarak.',
    fase1: 'Selang-seling jalan kaki dan joging',
    fase2: 'Joging 20 menit tanpa henti',
    fase3: 'Menuntaskan 5 km',
    resumenCorrer:
      'Delapan minggu dalam tiga fase: selang-seling jalan kaki dan joging sampai terasa ringan, bertahan joging dua puluh menit, lalu menambah jarak sampai 5 km.',
    leer: 'Membaca 6 buku semester ini',
    pasoLeer1: 'Memilih enam bukunya',
    pasoLeer2: 'Menyisihkan 20 menit sebelum tidur',
    leerFase1: 'Membangun ritme dengan dua buku tipis',
    leerSub1: 'Novel pendek sebagai pembuka',
    leerSub2: 'Satu buku esai singkat',
    leerFase2: 'Dua buku yang sudah lama menunggu',
    leerFase3: 'Menutup dengan dua buku paling tebal',
    resumenLeer:
      'Dua puluh enam minggu, satu buku per bulan: dua buku tipis untuk membangun ritme, dua yang sudah lama menunggu, dan dua paling tebal di akhir, saat kebiasaannya sudah terbentuk.',
    refresco: 'Berhenti minum soda di hari kerja',
    pasoRefresco1: 'Menggantinya dengan air lemon',
    pasoRefresco2: 'Bertahan 30 hari berturut-turut',
    notaRefresco: 'Tercapai: sekarang hanya di akhir pekan, dan sama sekali tidak dirindukan.',
    planA: 'Rencana A',
  },
  ja: {
    correr: '5kmを止まらずに走る',
    notaCorrer: '週3回、焦らずに。まずは走り続けられるように、それから距離を伸ばす。',
    fase1: 'ウォーキングとジョギングを交互に',
    fase2: '20分間続けてジョギング',
    fase3: '5kmを走り切る',
    resumenCorrer:
      '8週間を3つのフェーズで。楽になるまでウォーキングとジョギングを交互に行い、20分間ジョギングを続けられるようにし、最後に距離を5kmまで伸ばします。',
    leer: '今学期に本を6冊読む',
    pasoLeer1: '読む6冊を選ぶ',
    pasoLeer2: '寝る前の20分を確保する',
    leerFase1: '短い本2冊でリズムをつかむ',
    leerSub1: 'まずは短い小説を1冊',
    leerSub2: '短めのエッセイを1冊',
    leerFase2: 'ずっと積んでいた2冊',
    leerFase3: '最後は長い2冊で締めくくる',
    resumenLeer:
      '26週間、月に1冊。リズムをつかむための短い本を2冊、ずっと積んでいた本を2冊、そして習慣が身についた最後に長い本を2冊。',
    refresco: '平日は炭酸飲料をやめる',
    pasoRefresco1: 'レモン水に置き換える',
    pasoRefresco2: '30日間続ける',
    notaRefresco: '達成。今は週末だけで、特に恋しくもならない。',
    planA: 'プランA',
  },
  zh: {
    correr: '不停歇地跑完5公里',
    notaCorrer: '每周跑三次，不着急：先坚持下来，再加长距离。',
    fase1: '快走和慢跑交替',
    fase2: '连续慢跑20分钟',
    fase3: '跑完5公里',
    resumenCorrer:
      '八周分三个阶段：先快走和慢跑交替，直到不再吃力；再坚持连续慢跑二十分钟；最后把距离加到5公里。',
    leer: '这学期读完6本书',
    pasoLeer1: '选好要读的六本书',
    pasoLeer2: '睡前留出20分钟',
    leerFase1: '用两本薄书找到节奏',
    leerSub1: '先读一本短篇小说',
    leerSub2: '一本短小的散文集',
    leerFase2: '两本搁置已久的书',
    leerFase3: '最后读完最厚的两本',
    resumenLeer:
      '二十六周，每月一本：先用两本薄书找到节奏，再读两本搁置已久的书，等习惯养成后，最后读最厚的两本。',
    refresco: '工作日不喝汽水',
    pasoRefresco1: '换成柠檬水',
    pasoRefresco2: '连续坚持30天',
    notaRefresco: '已完成：现在只在周末喝，而且一点也不想念。',
    planA: '计划A',
  },
  ko: {
    correr: '쉬지 않고 5km 달리기',
    notaCorrer: '일주일에 세 번, 서두르지 않고: 먼저 버티고, 그다음 거리를 늘리기.',
    fase1: '걷기와 조깅 번갈아 하기',
    fase2: '20분 연속 조깅하기',
    fase3: '5km 완주하기',
    resumenCorrer:
      '8주를 세 단계로: 편해질 때까지 걷기와 조깅을 번갈아 하고, 20분 연속 조깅을 유지한 다음, 마지막으로 거리를 5km까지 늘립니다.',
    leer: '이번 학기에 책 6권 읽기',
    pasoLeer1: '읽을 책 여섯 권 고르기',
    pasoLeer2: '자기 전 20분 확보하기',
    leerFase1: '얇은 책 두 권으로 리듬 잡기',
    leerSub1: '시작은 짧은 소설 한 권',
    leerSub2: '짧은 에세이 한 권',
    leerFase2: '오래 미뤄 둔 책 두 권',
    leerFase3: '가장 두꺼운 두 권으로 마무리',
    resumenLeer:
      '26주 동안 한 달에 한 권: 리듬을 잡을 얇은 책 두 권, 오래 미뤄 둔 책 두 권, 그리고 습관이 자리 잡은 마지막에 가장 두꺼운 두 권.',
    refresco: '평일에는 탄산음료 끊기',
    pasoRefresco1: '레몬물로 바꾸기',
    pasoRefresco2: '30일 연속 버티기',
    notaRefresco: '달성: 이제 주말에만 마시고, 딱히 생각나지도 않는다.',
    planA: '계획 A',
  },
  ru: {
    correr: 'Пробежать 5 км без остановки',
    notaCorrer: 'Три пробежки в неделю, без спешки: сначала выносливость, потом дистанция.',
    fase1: 'Чередовать ходьбу и лёгкий бег',
    fase2: 'Бежать 20 минут без остановки',
    fase3: 'Пробежать все 5 км',
    resumenCorrer:
      'Восемь недель в три этапа: чередовать ходьбу и лёгкий бег, пока это не станет легко, продержаться двадцать минут бега и в конце увеличить дистанцию до 5 км.',
    leer: 'Прочитать 6 книг за семестр',
    pasoLeer1: 'Выбрать шесть книг',
    pasoLeer2: 'Выделить 20 минут перед сном',
    leerFase1: 'Войти в ритм с двумя короткими книгами',
    leerSub1: 'Для начала — короткий роман',
    leerSub2: 'Небольшое эссе',
    leerFase2: 'Две книги, которые давно ждут своей очереди',
    leerFase3: 'Закончить двумя самыми длинными',
    resumenLeer:
      'Двадцать шесть недель, по книге в месяц: две короткие, чтобы войти в ритм, две из тех, что давно ждут, и две самые длинные в конце, когда привычка уже сложится.',
    refresco: 'Отказаться от газировки в будни',
    pasoRefresco1: 'Заменить её водой с лимоном',
    pasoRefresco2: 'Продержаться 30 дней подряд',
    notaRefresco: 'Выполнено: теперь только по выходным, и совсем не тянет.',
    planA: 'План A',
  },
  hi: {
    correr: 'बिना रुके 5 किमी दौड़ना',
    notaCorrer: 'हफ़्ते में तीन बार, बिना जल्दबाज़ी के: पहले टिके रहना, फिर दूरी बढ़ाना।',
    fase1: 'पैदल चलना और जॉगिंग बारी-बारी से',
    fase2: 'लगातार 20 मिनट जॉगिंग',
    fase3: 'पूरे 5 किमी पूरे करना',
    resumenCorrer:
      'तीन चरणों में आठ हफ़्ते: जब तक आसान न लगे, पैदल चलना और जॉगिंग बारी-बारी से करना, फिर बीस मिनट लगातार जॉगिंग करना, और आख़िर में दूरी बढ़ाकर 5 किमी तक ले जाना।',
    leer: 'इस सेमेस्टर में 6 किताबें पढ़ना',
    pasoLeer1: 'छह किताबें चुनना',
    pasoLeer2: 'सोने से पहले 20 मिनट निकालना',
    leerFase1: 'दो छोटी किताबों से लय बनाना',
    leerSub1: 'शुरुआत के लिए एक छोटा उपन्यास',
    leerSub2: 'एक छोटा निबंध-संग्रह',
    leerFase2: 'लंबे समय से इंतज़ार कर रही दो किताबें',
    leerFase3: 'सबसे लंबी दो किताबों से समापन',
    resumenLeer:
      'छब्बीस हफ़्ते, हर महीने एक किताब: लय बनाने के लिए दो छोटी किताबें, दो जो लंबे समय से इंतज़ार कर रही हैं, और आख़िर में सबसे लंबी दो, जब आदत पक्की हो जाए।',
    refresco: 'हफ़्ते के दिनों में कोल्ड ड्रिंक छोड़ना',
    pasoRefresco1: 'उसकी जगह नींबू पानी पीना',
    pasoRefresco2: 'लगातार 30 दिन टिके रहना',
    notaRefresco: 'लक्ष्य पूरा: अब सिर्फ़ वीकेंड पर, और उसकी याद भी नहीं आती।',
    planA: 'योजना A',
  },
  ar: {
    correr: 'الجري 5 كم دون توقف',
    notaCorrer: 'ثلاث مرات في الأسبوع، بلا عجلة: الصمود أولًا، ثم زيادة المسافة.',
    fase1: 'التناوب بين المشي والهرولة',
    fase2: 'الهرولة 20 دقيقة متواصلة',
    fase3: 'إكمال الـ5 كم',
    resumenCorrer:
      'ثمانية أسابيع على ثلاث مراحل: التناوب بين المشي والهرولة حتى يصبح الأمر سهلًا، ثم الهرولة عشرين دقيقة متواصلة، وأخيرًا زيادة المسافة حتى 5 كم.',
    leer: 'قراءة 6 كتب هذا الفصل الدراسي',
    pasoLeer1: 'اختيار الكتب الستة',
    pasoLeer2: 'تخصيص 20 دقيقة قبل النوم',
    leerFase1: 'اكتساب الإيقاع بكتابين قصيرين',
    leerSub1: 'رواية قصيرة للبداية',
    leerSub2: 'كتاب مقالات قصير',
    leerFase2: 'كتابان مؤجلان منذ وقت طويل',
    leerFase3: 'الختام بأطول كتابين',
    resumenLeer:
      'ستة وعشرون أسبوعًا، كتاب كل شهر: كتابان قصيران لاكتساب الإيقاع، وكتابان مؤجلان منذ وقت طويل، وأطول كتابين في النهاية حين تكون العادة قد ترسخت.',
    refresco: 'ترك المشروبات الغازية في أيام العمل',
    pasoRefresco1: 'استبدالها بماء بالليمون',
    pasoRefresco2: 'الصمود 30 يومًا متتالية',
    notaRefresco: 'تحقق الهدف: الآن في عطلة نهاية الأسبوع فقط، ولا تُفتقد أصلًا.',
    planA: 'خطة A',
  },
}
