/**
 * Datos y matemática pura de la Montaña de Sísifo (gamificación anual).
 *
 * Temática: materiales de la tierra. Se asciende "excavando" de la arcilla en la
 * superficie hasta el diamante en la cima. Todo el progreso se deriva de un solo
 * número, `altura` (0–365 días subidos): ver core/gamificacion/sisifo.ts.
 *
 * Los nombres/temas son un catálogo temático extenso (12 + 52·2 textos), así que
 * viven por idioma aquí en vez de inflar `dict.ts` (como los catálogos de datos).
 * La cromática por material da la identidad visual sin pedir 64 iconos únicos.
 *
 * Cada entrada ES un `PorIdioma<string>`: el español es obligatorio y los demás
 * idiomas son campos opcionales que se van añadiendo al traducir.
 */

import { porIdioma, type PorIdioma } from '../i18n/porIdioma'

export const DIAS_META = 365
export const SEMANAS = 52
export const DIAS_POR_SEMANA = 7
/** Días de gracia (fallos sin castigo) por mes calendario. */
export const GRACIAS_MES = 2

export interface Rango extends PorIdioma<string> {
  /** 1–12. */
  n: number
  /** Tono del estrato (base terroso → precioso). */
  color: string
}

/** Los 12 rangos, de la base a la cima. Semanas acumuladas al final de cada uno. */
export const RANGOS: Rango[] = [
  {
    n: 1,
    es: 'Explorador de Arcilla',
    en: 'Clay Explorer',
    pt: 'Explorador de Argila',
    fr: 'Explorateur d’Argile',
    de: 'Lehm-Entdecker',
    it: 'Esploratore d’Argilla',
    ja: '粘土の探検者',
    zh: '黏土探索者',
    ko: '점토 탐험가',
    ru: 'Глиняный исследователь',
    hi: 'मिट्टी का अन्वेषक',
    tr: 'Kil Kâşifi',
    id: 'Penjelajah Tanah Liat',
    pl: 'Odkrywca gliny',
    nl: 'Klei-ontdekker',
    ar: 'مستكشف الطين',
    color: '#b5651d',
  },
  {
    n: 2,
    es: 'Viajero de Pizarra',
    en: 'Slate Traveler',
    pt: 'Viajante de Ardósia',
    fr: 'Voyageur d’Ardoise',
    de: 'Schiefer-Reisender',
    it: 'Viaggiatore d’Ardesia',
    ja: '粘板岩の旅人',
    zh: '板岩旅人',
    ko: '점판암 여행자',
    ru: 'Странник по сланцу',
    hi: 'स्लेट का यात्री',
    tr: 'Arduvaz Yolcusu',
    id: 'Pengembara Batu Sabak',
    pl: 'Wędrowiec łupków',
    nl: 'Leisteenreiziger',
    ar: 'رحّالة الأردواز',
    color: '#5a6672',
  },
  {
    n: 3,
    es: 'Caminante de Arenisca',
    en: 'Sandstone Walker',
    pt: 'Caminhante de Arenito',
    fr: 'Marcheur de Grès',
    de: 'Sandstein-Wanderer',
    it: 'Camminatore d’Arenaria',
    ja: '砂岩の踏破者',
    zh: '砂岩行者',
    ko: '사암 나그네',
    ru: 'Скиталец песчаника',
    hi: 'बलुआ पत्थर का पथिक',
    tr: 'Kumtaşı Gezgini',
    id: 'Pejalan Batu Pasir',
    pl: 'Piechur piaskowca',
    nl: 'Zandsteenwandelaar',
    ar: 'سائر الحجر الرملي',
    color: '#c2a878',
  },
  {
    n: 4,
    es: 'Rastreador de Granito',
    en: 'Granite Tracker',
    pt: 'Rastreador de Granito',
    fr: 'Pisteur de Granit',
    de: 'Granit-Späher',
    it: 'Segugio di Granito',
    ja: '花崗岩の追跡者',
    zh: '花岗岩追踪者',
    ko: '화강암 추적자',
    ru: 'Гранитный следопыт',
    hi: 'ग्रेनाइट का खोजी',
    tr: 'Granit İzcisi',
    id: 'Pelacak Granit',
    pl: 'Tropiciel granitu',
    nl: 'Granietspeurder',
    ar: 'متعقّب الغرانيت',
    color: '#7d7d7d',
  },
  {
    n: 5,
    es: 'Pionero de Obsidiana',
    en: 'Obsidian Pioneer',
    pt: 'Pioneiro da Obsidiana',
    fr: 'Pionnier de l’Obsidienne',
    de: 'Obsidian-Pionier',
    it: 'Pioniere dell’Ossidiana',
    ja: '黒曜石の開拓者',
    zh: '黑曜石先驱',
    ko: '흑요석 개척자',
    ru: 'Обсидиановый первопроходец',
    hi: 'ओब्सीडियन का अग्रदूत',
    tr: 'Obsidyen Öncüsü',
    id: 'Perintis Obsidian',
    pl: 'Pionier obsydianu',
    nl: 'Obsidiaanpionier',
    ar: 'رائد السَّبَج',
    color: '#2b2b33',
  },
  {
    n: 6,
    es: 'Navegante de Cobre',
    en: 'Copper Navigator',
    pt: 'Navegante de Cobre',
    fr: 'Navigateur de Cuivre',
    de: 'Kupfer-Navigator',
    it: 'Navigatore di Rame',
    ja: '銅の航海者',
    zh: '赤铜领航者',
    ko: '구리 항해자',
    ru: 'Медный штурман',
    hi: 'तांबे का नाविक',
    tr: 'Bakır Kılavuzu',
    id: 'Nakhoda Tembaga',
    pl: 'Żeglarz miedzi',
    nl: 'Kopernavigator',
    ar: 'ملّاح النحاس',
    color: '#b87333',
  },
  {
    n: 7,
    es: 'Buscador de Bronce',
    en: 'Bronze Seeker',
    pt: 'Buscador de Bronze',
    fr: 'Chercheur de Bronze',
    de: 'Bronze-Sucher',
    it: 'Cercatore di Bronzo',
    ja: '青銅の探求者',
    zh: '青铜寻宝者',
    ko: '청동 탐색자',
    ru: 'Бронзовый искатель',
    hi: 'कांस्य का साधक',
    tr: 'Tunç Arayıcısı',
    id: 'Pencari Perunggu',
    pl: 'Poszukiwacz brązu',
    nl: 'Bronszoeker',
    ar: 'منقّب البرونز',
    color: '#8c6d3f',
  },
  {
    n: 8,
    es: 'Aventurero de Plata',
    en: 'Silver Adventurer',
    pt: 'Aventureiro de Prata',
    fr: 'Aventurier d’Argent',
    de: 'Silber-Abenteurer',
    it: 'Avventuriero d’Argento',
    ja: '銀の冒険者',
    zh: '白银冒险者',
    ko: '은빛 모험가',
    ru: 'Серебряный смельчак',
    hi: 'चांदी का साहसी',
    tr: 'Gümüş Maceracısı',
    id: 'Petualang Perak',
    pl: 'Śmiałek srebra',
    nl: 'Zilveravonturier',
    ar: 'مغامر الفضة',
    color: '#c0c0c8',
  },
  {
    n: 9,
    es: 'Conquistador de Oro',
    en: 'Gold Conqueror',
    pt: 'Conquistador de Ouro',
    fr: 'Conquérant d’Or',
    de: 'Gold-Eroberer',
    it: 'Conquistatore d’Oro',
    ja: '金の征服者',
    zh: '黄金征服者',
    ko: '황금 정복자',
    ru: 'Золотой покоритель',
    hi: 'स्वर्ण का विजेता',
    tr: 'Altın Fatihi',
    id: 'Penakluk Emas',
    pl: 'Zdobywca złota',
    nl: 'Goudveroveraar',
    ar: 'فاتح الذهب',
    color: '#d4af37',
  },
  {
    n: 10,
    es: 'Guardián de Platino',
    en: 'Platinum Guardian',
    pt: 'Guardião de Platina',
    fr: 'Gardien de Platine',
    de: 'Platin-Wächter',
    it: 'Guardiano di Platino',
    ja: '白金の守護者',
    zh: '铂金守护者',
    ko: '백금 수호자',
    ru: 'Платиновый страж',
    hi: 'प्लैटिनम का प्रहरी',
    tr: 'Platin Muhafızı',
    id: 'Penjaga Platina',
    pl: 'Strażnik platyny',
    nl: 'Platinawachter',
    ar: 'حارس البلاتين',
    color: '#b6c1c7',
  },
  {
    n: 11,
    es: 'Maestro de Esmeralda',
    en: 'Emerald Master',
    pt: 'Mestre da Esmeralda',
    fr: 'Maître de l’Émeraude',
    de: 'Smaragd-Meister',
    it: 'Maestro dello Smeraldo',
    ja: 'エメラルドの達人',
    zh: '祖母绿大师',
    ko: '에메랄드 명인',
    ru: 'Изумрудный мастер',
    hi: 'पन्ने का उस्ताद',
    tr: 'Zümrüt Ustası',
    id: 'Empu Zamrud',
    pl: 'Mistrz szmaragdu',
    nl: 'Smaragdmeester',
    ar: 'سيّد الزمرد',
    color: '#2e8b57',
  },
  {
    n: 12,
    es: 'Leyenda de Diamante',
    en: 'Diamond Legend',
    pt: 'Lenda de Diamante',
    fr: 'Légende de Diamant',
    de: 'Diamant-Legende',
    it: 'Leggenda di Diamante',
    ja: 'ダイヤモンドの伝説',
    zh: '钻石传奇',
    ko: '다이아몬드 전설',
    ru: 'Алмазная легенда',
    hi: 'हीरे की किंवदंती',
    tr: 'Elmas Efsanesi',
    id: 'Legenda Berlian',
    pl: 'Legenda diamentu',
    nl: 'Diamantlegende',
    ar: 'أسطورة الألماس',
    color: '#7fd8ff',
  },
]

/**
 * Semanas acumuladas al FINAL de cada rango (distribución 5-4-4-5-4-4-5-4-4-5-4-4 = 52).
 * `altura` en días cruza `limite·7` para subir de rango. Exportado: la montaña
 * del overlay dibuja un escalón de color por rango usando estos mismos límites.
 */
export const LIMITES_SEMANA = [5, 9, 13, 18, 22, 26, 31, 35, 39, 44, 48, 52]

export interface CategoriaInsignia extends PorIdioma<string> {
  color: string
  /** Rango de números de insignia [desde, hasta] (1-indexado, inclusivo). */
  desde: number
  hasta: number
}

/** Las 5 familias geológicas: solo agrupan la rejilla de insignias visualmente. */
export const CATEGORIAS: CategoriaInsignia[] = [
  {
    es: 'Tierras y Sedimentos',
    en: 'Earth & Sediments',
    pt: 'Terras e Sedimentos',
    fr: 'Terres et Sédiments',
    de: 'Erde & Sedimente',
    it: 'Terre e Sedimenti',
    ja: '土と堆積物',
    zh: '土壤与沉积物',
    ko: '흙과 퇴적물',
    ru: 'Земли и осадочные породы',
    hi: 'मिट्टी और तलछट',
    tr: 'Topraklar ve Tortular',
    id: 'Tanah dan Sedimen',
    pl: 'Ziemie i osady',
    nl: 'Aarde & sedimenten',
    ar: 'التربة والرواسب',
    color: '#b5651d',
    desde: 1,
    hasta: 10,
  },
  {
    es: 'Rocas y Formaciones Volcánicas',
    en: 'Volcanic Rocks & Formations',
    pt: 'Rochas e Formações Vulcânicas',
    fr: 'Roches et Formations Volcaniques',
    de: 'Vulkangestein & Formationen',
    it: 'Rocce e Formazioni Vulcaniche',
    ja: '火山の岩と地形',
    zh: '火山岩与地貌',
    ko: '화산암과 지형',
    ru: 'Вулканические породы и формации',
    hi: 'ज्वालामुखी चट्टानें और संरचनाएँ',
    tr: 'Volkanik Kayalar ve Oluşumlar',
    id: 'Batuan dan Bentukan Vulkanik',
    pl: 'Skały i formacje wulkaniczne',
    nl: 'Vulkanisch gesteente & formaties',
    ar: 'الصخور والتشكيلات البركانية',
    color: '#a13d2d',
    desde: 11,
    hasta: 20,
  },
  {
    es: 'Minerales y Cristales Base',
    en: 'Base Minerals & Crystals',
    pt: 'Minerais e Cristais Base',
    fr: 'Minéraux et Cristaux de Base',
    de: 'Grundminerale & Kristalle',
    it: 'Minerali e Cristalli Base',
    ja: '基本の鉱物と結晶',
    zh: '基础矿物与晶体',
    ko: '기본 광물과 결정',
    ru: 'Базовые минералы и кристаллы',
    hi: 'आधार खनिज और क्रिस्टल',
    tr: 'Temel Mineraller ve Kristaller',
    id: 'Mineral dan Kristal Dasar',
    pl: 'Minerały i kryształy podstawowe',
    nl: 'Basismineralen & kristallen',
    ar: 'المعادن والبلورات الأساسية',
    color: '#8a7fb5',
    desde: 21,
    hasta: 31,
  },
  {
    es: 'Metales y Aleaciones',
    en: 'Metals & Alloys',
    pt: 'Metais e Ligas',
    fr: 'Métaux et Alliages',
    de: 'Metalle & Legierungen',
    it: 'Metalli e Leghe',
    ja: '金属と合金',
    zh: '金属与合金',
    ko: '금속과 합금',
    ru: 'Металлы и сплавы',
    hi: 'धातुएँ और मिश्रधातुएँ',
    tr: 'Metaller ve Alaşımlar',
    id: 'Logam dan Paduan',
    pl: 'Metale i stopy',
    nl: 'Metalen & legeringen',
    ar: 'الفلزات والسبائك',
    color: '#c9a227',
    desde: 32,
    hasta: 41,
  },
  {
    es: 'Gemas y Materiales Preciosos',
    en: 'Gems & Precious Materials',
    pt: 'Gemas e Materiais Preciosos',
    fr: 'Gemmes et Matières Précieuses',
    de: 'Edelsteine & Kostbarkeiten',
    it: 'Gemme e Materiali Preziosi',
    ja: '宝石と貴重な素材',
    zh: '宝石与珍贵材料',
    ko: '보석과 귀한 재료',
    ru: 'Самоцветы и драгоценные материалы',
    hi: 'रत्न और बहुमूल्य पदार्थ',
    tr: 'Değerli Taşlar ve Kıymetli Maddeler',
    id: 'Permata dan Bahan Berharga',
    pl: 'Klejnoty i materiały szlachetne',
    nl: 'Edelstenen & kostbaarheden',
    ar: 'الأحجار الكريمة والمواد الثمينة',
    color: '#2fa4a4',
    desde: 42,
    hasta: 52,
  },
]

export interface Insignia extends PorIdioma<string> {
  /** 1–52 (se gana en la semana N del ascenso). */
  n: number
  /** Por qué se gana, aparte porque es una segunda cadena localizable. */
  desc: PorIdioma<string>
}

/** Las 52 insignias, una por semana, en orden de ascenso. */
export const INSIGNIAS: Insignia[] = [
  // Tierras y Sedimentos
  {
    n: 1,
    es: 'Huella de Barro',
    en: 'Mud Print',
    pt: 'Pegada de Barro',
    fr: 'Empreinte de Boue',
    de: 'Schlammabdruck',
    it: 'Impronta di Fango',
    ja: '泥の足跡',
    zh: '泥泞足迹',
    ko: '진흙 발자국',
    ru: 'Отпечаток в грязи',
    hi: 'कीचड़ की छाप',
    tr: 'Çamur İzi',
    id: 'Jejak Lumpur',
    pl: 'Odcisk w błocie',
    nl: 'Modderafdruk',
    ar: 'أثر في الطين',
    desc: {
      es: 'Por dar el primer paso.',
      en: 'For taking the first step.',
      pt: 'Por dar o primeiro passo.',
      fr: 'Pour avoir fait le premier pas.',
      de: 'Für den ersten Schritt.',
      it: 'Per aver fatto il primo passo.',
      ja: '最初の一歩を踏み出しました。',
      zh: '迈出了第一步。',
      ko: '첫걸음을 내디뎠어요.',
      ru: 'За первый шаг.',
      hi: 'पहला कदम उठाने के लिए।',
      tr: 'İlk adımı attığın için.',
      id: 'Karena mengambil langkah pertama.',
      pl: 'Za pierwszy krok.',
      nl: 'Voor de eerste stap.',
      ar: 'لخطوتك الأولى.',
    },
  },
  {
    n: 2,
    es: 'Sello de Terracota',
    en: 'Terracotta Seal',
    pt: 'Selo de Terracota',
    fr: 'Sceau de Terre Cuite',
    de: 'Terrakotta-Siegel',
    it: 'Sigillo di Terracotta',
    ja: 'テラコッタの印',
    zh: '陶土印章',
    ko: '테라코타 인장',
    ru: 'Терракотовая печать',
    hi: 'टेराकोटा की मुहर',
    tr: 'Terakota Mühür',
    id: 'Segel Terakota',
    pl: 'Pieczęć z terakoty',
    nl: 'Terracottazegel',
    ar: 'ختم التراكوتا',
    desc: {
      es: 'Por consolidar los primeros hallazgos.',
      en: 'For consolidating your first finds.',
      pt: 'Por consolidar os primeiros achados.',
      fr: 'Pour avoir consolidé tes premières trouvailles.',
      de: 'Fürs Festigen deiner ersten Funde.',
      it: 'Per aver consolidato le prime scoperte.',
      ja: '最初の発見を確かなものにしました。',
      zh: '巩固了最初的发现。',
      ko: '첫 발견을 단단히 다졌어요.',
      ru: 'За закрепление первых находок.',
      hi: 'पहली खोजों को पक्का करने के लिए।',
      tr: 'İlk buluntularını sağlamlaştırdığın için.',
      id: 'Karena mengukuhkan temuan pertamamu.',
      pl: 'Za utrwalenie pierwszych znalezisk.',
      nl: 'Voor het vastleggen van je eerste vondsten.',
      ar: 'لترسيخ أولى اكتشافاتك.',
    },
  },
  {
    n: 3,
    es: 'Bloque de Adobe',
    en: 'Adobe Block',
    pt: 'Bloco de Adobe',
    fr: 'Brique de Terre Crue',
    de: 'Lehmziegel',
    it: 'Mattone di Adobe',
    ja: '日干しレンガ',
    zh: '土坯砖',
    ko: '흙벽돌',
    ru: 'Саманный блок',
    hi: 'कच्ची ईंट',
    tr: 'Kerpiç Blok',
    id: 'Bata Lumpur',
    pl: 'Cegła z gliny',
    nl: 'Lemen blok',
    ar: 'لبنة طينية',
    desc: {
      es: 'Por construir una base sólida de actividad.',
      en: 'For building a solid base of activity.',
      pt: 'Por construir uma base sólida de atividade.',
      fr: 'Pour avoir bâti une base solide d’activité.',
      de: 'Für ein solides Fundament an Aktivität.',
      it: 'Per aver costruito una base solida di attività.',
      ja: '活動の土台をしっかり築きました。',
      zh: '打下了扎实的活动基础。',
      ko: '활동의 탄탄한 기반을 쌓았어요.',
      ru: 'За прочный фундамент активности.',
      hi: 'गतिविधि की मज़बूत नींव रखने के लिए।',
      tr: 'Sağlam bir etkinlik temeli kurduğun için.',
      id: 'Karena membangun dasar aktivitas yang kokoh.',
      pl: 'Za zbudowanie solidnej podstawy aktywności.',
      nl: 'Voor een stevige basis van activiteit.',
      ar: 'لبنائك أساسًا متينًا من النشاط.',
    },
  },
  {
    n: 4,
    es: 'Polvo de Limo',
    en: 'Silt Dust',
    pt: 'Pó de Silte',
    fr: 'Poussière de Limon',
    de: 'Schluffstaub',
    it: 'Polvere di Limo',
    ja: 'シルトの粉',
    zh: '粉砂尘',
    ko: '실트 먼지',
    ru: 'Иловая пыль',
    hi: 'गाद की धूल',
    tr: 'Silt Tozu',
    id: 'Debu Lanau',
    pl: 'Mułowy pył',
    nl: 'Siltstof',
    ar: 'غبار الغرين',
    desc: {
      es: 'Por recorrer rutas sutiles.',
      en: 'For travelling subtle routes.',
      pt: 'Por percorrer rotas sutis.',
      fr: 'Pour avoir emprunté des routes subtiles.',
      de: 'Für feine, unauffällige Wege.',
      it: 'Per aver percorso rotte sottili.',
      ja: 'かすかな道筋をたどりました。',
      zh: '走过了细微的路线。',
      ko: '눈에 띄지 않는 길을 걸었어요.',
      ru: 'За неприметные маршруты.',
      hi: 'बारीक रास्तों पर चलने के लिए।',
      tr: 'İnce yollardan geçtiğin için.',
      id: 'Karena menyusuri jalur-jalur halus.',
      pl: 'Za subtelne ścieżki.',
      nl: 'Voor de subtiele routes.',
      ar: 'لسلوكك دروبًا خفيّة.',
    },
  },
  {
    n: 5,
    es: 'Canto Rodado',
    en: 'River Pebble',
    pt: 'Seixo Rolado',
    fr: 'Galet de Rivière',
    de: 'Flusskiesel',
    it: 'Ciottolo di Fiume',
    ja: '川の小石',
    zh: '河卵石',
    ko: '강가 조약돌',
    ru: 'Речная галька',
    hi: 'नदी का गोल पत्थर',
    tr: 'Dere Çakılı',
    id: 'Kerikil Sungai',
    pl: 'Otoczak rzeczny',
    nl: 'Rivierkiezel',
    ar: 'حصاة نهرية',
    desc: {
      es: 'Por fluir y adaptarse al entorno.',
      en: 'For flowing and adapting to your surroundings.',
      pt: 'Por fluir e se adaptar ao ambiente.',
      fr: 'Pour avoir suivi le courant et épousé le terrain.',
      de: 'Fürs Mitfließen und Anpassen.',
      it: 'Per aver assecondato la corrente e l’ambiente.',
      ja: '流れに乗り、まわりに合わせました。',
      zh: '顺着水流，适应了环境。',
      ko: '흐름을 타고 주변에 맞췄어요.',
      ru: 'За умение течь и подстраиваться.',
      hi: 'बहाव के साथ ढलने के लिए।',
      tr: 'Akışa ve çevreye uyum sağladığın için.',
      id: 'Karena mengalir dan menyesuaikan diri dengan sekitar.',
      pl: 'Za płynięcie z nurtem i dopasowanie się.',
      nl: 'Voor het meestromen en aanpassen.',
      ar: 'لانسيابك وتأقلمك مع ما حولك.',
    },
  },
  {
    n: 6,
    es: 'Roca de Río',
    en: 'River Rock',
    pt: 'Rocha de Rio',
    fr: 'Roche de Rivière',
    de: 'Flussstein',
    it: 'Roccia di Fiume',
    ja: '川の岩',
    zh: '河床岩石',
    ko: '강바닥 바위',
    ru: 'Речной валун',
    hi: 'नदी की चट्टान',
    tr: 'Nehir Kayası',
    id: 'Batu Sungai',
    pl: 'Rzeczny głaz',
    nl: 'Rivierrots',
    ar: 'صخرة النهر',
    desc: {
      es: 'Por la constancia en el movimiento.',
      en: 'For steady, constant movement.',
      pt: 'Pela constância no movimento.',
      fr: 'Pour la constance dans le mouvement.',
      de: 'Für Beständigkeit in Bewegung.',
      it: 'Per la costanza nel movimento.',
      ja: '動きを絶やさず続けました。',
      zh: '在移动中保持了恒心。',
      ko: '꾸준한 움직임을 이어갔어요.',
      ru: 'За постоянство в движении.',
      hi: 'गति में निरंतरता के लिए।',
      tr: 'Hareketteki istikrarın için.',
      id: 'Karena tekun bergerak terus.',
      pl: 'Za wytrwałość w ruchu.',
      nl: 'Voor de standvastigheid in beweging.',
      ar: 'لثباتك في الحركة.',
    },
  },
  {
    n: 7,
    es: 'Cristal de Sal',
    en: 'Salt Crystal',
    pt: 'Cristal de Sal',
    fr: 'Cristal de Sel',
    de: 'Salzkristall',
    it: 'Cristallo di Sale',
    ja: '塩の結晶',
    zh: '盐晶',
    ko: '소금 결정',
    ru: 'Кристалл соли',
    hi: 'नमक का क्रिस्टल',
    tr: 'Tuz Kristali',
    id: 'Kristal Garam',
    pl: 'Kryształ soli',
    nl: 'Zoutkristal',
    ar: 'بلورة ملح',
    desc: {
      es: 'Por extraer valor de lo cotidiano.',
      en: 'For extracting value from the everyday.',
      pt: 'Por extrair valor do cotidiano.',
      fr: 'Pour avoir tiré de la valeur du quotidien.',
      de: 'Für den Wert im Alltäglichen.',
      it: 'Per aver estratto valore dal quotidiano.',
      ja: '日々の暮らしから価値を取り出しました。',
      zh: '从日常中提炼出价值。',
      ko: '일상에서 가치를 캐냈어요.',
      ru: 'За ценность, добытую из будней.',
      hi: 'रोज़मर्रा से मूल्य निकालने के लिए।',
      tr: 'Sıradan günlerden değer çıkardığın için.',
      id: 'Karena memetik nilai dari hal sehari-hari.',
      pl: 'Za wartość wydobytą z codzienności.',
      nl: 'Voor de waarde uit het alledaagse.',
      ar: 'لاستخراجك قيمةً من يومك العادي.',
    },
  },
  {
    n: 8,
    es: 'Estrato de Tiza',
    en: 'Chalk Stratum',
    pt: 'Estrato de Giz',
    fr: 'Strate de Craie',
    de: 'Kreideschicht',
    it: 'Strato di Gesso',
    ja: '白亜の地層',
    zh: '白垩层',
    ko: '백악 지층',
    ru: 'Меловой пласт',
    hi: 'खड़िया की परत',
    tr: 'Tebeşir Katmanı',
    id: 'Lapisan Kapur',
    pl: 'Warstwa kredy',
    nl: 'Krijtlaag',
    ar: 'طبقة طباشيرية',
    desc: {
      es: 'Por dejar una marca visible.',
      en: 'For leaving a visible mark.',
      pt: 'Por deixar uma marca visível.',
      fr: 'Pour avoir laissé une marque visible.',
      de: 'Für eine sichtbare Spur.',
      it: 'Per aver lasciato un segno visibile.',
      ja: '目に見える跡を残しました。',
      zh: '留下了看得见的痕迹。',
      ko: '눈에 보이는 자국을 남겼어요.',
      ru: 'За заметный след.',
      hi: 'दिखाई देने वाला निशान छोड़ने के लिए।',
      tr: 'Görünür bir iz bıraktığın için.',
      id: 'Karena meninggalkan jejak yang terlihat.',
      pl: 'Za widoczny ślad.',
      nl: 'Voor een zichtbaar spoor.',
      ar: 'لأثرٍ ظاهر تركته.',
    },
  },
  {
    n: 9,
    es: 'Losa de Caliza',
    en: 'Limestone Slab',
    pt: 'Laje de Calcário',
    fr: 'Dalle de Calcaire',
    de: 'Kalksteinplatte',
    it: 'Lastra di Calcare',
    ja: '石灰岩の板石',
    zh: '石灰岩板',
    ko: '석회암 판석',
    ru: 'Известняковая плита',
    hi: 'चूना पत्थर की शिला',
    tr: 'Kireçtaşı Levhası',
    id: 'Lempeng Batu Kapur',
    pl: 'Płyta wapienna',
    nl: 'Kalksteenplaat',
    ar: 'لوح من الحجر الجيري',
    desc: {
      es: 'Por aguantar el paso del tiempo.',
      en: 'For enduring the passage of time.',
      pt: 'Por resistir à passagem do tempo.',
      fr: 'Pour avoir résisté au temps qui passe.',
      de: 'Fürs Standhalten gegen die Zeit.',
      it: 'Per aver retto il passare del tempo.',
      ja: '時の流れに耐えました。',
      zh: '经住了时间的流逝。',
      ko: '시간의 흐름을 견뎠어요.',
      ru: 'За стойкость перед временем.',
      hi: 'समय की मार सहने के लिए।',
      tr: 'Zamana direndiğin için.',
      id: 'Karena bertahan menghadapi waktu.',
      pl: 'Za wytrwanie próby czasu.',
      nl: 'Voor het trotseren van de tijd.',
      ar: 'لصمودك أمام الزمن.',
    },
  },
  {
    n: 10,
    es: 'Capa de Grava',
    en: 'Gravel Layer',
    pt: 'Camada de Cascalho',
    fr: 'Couche de Gravier',
    de: 'Schotterschicht',
    it: 'Strato di Ghiaia',
    ja: '砂利の層',
    zh: '砾石层',
    ko: '자갈층',
    ru: 'Слой гравия',
    hi: 'बजरी की परत',
    tr: 'Çakıl Katmanı',
    id: 'Lapisan Kerikil',
    pl: 'Warstwa żwiru',
    nl: 'Grindlaag',
    ar: 'طبقة حصى',
    desc: {
      es: 'Por superar terrenos difíciles.',
      en: 'For overcoming rough terrain.',
      pt: 'Por superar terrenos difíceis.',
      fr: 'Pour avoir franchi des terrains difficiles.',
      de: 'Für überwundenes schwieriges Gelände.',
      it: 'Per aver superato terreni difficili.',
      ja: '険しい地形を越えました。',
      zh: '越过了难行的地形。',
      ko: '험한 지형을 넘어섰어요.',
      ru: 'За преодоление трудной местности.',
      hi: 'कठिन ज़मीन पार करने के लिए।',
      tr: 'Zorlu araziyi aştığın için.',
      id: 'Karena melewati medan yang sulit.',
      pl: 'Za pokonanie trudnego terenu.',
      nl: 'Voor het overwinnen van ruw terrein.',
      ar: 'لتجاوزك أرضًا وعرة.',
    },
  },
  // Rocas y Formaciones Volcánicas
  {
    n: 11,
    es: 'Cumbre de Basalto',
    en: 'Basalt Peak',
    pt: 'Cume de Basalto',
    fr: 'Sommet de Basalte',
    de: 'Basaltgipfel',
    it: 'Vetta di Basalto',
    ja: '玄武岩の頂',
    zh: '玄武岩之巅',
    ko: '현무암 봉우리',
    ru: 'Базальтовая вершина',
    hi: 'बेसाल्ट की चोटी',
    tr: 'Bazalt Zirvesi',
    id: 'Puncak Basal',
    pl: 'Bazaltowy szczyt',
    nl: 'Basalttop',
    ar: 'قمة بازلتية',
    desc: {
      es: 'Por alcanzar un punto elevado.',
      en: 'For reaching a high point.',
      pt: 'Por alcançar um ponto elevado.',
      fr: 'Pour avoir atteint un point élevé.',
      de: 'Fürs Erreichen einer neuen Höhe.',
      it: 'Per aver raggiunto un punto elevato.',
      ja: '高みにたどり着きました。',
      zh: '抵达了一处高点。',
      ko: '높은 곳에 다다랐어요.',
      ru: 'За взятую высоту.',
      hi: 'एक ऊँचाई तक पहुँचने के लिए।',
      tr: 'Yüksek bir noktaya ulaştığın için.',
      id: 'Karena mencapai titik yang tinggi.',
      pl: 'Za zdobycie wysokiego punktu.',
      nl: 'Voor het bereiken van een hoogtepunt.',
      ar: 'لبلوغك نقطة مرتفعة.',
    },
  },
  {
    n: 12,
    es: 'Núcleo de Magma',
    en: 'Magma Core',
    pt: 'Núcleo de Magma',
    fr: 'Cœur de Magma',
    de: 'Magmakern',
    it: 'Nucleo di Magma',
    ja: 'マグマの核',
    zh: '岩浆核心',
    ko: '마그마 핵',
    ru: 'Ядро магмы',
    hi: 'मैग्मा का केंद्र',
    tr: 'Magma Çekirdeği',
    id: 'Inti Magma',
    pl: 'Jądro magmy',
    nl: 'Magmakern',
    ar: 'نواة الصهارة',
    desc: {
      es: 'Por mantener una racha ardiente.',
      en: 'For keeping a burning streak.',
      pt: 'Por manter uma sequência ardente.',
      fr: 'Pour avoir tenu une série brûlante.',
      de: 'Für eine glühende Serie.',
      it: 'Per aver tenuto viva una serie ardente.',
      ja: '燃えるような連続記録を守りました。',
      zh: '保持了火热的连续天数。',
      ko: '뜨거운 연속 기록을 이어갔어요.',
      ru: 'За пылающую серию.',
      hi: 'धधकता सिलसिला बनाए रखने के लिए।',
      tr: 'Yanan bir seriyi sürdürdüğün için.',
      id: 'Karena menjaga rentetan yang membara.',
      pl: 'Za rozpaloną passę.',
      nl: 'Voor een brandende reeks.',
      ar: 'لسلسلةٍ متّقدة حافظت عليها.',
    },
  },
  {
    n: 13,
    es: 'Piedra Pómez',
    en: 'Pumice Stone',
    pt: 'Pedra-Pomes',
    fr: 'Pierre Ponce',
    de: 'Bimsstein',
    it: 'Pietra Pomice',
    ja: '軽石',
    zh: '浮石',
    ko: '부석',
    ru: 'Пемза',
    hi: 'झांवा',
    tr: 'Sünger Taşı',
    id: 'Batu Apung',
    pl: 'Pumeks',
    nl: 'Puimsteen',
    ar: 'حجر الخفاف',
    desc: {
      es: 'Por moverse con ligereza y rapidez.',
      en: 'For moving light and fast.',
      pt: 'Por se mover com leveza e rapidez.',
      fr: 'Pour la légèreté et la vitesse.',
      de: 'Für Leichtigkeit und Tempo.',
      it: 'Per la leggerezza e la rapidità.',
      ja: '軽やかに、すばやく動きました。',
      zh: '轻盈而迅速地移动。',
      ko: '가볍고 빠르게 움직였어요.',
      ru: 'За лёгкость и быстроту.',
      hi: 'हल्केपन और तेज़ी के लिए।',
      tr: 'Hafif ve hızlı hareket ettiğin için.',
      id: 'Karena bergerak ringan dan cepat.',
      pl: 'Za lekkość i szybkość.',
      nl: 'Voor licht en snel bewegen.',
      ar: 'لخفّتك وسرعتك.',
    },
  },
  {
    n: 14,
    es: 'Ceniza Volcánica',
    en: 'Volcanic Ash',
    pt: 'Cinza Vulcânica',
    fr: 'Cendre Volcanique',
    de: 'Vulkanasche',
    it: 'Cenere Vulcanica',
    ja: '火山灰',
    zh: '火山灰',
    ko: '화산재',
    ru: 'Вулканический пепел',
    hi: 'ज्वालामुखी की राख',
    tr: 'Volkanik Kül',
    id: 'Abu Vulkanik',
    pl: 'Popiół wulkaniczny',
    nl: 'Vulkanische as',
    ar: 'رماد بركاني',
    desc: {
      es: 'Por resurgir o retomar la actividad.',
      en: 'For rising again or resuming activity.',
      pt: 'Por ressurgir e retomar a atividade.',
      fr: 'Pour avoir repris l’activité après la pause.',
      de: 'Fürs Wiederaufstehen und Weitermachen.',
      it: 'Per aver ripreso l’attività dopo la pausa.',
      ja: '灰の中からまた立ち上がりました。',
      zh: '从中断处重新出发。',
      ko: '다시 일어나 활동을 이어갔어요.',
      ru: 'За возвращение к делу после паузы.',
      hi: 'राख से फिर उठ खड़े होने के लिए।',
      tr: 'Külden yeniden doğduğun için.',
      id: 'Karena bangkit lagi dan melanjutkan.',
      pl: 'Za powrót do gry po przerwie.',
      nl: 'Voor het opstaan uit de as.',
      ar: 'لنهوضك من الرماد ومواصلتك.',
    },
  },
  {
    n: 15,
    es: 'Filo de Pedernal',
    en: 'Flint Edge',
    pt: 'Lâmina de Sílex',
    fr: 'Tranchant de Silex',
    de: 'Feuersteinklinge',
    it: 'Lama di Selce',
    ja: '火打ち石の刃',
    zh: '燧石锋刃',
    ko: '부싯돌 날',
    ru: 'Кремнёвое лезвие',
    hi: 'चकमक की धार',
    tr: 'Çakmaktaşı Ağzı',
    id: 'Mata Batu Api',
    pl: 'Krzemienne ostrze',
    nl: 'Vuurstenen snede',
    ar: 'حدّ الصوّان',
    desc: {
      es: 'Por decisiones rápidas y precisas.',
      en: 'For fast, precise decisions.',
      pt: 'Por decisões rápidas e precisas.',
      fr: 'Pour des décisions rapides et précises.',
      de: 'Für schnelle, präzise Entscheidungen.',
      it: 'Per decisioni rapide e precise.',
      ja: '素早く正確に決めました。',
      zh: '做出了迅速而准确的决定。',
      ko: '빠르고 정확하게 결정했어요.',
      ru: 'За быстрые и точные решения.',
      hi: 'तेज़ और सटीक फ़ैसलों के लिए।',
      tr: 'Hızlı ve isabetli kararların için.',
      id: 'Karena keputusan yang cepat dan tepat.',
      pl: 'Za szybkie i celne decyzje.',
      nl: 'Voor snelle, precieze beslissingen.',
      ar: 'لقراراتك السريعة الدقيقة.',
    },
  },
  {
    n: 16,
    es: 'Esquirla de Escoria',
    en: 'Slag Shard',
    pt: 'Lasca de Escória',
    fr: 'Éclat de Scorie',
    de: 'Schlackensplitter',
    it: 'Scheggia di Scoria',
    ja: 'スラグの破片',
    zh: '矿渣碎片',
    ko: '슬래그 조각',
    ru: 'Осколок шлака',
    hi: 'धातुमल का टुकड़ा',
    tr: 'Cüruf Parçası',
    id: 'Serpihan Terak',
    pl: 'Odłamek żużlu',
    nl: 'Slakscherf',
    ar: 'شظية خبث',
    desc: {
      es: 'Por limpiar y optimizar rutas.',
      en: 'For cleaning up and optimizing routes.',
      pt: 'Por limpar e otimizar rotas.',
      fr: 'Pour avoir nettoyé et optimisé tes trajets.',
      de: 'Fürs Aufräumen und Optimieren der Wege.',
      it: 'Per aver ripulito e ottimizzato i percorsi.',
      ja: '道筋を整理し、無駄を削りました。',
      zh: '清理并优化了路线。',
      ko: '경로를 정리하고 다듬었어요.',
      ru: 'За расчищенные и выверенные маршруты.',
      hi: 'रास्तों को साफ़ और बेहतर करने के लिए।',
      tr: 'Yolları temizleyip kısalttığın için.',
      id: 'Karena membersihkan dan merapikan jalur.',
      pl: 'Za oczyszczone i usprawnione trasy.',
      nl: 'Voor het opschonen en stroomlijnen van je routes.',
      ar: 'لتنظيفك الدروب وتحسينها.',
    },
  },
  {
    n: 17,
    es: 'Brecha de Toba',
    en: 'Tuff Breccia',
    pt: 'Brecha de Tufo',
    fr: 'Brèche de Tuf',
    de: 'Tuffbrekzie',
    it: 'Breccia di Tufo',
    ja: '凝灰角礫岩',
    zh: '凝灰角砾岩',
    ko: '응회 각력암',
    ru: 'Туфовая брекчия',
    hi: 'टफ़ ब्रेसिया',
    tr: 'Tüf Breşi',
    id: 'Breksi Tuf',
    pl: 'Brekcja tufowa',
    nl: 'Tufbreccie',
    ar: 'بريشيا التُّف',
    desc: {
      es: 'Por encontrar conexiones inesperadas.',
      en: 'For finding unexpected connections.',
      pt: 'Por encontrar conexões inesperadas.',
      fr: 'Pour avoir trouvé des liens inattendus.',
      de: 'Für unerwartete Verbindungen.',
      it: 'Per aver trovato connessioni inattese.',
      ja: '思いがけないつながりを見つけました。',
      zh: '找到了意想不到的联系。',
      ko: '뜻밖의 연결을 찾아냈어요.',
      ru: 'За неожиданные связи.',
      hi: 'अनपेक्षित जुड़ावों को खोजने के लिए।',
      tr: 'Beklenmedik bağlantılar bulduğun için.',
      id: 'Karena menemukan kaitan yang tak terduga.',
      pl: 'Za nieoczekiwane połączenia.',
      nl: 'Voor onverwachte verbanden.',
      ar: 'لعثورك على صلات غير متوقّعة.',
    },
  },
  {
    n: 18,
    es: 'Muro de Mármol',
    en: 'Marble Wall',
    pt: 'Muro de Mármore',
    fr: 'Mur de Marbre',
    de: 'Marmorwand',
    it: 'Muro di Marmo',
    ja: '大理石の壁',
    zh: '大理石墙',
    ko: '대리석 벽',
    ru: 'Мраморная стена',
    hi: 'संगमरमर की दीवार',
    tr: 'Mermer Duvar',
    id: 'Dinding Marmer',
    pl: 'Marmurowa ściana',
    nl: 'Marmeren muur',
    ar: 'جدار من الرخام',
    desc: {
      es: 'Por alcanzar la elegancia en el proceso.',
      en: 'For reaching elegance in the process.',
      pt: 'Por alcançar elegância no processo.',
      fr: 'Pour l’élégance atteinte en chemin.',
      de: 'Für Eleganz im Vorgehen.',
      it: 'Per l’eleganza raggiunta nel processo.',
      ja: '進み方に優雅さが宿りました。',
      zh: '让过程有了优雅。',
      ko: '과정에 품격이 생겼어요.',
      ru: 'За изящество в самом пути.',
      hi: 'प्रक्रिया में सुंदरता लाने के लिए।',
      tr: 'Yolunda zarafeti yakaladığın için.',
      id: 'Karena menemukan keanggunan dalam prosesnya.',
      pl: 'Za elegancję w działaniu.',
      nl: 'Voor de elegantie onderweg.',
      ar: 'لأناقةٍ بلغتها في الطريق.',
    },
  },
  {
    n: 19,
    es: 'Veta de Carbón',
    en: 'Coal Seam',
    pt: 'Veio de Carvão',
    fr: 'Veine de Charbon',
    de: 'Kohleflöz',
    it: 'Vena di Carbone',
    ja: '石炭の鉱脈',
    zh: '煤矿脉',
    ko: '석탄 광맥',
    ru: 'Угольный пласт',
    hi: 'कोयले की परत',
    tr: 'Kömür Damarı',
    id: 'Lapisan Batu Bara',
    pl: 'Pokład węgla',
    nl: 'Kolenlaag',
    ar: 'عرق فحم',
    desc: {
      es: 'Por acumular energía potencial.',
      en: 'For storing up potential energy.',
      pt: 'Por acumular energia potencial.',
      fr: 'Pour avoir accumulé de l’énergie en réserve.',
      de: 'Fürs Sammeln von Energie auf Vorrat.',
      it: 'Per aver accumulato energia potenziale.',
      ja: '力を蓄えました。',
      zh: '积蓄了潜在的能量。',
      ko: '잠재된 힘을 쌓았어요.',
      ru: 'За накопленную впрок энергию.',
      hi: 'ऊर्जा जमा करने के लिए।',
      tr: 'Yedekte güç biriktirdiğin için.',
      id: 'Karena menimbun tenaga cadangan.',
      pl: 'Za energię zgromadzoną na zapas.',
      nl: 'Voor het opslaan van energie.',
      ar: 'لطاقةٍ ادّخرتها.',
    },
  },
  {
    n: 20,
    es: 'Fuego de Pirita',
    en: 'Pyrite Fire',
    pt: 'Fogo de Pirita',
    fr: 'Feu de Pyrite',
    de: 'Pyritfeuer',
    it: 'Fuoco di Pirite',
    ja: '黄鉄鉱の火花',
    zh: '黄铁矿之火',
    ko: '황철석 불꽃',
    ru: 'Огонь пирита',
    hi: 'पाइराइट की चिंगारी',
    tr: 'Pirit Ateşi',
    id: 'Api Pirit',
    pl: 'Ogień pirytu',
    nl: 'Pyrietvuur',
    ar: 'شرارة البيريت',
    desc: {
      es: 'Por un descubrimiento sorprendente.',
      en: 'For a surprising discovery.',
      pt: 'Por uma descoberta surpreendente.',
      fr: 'Pour une découverte surprenante.',
      de: 'Für eine überraschende Entdeckung.',
      it: 'Per una scoperta sorprendente.',
      ja: '驚くような発見がありました。',
      zh: '有了一个惊人的发现。',
      ko: '놀라운 발견을 했어요.',
      ru: 'За удивительное открытие.',
      hi: 'एक चौंकाने वाली खोज के लिए।',
      tr: 'Şaşırtıcı bir keşif için.',
      id: 'Karena penemuan yang mengejutkan.',
      pl: 'Za zaskakujące odkrycie.',
      nl: 'Voor een verrassende ontdekking.',
      ar: 'لاكتشافٍ مفاجئ.',
    },
  },
  // Minerales y Cristales Base
  {
    n: 21,
    es: 'Prisma de Cuarzo',
    en: 'Quartz Prism',
    pt: 'Prisma de Quartzo',
    fr: 'Prisme de Quartz',
    de: 'Quarzprisma',
    it: 'Prisma di Quarzo',
    ja: '水晶のプリズム',
    zh: '石英棱镜',
    ko: '수정 프리즘',
    ru: 'Кварцевая призма',
    hi: 'स्फटिक का प्रिज़्म',
    tr: 'Kuvars Prizması',
    id: 'Prisma Kuarsa',
    pl: 'Pryzmat kwarcu',
    nl: 'Kwartsprisma',
    ar: 'موشور الكوارتز',
    desc: {
      es: 'Por enfocar los objetivos.',
      en: 'For focusing your goals.',
      pt: 'Por focar as metas.',
      fr: 'Pour avoir mis tes objectifs au point.',
      de: 'Fürs Schärfen deiner Ziele.',
      it: 'Per aver messo a fuoco gli obiettivi.',
      ja: '目標に焦点を合わせました。',
      zh: '让目标更清晰。',
      ko: '목표에 초점을 맞췄어요.',
      ru: 'За наведённые на резкость цели.',
      hi: 'लक्ष्यों को साफ़ करने के लिए।',
      tr: 'Hedeflerini netleştirdiğin için.',
      id: 'Karena menajamkan fokus pada tujuanmu.',
      pl: 'Za wyostrzenie celów.',
      nl: 'Voor het scherpstellen van je doelen.',
      ar: 'لتركيزك على أهدافك.',
    },
  },
  {
    n: 22,
    es: 'Reflejo de Citrino',
    en: 'Citrine Glint',
    pt: 'Reflexo de Citrino',
    fr: 'Éclat de Citrine',
    de: 'Citrin-Schimmer',
    it: 'Riflesso di Citrino',
    ja: 'シトリンのきらめき',
    zh: '黄水晶微光',
    ko: '시트린 반짝임',
    ru: 'Блик цитрина',
    hi: 'सिट्रीन की झलक',
    tr: 'Sitrin Parıltısı',
    id: 'Kilau Sitrin',
    pl: 'Blask cytrynu',
    nl: 'Citrienglans',
    ar: 'وميض السيترين',
    desc: {
      es: 'Por mantener una racha diurna.',
      en: 'For keeping a daytime streak.',
      pt: 'Por manter uma sequência diurna.',
      fr: 'Pour avoir tenu une série de jour.',
      de: 'Für eine Serie bei Tageslicht.',
      it: 'Per aver tenuto una serie diurna.',
      ja: '日中の連続記録を守りました。',
      zh: '保持了白天的连续天数。',
      ko: '낮의 연속 기록을 지켰어요.',
      ru: 'За дневную серию.',
      hi: 'दिन के सिलसिले को बनाए रखने के लिए।',
      tr: 'Gündüz serini sürdürdüğün için.',
      id: 'Karena menjaga rentetan di siang hari.',
      pl: 'Za dzienną passę.',
      nl: 'Voor een reeks bij daglicht.',
      ar: 'لسلسلةٍ نهاريّة حافظت عليها.',
    },
  },
  {
    n: 23,
    es: 'Reliquia de Jaspe',
    en: 'Jasper Relic',
    pt: 'Relíquia de Jaspe',
    fr: 'Relique de Jaspe',
    de: 'Jaspis-Relikt',
    it: 'Reliquia di Diaspro',
    ja: '碧玉の遺物',
    zh: '碧玉遗物',
    ko: '벽옥 유물',
    ru: 'Реликвия из яшмы',
    hi: 'जैस्पर की धरोहर',
    tr: 'Jasper Yadigârı',
    id: 'Pusaka Jasper',
    pl: 'Relikwia z jaspisu',
    nl: 'Jaspisrelikwie',
    ar: 'تحفة اليَشْب',
    desc: {
      es: 'Por encontrar puntos históricos.',
      en: 'For finding historic landmarks.',
      pt: 'Por encontrar pontos históricos.',
      fr: 'Pour avoir trouvé des lieux chargés d’histoire.',
      de: 'Für gefundene historische Orte.',
      it: 'Per aver trovato luoghi storici.',
      ja: '歴史ある場所を見つけました。',
      zh: '找到了历史的地点。',
      ko: '역사가 깃든 곳을 찾았어요.',
      ru: 'За найденные исторические места.',
      hi: 'ऐतिहासिक जगहें खोजने के लिए।',
      tr: 'Tarihî yerler bulduğun için.',
      id: 'Karena menemukan tempat-tempat bersejarah.',
      pl: 'Za odnalezione miejsca historyczne.',
      nl: 'Voor gevonden historische plekken.',
      ar: 'لعثورك على مواضع تاريخية.',
    },
  },
  {
    n: 24,
    es: 'Ojo de Tigre',
    en: 'Tiger’s Eye',
    pt: 'Olho de Tigre',
    fr: 'Œil-de-Tigre',
    de: 'Tigerauge',
    it: 'Occhio di Tigre',
    ja: '虎目石',
    zh: '虎眼石',
    ko: '호안석',
    ru: 'Тигровый глаз',
    hi: 'बाघ की आँख',
    tr: 'Kaplan Gözü',
    id: 'Mata Harimau',
    pl: 'Tygrysie oko',
    nl: 'Tijgeroog',
    ar: 'عين النمر',
    desc: {
      es: 'Por la agudeza en la exploración.',
      en: 'For sharpness in exploration.',
      pt: 'Pela agudeza na exploração.',
      fr: 'Pour l’acuité du regard en exploration.',
      de: 'Für den scharfen Blick beim Erkunden.',
      it: 'Per l’acutezza nell’esplorazione.',
      ja: '探索の目が鋭くなりました。',
      zh: '探索时目光敏锐。',
      ko: '탐험의 눈이 날카로워졌어요.',
      ru: 'За острый взгляд в поиске.',
      hi: 'खोज में पैनी नज़र के लिए।',
      tr: 'Keşifteki keskin bakışın için.',
      id: 'Karena ketajaman matamu saat menjelajah.',
      pl: 'Za bystre oko w poszukiwaniach.',
      nl: 'Voor de scherpe blik bij het verkennen.',
      ar: 'لحدّة نظرك في الاستكشاف.',
    },
  },
  {
    n: 25,
    es: 'Sombra de Ónice',
    en: 'Onyx Shadow',
    pt: 'Sombra de Ônix',
    fr: 'Ombre d’Onyx',
    de: 'Onyxschatten',
    it: 'Ombra d’Onice',
    ja: 'オニキスの影',
    zh: '缟玛瑙之影',
    ko: '오닉스 그림자',
    ru: 'Тень оникса',
    hi: 'ओनिक्स की छाया',
    tr: 'Oniks Gölgesi',
    id: 'Bayang Oniks',
    pl: 'Cień onyksu',
    nl: 'Onyxschaduw',
    ar: 'ظلّ الجزع',
    desc: {
      es: 'Por completar objetivos nocturnos.',
      en: 'For completing nighttime goals.',
      pt: 'Por concluir metas noturnas.',
      fr: 'Pour avoir bouclé des objectifs nocturnes.',
      de: 'Für erledigte Ziele bei Nacht.',
      it: 'Per aver completato obiettivi notturni.',
      ja: '夜の目標をやり遂げました。',
      zh: '完成了夜间的目标。',
      ko: '밤의 목표를 해냈어요.',
      ru: 'За цели, закрытые ночью.',
      hi: 'रात के लक्ष्य पूरे करने के लिए।',
      tr: 'Gece hedeflerini tamamladığın için.',
      id: 'Karena menuntaskan tujuan di malam hari.',
      pl: 'Za cele domknięte nocą.',
      nl: 'Voor doelen die je in de nacht haalde.',
      ar: 'لأهدافٍ أنجزتها في الليل.',
    },
  },
  {
    n: 26,
    es: 'Lágrima de Ágata',
    en: 'Agate Tear',
    pt: 'Lágrima de Ágata',
    fr: 'Larme d’Agate',
    de: 'Achat-Träne',
    it: 'Lacrima d’Agata',
    ja: '瑪瑙の雫',
    zh: '玛瑙之泪',
    ko: '마노 눈물',
    ru: 'Слеза агата',
    hi: 'अकीक का आँसू',
    tr: 'Akik Gözyaşı',
    id: 'Air Mata Akik',
    pl: 'Łza agatu',
    nl: 'Agaattraan',
    ar: 'دمعة العقيق',
    desc: {
      es: 'Por la resistencia en largos trayectos.',
      en: 'For endurance on long journeys.',
      pt: 'Pela resistência em trajetos longos.',
      fr: 'Pour l’endurance sur les longs trajets.',
      de: 'Für Ausdauer auf langen Strecken.',
      it: 'Per la resistenza sui lunghi tragitti.',
      ja: '長い道のりに耐えました。',
      zh: '在长途中撑住了。',
      ko: '긴 여정을 버텨냈어요.',
      ru: 'За выносливость на долгих переходах.',
      hi: 'लंबे सफ़र में टिके रहने के लिए।',
      tr: 'Uzun yollardaki dayanıklılığın için.',
      id: 'Karena tahan menempuh perjalanan panjang.',
      pl: 'Za wytrzymałość na długich trasach.',
      nl: 'Voor het uithoudingsvermogen op lange tochten.',
      ar: 'لتحمّلك في الدروب الطويلة.',
    },
  },
  {
    n: 27,
    es: 'Corazón de Hematita',
    en: 'Hematite Heart',
    pt: 'Coração de Hematita',
    fr: 'Cœur d’Hématite',
    de: 'Hämatit-Herz',
    it: 'Cuore di Ematite',
    ja: '赤鉄鉱の心臓',
    zh: '赤铁矿之心',
    ko: '적철석 심장',
    ru: 'Сердце гематита',
    hi: 'हेमेटाइट का हृदय',
    tr: 'Hematit Kalbi',
    id: 'Jantung Hematit',
    pl: 'Serce hematytu',
    nl: 'Hematiethart',
    ar: 'قلب الهيماتيت',
    desc: {
      es: 'Por mantener un ritmo constante.',
      en: 'For keeping a constant pace.',
      pt: 'Por manter um ritmo constante.',
      fr: 'Pour avoir tenu un rythme constant.',
      de: 'Für ein gleichmäßiges Tempo.',
      it: 'Per aver tenuto un ritmo costante.',
      ja: '一定のリズムを保ちました。',
      zh: '保持了稳定的节奏。',
      ko: '한결같은 리듬을 지켰어요.',
      ru: 'За ровный ритм.',
      hi: 'एक-सी रफ़्तार बनाए रखने के लिए।',
      tr: 'Değişmez bir tempo tutturduğun için.',
      id: 'Karena menjaga irama yang tetap.',
      pl: 'Za równe tempo.',
      nl: 'Voor een gelijkmatig tempo.',
      ar: 'لإيقاعٍ ثابت حافظت عليه.',
    },
  },
  {
    n: 28,
    es: 'Aura de Fluorita',
    en: 'Fluorite Aura',
    pt: 'Aura de Fluorita',
    fr: 'Aura de Fluorine',
    de: 'Fluorit-Aura',
    it: 'Aura di Fluorite',
    ja: '蛍石のオーラ',
    zh: '萤石光晕',
    ko: '형석 아우라',
    ru: 'Аура флюорита',
    hi: 'फ़्लोराइट की आभा',
    tr: 'Florit Halesi',
    id: 'Aura Fluorit',
    pl: 'Aura fluorytu',
    nl: 'Fluorietaura',
    ar: 'هالة الفلوريت',
    desc: {
      es: 'Por encontrar zonas de alta densidad.',
      en: 'For finding high-density areas.',
      pt: 'Por encontrar zonas de alta densidade.',
      fr: 'Pour avoir trouvé des zones très denses.',
      de: 'Für entdeckte Zonen hoher Dichte.',
      it: 'Per aver trovato zone ad alta densità.',
      ja: '密度の高い場所を見つけました。',
      zh: '找到了高密度的区域。',
      ko: '밀도 높은 구역을 찾아냈어요.',
      ru: 'За найденные плотные зоны.',
      hi: 'घने इलाक़े खोजने के लिए।',
      tr: 'Yoğunluğu yüksek bölgeler bulduğun için.',
      id: 'Karena menemukan kawasan berkepadatan tinggi.',
      pl: 'Za odnalezione strefy o dużej gęstości.',
      nl: 'Voor gevonden zones met hoge dichtheid.',
      ar: 'لعثورك على مناطق شديدة الكثافة.',
    },
  },
  {
    n: 29,
    es: 'Sol de Ámbar',
    en: 'Amber Sun',
    pt: 'Sol de Âmbar',
    fr: 'Soleil d’Ambre',
    de: 'Bernsteinsonne',
    it: 'Sole d’Ambra',
    ja: '琥珀の太陽',
    zh: '琥珀之阳',
    ko: '호박빛 태양',
    ru: 'Янтарное солнце',
    hi: 'अंबर का सूरज',
    tr: 'Kehribar Güneşi',
    id: 'Matahari Ambar',
    pl: 'Bursztynowe słońce',
    nl: 'Barnstenen zon',
    ar: 'شمس الكهرمان',
    desc: {
      es: 'Por capturar un momento perfecto.',
      en: 'For capturing a perfect moment.',
      pt: 'Por capturar um momento perfeito.',
      fr: 'Pour avoir capturé un moment parfait.',
      de: 'Für einen festgehaltenen perfekten Moment.',
      it: 'Per aver catturato un momento perfetto.',
      ja: '完璧な瞬間を閉じこめました。',
      zh: '留住了一个完美的瞬间。',
      ko: '완벽한 순간을 붙잡았어요.',
      ru: 'За пойманное безупречное мгновение.',
      hi: 'एक बेहतरीन पल को क़ैद करने के लिए।',
      tr: 'Kusursuz bir anı yakaladığın için.',
      id: 'Karena menangkap satu momen yang sempurna.',
      pl: 'Za uchwyconą idealną chwilę.',
      nl: 'Voor een perfect vastgelegd moment.',
      ar: 'للحظةٍ كاملة التقطتها.',
    },
  },
  {
    n: 30,
    es: 'Estrella de Bismuto',
    en: 'Bismuth Star',
    pt: 'Estrela de Bismuto',
    fr: 'Étoile de Bismuth',
    de: 'Wismut-Stern',
    it: 'Stella di Bismuto',
    ja: 'ビスマスの星',
    zh: '铋之星',
    ko: '비스무트 별',
    ru: 'Звезда висмута',
    hi: 'बिस्मथ का तारा',
    tr: 'Bizmut Yıldızı',
    id: 'Bintang Bismut',
    pl: 'Gwiazda bizmutu',
    nl: 'Bismutster',
    ar: 'نجمة البزموت',
    desc: {
      es: 'Por la complejidad y estructura.',
      en: 'For complexity and structure.',
      pt: 'Pela complexidade e estrutura.',
      fr: 'Pour la complexité et la structure.',
      de: 'Für Komplexität und Struktur.',
      it: 'Per la complessità e la struttura.',
      ja: '複雑さと構造を極めました。',
      zh: '构建了复杂而有序的结构。',
      ko: '복잡함과 구조를 세웠어요.',
      ru: 'За сложность и стройность.',
      hi: 'जटिलता और संरचना के लिए।',
      tr: 'Kurduğun düzen ve karmaşıklık için.',
      id: 'Karena kerumitan yang tertata rapi.',
      pl: 'Za złożoność i strukturę.',
      nl: 'Voor complexiteit en structuur.',
      ar: 'لتعقيدٍ منظّم أحكمته.',
    },
  },
  {
    n: 31,
    es: 'Brote de Crisocola',
    en: 'Chrysocolla Bloom',
    pt: 'Broto de Crisocola',
    fr: 'Pousse de Chrysocolle',
    de: 'Chrysokoll-Trieb',
    it: 'Germoglio di Crisocolla',
    ja: 'クリソコラの芽',
    zh: '硅孔雀石新芽',
    ko: '크리소콜라 새싹',
    ru: 'Росток хризоколлы',
    hi: 'क्राइसोकोला की कोंपल',
    tr: 'Krizokol Filizi',
    id: 'Tunas Krisokola',
    pl: 'Pęd chryzokoli',
    nl: 'Chrysocolla-scheut',
    ar: 'برعم الكريزوكولا',
    desc: {
      es: 'Por la regeneración y descanso.',
      en: 'For regeneration and rest.',
      pt: 'Pela regeneração e pelo descanso.',
      fr: 'Pour la régénération et le repos.',
      de: 'Für Erholung und Regeneration.',
      it: 'Per la rigenerazione e il riposo.',
      ja: '休んで、力を取り戻しました。',
      zh: '好好休息，恢复了元气。',
      ko: '쉬면서 기운을 되찾았어요.',
      ru: 'За отдых и восстановление.',
      hi: 'आराम और नई ताज़गी के लिए।',
      tr: 'Dinlenip toparlandığın için.',
      id: 'Karena beristirahat dan memulihkan diri.',
      pl: 'Za odpoczynek i regenerację.',
      nl: 'Voor rust en herstel.',
      ar: 'لراحةٍ استعدت بها قواك.',
    },
  },
  // Metales y Aleaciones
  {
    n: 32,
    es: 'Engranaje de Latón',
    en: 'Brass Gear',
    pt: 'Engrenagem de Latão',
    fr: 'Engrenage de Laiton',
    de: 'Messingzahnrad',
    it: 'Ingranaggio di Ottone',
    ja: '真鍮の歯車',
    zh: '黄铜齿轮',
    ko: '놋쇠 톱니바퀴',
    ru: 'Латунная шестерня',
    hi: 'पीतल का गियर',
    tr: 'Pirinç Dişli',
    id: 'Roda Gigi Kuningan',
    pl: 'Mosiężne koło zębate',
    nl: 'Messing tandwiel',
    ar: 'ترس من النحاس الأصفر',
    desc: {
      es: 'Por la sincronización perfecta.',
      en: 'For perfect synchronization.',
      pt: 'Pela sincronia perfeita.',
      fr: 'Pour une synchronisation parfaite.',
      de: 'Für perfekten Gleichlauf.',
      it: 'Per la sincronia perfetta.',
      ja: '息の合った動きができました。',
      zh: '配合得分毫不差。',
      ko: '완벽하게 맞아떨어졌어요.',
      ru: 'За безупречную слаженность.',
      hi: 'बिलकुल सही तालमेल के लिए।',
      tr: 'Kusursuz uyum için.',
      id: 'Karena semuanya berpadu tepat waktu.',
      pl: 'Za idealną synchronizację.',
      nl: 'Voor een perfecte samenloop.',
      ar: 'لتزامنٍ لا يخطئ.',
    },
  },
  {
    n: 33,
    es: 'Hilo de Cobre',
    en: 'Copper Wire',
    pt: 'Fio de Cobre',
    fr: 'Fil de Cuivre',
    de: 'Kupferdraht',
    it: 'Filo di Rame',
    ja: '銅の糸',
    zh: '铜丝',
    ko: '구리선',
    ru: 'Медная нить',
    hi: 'तांबे का तार',
    tr: 'Bakır Tel',
    id: 'Kawat Tembaga',
    pl: 'Miedziany drut',
    nl: 'Koperdraad',
    ar: 'سلك نحاسي',
    desc: {
      es: 'Por conectar múltiples puntos.',
      en: 'For connecting multiple points.',
      pt: 'Por conectar múltiplos pontos.',
      fr: 'Pour avoir relié plusieurs points.',
      de: 'Fürs Verbinden vieler Punkte.',
      it: 'Per aver collegato più punti.',
      ja: 'いくつもの点をつなぎました。',
      zh: '把许多点连在了一起。',
      ko: '여러 점을 이었어요.',
      ru: 'За множество связанных точек.',
      hi: 'कई बिंदुओं को जोड़ने के लिए।',
      tr: 'Birçok noktayı birbirine bağladığın için.',
      id: 'Karena menyambungkan banyak titik.',
      pl: 'Za połączenie wielu punktów.',
      nl: 'Voor het verbinden van vele punten.',
      ar: 'لوصلك نقاطًا كثيرة.',
    },
  },
  {
    n: 34,
    es: 'Escudo de Bronce',
    en: 'Bronze Shield',
    pt: 'Escudo de Bronze',
    fr: 'Bouclier de Bronze',
    de: 'Bronzeschild',
    it: 'Scudo di Bronzo',
    ja: '青銅の盾',
    zh: '青铜之盾',
    ko: '청동 방패',
    ru: 'Бронзовый щит',
    hi: 'कांस्य की ढाल',
    tr: 'Tunç Kalkan',
    id: 'Perisai Perunggu',
    pl: 'Spiżowa tarcza',
    nl: 'Bronzen schild',
    ar: 'درع برونزي',
    desc: {
      es: 'Por la persistencia y durabilidad.',
      en: 'For persistence and durability.',
      pt: 'Pela persistência e durabilidade.',
      fr: 'Pour la persévérance et la durée.',
      de: 'Für Ausdauer und Beständigkeit.',
      it: 'Per la persistenza e la durata.',
      ja: '粘り強く、長く続けました。',
      zh: '长久坚持，从不松懈。',
      ko: '끈질기게, 오래 버텼어요.',
      ru: 'За упорство и прочность.',
      hi: 'लगन और टिकाऊपन के लिए।',
      tr: 'Yılmadan, uzun süre devam ettiğin için.',
      id: 'Karena gigih dan tahan lama.',
      pl: 'Za upór i trwałość.',
      nl: 'Voor volharding en duurzaamheid.',
      ar: 'لإصرارك وطول نفَسك.',
    },
  },
  {
    n: 35,
    es: 'Gota de Mercurio',
    en: 'Mercury Drop',
    pt: 'Gota de Mercúrio',
    fr: 'Goutte de Mercure',
    de: 'Quecksilbertropfen',
    it: 'Goccia di Mercurio',
    ja: '水銀の雫',
    zh: '水银之滴',
    ko: '수은 방울',
    ru: 'Капля ртути',
    hi: 'पारे की बूँद',
    tr: 'Cıva Damlası',
    id: 'Tetes Raksa',
    pl: 'Kropla rtęci',
    nl: 'Kwikdruppel',
    ar: 'قطرة زئبق',
    desc: {
      es: 'Por la adaptabilidad extrema.',
      en: 'For extreme adaptability.',
      pt: 'Pela adaptabilidade extrema.',
      fr: 'Pour une adaptabilité extrême.',
      de: 'Für äußerste Wandlungsfähigkeit.',
      it: 'Per l’adattabilità estrema.',
      ja: 'どんな形にも合わせられました。',
      zh: '能屈能伸，随形而变。',
      ko: '어떤 모양에도 맞췄어요.',
      ru: 'За крайнюю гибкость.',
      hi: 'हर हाल में ढल जाने के लिए।',
      tr: 'Her kalıba girebildiğin için.',
      id: 'Karena bisa menyesuaikan bentuk apa pun.',
      pl: 'Za skrajną zdolność przystosowania.',
      nl: 'Voor het uiterste aanpassingsvermogen.',
      ar: 'لتشكّلك مع كل حال.',
    },
  },
  {
    n: 36,
    es: 'Corona de Estaño',
    en: 'Tin Crown',
    pt: 'Coroa de Estanho',
    fr: 'Couronne d’Étain',
    de: 'Zinnkrone',
    it: 'Corona di Stagno',
    ja: '錫の王冠',
    zh: '锡冠',
    ko: '주석 왕관',
    ru: 'Оловянная корона',
    hi: 'टिन का ताज',
    tr: 'Kalaydan Taç',
    id: 'Mahkota Timah',
    pl: 'Cynowa korona',
    nl: 'Tinnen kroon',
    ar: 'تاج من القصدير',
    desc: {
      es: 'Por proteger los logros obtenidos.',
      en: 'For protecting the achievements you’ve earned.',
      pt: 'Por proteger as conquistas obtidas.',
      fr: 'Pour avoir protégé tes acquis.',
      de: 'Fürs Bewahren des Erreichten.',
      it: 'Per aver protetto i traguardi raggiunti.',
      ja: '積み上げた成果を守りました。',
      zh: '守住了已有的成果。',
      ko: '이룬 것을 지켜냈어요.',
      ru: 'За сбережённые достижения.',
      hi: 'हासिल उपलब्धियों को बचाने के लिए।',
      tr: 'Kazandıklarını koruduğun için.',
      id: 'Karena menjaga apa yang sudah kamu raih.',
      pl: 'Za obronę tego, co zdobyte.',
      nl: 'Voor het beschermen van wat je bereikte.',
      ar: 'لحفاظك على ما أنجزته.',
    },
  },
  {
    n: 37,
    es: 'Moneda de Electrum',
    en: 'Electrum Coin',
    pt: 'Moeda de Electro',
    fr: 'Pièce d’Électrum',
    de: 'Elektrum-Münze',
    it: 'Moneta di Elettro',
    ja: 'エレクトラム貨',
    zh: '琥珀金币',
    ko: '호박금 동전',
    ru: 'Монета из электрума',
    hi: 'इलेक्ट्रम का सिक्का',
    tr: 'Elektrum Sikkesi',
    id: 'Koin Elektrum',
    pl: 'Moneta z elektrum',
    nl: 'Elektrummunt',
    ar: 'عملة من الإلكتروم',
    desc: {
      es: 'Por la dualidad de habilidades.',
      en: 'For a duality of skills.',
      pt: 'Pela dualidade de habilidades.',
      fr: 'Pour la dualité des compétences.',
      de: 'Für die Doppelbegabung.',
      it: 'Per la dualità delle abilità.',
      ja: '二つの才を併せ持ちました。',
      zh: '兼具两种本领。',
      ko: '두 가지 재능을 함께 지녔어요.',
      ru: 'За двойственность умений.',
      hi: 'दोहरे हुनर के लिए।',
      tr: 'İki yeteneği bir arada taşıdığın için.',
      id: 'Karena memadukan dua kemampuan sekaligus.',
      pl: 'Za dwoistość umiejętności.',
      nl: 'Voor de dubbele begaafdheid.',
      ar: 'لمهارتين اجتمعتا فيك.',
    },
  },
  {
    n: 38,
    es: 'Fusión de Titanio',
    en: 'Titanium Fusion',
    pt: 'Fusão de Titânio',
    fr: 'Fusion de Titane',
    de: 'Titanfusion',
    it: 'Fusione di Titanio',
    ja: 'チタンの融合',
    zh: '钛合金熔炼',
    ko: '티타늄 융합',
    ru: 'Титановая плавка',
    hi: 'टाइटेनियम का संगम',
    tr: 'Titanyum Füzyonu',
    id: 'Fusi Titanium',
    pl: 'Fuzja tytanu',
    nl: 'Titaniumfusie',
    ar: 'انصهار التيتانيوم',
    desc: {
      es: 'Por la máxima resistencia en una jornada.',
      en: 'For maximum endurance in a single day.',
      pt: 'Pela resistência máxima em um único dia.',
      fr: 'Pour l’endurance maximale en une seule journée.',
      de: 'Für höchste Ausdauer an einem Tag.',
      it: 'Per la massima resistenza in una sola giornata.',
      ja: '一日で最高の粘りを見せました。',
      zh: '在一天里撑到了极限。',
      ko: '하루 만에 최고의 지구력을 냈어요.',
      ru: 'За предельную выносливость за один день.',
      hi: 'एक ही दिन में सबसे ज़्यादा दमख़म के लिए।',
      tr: 'Bir günde en yüksek dayanıklılığı gösterdiğin için.',
      id: 'Karena daya tahan tertinggi dalam satu hari.',
      pl: 'Za największą wytrzymałość w jeden dzień.',
      nl: 'Voor de grootste uithouding op één dag.',
      ar: 'لأقصى تحمّلٍ في يومٍ واحد.',
    },
  },
  {
    n: 39,
    es: 'Escala de Paladio',
    en: 'Palladium Climb',
    pt: 'Escalada de Paládio',
    fr: 'Ascension de Palladium',
    de: 'Palladium-Aufstieg',
    it: 'Scalata di Palladio',
    ja: 'パラジウムの階段',
    zh: '钯金阶梯',
    ko: '팔라듐 계단',
    ru: 'Палладиевая лестница',
    hi: 'पैलेडियम की सीढ़ी',
    tr: 'Paladyum Merdiveni',
    id: 'Tangga Paladium',
    pl: 'Palladowe schody',
    nl: 'Palladiumtrap',
    ar: 'سلّم البلاديوم',
    desc: {
      es: 'Por escalar en los rangos rápidamente.',
      en: 'For climbing the ranks quickly.',
      pt: 'Por subir de patente rapidamente.',
      fr: 'Pour avoir grimpé les rangs à toute vitesse.',
      de: 'Für den schnellen Aufstieg durch die Ränge.',
      it: 'Per aver scalato i gradi in fretta.',
      ja: '称号を一気に駆け上がりました。',
      zh: '段位一路飙升。',
      ko: '등급을 빠르게 올라갔어요.',
      ru: 'За стремительный подъём по рангам.',
      hi: 'तेज़ी से रैंक चढ़ने के लिए।',
      tr: 'Rütbeleri hızla tırmandığın için.',
      id: 'Karena naik pangkat dengan cepat.',
      pl: 'Za błyskawiczny awans w rangach.',
      nl: 'Voor de snelle klim door de rangen.',
      ar: 'لصعودك السريع في الرتب.',
    },
  },
  {
    n: 40,
    es: 'Destello de Plata',
    en: 'Silver Flash',
    pt: 'Lampejo de Prata',
    fr: 'Éclair d’Argent',
    de: 'Silberblitz',
    it: 'Lampo d’Argento',
    ja: '銀の閃光',
    zh: '白银闪光',
    ko: '은빛 섬광',
    ru: 'Серебряная вспышка',
    hi: 'चांदी की चमक',
    tr: 'Gümüş Şimşek',
    id: 'Kilat Perak',
    pl: 'Srebrny błysk',
    nl: 'Zilveren flits',
    ar: 'وميض فضّي',
    desc: {
      es: 'Por la agilidad en la recolección.',
      en: 'For agility while collecting.',
      pt: 'Pela agilidade na coleta.',
      fr: 'Pour l’agilité dans la récolte.',
      de: 'Für Flinkheit beim Sammeln.',
      it: 'Per l’agilità nella raccolta.',
      ja: '集めるのが素早くなりました。',
      zh: '收集时身手敏捷。',
      ko: '재빠르게 거둬들였어요.',
      ru: 'За проворство в сборе.',
      hi: 'बटोरने की फुर्ती के लिए।',
      tr: 'Toplarken gösterdiğin çeviklik için.',
      id: 'Karena cekatan saat mengumpulkan.',
      pl: 'Za zwinność w zbieraniu.',
      nl: 'Voor de behendigheid bij het verzamelen.',
      ar: 'لرشاقتك في الجمع.',
    },
  },
  {
    n: 41,
    es: 'Pepita Dorada',
    en: 'Golden Nugget',
    pt: 'Pepita Dourada',
    fr: 'Pépite Dorée',
    de: 'Goldnugget',
    it: 'Pepita Dorata',
    ja: '黄金の粒',
    zh: '金块',
    ko: '황금 덩이',
    ru: 'Золотой самородок',
    hi: 'सोने की डली',
    tr: 'Altın Külçesi',
    id: 'Bongkahan Emas',
    pl: 'Złoty samorodek',
    nl: 'Goudklomp',
    ar: 'شذرة ذهب',
    desc: {
      es: 'Por un hallazgo de alto valor.',
      en: 'For a high-value find.',
      pt: 'Por um achado de grande valor.',
      fr: 'Pour une trouvaille de grande valeur.',
      de: 'Für einen besonders wertvollen Fund.',
      it: 'Per un ritrovamento di grande valore.',
      ja: '値打ちのある発見をしました。',
      zh: '有了一次高价值的发现。',
      ko: '값진 발견을 했어요.',
      ru: 'За находку большой ценности.',
      hi: 'बड़े मोल की खोज के लिए।',
      tr: 'Çok değerli bir buluş için.',
      id: 'Karena temuan yang sangat berharga.',
      pl: 'Za znalezisko wielkiej wartości.',
      nl: 'Voor een vondst van grote waarde.',
      ar: 'لعثورك على شيءٍ ثمين.',
    },
  },
  // Gemas y Materiales Preciosos
  {
    n: 42,
    es: 'Fragmento de Meteorito',
    en: 'Meteorite Fragment',
    pt: 'Fragmento de Meteorito',
    fr: 'Fragment de Météorite',
    de: 'Meteoritensplitter',
    it: 'Frammento di Meteorite',
    ja: '隕石のかけら',
    zh: '陨石碎片',
    ko: '운석 조각',
    ru: 'Осколок метеорита',
    hi: 'उल्कापिंड का टुकड़ा',
    tr: 'Göktaşı Parçası',
    id: 'Serpihan Meteorit',
    pl: 'Odłamek meteorytu',
    nl: 'Meteorietsplinter',
    ar: 'شظية نيزك',
    desc: {
      es: 'Por un logro fuera de lo común.',
      en: 'For an out-of-the-ordinary achievement.',
      pt: 'Por uma conquista fora do comum.',
      fr: 'Pour un exploit hors du commun.',
      de: 'Für eine außergewöhnliche Leistung.',
      it: 'Per un traguardo fuori dal comune.',
      ja: '並外れたことを成し遂げました。',
      zh: '完成了一件不寻常的事。',
      ko: '남다른 일을 해냈어요.',
      ru: 'За необычайное достижение.',
      hi: 'असाधारण उपलब्धि के लिए।',
      tr: 'Sıra dışı bir başarı için.',
      id: 'Karena pencapaian yang luar biasa.',
      pl: 'Za osiągnięcie nie z tej ziemi.',
      nl: 'Voor een buitengewone prestatie.',
      ar: 'لإنجازٍ خارج المألوف.',
    },
  },
  {
    n: 43,
    es: 'Alma de Turquesa',
    en: 'Turquoise Soul',
    pt: 'Alma de Turquesa',
    fr: 'Âme de Turquoise',
    de: 'Türkis-Seele',
    it: 'Anima di Turchese',
    ja: 'トルコ石の魂',
    zh: '绿松石之魂',
    ko: '터키석의 혼',
    ru: 'Душа бирюзы',
    hi: 'फ़िरोज़े की आत्मा',
    tr: 'Firuze Ruhu',
    id: 'Jiwa Pirus',
    pl: 'Dusza turkusu',
    nl: 'Turkooizen ziel',
    ar: 'روح الفيروز',
    desc: {
      es: 'Por la exploración de patrimonios.',
      en: 'For exploring heritage.',
      pt: 'Pela exploração do patrimônio.',
      fr: 'Pour l’exploration du patrimoine.',
      de: 'Fürs Erkunden von Kulturerbe.',
      it: 'Per l’esplorazione del patrimonio.',
      ja: '受け継がれた文化をたどりました。',
      zh: '探访了传承的遗产。',
      ko: '물려받은 유산을 둘러봤어요.',
      ru: 'За встречу с наследием.',
      hi: 'विरासत को खोजने के लिए।',
      tr: 'Mirası keşfe çıktığın için.',
      id: 'Karena menyusuri warisan budaya.',
      pl: 'Za odkrywanie dziedzictwa.',
      nl: 'Voor het verkennen van erfgoed.',
      ar: 'لاستكشافك التراث.',
    },
  },
  {
    n: 44,
    es: 'Gota de Aguamarina',
    en: 'Aquamarine Drop',
    pt: 'Gota de Água-Marinha',
    fr: 'Goutte d’Aigue-Marine',
    de: 'Aquamarin-Tropfen',
    it: 'Goccia d’Acquamarina',
    ja: 'アクアマリンの雫',
    zh: '海蓝宝之滴',
    ko: '아쿠아마린 물방울',
    ru: 'Капля аквамарина',
    hi: 'एक्वामरीन की बूँद',
    tr: 'Akuamarin Damlası',
    id: 'Tetes Akuamarin',
    pl: 'Kropla akwamarynu',
    nl: 'Aquamarijndruppel',
    ar: 'قطرة أكوامارين',
    desc: {
      es: 'Por la fluidez en la navegación.',
      en: 'For fluid navigation.',
      pt: 'Pela fluidez na navegação.',
      fr: 'Pour la fluidité de la navigation.',
      de: 'Für müheloses Navigieren.',
      it: 'Per la fluidità nella navigazione.',
      ja: 'よどみなく進みました。',
      zh: '一路顺畅无阻。',
      ko: '막힘없이 나아갔어요.',
      ru: 'За плавность движения.',
      hi: 'बेरोक-टोक चलने के लिए।',
      tr: 'Akıp giden ilerleyişin için.',
      id: 'Karena melaju tanpa hambatan.',
      pl: 'Za płynność w drodze.',
      nl: 'Voor het moeiteloze navigeren.',
      ar: 'لانسيابك في الطريق.',
    },
  },
  {
    n: 45,
    es: 'Resplandor de Malaquita',
    en: 'Malachite Glow',
    pt: 'Brilho de Malaquita',
    fr: 'Lueur de Malachite',
    de: 'Malachit-Leuchten',
    it: 'Bagliore di Malachite',
    ja: 'マラカイトの輝き',
    zh: '孔雀石光辉',
    ko: '공작석 광채',
    ru: 'Сияние малахита',
    hi: 'मैलाकाइट की आभा',
    tr: 'Malakit Işıltısı',
    id: 'Cahaya Malasit',
    pl: 'Blask malachitu',
    nl: 'Malachietgloed',
    ar: 'توهّج المالاكيت',
    desc: {
      es: 'Por el crecimiento continuo.',
      en: 'For continuous growth.',
      pt: 'Pelo crescimento contínuo.',
      fr: 'Pour la croissance continue.',
      de: 'Für stetiges Wachstum.',
      it: 'Per la crescita continua.',
      ja: '伸び続けました。',
      zh: '一直在生长。',
      ko: '끊임없이 자라났어요.',
      ru: 'За непрерывный рост.',
      hi: 'लगातार बढ़ते रहने के लिए।',
      tr: 'Durmadan büyüdüğün için.',
      id: 'Karena terus bertumbuh.',
      pl: 'Za nieustanny wzrost.',
      nl: 'Voor de gestage groei.',
      ar: 'لنموّك المتواصل.',
    },
  },
  {
    n: 46,
    es: 'Eco de Azurita',
    en: 'Azurite Echo',
    pt: 'Eco de Azurita',
    fr: 'Écho d’Azurite',
    de: 'Azurit-Echo',
    it: 'Eco d’Azzurrite',
    ja: 'アズライトの残響',
    zh: '蓝铜矿回声',
    ko: '남동석 메아리',
    ru: 'Эхо азурита',
    hi: 'अज़ुराइट की गूँज',
    tr: 'Azurit Yankısı',
    id: 'Gema Azurit',
    pl: 'Echo azurytu',
    nl: 'Azurietecho',
    ar: 'صدى الأزوريت',
    desc: {
      es: 'Por la profundidad del recorrido.',
      en: 'For the depth of your journey.',
      pt: 'Pela profundidade do percurso.',
      fr: 'Pour la profondeur du parcours.',
      de: 'Für die Tiefe des Weges.',
      it: 'Per la profondità del percorso.',
      ja: '深いところまで歩みました。',
      zh: '走出了旅程的深度。',
      ko: '여정의 깊이를 더했어요.',
      ru: 'За глубину пройденного пути.',
      hi: 'सफ़र की गहराई के लिए।',
      tr: 'Yolun derinliği için.',
      id: 'Karena kedalaman perjalananmu.',
      pl: 'Za głębię przebytej drogi.',
      nl: 'Voor de diepte van je tocht.',
      ar: 'لعمق الطريق الذي قطعته.',
    },
  },
  {
    n: 47,
    es: 'Profundidad de Zafiro',
    en: 'Sapphire Depth',
    pt: 'Profundeza de Safira',
    fr: 'Profondeur de Saphir',
    de: 'Saphirtiefe',
    it: 'Profondità di Zaffiro',
    ja: 'サファイアの深み',
    zh: '蓝宝石深处',
    ko: '사파이어의 깊이',
    ru: 'Глубина сапфира',
    hi: 'नीलम की गहराई',
    tr: 'Safir Derinliği',
    id: 'Kedalaman Safir',
    pl: 'Głębia szafiru',
    nl: 'Saffierdiepte',
    ar: 'عمق الياقوت الأزرق',
    desc: {
      es: 'Por la dedicación absoluta.',
      en: 'For absolute dedication.',
      pt: 'Pela dedicação absoluta.',
      fr: 'Pour un dévouement absolu.',
      de: 'Für absolute Hingabe.',
      it: 'Per la dedizione assoluta.',
      ja: 'ひたむきに打ち込みました。',
      zh: '全心全意地投入。',
      ko: '온 마음을 다했어요.',
      ru: 'За безоглядную преданность делу.',
      hi: 'पूरे समर्पण के लिए।',
      tr: 'Kendini tümüyle verdiğin için.',
      id: 'Karena mencurahkan segalanya.',
      pl: 'Za bezgraniczne oddanie.',
      nl: 'Voor de volledige toewijding.',
      ar: 'لتفانٍ لا حدّ له.',
    },
  },
  {
    n: 48,
    es: 'Hoja de Jade',
    en: 'Jade Leaf',
    pt: 'Folha de Jade',
    fr: 'Feuille de Jade',
    de: 'Jadeblatt',
    it: 'Foglia di Giada',
    ja: '翡翠の葉',
    zh: '翡翠叶',
    ko: '비취 잎',
    ru: 'Нефритовый лист',
    hi: 'जेड का पत्ता',
    tr: 'Yeşim Yaprağı',
    id: 'Daun Giok',
    pl: 'Liść nefrytu',
    nl: 'Jadeblad',
    ar: 'ورقة اليشم',
    desc: {
      es: 'Por la armonía y el equilibrio.',
      en: 'For harmony and balance.',
      pt: 'Pela harmonia e pelo equilíbrio.',
      fr: 'Pour l’harmonie et l’équilibre.',
      de: 'Für Harmonie und Gleichgewicht.',
      it: 'Per l’armonia e l’equilibrio.',
      ja: '調和と均衡を保ちました。',
      zh: '保持了和谐与平衡。',
      ko: '조화와 균형을 지켰어요.',
      ru: 'За гармонию и равновесие.',
      hi: 'संतुलन और सामंजस्य के लिए।',
      tr: 'Uyum ve dengeyi koruduğun için.',
      id: 'Karena menjaga selaras dan seimbang.',
      pl: 'Za harmonię i równowagę.',
      nl: 'Voor harmonie en evenwicht.',
      ar: 'لتوازنٍ وانسجام حافظت عليهما.',
    },
  },
  {
    n: 49,
    es: 'Fuego de Rubí',
    en: 'Ruby Fire',
    pt: 'Fogo de Rubi',
    fr: 'Feu de Rubis',
    de: 'Rubinfeuer',
    it: 'Fuoco di Rubino',
    ja: 'ルビーの炎',
    zh: '红宝石之火',
    ko: '루비 불꽃',
    ru: 'Рубиновое пламя',
    hi: 'माणिक की आग',
    tr: 'Yakut Ateşi',
    id: 'Api Rubi',
    pl: 'Ogień rubinu',
    nl: 'Robijnvuur',
    ar: 'لهب الياقوت',
    desc: {
      es: 'Por la pasión y la intensidad.',
      en: 'For passion and intensity.',
      pt: 'Pela paixão e pela intensidade.',
      fr: 'Pour la passion et l’intensité.',
      de: 'Für Leidenschaft und Intensität.',
      it: 'Per la passione e l’intensità.',
      ja: '情熱を燃やしました。',
      zh: '热情而炽烈。',
      ko: '뜨겁게 몰입했어요.',
      ru: 'За страсть и накал.',
      hi: 'जोश और शिद्दत के लिए।',
      tr: 'Tutkun ve o yoğunluğun için.',
      id: 'Karena bara semangatmu.',
      pl: 'Za pasję i żar.',
      nl: 'Voor passie en intensiteit.',
      ar: 'لشغفك وحرارتك.',
    },
  },
  {
    n: 50,
    es: 'Prisma de Ópalo',
    en: 'Opal Prism',
    pt: 'Prisma de Opala',
    fr: 'Prisme d’Opale',
    de: 'Opalprisma',
    it: 'Prisma d’Opale',
    ja: 'オパールのプリズム',
    zh: '蛋白石棱镜',
    ko: '오팔 프리즘',
    ru: 'Призма опала',
    hi: 'ओपल का प्रिज़्म',
    tr: 'Opal Prizması',
    id: 'Prisma Opal',
    pl: 'Pryzmat opalu',
    nl: 'Opaalprisma',
    ar: 'موشور الأوبال',
    desc: {
      es: 'Por la versatilidad en todas las áreas.',
      en: 'For versatility across every area.',
      pt: 'Pela versatilidade em todas as áreas.',
      fr: 'Pour la polyvalence dans tous les domaines.',
      de: 'Für Vielseitigkeit in allen Bereichen.',
      it: 'Per la versatilità in tutti gli ambiti.',
      ja: 'どの分野でも力を発揮しました。',
      zh: '在每个领域都游刃有余。',
      ko: '모든 분야에서 두루 해냈어요.',
      ru: 'За разносторонность во всех сферах.',
      hi: 'हर क्षेत्र में महारत के लिए।',
      tr: 'Her alanda kendini gösterdiğin için.',
      id: 'Karena piawai di segala bidang.',
      pl: 'Za wszechstronność w każdej dziedzinie.',
      nl: 'Voor veelzijdigheid op elk vlak.',
      ar: 'لبراعتك في كل مجال.',
    },
  },
  {
    n: 51,
    es: 'Faceta de Zircón',
    en: 'Zircon Facet',
    pt: 'Faceta de Zircão',
    fr: 'Facette de Zircon',
    de: 'Zirkon-Facette',
    it: 'Faccetta di Zircone',
    ja: 'ジルコンのカット面',
    zh: '锆石切面',
    ko: '지르콘 결정면',
    ru: 'Грань циркона',
    hi: 'ज़िरकॉन का पहलू',
    tr: 'Zirkon Faseti',
    id: 'Faset Zirkon',
    pl: 'Faseta cyrkonu',
    nl: 'Zirkoonfacet',
    ar: 'وجه الزركون',
    desc: {
      es: 'Por la resistencia a la fricción.',
      en: 'For resistance to friction.',
      pt: 'Pela resistência ao atrito.',
      fr: 'Pour la résistance à l’usure.',
      de: 'Für Widerstand gegen jede Reibung.',
      it: 'Per la resistenza all’attrito.',
      ja: '摩耗に負けませんでした。',
      zh: '顶住了一切磨损。',
      ko: '마찰에도 닳지 않았어요.',
      ru: 'За стойкость к любому трению.',
      hi: 'घिसाव सहने के लिए।',
      tr: 'Aşınmaya direndiğin için.',
      id: 'Karena tak terkikis oleh gesekan.',
      pl: 'Za odporność na tarcie.',
      nl: 'Voor de weerstand tegen slijtage.',
      ar: 'لصمودك أمام الاحتكاك.',
    },
  },
  {
    n: 52,
    es: 'Corona de Diamante',
    en: 'Diamond Crown',
    pt: 'Coroa de Diamante',
    fr: 'Couronne de Diamant',
    de: 'Diamantkrone',
    it: 'Corona di Diamante',
    ja: 'ダイヤモンドの王冠',
    zh: '钻石王冠',
    ko: '다이아몬드 왕관',
    ru: 'Алмазная корона',
    hi: 'हीरे का ताज',
    tr: 'Elmas Taç',
    id: 'Mahkota Berlian',
    pl: 'Diamentowa korona',
    nl: 'Diamanten kroon',
    ar: 'تاج من الألماس',
    desc: {
      es: 'Por completar el ciclo de exploración completo.',
      en: 'For completing the full cycle of exploration.',
      pt: 'Por completar todo o ciclo de exploração.',
      fr: 'Pour avoir bouclé le cycle d’exploration complet.',
      de: 'Fürs Vollenden des ganzen Erkundungszyklus.',
      it: 'Per aver completato l’intero ciclo di esplorazione.',
      ja: '探索の一巡りを完走しました。',
      zh: '走完了整整一轮探索。',
      ko: '탐험의 한 바퀴를 완주했어요.',
      ru: 'За пройденный до конца круг исследования.',
      hi: 'खोज का पूरा चक्र पूरा करने के लिए।',
      tr: 'Keşif döngüsünü baştan sona tamamladığın için.',
      id: 'Karena menuntaskan satu putaran penjelajahan penuh.',
      pl: 'Za domknięcie pełnego cyklu wypraw.',
      nl: 'Voor het voltooien van de volledige verkenningscyclus.',
      ar: 'لإتمامك دورة الاستكشاف كاملة.',
    },
  },
]

// ─── Helpers puros derivados de `altura` (días subidos) ───

/** Insignias ganadas: una por cada semana completa subida (0–52). */
export function insigniasGanadas(altura: number): number {
  return Math.min(SEMANAS, Math.floor(altura / DIAS_POR_SEMANA))
}

/** Rango actual (1–12) según la altura. */
export function rangoDe(altura: number): number {
  const semanas = altura / DIAS_POR_SEMANA
  for (let i = 0; i < LIMITES_SEMANA.length; i++) {
    if (semanas < LIMITES_SEMANA[i]) return i + 1
  }
  return 12
}

/** Altura (en días) del rellano donde empieza el rango actual: destino del retroceso. */
export function inicioDeRango(altura: number): number {
  const r = rangoDe(altura)
  return r <= 1 ? 0 : LIMITES_SEMANA[r - 2] * DIAS_POR_SEMANA
}

/** Los 7 colores del arcoíris (rojo→violeta): ciclan por cada insignia semanal. */
const ARCOIRIS = ['#e11d48', '#f97316', '#eab308', '#22c55e', '#0ea5e9', '#6366f1', '#a855f7']

/** Color de la insignia nº n (1–52): cicla el arcoíris cada 7 semanas. */
export function colorArcoiris(n: number): string {
  return ARCOIRIS[(n - 1) % 7]
}

// ─── Accesores localizados (leen el idioma activo al vuelo) ───

export const nombreRango = (r: Rango): string => porIdioma(r)
export const nombreInsignia = (b: Insignia): string => porIdioma(b)
export const descInsignia = (b: Insignia): string => porIdioma(b.desc)
export const nombreCategoria = (c: CategoriaInsignia): string => porIdioma(c)
