// Contenido de los dibujos de fábrica de arte, por idioma. Vive aparte de
// `dict.ts` a propósito: en cuanto se crea es dato del usuario, no interfaz.
// Los dibujos los pinta `ejemplos.ts` con canvas; aquí solo van sus nombres.

export const TEXTOS_ARTE = {
  es: {
    dibujo: 'Tarde en el valle',
    capaCielo: 'Cielo',
    capaColinas: 'Colinas',
    capaFrente: 'Árbol y camino',
    bodegon: 'Bodegón de frutas',
    capaMesa: 'Pared y mesa',
    capaJarra: 'Jarra',
    capaFrutas: 'Frutas',
  },
  en: {
    dibujo: 'Afternoon in the valley',
    capaCielo: 'Sky',
    capaColinas: 'Hills',
    capaFrente: 'Tree and path',
    bodegon: 'Fruit still life',
    capaMesa: 'Wall and table',
    capaJarra: 'Pitcher',
    capaFrutas: 'Fruit',
  },
  pt: {
    dibujo: 'Tarde no vale',
    capaCielo: 'Céu',
    capaColinas: 'Colinas',
    capaFrente: 'Árvore e caminho',
    bodegon: 'Natureza-morta com frutas',
    capaMesa: 'Parede e mesa',
    capaJarra: 'Jarra',
    capaFrutas: 'Frutas',
  },
  fr: {
    dibujo: 'Après-midi dans la vallée',
    capaCielo: 'Ciel',
    capaColinas: 'Collines',
    capaFrente: 'Arbre et chemin',
    bodegon: 'Nature morte aux fruits',
    capaMesa: 'Mur et table',
    capaJarra: 'Cruche',
    capaFrutas: 'Fruits',
  },
  de: {
    dibujo: 'Nachmittag im Tal',
    capaCielo: 'Himmel',
    capaColinas: 'Hügel',
    capaFrente: 'Baum und Weg',
    bodegon: 'Stillleben mit Obst',
    capaMesa: 'Wand und Tisch',
    capaJarra: 'Krug',
    capaFrutas: 'Obst',
  },
  it: {
    dibujo: 'Pomeriggio nella valle',
    capaCielo: 'Cielo',
    capaColinas: 'Colline',
    capaFrente: 'Albero e sentiero',
    bodegon: 'Natura morta con frutta',
    capaMesa: 'Parete e tavolo',
    capaJarra: 'Brocca',
    capaFrutas: 'Frutta',
  },
  ja: {
    dibujo: '谷の午後',
    capaCielo: '空',
    capaColinas: '丘',
    capaFrente: '木と道',
    bodegon: '果物の静物画',
    capaMesa: '壁とテーブル',
    capaJarra: '水差し',
    capaFrutas: '果物',
  },
  zh: {
    dibujo: '山谷的午后',
    capaCielo: '天空',
    capaColinas: '山丘',
    capaFrente: '树与小路',
    bodegon: '水果静物',
    capaMesa: '墙与桌子',
    capaJarra: '水壶',
    capaFrutas: '水果',
  },
  ko: {
    dibujo: '골짜기의 오후',
    capaCielo: '하늘',
    capaColinas: '언덕',
    capaFrente: '나무와 길',
    bodegon: '과일 정물화',
    capaMesa: '벽과 탁자',
    capaJarra: '물병',
    capaFrutas: '과일',
  },
  ru: {
    dibujo: 'Вечер в долине',
    capaCielo: 'Небо',
    capaColinas: 'Холмы',
    capaFrente: 'Дерево и тропа',
    bodegon: 'Натюрморт с фруктами',
    capaMesa: 'Стена и стол',
    capaJarra: 'Кувшин',
    capaFrutas: 'Фрукты',
  },
  hi: {
    dibujo: 'घाटी में दोपहर',
    capaCielo: 'आकाश',
    capaColinas: 'पहाड़ियाँ',
    capaFrente: 'पेड़ और रास्ता',
    bodegon: 'फलों का स्थिर चित्र',
    capaMesa: 'दीवार और मेज़',
    capaJarra: 'सुराही',
    capaFrutas: 'फल',
  },
  tr: {
    dibujo: 'Vadide öğleden sonra',
    capaCielo: 'Gökyüzü',
    capaColinas: 'Tepeler',
    capaFrente: 'Ağaç ve yol',
    bodegon: 'Meyveli natürmort',
    capaMesa: 'Duvar ve masa',
    capaJarra: 'Sürahi',
    capaFrutas: 'Meyveler',
  },
  id: {
    dibujo: 'Sore di lembah',
    capaCielo: 'Langit',
    capaColinas: 'Bukit',
    capaFrente: 'Pohon dan jalan',
    bodegon: 'Lukisan buah-buahan',
    capaMesa: 'Dinding dan meja',
    capaJarra: 'Kendi',
    capaFrutas: 'Buah-buahan',
  },
  pl: {
    dibujo: 'Popołudnie w dolinie',
    capaCielo: 'Niebo',
    capaColinas: 'Wzgórza',
    capaFrente: 'Drzewo i ścieżka',
    bodegon: 'Martwa natura z owocami',
    capaMesa: 'Ściana i stół',
    capaJarra: 'Dzbanek',
    capaFrutas: 'Owoce',
  },
  ar: {
    dibujo: 'عصر في الوادي',
    capaCielo: 'السماء',
    capaColinas: 'التلال',
    capaFrente: 'الشجرة والطريق',
    bodegon: 'طبيعة صامتة بالفواكه',
    capaMesa: 'الجدار والطاولة',
    capaJarra: 'الإبريق',
    capaFrutas: 'الفواكه',
  },
  nl: {
    dibujo: 'Middag in de vallei',
    capaCielo: 'Lucht',
    capaColinas: 'Heuvels',
    capaFrente: 'Boom en pad',
    bodegon: 'Stilleven met fruit',
    capaMesa: 'Muur en tafel',
    capaJarra: 'Kan',
    capaFrutas: 'Fruit',
  },
}
