import {
  // Chrome
  Pencil,
  Check,
  Wrench,
  House,
  Layers,
  Layers2,
  ChartColumn,
  DoorOpen,
  Settings,
  Plus,
  Minus,
  Heart,
  Zap,
  Flame,
  BookOpen,
  MessageCircle,
  NotebookText,
  Brain,
  AlarmClock,
  MonitorOff,
  Camera,
  Mic,
  Target,
  Trash2,
  ArrowDown,
  RotateCcw,
  RotateCw,
  Sun,
  Moon,
  CalendarDays,
  NotebookPen,
  Sparkles,
  Waves,
  Laptop,
  Volume2,
  Languages,
  X,
  Send,
  Share2,
  Microscope,
  Contrast,
  Aperture,
  // Infraestructura del mapa
  Construction,
  Route,
  TrainTrack,
  RollerCoaster,
  LandPlot,
  Shovel,
  Fence,
  PawPrint,
  // Cuartos
  ChefHat,
  BicepsFlexed,
  BedDouble,
  PenLine,
  Wallet,
  Library,
  Gamepad2,
  Plane,
  Flower2,
  Newspaper,
  Package,
  // Tabs y acciones comunes
  SquarePen,
  CookingPot,
  ShoppingCart,
  Dumbbell,
  Activity,
  CircleCheck,
  ClipboardList,
  Eye,
  TrendingUp,
  Tag,
  // Temas de UI
  TreePine,
  Sunset,
  Grape,
  // Mascotas y estados
  WandSparkles,
  Cat,
  Dog,
  Bird,
  Bot,
  Smile,
  SmilePlus,
  Meh,
  Frown,
  Laugh,
  Angry,
  Annoyed,
  // Chrome ampliado (ciclo, constructor, chat)
  Lightbulb,
  MapPin,
  CloudRain,
  Droplet,
  Wind,
  Umbrella,
  Sunrise,
  CloudSun,
  CloudFog,
  CloudDrizzle,
  CloudSnow,
  CloudLightning,
  Thermometer,
  ArrowUp,
  Cloud,
  BrickWall,
  Grid2x2,
  Grid3x3,
  Leaf,
  Square,
  Triangle,
  Move,
  Expand,
  Shell,
  SquareArrowUp,
  ArrowUpDown,
  Rainbow,
  Image,
  Map as MapIcon,
  Pointer,
  Handshake,
  Repeat,
  Palette,
  Ruler,
  Armchair,
  PersonStanding,
  FolderOpen,
  Sparkle,
  Gem,
  Shirt,
  User,
  Circle,
  Cylinder,
  Copy,
  Link,
  Box,
  RectangleHorizontal,
  // Cocina
  Utensils,
  CupSoda,
  Carrot,
  Beef,
  Milk,
  Croissant,
  Wheat,
  Candy,
  Snowflake,
  SprayCan,
  Scale,
  Calculator,
  TrendingDown,
  ShoppingBasket,
  // Jardín
  NotebookTabs,
  Headphones,
  HandHeart,
  Trophy,
  // Despacho (finanzas)
  Sandwich,
  PartyPopper,
  Pill,
  ShoppingBag,
  Briefcase,
  Gift,
  ArrowRightLeft,
  // Sala (viajes)
  PlaneTakeoff,
  TreePalm,
  Building2,
  Mountain,
  Globe,
  Hotel,
  CarTaxiFront,
  Ticket,
  Users,
  Car,
  // Entretenimiento
  Film,
  Tv,
  Puzzle,
  Scroll,
  Dices,
  // Garage y diario
  Bike,
  Truck,
  Landmark,
  Vote,
  FlaskConical,
  Hospital,
  Volleyball,
  Drama,
  RefreshCw,
  Cpu,
  Star,
  Hash,
  Atom,
  Archive,
  // Fondos de cielo y temas de la casa (selectores del editor)
  MoonStar,
  Orbit,
  Castle,
  Pyramid,
  Rocket,
  Ghost,
  // Reproducción, juegos y avisos (migración de emojis de UI)
  Play,
  Pause,
  Timer,
  Hourglass,
  TriangleAlert,
  Lock,
  Shuffle,
  Bomb,
  Banana,
  Flag,
  Coins,
  Compass,
  Luggage,
  Folder,
  Sprout,
  GitBranch,
  Crown,
  Spade,
  FerrisWheel,
  Joystick,
  Watch,
  Hand,
  Bell,
  Search,
  Sofa,
  Glasses,
  Skull,
  Rabbit,
  Music,
  Crosshair,
  ToyBrick,
  Hammer,
  Droplets,
  Frame,
  CircleDot,
  TreeDeciduous,
  // Editor de grafiti (juguete)
  Paintbrush,
  Eraser,
  Undo2,
  Save,
  PaintBucket,
  ChevronLeft,
  ChevronRight,
  // Rueda de herramientas, granja, huerto, canchas, prendas (auditoría jul 2026)
  Cable,
  Accessibility,
  Bubbles,
  ArrowLeft,
  Satellite,
  Guitar,
  Axe,
  Drill,
  Book,
  Amphora,
  Egg,
  PiggyBank,
  MountainSnow,
  Bath,
  Salad,
  Flower,
  Apple,
  Citrus,
  Balloon,
  CircleHelp,
  GraduationCap,
  Stethoscope,
  Speech,
  Pin,
  Spool,
  Pizza,
  Fish,
  Drumstick,
  Nut,
  Footprints,
  type LucideIcon,
} from 'lucide-react'

/**
 * Catálogo central de iconos de la interfaz. Cada entrada asocia un nombre
 * semántico con su emoji (estilo "emoji") y su SVG de lucide (estilo
 * "profesional"). El componente <Icono> elige según el ajuste `estiloIconos`.
 *
 * El mapa inverso emoji → nombre permite resolver emojis guardados en
 * catálogos de dominio o en la BD (p. ej. `cuarto.icon`) sin migrar datos.
 * ANTE EMOJIS REPETIDOS GANA LA PRIMERA ENTRADA: mantener el orden
 * chrome → cuartos → tabs → dominios.
 */

export interface DefIcono {
  emoji: string
  Svg: LucideIcon
}

export const CATALOGO = {
  // — Chrome (editor, HUD, menús, chat) —
  editar: { emoji: '✏️', Svg: Pencil },
  confirmar: { emoji: '✓', Svg: Check },
  cerrar: { emoji: '✕', Svg: X },
  enviar: { emoji: '➤', Svg: Send },
  compartir: { emoji: '📤', Svg: Share2 },
  herramienta: { emoji: '🔧', Svg: Wrench },
  casa: { emoji: '🏠', Svg: House },
  // Explosión de la casa: separar los pisos ↔ volver a juntarlos.
  pisosSeparar: { emoji: '🧇', Svg: Layers2 },
  pisosJuntar: { emoji: '🥞', Svg: Layers },
  progreso: { emoji: '📊', Svg: ChartColumn },
  cuartos: { emoji: '🚪', Svg: DoorOpen },
  inventario: { emoji: '🎒', Svg: Box },
  ajustes: { emoji: '⚙️', Svg: Settings },
  agregar: { emoji: '➕', Svg: Plus },
  quitar: { emoji: '➖', Svg: Minus },
  restaurar: { emoji: '♻️', Svg: RotateCcw },
  salud: { emoji: '❤️', Svg: Heart },
  energia: { emoji: '⚡', Svg: Zap },
  racha: { emoji: '🔥', Svg: Flame },
  registros: { emoji: '📖', Svg: BookOpen },
  chat: { emoji: '💬', Svg: MessageCircle },
  nota: { emoji: '🗒️', Svg: NotebookText },
  memoria: { emoji: '🧠', Svg: Brain },
  alarma: { emoji: '⏰', Svg: AlarmClock },
  pantallas: { emoji: '📵', Svg: MonitorOff },
  foto: { emoji: '📷', Svg: Camera },
  microfono: { emoji: '🎤', Svg: Mic },
  objetivo: { emoji: '🎯', Svg: Target },
  basura: { emoji: '🗑️', Svg: Trash2 },
  abajo: { emoji: '👇', Svg: ArrowDown },
  'rotar-izq': { emoji: '⟲', Svg: RotateCcw },
  'rotar-der': { emoji: '⟳', Svg: RotateCw },
  volver: { emoji: '‹', Svg: ChevronLeft },
  siguiente: { emoji: '›', Svg: ChevronRight },
  centrar: { emoji: '⌂', Svg: House },
  dia: { emoji: '☀️', Svg: Sun },
  noche: { emoji: '🌙', Svg: Moon },
  calendario: { emoji: '📅', Svg: CalendarDays },
  anecdotario: { emoji: '📒', Svg: NotebookPen },
  foco: { emoji: '💡', Svg: Lightbulb },
  ubicacion: { emoji: '📍', Svg: MapPin },
  lluvia: { emoji: '🌧️', Svg: CloudRain },
  humedad: { emoji: '💧', Svg: Droplet },
  viento: { emoji: '💨', Svg: Wind },
  paraguas: { emoji: '☔', Svg: Umbrella },
  amanecer: { emoji: '🌅', Svg: Sunrise },
  atardecer: { emoji: '🌇', Svg: Sunset },
  'clima-nublado': { emoji: '⛅', Svg: CloudSun },
  'clima-niebla': { emoji: '🌫️', Svg: CloudFog },
  'clima-llovizna': { emoji: '🌦️', Svg: CloudDrizzle },
  'clima-nieve': { emoji: '🌨️', Svg: CloudSnow },
  'clima-tormenta': { emoji: '⛈️', Svg: CloudLightning },
  'clima-variable': { emoji: '🌡️', Svg: Thermometer },
  subir: { emoji: '⬆️', Svg: ArrowUp },
  bajar: { emoji: '⬇️', Svg: ArrowDown },
  brillo: { emoji: '✨', Svg: Sparkles },
  apunta: { emoji: '☝️', Svg: Pointer },
  vinculo: { emoji: '🤝', Svg: Handshake },
  paleta: { emoji: '🎨', Svg: Palette },
  pincel: { emoji: '🖌️', Svg: Paintbrush },
  spray: { emoji: '🧴', Svg: SprayCan },
  borrador: { emoji: '🧽', Svg: Eraser },
  bote: { emoji: '🪣', Svg: PaintBucket },
  deshacer: { emoji: '↩️', Svg: Undo2 },
  guardar: { emoji: '💾', Svg: Save },
  // — Infraestructura del mapa (caminos, canchas, huerto) —
  construir: { emoji: '🏗️', Svg: Construction },
  pista: { emoji: '🏎️', Svg: Route },
  riel: { emoji: '🚂', Svg: TrainTrack },
  'montana-rusa': { emoji: '🎢', Svg: RollerCoaster },
  cancha: { emoji: '🏟️', Svg: LandPlot },
  parcela: { emoji: '🟫', Svg: Shovel },
  sembrar: { emoji: '🌱', Svg: Sprout },
  regadera: { emoji: '💧', Svg: Droplets },
  cosechar: { emoji: '🧺', Svg: ShoppingBasket },
  granja: { emoji: '🐄', Svg: Fence },
  animal: { emoji: '🐾', Svg: PawPrint },
  alimentar: { emoji: '🌾', Svg: Wheat },
  mimar: { emoji: '💗', Svg: HandHeart },
  accesorio: { emoji: '🧸', Svg: Volleyball },
  aspersor: { emoji: '💦', Svg: Droplets },
  regla: { emoji: '📐', Svg: Ruler },
  medida: { emoji: '📏', Svg: Ruler },
  ropa: { emoji: '👕', Svg: Shirt },
  perfil: { emoji: '👤', Svg: User },
  esfera: { emoji: '⚪', Svg: Circle },
  cilindro: { emoji: '🛢️', Svg: Cylinder },
  caja: { emoji: '⬛', Svg: Box },
  plano: { emoji: '⬜', Svg: RectangleHorizontal },
  duplicar: { emoji: '📄', Svg: Copy },
  vincular: { emoji: '🔗', Svg: Link },
  silla: { emoji: '🪑', Svg: Armchair },
  persona: { emoji: '🧍', Svg: PersonStanding },
  archivador: { emoji: '🗂️', Svg: FolderOpen },
  mapa: { emoji: '🗺️', Svg: MapIcon },
  imagen: { emoji: '🖼️', Svg: Image },
  multicolor: { emoji: '🌈', Svg: Rainbow },
  repetir: { emoji: '🔁', Svg: Repeat },

  // — Constructor de mapa (modos y accesos) —
  nube: { emoji: '☁️', Svg: Cloud },
  muro: { emoji: '🧱', Svg: BrickWall },
  ventana: { emoji: '🪟', Svg: Grid2x2 },
  pasto: { emoji: '🌿', Svg: Leaf },
  'piso-interior': { emoji: '🟫', Svg: Square },
  techo: { emoji: '🔺', Svg: Triangle },
  mover: { emoji: '✥', Svg: Move },
  expandir: { emoji: '⤢', Svg: Expand },
  escalera: { emoji: '🌀', Svg: Shell },
  elevador: { emoji: '🛗', Svg: SquareArrowUp },
  resbaladilla: { emoji: '💨', Svg: Wind },
  niveles: { emoji: '🪜', Svg: ArrowUpDown },

  // — Cuartos (mismo emoji que la plantilla en src/rooms/<id>/index.tsx) —
  'cuarto-cocina': { emoji: '🍳', Svg: ChefHat },
  'cuarto-ejercicio': { emoji: '💪', Svg: BicepsFlexed },
  'cuarto-descanso': { emoji: '🛏️', Svg: BedDouble },
  'cuarto-anecdotario': { emoji: '✍️', Svg: PenLine },
  'cuarto-despacho': { emoji: '💰', Svg: Wallet },
  'cuarto-biblioteca': { emoji: '📚', Svg: Library },
  'cuarto-entretenimiento': { emoji: '🎮', Svg: Gamepad2 },
  'cuarto-sala': { emoji: '✈️', Svg: Plane },
  'cuarto-jardin': { emoji: '🧘', Svg: Flower2 },
  'cuarto-diario': { emoji: '📰', Svg: Newspaper },
  'cuarto-bodega': { emoji: '📦', Svg: Package },

  // — Cocina (momentos, compras, metas) —
  comida: { emoji: '🍽️', Svg: Utensils },
  bebida: { emoji: '🥤', Svg: CupSoda },
  verduras: { emoji: '🥦', Svg: Carrot },
  carne: { emoji: '🥩', Svg: Beef },
  lacteos: { emoji: '🧀', Svg: Milk },
  pan: { emoji: '🍞', Svg: Croissant },
  cereal: { emoji: '🌾', Svg: Wheat },
  dulces: { emoji: '🍬', Svg: Candy },
  congelados: { emoji: '🧊', Svg: Snowflake },
  limpieza: { emoji: '🧻', Svg: SprayCan },
  balanza: { emoji: '⚖️', Svg: Scale },
  calculadora: { emoji: '🧮', Svg: Calculator },
  bajando: { emoji: '🔻', Svg: TrendingDown },
  canasta: { emoji: '🧺', Svg: ShoppingBasket },
  chef: { emoji: '👨‍🍳', Svg: ChefHat },

  // — Jardín (mindfulness) —
  cuaderno: { emoji: '📔', Svg: NotebookTabs },
  respiracion: { emoji: '🌬️', Svg: Wind },
  audifonos: { emoji: '🎧', Svg: Headphones },
  gratitud: { emoji: '🙏', Svg: HandHeart },
  trofeo: { emoji: '🏆', Svg: Trophy },

  // — Despacho (categorías de gasto/ingreso) —
  hamburguesa: { emoji: '🍔', Svg: Sandwich },
  fiesta: { emoji: '🎉', Svg: PartyPopper },
  pastilla: { emoji: '💊', Svg: Pill },
  bolsa: { emoji: '🛍️', Svg: ShoppingBag },
  maletin: { emoji: '💼', Svg: Briefcase },
  regalo: { emoji: '🎁', Svg: Gift },
  movimientos: { emoji: '💸', Svg: ArrowRightLeft },

  // — Sala (viajes) —
  despegue: { emoji: '🛫', Svg: PlaneTakeoff },
  playa: { emoji: '🏖️', Svg: TreePalm },
  ciudad: { emoji: '🏙️', Svg: Building2 },
  aventura: { emoji: '🥾', Svg: Mountain },
  mundo: { emoji: '🌍', Svg: Globe },
  hotel: { emoji: '🏨', Svg: Hotel },
  taxi: { emoji: '🚕', Svg: CarTaxiFront },
  boleto: { emoji: '🎫', Svg: Ticket },
  companeros: { emoji: '👥', Svg: Users },
  auto: { emoji: '🚗', Svg: Car },

  // — Idiomas —
  bocina: { emoji: '🔊', Svg: Volume2 },
  musica: { emoji: '🎵', Svg: Music },
  idiomas: { emoji: '🌐', Svg: Languages },

  // — Entretenimiento —
  pelicula: { emoji: '🎬', Svg: Film },
  serie: { emoji: '📺', Svg: Tv },
  estrategia: { emoji: '♟️', Svg: Puzzle },
  familia: { emoji: '👨‍👩‍👧', Svg: Users },
  rol: { emoji: '📜', Svg: Scroll },
  dados: { emoji: '🎲', Svg: Dices },

  // — Garage (vehículos) —
  bici: { emoji: '🚲', Svg: Bike },
  moto: { emoji: '🏍️', Svg: Bike },
  scooter: { emoji: '🛵', Svg: Bike },
  camioneta: { emoji: '🛻', Svg: Truck },

  // — Diario (categorías de noticias) —
  red: { emoji: '🌐', Svg: Globe },
  gobierno: { emoji: '🏛️', Svg: Landmark },
  voto: { emoji: '🗳️', Svg: Vote },
  tecnologia: { emoji: '💻', Svg: Laptop },
  ciencia: { emoji: '🔬', Svg: FlaskConical },
  hospital: { emoji: '🏥', Svg: Hospital },
  deportes: { emoji: '⚽', Svg: Volleyball },
  cultura: { emoji: '🎭', Svg: Drama },
  sincronizar: { emoji: '🔄', Svg: RefreshCw },
  chip: { emoji: '🖥️', Svg: Cpu },
  estrella: { emoji: '⭐', Svg: Star },
  montaña: { emoji: '⛰️', Svg: Mountain },
  gema: { emoji: '💎', Svg: Gem },

  // — Estilos de render y efectos visuales (Configuraciones › estilo del mapa) —
  'render-comic': { emoji: '💥', Svg: Zap },
  'render-miniatura': { emoji: '🔬', Svg: Microscope },
  'render-retro': { emoji: '👾', Svg: Gamepad2 },
  'render-neon': { emoji: '🌟', Svg: Star },
  'render-byn': { emoji: '⚫', Svg: Contrast },
  'render-sepia': { emoji: '🟤', Svg: Camera },
  'render-vineta': { emoji: '⭕', Svg: Aperture },

  // — Biblioteca (pilares) —
  numeros: { emoji: '🔢', Svg: Hash },
  atomo: { emoji: '⚛️', Svg: Atom },
  rompecabezas: { emoji: '🧩', Svg: Puzzle },
  archivo: { emoji: '🗄️', Svg: Archive },

  // — Fondos de cielo y temas de la casa (selectores del editor) —
  'luna-nueva': { emoji: '🌑', Svg: MoonStar },
  galaxia: { emoji: '🌌', Svg: Sparkles },
  planeta: { emoji: '🪐', Svg: Orbit },
  castillo: { emoji: '🏰', Svg: Castle },
  desierto: { emoji: '🏜️', Svg: Pyramid },
  'ciudad-noche': { emoji: '🌃', Svg: Building2 },
  nieve: { emoji: '❄️', Svg: Snowflake },
  cohete: { emoji: '🚀', Svg: Rocket },
  telaraña: { emoji: '🕸️', Svg: Ghost },
  corazon: { emoji: '💖', Svg: Heart },
  navidad: { emoji: '🎄', Svg: TreePine },

  // — Tabs y acciones comunes de las apps —
  'tab-diario': { emoji: '📝', Svg: SquarePen },
  'tab-recetas': { emoji: '🍲', Svg: CookingPot },
  'tab-compras': { emoji: '🛒', Svg: ShoppingCart },
  'tab-fuerza': { emoji: '🏋️', Svg: Dumbbell },
  'tab-cardio': { emoji: '🏃', Svg: Activity },
  hecho: { emoji: '✅', Svg: CircleCheck },
  lista: { emoji: '📋', Svg: ClipboardList },
  rejilla: { emoji: '▦', Svg: Grid3x3 },
  ver: { emoji: '👀', Svg: Eye },
  tendencia: { emoji: '📈', Svg: TrendingUp },
  etiqueta: { emoji: '🏷️', Svg: Tag },

  // — Temas de UI (selector en Configuraciones) —
  'tema-neon': { emoji: '🟣', Svg: Sparkles },
  'tema-bosque': { emoji: '🌲', Svg: TreePine },
  'tema-ambar': { emoji: '🟠', Svg: Sunset },
  'tema-ciruela': { emoji: '🟪', Svg: Grape },

  // — Proveedores de IA (chat) —
  'ia-claude': { emoji: '✴️', Svg: Sparkle },
  'ia-gemini': { emoji: '♊', Svg: Gem },
  'ia-chatgpt': { emoji: '🟢', Svg: Sparkles },
  'ia-deepseek': { emoji: '🐋', Svg: Waves },
  'ia-local': { emoji: '💻', Svg: Laptop },

  // — Mascotas / asistentes —
  'mascota-mago': { emoji: '🧙', Svg: WandSparkles },
  'mascota-gato': { emoji: '🐱', Svg: Cat },
  'mascota-perro': { emoji: '🐶', Svg: Dog },
  'mascota-buho': { emoji: '🦉', Svg: Bird },
  'mascota-robot': { emoji: '🤖', Svg: Bot },

  // — Reproducción, juegos y avisos (migración de emojis de UI, jul 2026) —
  play: { emoji: '▶️', Svg: Play },
  pausa: { emoji: '⏸️', Svg: Pause },
  detener: { emoji: '⏹️', Svg: Square },
  cronometro: { emoji: '⏱️', Svg: Timer },
  'reloj-arena': { emoji: '⏳', Svg: Hourglass },
  alerta: { emoji: '⚠️', Svg: TriangleAlert },
  candado: { emoji: '🔒', Svg: Lock },
  barajar: { emoji: '🔀', Svg: Shuffle },
  bomba: { emoji: '💣', Svg: Bomb },
  banana: { emoji: '🍌', Svg: Banana },
  bandera: { emoji: '🚩', Svg: Flag },
  moneda: { emoji: '🪙', Svg: Coins },
  brujula: { emoji: '🧭', Svg: Compass },
  maleta: { emoji: '🧳', Svg: Luggage },
  carpeta: { emoji: '📁', Svg: Folder },
  flor: { emoji: '🌼', Svg: Flower2 },
  semilla: { emoji: '🌱', Svg: Sprout },
  rama: { emoji: '🌿', Svg: GitBranch },
  sombrero: { emoji: '🎩', Svg: Crown },
  naipe: { emoji: '🃏', Svg: Spade },
  'rueda-fortuna': { emoji: '🎡', Svg: FerrisWheel },
  joystick: { emoji: '🕹️', Svg: Joystick },
  'reloj-pulsera': { emoji: '⌚', Svg: Watch },
  mano: { emoji: '✋', Svg: Hand },
  campana: { emoji: '🔔', Svg: Bell },
  lupa: { emoji: '🔍', Svg: Search },
  sofa: { emoji: '🛋️', Svg: Sofa },
  captura: { emoji: '📸', Svg: Camera },
  periodico: { emoji: '🗞️', Svg: Newspaper },
  divisas: { emoji: '💱', Svg: ArrowRightLeft },
  saltar: { emoji: '🦘', Svg: Rabbit },
  bailar: { emoji: '💃', Svg: Music },
  laser: { emoji: '🔫', Svg: Crosshair },
  juguete: { emoji: '🧸', Svg: ToyBrick },

  // — Muebles del catálogo de recursos (modelosRecursos.tsx, F4) —
  taller: { emoji: '🛠️', Svg: Hammer },
  fregadero: { emoji: '🚰', Svg: Droplets },
  espejo: { emoji: '🪞', Svg: Frame },
  billar: { emoji: '🎱', Svg: CircleDot },
  arbol: { emoji: '🌳', Svg: TreeDeciduous },
  'placa-verde': { emoji: '🟩', Svg: Square },

  // — Emociones (pickers de ánimo y estados del personaje) —
  'animo-sereno': { emoji: '😌', Svg: Smile },
  'animo-contento': { emoji: '🙂', Svg: SmilePlus },
  'animo-neutral': { emoji: '😐', Svg: Meh },
  'animo-triste': { emoji: '😔', Svg: Frown },
  'animo-ansioso': { emoji: '😰', Svg: Annoyed },
  'animo-genial': { emoji: '🤩', Svg: Laugh },
  'animo-dormido': { emoji: '😴', Svg: Moon },
  'animo-enojado': { emoji: '😤', Svg: Angry },
  'animo-feliz': { emoji: '😄', Svg: Laugh },
  'animo-llorando': { emoji: '😢', Svg: Frown },
  'animo-sonriente': { emoji: '😀', Svg: Laugh },
  'animo-frustrado': { emoji: '😣', Svg: Annoyed },
  'animo-cool': { emoji: '😎', Svg: Glasses },
  'animo-ko': { emoji: '😵', Svg: Skull },
  'animo-descontento': { emoji: '😕', Svg: Annoyed },
  'animo-alegre': { emoji: '😊', Svg: Laugh },

  // — Rueda de herramientas (movimientos y juguetes) —
  cuerda: { emoji: '🪢', Svg: Cable },
  mortal: { emoji: '🤸', Svg: Accessibility },
  saludar: { emoji: '👋', Svg: Hand },
  fuegos: { emoji: '🎆', Svg: Sparkles },
  burbujas: { emoji: '🫧', Svg: Bubbles },
  // 🧊 pertenece a 'congelados' (cocina) en el mapa inverso: el centro de la
  // rueda usa este nombre explícito para mostrar un cubo y no un copo.
  'cubo-vistas': { emoji: '🧊', Svg: Box },
  atras: { emoji: '←', Svg: ArrowLeft },
  ovni: { emoji: '🛸', Svg: Satellite },

  // — Objetos del catálogo de muebles (chips de creación del chat) —
  guitarra: { emoji: '🎸', Svg: Guitar },
  madera: { emoji: '🪵', Svg: Axe },
  'caja-herramientas': { emoji: '🧰', Svg: Drill },
  libro: { emoji: '📕', Svg: Book },
  maceta: { emoji: '🪴', Svg: Amphora },

  // — Granja y huerto —
  gallina: { emoji: '🐔', Svg: Egg },
  cerdo: { emoji: '🐷', Svg: PiggyBank },
  cabra: { emoji: '🐐', Svg: MountainSnow },
  oveja: { emoji: '🐑', Svg: Cloud },
  dormir: { emoji: '💤', Svg: Moon },
  tina: { emoji: '🛁', Svg: Bath },
  zanahoria: { emoji: '🥕', Svg: Carrot },
  lechuga: { emoji: '🥬', Svg: Salad },
  girasol: { emoji: '🌻', Svg: Flower },
  tomate: { emoji: '🍅', Svg: Apple },
  maiz: { emoji: '🌽', Svg: Wheat },
  calabaza: { emoji: '🎃', Svg: Citrus },

  // — Canchas —
  'pelota-tenis': { emoji: '🎾', Svg: CircleDot },
  basquet: { emoji: '🏀', Svg: Circle },

  // — Prendas del editor de personajes —
  lentes: { emoji: '🕶️', Svg: Glasses },
  chamarra: { emoji: '🧥', Svg: Layers },
  pantalon: { emoji: '👖', Svg: PersonStanding },
  calzado: { emoji: '👟', Svg: Footprints },

  // — Jardín (etapas de calma y meditación) —
  bellota: { emoji: '🌰', Svg: Nut },
  'flor-cerezo': { emoji: '🌸', Svg: Flower2 },
  paisaje: { emoji: '🏞️', Svg: Mountain },
  olas: { emoji: '🌊', Svg: Waves },

  // — Animación y varios de UI —
  globo: { emoji: '🎈', Svg: Balloon },
  'meta-carrera': { emoji: '🏁', Svg: Flag },
  ayuda: { emoji: '❓', Svg: CircleHelp },
  tutorial: { emoji: '🎓', Svg: GraduationCap },
  estetoscopio: { emoji: '🩺', Svg: Stethoscope },
  hablar: { emoji: '🗣️', Svg: Speech },
  pin: { emoji: '📌', Svg: Pin },
  'tema-oeste': { emoji: '🤠', Svg: Sunset },
  estambre: { emoji: '🧶', Svg: Spool },
  'bandera-blanca': { emoji: '🏳️', Svg: Flag },
  via: { emoji: '🛤️', Svg: TrainTrack },

  // — Comida (recetas sembradas y ejemplos) —
  ensalada: { emoji: '🥗', Svg: Salad },
  pizza: { emoji: '🍕', Svg: Pizza },
  pescado: { emoji: '🐟', Svg: Fish },
  pollo: { emoji: '🍗', Svg: Drumstick },
} satisfies Record<string, DefIcono>

export type NombreIcono = keyof typeof CATALOGO

/** Normaliza selectores de variación (FE0F) para que '✏️' y '✏' coincidan. */
const clave = (emoji: string) => emoji.replace(/\uFE0F/g, '')

const EMOJI_A_NOMBRE = new Map<string, NombreIcono>()
for (const [nombre, def] of Object.entries(CATALOGO) as [NombreIcono, DefIcono][]) {
  const k = clave(def.emoji)
  if (!EMOJI_A_NOMBRE.has(k)) EMOJI_A_NOMBRE.set(k, nombre)
}

/** Nombre del catálogo para un emoji dado (o null si no tiene equivalente). */
export function iconoDe(emoji: string): NombreIcono | null {
  return EMOJI_A_NOMBRE.get(clave(emoji)) ?? null
}
