import {
  // Sala de cómputo
  Sigma,
  Redo2,
  ClipboardPaste,
  Bold,
  AlignLeft,
  AlignCenter,
  AlignRight,
  ChartSpline,
  ChartLine,
  ChartArea,
  ChartPie,
  ChartScatter,
  Radical,
  Table,
  Printer,
  Download,
  // Chrome
  Pencil,
  Check,
  Wrench,
  House,
  Layers,
  Layers2,
  ChartColumn,
  Funnel,
  DoorOpen,
  Settings,
  Plus,
  Minus,
  Heart,
  Zap,
  Flame,
  BookOpen,
  MessageCircle,
  NotebookText,
  Brain,
  Bone,
  AlarmClock,
  MonitorOff,
  Camera,
  Mic,
  Target,
  Trash2,
  ArrowDown,
  RotateCcw,
  RotateCw,
  Sun,
  Moon,
  CalendarDays,
  NotebookPen,
  Sparkles,
  Waves,
  Laptop,
  Volume2,
  Languages,
  X,
  Send,
  Share2,
  Microscope,
  Contrast,
  Aperture,
  // Infraestructura del mapa
  Construction,
  Route,
  TrainTrack,
  RollerCoaster,
  LandPlot,
  Shovel,
  Fence,
  PawPrint,
  // Cuartos
  ChefHat,
  BicepsFlexed,
  BedDouble,
  PenLine,
  Wallet,
  Library,
  Gamepad2,
  Plane,
  Flower2,
  Newspaper,
  Package,
  // Tabs y acciones comunes
  SquarePen,
  CookingPot,
  ShoppingCart,
  Dumbbell,
  Activity,
  CircleCheck,
  ClipboardList,
  Eye,
  EyeOff,
  TrendingUp,
  Tag,
  // Temas de UI
  TreePine,
  Sunset,
  Grape,
  // Mascotas y estados
  WandSparkles,
  Cat,
  Dog,
  Bird,
  Bot,
  Smile,
  SmilePlus,
  Meh,
  Frown,
  Laugh,
  Angry,
  Annoyed,
  ThumbsUp,
  // Chrome ampliado (ciclo, constructor, chat)
  Lightbulb,
  MapPin,
  CloudRain,
  Droplet,
  Wind,
  Umbrella,
  Sunrise,
  CloudSun,
  CloudFog,
  CloudDrizzle,
  CloudSnow,
  CloudLightning,
  Thermometer,
  ArrowUp,
  Cloud,
  BrickWall,
  Grid2x2,
  Grid3x3,
  Columns3,
  Leaf,
  Square,
  Triangle,
  Move,
  Expand,
  Shell,
  SquareArrowUp,
  ArrowUpDown,
  Rainbow,
  Image,
  FileText,
  Map as MapIcon,
  Pointer,
  Handshake,
  Repeat,
  Palette,
  Ruler,
  Armchair,
  PersonStanding,
  FolderOpen,
  Sparkle,
  Gem,
  Shirt,
  User,
  Circle,
  Cylinder,
  Copy,
  Link,
  Box,
  RectangleHorizontal,
  // Cocina
  Utensils,
  CupSoda,
  Carrot,
  Beef,
  Milk,
  Croissant,
  Wheat,
  Candy,
  Snowflake,
  SprayCan,
  Brush,
  Scale,
  Calculator,
  TrendingDown,
  ShoppingBasket,
  // Jardín
  NotebookTabs,
  Headphones,
  HandHeart,
  Trophy,
  // Despacho (finanzas)
  Sandwich,
  PartyPopper,
  Pill,
  ShoppingBag,
  Briefcase,
  Gift,
  ArrowRightLeft,
  // Sala (viajes)
  PlaneTakeoff,
  TreePalm,
  Building2,
  Mountain,
  Globe,
  Hotel,
  CarTaxiFront,
  Ticket,
  Users,
  Car,
  // Agenda (trabajo, salud y personas)
  CalendarClock,
  Phone,
  Mail,
  Cake,
  // Entretenimiento
  Film,
  Tv,
  Puzzle,
  Scroll,
  Dices,
  // Garage y diario
  Bike,
  Truck,
  Landmark,
  Vote,
  FlaskConical,
  Hospital,
  Volleyball,
  Drama,
  RefreshCw,
  Cpu,
  Star,
  Hash,
  Atom,
  Archive,
  // Fondos de cielo y temas de la casa (selectores del editor)
  MoonStar,
  Orbit,
  Castle,
  Pyramid,
  Rocket,
  Ghost,
  // Reproducción, juegos y avisos (migración de emojis de UI)
  Play,
  Pause,
  Timer,
  Hourglass,
  TriangleAlert,
  Lock,
  Shuffle,
  Bomb,
  Banana,
  Flag,
  Coins,
  Compass,
  Luggage,
  Folder,
  Sprout,
  GitBranch,
  Waypoints,
  Workflow,
  Blend,
  GitCompare,
  Braces,
  Crown,
  Spade,
  FerrisWheel,
  Joystick,
  Watch,
  Hand,
  Bell,
  Search,
  Sofa,
  Glasses,
  Skull,
  Rabbit,
  Music,
  Crosshair,
  ToyBrick,
  Hammer,
  Droplets,
  Frame,
  CircleDot,
  CircleDashed,
  TreeDeciduous,
  // Editor de grafiti (juguete)
  Paintbrush,
  Eraser,
  Undo2,
  Save,
  PaintBucket,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  // Rueda de herramientas, granja, huerto, canchas, prendas (auditoría jul 2026)
  Cable,
  Accessibility,
  Bubbles,
  ArrowLeft,
  ArrowRight,
  Satellite,
  Guitar,
  Axe,
  Drill,
  Book,
  Amphora,
  Egg,
  PiggyBank,
  MountainSnow,
  Bath,
  Salad,
  Flower,
  Apple,
  Citrus,
  Balloon,
  CircleHelp,
  GraduationCap,
  Stethoscope,
  Speech,
  Pin,
  Spool,
  Pizza,
  Fish,
  Drumstick,
  Nut,
  Footprints,
  // Mascotas de la agenda (especies y cuidados)
  Rat,
  Syringe,
  Bug,
  // Auditoría de estilo de iconos (jul 2026): prendas, rostros, peinados,
  // cuerpos, techos/pisos, recetas y juegos que se quedaban en emoji.
  Ribbon,
  HardHat,
  Bookmark,
  Shield,
  ShieldCheck,
  IdCard,
  Venus,
  Scissors,
  Ban,
  ScanFace,
  Rows3,
  Disc,
  Disc3,
  Feather,
  Soup,
  VenetianMask,
  Shrub,
  Rose,
  Stone,
  Warehouse,
  Bolt,
  Milestone,
  Church,
  Tent,
  SquareDashed,
  UtensilsCrossed,
  LoaderPinwheel,
  Worm,
  Turtle,
  Table2,
  TrafficCone,
  VolumeX,
  Rows2,
  type LucideIcon,
} from 'lucide-react'
import type { NombreIcono } from './catalogo'

/**
 * Los SVG de lucide del catálogo de iconos, en módulo APARTE: 448 componentes
 * que solo hacen falta en estilo "profesional". Lo carga `svgStore.ts` con
 * import(); en estilo "emoji" jamás se descarga.
 *
 * `Record<NombreIcono, LucideIcon>` exige exactamente las claves de EMOJIS:
 * un icono nuevo sin su SVG (o al revés) no compila.
 */
export const SVGS: Record<NombreIcono, LucideIcon> = {
  // — Chrome (editor, HUD, menús, chat) —
  editar: Pencil,
  confirmar: Check,
  cerrar: X,
  enviar: Send,
  compartir: Share2,
  herramienta: Wrench,
  casa: House,
  // Explosión de la casa: separar los pisos ↔ volver a juntarlos.
  pisosSeparar: Layers2,
  pisosJuntar: Layers,
  progreso: ChartColumn,
  filtro: Funnel,
  cuartos: DoorOpen,
  inventario: Box,
  ajustes: Settings,
  agregar: Plus,
  quitar: Minus,
  restaurar: RotateCcw,
  salud: Heart,
  energia: Zap,
  racha: Flame,
  registros: BookOpen,
  chat: MessageCircle,
  nota: NotebookText,
  memoria: Brain,
  alarma: AlarmClock,
  pantallas: MonitorOff,
  foto: Camera,
  pdf: FileText,
  mascara: Drama,
  'chat-ar': ScanFace,
  microfono: Mic,
  objetivo: Target,
  basura: Trash2,
  abajo: ArrowDown,
  'rotar-izq': RotateCcw,
  'rotar-der': RotateCw,
  volver: ChevronLeft,
  siguiente: ChevronRight,
  // Chevrons de plegable (los `▸/▾` que antes iban crudos en los botones).
  plegado: ChevronRight,
  desplegado: ChevronDown,
  centrar: House,
  dia: Sun,
  noche: Moon,
  calendario: CalendarDays,
  anecdotario: NotebookPen,
  foco: Lightbulb,
  ubicacion: MapPin,
  lluvia: CloudRain,
  humedad: Droplet,
  viento: Wind,
  paraguas: Umbrella,
  amanecer: Sunrise,
  atardecer: Sunset,
  'clima-nublado': CloudSun,
  'clima-niebla': CloudFog,
  'clima-llovizna': CloudDrizzle,
  'clima-nieve': CloudSnow,
  'clima-tormenta': CloudLightning,
  'clima-variable': Thermometer,
  subir: ArrowUp,
  bajar: ArrowDown,
  izquierda: ArrowLeft,
  derecha: ArrowRight,
  brillo: Sparkles,
  apunta: Pointer,
  vinculo: Handshake,
  paleta: Palette,
  pincel: Paintbrush,
  spray: SprayCan,
  borrador: Eraser,
  bote: PaintBucket,
  deshacer: Undo2,
  guardar: Save,
  // — Infraestructura del mapa (caminos, canchas, huerto) —
  construir: Construction,
  pista: Route,
  riel: TrainTrack,
  'montana-rusa': RollerCoaster,
  cancha: LandPlot,
  paintball: CircleDot,
  parcela: Shovel,
  sembrar: Sprout,
  regadera: Droplets,
  cosechar: ShoppingBasket,
  granja: Fence,
  animal: PawPrint,
  alimentar: Wheat,
  mimar: HandHeart,
  curar: Pill,
  escoba: Brush,
  accesorio: Volleyball,
  aspersor: Droplets,
  regla: Ruler,
  medida: Ruler,
  ropa: Shirt,
  perfil: User,
  esfera: Circle,
  cilindro: Cylinder,
  caja: Box,
  plano: RectangleHorizontal,
  duplicar: Copy,
  vincular: Link,
  silla: Armchair,
  persona: PersonStanding,
  archivador: FolderOpen,
  mapa: MapIcon,
  imagen: Image,
  multicolor: Rainbow,
  repetir: Repeat,

  // — Constructor de mapa (modos y accesos) —
  nube: Cloud,
  muro: BrickWall,
  ventana: Grid2x2,
  pasto: Leaf,
  'piso-interior': Square,
  techo: Triangle,
  mover: Move,
  expandir: Expand,
  escalera: Shell,
  elevador: SquareArrowUp,
  resbaladilla: Wind,
  niveles: ArrowUpDown,

  // — Cuartos (mismo emoji que la plantilla en src/rooms/<id>/index.tsx) —
  'cuarto-cocina': ChefHat,
  'cuarto-ejercicio': BicepsFlexed,
  'cuarto-descanso': BedDouble,
  'cuarto-anecdotario': PenLine,
  'cuarto-despacho': Wallet,
  'cuarto-biblioteca': Library,
  'cuarto-entretenimiento': Gamepad2,
  'cuarto-sala': Plane,
  'cuarto-jardin': Flower2,
  'cuarto-diario': Newspaper,
  'cuarto-bodega': Package,

  // — Cocina (momentos, compras, metas) —
  comida: Utensils,
  bebida: CupSoda,
  verduras: Carrot,
  carne: Beef,
  lacteos: Milk,
  pan: Croissant,
  cereal: Wheat,
  dulces: Candy,
  congelados: Snowflake,
  limpieza: SprayCan,
  balanza: Scale,
  calculadora: Calculator,
  bajando: TrendingDown,
  canasta: ShoppingBasket,
  chef: ChefHat,

  // — Jardín (mindfulness) —
  cuaderno: NotebookTabs,
  respiracion: Wind,
  audifonos: Headphones,
  gratitud: HandHeart,
  trofeo: Trophy,

  // — Despacho (categorías de gasto/ingreso) —
  hamburguesa: Sandwich,
  fiesta: PartyPopper,
  pastilla: Pill,
  bolsa: ShoppingBag,
  maletin: Briefcase,
  regalo: Gift,
  movimientos: ArrowRightLeft,

  // — Sala (viajes) —
  despegue: PlaneTakeoff,
  playa: TreePalm,
  ciudad: Building2,
  aventura: Mountain,
  mundo: Globe,
  hotel: Hotel,
  taxi: CarTaxiFront,
  boleto: Ticket,
  companeros: Users,
  auto: Car,

  // — Agenda (trabajo, salud y personas) —
  agenda: CalendarClock,
  telefono: Phone,
  correo: Mail,
  pastel: Cake,

  // — Idiomas —
  bocina: Volume2,
  musica: Music,
  idiomas: Languages,

  // — Entretenimiento —
  pelicula: Film,
  serie: Tv,
  estrategia: Puzzle,
  familia: Users,
  rol: Scroll,
  dados: Dices,

  // — Garage (vehículos) —
  bici: Bike,
  moto: Bike,
  scooter: Bike,
  camioneta: Truck,

  // — Diario (categorías de noticias) —
  red: Globe,
  gobierno: Landmark,
  voto: Vote,
  tecnologia: Laptop,
  ciencia: FlaskConical,
  hospital: Hospital,
  deportes: Volleyball,
  cultura: Drama,
  sincronizar: RefreshCw,
  chip: Cpu,
  estrella: Star,
  montaña: Mountain,
  gema: Gem,

  // — Estilos de render y efectos visuales (Configuraciones › estilo del mapa) —
  'render-comic': Zap,
  'render-miniatura': Microscope,
  'render-retro': Gamepad2,
  'render-neon': Star,
  'render-byn': Contrast,
  'render-sepia': Camera,
  'render-vineta': Aperture,

  // — Biblioteca (pilares) —
  numeros: Hash,
  atomo: Atom,
  rompecabezas: Puzzle,
  archivo: Archive,

  // — Fondos de cielo y temas de la casa (selectores del editor) —
  'luna-nueva': MoonStar,
  galaxia: Sparkles,
  planeta: Orbit,
  castillo: Castle,
  desierto: Pyramid,
  'ciudad-noche': Building2,
  nieve: Snowflake,
  cohete: Rocket,
  telaraña: Ghost,
  corazon: Heart,
  navidad: TreePine,

  // — Tabs y acciones comunes de las apps —
  'tab-diario': SquarePen,
  'tab-recetas': CookingPot,
  'tab-compras': ShoppingCart,
  'tab-fuerza': Dumbbell,
  'tab-cardio': Activity,
  hecho: CircleCheck,
  lista: ClipboardList,
  rejilla: Grid3x3,
  tablero: Columns3,
  ver: Eye,
  ocultar: EyeOff,
  tendencia: TrendingUp,
  etiqueta: Tag,

  // — Sala de cómputo —
  rehacer: Redo2,
  cortar: Scissors,
  pegar: ClipboardPaste,
  negrita: Bold,
  alinearIzq: AlignLeft,
  alinearCentro: AlignCenter,
  alinearDer: AlignRight,
  ordenar: ArrowUpDown,
  sigma: Sigma,
  funcion: ChartSpline,
  // Gráficas de las hojas de cálculo (una por tipo, para el selector)
  grafica: ChartColumn,
  graficaLineas: ChartLine,
  graficaArea: ChartArea,
  graficaPastel: ChartPie,
  graficaDispersion: ChartScatter,
  raiz: Radical,
  hoja: Table,
  imprimir: Printer,
  descargar: Download,

  // — Temas de UI (selector en Configuraciones) —
  'tema-neon': Sparkles,
  'tema-bosque': TreePine,
  'tema-ambar': Sunset,
  'tema-ciruela': Grape,

  // — Proveedores de IA (chat) —
  'ia-claude': Sparkle,
  'ia-gemini': Gem,
  'ia-chatgpt': Sparkles,
  'ia-local': Laptop,

  // — Mascotas / asistentes —
  'mascota-mago': WandSparkles,
  'mascota-gato': Cat,
  'mascota-perro': Dog,
  'mascota-buho': Bird,
  'mascota-robot': Bot,

  // — Reproducción, juegos y avisos (migración de emojis de UI, jul 2026) —
  play: Play,
  pausa: Pause,
  detener: Square,
  cronometro: Timer,
  'reloj-arena': Hourglass,
  alerta: TriangleAlert,
  candado: Lock,
  barajar: Shuffle,
  bomba: Bomb,
  banana: Banana,
  bandera: Flag,
  moneda: Coins,
  brujula: Compass,
  maleta: Luggage,
  carpeta: Folder,
  flor: Flower2,
  semilla: Sprout,
  rama: GitBranch,
  nodos: Waypoints,
  flujo: Workflow,
  venn: Blend,
  comparar: GitCompare,
  llaves: Braces,
  sombrero: Crown,
  naipe: Spade,
  'rueda-fortuna': FerrisWheel,
  joystick: Joystick,
  'reloj-pulsera': Watch,
  mano: Hand,
  campana: Bell,
  lupa: Search,
  sofa: Sofa,
  captura: Camera,
  periodico: Newspaper,
  divisas: ArrowRightLeft,
  saltar: Rabbit,
  bailar: Music,
  laser: Crosshair,
  juguete: ToyBrick,

  // — Muebles del catálogo de recursos (modelosRecursos.tsx, F4) —
  taller: Hammer,
  fregadero: Droplets,
  espejo: Frame,
  billar: CircleDot,
  arbol: TreeDeciduous,
  'placa-verde': Square,

  // — Emociones (pickers de ánimo y estados del personaje) —
  'animo-sereno': Smile,
  'animo-contento': SmilePlus,
  'animo-neutral': Meh,
  'animo-triste': Frown,
  'animo-ansioso': Annoyed,
  'animo-genial': Laugh,
  'animo-dormido': Moon,
  'animo-enojado': Angry,
  'animo-feliz': Laugh,
  'animo-llorando': Frown,
  'animo-sonriente': Laugh,
  'animo-frustrado': Annoyed,
  'animo-cool': Glasses,
  'animo-ko': Skull,
  'animo-descontento': Annoyed,
  'animo-alegre': Laugh,

  // — Rueda de herramientas (movimientos y juguetes) —
  cuerda: Cable,
  mortal: Accessibility,
  saludar: Hand,
  fuegos: Sparkles,
  burbujas: Bubbles,
  // 🧊 pertenece a 'congelados' (cocina) en el mapa inverso: el centro de la
  // rueda usa este nombre explícito para mostrar un cubo y no un copo.
  'cubo-vistas': Box,
  atras: ArrowLeft,
  ovni: Satellite,

  // — Objetos del catálogo de muebles (chips de creación del chat) —
  guitarra: Guitar,
  madera: Axe,
  'caja-herramientas': Drill,
  libro: Book,
  maceta: Amphora,

  // — Granja y huerto —
  gallina: Egg,
  cerdo: PiggyBank,
  cabra: MountainSnow,
  oveja: Cloud,
  caballo: Wind,
  dormir: Moon,
  tina: Bath,
  zanahoria: Carrot,
  lechuga: Salad,
  girasol: Flower,
  tomate: Apple,
  maiz: Wheat,
  calabaza: Citrus,

  // — Canchas —
  'pelota-tenis': CircleDot,
  basquet: Circle,
  beisbol: CircleDashed,

  // — Prendas del editor de personajes —
  lentes: Glasses,
  chamarra: Layers,
  pantalon: PersonStanding,
  calzado: Footprints,

  // — Jardín (etapas de calma y meditación) —
  bellota: Nut,
  'flor-cerezo': Flower2,
  paisaje: Mountain,
  olas: Waves,

  // — Animación y varios de UI —
  globo: Balloon,
  'meta-carrera': Flag,
  ayuda: CircleHelp,
  tutorial: GraduationCap,
  estetoscopio: Stethoscope,
  // Especialidades médicas de la Agenda. Lucide no trae diente: la sonrisa es lo
  // más cercano y se entiende en la fila de la cita.
  diente: Smile,
  hueso: Bone,
  chincheta: Pin,
  ciclo: Droplet,

  // — Mascotas de la agenda (🐶, 🐱, 🐟, 🐴 y 🐾 ya los resuelven otras entradas) —
  ave: Bird,
  roedor: Rat,
  reptil: Turtle,
  vacuna: Syringe,
  desparasitar: Bug,
  tijeras: Scissors,
  hablar: Speech,
  pin: Pin,
  'tema-oeste': Sunset,
  estambre: Spool,
  'bandera-blanca': Flag,
  via: TrainTrack,

  // — Comida (recetas sembradas y ejemplos) —
  ensalada: Salad,
  pizza: Pizza,
  pescado: Fish,
  pollo: Drumstick,

  // — Prendas y rostros del editor de personajes (apariencia.ts) —
  bufanda: Rows3,
  'gorro-chef': ChefHat,
  gorra: HardHat,
  corbata: Bookmark,
  camisa: Shirt,
  capa: Shield,
  vestido: Venus,
  falda: Triangle,
  shorts: PersonStanding,
  guantes: Hand,
  'cara-sorpresa': ScanFace,
  'cara-guino': Smile,
  'cara-serio': Angry,
  'cara-ternura': Heart,
  'cara-enojo': Angry,
  aprobar: ThumbsUp,

  // — Peinados (apariencia.ts) —
  'sin-pelo': Ban,
  'pelo-corto': Scissors,
  'pelo-puntas': Sparkle,
  'pelo-coleta': Ribbon,
  'pelo-chongo': Disc3,
  'pelo-largo': Waves,
  'pelo-mohawk': Feather,
  tazon: Soup,

  // — Cuerpos preset (cuerpos.ts) —
  astronauta: Rocket,
  ninja: VenetianMask,
  alien: Ghost,
  princesa: Crown,

  // — Plantas del catálogo de recursos (modelosRecursos.tsx) —
  hibisco: Flower2,
  cactus: Shrub,
  hojas: Leaf,
  tulipan: Rose,
  marchito: Flower,

  // — Materiales y formas de techo/piso (techos.ts, pisos.ts) —
  piedra: Stone,
  'casa-jardin': House,
  baldosa: SquareDashed,
  ruina: Warehouse,
  metal: Bolt,
  lapida: Milestone,
  cupula: Church,
  choza: Tent,

  // — Recetas sembradas (cocina/ejemplos.ts) —
  pasta: UtensilsCrossed,
  taco: Sandwich,
  wrap: Salad,

  // — Juegos de la mesa digital (juegos/catalogo.ts) —
  'ficha-roja': Circle,
  picas: Spade,
  ruleta: LoaderPinwheel,
  vibora: Worm,
  dinosaurio: Turtle,
  pingpong: Table2,
  hockey: Disc,
  'ficha-amarilla': Grid3x3,
  semaforo: TrafficCone,
  domino: Rows2,

  // — Trámites del garaje (seguro y tarjeta de circulación) —
  escudo: ShieldCheck,
  tarjeta: IdCard,

  // — Sueltos que aún caían en emoji —
  hilo: Spool,
  silencio: VolumeX,
}
