// Generado por `npm run ejemplos:texto` — no lo edites a mano.
// Contenido del ejemplo de fábrica de descanso, en los dos idiomas. Vive aparte
// de `dict.ts` a propósito: en cuanto se crea es dato del usuario, no interfaz.

export const TEXTOS_DESCANSO = {
  es: {
    notaBuena: 'Cena ligera y sin móvil en la cama. Del tirón.',
    notaRegular: 'Me desperté a las 4 pero volví a dormirme.',
    notaMala: 'El vecino de arriba con la lavadora a las 2.',
    notaCorta: 'Serie hasta la 1:30 y el despertador a las 6.',
    notaSiesta: 'Siesta de 25 min en el sofá y como nueva.',
  },
  en: {
    notaBuena: 'Light dinner, no phone in bed. Out like a light.',
    notaRegular: 'Woke up at 4 but managed to drift back off.',
    notaMala: 'Upstairs neighbour ran the washer at 2am.',
    notaCorta: 'One more episode till 1:30, alarm at 6.',
    notaSiesta: 'Twenty-minute nap on the couch and I was fine.',
  },
  pt: {
    notaBuena: 'Jantar leve e sem celular na cama. Dormi a noite toda.',
    notaRegular: 'Acordei às 4 mas consegui voltar a dormir.',
    notaMala: 'O vizinho de cima com a máquina de lavar às 2 da manhã.',
    notaCorta: 'Série até 1h30 e o despertador às 6.',
    notaSiesta: 'Soneca de 25 min no sofá e fiquei nova em folha.',
  },
  fr: {
    notaBuena: 'Dîner léger et pas de téléphone au lit. Dormi d\'une traite.',
    notaRegular: 'Réveillée à 4h mais rendormie aussitôt.',
    notaMala: 'Le voisin du dessus avec sa machine à laver à 2h du matin.',
    notaCorta: 'Une série jusqu\'à 1h30 et le réveil à 6h.',
    notaSiesta: 'Sieste de 25 min sur le canapé et comme neuve.',
  },
  de: {
    notaBuena: 'Leichtes Abendessen, kein Handy im Bett. Durchgeschlafen.',
    notaRegular: 'Um 4 Uhr aufgewacht, aber wieder eingeschlafen.',
    notaMala: 'Der Nachbar von oben mit der Waschmaschine um 2 Uhr.',
    notaCorta: 'Serie bis 1:30 Uhr geschaut, Wecker um 6.',
    notaSiesta: '25 Minuten Nickerchen auf dem Sofa, wie neu.',
  },
  it: {
    notaBuena: 'Cena leggera e niente telefono a letto. Dormito filato.',
    notaRegular: 'Mi sono svegliata alle 4 ma mi sono riaddormentata.',
    notaMala: 'Il vicino di sopra con la lavatrice alle 2 di notte.',
    notaCorta: 'Serie fino all\'1:30 e sveglia alle 6.',
    notaSiesta: 'Pisolino di 25 min sul divano e come nuova.',
  },
  ja: {
    notaBuena: '軽めの夕食、ベッドではスマホなし。ぐっすり朝まで。',
    notaRegular: '4時に目が覚めたけど、また眠れました。',
    notaMala: '上の階の洗濯機が夜中の2時に。',
    notaCorta: '1時半までドラマを見て、目覚ましは6時。',
    notaSiesta: 'ソファで25分の昼寝、すっきり生き返りました。',
  },
  zh: {
    notaBuena: '晚饭吃得清淡,床上没碰手机,一觉到天亮。',
    notaRegular: '凌晨4点醒了一次,但又睡着了。',
    notaMala: '楼上邻居凌晨2点开洗衣机。',
    notaCorta: '追剧到1点半,闹钟定的6点。',
    notaSiesta: '在沙发上午睡25分钟,整个人都活过来了。',
  },
  ko: {
    notaBuena: '가볍게 저녁 먹고 침대에서 휴대폰 안 봤어요. 한 번도 안 깨고 푹 잤어요.',
    notaRegular: '4시에 깼는데 다시 잠들었어요.',
    notaMala: '윗집에서 새벽 2시에 세탁기를 돌렸어요.',
    notaCorta: '1시 반까지 드라마 보고 알람은 6시로 맞췄어요.',
    notaSiesta: '소파에서 25분 낮잠 잤더니 다시 팔팔해졌어요.',
  },
  ru: {
    notaBuena: 'Лёгкий ужин, телефон в постели не открывался. Уснулось сразу и до утра.',
    notaRegular: 'В 4 утра случилось проснуться, но получилось снова уснуть.',
    notaMala: 'Сосед сверху включил стиральную машину в 2 ночи.',
    notaCorta: 'Сериал до половины второго, будильник на 6.',
    notaSiesta: 'Двадцать пять минут сна на диване — и сил как будто прибавилось.',
  },
  hi: {
    notaBuena: 'हल्का खाना और बिस्तर में फ़ोन नहीं। नींद एक ही बार में पूरी रात के लिए आ गई।',
    notaRegular: '4 बजे नींद खुल गई, पर फिर से नींद लग गई।',
    notaMala: 'ऊपर वाले पड़ोसी ने रात 2 बजे वॉशिंग मशीन चला दी।',
    notaCorta: 'डेढ़ बजे तक सीरीज़ और अलार्म 6 बजे का।',
    notaSiesta: 'सोफ़े पर 25 मिनट की झपकी लगी और ताज़गी लौट आई।',
  },
  tr: {
    notaBuena: 'Hafif bir akşam yemeği, yatakta telefon yok. Sabaha kadar kütük gibi uyudum.',
    notaRegular: 'Saat 4\'te uyandım ama tekrar uyuyabildim.',
    notaMala: 'Üst kattaki komşu gece 2\'de çamaşır makinesini çalıştırdı.',
    notaCorta: 'Diziyi 1.30\'a kadar izledim, alarm 6\'ya kurulu.',
    notaSiesta: 'Kanepede 25 dakikalık şekerleme, yeniden doğmuş gibi oldum.',
  },
  id: {
    notaBuena: 'Makan malam ringan, tanpa HP di tempat tidur. Tidur nyenyak semalaman.',
    notaRegular: 'Bangun jam 4 pagi, tapi berhasil tidur lagi.',
    notaMala: 'Tetangga atas menyalakan mesin cuci jam 2 pagi.',
    notaCorta: 'Nonton series sampai jam 1:30, alarm disetel jam 6.',
    notaSiesta: 'Tidur siang 25 menit di sofa, langsung segar lagi.',
  },
  pl: {
    notaBuena: 'Lekka kolacja, żadnego telefonu w łóżku. Spanie bez przerwy do rana.',
    notaRegular: 'Przebudzenie o 4, ale udało się zasnąć z powrotem.',
    notaMala: 'Sąsiad z góry włączył pralkę o 2 w nocy.',
    notaCorta: 'Serial do 1:30, budzik ustawiony na 6.',
    notaSiesta: 'Drzemka 25 minut na kanapie i od razu więcej energii.',
  },
  ar: {
    notaBuena: 'عشاء خفيف، وبدون جوال في السرير. نوم متواصل حتى الصباح.',
    notaRegular: 'استيقظتُ الساعة 4 لكن عدتُ للنوم.',
    notaMala: 'الجار في الطابق العلوي شغّل الغسالة الساعة 2 فجرًا.',
    notaCorta: 'مسلسل حتى الساعة 1:30 والمنبه على الساعة 6.',
    notaSiesta: 'قيلولة 25 دقيقة على الأريكة، واستعدتُ نشاطي.',
  },
  nl: {
    notaBuena: 'Licht avondeten en geen telefoon in bed. In één ruk doorgeslapen.',
    notaRegular: 'Werd om 4 uur wakker, maar sliep weer in.',
    notaMala: 'De buren boven met de wasmachine om 2 uur \'s nachts.',
    notaCorta: 'Serie gekeken tot half 2, wekker om 6 uur.',
    notaSiesta: 'Dutje van 25 minuten op de bank en weer helemaal fris.',
  },
}
