// Generado por `npm run ejemplos:texto` — no lo edites a mano.
// Contenido del ejemplo de fábrica de anecdotario, en los dos idiomas. Vive aparte
// de `dict.ts` a propósito: en cuanto se crea es dato del usuario, no interfaz.

export const TEXTOS_ANECDOTARIO = {
  es: {
    tituloPaseo: 'Vuelta al río con la bici vieja',
    textoPaseo: 'Salí sin rumbo y acabé en el puente donde están las garzas. Había un señor dando de comer a los patos con pan del día antes. Volví con las manos frías y con ganas de repetir el domingo.',
    tituloCena: 'Tortilla en casa de Marta',
    textoCena: 'Marta hizo tortilla de patatas y yo llevé el pan y las aceitunas. Nos quedamos hasta las dos hablando de los veranos en el pueblo. No miramos el móvil ni una vez.',
    tituloBache: 'Martes de lluvia y lavadoras',
    textoBache: 'Se me pasó la hora del dentista y empezó a llover justo al salir sin paraguas. Comí arroz de ayer de pie en la cocina. Por la tarde puse un pódcast que me hizo reír sola en el metro.',
  },
  en: {
    tituloPaseo: 'River loop on the old bike',
    textoPaseo: 'I set off with no plan and ended up at the bridge where the herons stand. An old man was feeding the ducks with yesterday\'s bread. I got home with cold hands and wanted to do it again Sunday.',
    tituloCena: 'Shepherd\'s pie at Hannah\'s',
    textoCena: 'Hannah made shepherd\'s pie and I brought the bread and a tub of olives. We stayed up till two talking about summers at her nan\'s house. Nobody touched a phone all night.',
    tituloBache: 'Rainy Tuesday and the laundry',
    textoBache: 'I missed the dentist appointment and it started raining the second I left without an umbrella. Ate last night\'s rice standing at the counter. Then a podcast made me laugh out loud on the bus.',
  },
  pt: {
    tituloPaseo: 'Volta ao rio na bicicleta velha',
    textoPaseo: 'Saí sem rumo e acabei na ponte onde ficam as garças. Um senhor estava dando pão do dia anterior para os patos. Voltei com as mãos geladas e com vontade de repetir no domingo.',
    tituloCena: 'Tortilha na casa da Marta',
    textoCena: 'A Marta fez tortilha de batata e eu levei o pão e as azeitonas. Ficamos até as duas da manhã falando dos verões na cidade natal dela. Não olhamos o celular nem uma vez.',
    tituloBache: 'Terça de chuva e máquinas de lavar',
    textoBache: 'Esqueci a hora do dentista, e começou a chover assim que saí sem guarda-chuva. Comi o arroz de ontem em pé na cozinha. À tarde, ouvi um podcast que me fez rir sozinha no metrô.',
  },
  fr: {
    tituloPaseo: 'Tour au bord de la rivière avec le vieux vélo',
    textoPaseo: 'Je suis partie sans but et j\'ai fini sur le pont où se tiennent les hérons. Un monsieur donnait du pain de la veille aux canards. Je suis rentrée les mains froides, avec l\'envie de recommencer dimanche.',
    tituloCena: 'Tortilla chez Marta',
    textoCena: 'Marta a préparé une tortilla de pommes de terre et j\'ai apporté le pain et les olives. On est restées jusqu\'à deux heures du matin à parler des étés au village. On n\'a pas touché nos téléphones une seule fois.',
    tituloBache: 'Mardi de pluie et de machines à laver',
    textoBache: 'J\'ai raté l\'heure du dentiste et il s\'est mis à pleuvoir juste au moment où je sortais sans parapluie. J\'ai mangé le riz de la veille debout dans la cuisine. L\'après-midi, un podcast m\'a fait rire toute seule dans le métro.',
  },
  de: {
    tituloPaseo: 'Flussrunde mit dem alten Fahrrad',
    textoPaseo: 'Ich bin ziellos losgefahren und an der Brücke gelandet, wo die Reiher stehen. Ein Mann fütterte die Enten mit Brot von gestern. Ich kam mit kalten Händen nach Hause und wollte es am Sonntag wiederholen.',
    tituloCena: 'Tortilla bei Marta',
    textoCena: 'Marta hat Kartoffel-Tortilla gemacht, und ich habe das Brot und die Oliven mitgebracht. Wir sind bis zwei Uhr geblieben und haben über die Sommer im Dorf geredet. Kein einziges Mal haben wir aufs Handy geschaut.',
    tituloBache: 'Regnerischer Dienstag und Waschmaschinen',
    textoBache: 'Ich habe den Zahnarzttermin verpasst, und genau als ich ohne Regenschirm rausging, fing es an zu regnen. Ich habe den Reis von gestern stehend in der Küche gegessen. Am Nachmittag hat mich ein Podcast in der U-Bahn laut zum Lachen gebracht.',
  },
  it: {
    tituloPaseo: 'Giro lungo il fiume con la bici vecchia',
    textoPaseo: 'Sono uscita senza meta e sono finita sul ponte dove stanno gli aironi. Un signore dava il pane del giorno prima alle anatre. Sono tornata a casa con le mani fredde e con la voglia di rifarlo la domenica.',
    tituloCena: 'Tortilla a casa di Marta',
    textoCena: 'Marta ha fatto la tortilla di patate e io ho portato il pane e le olive. Siamo rimaste fino alle due a parlare delle estati al paese. Non abbiamo guardato il telefono nemmeno una volta.',
    tituloBache: 'Martedì di pioggia e lavatrici',
    textoBache: 'Mi sono dimenticata l\'ora del dentista ed è iniziato a piovere proprio mentre uscivo senza ombrello. Ho mangiato il riso di ieri in piedi in cucina. Nel pomeriggio ho ascoltato un podcast che mi ha fatto ridere da sola in metro.',
  },
  ja: {
    tituloPaseo: '古い自転車で川沿いへ',
    textoPaseo: 'あてもなく出かけて、サギがいる橋にたどり着きました。前の日のパンでカモに餌をあげているおじさんがいました。手を冷たくして帰ってきましたが、また日曜日にやりたくなりました。',
    tituloCena: 'マルタの家でトルティージャ',
    textoCena: 'マルタがポテトのトルティージャを作ってくれて、パンとオリーブを持っていきました。夜中の2時まで田舎の夏の話をして過ごしました。一度もスマホを見ませんでした。',
    tituloBache: '雨の火曜日と洗濯機',
    textoBache: '歯医者の時間をうっかり忘れていて、傘を持たずに出た瞬間に雨が降り出しました。台所に立ったまま昨日のご飯を食べました。午後、地下鉄でひとり笑ってしまうポッドキャストを聞きました。',
  },
  zh: {
    tituloPaseo: '骑旧自行车沿河而行',
    textoPaseo: '没有目的地骑了一圈,最后到了鹭鸟栖息的那座桥。一位大叔正用前一天的面包喂鸭子。回家时手冻僵了,还想着周日再去一次。',
    tituloCena: '在玛尔塔家吃西班牙烘蛋',
    textoCena: '玛尔塔做了土豆烘蛋,我带了面包和橄榄。聊到凌晨两点,说起小时候在村里的夏天。整晚都没看手机。',
    tituloBache: '下雨的星期二和洗衣机',
    textoBache: '忘了牙医预约的时间,刚出门没带伞就下起雨来。站在厨房里吃了昨天剩的米饭。下午听了一个播客,在地铁里忍不住笑出声来。',
  },
  ko: {
    tituloPaseo: '낡은 자전거로 강가 한 바퀴',
    textoPaseo: '목적지 없이 나섰다가 왜가리가 있는 다리까지 갔어요. 어떤 아저씨가 어제 남은 빵으로 오리에게 먹이를 주고 있었어요. 손이 꽁꽁 언 채로 돌아왔는데 일요일에 또 하고 싶어졌어요.',
    tituloCena: '마르타네 집에서 먹은 감자 토르티야',
    textoCena: '마르타가 감자 토르티야를 만들고 저는 빵과 올리브를 가져갔어요. 새벽 두 시까지 고향 마을의 여름 이야기를 나눴어요. 한 번도 휴대폰을 보지 않았어요.',
    tituloBache: '비 오는 화요일과 세탁기',
    textoBache: '치과 예약 시간을 깜빡했는데 우산 없이 나가자마자 비가 내리기 시작했어요. 부엌에 선 채로 어제 남은 밥을 먹었어요. 오후에는 지하철에서 혼자 웃게 만든 팟캐스트를 들었어요.',
  },
  ru: {
    tituloPaseo: 'Круг вдоль реки на старом велосипеде',
    textoPaseo: 'Поездка началась без всякой цели и закончилась на мосту, где стоят цапли. Какой-то мужчина кормил уток вчерашним хлебом. Домой пришлось возвращаться с замёрзшими руками — и сразу захотелось повторить это в воскресенье.',
    tituloCena: 'Тортилья в гостях у Марты',
    textoCena: 'Марта приготовила картофельную тортилью, а хлеб с оливками — от меня. До двух ночи говорили о летних каникулах в деревне. За весь вечер к телефону никто не притронулся.',
    tituloBache: 'Дождливый вторник и стиральные машины',
    textoBache: 'Про визит к стоматологу забылось начисто, а стоило выйти на улицу без зонта, как полил дождь. Вчерашний рис пришлось есть стоя на кухне. Днём попался подкаст, из-за которого пришлось смеяться в голос в метро.',
  },
  hi: {
    tituloPaseo: 'पुरानी साइकिल पर नदी किनारे का चक्कर',
    textoPaseo: 'बिना किसी मंज़िल के निकलना हुआ और बगुलों वाले पुल तक पहुँचना हो गया। एक सज्जन बत्तखों को कल की रोटी खिला रहे थे। हाथ ठंडे पड़ गए, और रविवार को फिर से यही करने का मन बन गया।',
    tituloCena: 'मार्टा के घर पर टॉर्टिया',
    textoCena: 'मार्टा ने आलू वाली टॉर्टिया बनाई, रोटी और ज़ैतून लाने की बारी अपनी थी। रात दो बजे तक गाँव की गर्मियों की बातें होती रहीं। पूरी शाम फ़ोन को हाथ तक नहीं लगाया गया।',
    tituloBache: 'बारिश वाला मंगलवार और वॉशिंग मशीनें',
    textoBache: 'डेंटिस्ट का समय याद ही नहीं रहा, और बिना छाते के निकलते ही बारिश शुरू हो गई। कल का चावल रसोई में खड़े-खड़े खाना पड़ा। दोपहर में एक पॉडकास्ट ऐसा मिला कि मेट्रो में हँसी रोकना मुश्किल हो गया।',
  },
  tr: {
    tituloPaseo: 'Eski bisikletle nehir turu',
    textoPaseo: 'Amaçsızca çıktım ve balıkçıl kuşlarının bulunduğu köprüde buldum kendimi. Bir amca ördeklere bir gün önceden kalma ekmek veriyordu. Elim buz gibi ama pazar günü yine yapmak isteyerek döndüm.',
    tituloCena: 'Marta\'nın evinde tortilla',
    textoCena: 'Marta patatesli tortilla yaptı, ben de ekmek ve zeytin götürdüm. Saat ikiye kadar köydeki yazları konuşarak oturduk. Bir kez bile telefona bakmadık.',
    tituloBache: 'Yağmurlu salı ve çamaşır makineleri',
    textoBache: 'Dişçi randevusunu kaçırdım ve şemsiyesiz çıkar çıkmaz yağmur başladı. Mutfakta ayakta dünkü pilavı yedim. Öğleden sonra metroda beni tek başıma güldüren bir podcast dinledim.',
  },
  id: {
    tituloPaseo: 'Muter-muter sungai naik sepeda tua',
    textoPaseo: 'Berangkat tanpa tujuan dan berakhir di jembatan tempat burung bangau berkumpul. Ada seorang bapak yang memberi makan bebek dengan roti kemarin. Pulang dengan tangan dingin dan ingin mengulanginya hari Minggu.',
    tituloCena: 'Tortilla di rumah Marta',
    textoCena: 'Marta bikin tortilla kentang, aku bawa roti dan zaitun. Kami ngobrol sampai jam dua tentang musim panas di kampung. Tidak sekalipun buka HP.',
    tituloBache: 'Selasa hujan dan mesin cuci',
    textoBache: 'Lupa jadwal ke dokter gigi, dan hujan mulai turun tepat saat keluar tanpa payung. Makan nasi sisa kemarin sambil berdiri di dapur. Sore harinya dengar podcast yang bikin ketawa sendiri di kereta.',
  },
  pl: {
    tituloPaseo: 'Wycieczka nad rzekę na starym rowerze',
    textoPaseo: 'Wyjazd bez celu i koniec na moście, gdzie stoją czaple. Jakiś pan karmił kaczki wczorajszym chlebem. Powrót z zimnymi rękami i ochotą, żeby powtórzyć to w niedzielę.',
    tituloCena: 'Tortilla u Marty',
    textoCena: 'Marta zrobiła tortillę ziemniaczaną, chleb i oliwki to mój wkład. Rozmowy o wakacjach na wsi ciągnęły się do drugiej w nocy. Ani razu telefon w rękach.',
    tituloBache: 'Deszczowy wtorek i pralki',
    textoBache: 'Zapomniane spotkanie u dentysty, a deszcz zaczął padać dokładnie w chwili wyjścia bez parasola. Wczorajszy ryż zjedzony na stojąco w kuchni. Po południu trafił się podcast, który rozśmieszył do łez w metrze.',
  },
  ar: {
    tituloPaseo: 'جولة على النهر بالدراجة القديمة',
    textoPaseo: 'خرجتُ بلا وجهة وانتهى بي المطاف عند الجسر حيث تقف مالك الحزين. كان رجل يُطعم البط خبز الأمس. عدتُ ويدايَ باردتان، وفي نفسي رغبة في تكرارها يوم الأحد.',
    tituloCena: 'تورتيا في بيت مارتا',
    textoCena: 'أعدّت مارتا تورتيا البطاطس وأحضرتُ الخبز والزيتون. بقينا حتى الساعة الثانية نتحدث عن صيف القرية. لم نلمس الهاتف ولو لمرة واحدة.',
    tituloBache: 'ثلاثاء ممطر وغسالات',
    textoBache: 'نسيتُ موعد طبيب الأسنان وبدأ المطر بالهطول فور خروجي بلا مظلة. أكلتُ أرز الأمس واقفًا في المطبخ. وبعد الظهر استمعتُ إلى بودكاست أضحكني وحدي في المترو.',
  },
  nl: {
    tituloPaseo: 'Rondje rivier op de oude fiets',
    textoPaseo: 'Vertrokken zonder plan en uiteindelijk bij de brug beland waar de reigers staan. Een meneer voerde de eendjes met brood van de dag ervoor. Thuisgekomen met koude handen en zin om het zondag over te doen.',
    tituloCena: 'Tortilla bij Marta',
    textoCena: 'Marta maakte aardappeltortilla en ik nam het brood en de olijven mee. We bleven tot twee uur \'s nachts praten over de zomers in het dorp. Geen enkele keer naar de telefoon gekeken.',
    tituloBache: 'Regenachtige dinsdag en wasmachines',
    textoBache: 'De tandartsafspraak gemist en het begon te regenen precies toen ik zonder paraplu naar buiten ging. Rijst van gisteren staand in de keuken gegeten. \'s Middags een podcast beluisterd waar ik in mijn eentje om moest lachen in de metro.',
  },
}
