// Generado por `npm run ejemplos:texto` — no lo edites a mano.
// Contenido del ejemplo de fábrica de biblioteca, en los dos idiomas. Vive aparte
// de `dict.ts` a propósito: en cuanto se crea es dato del usuario, no interfaz.

export const TEXTOS_BIBLIOTECA = {
  es: {
    entrada1Titulo: 'La dicotomía del control',
    entrada1Resumen: 'Los estoicos separan lo que depende de mí de lo que no. Mis juicios y mis actos están en mi mano; el clima, el tráfico y la opinión ajena no lo están. La calma llega al poner el esfuerzo solo en la primera columna.',
    entrada1Punto1: 'Dos columnas: lo que depende de mí y lo que no; el lío nace de mezclarlas.',
    entrada1Punto2: 'No es resignarse: es actuar donde puedo y soltar el resultado.',
    entrada1Punto3: 'Prueba diaria: en un atasco, ¿qué parte de esto elijo yo de verdad?',
    entrada2Titulo: 'El barco de Teseo',
    entrada2Resumen: 'Si a un barco le cambian una tabla cada año, al final no queda madera original. ¿Sigue siendo el mismo barco? Sirve para preguntarse qué hace que algo, o alguien, siga siendo lo mismo con el tiempo.',
    entrada2Punto1: 'La identidad puede estar en la continuidad, no en conservar los materiales.',
    entrada2Punto2: 'Versión personal: cambian mis células y mis ideas, y sigo diciendo yo.',
    notaEstudio1: 'Martes, 25 min: releí la dicotomía y marqué ejemplos.',
    notaEstudio2: 'Jueves, 20 min: me atasqué en si desear depende de mí.',
    notaEstudio3: 'Sábado, 10 min: repaso rápido del barco.',
  },
  en: {
    entrada1Titulo: 'The dichotomy of control',
    entrada1Resumen: 'The Stoics split things into what is up to me and what is not. My judgements and my actions are mine; the weather, the traffic and other people\'s opinions are not. Calm comes from spending effort only on the first list.',
    entrada1Punto1: 'Two lists: what is up to me and what is not; trouble starts when they blur.',
    entrada1Punto2: 'Not giving up: act where you can, then let the outcome go.',
    entrada1Punto3: 'Daily test: stuck in a queue, which part of this do I actually choose?',
    entrada2Titulo: 'The ship of Theseus',
    entrada2Resumen: 'Swap one plank a year and eventually no original wood is left. Is it still the same ship? A neat way to ask what makes a thing, or a person, stay itself over time.',
    entrada2Punto1: 'Identity may rest on continuity, not on keeping the same materials.',
    entrada2Punto2: 'Personal version: my cells and my views change, and I still say I.',
    notaEstudio1: 'Tuesday, 25 min: reread the dichotomy, marked examples.',
    notaEstudio2: 'Thursday, 20 min: stuck on whether wanting is up to me.',
    notaEstudio3: 'Saturday, 10 min: quick recap of the ship.',
  },
  pt: {
    entrada1Titulo: 'A dicotomia do controle',
    entrada1Resumen: 'Os estoicos separam o que depende de mim do que não depende. Meus juízos e minhas ações estão em minhas mãos; o clima, o trânsito e a opinião alheia não estão. A calma vem de colocar o esforço só na primeira coluna.',
    entrada1Punto1: 'Duas colunas: o que depende de mim e o que não depende; a confusão nasce de misturá-las.',
    entrada1Punto2: 'Não é se resignar: é agir onde posso e soltar o resultado.',
    entrada1Punto3: 'Teste diário: num engarrafamento, que parte disso eu realmente escolho?',
    entrada2Titulo: 'O barco de Teseu',
    entrada2Resumen: 'Se um barco tem uma tábua trocada a cada ano, no final não sobra madeira original. Ainda é o mesmo barco? Serve para perguntar o que faz algo, ou alguém, continuar sendo o mesmo com o tempo.',
    entrada2Punto1: 'A identidade pode estar na continuidade, não em conservar os materiais.',
    entrada2Punto2: 'Versão pessoal: minhas células e minhas ideias mudam, e eu continuo dizendo eu.',
    notaEstudio1: 'Terça, 25 min: reli a dicotomia e marquei exemplos.',
    notaEstudio2: 'Quinta, 20 min: fiquei travada em saber se desejar depende de mim.',
    notaEstudio3: 'Sábado, 10 min: revisão rápida do barco.',
  },
  fr: {
    entrada1Titulo: 'La dichotomie du contrôle',
    entrada1Resumen: 'Les stoïciens séparent ce qui dépend de moi de ce qui n\'en dépend pas. Mes jugements et mes actes sont entre mes mains; la météo, la circulation et l\'opinion des autres ne le sont pas. Le calme vient de ne mettre son effort que dans la première colonne.',
    entrada1Punto1: 'Deux colonnes: ce qui dépend de moi et ce qui n\'en dépend pas; le trouble naît de les mélanger.',
    entrada1Punto2: 'Ce n\'est pas se résigner: c\'est agir là où je peux et lâcher le résultat.',
    entrada1Punto3: 'Test quotidien: dans un embouteillage, quelle part de tout ça je choisis vraiment ?',
    entrada2Titulo: 'Le bateau de Thésée',
    entrada2Resumen: 'Si on remplace une planche par an sur un bateau, il ne reste plus de bois d\'origine à la fin. Est-ce toujours le même bateau ? Une façon de se demander ce qui fait qu\'une chose, ou une personne, reste elle-même avec le temps.',
    entrada2Punto1: 'L\'identité peut tenir à la continuité, pas au fait de garder les mêmes matériaux.',
    entrada2Punto2: 'Version personnelle: mes cellules et mes idées changent, et je continue à dire moi.',
    notaEstudio1: 'Mardi, 25 min: relu la dichotomie, noté des exemples.',
    notaEstudio2: 'Jeudi, 20 min: blocage sur la question de savoir si désirer dépend de moi.',
    notaEstudio3: 'Samedi, 10 min: révision rapide du bateau.',
  },
  de: {
    entrada1Titulo: 'Die Dichotomie der Kontrolle',
    entrada1Resumen: 'Die Stoiker trennen, was von mir abhängt, von dem, was nicht von mir abhängt. Meine Urteile und meine Handlungen liegen in meiner Hand; das Wetter, der Verkehr und die Meinung anderer nicht. Ruhe entsteht, wenn ich meine Anstrengung nur in die erste Spalte stecke.',
    entrada1Punto1: 'Zwei Spalten: was von mir abhängt und was nicht; das Durcheinander entsteht, wenn man sie vermischt.',
    entrada1Punto2: 'Es ist kein Resignieren: Es ist Handeln, wo ich kann, und das Ergebnis loslassen.',
    entrada1Punto3: 'Tägliche Probe: Im Stau, welchen Teil davon wähle ich wirklich selbst?',
    entrada2Titulo: 'Das Schiff des Theseus',
    entrada2Resumen: 'Wenn an einem Schiff jedes Jahr ein Brett ausgetauscht wird, ist am Ende kein Originalholz mehr übrig. Ist es noch dasselbe Schiff? Eine Möglichkeit zu fragen, was etwas, oder jemanden, über die Zeit hinweg dasselbe bleiben lässt.',
    entrada2Punto1: 'Identität kann in der Kontinuität liegen, nicht darin, dieselben Materialien zu behalten.',
    entrada2Punto2: 'Persönliche Version: Meine Zellen und meine Ansichten ändern sich, und ich sage weiterhin ich.',
    notaEstudio1: 'Dienstag, 25 Min.: Dichotomie noch mal gelesen und Beispiele markiert.',
    notaEstudio2: 'Donnerstag, 20 Min.: hängengeblieben bei der Frage, ob Wünschen von mir abhängt.',
    notaEstudio3: 'Samstag, 10 Min.: schnelle Wiederholung zum Schiff.',
  },
  it: {
    entrada1Titulo: 'La dicotomia del controllo',
    entrada1Resumen: 'Gli stoici separano ciò che dipende da me da ciò che non dipende. I miei giudizi e le mie azioni sono nelle mie mani; il clima, il traffico e l\'opinione altrui no. La calma arriva mettendo lo sforzo solo nella prima colonna.',
    entrada1Punto1: 'Due colonne: ciò che dipende da me e ciò che non dipende; il pasticcio nasce dal mescolarle.',
    entrada1Punto2: 'Non è rassegnarsi: è agire dove posso e lasciar andare il risultato.',
    entrada1Punto3: 'Prova quotidiana: in un ingorgo, quale parte di tutto questo scelgo davvero io?',
    entrada2Titulo: 'La nave di Teseo',
    entrada2Resumen: 'Se a una nave si cambia una tavola ogni anno, alla fine non resta legno originale. È ancora la stessa nave? Serve a chiedersi cosa fa sì che qualcosa, o qualcuno, resti lo stesso nel tempo.',
    entrada2Punto1: 'L\'identità può stare nella continuità, non nel conservare gli stessi materiali.',
    entrada2Punto2: 'Versione personale: le mie cellule e le mie idee cambiano, e continuo a dire io.',
    notaEstudio1: 'Martedì, 25 min: riletto la dicotomia e segnato esempi.',
    notaEstudio2: 'Giovedì, 20 min: blocco sul fatto se desiderare dipenda da me.',
    notaEstudio3: 'Sabato, 10 min: ripasso veloce della nave.',
  },
  ja: {
    entrada1Titulo: '制御の二分法',
    entrada1Resumen:
      'ストア派は、自分次第のものとそうでないものを分けます。自分の判断や行動は自分の手の中にありますが、天気や渋滞、他人の評価はそうではありません。努力を最初の列だけに向けると、心が落ち着きます。',
    entrada1Punto1: '「自分次第のもの」と「そうでないもの」の二列。混乱はこの二つを混ぜるところから生まれます。',
    entrada1Punto2: '諦めることではありません。できる範囲で行動し、結果は手放すことです。',
    entrada1Punto3: '毎日の練習:渋滞の中で、本当に自分が選んでいる部分はどこか。',
    entrada2Titulo: 'テセウスの船',
    entrada2Resumen:
      '船の板を毎年一枚ずつ取り替えていけば、最後には元の木材は一つも残りません。それでも同じ船と言えるでしょうか。何か、あるいは誰かが時間とともに「同じ」であり続けるとはどういうことかを考えるための問いです。',
    entrada2Punto1: 'アイデンティティは素材を保つことではなく、連続性の中にあるのかもしれません。',
    entrada2Punto2: '自分に当てはめると:細胞も考え方も変わっていくのに、それでも「自分」と言い続けています。',
    notaEstudio1: '火曜、25分:二分法を読み返して例に印をつけました。',
    notaEstudio2: '木曜、20分:望むことが自分次第かどうかで詰まりました。',
    notaEstudio3: '土曜、10分:船の話を軽く復習しました。',
  },
  zh: {
    entrada1Titulo: '控制的二分法',
    entrada1Resumen:
      '斯多葛学派把事情分成取决于我的和不取决于我的。我的判断和行为在我手中,天气、交通和别人的看法不在。把精力只放在第一栏,内心就会平静下来。',
    entrada1Punto1: '两栏:取决于我的和不取决于我的,混淆两者才是麻烦的根源。',
    entrada1Punto2: '这不是放弃,而是在能做的地方行动,然后放下结果。',
    entrada1Punto3: '每日练习:堵车时,这里面真正由我选择的部分是什么?',
    entrada2Titulo: '忒修斯之船',
    entrada2Resumen:
      '如果一艘船每年换一块木板,最后原来的木材就一块也不剩了。它还是原来那艘船吗?这个问题可以用来想:是什么让一件事物,或一个人,在时间中始终是"同一个"。',
    entrada2Punto1: '身份也许在于延续性,而不在于保留同样的材料。',
    entrada2Punto2: '套到自己身上:细胞和想法都在变,但还是一直说"我"。',
    notaEstudio1: '周二,25分钟:重读了二分法,标出了例子。',
    notaEstudio2: '周四,20分钟:卡在"渴望是否取决于我"这个问题上。',
    notaEstudio3: '周六,10分钟:快速复习了忒修斯之船。',
  },
  ko: {
    entrada1Titulo: '통제의 이분법',
    entrada1Resumen:
      '스토아 철학자들은 나에게 달린 것과 그렇지 않은 것을 나눠요. 내 판단과 행동은 내 손 안에 있지만, 날씨나 교통, 남의 평가는 그렇지 않아요. 첫 번째 칸에만 힘을 쏟으면 마음이 평온해져요.',
    entrada1Punto1: '두 칸: 나에게 달린 것과 아닌 것. 혼란은 이 둘을 섞는 데서 시작돼요.',
    entrada1Punto2: '체념이 아니에요. 할 수 있는 만큼 행동하고 결과는 놓아주는 거예요.',
    entrada1Punto3: '매일의 연습: 교통 체증 속에서, 진짜 내가 선택하는 부분은 어디일까요.',
    entrada2Titulo: '테세우스의 배',
    entrada2Resumen:
      '배의 널빤지를 매년 하나씩 바꾸다 보면 결국 원래 나무는 하나도 남지 않아요. 그래도 같은 배일까요? 무언가, 혹은 누군가가 시간이 지나도 계속 같은 존재로 남는다는 게 무엇인지 묻게 해주는 질문이에요.',
    entrada2Punto1: '정체성은 재료를 그대로 지키는 데 있는 게 아니라 연속성에 있을 수 있어요.',
    entrada2Punto2: '나에게 대입해보면: 세포도 생각도 변하는데, 그래도 계속 "나"라고 말하고 있어요.',
    notaEstudio1: '화요일, 25분: 이분법을 다시 읽고 예시에 표시했어요.',
    notaEstudio2: '목요일, 20분: 원하고 싶은 것이 나에게 달렸는지 고민하다 막혔어요.',
    notaEstudio3: '토요일, 10분: 배 이야기를 가볍게 복습했어요.',
  },
  ru: {
    entrada1Titulo: 'Дихотомия контроля',
    entrada1Resumen:
      'Стоики отделяют то, что зависит от меня, от того, что не зависит. Мои суждения и поступки — в моих руках; погода, пробки и чужое мнение — нет. Спокойствие приходит, когда усилия вкладываются только в первую колонку.',
    entrada1Punto1: 'Две колонки: что зависит от меня и что нет; путаница возникает, когда их смешивают.',
    entrada1Punto2: 'Это не смирение: это действие там, где могу, и отпускание результата.',
    entrada1Punto3: 'Ежедневная проверка: в пробке — какую часть этого я на самом деле выбираю?',
    entrada2Titulo: 'Корабль Тесея',
    entrada2Resumen:
      'Если менять на корабле по одной доске в год, в конце концов от исходного дерева ничего не останется. Это всё ещё тот же корабль? Вопрос помогает понять, что делает нечто — или кого-то — тем же самым с течением времени.',
    entrada2Punto1: 'Идентичность может держаться на непрерывности, а не на сохранении тех же материалов.',
    entrada2Punto2: 'Личная версия: клетки и взгляды меняются, а слово «я» произносится всё так же.',
    notaEstudio1: 'Вторник, 25 мин: дихотомия перечитана, примеры отмечены.',
    notaEstudio2: 'Четверг, 20 мин: затык на вопросе, зависит ли желание от меня.',
    notaEstudio3: 'Суббота, 10 мин: короткое повторение про корабль.',
  },
  hi: {
    entrada1Titulo: 'नियंत्रण की द्विभाजन-रेखा',
    entrada1Resumen:
      'स्टोइक दार्शनिक उसे अलग करते हैं जो मुझ पर निर्भर है उससे जो नहीं है। मेरे फ़ैसले और मेरे काम मेरे हाथ में हैं; मौसम, ट्रैफ़िक और दूसरों की राय नहीं। जब मेहनत सिर्फ़ पहले कॉलम पर लगाई जाए, तो मन शांत हो जाता है।',
    entrada1Punto1: 'दो कॉलम: जो मुझ पर निर्भर है और जो नहीं; गड़बड़ इन्हें मिलाने से पैदा होती है।',
    entrada1Punto2: 'यह हार मान लेना नहीं है: जहाँ हो सके वहाँ काम करना है और नतीजा छोड़ देना है।',
    entrada1Punto3: 'रोज़ की परीक्षा: ट्रैफ़िक जाम में, इसमें से सच में मेरी अपनी चुनी हुई बात कौन-सी है?',
    entrada2Titulo: 'थीसियस का जहाज़',
    entrada2Resumen:
      'अगर किसी जहाज़ का एक तख्ता हर साल बदला जाए, तो आख़िर में मूल लकड़ी का एक टुकड़ा भी नहीं बचता। क्या तब भी वह वही जहाज़ है? यह सवाल पूछने में मदद करता है कि कोई चीज़, या कोई इंसान, समय के साथ ‘वही’ कैसे बना रहता है।',
    entrada2Punto1: 'पहचान शायद निरंतरता में होती है, वही सामग्री बनाए रखने में नहीं।',
    entrada2Punto2: 'अपनी बात करें तो: कोशिकाएँ और विचार बदलते रहते हैं, फिर भी ‘मैं’ कहना जारी रहता है।',
    notaEstudio1: 'मंगलवार, 25 मिनट: द्विभाजन-रेखा दोबारा पढ़ी गई और उदाहरण चिह्नित किए गए।',
    notaEstudio2: 'गुरुवार, 20 मिनट: क्या चाहना मुझ पर निर्भर है, इस सवाल पर अटकाव हो गया।',
    notaEstudio3: 'शनिवार, 10 मिनट: जहाज़ वाले हिस्से का जल्दी दोहराव।',
  },
  tr: {
    entrada1Titulo: 'Kontrol ikilemi',
    entrada1Resumen: 'Stoacılar bana bağlı olanla olmayanı ayırır. Yargılarım ve eylemlerim elimde; hava durumu, trafik ve başkalarının fikri elimde değil. Çabayı yalnızca ilk sütuna koyunca huzur gelir.',
    entrada1Punto1: 'İki sütun: bana bağlı olan ve olmayan; karmaşa bu ikisini karıştırmaktan doğar.',
    entrada1Punto2: 'Bu boyun eğmek değil: yapabildiğim yerde hareket edip sonucu bırakmak.',
    entrada1Punto3: 'Günlük deneme: trafikte, bunun gerçekten hangi kısmını ben seçiyorum?',
    entrada2Titulo: 'Theseus\'un gemisi',
    entrada2Resumen: 'Bir geminin her yıl bir tahtası değiştirilirse, sonunda orijinal ahşaptan hiçbir şey kalmaz. Hâlâ aynı gemi mi? Bir şeyin, ya da birinin, zaman içinde aynı kalmasını neyin sağladığını sormak için işe yarar.',
    entrada2Punto1: 'Kimlik, malzemeleri korumakta değil sürekliliğinde olabilir.',
    entrada2Punto2: 'Kişisel versiyon: hücrelerim ve fikirlerim değişiyor, ben yine de "ben" demeye devam ediyorum.',
    notaEstudio1: 'Salı, 25 dk: ikilemi yeniden okudum ve örnekleri işaretledim.',
    notaEstudio2: 'Perşembe, 20 dk: istemenin bana bağlı olup olmadığında takıldım.',
    notaEstudio3: 'Cumartesi, 10 dk: gemi konusuna hızlı bir tekrar.',
  },
  id: {
    entrada1Titulo: 'Dikotomi kendali',
    entrada1Resumen: 'Kaum Stoa memisahkan apa yang bergantung padaku dari apa yang tidak. Penilaian dan tindakanku ada di tanganku; cuaca, lalu lintas, dan pendapat orang lain tidak. Ketenangan datang saat usaha hanya dicurahkan pada kolom pertama.',
    entrada1Punto1: 'Dua kolom: yang bergantung padaku dan yang tidak; kekacauan muncul saat keduanya tercampur.',
    entrada1Punto2: 'Ini bukan menyerah: ini bertindak di mana aku bisa dan melepaskan hasilnya.',
    entrada1Punto3: 'Latihan harian: saat macet, bagian mana dari ini yang benar-benar aku pilih sendiri?',
    entrada2Titulo: 'Kapal Theseus',
    entrada2Resumen: 'Kalau satu papan kapal diganti setiap tahun, akhirnya tidak ada kayu asli yang tersisa. Apa itu masih kapal yang sama? Berguna untuk bertanya apa yang membuat sesuatu, atau seseorang, tetap sama seiring waktu.',
    entrada2Punto1: 'Identitas bisa terletak pada kesinambungan, bukan pada mempertahankan bahan yang sama.',
    entrada2Punto2: 'Versi pribadi: sel-selku dan pemikiranku berubah, tapi aku tetap bilang "aku".',
    notaEstudio1: 'Selasa, 25 menit: baca ulang dikotomi dan menandai contoh.',
    notaEstudio2: 'Kamis, 20 menit: macet di soal apakah keinginan bergantung padaku.',
    notaEstudio3: 'Sabtu, 10 menit: review cepat soal kapal.',
  },
  pl: {
    entrada1Titulo: 'Dychotomia kontroli',
    entrada1Resumen: 'Stoicy oddzielają to, co zależy ode mnie, od tego, co nie zależy. Moje osądy i czyny są w moich rękach; pogoda, korki i opinie innych — nie. Spokój przychodzi, gdy wysiłek trafia tylko do pierwszej kolumny.',
    entrada1Punto1: 'Dwie kolumny: to, co zależy ode mnie, i to, co nie; zamieszanie bierze się z ich mieszania.',
    entrada1Punto2: 'To nie rezygnacja: to działanie tam, gdzie się da, i puszczenie wyniku.',
    entrada1Punto3: 'Codzienny test: w korku, którą część tego naprawdę wybieram?',
    entrada2Titulo: 'Statek Tezeusza',
    entrada2Resumen: 'Jeśli w statku co roku wymienia się jedną deskę, w końcu nie zostaje ani kawałka oryginalnego drewna. Czy to nadal ten sam statek? Dobre pytanie, żeby zastanowić się, co sprawia, że coś, albo ktoś, pozostaje sobą z upływem czasu.',
    entrada2Punto1: 'Tożsamość może tkwić w ciągłości, a nie w zachowaniu tych samych materiałów.',
    entrada2Punto2: 'Wersja osobista: komórki i poglądy się zmieniają, a ja nadal mówię "ja".',
    notaEstudio1: 'Wtorek, 25 min: ponowna lektura dychotomii i zaznaczone przykłady.',
    notaEstudio2: 'Czwartek, 20 min: zacięcie przy pytaniu, czy pragnienie zależy ode mnie.',
    notaEstudio3: 'Sobota, 10 min: szybkie powtórzenie wątku o statku.',
  },
  ar: {
    entrada1Titulo: 'ثنائية السيطرة',
    entrada1Resumen: 'يفصل الرواقيون بين ما يعتمد عليّ وما لا يعتمد. أحكامي وأفعالي بين يديّ؛ أما الطقس والزحام ورأي الآخرين فليست كذلك. يأتي الهدوء حين يُوجَّه الجهد إلى العمود الأول فقط.',
    entrada1Punto1: 'عمودان: ما يعتمد عليّ وما لا يعتمد؛ والفوضى تولد من خلطهما.',
    entrada1Punto2: 'ليس استسلامًا: بل عمل في حدود الممكن وترك النتيجة.',
    entrada1Punto3: 'اختبار يومي: في الزحام، أي جزء من هذا أختاره أنا فعلًا؟',
    entrada2Titulo: 'سفينة ثيسيوس',
    entrada2Resumen: 'إذا استُبدلت لوحة من سفينة كل عام، لا يبقى في النهاية أي خشب أصلي. هل تظل السفينة نفسها؟ سؤال يفيد في التفكير بما يجعل شيئًا، أو شخصًا، هو نفسه مع مرور الوقت.',
    entrada2Punto1: 'قد تكمن الهوية في الاستمرارية، لا في الحفاظ على المواد نفسها.',
    entrada2Punto2: 'نسخة شخصية: تتغيّر خلاياي وأفكاري، وما زلتُ أقول "أنا".',
    notaEstudio1: 'الثلاثاء، 25 دقيقة: إعادة قراءة الثنائية وتحديد أمثلة.',
    notaEstudio2: 'الخميس، 20 دقيقة: توقفتُ عند سؤال هل الرغبة تعتمد عليّ.',
    notaEstudio3: 'السبت، 10 دقائق: مراجعة سريعة لموضوع السفينة.',
  },
  nl: {
    entrada1Titulo: 'De dichotomie van controle',
    entrada1Resumen: 'De stoïcijnen scheiden wat van mij afhangt van wat niet van mij afhangt. Mijn oordelen en daden liggen in mijn handen; het weer, het verkeer en de mening van anderen niet. Rust ontstaat door de inspanning alleen in de eerste kolom te steken.',
    entrada1Punto1: 'Twee kolommen: wat van mij afhangt en wat niet; de verwarring ontstaat als je ze door elkaar haalt.',
    entrada1Punto2: 'Het is geen berusting: het is handelen waar je kunt en het resultaat loslaten.',
    entrada1Punto3: 'Dagelijkse test: in de file, welk deel hiervan kies ik nu echt zelf?',
    entrada2Titulo: 'Het schip van Theseus',
    entrada2Resumen: 'Als er elk jaar één plank van een schip wordt vervangen, blijft er uiteindelijk geen origineel hout meer over. Is het nog hetzelfde schip? Handig om je af te vragen wat maakt dat iets, of iemand, zichzelf blijft in de tijd.',
    entrada2Punto1: 'Identiteit kan liggen in continuïteit, niet in het behouden van dezelfde materialen.',
    entrada2Punto2: 'Persoonlijke versie: mijn cellen en mijn ideeën veranderen, en toch blijf ik "ik" zeggen.',
    notaEstudio1: 'Dinsdag, 25 min: dichotomie herlezen en voorbeelden aangestreept.',
    notaEstudio2: 'Donderdag, 20 min: vastgelopen bij de vraag of verlangen van mij afhangt.',
    notaEstudio3: 'Zaterdag, 10 min: snel het schip herhaald.',
  },
}
