// Generado por `npm run ejemplos:texto` — no lo edites a mano.
// Contenido del ejemplo de fábrica de biblioteca, en los dos idiomas. Vive aparte
// de `dict.ts` a propósito: en cuanto se crea es dato del usuario, no interfaz.

export const TEXTOS_BIBLIOTECA = {
  es: {
    entrada1Titulo: 'La dicotomía del control',
    entrada1Resumen: 'Los estoicos separan lo que depende de mí de lo que no. Mis juicios y mis actos están en mi mano; el clima, el tráfico y la opinión ajena no lo están. La calma llega al poner el esfuerzo solo en la primera columna.',
    entrada1Punto1: 'Dos columnas: lo que depende de mí y lo que no; el lío nace de mezclarlas.',
    entrada1Punto2: 'No es resignarse: es actuar donde puedo y soltar el resultado.',
    entrada1Punto3: 'Prueba diaria: en un atasco, ¿qué parte de esto elijo yo de verdad?',
    entrada2Titulo: 'El barco de Teseo',
    entrada2Resumen: 'Si a un barco le cambian una tabla cada año, al final no queda madera original. ¿Sigue siendo el mismo barco? Sirve para preguntarse qué hace que algo, o alguien, siga siendo lo mismo con el tiempo.',
    entrada2Punto1: 'La identidad puede estar en la continuidad, no en conservar los materiales.',
    entrada2Punto2: 'Versión personal: cambian mis células y mis ideas, y sigo diciendo yo.',
    notaEstudio1: 'Martes, 25 min: releí la dicotomía y marqué ejemplos.',
    notaEstudio2: 'Jueves, 20 min: me atasqué en si desear depende de mí.',
    notaEstudio3: 'Sábado, 10 min: repaso rápido del barco.',
    charlaTitulo: 'Lo que depende de mí',
    charlaPregunta1: 'Oí que los estoicos separaban lo que depende de uno de lo que no. ¿Cómo es eso?',
    charlaRespuesta1:
      'Es la idea con la que Epicteto abre su Manual. Hay cosas que dependen de ti: tus juicios, tus decisiones y lo que haces con ellas. Y hay cosas que no: el clima, el tráfico, lo que otros piensen de ti.\n\nEl malestar, decía, nace de mezclar las dos columnas: sufrimos por lo que no controlamos y descuidamos lo que sí. La propuesta es poner todo el esfuerzo en la primera.\n\n¿Lo probamos con algo que te haya pasado esta semana?',
    charlaPregunta2: 'Pero si el tráfico no depende de mí, ¿me aguanto y ya? Suena a resignarse.',
    charlaRespuesta2:
      'No exactamente. Resignarse sería no hacer nada; aquí actúas donde puedes: sales antes, cambias de ruta, aprovechas el rato para escuchar algo. Lo que sueltas es el resultado.\n\nLos estoicos lo explicaban con un arquero: apunta lo mejor que sabe, pero cuando la flecha sale, el viento ya no es cosa suya.\n\nUna prueba para el día a día: en el próximo atasco, pregúntate qué parte de eso eliges tú de verdad.',
  },
  en: {
    entrada1Titulo: 'The dichotomy of control',
    entrada1Resumen: 'The Stoics split things into what is up to me and what is not. My judgements and my actions are mine; the weather, the traffic and other people\'s opinions are not. Calm comes from spending effort only on the first list.',
    entrada1Punto1: 'Two lists: what is up to me and what is not; trouble starts when they blur.',
    entrada1Punto2: 'Not giving up: act where you can, then let the outcome go.',
    entrada1Punto3: 'Daily test: stuck in a queue, which part of this do I actually choose?',
    entrada2Titulo: 'The ship of Theseus',
    entrada2Resumen: 'Swap one plank a year and eventually no original wood is left. Is it still the same ship? A neat way to ask what makes a thing, or a person, stay itself over time.',
    entrada2Punto1: 'Identity may rest on continuity, not on keeping the same materials.',
    entrada2Punto2: 'Personal version: my cells and my views change, and I still say I.',
    notaEstudio1: 'Tuesday, 25 min: reread the dichotomy, marked examples.',
    notaEstudio2: 'Thursday, 20 min: stuck on whether wanting is up to me.',
    notaEstudio3: 'Saturday, 10 min: quick recap of the ship.',
    charlaTitulo: 'What is up to me',
    charlaPregunta1: 'I heard the Stoics split what is up to you from what is not. How does that work?',
    charlaRespuesta1:
      'It is the idea Epictetus opens his Handbook with. Some things are up to you: your judgements, your choices and what you do with them. Others are not: the weather, the traffic, what other people think of you.\n\nTrouble starts, he said, when the two lists blur: we fret over what we cannot control and neglect what we can. His advice is to put all your effort into the first list.\n\nShall we try it on something that happened to you this week?',
    charlaPregunta2: 'But if the traffic is not up to me, do I just put up with it? Sounds like giving up.',
    charlaRespuesta2:
      'Not quite. Giving up would mean doing nothing; here you act where you can: leave earlier, take another route, use the time to listen to something. What you let go of is the outcome.\n\nThe Stoics pictured an archer: he aims as well as he can, but once the arrow is loose, the wind is no longer his business.\n\nA daily test: next time you are stuck in a queue or in traffic, ask yourself which part of it you actually choose.',
  },
  pt: {
    entrada1Titulo: 'A dicotomia do controle',
    entrada1Resumen: 'Os estoicos separam o que depende de mim do que não depende. Meus juízos e minhas ações estão em minhas mãos; o clima, o trânsito e a opinião alheia não estão. A calma vem de colocar o esforço só na primeira coluna.',
    entrada1Punto1: 'Duas colunas: o que depende de mim e o que não depende; a confusão nasce de misturá-las.',
    entrada1Punto2: 'Não é se resignar: é agir onde posso e soltar o resultado.',
    entrada1Punto3: 'Teste diário: num engarrafamento, que parte disso eu realmente escolho?',
    entrada2Titulo: 'O barco de Teseu',
    entrada2Resumen: 'Se um barco tem uma tábua trocada a cada ano, no final não sobra madeira original. Ainda é o mesmo barco? Serve para perguntar o que faz algo, ou alguém, continuar sendo o mesmo com o tempo.',
    entrada2Punto1: 'A identidade pode estar na continuidade, não em conservar os materiais.',
    entrada2Punto2: 'Versão pessoal: minhas células e minhas ideias mudam, e eu continuo dizendo eu.',
    notaEstudio1: 'Terça, 25 min: reli a dicotomia e marquei exemplos.',
    notaEstudio2: 'Quinta, 20 min: fiquei travada em saber se desejar depende de mim.',
    notaEstudio3: 'Sábado, 10 min: revisão rápida do barco.',
    charlaTitulo: 'O que depende de mim',
    charlaPregunta1: 'Ouvi dizer que os estoicos separavam o que depende da gente do que não depende. Como é isso?',
    charlaRespuesta1:
      'É a ideia com que Epicteto abre o seu Manual. Há coisas que dependem de você: seus juízos, suas decisões e o que você faz com elas. E há coisas que não: o clima, o trânsito, o que os outros pensam de você.\n\nO mal-estar, dizia ele, nasce de misturar as duas colunas: sofremos pelo que não controlamos e descuidamos do que controlamos. A proposta é colocar todo o esforço na primeira.\n\nVamos testar com algo que aconteceu com você esta semana?',
    charlaPregunta2: 'Mas, se o trânsito não depende de mim, eu só aguento e pronto? Parece resignação.',
    charlaRespuesta2:
      'Não exatamente. Resignar-se seria não fazer nada; aqui você age onde pode: sai mais cedo, muda o caminho, aproveita o tempo para ouvir alguma coisa. O que você solta é o resultado.\n\nOs estoicos explicavam isso com um arqueiro: ele mira o melhor que sabe, mas, quando a flecha sai, o vento já não é com ele.\n\nUm teste para o dia a dia: no próximo engarrafamento, pergunte-se que parte disso você realmente escolhe.',
  },
  fr: {
    entrada1Titulo: 'La dichotomie du contrôle',
    entrada1Resumen: 'Les stoïciens séparent ce qui dépend de moi de ce qui n\'en dépend pas. Mes jugements et mes actes sont entre mes mains; la météo, la circulation et l\'opinion des autres ne le sont pas. Le calme vient de ne mettre son effort que dans la première colonne.',
    entrada1Punto1: 'Deux colonnes: ce qui dépend de moi et ce qui n\'en dépend pas; le trouble naît de les mélanger.',
    entrada1Punto2: 'Ce n\'est pas se résigner: c\'est agir là où je peux et lâcher le résultat.',
    entrada1Punto3: 'Test quotidien: dans un embouteillage, quelle part de tout ça je choisis vraiment ?',
    entrada2Titulo: 'Le bateau de Thésée',
    entrada2Resumen: 'Si on remplace une planche par an sur un bateau, il ne reste plus de bois d\'origine à la fin. Est-ce toujours le même bateau ? Une façon de se demander ce qui fait qu\'une chose, ou une personne, reste elle-même avec le temps.',
    entrada2Punto1: 'L\'identité peut tenir à la continuité, pas au fait de garder les mêmes matériaux.',
    entrada2Punto2: 'Version personnelle: mes cellules et mes idées changent, et je continue à dire moi.',
    notaEstudio1: 'Mardi, 25 min: relu la dichotomie, noté des exemples.',
    notaEstudio2: 'Jeudi, 20 min: blocage sur la question de savoir si désirer dépend de moi.',
    notaEstudio3: 'Samedi, 10 min: révision rapide du bateau.',
    charlaTitulo: 'Ce qui dépend de moi',
    charlaPregunta1: 'J\'ai entendu dire que les stoïciens séparaient ce qui dépend de nous de ce qui n\'en dépend pas. C\'est-à-dire ?',
    charlaRespuesta1:
      'C\'est l\'idée qui ouvre le Manuel d\'Épictète. Certaines choses dépendent de toi: tes jugements, tes décisions et ce que tu en fais. D\'autres non: la météo, la circulation, ce que les autres pensent de toi.\n\nLe malaise, disait-il, naît quand on mélange les deux colonnes: on souffre de ce qu\'on ne contrôle pas et on néglige ce qu\'on contrôle. Son conseil: mettre tout son effort dans la première.\n\nOn essaie avec quelque chose qui t\'est arrivé cette semaine ?',
    charlaPregunta2: 'Mais si la circulation ne dépend pas de moi, je subis et c\'est tout ? Ça ressemble à de la résignation.',
    charlaRespuesta2:
      'Pas tout à fait. Se résigner, ce serait ne rien faire; ici, tu agis là où tu peux: partir plus tôt, changer d\'itinéraire, profiter du trajet pour écouter quelque chose. Ce que tu lâches, c\'est le résultat.\n\nLes stoïciens l\'expliquaient avec un archer: il vise du mieux qu\'il peut, mais une fois la flèche partie, le vent n\'est plus son affaire.\n\nUn test pour tous les jours: dans le prochain embouteillage, demande-toi quelle part de tout ça tu choisis vraiment.',
  },
  de: {
    entrada1Titulo: 'Die Dichotomie der Kontrolle',
    entrada1Resumen: 'Die Stoiker trennen, was von mir abhängt, von dem, was nicht von mir abhängt. Meine Urteile und meine Handlungen liegen in meiner Hand; das Wetter, der Verkehr und die Meinung anderer nicht. Ruhe entsteht, wenn ich meine Anstrengung nur in die erste Spalte stecke.',
    entrada1Punto1: 'Zwei Spalten: was von mir abhängt und was nicht; das Durcheinander entsteht, wenn man sie vermischt.',
    entrada1Punto2: 'Es ist kein Resignieren: Es ist Handeln, wo ich kann, und das Ergebnis loslassen.',
    entrada1Punto3: 'Tägliche Probe: Im Stau, welchen Teil davon wähle ich wirklich selbst?',
    entrada2Titulo: 'Das Schiff des Theseus',
    entrada2Resumen: 'Wenn an einem Schiff jedes Jahr ein Brett ausgetauscht wird, ist am Ende kein Originalholz mehr übrig. Ist es noch dasselbe Schiff? Eine Möglichkeit zu fragen, was etwas, oder jemanden, über die Zeit hinweg dasselbe bleiben lässt.',
    entrada2Punto1: 'Identität kann in der Kontinuität liegen, nicht darin, dieselben Materialien zu behalten.',
    entrada2Punto2: 'Persönliche Version: Meine Zellen und meine Ansichten ändern sich, und ich sage weiterhin ich.',
    notaEstudio1: 'Dienstag, 25 Min.: Dichotomie noch mal gelesen und Beispiele markiert.',
    notaEstudio2: 'Donnerstag, 20 Min.: hängengeblieben bei der Frage, ob Wünschen von mir abhängt.',
    notaEstudio3: 'Samstag, 10 Min.: schnelle Wiederholung zum Schiff.',
    charlaTitulo: 'Was von mir abhängt',
    charlaPregunta1: 'Angeblich unterschieden die Stoiker zwischen dem, was von uns abhängt, und dem, was nicht. Wie ist das gemeint?',
    charlaRespuesta1:
      'Mit diesem Gedanken beginnt Epiktet sein Handbüchlein. Manches hängt von dir ab: deine Urteile, deine Entscheidungen und was du daraus machst. Anderes nicht: das Wetter, der Verkehr, was andere von dir denken.\n\nDas Unbehagen, sagte er, entsteht, wenn man beide Spalten vermischt: Wir leiden unter dem, was wir nicht steuern können, und vernachlässigen, was wir steuern können. Sein Rat: die ganze Anstrengung in die erste Spalte stecken.\n\nWollen wir es an etwas ausprobieren, das dir diese Woche passiert ist?',
    charlaPregunta2: 'Aber wenn der Verkehr nicht von mir abhängt, soll ich ihn dann einfach ertragen? Das klingt nach Resignation.',
    charlaRespuesta2:
      'Nicht ganz. Resignieren hieße, nichts zu tun; hier handelst du, wo du kannst: früher losfahren, eine andere Strecke nehmen, die Zeit nutzen, um etwas zu hören. Was du loslässt, ist das Ergebnis.\n\nDie Stoiker erklärten das mit einem Bogenschützen: Er zielt, so gut er kann, doch sobald der Pfeil die Sehne verlassen hat, ist der Wind nicht mehr seine Sache.\n\nEine Probe für den Alltag: Frag dich im nächsten Stau, welchen Teil davon du wirklich selbst wählst.',
  },
  it: {
    entrada1Titulo: 'La dicotomia del controllo',
    entrada1Resumen: 'Gli stoici separano ciò che dipende da me da ciò che non dipende. I miei giudizi e le mie azioni sono nelle mie mani; il clima, il traffico e l\'opinione altrui no. La calma arriva mettendo lo sforzo solo nella prima colonna.',
    entrada1Punto1: 'Due colonne: ciò che dipende da me e ciò che non dipende; il pasticcio nasce dal mescolarle.',
    entrada1Punto2: 'Non è rassegnarsi: è agire dove posso e lasciar andare il risultato.',
    entrada1Punto3: 'Prova quotidiana: in un ingorgo, quale parte di tutto questo scelgo davvero io?',
    entrada2Titulo: 'La nave di Teseo',
    entrada2Resumen: 'Se a una nave si cambia una tavola ogni anno, alla fine non resta legno originale. È ancora la stessa nave? Serve a chiedersi cosa fa sì che qualcosa, o qualcuno, resti lo stesso nel tempo.',
    entrada2Punto1: 'L\'identità può stare nella continuità, non nel conservare gli stessi materiali.',
    entrada2Punto2: 'Versione personale: le mie cellule e le mie idee cambiano, e continuo a dire io.',
    notaEstudio1: 'Martedì, 25 min: riletto la dicotomia e segnato esempi.',
    notaEstudio2: 'Giovedì, 20 min: blocco sul fatto se desiderare dipenda da me.',
    notaEstudio3: 'Sabato, 10 min: ripasso veloce della nave.',
    charlaTitulo: 'Ciò che dipende da me',
    charlaPregunta1: 'Ho sentito che gli stoici separavano ciò che dipende da noi da ciò che non dipende. In che senso?',
    charlaRespuesta1:
      'È l\'idea con cui Epitteto apre il suo Manuale. Alcune cose dipendono da te: i tuoi giudizi, le tue decisioni e quello che ne fai. Altre no: il meteo, il traffico, quello che gli altri pensano di te.\n\nIl malessere, diceva, nasce dal mescolare le due colonne: soffriamo per ciò che non controlliamo e trascuriamo ciò che controlliamo. La proposta è mettere tutto lo sforzo nella prima.\n\nProviamo con qualcosa che ti è successo questa settimana?',
    charlaPregunta2: 'Ma se il traffico non dipende da me, devo solo sopportarlo? Sembra rassegnazione.',
    charlaRespuesta2:
      'Non proprio. Rassegnarsi vorrebbe dire non fare niente; qui agisci dove puoi: esci prima, cambi strada, sfrutti il tempo per ascoltare qualcosa. Quello che lasci andare è il risultato.\n\nGli stoici lo spiegavano con un arciere: mira come meglio può, ma una volta scoccata la freccia, il vento non è più affar suo.\n\nUna prova quotidiana: nel prossimo ingorgo, chiediti quale parte di tutto questo scegli davvero tu.',
  },
  ja: {
    entrada1Titulo: '制御の二分法',
    entrada1Resumen:
      'ストア派は、自分次第のものとそうでないものを分けます。自分の判断や行動は自分の手の中にありますが、天気や渋滞、他人の評価はそうではありません。努力を最初の列だけに向けると、心が落ち着きます。',
    entrada1Punto1: '「自分次第のもの」と「そうでないもの」の二列。混乱はこの二つを混ぜるところから生まれます。',
    entrada1Punto2: '諦めることではありません。できる範囲で行動し、結果は手放すことです。',
    entrada1Punto3: '毎日の練習:渋滞の中で、本当に自分が選んでいる部分はどこか。',
    entrada2Titulo: 'テセウスの船',
    entrada2Resumen:
      '船の板を毎年一枚ずつ取り替えていけば、最後には元の木材は一つも残りません。それでも同じ船と言えるでしょうか。何か、あるいは誰かが時間とともに「同じ」であり続けるとはどういうことかを考えるための問いです。',
    entrada2Punto1: 'アイデンティティは素材を保つことではなく、連続性の中にあるのかもしれません。',
    entrada2Punto2: '自分に当てはめると:細胞も考え方も変わっていくのに、それでも「自分」と言い続けています。',
    notaEstudio1: '火曜、25分:二分法を読み返して例に印をつけました。',
    notaEstudio2: '木曜、20分:望むことが自分次第かどうかで詰まりました。',
    notaEstudio3: '土曜、10分:船の話を軽く復習しました。',
    charlaTitulo: '自分次第のもの',
    charlaPregunta1: 'ストア派は、自分次第のものとそうでないものを分けていたと聞きました。どういうことですか?',
    charlaRespuesta1:
      'エピクテトスが手引き書の冒頭に置いた考え方です。自分次第のものがあります:自分の判断や決断、そしてそれをどう行動に移すか。そうでないものもあります:天気、渋滞、他人が自分をどう思うか。\n\n彼によれば、苦しみはこの二つの列を混ぜるところから生まれます。どうにもならないことに悩み、どうにかできることをおろそかにしてしまうのです。だから努力はすべて最初の列に注ぐ、というのが彼の提案です。\n\n今週あったことで試してみましょうか?',
    charlaPregunta2: 'でも、渋滞が自分次第じゃないなら、ただ我慢するしかないんですか?それって諦めみたいです。',
    charlaRespuesta2:
      'そうとは限りません。諦めるとは、何もしないこと。ここでは、できるところで行動します:早めに出る、道を変える、その時間に何かを聴く。手放すのは結果のほうです。\n\nストア派はこれを弓の射手にたとえました。射手はできる限りうまく狙いますが、矢が放たれたら、風はもう射手の領分ではありません。\n\n毎日の練習:次に渋滞にはまったら、このうち本当に自分が選んでいる部分はどこか、自分に聞いてみてください。',
  },
  zh: {
    entrada1Titulo: '控制的二分法',
    entrada1Resumen:
      '斯多葛学派把事情分成取决于我的和不取决于我的。我的判断和行为在我手中,天气、交通和别人的看法不在。把精力只放在第一栏,内心就会平静下来。',
    entrada1Punto1: '两栏:取决于我的和不取决于我的,混淆两者才是麻烦的根源。',
    entrada1Punto2: '这不是放弃,而是在能做的地方行动,然后放下结果。',
    entrada1Punto3: '每日练习:堵车时,这里面真正由我选择的部分是什么?',
    entrada2Titulo: '忒修斯之船',
    entrada2Resumen:
      '如果一艘船每年换一块木板,最后原来的木材就一块也不剩了。它还是原来那艘船吗?这个问题可以用来想:是什么让一件事物,或一个人,在时间中始终是"同一个"。',
    entrada2Punto1: '身份也许在于延续性,而不在于保留同样的材料。',
    entrada2Punto2: '套到自己身上:细胞和想法都在变,但还是一直说"我"。',
    notaEstudio1: '周二,25分钟:重读了二分法,标出了例子。',
    notaEstudio2: '周四,20分钟:卡在"渴望是否取决于我"这个问题上。',
    notaEstudio3: '周六,10分钟:快速复习了忒修斯之船。',
    charlaTitulo: '取决于我的事',
    charlaPregunta1: '听说斯多葛学派会把取决于我们的事和不取决于我们的事分开。这是怎么回事?',
    charlaRespuesta1:
      '这是爱比克泰德在《手册》开头提出的想法。有些事取决于你:你的判断、你的决定,以及你怎么去做。有些事不取决于你:天气、交通、别人怎么看你。\n\n他说,烦恼来自把这两栏混在一起:为控制不了的事痛苦,却忽略了能控制的事。他的建议是把全部精力都放在第一栏。\n\n要不要拿你这周遇到的一件事来试试?',
    charlaPregunta2: '可是如果堵车不取决于我,那我就只能忍着吗?听起来像是认命。',
    charlaRespuesta2:
      '不完全是。认命是什么都不做;而这里是在能做的地方行动:早点出门、换条路线、利用这段时间听点东西。你放下的是结果。\n\n斯多葛学派用弓箭手来比喻:他尽力瞄准,但箭一离弦,风就不归他管了。\n\n一个日常练习:下次堵车时,问问自己,这里面真正由你选择的部分是什么?',
  },
  ko: {
    entrada1Titulo: '통제의 이분법',
    entrada1Resumen:
      '스토아 철학자들은 나에게 달린 것과 그렇지 않은 것을 나눠요. 내 판단과 행동은 내 손 안에 있지만, 날씨나 교통, 남의 평가는 그렇지 않아요. 첫 번째 칸에만 힘을 쏟으면 마음이 평온해져요.',
    entrada1Punto1: '두 칸: 나에게 달린 것과 아닌 것. 혼란은 이 둘을 섞는 데서 시작돼요.',
    entrada1Punto2: '체념이 아니에요. 할 수 있는 만큼 행동하고 결과는 놓아주는 거예요.',
    entrada1Punto3: '매일의 연습: 교통 체증 속에서, 진짜 내가 선택하는 부분은 어디일까요.',
    entrada2Titulo: '테세우스의 배',
    entrada2Resumen:
      '배의 널빤지를 매년 하나씩 바꾸다 보면 결국 원래 나무는 하나도 남지 않아요. 그래도 같은 배일까요? 무언가, 혹은 누군가가 시간이 지나도 계속 같은 존재로 남는다는 게 무엇인지 묻게 해주는 질문이에요.',
    entrada2Punto1: '정체성은 재료를 그대로 지키는 데 있는 게 아니라 연속성에 있을 수 있어요.',
    entrada2Punto2: '나에게 대입해보면: 세포도 생각도 변하는데, 그래도 계속 "나"라고 말하고 있어요.',
    notaEstudio1: '화요일, 25분: 이분법을 다시 읽고 예시에 표시했어요.',
    notaEstudio2: '목요일, 20분: 원하고 싶은 것이 나에게 달렸는지 고민하다 막혔어요.',
    notaEstudio3: '토요일, 10분: 배 이야기를 가볍게 복습했어요.',
    charlaTitulo: '나에게 달린 것',
    charlaPregunta1: '스토아 철학자들이 우리에게 달린 것과 그렇지 않은 것을 나눴다고 들었어요. 그게 무슨 뜻이에요?',
    charlaRespuesta1:
      '에픽테토스가 자신의 책 첫머리에 둔 생각이에요. 어떤 것은 우리에게 달려 있어요: 우리의 판단과 결정, 그리고 그걸로 무엇을 하는지. 어떤 것은 그렇지 않아요: 날씨, 교통 체증, 남들이 우리를 어떻게 보는지.\n\n그는 불안이 이 두 칸을 섞는 데서 생긴다고 했어요. 통제할 수 없는 일로 괴로워하고, 통제할 수 있는 일은 소홀히 하게 되니까요. 그래서 모든 노력을 첫 번째 칸에 쏟으라고 권해요.\n\n이번 주에 있었던 일로 한번 해볼까요?',
    charlaPregunta2: '그런데 교통 체증이 나에게 달린 게 아니라면, 그냥 참기만 해야 하나요? 체념처럼 들려요.',
    charlaRespuesta2:
      '꼭 그렇지는 않아요. 체념은 아무것도 하지 않는 거예요. 여기서는 할 수 있는 곳에서 행동해요: 조금 일찍 나서고, 길을 바꾸고, 그 시간에 뭔가를 들어요. 놓아주는 건 결과예요.\n\n스토아 철학자들은 이걸 궁수에 빗대어 설명했어요. 궁수는 최선을 다해 겨누지만, 화살이 시위를 떠나면 바람은 더 이상 궁수의 몫이 아니에요.\n\n매일의 연습: 다음번 교통 체증 속에서, 이 중에 진짜 내가 선택하는 부분이 어디인지 스스로에게 물어보세요.',
  },
  ru: {
    entrada1Titulo: 'Дихотомия контроля',
    entrada1Resumen:
      'Стоики отделяют то, что зависит от меня, от того, что не зависит. Мои суждения и поступки — в моих руках; погода, пробки и чужое мнение — нет. Спокойствие приходит, когда усилия вкладываются только в первую колонку.',
    entrada1Punto1: 'Две колонки: что зависит от меня и что нет; путаница возникает, когда их смешивают.',
    entrada1Punto2: 'Это не смирение: это действие там, где могу, и отпускание результата.',
    entrada1Punto3: 'Ежедневная проверка: в пробке — какую часть этого я на самом деле выбираю?',
    entrada2Titulo: 'Корабль Тесея',
    entrada2Resumen:
      'Если менять на корабле по одной доске в год, в конце концов от исходного дерева ничего не останется. Это всё ещё тот же корабль? Вопрос помогает понять, что делает нечто — или кого-то — тем же самым с течением времени.',
    entrada2Punto1: 'Идентичность может держаться на непрерывности, а не на сохранении тех же материалов.',
    entrada2Punto2: 'Личная версия: клетки и взгляды меняются, а слово «я» произносится всё так же.',
    notaEstudio1: 'Вторник, 25 мин: дихотомия перечитана, примеры отмечены.',
    notaEstudio2: 'Четверг, 20 мин: затык на вопросе, зависит ли желание от меня.',
    notaEstudio3: 'Суббота, 10 мин: короткое повторение про корабль.',
    charlaTitulo: 'Что зависит от меня',
    charlaPregunta1: 'Говорят, стоики отделяли то, что зависит от нас, от того, что не зависит. Как это понимать?',
    charlaRespuesta1:
      'С этой мысли Эпиктет начинает своё «Руководство». Одно зависит от тебя: твои суждения, решения и то, что ты с ними делаешь. Другое — нет: погода, пробки, то, что думают о тебе другие.\n\nБеспокойство, по его словам, рождается, когда эти две колонки смешиваются: мы страдаем из-за того, что не контролируем, и забываем о том, что контролируем. Его совет: вкладывать все усилия в первую колонку.\n\nПопробуем на чём-нибудь, что случилось с тобой на этой неделе?',
    charlaPregunta2: 'Но если пробки не зависят от меня, мне что, просто терпеть? Звучит как смирение.',
    charlaRespuesta2:
      'Не совсем. Смириться — значит ничего не делать; а здесь ты действуешь там, где можешь: выходишь пораньше, меняешь маршрут, используешь время, чтобы что-нибудь послушать. Отпускаешь ты только результат.\n\nСтоики объясняли это на примере лучника: он целится как можно лучше, но когда стрела уже выпущена, ветер больше не его забота.\n\nПроверка на каждый день: в следующей пробке спроси себя, какую часть этого ты на самом деле выбираешь.',
  },
  hi: {
    entrada1Titulo: 'नियंत्रण की द्विभाजन-रेखा',
    entrada1Resumen:
      'स्टोइक दार्शनिक उसे अलग करते हैं जो मुझ पर निर्भर है उससे जो नहीं है। मेरे फ़ैसले और मेरे काम मेरे हाथ में हैं; मौसम, ट्रैफ़िक और दूसरों की राय नहीं। जब मेहनत सिर्फ़ पहले कॉलम पर लगाई जाए, तो मन शांत हो जाता है।',
    entrada1Punto1: 'दो कॉलम: जो मुझ पर निर्भर है और जो नहीं; गड़बड़ इन्हें मिलाने से पैदा होती है।',
    entrada1Punto2: 'यह हार मान लेना नहीं है: जहाँ हो सके वहाँ काम करना है और नतीजा छोड़ देना है।',
    entrada1Punto3: 'रोज़ की परीक्षा: ट्रैफ़िक जाम में, इसमें से सच में मेरी अपनी चुनी हुई बात कौन-सी है?',
    entrada2Titulo: 'थीसियस का जहाज़',
    entrada2Resumen:
      'अगर किसी जहाज़ का एक तख्ता हर साल बदला जाए, तो आख़िर में मूल लकड़ी का एक टुकड़ा भी नहीं बचता। क्या तब भी वह वही जहाज़ है? यह सवाल पूछने में मदद करता है कि कोई चीज़, या कोई इंसान, समय के साथ ‘वही’ कैसे बना रहता है।',
    entrada2Punto1: 'पहचान शायद निरंतरता में होती है, वही सामग्री बनाए रखने में नहीं।',
    entrada2Punto2: 'अपनी बात करें तो: कोशिकाएँ और विचार बदलते रहते हैं, फिर भी ‘मैं’ कहना जारी रहता है।',
    notaEstudio1: 'मंगलवार, 25 मिनट: द्विभाजन-रेखा दोबारा पढ़ी गई और उदाहरण चिह्नित किए गए।',
    notaEstudio2: 'गुरुवार, 20 मिनट: क्या चाहना मुझ पर निर्भर है, इस सवाल पर अटकाव हो गया।',
    notaEstudio3: 'शनिवार, 10 मिनट: जहाज़ वाले हिस्से का जल्दी दोहराव।',
    charlaTitulo: 'जो मुझ पर निर्भर है',
    charlaPregunta1: 'सुना है कि स्टोइक दार्शनिक उन बातों को अलग करते थे जो हम पर निर्भर हैं और जो नहीं। इसका मतलब क्या है?',
    charlaRespuesta1:
      'यह वही विचार है जिससे एपिक्टेटस अपनी पुस्तिका की शुरुआत करते हैं। कुछ चीज़ें हम पर निर्भर हैं: हमारे फ़ैसले, हमारे चुनाव और उनके साथ हम क्या करते हैं। कुछ नहीं: मौसम, ट्रैफ़िक, दूसरे हमारे बारे में क्या सोचते हैं।\n\nउनके अनुसार बेचैनी तब पैदा होती है जब ये दोनों कॉलम आपस में मिल जाते हैं: जो बस में नहीं, उसके लिए दुख होता है, और जो बस में है, उसकी अनदेखी हो जाती है। उनका सुझाव है कि पूरी मेहनत पहले कॉलम पर लगाई जाए।\n\nक्या इस हफ़्ते की किसी घटना पर इसे आज़माकर देखें?',
    charlaPregunta2: 'लेकिन अगर ट्रैफ़िक मुझ पर निर्भर नहीं है, तो क्या बस सहते रहना है? यह तो हार मान लेने जैसा लगता है।',
    charlaRespuesta2:
      'पूरी तरह नहीं। हार मान लेने का मतलब है कुछ न करना; यहाँ जहाँ हो सके वहाँ कदम उठाया जाता है: जल्दी निकलना, रास्ता बदलना, उस समय में कुछ सुन लेना। जो छोड़ा जाता है, वह है नतीजा।\n\nस्टोइक इसे एक तीरंदाज़ के उदाहरण से समझाते थे: वह जितना अच्छा हो सके निशाना साधता है, लेकिन तीर छूटने के बाद हवा उसके बस में नहीं रहती।\n\nरोज़ की परीक्षा: अगले ट्रैफ़िक जाम में खुद से पूछिए कि इसमें से सच में कौन-सी बात आपकी अपनी चुनी हुई है।',
  },
  tr: {
    entrada1Titulo: 'Kontrol ikilemi',
    entrada1Resumen: 'Stoacılar bana bağlı olanla olmayanı ayırır. Yargılarım ve eylemlerim elimde; hava durumu, trafik ve başkalarının fikri elimde değil. Çabayı yalnızca ilk sütuna koyunca huzur gelir.',
    entrada1Punto1: 'İki sütun: bana bağlı olan ve olmayan; karmaşa bu ikisini karıştırmaktan doğar.',
    entrada1Punto2: 'Bu boyun eğmek değil: yapabildiğim yerde hareket edip sonucu bırakmak.',
    entrada1Punto3: 'Günlük deneme: trafikte, bunun gerçekten hangi kısmını ben seçiyorum?',
    entrada2Titulo: 'Theseus\'un gemisi',
    entrada2Resumen: 'Bir geminin her yıl bir tahtası değiştirilirse, sonunda orijinal ahşaptan hiçbir şey kalmaz. Hâlâ aynı gemi mi? Bir şeyin, ya da birinin, zaman içinde aynı kalmasını neyin sağladığını sormak için işe yarar.',
    entrada2Punto1: 'Kimlik, malzemeleri korumakta değil sürekliliğinde olabilir.',
    entrada2Punto2: 'Kişisel versiyon: hücrelerim ve fikirlerim değişiyor, ben yine de "ben" demeye devam ediyorum.',
    notaEstudio1: 'Salı, 25 dk: ikilemi yeniden okudum ve örnekleri işaretledim.',
    notaEstudio2: 'Perşembe, 20 dk: istemenin bana bağlı olup olmadığında takıldım.',
    notaEstudio3: 'Cumartesi, 10 dk: gemi konusuna hızlı bir tekrar.',
    charlaTitulo: 'Bana bağlı olan',
    charlaPregunta1: 'Stoacıların bize bağlı olanla olmayanı ayırdığını duydum. Bu ne demek?',
    charlaRespuesta1:
      'Epiktetos ünlü el kitabına bu fikirle başlar. Bazı şeyler sana bağlıdır: yargıların, kararların ve onlarla ne yaptığın. Bazıları değildir: hava durumu, trafik, başkalarının senin hakkında ne düşündüğü.\n\nOna göre huzursuzluk, iki sütunu karıştırmaktan doğar: kontrol edemediğimiz şeyler için acı çekeriz, edebildiklerimizi ise ihmal ederiz. Önerisi, bütün çabayı ilk sütuna koymaktır.\n\nBunu bu hafta başına gelen bir şeyle deneyelim mi?',
    charlaPregunta2: 'Ama trafik bana bağlı değilse, katlanıp geçecek miyim yani? Bu boyun eğmek gibi geliyor.',
    charlaRespuesta2:
      'Tam olarak değil. Boyun eğmek hiçbir şey yapmamak olurdu; burada yapabildiğin yerde harekete geçersin: daha erken çıkarsın, başka bir yol seçersin, o zamanı bir şey dinleyerek değerlendirirsin. Bıraktığın şey sonuçtur.\n\nStoacılar bunu bir okçu örneğiyle anlatırdı: okçu elinden geldiğince iyi nişan alır, ama ok yaydan çıktıktan sonra rüzgâr artık onun işi değildir.\n\nGünlük bir deneme: bir sonraki trafik sıkışıklığında kendine sor, bunun gerçekten hangi kısmını sen seçiyorsun?',
  },
  id: {
    entrada1Titulo: 'Dikotomi kendali',
    entrada1Resumen: 'Kaum Stoa memisahkan apa yang bergantung padaku dari apa yang tidak. Penilaian dan tindakanku ada di tanganku; cuaca, lalu lintas, dan pendapat orang lain tidak. Ketenangan datang saat usaha hanya dicurahkan pada kolom pertama.',
    entrada1Punto1: 'Dua kolom: yang bergantung padaku dan yang tidak; kekacauan muncul saat keduanya tercampur.',
    entrada1Punto2: 'Ini bukan menyerah: ini bertindak di mana aku bisa dan melepaskan hasilnya.',
    entrada1Punto3: 'Latihan harian: saat macet, bagian mana dari ini yang benar-benar aku pilih sendiri?',
    entrada2Titulo: 'Kapal Theseus',
    entrada2Resumen: 'Kalau satu papan kapal diganti setiap tahun, akhirnya tidak ada kayu asli yang tersisa. Apa itu masih kapal yang sama? Berguna untuk bertanya apa yang membuat sesuatu, atau seseorang, tetap sama seiring waktu.',
    entrada2Punto1: 'Identitas bisa terletak pada kesinambungan, bukan pada mempertahankan bahan yang sama.',
    entrada2Punto2: 'Versi pribadi: sel-selku dan pemikiranku berubah, tapi aku tetap bilang "aku".',
    notaEstudio1: 'Selasa, 25 menit: baca ulang dikotomi dan menandai contoh.',
    notaEstudio2: 'Kamis, 20 menit: macet di soal apakah keinginan bergantung padaku.',
    notaEstudio3: 'Sabtu, 10 menit: review cepat soal kapal.',
    charlaTitulo: 'Yang bergantung padaku',
    charlaPregunta1: 'Katanya kaum Stoa memisahkan apa yang bergantung pada kita dari apa yang tidak. Maksudnya bagaimana?',
    charlaRespuesta1:
      'Dengan gagasan inilah Epiktetos membuka buku pegangannya. Ada hal yang bergantung padamu: penilaianmu, keputusanmu, dan apa yang kamu lakukan dengannya. Ada juga yang tidak: cuaca, lalu lintas, apa yang orang lain pikirkan tentangmu.\n\nMenurutnya, rasa gelisah muncul saat dua kolom itu tercampur: kita menderita karena hal yang tidak bisa kita kendalikan dan mengabaikan yang bisa. Sarannya, curahkan seluruh usaha pada kolom pertama.\n\nMau kita coba dengan sesuatu yang terjadi padamu minggu ini?',
    charlaPregunta2: 'Tapi kalau lalu lintas tidak bergantung padaku, apa aku cuma harus menerimanya begitu saja? Kedengarannya seperti menyerah.',
    charlaRespuesta2:
      'Tidak persis begitu. Menyerah berarti tidak berbuat apa-apa; di sini kamu bertindak di mana kamu bisa: berangkat lebih awal, ganti rute, memakai waktunya untuk mendengarkan sesuatu. Yang kamu lepaskan adalah hasilnya.\n\nKaum Stoa menjelaskannya dengan seorang pemanah: ia membidik sebaik mungkin, tapi begitu anak panah lepas, angin bukan lagi urusannya.\n\nLatihan harian: saat macet berikutnya, tanyakan pada dirimu bagian mana dari semua itu yang benar-benar kamu pilih.',
  },
  pl: {
    entrada1Titulo: 'Dychotomia kontroli',
    entrada1Resumen: 'Stoicy oddzielają to, co zależy ode mnie, od tego, co nie zależy. Moje osądy i czyny są w moich rękach; pogoda, korki i opinie innych — nie. Spokój przychodzi, gdy wysiłek trafia tylko do pierwszej kolumny.',
    entrada1Punto1: 'Dwie kolumny: to, co zależy ode mnie, i to, co nie; zamieszanie bierze się z ich mieszania.',
    entrada1Punto2: 'To nie rezygnacja: to działanie tam, gdzie się da, i puszczenie wyniku.',
    entrada1Punto3: 'Codzienny test: w korku, którą część tego naprawdę wybieram?',
    entrada2Titulo: 'Statek Tezeusza',
    entrada2Resumen: 'Jeśli w statku co roku wymienia się jedną deskę, w końcu nie zostaje ani kawałka oryginalnego drewna. Czy to nadal ten sam statek? Dobre pytanie, żeby zastanowić się, co sprawia, że coś, albo ktoś, pozostaje sobą z upływem czasu.',
    entrada2Punto1: 'Tożsamość może tkwić w ciągłości, a nie w zachowaniu tych samych materiałów.',
    entrada2Punto2: 'Wersja osobista: komórki i poglądy się zmieniają, a ja nadal mówię "ja".',
    notaEstudio1: 'Wtorek, 25 min: ponowna lektura dychotomii i zaznaczone przykłady.',
    notaEstudio2: 'Czwartek, 20 min: zacięcie przy pytaniu, czy pragnienie zależy ode mnie.',
    notaEstudio3: 'Sobota, 10 min: szybkie powtórzenie wątku o statku.',
    charlaTitulo: 'To, co zależy ode mnie',
    charlaPregunta1: 'Podobno stoicy oddzielali to, co od nas zależy, od tego, co nie zależy. Jak to rozumieć?',
    charlaRespuesta1:
      'Tą myślą Epiktet otwiera swój Podręcznik. Niektóre rzeczy zależą od ciebie: twoje osądy, decyzje i to, co z nimi robisz. Inne nie: pogoda, korki, to, co inni o tobie myślą.\n\nNiepokój, jak mówił, bierze się z mieszania tych dwóch kolumn: cierpimy z powodu tego, na co nie mamy wpływu, i zaniedbujemy to, na co mamy. Jego rada: cały wysiłek wkładać w pierwszą kolumnę.\n\nSprawdzimy to na czymś, co przydarzyło ci się w tym tygodniu?',
    charlaPregunta2: 'Ale skoro korki nie zależą ode mnie, to mam je po prostu znosić? Brzmi jak rezygnacja.',
    charlaRespuesta2:
      'Nie do końca. Rezygnacja oznaczałaby bezczynność; tu działasz tam, gdzie się da: wychodzisz wcześniej, zmieniasz trasę, wykorzystujesz czas, żeby czegoś posłuchać. To, co puszczasz, to wynik.\n\nStoicy tłumaczyli to na przykładzie łucznika: celuje najlepiej, jak potrafi, ale gdy strzała już poleci, wiatr nie jest jego sprawą.\n\nTest na co dzień: w najbliższym korku zapytaj siebie, którą część tego naprawdę wybierasz.',
  },
  ar: {
    entrada1Titulo: 'ثنائية السيطرة',
    entrada1Resumen: 'يفصل الرواقيون بين ما يعتمد عليّ وما لا يعتمد. أحكامي وأفعالي بين يديّ؛ أما الطقس والزحام ورأي الآخرين فليست كذلك. يأتي الهدوء حين يُوجَّه الجهد إلى العمود الأول فقط.',
    entrada1Punto1: 'عمودان: ما يعتمد عليّ وما لا يعتمد؛ والفوضى تولد من خلطهما.',
    entrada1Punto2: 'ليس استسلامًا: بل عمل في حدود الممكن وترك النتيجة.',
    entrada1Punto3: 'اختبار يومي: في الزحام، أي جزء من هذا أختاره أنا فعلًا؟',
    entrada2Titulo: 'سفينة ثيسيوس',
    entrada2Resumen: 'إذا استُبدلت لوحة من سفينة كل عام، لا يبقى في النهاية أي خشب أصلي. هل تظل السفينة نفسها؟ سؤال يفيد في التفكير بما يجعل شيئًا، أو شخصًا، هو نفسه مع مرور الوقت.',
    entrada2Punto1: 'قد تكمن الهوية في الاستمرارية، لا في الحفاظ على المواد نفسها.',
    entrada2Punto2: 'نسخة شخصية: تتغيّر خلاياي وأفكاري، وما زلتُ أقول "أنا".',
    notaEstudio1: 'الثلاثاء، 25 دقيقة: إعادة قراءة الثنائية وتحديد أمثلة.',
    notaEstudio2: 'الخميس، 20 دقيقة: توقفتُ عند سؤال هل الرغبة تعتمد عليّ.',
    notaEstudio3: 'السبت، 10 دقائق: مراجعة سريعة لموضوع السفينة.',
    charlaTitulo: 'ما يعتمد عليّ',
    charlaPregunta1: 'سمعتُ أن الرواقيين كانوا يفصلون بين ما يعتمد علينا وما لا يعتمد. كيف ذلك؟',
    charlaRespuesta1:
      'إنها الفكرة التي افتتح بها إبكتيتوس كتيّبه. بعض الأمور تعتمد علينا: أحكامنا وقراراتنا وما نفعله بها. وبعضها لا: الطقس والزحام وما يظنه الآخرون بنا.\n\nوكان يرى أن الضيق يولد من خلط العمودين: نتألم مما لا نتحكم فيه، ونُهمل ما نتحكم فيه. ونصيحته أن يوضع الجهد كله في العمود الأول.\n\nهل نجرّب ذلك على أمر حدث هذا الأسبوع؟',
    charlaPregunta2: 'لكن إذا كان الزحام لا يعتمد عليّ، فهل أتحمّله وحسب؟ يبدو ذلك استسلامًا.',
    charlaRespuesta2:
      'ليس تمامًا. الاستسلام يعني ألّا نفعل شيئًا؛ أما هنا فنعمل حيث نستطيع: الخروج أبكر، أو تغيير الطريق، أو استغلال الوقت للاستماع إلى شيء ما. وما نتركه هو النتيجة.\n\nكان الرواقيون يشرحون ذلك بصورة الرامي: يصوّب بأفضل ما يستطيع، لكن حين ينطلق السهم لا تعود الريح من شأنه.\n\nاختبار يومي: في الزحام القادم، يكفي سؤال واحد: أي جزء من هذا أختاره أنا فعلًا؟',
  },
  nl: {
    entrada1Titulo: 'De dichotomie van controle',
    entrada1Resumen: 'De stoïcijnen scheiden wat van mij afhangt van wat niet van mij afhangt. Mijn oordelen en daden liggen in mijn handen; het weer, het verkeer en de mening van anderen niet. Rust ontstaat door de inspanning alleen in de eerste kolom te steken.',
    entrada1Punto1: 'Twee kolommen: wat van mij afhangt en wat niet; de verwarring ontstaat als je ze door elkaar haalt.',
    entrada1Punto2: 'Het is geen berusting: het is handelen waar je kunt en het resultaat loslaten.',
    entrada1Punto3: 'Dagelijkse test: in de file, welk deel hiervan kies ik nu echt zelf?',
    entrada2Titulo: 'Het schip van Theseus',
    entrada2Resumen: 'Als er elk jaar één plank van een schip wordt vervangen, blijft er uiteindelijk geen origineel hout meer over. Is het nog hetzelfde schip? Handig om je af te vragen wat maakt dat iets, of iemand, zichzelf blijft in de tijd.',
    entrada2Punto1: 'Identiteit kan liggen in continuïteit, niet in het behouden van dezelfde materialen.',
    entrada2Punto2: 'Persoonlijke versie: mijn cellen en mijn ideeën veranderen, en toch blijf ik "ik" zeggen.',
    notaEstudio1: 'Dinsdag, 25 min: dichotomie herlezen en voorbeelden aangestreept.',
    notaEstudio2: 'Donderdag, 20 min: vastgelopen bij de vraag of verlangen van mij afhangt.',
    notaEstudio3: 'Zaterdag, 10 min: snel het schip herhaald.',
    charlaTitulo: 'Wat van mij afhangt',
    charlaPregunta1: 'Ik hoorde dat de stoïcijnen onderscheid maakten tussen wat van ons afhangt en wat niet. Hoe zit dat?',
    charlaRespuesta1:
      'Met dat idee opent Epictetus zijn Handboekje. Sommige dingen hangen van jou af: je oordelen, je keuzes en wat je ermee doet. Andere niet: het weer, het verkeer, wat anderen van je denken.\n\nHet onbehagen, zei hij, ontstaat als je de twee kolommen door elkaar haalt: we lijden onder wat we niet in de hand hebben en verwaarlozen wat we wel in de hand hebben. Zijn advies: steek alle moeite in de eerste kolom.\n\nZullen we het proberen met iets wat je deze week is overkomen?',
    charlaPregunta2: 'Maar als het verkeer niet van mij afhangt, moet ik het dan gewoon over me heen laten komen? Dat klinkt als berusting.',
    charlaRespuesta2:
      'Niet helemaal. Berusten zou betekenen dat je niets doet; hier handel je waar je kunt: eerder vertrekken, een andere route nemen, de tijd gebruiken om naar iets te luisteren. Wat je loslaat, is het resultaat.\n\nDe stoïcijnen legden het uit met een boogschutter: hij mikt zo goed als hij kan, maar zodra de pijl weg is, is de wind zijn zaak niet meer.\n\nEen test voor elke dag: vraag je in de volgende file af welk deel daarvan je echt zelf kiest.',
  },
}
