// Contenido del ejemplo de fábrica del diario de ideas, en los 16 idiomas (el de
// los mapas y diagramas sale del catálogo por formato de `ejemplos.ts`). Vive
// aparte de `dict.ts` a propósito: en cuanto se crea es dato del usuario, no
// interfaz. `ventajas`/`desventajas` titulan las columnas del diagrama de
// ejemplo: son las mismas palabras que `ideas.mapa.ventajas` en cada `dict`.

export const TEXTOS_IDEAS = {
  es: {
    carpetaProyectos: 'Proyectos',
    carpetaEpisodios: 'Episodios del pódcast',
    carpetaCasa: 'Casa',
    podcast: 'Empezar un pódcast sobre oficios poco conocidos',
    podcastPunto1: 'Escuchar tres programas parecidos y anotar qué funciona',
    podcastPunto2: 'Grabar un episodio de prueba de quince minutos',
    podcastPunto3: 'Decidir el nombre con una lluvia de ideas',
    relojeria: 'Entrevistar a quien arregla relojes en la esquina',
    huerto: 'Huerto de hierbas en la ventana de la cocina',
    huertoPunto1: 'Medir el alféizar',
    huertoPunto2: 'Albahaca, menta y cilantro, que son las que más uso',
    temaLluvia: 'Nombre del pódcast',
    lluvia1: 'Oficios con historia',
    lluvia2: 'Manos a la obra',
    lluvia3: 'Lo que nadie ve',
    ventajas: 'Ventajas',
    desventajas: 'Desventajas',
  },
  en: {
    carpetaProyectos: 'Projects',
    carpetaEpisodios: 'Podcast episodes',
    carpetaCasa: 'Home',
    podcast: 'Start a podcast about little-known trades',
    podcastPunto1: 'Listen to three similar shows and note what works',
    podcastPunto2: 'Record a fifteen-minute test episode',
    podcastPunto3: 'Pick the name with a brainstorm',
    relojeria: 'Interview the watch repairer on the corner',
    huerto: 'Herb garden in the kitchen window',
    huertoPunto1: 'Measure the windowsill',
    huertoPunto2: 'Basil, mint and coriander, the ones I use most',
    temaLluvia: 'Podcast name',
    lluvia1: 'Trades with a story',
    lluvia2: 'Hands on',
    lluvia3: 'What nobody sees',
    ventajas: 'Pros',
    desventajas: 'Cons',
  },
  pt: {
    carpetaProyectos: 'Projetos',
    carpetaEpisodios: 'Episódios do podcast',
    carpetaCasa: 'Casa',
    podcast: 'Começar um podcast sobre ofícios pouco conhecidos',
    podcastPunto1: 'Ouvir três programas parecidos e anotar o que funciona',
    podcastPunto2: 'Gravar um episódio de teste de quinze minutos',
    podcastPunto3: 'Decidir o nome com uma chuva de ideias',
    relojeria: 'Entrevistar quem conserta relógios na esquina',
    huerto: 'Horta de ervas na janela da cozinha',
    huertoPunto1: 'Medir o parapeito da janela',
    huertoPunto2: 'Manjericão, hortelã e coentro, que são as que mais uso',
    temaLluvia: 'Nome do podcast',
    lluvia1: 'Ofícios com história',
    lluvia2: 'Mãos à obra',
    lluvia3: 'O que ninguém vê',
    ventajas: 'Prós',
    desventajas: 'Contras',
  },
  fr: {
    carpetaProyectos: 'Projets',
    carpetaEpisodios: 'Épisodes du podcast',
    carpetaCasa: 'Maison',
    podcast: 'Lancer un podcast sur des métiers méconnus',
    podcastPunto1: 'Écouter trois émissions similaires et noter ce qui marche',
    podcastPunto2: 'Enregistrer un épisode test de quinze minutes',
    podcastPunto3: 'Choisir le nom avec un remue-méninges',
    relojeria: 'Interviewer la personne qui répare les montres au coin de la rue',
    huerto: 'Herbes aromatiques à la fenêtre de la cuisine',
    huertoPunto1: 'Mesurer le rebord de la fenêtre',
    huertoPunto2: 'Basilic, menthe et coriandre, celles que j\'utilise le plus',
    temaLluvia: 'Nom du podcast',
    lluvia1: 'Des métiers et des histoires',
    lluvia2: 'Les mains dans le cambouis',
    lluvia3: 'Ce que personne ne voit',
    ventajas: 'Pour',
    desventajas: 'Contre',
  },
  de: {
    carpetaProyectos: 'Projekte',
    carpetaEpisodios: 'Podcast-Folgen',
    carpetaCasa: 'Zuhause',
    podcast: 'Einen Podcast über wenig bekannte Handwerksberufe starten',
    podcastPunto1: 'Drei ähnliche Sendungen hören und notieren, was funktioniert',
    podcastPunto2: 'Eine Probefolge von fünfzehn Minuten aufnehmen',
    podcastPunto3: 'Den Namen per Brainstorming finden',
    relojeria: 'Ein Interview in der Uhrmacherwerkstatt an der Ecke führen',
    huerto: 'Kräutergarten am Küchenfenster',
    huertoPunto1: 'Die Fensterbank ausmessen',
    huertoPunto2: 'Basilikum, Minze und Koriander, die nutze ich am meisten',
    temaLluvia: 'Name des Podcasts',
    lluvia1: 'Berufe mit Geschichte',
    lluvia2: 'Hand anlegen',
    lluvia3: 'Was niemand sieht',
    ventajas: 'Pro',
    desventajas: 'Kontra',
  },
  it: {
    carpetaProyectos: 'Progetti',
    carpetaEpisodios: 'Episodi del podcast',
    carpetaCasa: 'Casa',
    podcast: 'Avviare un podcast sui mestieri poco conosciuti',
    podcastPunto1: 'Ascoltare tre programmi simili e annotare cosa funziona',
    podcastPunto2: 'Registrare un episodio di prova di quindici minuti',
    podcastPunto3: 'Scegliere il nome con un brainstorming',
    relojeria: 'Intervistare chi ripara orologi all\'angolo',
    huerto: 'Orto di erbe aromatiche alla finestra della cucina',
    huertoPunto1: 'Misurare il davanzale',
    huertoPunto2: 'Basilico, menta e coriandolo, quelle che uso di più',
    temaLluvia: 'Nome del podcast',
    lluvia1: 'Mestieri con una storia',
    lluvia2: 'Mani in pasta',
    lluvia3: 'Quello che nessuno vede',
    ventajas: 'Pro',
    desventajas: 'Contro',
  },
  ja: {
    carpetaProyectos: 'プロジェクト',
    carpetaEpisodios: 'ポッドキャストのエピソード',
    carpetaCasa: '家のこと',
    podcast: 'あまり知られていない職業のポッドキャストを始める',
    podcastPunto1: '似た番組を3本聴いて、うまくいっている点をメモする',
    podcastPunto2: '15分の試しエピソードを録音する',
    podcastPunto3: 'ブレインストーミングで名前を決める',
    relojeria: '角の時計修理店でインタビューする',
    huerto: 'キッチンの窓辺でハーブを育てる',
    huertoPunto1: '窓台の幅を測る',
    huertoPunto2: 'バジル、ミント、パクチー（いちばんよく使う3つ）',
    temaLluvia: 'ポッドキャストの名前',
    lluvia1: '物語のある仕事',
    lluvia2: '手を動かす人たち',
    lluvia3: '誰も知らない舞台裏',
    ventajas: 'メリット',
    desventajas: 'デメリット',
  },
  zh: {
    carpetaProyectos: '项目',
    carpetaEpisodios: '播客单集',
    carpetaCasa: '家里',
    podcast: '做一档关于冷门职业的播客',
    podcastPunto1: '听三档类似的节目，记下哪些做法有效',
    podcastPunto2: '录一期十五分钟的试播节目',
    podcastPunto3: '用头脑风暴定下名字',
    relojeria: '采访街角修手表的师傅',
    huerto: '在厨房窗台种香草',
    huertoPunto1: '量一下窗台',
    huertoPunto2: '罗勒、薄荷和香菜，是我最常用的三种',
    temaLluvia: '播客名字',
    lluvia1: '有故事的手艺',
    lluvia2: '动手吧',
    lluvia3: '没人看见的地方',
    ventajas: '优点',
    desventajas: '缺点',
  },
  ko: {
    carpetaProyectos: '프로젝트',
    carpetaEpisodios: '팟캐스트 에피소드',
    carpetaCasa: '집',
    podcast: '잘 알려지지 않은 직업에 관한 팟캐스트 시작하기',
    podcastPunto1: '비슷한 프로그램 세 개를 듣고 잘된 점 적어 두기',
    podcastPunto2: '15분짜리 시험 에피소드 녹음하기',
    podcastPunto3: '브레인스토밍으로 이름 정하기',
    relojeria: '길모퉁이 시계 수리점 사장님 인터뷰하기',
    huerto: '부엌 창가에 허브 키우기',
    huertoPunto1: '창턱 길이 재기',
    huertoPunto2: '바질, 민트, 고수: 제일 자주 쓰는 세 가지',
    temaLluvia: '팟캐스트 이름',
    lluvia1: '이야기가 있는 직업',
    lluvia2: '손으로 일하는 사람들',
    lluvia3: '아무도 모르는 뒷이야기',
    ventajas: '장점',
    desventajas: '단점',
  },
  ru: {
    carpetaProyectos: 'Проекты',
    carpetaEpisodios: 'Выпуски подкаста',
    carpetaCasa: 'Дом',
    podcast: 'Запустить подкаст о малоизвестных профессиях',
    podcastPunto1: 'Послушать три похожие передачи и записать, что в них работает',
    podcastPunto2: 'Записать пробный выпуск на пятнадцать минут',
    podcastPunto3: 'Выбрать название мозговым штурмом',
    relojeria: 'Взять интервью в часовой мастерской на углу',
    huerto: 'Мини-огород с травами на кухонном окне',
    huertoPunto1: 'Измерить подоконник',
    huertoPunto2: 'Базилик, мята и кинза — самые ходовые',
    temaLluvia: 'Название подкаста',
    lluvia1: 'Ремёсла с историей',
    lluvia2: 'Своими руками',
    lluvia3: 'То, чего никто не видит',
    ventajas: 'Плюсы',
    desventajas: 'Минусы',
  },
  hi: {
    carpetaProyectos: 'प्रोजेक्ट',
    carpetaEpisodios: 'पॉडकास्ट के एपिसोड',
    carpetaCasa: 'घर',
    podcast: 'कम जाने-पहचाने पेशों पर पॉडकास्ट शुरू करना',
    podcastPunto1: 'मिलते-जुलते तीन शो सुनना और लिखना कि क्या काम करता है',
    podcastPunto2: 'पंद्रह मिनट का एक ट्रायल एपिसोड रिकॉर्ड करना',
    podcastPunto3: 'विचार-मंथन से नाम तय करना',
    relojeria: 'नुक्कड़ की घड़ी मरम्मत की दुकान पर इंटरव्यू करना',
    huerto: 'रसोई की खिड़की पर जड़ी-बूटियों का छोटा बगीचा',
    huertoPunto1: 'खिड़की की सिल नापना',
    huertoPunto2: 'बेसिल, पुदीना और धनिया, जो सबसे ज़्यादा काम आते हैं',
    temaLluvia: 'पॉडकास्ट का नाम',
    lluvia1: 'हुनर की कहानियाँ',
    lluvia2: 'हाथ का काम',
    lluvia3: 'जो कोई नहीं देखता',
    ventajas: 'फ़ायदे',
    desventajas: 'नुक़सान',
  },
  tr: {
    carpetaProyectos: 'Projeler',
    carpetaEpisodios: 'Podcast bölümleri',
    carpetaCasa: 'Ev',
    podcast: 'Az bilinen meslekler üzerine bir podcast başlatmak',
    podcastPunto1: 'Benzer üç programı dinleyip neyin işe yaradığını not etmek',
    podcastPunto2: 'On beş dakikalık bir deneme bölümü kaydetmek',
    podcastPunto3: 'İsmi beyin fırtınasıyla seçmek',
    relojeria: 'Köşedeki saat tamircisiyle röportaj yapmak',
    huerto: 'Mutfak penceresinde küçük bir ot bahçesi',
    huertoPunto1: 'Pencere pervazını ölçmek',
    huertoPunto2: 'Fesleğen, nane ve kişniş, en çok kullandıklarım',
    temaLluvia: 'Podcast adı',
    lluvia1: 'Hikâyesi olan meslekler',
    lluvia2: 'Kolları sıvamak',
    lluvia3: 'Kimsenin görmediği',
    ventajas: 'Artılar',
    desventajas: 'Eksiler',
  },
  id: {
    carpetaProyectos: 'Proyek',
    carpetaEpisodios: 'Episode podcast',
    carpetaCasa: 'Rumah',
    podcast: 'Memulai podcast tentang profesi yang jarang dikenal',
    podcastPunto1: 'Mendengarkan tiga acara serupa dan mencatat apa yang berhasil',
    podcastPunto2: 'Merekam episode percobaan lima belas menit',
    podcastPunto3: 'Menentukan nama lewat brainstorming',
    relojeria: 'Mewawancarai tukang servis jam di ujung jalan',
    huerto: 'Kebun herba di jendela dapur',
    huertoPunto1: 'Mengukur ambang jendela',
    huertoPunto2: 'Kemangi, mint, dan ketumbar, yang paling sering dipakai',
    temaLluvia: 'Nama podcast',
    lluvia1: 'Profesi penuh cerita',
    lluvia2: 'Turun tangan',
    lluvia3: 'Yang tak terlihat',
    ventajas: 'Kelebihan',
    desventajas: 'Kekurangan',
  },
  pl: {
    carpetaProyectos: 'Projekty',
    carpetaEpisodios: 'Odcinki podcastu',
    carpetaCasa: 'Dom',
    podcast: 'Założyć podcast o mało znanych zawodach',
    podcastPunto1: 'Posłuchać trzech podobnych audycji i zapisać, co działa',
    podcastPunto2: 'Nagrać piętnastominutowy odcinek próbny',
    podcastPunto3: 'Wybrać nazwę podczas burzy mózgów',
    relojeria: 'Przeprowadzić wywiad w pracowni zegarmistrzowskiej na rogu',
    huerto: 'Ogródek ziołowy w kuchennym oknie',
    huertoPunto1: 'Zmierzyć parapet',
    huertoPunto2: 'Bazylia, mięta i kolendra, bo tych używam najczęściej',
    temaLluvia: 'Nazwa podcastu',
    lluvia1: 'Zawody z historią',
    lluvia2: 'Do dzieła',
    lluvia3: 'Czego nikt nie widzi',
    ventajas: 'Za',
    desventajas: 'Przeciw',
  },
  ar: {
    carpetaProyectos: 'مشاريع',
    carpetaEpisodios: 'حلقات البودكاست',
    carpetaCasa: 'المنزل',
    podcast: 'إطلاق بودكاست عن مهن غير معروفة',
    podcastPunto1: 'الاستماع إلى ثلاثة برامج مشابهة وتدوين ما ينجح فيها',
    podcastPunto2: 'تسجيل حلقة تجريبية مدتها خمس عشرة دقيقة',
    podcastPunto3: 'اختيار الاسم بعصف ذهني',
    relojeria: 'إجراء مقابلة في محل تصليح الساعات عند الزاوية',
    huerto: 'حديقة أعشاب صغيرة على نافذة المطبخ',
    huertoPunto1: 'قياس عتبة النافذة',
    huertoPunto2: 'ريحان ونعناع وكزبرة، وهي الأكثر استخدامًا',
    temaLluvia: 'اسم البودكاست',
    lluvia1: 'مهن لها حكاية',
    lluvia2: 'صنعة يد',
    lluvia3: 'ما لا يراه أحد',
    ventajas: 'الإيجابيات',
    desventajas: 'السلبيات',
  },
  nl: {
    carpetaProyectos: 'Projecten',
    carpetaEpisodios: 'Podcastafleveringen',
    carpetaCasa: 'Thuis',
    podcast: 'Een podcast beginnen over onbekende ambachten',
    podcastPunto1: 'Drie vergelijkbare programma\'s luisteren en noteren wat werkt',
    podcastPunto2: 'Een proefaflevering van een kwartier opnemen',
    podcastPunto3: 'De naam kiezen met een brainstorm',
    relojeria: 'De horlogemaker op de hoek interviewen',
    huerto: 'Kruidentuintje in het keukenraam',
    huertoPunto1: 'De vensterbank opmeten',
    huertoPunto2: 'Basilicum, munt en koriander, die gebruik ik het meest',
    temaLluvia: 'Naam van de podcast',
    lluvia1: 'Ambachten met een verhaal',
    lluvia2: 'De handen uit de mouwen',
    lluvia3: 'Wat niemand ziet',
    ventajas: 'Voordelen',
    desventajas: 'Nadelen',
  },
}
