/**
 * Etiquetas de la casa demo que NO son contenido generado: los rótulos fijos de
 * los builders (cuidados de la agenda, pines de viaje, hábitos del calendario…)
 * y lo que la casa de Pep@ trae escrito en `public/demo/casa.json` (zonas,
 * Laika, letreros). Mismo criterio que `AHORROS` en el builder del despacho: van
 * aquí y no en `demo.data.ts` porque ese archivo lo genera la IA, y no en
 * `dict.ts` porque solo los usa la demo, que se carga aparte.
 *
 * El tipo obliga a que cada idioma traiga TODAS las claves. `{nombre}` es el de
 * la protagonista en el idioma activo (`demo.pep.nombre`).
 */
import { enIdioma, type PorIdioma } from '../core/i18n/porIdioma'
import type { Idioma } from '../core/i18n/idiomas'

const ES = {
  'cal.turno': 'Turno en la cafetería',
  'cal.clases': 'Clases de física',
  'cal.estudiar': 'Estudiar física',
  'cal.pantallas': 'Apagar todo y dormir',
  'cal.piano': 'Piano 20 minutos',
  'cal.idioma': 'Repaso de idioma',
  'cal.meditar': 'Meditar antes de salir',
  'cal.correr': 'Salir a correr',
  'cal.notaTurno': 'Cambié el turno con Nuria.',
  'ag.raza': 'Criolla',
  'ag.vacuna': 'Vacuna anual',
  'ag.desparasitacion': 'Desparasitación',
  'ag.bano': 'Baño y cepillado',
  'ag.vitaminaD': 'Vitamina D',
  'ag.dosisVitaminaD': '1000 UI',
  'ag.antiinflamatorio': 'Antiinflamatorio',
  'ag.notaRodilla': 'Por la rodilla, mientras duró la lesión.',
  'ag.enalapril': 'Enalapril',
  'ag.notaTension': 'Para la tensión. No saltarse ninguna.',
  'ag.chequeo': 'Chequeo general',
  'ag.dental': 'Limpieza dental',
  'ag.vista': 'Revisión de la vista',
  'ag.tension': 'Control de tensión',
  'ag.analisis': 'Análisis de sangre',
  'ag.cardiologo': 'Revisión con el cardiólogo',
  'ag.drFerran': 'Dra. Ferrán',
  'ag.labSur': 'Laboratorio Sur',
  'sala.lugar.tokio': 'Tokio',
  'sala.lugar.hakone': 'Hakone',
  'sala.lugar.kawaguchiko': 'Lago Kawaguchi',
  'sala.lugar.kioto': 'Kioto',
  'sala.lugar.nara': 'Nara',
  'sala.lugar.osaka': 'Osaka',
  'sala.lugar.hiroshima': 'Hiroshima',
  'sala.lugar.oaxaca': 'Oaxaca',
  'sala.lugar.valle': 'Valle de Bravo',
  'sala.lugar.seul': 'Seúl',
  'sala.lugar.patagonia': 'Patagonia',
  'sala.lugar.islandia': 'Reikiavik',
  'sala.ciudad.oaxaca': 'Oaxaca de Juárez',
  'sala.ruta.japon': 'Japón: de Tokio a Hiroshima',
  'sala.ruta.corea': 'Lo que sigue: Corea',
  'fin.propinas': 'Propinas',
  'bib.ramaDesc': 'Salió hablando con el tutor; lo dejé apuntado para volver.',
  'casa.zona.casa': 'La casa',
  'casa.zona.canchas': 'Canchas',
  'casa.zona.santuario': 'Santuario',
  'casa.zona.pista': 'Pista de carreras',
  'casa.zona.mindfulness': 'Mindfulness',
  'casa.zona.feria': 'Tren y feria',
  'casa.laika.historia': 'La gata de {nombre}. Llegó a la casa el mismo mes en que empezó a correr.',
  'casa.laika.personalidad': 'Curiosa y dormilona; opina de todo con calma felina.',
  'casa.laika.saludo': 'Miau. ¿Ya saliste a correr hoy?',
  'casa.laika.nombre': 'Laika',
  'casa.coche': 'Coche viejo',
  'casa.letrero': 'CASA DE {nombre}',
  'casa.feria': 'FERIA',
  'casa.alberca': 'Alberca',
  'ag.prox.turnoExtra': 'Turno extra en la cafetería',
  'ag.prox.cafeFamilia': 'Café con la familia',
  'ag.prox.rodilla': 'Revisión de la rodilla',
  'ag.prox.proyecto': 'Entrega del proyecto semestral',
}

export type ClaveDemo = keyof typeof ES

const TEXTOS: PorIdioma<Record<ClaveDemo, string>> = {
  es: ES,
  en: {
    'cal.turno': 'Shift at the coffee shop',
    'cal.clases': 'Physics classes',
    'cal.estudiar': 'Study physics',
    'cal.pantallas': 'Screens off, sleep',
    'cal.piano': 'Piano, 20 minutes',
    'cal.idioma': 'Language review',
    'cal.meditar': 'Meditate before heading out',
    'cal.correr': 'Go for a run',
    'cal.notaTurno': 'Swapped shifts with Nuria.',
    'ag.raza': 'Domestic shorthair',
    'ag.vacuna': 'Annual shot',
    'ag.desparasitacion': 'Deworming',
    'ag.bano': 'Bath and brushing',
    'ag.vitaminaD': 'Vitamin D',
    'ag.dosisVitaminaD': '1000 IU',
    'ag.antiinflamatorio': 'Anti-inflammatory',
    'ag.notaRodilla': 'For the knee, while the injury lasted.',
    'ag.enalapril': 'Enalapril',
    'ag.notaTension': 'Blood pressure. Never skip one.',
    'ag.chequeo': 'General checkup',
    'ag.dental': 'Dental cleaning',
    'ag.vista': 'Eye checkup',
    'ag.tension': 'Blood pressure check',
    'ag.analisis': 'Blood tests',
    'ag.cardiologo': 'Cardiologist follow-up',
    'ag.drFerran': 'Dr. Ferrán',
    'ag.labSur': 'South Lab',
    'sala.lugar.tokio': 'Tokyo',
    'sala.lugar.hakone': 'Hakone',
    'sala.lugar.kawaguchiko': 'Lake Kawaguchi',
    'sala.lugar.kioto': 'Kyoto',
    'sala.lugar.nara': 'Nara',
    'sala.lugar.osaka': 'Osaka',
    'sala.lugar.hiroshima': 'Hiroshima',
    'sala.lugar.oaxaca': 'Oaxaca',
    'sala.lugar.valle': 'Valle de Bravo',
    'sala.lugar.seul': 'Seoul',
    'sala.lugar.patagonia': 'Patagonia',
    'sala.lugar.islandia': 'Reykjavík',
    'sala.ciudad.oaxaca': 'Oaxaca de Juárez',
    'sala.ruta.japon': 'Japan: Tokyo to Hiroshima',
    'sala.ruta.corea': "What's next: Korea",
    'fin.propinas': 'Tips',
    'bib.ramaDesc': 'Came up while talking with the tutor; noted it to come back to it.',
    'casa.zona.casa': 'The house',
    'casa.zona.canchas': 'Courts',
    'casa.zona.santuario': 'Sanctuary',
    'casa.zona.pista': 'Race track',
    'casa.zona.mindfulness': 'Mindfulness',
    'casa.zona.feria': 'Train and fair',
    'casa.laika.historia': "{nombre}'s cat. She showed up at the house the same month {nombre} took up running.",
    'casa.laika.personalidad': 'Curious and sleepy; has an opinion on everything, with feline calm.',
    'casa.laika.saludo': 'Meow. Have you been out for a run yet today?',
    'casa.laika.nombre': 'Laika',
    'casa.coche': 'Old car',
    'casa.letrero': "{nombre}'S HOUSE",
    'casa.feria': 'FAIR',
    'casa.alberca': 'Pool',
    'ag.prox.turnoExtra': 'Extra shift at the coffee shop',
    'ag.prox.cafeFamilia': 'Coffee with the family',
    'ag.prox.rodilla': 'Knee check-up',
    'ag.prox.proyecto': 'Semester project hand-in',
  },
  pt: {
    'cal.turno': 'Turno na cafeteria',
    'cal.clases': 'Aulas de física',
    'cal.estudiar': 'Estudar física',
    'cal.pantallas': 'Desligar tudo e dormir',
    'cal.piano': 'Piano 20 minutos',
    'cal.idioma': 'Revisão de idioma',
    'cal.meditar': 'Meditar antes de sair',
    'cal.correr': 'Sair para correr',
    'cal.notaTurno': 'Troquei o turno com a Nuria.',
    'ag.raza': 'Vira-lata',
    'ag.vacuna': 'Vacina anual',
    'ag.desparasitacion': 'Vermífugo',
    'ag.bano': 'Banho e escovação',
    'ag.vitaminaD': 'Vitamina D',
    'ag.dosisVitaminaD': '1000 UI',
    'ag.antiinflamatorio': 'Anti-inflamatório',
    'ag.notaRodilla': 'Para o joelho, enquanto durou a lesão.',
    'ag.enalapril': 'Enalapril',
    'ag.notaTension': 'Para a pressão. Não pular nenhuma dose.',
    'ag.chequeo': 'Check-up geral',
    'ag.dental': 'Limpeza dental',
    'ag.vista': 'Exame de vista',
    'ag.tension': 'Controle da pressão',
    'ag.analisis': 'Exame de sangue',
    'ag.cardiologo': 'Retorno com a cardiologista',
    'ag.drFerran': 'Dra. Ferrán',
    'ag.labSur': 'Laboratório Sul',
    'sala.lugar.tokio': 'Tóquio',
    'sala.lugar.hakone': 'Hakone',
    'sala.lugar.kawaguchiko': 'Lago Kawaguchi',
    'sala.lugar.kioto': 'Quioto',
    'sala.lugar.nara': 'Nara',
    'sala.lugar.osaka': 'Osaka',
    'sala.lugar.hiroshima': 'Hiroshima',
    'sala.lugar.oaxaca': 'Oaxaca',
    'sala.lugar.valle': 'Valle de Bravo',
    'sala.lugar.seul': 'Seul',
    'sala.lugar.patagonia': 'Patagônia',
    'sala.lugar.islandia': 'Reykjavík',
    'sala.ciudad.oaxaca': 'Oaxaca de Juárez',
    'sala.ruta.japon': 'Japão: de Tóquio a Hiroshima',
    'sala.ruta.corea': 'Próximo destino: Coreia',
    'fin.propinas': 'Gorjetas',
    'bib.ramaDesc': 'Surgiu conversando com o tutor; deixei anotado para retomar depois.',
    'casa.zona.casa': 'A casa',
    'casa.zona.canchas': 'Quadras',
    'casa.zona.santuario': 'Santuário',
    'casa.zona.pista': 'Pista de corrida',
    'casa.zona.mindfulness': 'Mindfulness',
    'casa.zona.feria': 'Trem e parque',
    'casa.laika.historia': 'A gata de {nombre}. Chegou à casa no mesmo mês das primeiras corridas.',
    'casa.laika.personalidad': 'Curiosa e dorminhoca; opina sobre tudo com calma felina.',
    'casa.laika.saludo': 'Miau. Você já saiu para correr hoje?',
    'casa.laika.nombre': 'Laika',
    'casa.coche': 'Carro velho',
    'casa.letrero': 'CASA DE {nombre}',
    'casa.feria': 'PARQUE',
    'casa.alberca': 'Piscina',
    'ag.prox.turnoExtra': 'Turno extra na cafeteria',
    'ag.prox.cafeFamilia': 'Café com a família',
    'ag.prox.rodilla': 'Consulta do joelho',
    'ag.prox.proyecto': 'Entrega do projeto semestral',
  },
  fr: {
    'cal.turno': 'Service au café',
    'cal.clases': 'Cours de physique',
    'cal.estudiar': 'Étudier la physique',
    'cal.pantallas': 'Tout éteindre et dormir',
    'cal.piano': 'Piano, 20 minutes',
    'cal.idioma': 'Révision de langue',
    'cal.meditar': 'Méditer avant de sortir',
    'cal.correr': 'Aller courir',
    'cal.notaTurno': 'J’ai échangé mon service avec Nuria.',
    'ag.raza': 'Européenne',
    'ag.vacuna': 'Vaccin annuel',
    'ag.desparasitacion': 'Vermifuge',
    'ag.bano': 'Bain et brossage',
    'ag.vitaminaD': 'Vitamine D',
    'ag.dosisVitaminaD': '1000 UI',
    'ag.antiinflamatorio': 'Anti-inflammatoire',
    'ag.notaRodilla': 'Pour le genou, le temps qu’a duré la blessure.',
    'ag.enalapril': 'Énalapril',
    'ag.notaTension': 'Pour la tension. Ne sauter aucune prise.',
    'ag.chequeo': 'Bilan général',
    'ag.dental': 'Détartrage dentaire',
    'ag.vista': 'Contrôle de la vue',
    'ag.tension': 'Contrôle de la tension',
    'ag.analisis': 'Prise de sang',
    'ag.cardiologo': 'Suivi cardiologique',
    'ag.drFerran': 'Dr Ferrán',
    'ag.labSur': 'Laboratoire Sud',
    'sala.lugar.tokio': 'Tokyo',
    'sala.lugar.hakone': 'Hakone',
    'sala.lugar.kawaguchiko': 'Lac Kawaguchi',
    'sala.lugar.kioto': 'Kyoto',
    'sala.lugar.nara': 'Nara',
    'sala.lugar.osaka': 'Osaka',
    'sala.lugar.hiroshima': 'Hiroshima',
    'sala.lugar.oaxaca': 'Oaxaca',
    'sala.lugar.valle': 'Valle de Bravo',
    'sala.lugar.seul': 'Séoul',
    'sala.lugar.patagonia': 'Patagonie',
    'sala.lugar.islandia': 'Reykjavik',
    'sala.ciudad.oaxaca': 'Oaxaca de Juárez',
    'sala.ruta.japon': 'Japon : de Tokyo à Hiroshima',
    'sala.ruta.corea': 'Prochaine étape : la Corée',
    'fin.propinas': 'Pourboires',
    'bib.ramaDesc': 'C’est sorti d’une discussion avec le tuteur ; je l’ai noté pour y revenir.',
    'casa.zona.casa': 'La maison',
    'casa.zona.canchas': 'Terrains',
    'casa.zona.santuario': 'Sanctuaire',
    'casa.zona.pista': 'Circuit de course',
    'casa.zona.mindfulness': 'Pleine conscience',
    'casa.zona.feria': 'Train et manèges',
    'casa.laika.historia': 'La compagne féline de {nombre}. Elle est arrivée à la maison le mois même des premiers footings.',
    'casa.laika.personalidad': 'Curieuse et grande dormeuse ; elle donne son avis sur tout avec un calme félin.',
    'casa.laika.saludo': 'Miaou. Tu as déjà couru aujourd’hui ?',
    'casa.laika.nombre': 'Laika',
    'casa.coche': 'Vieille voiture',
    'casa.letrero': 'CHEZ {nombre}',
    'casa.feria': 'FOIRE',
    'casa.alberca': 'Piscine',
    'ag.prox.turnoExtra': 'Service supplémentaire au café',
    'ag.prox.cafeFamilia': 'Café en famille',
    'ag.prox.rodilla': 'Contrôle du genou',
    'ag.prox.proyecto': 'Rendu du projet semestriel',
  },
  de: {
    'cal.turno': 'Schicht im Café',
    'cal.clases': 'Physikvorlesungen',
    'cal.estudiar': 'Physik lernen',
    'cal.pantallas': 'Alles aus und schlafen',
    'cal.piano': 'Klavier, 20 Minuten',
    'cal.idioma': 'Vokabeln wiederholen',
    'cal.meditar': 'Meditieren vor dem Losgehen',
    'cal.correr': 'Laufen gehen',
    'cal.notaTurno': 'Schicht mit Nuria getauscht.',
    'ag.raza': 'Hauskatze',
    'ag.vacuna': 'Jährliche Impfung',
    'ag.desparasitacion': 'Entwurmung',
    'ag.bano': 'Baden und Bürsten',
    'ag.vitaminaD': 'Vitamin D',
    'ag.dosisVitaminaD': '1000 I.E.',
    'ag.antiinflamatorio': 'Entzündungshemmer',
    'ag.notaRodilla': 'Fürs Knie, solange die Verletzung dauerte.',
    'ag.enalapril': 'Enalapril',
    'ag.notaTension': 'Für den Blutdruck. Keine Einnahme auslassen.',
    'ag.chequeo': 'Allgemeine Kontrolle',
    'ag.dental': 'Zahnreinigung',
    'ag.vista': 'Augenkontrolle',
    'ag.tension': 'Blutdruckkontrolle',
    'ag.analisis': 'Blutuntersuchung',
    'ag.cardiologo': 'Kardiologische Kontrolle',
    'ag.drFerran': 'Dr. Ferrán',
    'ag.labSur': 'Labor Süd',
    'sala.lugar.tokio': 'Tokio',
    'sala.lugar.hakone': 'Hakone',
    'sala.lugar.kawaguchiko': 'Kawaguchi-See',
    'sala.lugar.kioto': 'Kyoto',
    'sala.lugar.nara': 'Nara',
    'sala.lugar.osaka': 'Osaka',
    'sala.lugar.hiroshima': 'Hiroshima',
    'sala.lugar.oaxaca': 'Oaxaca',
    'sala.lugar.valle': 'Valle de Bravo',
    'sala.lugar.seul': 'Seoul',
    'sala.lugar.patagonia': 'Patagonien',
    'sala.lugar.islandia': 'Reykjavík',
    'sala.ciudad.oaxaca': 'Oaxaca de Juárez',
    'sala.ruta.japon': 'Japan: von Tokio nach Hiroshima',
    'sala.ruta.corea': 'Als Nächstes: Korea',
    'fin.propinas': 'Trinkgeld',
    'bib.ramaDesc': 'Kam im Gespräch mit dem Tutor auf; ich habe es mir notiert, um darauf zurückzukommen.',
    'casa.zona.casa': 'Das Haus',
    'casa.zona.canchas': 'Plätze',
    'casa.zona.santuario': 'Refugium',
    'casa.zona.pista': 'Rennstrecke',
    'casa.zona.mindfulness': 'Achtsamkeit',
    'casa.zona.feria': 'Zug und Jahrmarkt',
    'casa.laika.historia': '{nombre}s Katze. Sie zog im selben Monat ein, in dem auch das Laufen anfing.',
    'casa.laika.personalidad': 'Neugierig und verschlafen; hat zu allem eine Meinung, mit katzenhafter Gelassenheit.',
    'casa.laika.saludo': 'Miau. Warst du heute schon laufen?',
    'casa.laika.nombre': 'Laika',
    'casa.coche': 'Altes Auto',
    'casa.letrero': '{nombre}S HAUS',
    'casa.feria': 'JAHRMARKT',
    'casa.alberca': 'Pool',
    'ag.prox.turnoExtra': 'Extraschicht im Café',
    'ag.prox.cafeFamilia': 'Kaffee mit der Familie',
    'ag.prox.rodilla': 'Knie-Kontrolle',
    'ag.prox.proyecto': 'Abgabe des Semesterprojekts',
  },
  it: {
    'cal.turno': 'Turno al bar',
    'cal.clases': 'Lezioni di fisica',
    'cal.estudiar': 'Studiare fisica',
    'cal.pantallas': 'Spegnere tutto e dormire',
    'cal.piano': 'Pianoforte 20 minuti',
    'cal.idioma': 'Ripasso della lingua',
    'cal.meditar': 'Meditare prima di uscire',
    'cal.correr': 'Andare a correre',
    'cal.notaTurno': 'Ho scambiato il turno con Nuria.',
    'ag.raza': 'Comune europeo',
    'ag.vacuna': 'Vaccino annuale',
    'ag.desparasitacion': 'Sverminazione',
    'ag.bano': 'Bagno e spazzolatura',
    'ag.vitaminaD': 'Vitamina D',
    'ag.dosisVitaminaD': '1000 UI',
    'ag.antiinflamatorio': 'Antinfiammatorio',
    'ag.notaRodilla': "Per il ginocchio, finché è durato l'infortunio.",
    'ag.enalapril': 'Enalapril',
    'ag.notaTension': 'Per la pressione. Non saltarne nemmeno una.',
    'ag.chequeo': 'Controllo generale',
    'ag.dental': 'Pulizia dei denti',
    'ag.vista': 'Controllo della vista',
    'ag.tension': 'Controllo della pressione',
    'ag.analisis': 'Esami del sangue',
    'ag.cardiologo': 'Controllo dal cardiologo',
    'ag.drFerran': 'Dott.ssa Ferrán',
    'ag.labSur': 'Laboratorio Sud',
    'sala.lugar.tokio': 'Tokyo',
    'sala.lugar.hakone': 'Hakone',
    'sala.lugar.kawaguchiko': 'Lago Kawaguchi',
    'sala.lugar.kioto': 'Kyoto',
    'sala.lugar.nara': 'Nara',
    'sala.lugar.osaka': 'Osaka',
    'sala.lugar.hiroshima': 'Hiroshima',
    'sala.lugar.oaxaca': 'Oaxaca',
    'sala.lugar.valle': 'Valle de Bravo',
    'sala.lugar.seul': 'Seul',
    'sala.lugar.patagonia': 'Patagonia',
    'sala.lugar.islandia': 'Reykjavík',
    'sala.ciudad.oaxaca': 'Oaxaca de Juárez',
    'sala.ruta.japon': 'Giappone: da Tokyo a Hiroshima',
    'sala.ruta.corea': 'Prossima tappa: Corea',
    'fin.propinas': 'Mance',
    'bib.ramaDesc': "È saltato fuori in una chiacchierata con il tutor; l'ho annotato per tornarci sopra.",
    'casa.zona.casa': 'La casa',
    'casa.zona.canchas': 'Campi',
    'casa.zona.santuario': 'Santuario',
    'casa.zona.pista': 'Pista da corsa',
    'casa.zona.mindfulness': 'Mindfulness',
    'casa.zona.feria': 'Treno e luna park',
    'casa.laika.historia': "La gatta di {nombre}, che l'ha accolta in casa nello stesso mese in cui ha iniziato a correre.",
    'casa.laika.personalidad': 'Curiosa e dormigliona; dice la sua su tutto con calma felina.',
    'casa.laika.saludo': 'Miao. Oggi hai già corso?',
    'casa.laika.nombre': 'Laika',
    'casa.coche': 'Vecchia auto',
    'casa.letrero': 'CASA DI {nombre}',
    'casa.feria': 'LUNAPARK',
    'casa.alberca': 'Piscina',
    'ag.prox.turnoExtra': 'Turno extra al bar',
    'ag.prox.cafeFamilia': 'Caffè con la famiglia',
    'ag.prox.rodilla': 'Controllo del ginocchio',
    'ag.prox.proyecto': 'Consegna del progetto semestrale',
  },
  ja: {
    'cal.turno': 'カフェのシフト',
    'cal.clases': '物理学の授業',
    'cal.estudiar': '物理学を勉強する',
    'cal.pantallas': '画面を消して寝る',
    'cal.piano': 'ピアノ20分',
    'cal.idioma': '語学の復習',
    'cal.meditar': '出かける前に瞑想する',
    'cal.correr': '走りに行く',
    'cal.notaTurno': 'ヌリアとシフトを交換しました。',
    'ag.raza': 'ミックス',
    'ag.vacuna': '年1回のワクチン',
    'ag.desparasitacion': '駆虫',
    'ag.bano': 'シャンプーとブラッシング',
    'ag.vitaminaD': 'ビタミンD',
    'ag.dosisVitaminaD': '1000 IU',
    'ag.antiinflamatorio': '消炎鎮痛剤',
    'ag.notaRodilla': '膝のけがが治るまでの間、飲んでいました。',
    'ag.enalapril': 'エナラプリル',
    'ag.notaTension': '血圧の薬です。一度も飲み忘れないように。',
    'ag.chequeo': '総合健診',
    'ag.dental': '歯のクリーニング',
    'ag.vista': '眼科検診',
    'ag.tension': '血圧チェック',
    'ag.analisis': '血液検査',
    'ag.cardiologo': '循環器内科の診察',
    'ag.drFerran': 'フェラン先生',
    'ag.labSur': 'みなみ検査センター',
    'sala.lugar.tokio': '東京',
    'sala.lugar.hakone': '箱根',
    'sala.lugar.kawaguchiko': '河口湖',
    'sala.lugar.kioto': '京都',
    'sala.lugar.nara': '奈良',
    'sala.lugar.osaka': '大阪',
    'sala.lugar.hiroshima': '広島',
    'sala.lugar.oaxaca': 'オアハカ',
    'sala.lugar.valle': 'バジェ・デ・ブラボ',
    'sala.lugar.seul': 'ソウル',
    'sala.lugar.patagonia': 'パタゴニア',
    'sala.lugar.islandia': 'レイキャビク',
    'sala.ciudad.oaxaca': 'オアハカ・デ・フアレス',
    'sala.ruta.japon': '日本：東京から広島へ',
    'sala.ruta.corea': '次の旅：韓国',
    'fin.propinas': 'チップ',
    'bib.ramaDesc': 'チューターと話していて出てきた話題です。あとで戻れるようにメモしておきました。',
    'casa.zona.casa': '家',
    'casa.zona.canchas': 'コート',
    'casa.zona.santuario': 'サンクチュアリ',
    'casa.zona.pista': 'レーストラック',
    'casa.zona.mindfulness': 'マインドフルネス',
    'casa.zona.feria': '汽車と遊園地',
    'casa.laika.historia': '{nombre}の猫です。飼い主がランニングを始めたのと同じ月に、この家にやって来ました。',
    'casa.laika.personalidad': '好奇心旺盛で、お昼寝が大好きです。何にでも猫らしく落ち着き払って意見を言います。',
    'casa.laika.saludo': 'にゃー。今日はもう走りに行きましたか？',
    'casa.laika.nombre': 'ライカ',
    'casa.coche': '古い車',
    'casa.letrero': '{nombre}の家',
    'casa.feria': '遊園地',
    'casa.alberca': 'プール',
    'ag.prox.turnoExtra': 'カフェの臨時シフト',
    'ag.prox.cafeFamilia': '家族とお茶',
    'ag.prox.rodilla': '膝の診察',
    'ag.prox.proyecto': '学期プロジェクトの提出',
  },
  zh: {
    'cal.turno': '咖啡店上班',
    'cal.clases': '物理课',
    'cal.estudiar': '学习物理',
    'cal.pantallas': '关机睡觉',
    'cal.piano': '练琴20分钟',
    'cal.idioma': '复习外语',
    'cal.meditar': '出门前冥想',
    'cal.correr': '出门跑步',
    'cal.notaTurno': '跟努丽亚换了班。',
    'ag.raza': '田园猫',
    'ag.vacuna': '年度疫苗',
    'ag.desparasitacion': '驱虫',
    'ag.bano': '洗澡和梳毛',
    'ag.vitaminaD': '维生素D',
    'ag.dosisVitaminaD': '1000 IU',
    'ag.antiinflamatorio': '消炎止痛药',
    'ag.notaRodilla': '治膝盖的，受伤那段时间吃的。',
    'ag.enalapril': '依那普利',
    'ag.notaTension': '降血压用的。一次都不能漏。',
    'ag.chequeo': '全面体检',
    'ag.dental': '洗牙',
    'ag.vista': '视力检查',
    'ag.tension': '血压检查',
    'ag.analisis': '验血',
    'ag.cardiologo': '心内科复诊',
    'ag.drFerran': '费兰医生',
    'ag.labSur': '城南检验中心',
    'sala.lugar.tokio': '东京',
    'sala.lugar.hakone': '箱根',
    'sala.lugar.kawaguchiko': '河口湖',
    'sala.lugar.kioto': '京都',
    'sala.lugar.nara': '奈良',
    'sala.lugar.osaka': '大阪',
    'sala.lugar.hiroshima': '广岛',
    'sala.lugar.oaxaca': '瓦哈卡',
    'sala.lugar.valle': '巴耶德布拉沃',
    'sala.lugar.seul': '首尔',
    'sala.lugar.patagonia': '巴塔哥尼亚',
    'sala.lugar.islandia': '雷克雅未克',
    'sala.ciudad.oaxaca': '瓦哈卡德华雷斯',
    'sala.ruta.japon': '日本：从东京到广岛',
    'sala.ruta.corea': '下一站：韩国',
    'fin.propinas': '小费',
    'bib.ramaDesc': '和智者聊天时冒出来的；先记下来，回头再看。',
    'casa.zona.casa': '家',
    'casa.zona.canchas': '球场',
    'casa.zona.santuario': '庇护所',
    'casa.zona.pista': '赛道',
    'casa.zona.mindfulness': '正念',
    'casa.zona.feria': '火车与游乐场',
    'casa.laika.historia': '{nombre}的猫。她来到这个家的那个月，主人刚好开始跑步。',
    'casa.laika.personalidad': '好奇又贪睡；什么都要点评几句，一副猫科动物的淡定。',
    'casa.laika.saludo': '喵。今天出门跑过步了吗？',
    'casa.laika.nombre': '莱卡',
    'casa.coche': '老爷车',
    'casa.letrero': '{nombre}的家',
    'casa.feria': '游乐场',
    'casa.alberca': '泳池',
    'ag.prox.turnoExtra': '咖啡馆加班',
    'ag.prox.cafeFamilia': '和家人喝咖啡',
    'ag.prox.rodilla': '膝盖复查',
    'ag.prox.proyecto': '提交学期项目',
  },
  ko: {
    'cal.turno': '카페 근무',
    'cal.clases': '물리학 수업',
    'cal.estudiar': '물리학 공부하기',
    'cal.pantallas': '화면 끄고 잠들기',
    'cal.piano': '피아노 20분',
    'cal.idioma': '어학 복습',
    'cal.meditar': '나가기 전에 명상하기',
    'cal.correr': '달리러 나가기',
    'cal.notaTurno': '누리아와 근무를 바꿨어요.',
    'ag.raza': '코리안 숏헤어',
    'ag.vacuna': '연간 예방접종',
    'ag.desparasitacion': '구충',
    'ag.bano': '목욕과 빗질',
    'ag.vitaminaD': '비타민 D',
    'ag.dosisVitaminaD': '1000 IU',
    'ag.antiinflamatorio': '소염제',
    'ag.notaRodilla': '무릎 때문에, 부상이 나을 때까지 먹었어요.',
    'ag.enalapril': '에날라프릴',
    'ag.notaTension': '혈압약이에요. 한 번도 거르면 안 돼요.',
    'ag.chequeo': '종합 건강검진',
    'ag.dental': '스케일링',
    'ag.vista': '시력 검사',
    'ag.tension': '혈압 검사',
    'ag.analisis': '혈액 검사',
    'ag.cardiologo': '심장내과 정기 진료',
    'ag.drFerran': '페란 선생님',
    'ag.labSur': '남부 임상검사센터',
    'sala.lugar.tokio': '도쿄',
    'sala.lugar.hakone': '하코네',
    'sala.lugar.kawaguchiko': '가와구치호',
    'sala.lugar.kioto': '교토',
    'sala.lugar.nara': '나라',
    'sala.lugar.osaka': '오사카',
    'sala.lugar.hiroshima': '히로시마',
    'sala.lugar.oaxaca': '오악사카',
    'sala.lugar.valle': '바예데브라보',
    'sala.lugar.seul': '서울',
    'sala.lugar.patagonia': '파타고니아',
    'sala.lugar.islandia': '레이캬비크',
    'sala.ciudad.oaxaca': '오악사카데후아레스',
    'sala.ruta.japon': '일본: 도쿄에서 히로시마까지',
    'sala.ruta.corea': '다음 여행: 한국',
    'fin.propinas': '팁',
    'bib.ramaDesc': '현자와 이야기하다가 나온 주제예요. 나중에 다시 보려고 적어 뒀어요.',
    'casa.zona.casa': '집',
    'casa.zona.canchas': '코트',
    'casa.zona.santuario': '생추어리',
    'casa.zona.pista': '경주 트랙',
    'casa.zona.mindfulness': '마음챙김',
    'casa.zona.feria': '기차와 놀이동산',
    'casa.laika.historia': '{nombre}의 고양이예요. 주인이 달리기를 시작한 바로 그달에 이 집에 왔어요.',
    'casa.laika.personalidad': '호기심 많은 잠꾸러기예요. 무슨 일에든 고양이다운 여유로 한마디씩 해요.',
    'casa.laika.saludo': '야옹. 오늘 벌써 달리고 왔어요?',
    'casa.laika.nombre': '라이카',
    'casa.coche': '낡은 차',
    'casa.letrero': '{nombre}의 집',
    'casa.feria': '놀이동산',
    'casa.alberca': '수영장',
    'ag.prox.turnoExtra': '카페 추가 근무',
    'ag.prox.cafeFamilia': '가족과 커피',
    'ag.prox.rodilla': '무릎 검진',
    'ag.prox.proyecto': '학기 프로젝트 제출',
  },
  ru: {
    'cal.turno': 'Смена в кофейне',
    'cal.clases': 'Занятия по физике',
    'cal.estudiar': 'Учить физику',
    'cal.pantallas': 'Выключить всё и спать',
    'cal.piano': 'Пианино 20 минут',
    'cal.idioma': 'Повторение языка',
    'cal.meditar': 'Помедитировать перед выходом',
    'cal.correr': 'Выйти на пробежку',
    'cal.notaTurno': 'Поменялись с Нурией сменами.',
    'ag.raza': 'Беспородная',
    'ag.vacuna': 'Ежегодная прививка',
    'ag.desparasitacion': 'Дегельминтизация',
    'ag.bano': 'Купание и вычёсывание',
    'ag.vitaminaD': 'Витамин D',
    'ag.dosisVitaminaD': '1000 МЕ',
    'ag.antiinflamatorio': 'Противовоспалительное',
    'ag.notaRodilla': 'Для колена, пока длилась травма.',
    'ag.enalapril': 'Эналаприл',
    'ag.notaTension': 'От давления. Не пропускать ни одного приёма.',
    'ag.chequeo': 'Общий осмотр',
    'ag.dental': 'Профчистка зубов',
    'ag.vista': 'Проверка зрения',
    'ag.tension': 'Контроль давления',
    'ag.analisis': 'Анализ крови',
    'ag.cardiologo': 'Приём у кардиолога',
    'ag.drFerran': 'Доктор Ферран',
    'ag.labSur': 'Лаборатория «Юг»',
    'sala.lugar.tokio': 'Токио',
    'sala.lugar.hakone': 'Хаконэ',
    'sala.lugar.kawaguchiko': 'Озеро Кавагутико',
    'sala.lugar.kioto': 'Киото',
    'sala.lugar.nara': 'Нара',
    'sala.lugar.osaka': 'Осака',
    'sala.lugar.hiroshima': 'Хиросима',
    'sala.lugar.oaxaca': 'Оахака',
    'sala.lugar.valle': 'Валье-де-Браво',
    'sala.lugar.seul': 'Сеул',
    'sala.lugar.patagonia': 'Патагония',
    'sala.lugar.islandia': 'Рейкьявик',
    'sala.ciudad.oaxaca': 'Оахака-де-Хуарес',
    'sala.ruta.japon': 'Япония: из Токио в Хиросиму',
    'sala.ruta.corea': 'На очереди: Корея',
    'fin.propinas': 'Чаевые',
    'bib.ramaDesc': 'Всплыло в разговоре с репетитором; записано, чтобы к этому вернуться.',
    'casa.zona.casa': 'Дом',
    'casa.zona.canchas': 'Площадки',
    'casa.zona.santuario': 'Приют',
    'casa.zona.pista': 'Гоночная трасса',
    'casa.zona.mindfulness': 'Осознанность',
    'casa.zona.feria': 'Поезд и ярмарка',
    'casa.laika.historia': 'Кошка, с которой живёт {nombre}. Появилась в доме в тот же месяц, когда начались пробежки.',
    'casa.laika.personalidad': 'Любопытная и большая соня; высказывается обо всём с кошачьим спокойствием.',
    'casa.laika.saludo': 'Мяу. Сегодня пробежка уже была?',
    'casa.laika.nombre': 'Лайка',
    'casa.coche': 'Старая машина',
    'casa.letrero': 'ЗДЕСЬ ЖИВЁТ {nombre}',
    'casa.feria': 'ЯРМАРКА',
    'casa.alberca': 'Бассейн',
    'ag.prox.turnoExtra': 'Дополнительная смена в кофейне',
    'ag.prox.cafeFamilia': 'Кофе с семьёй',
    'ag.prox.rodilla': 'Осмотр колена',
    'ag.prox.proyecto': 'Сдача семестрового проекта',
  },
  hi: {
    'cal.turno': 'कैफ़े की शिफ़्ट',
    'cal.clases': 'फ़िज़िक्स की क्लास',
    'cal.estudiar': 'फ़िज़िक्स की पढ़ाई',
    'cal.pantallas': 'सब बंद करके सोना',
    'cal.piano': 'पियानो 20 मिनट',
    'cal.idioma': 'भाषा का रिवीज़न',
    'cal.meditar': 'निकलने से पहले ध्यान',
    'cal.correr': 'दौड़ने जाना',
    'cal.notaTurno': 'नूरिया के साथ शिफ़्ट बदल ली।',
    'ag.raza': 'देसी',
    'ag.vacuna': 'सालाना वैक्सीन',
    'ag.desparasitacion': 'कृमि मुक्ति',
    'ag.bano': 'नहलाना और कंघी करना',
    'ag.vitaminaD': 'विटामिन डी',
    'ag.dosisVitaminaD': '1000 आईयू',
    'ag.antiinflamatorio': 'सूजन की दवा',
    'ag.notaRodilla': 'घुटने के लिए, जब तक चोट रही।',
    'ag.enalapril': 'एनालाप्रिल',
    'ag.notaTension': 'ब्लड प्रेशर के लिए। एक भी खुराक न छूटे।',
    'ag.chequeo': 'सामान्य जांच',
    'ag.dental': 'दांतों की सफ़ाई',
    'ag.vista': 'आंखों की जांच',
    'ag.tension': 'ब्लड प्रेशर की जांच',
    'ag.analisis': 'ब्लड टेस्ट',
    'ag.cardiologo': 'कार्डियोलॉजिस्ट से जांच',
    'ag.drFerran': 'डॉ. फ़ेरान',
    'ag.labSur': 'साउथ पैथ लैब',
    'sala.lugar.tokio': 'टोक्यो',
    'sala.lugar.hakone': 'हाकोने',
    'sala.lugar.kawaguchiko': 'कावागुची झील',
    'sala.lugar.kioto': 'क्योटो',
    'sala.lugar.nara': 'नारा',
    'sala.lugar.osaka': 'ओसाका',
    'sala.lugar.hiroshima': 'हिरोशिमा',
    'sala.lugar.oaxaca': 'वाहाका',
    'sala.lugar.valle': 'वाये दे ब्रावो',
    'sala.lugar.seul': 'सियोल',
    'sala.lugar.patagonia': 'पैटागोनिया',
    'sala.lugar.islandia': 'रेक्याविक',
    'sala.ciudad.oaxaca': 'वाहाका दे हुआरेज़',
    'sala.ruta.japon': 'जापान: टोक्यो से हिरोशिमा तक',
    'sala.ruta.corea': 'अगला सफ़र: कोरिया',
    'fin.propinas': 'टिप',
    'bib.ramaDesc': 'ट्यूटर से बातों-बातों में यह विषय निकल आया; बाद में इस पर लौटने के लिए नोट कर लिया।',
    'casa.zona.casa': 'घर',
    'casa.zona.canchas': 'मैदान',
    'casa.zona.santuario': 'अभयारण्य',
    'casa.zona.pista': 'रेस ट्रैक',
    'casa.zona.mindfulness': 'सजगता',
    'casa.zona.feria': 'ट्रेन और मेला',
    'casa.laika.historia': '{nombre} की बिल्ली। वह उसी महीने घर आई, जिस महीने {nombre} ने दौड़ना शुरू किया।',
    'casa.laika.personalidad': 'जिज्ञासु और नींद की दीवानी; हर बात पर बिल्लियों वाले इत्मीनान से अपनी राय देती है।',
    'casa.laika.saludo': 'म्याऊं। आपने आज दौड़ लगा ली?',
    'casa.laika.nombre': 'लाइका',
    'casa.coche': 'पुरानी कार',
    'casa.letrero': '{nombre} का घर',
    'casa.feria': 'मेला',
    'casa.alberca': 'स्विमिंग पूल',
    'ag.prox.turnoExtra': 'कैफ़े में अतिरिक्त शिफ़्ट',
    'ag.prox.cafeFamilia': 'परिवार के साथ कॉफ़ी',
    'ag.prox.rodilla': 'घुटने की जाँच',
    'ag.prox.proyecto': 'सेमेस्टर प्रोजेक्ट जमा करना',
  },
  tr: {
    'cal.turno': 'Kafede vardiya',
    'cal.clases': 'Fizik dersleri',
    'cal.estudiar': 'Fizik çalış',
    'cal.pantallas': 'Her şeyi kapat ve uyu',
    'cal.piano': '20 dakika piyano',
    'cal.idioma': 'Dil tekrarı',
    'cal.meditar': 'Çıkmadan önce meditasyon yap',
    'cal.correr': 'Koşuya çık',
    'cal.notaTurno': 'Vardiyamı Nuria’yla değiştim.',
    'ag.raza': 'Melez',
    'ag.vacuna': 'Yıllık aşı',
    'ag.desparasitacion': 'Parazit tedavisi',
    'ag.bano': 'Banyo ve tarama',
    'ag.vitaminaD': 'D vitamini',
    'ag.dosisVitaminaD': '1000 IU',
    'ag.antiinflamatorio': 'İltihap giderici',
    'ag.notaRodilla': 'Dizim için, sakatlık süresince.',
    'ag.enalapril': 'Enalapril',
    'ag.notaTension': 'Tansiyon için. Tek doz bile atlanmasın.',
    'ag.chequeo': 'Genel kontrol',
    'ag.dental': 'Diş temizliği',
    'ag.vista': 'Göz kontrolü',
    'ag.tension': 'Tansiyon kontrolü',
    'ag.analisis': 'Kan tahlili',
    'ag.cardiologo': 'Kardiyolog kontrolü',
    'ag.drFerran': 'Dr. Ferrán',
    'ag.labSur': 'Güney Laboratuvarı',
    'sala.lugar.tokio': 'Tokyo',
    'sala.lugar.hakone': 'Hakone',
    'sala.lugar.kawaguchiko': 'Kawaguchi Gölü',
    'sala.lugar.kioto': 'Kyoto',
    'sala.lugar.nara': 'Nara',
    'sala.lugar.osaka': 'Osaka',
    'sala.lugar.hiroshima': 'Hiroshima',
    'sala.lugar.oaxaca': 'Oaxaca',
    'sala.lugar.valle': 'Valle de Bravo',
    'sala.lugar.seul': 'Seul',
    'sala.lugar.patagonia': 'Patagonya',
    'sala.lugar.islandia': 'Reykjavik',
    'sala.ciudad.oaxaca': 'Oaxaca de Juárez',
    'sala.ruta.japon': 'Japonya: Tokyo’dan Hiroshima’ya',
    'sala.ruta.corea': 'Sıradaki: Kore',
    'fin.propinas': 'Bahşiş',
    'bib.ramaDesc': 'Öğretmenle sohbet ederken çıktı; sonra dönmek için bir kenara not ettim.',
    'casa.zona.casa': 'Ev',
    'casa.zona.canchas': 'Sahalar',
    'casa.zona.santuario': 'Sığınak',
    'casa.zona.pista': 'Yarış pisti',
    'casa.zona.mindfulness': 'Farkındalık',
    'casa.zona.feria': 'Tren ve lunapark',
    'casa.laika.historia': '{nombre}’in kedisi. Tam da sahibinin koşmaya başladığı ay eve geldi.',
    'casa.laika.personalidad': 'Meraklı ve uykucu; her konuda fikrini kedilere özgü bir sakinlikle söyler.',
    'casa.laika.saludo': 'Miyav. Bugün koşuya çıktın mı?',
    'casa.laika.nombre': 'Laika',
    'casa.coche': 'Eski araba',
    'casa.letrero': '{nombre}’İN EVİ',
    'casa.feria': 'LUNAPARK',
    'casa.alberca': 'Havuz',
    'ag.prox.turnoExtra': 'Kafede ek vardiya',
    'ag.prox.cafeFamilia': 'Aileyle kahve',
    'ag.prox.rodilla': 'Diz kontrolü',
    'ag.prox.proyecto': 'Dönem projesi teslimi',
  },
  id: {
    'cal.turno': 'Shift di kafe',
    'cal.clases': 'Kuliah fisika',
    'cal.estudiar': 'Belajar fisika',
    'cal.pantallas': 'Matikan semua lalu tidur',
    'cal.piano': 'Piano 20 menit',
    'cal.idioma': 'Mengulang materi bahasa',
    'cal.meditar': 'Meditasi sebelum berangkat',
    'cal.correr': 'Pergi lari',
    'cal.notaTurno': 'Aku tukar shift dengan Nuria.',
    'ag.raza': 'Kucing kampung',
    'ag.vacuna': 'Vaksin tahunan',
    'ag.desparasitacion': 'Obat cacing',
    'ag.bano': 'Mandi dan sisir bulu',
    'ag.vitaminaD': 'Vitamin D',
    'ag.dosisVitaminaD': '1000 IU',
    'ag.antiinflamatorio': 'Obat antiradang',
    'ag.notaRodilla': 'Untuk lututku, selama masih cedera.',
    'ag.enalapril': 'Enalapril',
    'ag.notaTension': 'Untuk tekanan darah. Jangan sampai ada yang terlewat.',
    'ag.chequeo': 'Pemeriksaan umum',
    'ag.dental': 'Pembersihan gigi',
    'ag.vista': 'Pemeriksaan mata',
    'ag.tension': 'Cek tekanan darah',
    'ag.analisis': 'Tes darah',
    'ag.cardiologo': 'Kontrol ke dokter jantung',
    'ag.drFerran': 'dr. Ferrán',
    'ag.labSur': 'Lab Klinik Selatan',
    'sala.lugar.tokio': 'Tokyo',
    'sala.lugar.hakone': 'Hakone',
    'sala.lugar.kawaguchiko': 'Danau Kawaguchi',
    'sala.lugar.kioto': 'Kyoto',
    'sala.lugar.nara': 'Nara',
    'sala.lugar.osaka': 'Osaka',
    'sala.lugar.hiroshima': 'Hiroshima',
    'sala.lugar.oaxaca': 'Oaxaca',
    'sala.lugar.valle': 'Valle de Bravo',
    'sala.lugar.seul': 'Seoul',
    'sala.lugar.patagonia': 'Patagonia',
    'sala.lugar.islandia': 'Reykjavík',
    'sala.ciudad.oaxaca': 'Oaxaca de Juárez',
    'sala.ruta.japon': 'Jepang: dari Tokyo ke Hiroshima',
    'sala.ruta.corea': 'Berikutnya: Korea',
    'fin.propinas': 'Tip',
    'bib.ramaDesc': 'Muncul saat ngobrol dengan tutor; kucatat supaya nanti bisa kembali ke topik ini.',
    'casa.zona.casa': 'Rumah',
    'casa.zona.canchas': 'Lapangan',
    'casa.zona.santuario': 'Suaka',
    'casa.zona.pista': 'Lintasan balap',
    'casa.zona.mindfulness': 'Mindfulness',
    'casa.zona.feria': 'Kereta dan karnaval',
    'casa.laika.historia': 'Kucing milik {nombre}. Datang ke rumah pada bulan yang sama saat pemiliknya mulai rutin lari.',
    'casa.laika.personalidad': 'Selalu penasaran dan tukang tidur; punya pendapat soal apa saja, dengan ketenangan khas kucing.',
    'casa.laika.saludo': 'Meong. Hari ini kamu sudah lari belum?',
    'casa.laika.nombre': 'Laika',
    'casa.coche': 'Mobil tua',
    'casa.letrero': 'RUMAH {nombre}',
    'casa.feria': 'KARNAVAL',
    'casa.alberca': 'Kolam renang',
    'ag.prox.turnoExtra': 'Shift tambahan di kedai kopi',
    'ag.prox.cafeFamilia': 'Ngopi bareng keluarga',
    'ag.prox.rodilla': 'Kontrol lutut',
    'ag.prox.proyecto': 'Pengumpulan proyek semester',
  },
  pl: {
    'cal.turno': 'Zmiana w kawiarni',
    'cal.clases': 'Zajęcia z fizyki',
    'cal.estudiar': 'Uczyć się fizyki',
    'cal.pantallas': 'Wyłączyć wszystko i spać',
    'cal.piano': 'Pianino 20 minut',
    'cal.idioma': 'Powtórka z języka',
    'cal.meditar': 'Medytować przed wyjściem',
    'cal.correr': 'Wyjść pobiegać',
    'cal.notaTurno': 'Zamiana zmian z Nurią.',
    'ag.raza': 'Dachowiec',
    'ag.vacuna': 'Coroczne szczepienie',
    'ag.desparasitacion': 'Odrobaczanie',
    'ag.bano': 'Kąpiel i czesanie',
    'ag.vitaminaD': 'Witamina D',
    'ag.dosisVitaminaD': '1000 j.m.',
    'ag.antiinflamatorio': 'Lek przeciwzapalny',
    'ag.notaRodilla': 'Na kolano, dopóki trwała kontuzja.',
    'ag.enalapril': 'Enalapryl',
    'ag.notaTension': 'Na ciśnienie. Nie pomijać ani jednej dawki.',
    'ag.chequeo': 'Ogólne badanie kontrolne',
    'ag.dental': 'Higienizacja zębów',
    'ag.vista': 'Kontrola wzroku',
    'ag.tension': 'Kontrola ciśnienia',
    'ag.analisis': 'Badania krwi',
    'ag.cardiologo': 'Wizyta kontrolna u kardiologa',
    'ag.drFerran': 'dr Ferrán',
    'ag.labSur': 'Laboratorium Południowe',
    'sala.lugar.tokio': 'Tokio',
    'sala.lugar.hakone': 'Hakone',
    'sala.lugar.kawaguchiko': 'Jezioro Kawaguchi',
    'sala.lugar.kioto': 'Kioto',
    'sala.lugar.nara': 'Nara',
    'sala.lugar.osaka': 'Osaka',
    'sala.lugar.hiroshima': 'Hiroszima',
    'sala.lugar.oaxaca': 'Oaxaca',
    'sala.lugar.valle': 'Valle de Bravo',
    'sala.lugar.seul': 'Seul',
    'sala.lugar.patagonia': 'Patagonia',
    'sala.lugar.islandia': 'Reykjavík',
    'sala.ciudad.oaxaca': 'Oaxaca de Juárez',
    'sala.ruta.japon': 'Japonia: z Tokio do Hiroszimy',
    'sala.ruta.corea': 'Następny przystanek: Korea',
    'fin.propinas': 'Napiwki',
    'bib.ramaDesc': 'Wyszło w rozmowie z tutorem; zanotowane, żeby do tego wrócić.',
    'casa.zona.casa': 'Dom',
    'casa.zona.canchas': 'Boiska',
    'casa.zona.santuario': 'Sanktuarium',
    'casa.zona.pista': 'Tor wyścigowy',
    'casa.zona.mindfulness': 'Uważność',
    'casa.zona.feria': 'Pociąg i lunapark',
    'casa.laika.historia': 'Kotka, z którą mieszka {nombre}. Trafiła do domu w tym samym miesiącu, w którym zaczęła się przygoda z bieganiem.',
    'casa.laika.personalidad': 'Ciekawska i wiecznie zaspana; ma zdanie o wszystkim i wygłasza je z kocim spokojem.',
    'casa.laika.saludo': 'Miau. Było już dziś bieganie?',
    'casa.laika.nombre': 'Laika',
    'casa.coche': 'Stary samochód',
    'casa.letrero': 'TU MIESZKA {nombre}',
    'casa.feria': 'LUNAPARK',
    'casa.alberca': 'Basen',
    'ag.prox.turnoExtra': 'Dodatkowa zmiana w kawiarni',
    'ag.prox.cafeFamilia': 'Kawa z rodziną',
    'ag.prox.rodilla': 'Kontrola kolana',
    'ag.prox.proyecto': 'Oddanie projektu semestralnego',
  },
  nl: {
    'cal.turno': 'Dienst in het café',
    'cal.clases': 'Colleges natuurkunde',
    'cal.estudiar': 'Natuurkunde studeren',
    'cal.pantallas': 'Alles uit en slapen',
    'cal.piano': 'Piano, 20 minuten',
    'cal.idioma': 'Taal herhalen',
    'cal.meditar': 'Mediteren voor het weggaan',
    'cal.correr': 'Rondje hardlopen',
    'cal.notaTurno': 'Dienst geruild met Nuria.',
    'ag.raza': 'Europese korthaar',
    'ag.vacuna': 'Jaarlijkse prik',
    'ag.desparasitacion': 'Ontworming',
    'ag.bano': 'Wassen en borstelen',
    'ag.vitaminaD': 'Vitamine D',
    'ag.dosisVitaminaD': '1000 IE',
    'ag.antiinflamatorio': 'Ontstekingsremmer',
    'ag.notaRodilla': 'Voor mijn knie, zolang de blessure duurde.',
    'ag.enalapril': 'Enalapril',
    'ag.notaTension': 'Voor de bloeddruk. Geen enkele dosis overslaan.',
    'ag.chequeo': 'Algemene controle',
    'ag.dental': 'Gebitsreiniging',
    'ag.vista': 'Oogcontrole',
    'ag.tension': 'Bloeddrukcontrole',
    'ag.analisis': 'Bloedonderzoek',
    'ag.cardiologo': 'Controle bij de cardioloog',
    'ag.drFerran': 'Dr. Ferrán',
    'ag.labSur': 'Laboratorium Zuid',
    'sala.lugar.tokio': 'Tokio',
    'sala.lugar.hakone': 'Hakone',
    'sala.lugar.kawaguchiko': 'Kawaguchimeer',
    'sala.lugar.kioto': 'Kyoto',
    'sala.lugar.nara': 'Nara',
    'sala.lugar.osaka': 'Osaka',
    'sala.lugar.hiroshima': 'Hiroshima',
    'sala.lugar.oaxaca': 'Oaxaca',
    'sala.lugar.valle': 'Valle de Bravo',
    'sala.lugar.seul': 'Seoel',
    'sala.lugar.patagonia': 'Patagonië',
    'sala.lugar.islandia': 'Reykjavik',
    'sala.ciudad.oaxaca': 'Oaxaca de Juárez',
    'sala.ruta.japon': 'Japan: van Tokio naar Hiroshima',
    'sala.ruta.corea': 'Volgende bestemming: Korea',
    'fin.propinas': 'Fooien',
    'bib.ramaDesc': 'Kwam ter sprake in een gesprek met de tutor; ik heb het genoteerd om erop terug te komen.',
    'casa.zona.casa': 'Het huis',
    'casa.zona.canchas': 'Velden',
    'casa.zona.santuario': 'Opvang',
    'casa.zona.pista': 'Racebaan',
    'casa.zona.mindfulness': 'Mindfulness',
    'casa.zona.feria': 'Trein en kermis',
    'casa.laika.historia': 'De kat van {nombre}. In dezelfde maand waarin het hardlopen begon, kwam ze in huis.',
    'casa.laika.personalidad': 'Nieuwsgierig en een slaapkop; heeft overal een mening over, met katachtige kalmte.',
    'casa.laika.saludo': 'Miauw. Ben je vandaag al gaan hardlopen?',
    'casa.laika.nombre': 'Laika',
    'casa.coche': 'Oude auto',
    'casa.letrero': 'HUIS VAN {nombre}',
    'casa.feria': 'KERMIS',
    'casa.alberca': 'Zwembad',
    'ag.prox.turnoExtra': 'Extra dienst in het café',
    'ag.prox.cafeFamilia': 'Koffie met de familie',
    'ag.prox.rodilla': 'Controle van de knie',
    'ag.prox.proyecto': 'Inleveren semesterproject',
  },
  ar: {
    'cal.turno': 'مناوبة في المقهى',
    'cal.clases': 'محاضرات الفيزياء',
    'cal.estudiar': 'مذاكرة الفيزياء',
    'cal.pantallas': 'إطفاء كل شيء والنوم',
    'cal.piano': 'عزف البيانو 20 دقيقة',
    'cal.idioma': 'مراجعة اللغة',
    'cal.meditar': 'التأمل قبل الخروج',
    'cal.correr': 'الخروج للركض',
    'cal.notaTurno': 'بدّلتُ المناوبة مع نوريا.',
    'ag.raza': 'محلية',
    'ag.vacuna': 'اللقاح السنوي',
    'ag.desparasitacion': 'إزالة الطفيليات',
    'ag.bano': 'الاستحمام والتمشيط',
    'ag.vitaminaD': 'فيتامين د',
    'ag.dosisVitaminaD': '1000 وحدة دولية',
    'ag.antiinflamatorio': 'مضاد للالتهاب',
    'ag.notaRodilla': 'للركبة، طوال فترة الإصابة.',
    'ag.enalapril': 'إنالابريل',
    'ag.notaTension': 'لضغط الدم. ممنوع تفويت أي جرعة.',
    'ag.chequeo': 'الفحص العام',
    'ag.dental': 'تنظيف الأسنان',
    'ag.vista': 'فحص النظر',
    'ag.tension': 'فحص ضغط الدم',
    'ag.analisis': 'تحاليل الدم',
    'ag.cardiologo': 'مراجعة طبيب القلب',
    'ag.drFerran': 'الدكتورة فيران',
    'ag.labSur': 'مختبرات الجنوب',
    'sala.lugar.tokio': 'طوكيو',
    'sala.lugar.hakone': 'هاكوني',
    'sala.lugar.kawaguchiko': 'بحيرة كاواغوتشي',
    'sala.lugar.kioto': 'كيوتو',
    'sala.lugar.nara': 'نارا',
    'sala.lugar.osaka': 'أوساكا',
    'sala.lugar.hiroshima': 'هيروشيما',
    'sala.lugar.oaxaca': 'واهاكا',
    'sala.lugar.valle': 'فالي دي برافو',
    'sala.lugar.seul': 'سول',
    'sala.lugar.patagonia': 'باتاغونيا',
    'sala.lugar.islandia': 'ريكيافيك',
    'sala.ciudad.oaxaca': 'واهاكا دي خواريز',
    'sala.ruta.japon': 'اليابان: من طوكيو إلى هيروشيما',
    'sala.ruta.corea': 'الوجهة التالية: كوريا',
    'fin.propinas': 'الإكراميات',
    'bib.ramaDesc': 'ظهر أثناء الحديث مع المعلّم؛ دوّنتُه لأعود إليه.',
    'casa.zona.casa': 'البيت',
    'casa.zona.canchas': 'الملاعب',
    'casa.zona.santuario': 'المحمية',
    'casa.zona.pista': 'حلبة السباق',
    'casa.zona.mindfulness': 'اليقظة الذهنية',
    'casa.zona.feria': 'القطار والملاهي',
    'casa.laika.historia': 'قطة {nombre}. وصلت إلى البيت في الشهر نفسه الذي بدأت فيه رحلة الركض.',
    'casa.laika.personalidad': 'فضولية وكثيرة النوم؛ تُدلي برأيها في كل شيء بهدوء القطط.',
    'casa.laika.saludo': 'مياو. هل خرجت للركض اليوم؟',
    'casa.laika.nombre': 'لايكا',
    'casa.coche': 'سيارة قديمة',
    'casa.letrero': 'بيت {nombre}',
    'casa.feria': 'الملاهي',
    'casa.alberca': 'المسبح',
    'ag.prox.turnoExtra': 'وردية إضافية في المقهى',
    'ag.prox.cafeFamilia': 'قهوة مع العائلة',
    'ag.prox.rodilla': 'فحص الركبة',
    'ag.prox.proyecto': 'تسليم مشروع الفصل الدراسي',
  },
}

/** Un texto de la demo en el idioma dado, con sus `{marcadores}` rellenos. */
export function textoDemo(idioma: Idioma, clave: ClaveDemo, vars?: Record<string, string>): string {
  const texto = enIdioma(TEXTOS, idioma)[clave]
  return vars ? texto.replace(/\{(\w+)\}/g, (m, k: string) => vars[k] ?? m) : texto
}

/** El mismo texto como catálogo `PorIdioma` (para quien ya elige con `enIdioma`). */
export function porIdiomaDemo(clave: ClaveDemo): PorIdioma<string> {
  return Object.fromEntries(Object.entries(TEXTOS).map(([id, rama]) => [id, rama[clave]])) as PorIdioma<string>
}
