// Generado por `npm run ejemplos:texto` — no lo edites a mano.
// Contenido del ejemplo de fábrica de hobbies, en los dos idiomas. Vive aparte
// de `dict.ts` a propósito: en cuanto se crea es dato del usuario, no interfaz.

export const TEXTOS_HOBBIES = {
  es: {
    hobby: 'Acuarela',
    proyecto: 'Lámina de las macetas del balcón',
    notaProyecto: 'Se la quiero regalar a mi hermana cuando estrene piso. Falta el geranio del centro y decidir si dejo el fondo en blanco.',
    sesionCorta: '20 min de aguadas antes de cenar',
    sesionLarga: 'Hora de húmedo sobre húmedo y grises',
    sesionHoy: 'Repaso: las hojas del boceto viejo',
  },
  en: {
    hobby: 'Watercolour',
    proyecto: 'Balcony flowerpots painting',
    notaProyecto: 'It\'s a housewarming gift for my sister. Still missing the geranium in the middle, and I can\'t decide if the background stays white.',
    sesionCorta: '20 min of washes before dinner',
    sesionLarga: 'Long hour: wet-on-wet and mixing greys',
    sesionHoy: 'Redid the leaves from the old sketch',
  },
  pt: {
    hobby: 'Aquarela',
    proyecto: 'Quadro dos vasos da varanda',
    notaProyecto: 'Quero dar de presente para minha irmã quando ela se mudar. Falta o gerânio do centro e decidir se deixo o fundo em branco.',
    sesionCorta: '20 min de lavagens antes do jantar',
    sesionLarga: 'Uma hora de úmido sobre úmido e misturando cinzas',
    sesionHoy: 'Retoque: as folhas do esboço antigo',
  },
  fr: {
    hobby: 'Aquarelle',
    proyecto: 'Tableau des pots de fleurs du balcon',
    notaProyecto: 'C\'est un cadeau de crémaillère pour ma sœur. Il manque encore le géranium au centre, et je n\'arrive pas à décider si je laisse le fond blanc.',
    sesionCorta: '20 min de lavis avant le dîner',
    sesionLarga: 'Une heure de mouillé sur mouillé et de mélanges de gris',
    sesionHoy: 'Reprise: les feuilles du vieux croquis',
  },
  de: {
    hobby: 'Aquarell',
    proyecto: 'Bild der Blumentöpfe auf dem Balkon',
    notaProyecto: 'Ich möchte es meiner Schwester zum Einzug schenken. Die Geranie in der Mitte fehlt noch, und ich weiß nicht, ob der Hintergrund weiß bleiben soll.',
    sesionCorta: '20 Min. Lavuren vor dem Abendessen',
    sesionLarga: 'Eine Stunde Nass-in-Nass und Grautöne mischen',
    sesionHoy: 'Wiederholt: die Blätter aus der alten Skizze',
  },
  it: {
    hobby: 'Acquerello',
    proyecto: 'Quadro dei vasi del balcone',
    notaProyecto: 'Voglio regalarlo a mia sorella quando cambia casa. Manca il geranio al centro e devo decidere se lasciare lo sfondo bianco.',
    sesionCorta: '20 min di velature prima di cena',
    sesionLarga: 'Un\'ora di bagnato su bagnato e grigi da mescolare',
    sesionHoy: 'Ripasso: le foglie dello schizzo vecchio',
  },
  ja: {
    hobby: '水彩画',
    proyecto: 'バルコニーの鉢植えの絵',
    notaProyecto: '妹が新居に引っ越すときにプレゼントしたいと思っています。真ん中のゼラニウムがまだで、背景を白のままにするか迷っています。',
    sesionCorta: '夕食前に20分、にじみ技法の練習',
    sesionLarga: '1時間かけてウェット・オン・ウェットとグレーの混色',
    sesionHoy: '復習:古いスケッチの葉っぱ',
  },
  zh: {
    hobby: '水彩画',
    proyecto: '阳台花盆的画',
    notaProyecto: '想在妹妹搬新家的时候送给她。中间的天竺葵还没画,背景留不留白也还没想好。',
    sesionCorta: '晚饭前20分钟练习湿画法',
    sesionLarga: '一小时湿画叠加和调灰色',
    sesionHoy: '复习:旧草稿里的叶子',
  },
  ko: {
    hobby: '수채화',
    proyecto: '발코니 화분 그림',
    notaProyecto: '여동생이 새집으로 이사할 때 선물하고 싶어요. 가운데 제라늄이 아직이고, 배경을 흰색으로 둘지 고민 중이에요.',
    sesionCorta: '저녁 먹기 전 20분, 워시 기법 연습',
    sesionLarga: '한 시간 동안 웨트온웨트와 회색 혼색',
    sesionHoy: '복습: 옛날 스케치의 잎사귀',
  },
  ru: {
    hobby: 'Акварель',
    proyecto: 'Картина с горшками с балкона',
    notaProyecto: 'Подарок сестре на новоселье. Не хватает герани в центре, и ещё не решено, оставлять ли фон белым.',
    sesionCorta: '20 минут отмывок перед ужином',
    sesionLarga: 'Час техники мокрым по мокрому и смешивания серых',
    sesionHoy: 'Повтор: листья со старого эскиза',
  },
  hi: {
    hobby: 'वॉटरकलर',
    proyecto: 'बालकनी के गमलों की तस्वीर',
    notaProyecto: 'बहन के नए घर में जाने पर उसे तोहफ़े में देने का इरादा है। बीच वाला जेरेनियम अभी बाक़ी है और तय करना है कि बैकग्राउंड सफ़ेद ही रहने दें या नहीं।',
    sesionCorta: 'खाने से पहले 20 मिनट वॉश तकनीक का अभ्यास',
    sesionLarga: 'गीले पर गीला और स्लेटी रंग मिलाने में एक घंटा',
    sesionHoy: 'दोहराव: पुराने स्केच की पत्तियाँ',
  },
  tr: {
    hobby: 'Suluboya',
    proyecto: 'Balkondaki saksılar tablosu',
    notaProyecto: 'Kız kardeşim yeni evine taşınınca hediye etmek istiyorum. Ortadaki sardunya eksik ve arka planı beyaz bırakıp bırakmayacağıma karar vermem gerekiyor.',
    sesionCorta: 'Akşam yemeğinden önce 20 dk yıkama tekniği',
    sesionLarga: 'Islak üstüne ıslak ve gri tonları karıştırmaya bir saat',
    sesionHoy: 'Tekrar: eski taslaktaki yapraklar',
  },
  id: {
    hobby: 'Cat air',
    proyecto: 'Lukisan pot bunga di balkon',
    notaProyecto: 'Mau dikasih ke kakak perempuan waktu dia pindah ke rumah baru. Masih kurang bunga geranium di tengah, dan belum diputuskan apa latar belakangnya dibiarkan putih.',
    sesionCorta: '20 menit teknik wash sebelum makan malam',
    sesionLarga: 'Satu jam teknik basah di atas basah dan mencampur abu-abu',
    sesionHoy: 'Ulang: daun-daun dari sketsa lama',
  },
  pl: {
    hobby: 'Akwarela',
    proyecto: 'Obrazek doniczek z balkonu',
    notaProyecto: 'Prezent dla siostry na nowe mieszkanie. Brakuje jeszcze pelargonii na środku i decyzji, czy tło zostaje białe.',
    sesionCorta: '20 min laserunków przed kolacją',
    sesionLarga: 'Godzina mokrego na mokrym i mieszania szarości',
    sesionHoy: 'Powtórka: liście ze starego szkicu',
  },
  ar: {
    hobby: 'الألوان المائية',
    proyecto: 'لوحة أصص الشرفة',
    notaProyecto: 'أريد إهداءها لأختي عند انتقالها إلى شقتها الجديدة. ينقصها نبات الجيرانيوم في المنتصف، ولم أقرر بعد إن كنت سأترك الخلفية بيضاء.',
    sesionCorta: '20 دقيقة من تقنية الغسل قبل العشاء',
    sesionLarga: 'ساعة من الرطب على الرطب ومزج الرمادي',
    sesionHoy: 'مراجعة: أوراق الرسم التخطيطي القديم',
  },
  nl: {
    hobby: 'Aquarel',
    proyecto: 'Schilderij van de bloempotten op het balkon',
    notaProyecto: 'Wil het aan mijn zus geven als ze haar nieuwe huis heeft. De geranium in het midden ontbreekt nog en ik moet nog beslissen of de achtergrond wit blijft.',
    sesionCorta: '20 min wassen voor het avondeten',
    sesionLarga: 'Een uur nat-in-nat en grijstinten mengen',
    sesionHoy: 'Herhaling: de bladeren van de oude schets',
  },
}
