/**
 * El formulario de fábrica en inglés.
 *
 * No se duplican las 54 estructuras: la notación (`tex`, `expresion`, los
 * símbolos) es universal y solo cambian los NOMBRES. Aquí viven esos nombres y
 * `catalogo.ts` arma el catálogo inglés aplicándolos. Los de variable van en un
 * diccionario global porque se repiten mucho («masa» sale en once fórmulas).
 *
 * Lo que no esté traducido se queda en español antes que desaparecer.
 */
import type { AreaFabrica } from './constantes'

export const AREAS_EN: Record<AreaFabrica, string> = {
  matematicas: 'Mathematics',
  fisica: 'Physics',
  quimica: 'Chemistry',
}

export const GRUPOS_EN: Record<string, string> = {
  'Geometría': 'Geometry',
  'Álgebra': 'Algebra',
  'Sucesiones': 'Sequences',
  'Trigonometría': 'Trigonometry',
  'Finanzas': 'Finance',
  'Cinemática': 'Kinematics',
  'Dinámica': 'Dynamics',
  'Energía': 'Energy',
  'Ondas': 'Waves',
  'Electricidad': 'Electricity',
  'Gases': 'Gases',
  'Disoluciones': 'Solutions',
  'Estequiometría': 'Stoichiometry',
  'Termoquímica': 'Thermochemistry',
}

/** Nombre de cada fórmula, por slug. */
export const FORMULAS_EN: Record<string, string> = {
  // Matemáticas
  'area-circulo': 'Area of a circle',
  circunferencia: 'Circumference',
  'area-triangulo': 'Area of a triangle',
  'area-trapecio': 'Area of a trapezoid',
  'volumen-cilindro': 'Volume of a cylinder',
  'volumen-esfera': 'Volume of a sphere',
  'volumen-cono': 'Volume of a cone',
  pitagoras: 'Pythagorean theorem',
  'formula-general': 'Quadratic formula (positive root)',
  discriminante: 'Discriminant',
  pendiente: 'Slope of a line',
  'distancia-puntos': 'Distance between two points',
  'cambio-base': 'Change of logarithm base',
  'termino-aritmetica': 'Nth term of an arithmetic sequence',
  'suma-geometrica': 'Sum of a geometric sequence',
  'ley-senos': 'Law of sines',
  'ley-cosenos': 'Law of cosines',
  'interes-compuesto': 'Compound interest',
  // Física
  'velocidad-media': 'Average velocity',
  'mrua-velocidad': 'Velocity under constant acceleration',
  'mrua-posicion': 'Position under constant acceleration',
  torricelli: "Torricelli's equation",
  'alcance-tiro': 'Projectile range',
  'segunda-ley': "Newton's second law",
  peso: 'Weight',
  friccion: 'Friction force',
  hooke: "Hooke's law",
  'energia-cinetica': 'Kinetic energy',
  'energia-potencial': 'Gravitational potential energy',
  trabajo: 'Work',
  potencia: 'Power',
  'periodo-pendulo': 'Period of a simple pendulum',
  'velocidad-onda': 'Wave speed',
  presion: 'Pressure',
  'ley-ohm': "Ohm's law",
  'potencia-electrica': 'Electrical power',
  // Química
  'gas-ideal': 'Ideal gas law (pressure)',
  boyle: "Boyle's law",
  charles: "Charles's law",
  'gay-lussac': "Gay-Lussac's law",
  molaridad: 'Molarity',
  molalidad: 'Molality',
  dilucion: 'Dilution',
  'porcentaje-masa': 'Mass percent',
  ph: 'pH',
  poh: 'pOH from pH',
  moles: 'Moles from mass',
  'masa-de-moles': 'Mass from moles',
  'numero-particulas': 'Number of particles',
  rendimiento: 'Reaction yield',
  'calor-sensible': 'Sensible heat',
  'calor-latente': 'Latent heat',
  densidad: 'Density',
  'entalpia-reaccion': 'Enthalpy of reaction',
}

/** Nombres de variable, por su texto en español. */
export const VARIABLES_EN: Record<string, string> = {
  radio: 'radius',
  base: 'base',
  altura: 'height',
  'base mayor': 'longer base',
  'base menor': 'shorter base',
  cateto: 'leg',
  'coeficiente cuadrático': 'quadratic coefficient',
  'coeficiente lineal': 'linear coefficient',
  'término independiente': 'constant term',
  'x del primer punto': 'x of the first point',
  'y del primer punto': 'y of the first point',
  'x del segundo punto': 'x of the second point',
  'y del segundo punto': 'y of the second point',
  argumento: 'argument',
  'primer término': 'first term',
  posición: 'position',
  diferencia: 'common difference',
  razón: 'common ratio',
  'número de términos': 'number of terms',
  'lado conocido': 'known side',
  lado: 'side',
  'ángulo opuesto a a': 'angle opposite a',
  'ángulo opuesto a b': 'angle opposite b',
  'ángulo entre a y b': 'angle between a and b',
  'capital inicial': 'principal',
  'tasa anual (0.08 = 8 %)': 'annual rate (0.08 = 8%)',
  'capitalizaciones al año': 'compounds per year',
  'años': 'years',
  distancia: 'distance',
  tiempo: 'time',
  'velocidad inicial': 'initial velocity',
  aceleración: 'acceleration',
  'posición inicial': 'initial position',
  desplazamiento: 'displacement',
  'ángulo de lanzamiento': 'launch angle',
  gravedad: 'gravity',
  masa: 'mass',
  'coeficiente de fricción': 'friction coefficient',
  'fuerza normal': 'normal force',
  'constante del resorte': 'spring constant',
  deformación: 'displacement',
  velocidad: 'velocity',
  fuerza: 'force',
  'ángulo entre F y d': 'angle between F and d',
  trabajo: 'work',
  longitud: 'length',
  'longitud de onda': 'wavelength',
  frecuencia: 'frequency',
  'área': 'area',
  corriente: 'current',
  resistencia: 'resistance',
  voltaje: 'voltage',
  moles: 'moles',
  'constante de los gases': 'gas constant',
  temperatura: 'temperature',
  volumen: 'volume',
  'presión inicial': 'initial pressure',
  'volumen inicial': 'initial volume',
  'volumen final': 'final volume',
  'temperatura inicial': 'initial temperature',
  'temperatura final': 'final temperature',
  'moles de soluto': 'moles of solute',
  'volumen de disolución': 'solution volume',
  'masa de disolvente': 'solvent mass',
  'concentración inicial': 'initial concentration',
  'masa de soluto': 'solute mass',
  'masa total': 'total mass',
  'concentración de H⁺': 'H⁺ concentration',
  'pH de la disolución': 'pH of the solution',
  'masa molar': 'molar mass',
  'número de Avogadro': "Avogadro's number",
  'producto obtenido': 'actual yield',
  'producto teórico': 'theoretical yield',
  'calor específico': 'specific heat',
  'cambio de temperatura': 'temperature change',
  'calor latente': 'latent heat',
  'entalpía de los productos': 'enthalpy of products',
  'entalpía de los reactivos': 'enthalpy of reactants',
}

/** Unidades escritas con palabras (las de símbolo son universales). */
export const UNIDADES_EN: Record<string, string> = { 'años': 'years' }
