/**
 * El formulario de fábrica en indonesio.
 *
 * No se duplican las 54 estructuras: la notación (`tex`, `expresion`, los
 * símbolos) es universal y solo cambian los NOMBRES. Aquí viven esos nombres y
 * `catalogo.ts` arma el catálogo traducido aplicándolos. Los de variable van en
 * un diccionario global porque se repiten mucho («masa» sale en once fórmulas).
 *
 * Lo que no esté traducido se queda en español antes que desaparecer.
 */
import type { AreaFabrica } from './constantes'

export const AREAS_ID: Record<AreaFabrica, string> = {
  matematicas: 'Matematika',
  fisica: 'Fisika',
  quimica: 'Kimia',
}

export const GRUPOS_ID: Record<string, string> = {
  'Geometría': 'Geometri',
  'Álgebra': 'Aljabar',
  'Sucesiones': 'Barisan',
  'Trigonometría': 'Trigonometri',
  'Finanzas': 'Keuangan',
  'Cinemática': 'Kinematika',
  'Dinámica': 'Dinamika',
  'Energía': 'Energi',
  'Ondas': 'Gelombang',
  'Electricidad': 'Listrik',
  'Gases': 'Gas',
  'Disoluciones': 'Larutan',
  'Estequiometría': 'Stoikiometri',
  'Termoquímica': 'Termokimia',
}

/** Nombre de cada fórmula, por slug. */
export const FORMULAS_ID: Record<string, string> = {
  // Matemáticas
  'area-circulo': 'Luas lingkaran',
  circunferencia: 'Keliling lingkaran',
  'area-triangulo': 'Luas segitiga',
  'area-trapecio': 'Luas trapesium',
  'volumen-cilindro': 'Volume tabung',
  'volumen-esfera': 'Volume bola',
  'volumen-cono': 'Volume kerucut',
  pitagoras: 'Teorema Pythagoras',
  'formula-general': 'Rumus ABC (akar positif)',
  discriminante: 'Diskriminan',
  pendiente: 'Gradien garis',
  'distancia-puntos': 'Jarak antara dua titik',
  'cambio-base': 'Perubahan basis logaritma',
  'termino-aritmetica': 'Suku ke-n barisan aritmetika',
  'suma-geometrica': 'Jumlah deret geometri',
  'ley-senos': 'Aturan sinus',
  'ley-cosenos': 'Aturan kosinus',
  'interes-compuesto': 'Bunga majemuk',
  // Física
  'velocidad-media': 'Kecepatan rata-rata',
  'mrua-velocidad': 'Kecepatan dengan percepatan tetap',
  'mrua-posicion': 'Posisi dengan percepatan tetap',
  torricelli: 'Persamaan Torricelli',
  'alcance-tiro': 'Jangkauan gerak parabola',
  'segunda-ley': 'Hukum II Newton',
  peso: 'Berat',
  friccion: 'Gaya gesek',
  hooke: 'Hukum Hooke',
  'energia-cinetica': 'Energi kinetik',
  'energia-potencial': 'Energi potensial gravitasi',
  trabajo: 'Usaha',
  potencia: 'Daya',
  'periodo-pendulo': 'Periode bandul sederhana',
  'velocidad-onda': 'Cepat rambat gelombang',
  presion: 'Tekanan',
  'ley-ohm': 'Hukum Ohm',
  'potencia-electrica': 'Daya listrik',
  // Química
  'gas-ideal': 'Hukum gas ideal (tekanan)',
  boyle: 'Hukum Boyle',
  charles: 'Hukum Charles',
  'gay-lussac': 'Hukum Gay-Lussac',
  molaridad: 'Molaritas',
  molalidad: 'Molalitas',
  dilucion: 'Pengenceran',
  'porcentaje-masa': 'Persen massa',
  ph: 'pH',
  poh: 'pOH dari pH',
  moles: 'Mol dari massa',
  'masa-de-moles': 'Massa dari mol',
  'numero-particulas': 'Jumlah partikel',
  rendimiento: 'Rendemen reaksi',
  'calor-sensible': 'Kalor sensibel',
  'calor-latente': 'Kalor laten',
  densidad: 'Massa jenis',
  'entalpia-reaccion': 'Entalpi reaksi',
}

/** Nombres de variable, por su texto en español. */
export const VARIABLES_ID: Record<string, string> = {
  radio: 'jari-jari',
  base: 'alas',
  altura: 'tinggi',
  'base mayor': 'alas besar',
  'base menor': 'alas kecil',
  cateto: 'sisi siku-siku',
  'coeficiente cuadrático': 'koefisien kuadrat',
  'coeficiente lineal': 'koefisien linear',
  'término independiente': 'suku konstan',
  'x del primer punto': 'x titik pertama',
  'y del primer punto': 'y titik pertama',
  'x del segundo punto': 'x titik kedua',
  'y del segundo punto': 'y titik kedua',
  argumento: 'argumen',
  'primer término': 'suku pertama',
  posición: 'nomor suku',
  diferencia: 'beda',
  razón: 'rasio',
  'número de términos': 'banyak suku',
  'lado conocido': 'sisi yang diketahui',
  lado: 'sisi',
  'ángulo opuesto a a': 'sudut di hadapan a',
  'ángulo opuesto a b': 'sudut di hadapan b',
  'ángulo entre a y b': 'sudut antara a dan b',
  'capital inicial': 'modal awal',
  'tasa anual (0.08 = 8 %)': 'suku bunga tahunan (0.08 = 8%)',
  'capitalizaciones al año': 'periode majemuk per tahun',
  'años': 'tahun',
  distancia: 'jarak',
  tiempo: 'waktu',
  'velocidad inicial': 'kecepatan awal',
  aceleración: 'percepatan',
  'posición inicial': 'posisi awal',
  desplazamiento: 'perpindahan',
  'ángulo de lanzamiento': 'sudut elevasi',
  gravedad: 'percepatan gravitasi',
  masa: 'massa',
  'coeficiente de fricción': 'koefisien gesek',
  'fuerza normal': 'gaya normal',
  'constante del resorte': 'konstanta pegas',
  deformación: 'pertambahan panjang',
  velocidad: 'kecepatan',
  fuerza: 'gaya',
  'ángulo entre F y d': 'sudut antara F dan d',
  trabajo: 'usaha',
  longitud: 'panjang',
  'longitud de onda': 'panjang gelombang',
  frecuencia: 'frekuensi',
  'área': 'luas',
  corriente: 'arus',
  resistencia: 'hambatan',
  voltaje: 'tegangan',
  moles: 'mol',
  'constante de los gases': 'konstanta gas',
  temperatura: 'suhu',
  volumen: 'volume',
  'presión inicial': 'tekanan awal',
  'volumen inicial': 'volume awal',
  'volumen final': 'volume akhir',
  'temperatura inicial': 'suhu awal',
  'temperatura final': 'suhu akhir',
  'moles de soluto': 'mol zat terlarut',
  'volumen de disolución': 'volume larutan',
  'masa de disolvente': 'massa pelarut',
  'concentración inicial': 'konsentrasi awal',
  'masa de soluto': 'massa zat terlarut',
  'masa total': 'massa total',
  'concentración de H⁺': 'konsentrasi H⁺',
  'pH de la disolución': 'pH larutan',
  'masa molar': 'massa molar',
  'número de Avogadro': 'bilangan Avogadro',
  'producto obtenido': 'hasil praktik',
  'producto teórico': 'hasil teoritis',
  'calor específico': 'kalor jenis',
  'cambio de temperatura': 'perubahan suhu',
  'calor latente': 'kalor laten',
  'entalpía de los productos': 'entalpi produk',
  'entalpía de los reactivos': 'entalpi reaktan',
}

/** Unidades escritas con palabras (las de símbolo son universales). */
export const UNIDADES_ID: Record<string, string> = { 'años': 'tahun' }
