/**
 * El formulario de fábrica en ruso.
 *
 * No se duplican las 54 estructuras: la notación (`tex`, `expresion`, los
 * símbolos) es universal y solo cambian los NOMBRES. Aquí viven esos nombres y
 * `catalogo.ts` arma el catálogo traducido aplicándolos. Los de variable van en
 * un diccionario global porque se repiten mucho («masa» sale en once fórmulas).
 *
 * Lo que no esté traducido se queda en español antes que desaparecer.
 */
import type { AreaFabrica } from './constantes'

export const AREAS_RU: Record<AreaFabrica, string> = {
  matematicas: 'Математика',
  fisica: 'Физика',
  quimica: 'Химия',
}

export const GRUPOS_RU: Record<string, string> = {
  'Geometría': 'Геометрия',
  'Álgebra': 'Алгебра',
  'Sucesiones': 'Последовательности',
  'Trigonometría': 'Тригонометрия',
  'Finanzas': 'Финансы',
  'Cinemática': 'Кинематика',
  'Dinámica': 'Динамика',
  'Energía': 'Энергия',
  'Ondas': 'Волны',
  'Electricidad': 'Электричество',
  'Gases': 'Газы',
  'Disoluciones': 'Растворы',
  'Estequiometría': 'Стехиометрия',
  'Termoquímica': 'Термохимия',
}

/** Nombre de cada fórmula, por slug. */
export const FORMULAS_RU: Record<string, string> = {
  // Matemáticas
  'area-circulo': 'Площадь круга',
  circunferencia: 'Длина окружности',
  'area-triangulo': 'Площадь треугольника',
  'area-trapecio': 'Площадь трапеции',
  'volumen-cilindro': 'Объём цилиндра',
  'volumen-esfera': 'Объём шара',
  'volumen-cono': 'Объём конуса',
  pitagoras: 'Теорема Пифагора',
  'formula-general': 'Формула корней квадратного уравнения (положительный корень)',
  discriminante: 'Дискриминант',
  pendiente: 'Угловой коэффициент прямой',
  'distancia-puntos': 'Расстояние между двумя точками',
  'cambio-base': 'Смена основания логарифма',
  'termino-aritmetica': 'Общий член арифметической прогрессии',
  'suma-geometrica': 'Сумма геометрической прогрессии',
  'ley-senos': 'Теорема синусов',
  'ley-cosenos': 'Теорема косинусов',
  'interes-compuesto': 'Сложные проценты',
  // Física
  'velocidad-media': 'Средняя скорость',
  'mrua-velocidad': 'Скорость при постоянном ускорении',
  'mrua-posicion': 'Положение при постоянном ускорении',
  torricelli: 'Уравнение Торричелли',
  'alcance-tiro': 'Дальность параболического броска',
  'segunda-ley': 'Второй закон Ньютона',
  peso: 'Вес',
  friccion: 'Сила трения',
  hooke: 'Закон Гука',
  'energia-cinetica': 'Кинетическая энергия',
  'energia-potencial': 'Гравитационная потенциальная энергия',
  trabajo: 'Работа',
  potencia: 'Мощность',
  'periodo-pendulo': 'Период математического маятника',
  'velocidad-onda': 'Скорость волны',
  presion: 'Давление',
  'ley-ohm': 'Закон Ома',
  'potencia-electrica': 'Электрическая мощность',
  // Química
  'gas-ideal': 'Закон идеального газа (давление)',
  boyle: 'Закон Бойля',
  charles: 'Закон Шарля',
  'gay-lussac': 'Закон Гей-Люссака',
  molaridad: 'Молярность',
  molalidad: 'Моляльность',
  dilucion: 'Разбавление',
  'porcentaje-masa': 'Массовая доля',
  ph: 'pH',
  poh: 'pOH из pH',
  moles: 'Количество вещества по массе',
  'masa-de-moles': 'Масса по количеству вещества',
  'numero-particulas': 'Число частиц',
  rendimiento: 'Выход реакции',
  'calor-sensible': 'Явная теплота',
  'calor-latente': 'Скрытая теплота',
  densidad: 'Плотность',
  'entalpia-reaccion': 'Энтальпия реакции',
}

/** Nombres de variable, por su texto en español. */
export const VARIABLES_RU: Record<string, string> = {
  radio: 'радиус',
  base: 'основание',
  altura: 'высота',
  'base mayor': 'большее основание',
  'base menor': 'меньшее основание',
  cateto: 'катет',
  'coeficiente cuadrático': 'квадратичный коэффициент',
  'coeficiente lineal': 'линейный коэффициент',
  'término independiente': 'свободный член',
  'x del primer punto': 'x первой точки',
  'y del primer punto': 'y первой точки',
  'x del segundo punto': 'x второй точки',
  'y del segundo punto': 'y второй точки',
  argumento: 'аргумент',
  'primer término': 'первый член',
  posición: 'позиция',
  diferencia: 'общая разность',
  razón: 'знаменатель прогрессии',
  'número de términos': 'число членов',
  'lado conocido': 'известная сторона',
  lado: 'сторона',
  'ángulo opuesto a a': 'угол, противолежащий a',
  'ángulo opuesto a b': 'угол, противолежащий b',
  'ángulo entre a y b': 'угол между a и b',
  'capital inicial': 'начальный капитал',
  'tasa anual (0.08 = 8 %)': 'годовая ставка (0.08 = 8 %)',
  'capitalizaciones al año': 'количество начислений в год',
  'años': 'лет',
  distancia: 'расстояние',
  tiempo: 'время',
  'velocidad inicial': 'начальная скорость',
  aceleración: 'ускорение',
  'posición inicial': 'начальное положение',
  desplazamiento: 'перемещение',
  'ángulo de lanzamiento': 'угол броска',
  gravedad: 'ускорение свободного падения',
  masa: 'масса',
  'coeficiente de fricción': 'коэффициент трения',
  'fuerza normal': 'сила нормальной реакции',
  'constante del resorte': 'жёсткость пружины',
  deformación: 'деформация',
  velocidad: 'скорость',
  fuerza: 'сила',
  'ángulo entre F y d': 'угол между F и d',
  trabajo: 'работа',
  longitud: 'длина',
  'longitud de onda': 'длина волны',
  frecuencia: 'частота',
  'área': 'площадь',
  corriente: 'сила тока',
  resistencia: 'сопротивление',
  voltaje: 'напряжение',
  moles: 'количество вещества',
  'constante de los gases': 'газовая постоянная',
  temperatura: 'температура',
  volumen: 'объём',
  'presión inicial': 'начальное давление',
  'volumen inicial': 'начальный объём',
  'volumen final': 'конечный объём',
  'temperatura inicial': 'начальная температура',
  'temperatura final': 'конечная температура',
  'moles de soluto': 'число молей растворённого вещества',
  'volumen de disolución': 'объём раствора',
  'masa de disolvente': 'масса растворителя',
  'concentración inicial': 'начальная концентрация',
  'masa de soluto': 'масса растворённого вещества',
  'masa total': 'общая масса',
  'concentración de H⁺': 'концентрация H⁺',
  'pH de la disolución': 'pH раствора',
  'masa molar': 'молярная масса',
  'número de Avogadro': 'число Авогадро',
  'producto obtenido': 'практический выход',
  'producto teórico': 'теоретический выход',
  'calor específico': 'удельная теплоёмкость',
  'cambio de temperatura': 'изменение температуры',
  'calor latente': 'скрытая теплота',
  'entalpía de los productos': 'энтальпия продуктов',
  'entalpía de los reactivos': 'энтальпия реагентов',
}

/** Unidades escritas con palabras (las de símbolo son universales). */
export const UNIDADES_RU: Record<string, string> = { 'años': 'лет' }
