/**
 * El formulario de fábrica en turco.
 *
 * No se duplican las 54 estructuras: la notación (`tex`, `expresion`, los
 * símbolos) es universal y solo cambian los NOMBRES. Aquí viven esos nombres y
 * `catalogo.ts` arma el catálogo traducido aplicándolos. Los de variable van en
 * un diccionario global porque se repiten mucho («masa» sale en once fórmulas).
 *
 * Lo que no esté traducido se queda en español antes que desaparecer.
 */
import type { AreaFabrica } from './constantes'

export const AREAS_TR: Record<AreaFabrica, string> = {
  matematicas: 'Matematik',
  fisica: 'Fizik',
  quimica: 'Kimya',
}

export const GRUPOS_TR: Record<string, string> = {
  'Geometría': 'Geometri',
  'Álgebra': 'Cebir',
  'Sucesiones': 'Diziler',
  'Trigonometría': 'Trigonometri',
  'Finanzas': 'Finans',
  'Cinemática': 'Kinematik',
  'Dinámica': 'Dinamik',
  'Energía': 'Enerji',
  'Ondas': 'Dalgalar',
  'Electricidad': 'Elektrik',
  'Gases': 'Gazlar',
  'Disoluciones': 'Çözeltiler',
  'Estequiometría': 'Stokiyometri',
  'Termoquímica': 'Termokimya',
}

/** Nombre de cada fórmula, por slug. */
export const FORMULAS_TR: Record<string, string> = {
  // Matemáticas
  'area-circulo': 'Dairenin alanı',
  circunferencia: 'Çemberin çevresi',
  'area-triangulo': 'Üçgenin alanı',
  'area-trapecio': 'Yamuğun alanı',
  'volumen-cilindro': 'Silindirin hacmi',
  'volumen-esfera': 'Kürenin hacmi',
  'volumen-cono': 'Koninin hacmi',
  pitagoras: 'Pisagor teoremi',
  'formula-general': 'Genel formül (pozitif kök)',
  discriminante: 'Diskriminant',
  pendiente: 'Doğrunun eğimi',
  'distancia-puntos': 'İki nokta arasındaki uzaklık',
  'cambio-base': 'Logaritmanın taban değişimi',
  'termino-aritmetica': 'Aritmetik dizinin genel terimi',
  'suma-geometrica': 'Geometrik dizinin toplamı',
  'ley-senos': 'Sinüs teoremi',
  'ley-cosenos': 'Kosinüs teoremi',
  'interes-compuesto': 'Bileşik faiz',
  // Física
  'velocidad-media': 'Ortalama hız',
  'mrua-velocidad': 'Sabit ivmeli hız',
  'mrua-posicion': 'Sabit ivmeli konum',
  torricelli: 'Torricelli denklemi',
  'alcance-tiro': 'Eğik atışın menzili',
  'segunda-ley': 'Newton’un ikinci yasası',
  peso: 'Ağırlık',
  friccion: 'Sürtünme kuvveti',
  hooke: 'Hooke yasası',
  'energia-cinetica': 'Kinetik enerji',
  'energia-potencial': 'Yerçekimi potansiyel enerjisi',
  trabajo: 'İş',
  potencia: 'Güç',
  'periodo-pendulo': 'Basit sarkacın periyodu',
  'velocidad-onda': 'Dalga hızı',
  presion: 'Basınç',
  'ley-ohm': 'Ohm yasası',
  'potencia-electrica': 'Elektrik gücü',
  // Química
  'gas-ideal': 'İdeal gaz yasası (basınç)',
  boyle: 'Boyle yasası',
  charles: 'Charles yasası',
  'gay-lussac': 'Gay-Lussac yasası',
  molaridad: 'Molarite',
  molalidad: 'Molalite',
  dilucion: 'Seyreltme',
  'porcentaje-masa': 'Kütlece yüzde',
  ph: 'pH',
  poh: 'pH’tan pOH',
  moles: 'Kütleden mol sayısı',
  'masa-de-moles': 'Mol sayısından kütle',
  'numero-particulas': 'Parçacık sayısı',
  rendimiento: 'Reaksiyon verimi',
  'calor-sensible': 'Duyulur ısı',
  'calor-latente': 'Gizli ısı',
  densidad: 'Yoğunluk',
  'entalpia-reaccion': 'Reaksiyon entalpisi',
}

/** Nombres de variable, por su texto en español. */
export const VARIABLES_TR: Record<string, string> = {
  radio: 'yarıçap',
  base: 'taban',
  altura: 'yükseklik',
  'base mayor': 'büyük taban',
  'base menor': 'küçük taban',
  cateto: 'dik kenar',
  'coeficiente cuadrático': 'ikinci derece katsayısı',
  'coeficiente lineal': 'birinci derece katsayısı',
  'término independiente': 'sabit terim',
  'x del primer punto': 'birinci noktanın x’i',
  'y del primer punto': 'birinci noktanın y’si',
  'x del segundo punto': 'ikinci noktanın x’i',
  'y del segundo punto': 'ikinci noktanın y’si',
  argumento: 'argüman',
  'primer término': 'ilk terim',
  posición: 'terim numarası',
  diferencia: 'ortak fark',
  razón: 'ortak oran',
  'número de términos': 'terim sayısı',
  'lado conocido': 'bilinen kenar',
  lado: 'kenar',
  'ángulo opuesto a a': 'a’nın karşısındaki açı',
  'ángulo opuesto a b': 'b’nin karşısındaki açı',
  'ángulo entre a y b': 'a ile b arasındaki açı',
  'capital inicial': 'başlangıç sermayesi',
  'tasa anual (0.08 = 8 %)': 'yıllık faiz oranı (0.08 = %8)',
  'capitalizaciones al año': 'yıllık bileşiklenme sayısı',
  'años': 'yıl',
  distancia: 'mesafe',
  tiempo: 'zaman',
  'velocidad inicial': 'ilk hız',
  aceleración: 'ivme',
  'posición inicial': 'ilk konum',
  desplazamiento: 'yer değiştirme',
  'ángulo de lanzamiento': 'atış açısı',
  gravedad: 'yerçekimi ivmesi',
  masa: 'kütle',
  'coeficiente de fricción': 'sürtünme katsayısı',
  'fuerza normal': 'normal kuvvet',
  'constante del resorte': 'yay sabiti',
  deformación: 'uzama',
  velocidad: 'hız',
  fuerza: 'kuvvet',
  'ángulo entre F y d': 'F ile d arasındaki açı',
  trabajo: 'iş',
  longitud: 'uzunluk',
  'longitud de onda': 'dalga boyu',
  frecuencia: 'frekans',
  'área': 'alan',
  corriente: 'akım',
  resistencia: 'direnç',
  voltaje: 'gerilim',
  moles: 'mol sayısı',
  'constante de los gases': 'gaz sabiti',
  temperatura: 'sıcaklık',
  volumen: 'hacim',
  'presión inicial': 'ilk basınç',
  'volumen inicial': 'ilk hacim',
  'volumen final': 'son hacim',
  'temperatura inicial': 'ilk sıcaklık',
  'temperatura final': 'son sıcaklık',
  'moles de soluto': 'çözünenin mol sayısı',
  'volumen de disolución': 'çözeltinin hacmi',
  'masa de disolvente': 'çözücünün kütlesi',
  'concentración inicial': 'ilk derişim',
  'masa de soluto': 'çözünenin kütlesi',
  'masa total': 'toplam kütle',
  'concentración de H⁺': 'H⁺ derişimi',
  'pH de la disolución': 'çözeltinin pH’ı',
  'masa molar': 'molar kütle',
  'número de Avogadro': 'Avogadro sayısı',
  'producto obtenido': 'gerçek verim',
  'producto teórico': 'teorik verim',
  'calor específico': 'özgül ısı',
  'cambio de temperatura': 'sıcaklık değişimi',
  'calor latente': 'gizli ısı',
  'entalpía de los productos': 'ürünlerin entalpisi',
  'entalpía de los reactivos': 'girenlerin entalpisi',
}

/** Unidades escritas con palabras (las de símbolo son universales). */
export const UNIDADES_TR: Record<string, string> = { 'años': 'yıl' }
