/**
 * El formulario de fábrica en árabe.
 *
 * No se duplican las 54 estructuras: la notación (`tex`, `expresion`, los
 * símbolos) es universal y solo cambian los NOMBRES. Aquí viven esos nombres y
 * `catalogo.ts` arma el catálogo traducido aplicándolos. Los de variable van en
 * un diccionario global porque se repiten mucho («masa» sale en once fórmulas).
 *
 * Lo que no esté traducido se queda en español antes que desaparecer.
 *
 * El `tex` NO se toca aquí (sigue universal, con los rótulos en latín para
 * KaTeX+RTL): solo se traducen nombre/grupo/variable, con cifras occidentales.
 */
import type { AreaFabrica } from './constantes'

export const AREAS_AR: Record<AreaFabrica, string> = {
  matematicas: 'الرياضيات',
  fisica: 'الفيزياء',
  quimica: 'الكيمياء',
}

export const GRUPOS_AR: Record<string, string> = {
  'Geometría': 'الهندسة',
  'Álgebra': 'الجبر',
  'Sucesiones': 'المتتاليات',
  'Trigonometría': 'حساب المثلثات',
  'Finanzas': 'المالية',
  'Cinemática': 'الحركة',
  'Dinámica': 'الديناميكا',
  'Energía': 'الطاقة',
  'Ondas': 'الموجات',
  'Electricidad': 'الكهرباء',
  'Gases': 'الغازات',
  'Disoluciones': 'المحاليل',
  'Estequiometría': 'الحسابات الكيميائية',
  'Termoquímica': 'الكيمياء الحرارية',
}

/** Nombre de cada fórmula, por slug. */
export const FORMULAS_AR: Record<string, string> = {
  // Matemáticas
  'area-circulo': 'مساحة الدائرة',
  circunferencia: 'محيط الدائرة',
  'area-triangulo': 'مساحة المثلث',
  'area-trapecio': 'مساحة شبه المنحرف',
  'volumen-cilindro': 'حجم الأسطوانة',
  'volumen-esfera': 'حجم الكرة',
  'volumen-cono': 'حجم المخروط',
  pitagoras: 'نظرية فيثاغورس',
  'formula-general': 'القانون العام لحل المعادلة التربيعية (الجذر الموجب)',
  discriminante: 'المميز',
  pendiente: 'ميل المستقيم',
  'distancia-puntos': 'المسافة بين نقطتين',
  'cambio-base': 'تغيير أساس اللوغاريتم',
  'termino-aritmetica': 'الحد العام للمتتالية الحسابية',
  'suma-geometrica': 'مجموع متتالية هندسية',
  'ley-senos': 'قانون الجيب',
  'ley-cosenos': 'قانون جيب التمام',
  'interes-compuesto': 'الفائدة المركبة',
  // Física
  'velocidad-media': 'السرعة المتوسطة',
  'mrua-velocidad': 'السرعة بتسارع ثابت',
  'mrua-posicion': 'الموضع بتسارع ثابت',
  torricelli: 'معادلة توريتشيلي',
  'alcance-tiro': 'مدى القذف المائل',
  'segunda-ley': 'قانون نيوتن الثاني',
  peso: 'الوزن',
  friccion: 'قوة الاحتكاك',
  hooke: 'قانون هوك',
  'energia-cinetica': 'الطاقة الحركية',
  'energia-potencial': 'طاقة الوضع الثقالية',
  trabajo: 'الشغل',
  potencia: 'القدرة',
  'periodo-pendulo': 'الدور الزمني للبندول البسيط',
  'velocidad-onda': 'سرعة الموجة',
  presion: 'الضغط',
  'ley-ohm': 'قانون أوم',
  'potencia-electrica': 'القدرة الكهربائية',
  // Química
  'gas-ideal': 'قانون الغاز المثالي (الضغط)',
  boyle: 'قانون بويل',
  charles: 'قانون شارل',
  'gay-lussac': 'قانون غاي لوساك',
  molaridad: 'التركيز المولاري',
  molalidad: 'التركيز المولالي',
  dilucion: 'التخفيف',
  'porcentaje-masa': 'النسبة المئوية الكتلية',
  ph: 'pH',
  poh: 'pOH من pH',
  moles: 'عدد المولات من الكتلة',
  'masa-de-moles': 'الكتلة من عدد المولات',
  'numero-particulas': 'عدد الجسيمات',
  rendimiento: 'مردود التفاعل',
  'calor-sensible': 'الحرارة المحسوسة',
  'calor-latente': 'الحرارة الكامنة',
  densidad: 'الكثافة',
  'entalpia-reaccion': 'إنثالبي التفاعل',
}

/** Nombres de variable, por su texto en español. */
export const VARIABLES_AR: Record<string, string> = {
  radio: 'نصف القطر',
  base: 'القاعدة',
  altura: 'الارتفاع',
  'base mayor': 'القاعدة الكبرى',
  'base menor': 'القاعدة الصغرى',
  cateto: 'الضلع القائم',
  'coeficiente cuadrático': 'المعامل التربيعي',
  'coeficiente lineal': 'المعامل الخطي',
  'término independiente': 'الحد الثابت',
  'x del primer punto': 'x للنقطة الأولى',
  'y del primer punto': 'y للنقطة الأولى',
  'x del segundo punto': 'x للنقطة الثانية',
  'y del segundo punto': 'y للنقطة الثانية',
  argumento: 'الوسيطة',
  'primer término': 'الحد الأول',
  posición: 'الرتبة',
  diferencia: 'الفرق المشترك',
  razón: 'النسبة المشتركة',
  'número de términos': 'عدد الحدود',
  'lado conocido': 'الضلع المعلوم',
  lado: 'الضلع',
  'ángulo opuesto a a': 'الزاوية المقابلة لـ a',
  'ángulo opuesto a b': 'الزاوية المقابلة لـ b',
  'ángulo entre a y b': 'الزاوية بين a و b',
  'capital inicial': 'رأس المال الابتدائي',
  'tasa anual (0.08 = 8 %)': 'المعدل السنوي (0.08 = 8 %)',
  'capitalizaciones al año': 'عدد مرات التركيب في السنة',
  'años': 'سنوات',
  distancia: 'المسافة',
  tiempo: 'الزمن',
  'velocidad inicial': 'السرعة الابتدائية',
  aceleración: 'التسارع',
  'posición inicial': 'الموضع الابتدائي',
  desplazamiento: 'الإزاحة',
  'ángulo de lanzamiento': 'زاوية الإطلاق',
  gravedad: 'تسارع الجاذبية',
  masa: 'الكتلة',
  'coeficiente de fricción': 'معامل الاحتكاك',
  'fuerza normal': 'القوة العمودية',
  'constante del resorte': 'ثابت الزنبرك',
  deformación: 'التشوه',
  velocidad: 'السرعة',
  fuerza: 'القوة',
  'ángulo entre F y d': 'الزاوية بين F و d',
  trabajo: 'الشغل',
  longitud: 'الطول',
  'longitud de onda': 'الطول الموجي',
  frecuencia: 'التردد',
  'área': 'المساحة',
  corriente: 'شدة التيار',
  resistencia: 'المقاومة',
  voltaje: 'الجهد الكهربائي',
  moles: 'عدد المولات',
  'constante de los gases': 'ثابت الغازات',
  temperatura: 'درجة الحرارة',
  volumen: 'الحجم',
  'presión inicial': 'الضغط الابتدائي',
  'volumen inicial': 'الحجم الابتدائي',
  'volumen final': 'الحجم النهائي',
  'temperatura inicial': 'درجة الحرارة الابتدائية',
  'temperatura final': 'درجة الحرارة النهائية',
  'moles de soluto': 'عدد مولات المذاب',
  'volumen de disolución': 'حجم المحلول',
  'masa de disolvente': 'كتلة المذيب',
  'concentración inicial': 'التركيز الابتدائي',
  'masa de soluto': 'كتلة المذاب',
  'masa total': 'الكتلة الكلية',
  'concentración de H⁺': 'تركيز H⁺',
  'pH de la disolución': 'pH المحلول',
  'masa molar': 'الكتلة المولية',
  'número de Avogadro': 'عدد أفوغادرو',
  'producto obtenido': 'الناتج الفعلي',
  'producto teórico': 'الناتج النظري',
  'calor específico': 'الحرارة النوعية',
  'cambio de temperatura': 'التغير في درجة الحرارة',
  'calor latente': 'الحرارة الكامنة',
  'entalpía de los productos': 'إنثالبي النواتج',
  'entalpía de los reactivos': 'إنثالبي المتفاعلات',
}

/** Unidades escritas con palabras (las de símbolo son universales). */
export const UNIDADES_AR: Record<string, string> = { 'años': 'سنوات' }
