/**
 * El formulario de fábrica en coreano.
 *
 * No se duplican las 54 estructuras: la notación (`tex`, `expresion`, los
 * símbolos) es universal y solo cambian los NOMBRES. Aquí viven esos nombres y
 * `catalogo.ts` arma el catálogo traducido aplicándolos. Los de variable van en
 * un diccionario global porque se repiten mucho («masa» sale en once fórmulas).
 *
 * Lo que no esté traducido se queda en español antes que desaparecer.
 */
import type { AreaFabrica } from './constantes'

export const AREAS_KO: Record<AreaFabrica, string> = {
  matematicas: '수학',
  fisica: '물리',
  quimica: '화학',
}

export const GRUPOS_KO: Record<string, string> = {
  'Geometría': '기하',
  'Álgebra': '대수',
  'Sucesiones': '수열',
  'Trigonometría': '삼각법',
  'Finanzas': '금융',
  'Cinemática': '운동학',
  'Dinámica': '동역학',
  'Energía': '에너지',
  'Ondas': '파동',
  'Electricidad': '전기',
  'Gases': '기체',
  'Disoluciones': '용액',
  'Estequiometría': '화학량론',
  'Termoquímica': '열화학',
}

/** Nombre de cada fórmula, por slug. */
export const FORMULAS_KO: Record<string, string> = {
  // Matemáticas
  'area-circulo': '원의 넓이',
  circunferencia: '원의 둘레',
  'area-triangulo': '삼각형의 넓이',
  'area-trapecio': '사다리꼴의 넓이',
  'volumen-cilindro': '원기둥의 부피',
  'volumen-esfera': '구의 부피',
  'volumen-cono': '원뿔의 부피',
  pitagoras: '피타고라스 정리',
  'formula-general': '근의 공식(양의 근)',
  discriminante: '판별식',
  pendiente: '직선의 기울기',
  'distancia-puntos': '두 점 사이의 거리',
  'cambio-base': '로그의 밑 변환',
  'termino-aritmetica': '등차수열의 일반항',
  'suma-geometrica': '등비수열의 합',
  'ley-senos': '사인 법칙',
  'ley-cosenos': '코사인 법칙',
  'interes-compuesto': '복리',
  // Física
  'velocidad-media': '평균 속도',
  'mrua-velocidad': '등가속도 직선 운동의 속도',
  'mrua-posicion': '등가속도 직선 운동의 위치',
  torricelli: '토리첼리 공식',
  'alcance-tiro': '포물선 운동의 도달 거리',
  'segunda-ley': '뉴턴 운동 제2법칙',
  peso: '중력',
  friccion: '마찰력',
  hooke: '훅의 법칙',
  'energia-cinetica': '운동 에너지',
  'energia-potencial': '중력 위치 에너지',
  trabajo: '일',
  potencia: '일률',
  'periodo-pendulo': '단진자의 주기',
  'velocidad-onda': '파동의 속력',
  presion: '압력',
  'ley-ohm': '옴의 법칙',
  'potencia-electrica': '전력',
  // Química
  'gas-ideal': '이상 기체 상태 방정식(압력)',
  boyle: '보일의 법칙',
  charles: '샤를의 법칙',
  'gay-lussac': '게이뤼삭의 법칙',
  molaridad: '몰 농도',
  molalidad: '몰랄 농도',
  dilucion: '희석',
  'porcentaje-masa': '질량 백분율',
  ph: 'pH',
  poh: 'pH로 구하는 pOH',
  moles: '질량으로 구하는 몰수',
  'masa-de-moles': '몰수로 구하는 질량',
  'numero-particulas': '입자 수',
  rendimiento: '반응 수율',
  'calor-sensible': '현열',
  'calor-latente': '잠열',
  densidad: '밀도',
  'entalpia-reaccion': '반응 엔탈피 변화',
}

/** Nombres de variable, por su texto en español. */
export const VARIABLES_KO: Record<string, string> = {
  radio: '반지름',
  base: '밑',
  altura: '높이',
  'base mayor': '아랫변',
  'base menor': '윗변',
  cateto: '직각변',
  'coeficiente cuadrático': '이차항의 계수',
  'coeficiente lineal': '일차항의 계수',
  'término independiente': '상수항',
  'x del primer punto': '첫 번째 점의 x',
  'y del primer punto': '첫 번째 점의 y',
  'x del segundo punto': '두 번째 점의 x',
  'y del segundo punto': '두 번째 점의 y',
  argumento: '진수',
  'primer término': '첫째항',
  posición: '항 번호',
  diferencia: '공차',
  razón: '공비',
  'número de términos': '항의 개수',
  'lado conocido': '알고 있는 변',
  lado: '변',
  'ángulo opuesto a a': '변 a의 대각',
  'ángulo opuesto a b': '변 b의 대각',
  'ángulo entre a y b': '변 a와 변 b 사이의 각',
  'capital inicial': '원금',
  'tasa anual (0.08 = 8 %)': '연이율 (0.08 = 8%)',
  'capitalizaciones al año': '연간 복리 횟수',
  'años': '년',
  distancia: '거리',
  tiempo: '시간',
  'velocidad inicial': '초기 속도',
  aceleración: '가속도',
  'posición inicial': '초기 위치',
  desplazamiento: '변위',
  'ángulo de lanzamiento': '발사각',
  gravedad: '중력 가속도',
  masa: '질량',
  'coeficiente de fricción': '마찰 계수',
  'fuerza normal': '수직항력',
  'constante del resorte': '스프링 상수',
  deformación: '변형량',
  velocidad: '속도',
  fuerza: '힘',
  'ángulo entre F y d': '힘 F와 변위 d 사이의 각',
  trabajo: '일',
  longitud: '길이',
  'longitud de onda': '파장',
  frecuencia: '진동수',
  'área': '넓이',
  corriente: '전류',
  resistencia: '저항',
  voltaje: '전압',
  moles: '몰수',
  'constante de los gases': '기체 상수',
  temperatura: '온도',
  volumen: '부피',
  'presión inicial': '초기 압력',
  'volumen inicial': '초기 부피',
  'volumen final': '최종 부피',
  'temperatura inicial': '초기 온도',
  'temperatura final': '최종 온도',
  'moles de soluto': '용질의 몰수',
  'volumen de disolución': '용액의 부피',
  'masa de disolvente': '용매의 질량',
  'concentración inicial': '초기 농도',
  'masa de soluto': '용질의 질량',
  'masa total': '전체 질량',
  'concentración de H⁺': '수소 이온 농도',
  'pH de la disolución': '용액의 pH',
  'masa molar': '몰 질량',
  'número de Avogadro': '아보가드로 수',
  'producto obtenido': '실제 수득량',
  'producto teórico': '이론 수득량',
  'calor específico': '비열',
  'cambio de temperatura': '온도 변화',
  'calor latente': '잠열',
  'entalpía de los productos': '생성물의 엔탈피',
  'entalpía de los reactivos': '반응물의 엔탈피',
}

/** Unidades escritas con palabras (las de símbolo son universales). */
export const UNIDADES_KO: Record<string, string> = { 'años': '년' }
