/**
 * El formulario de fábrica en italiano.
 *
 * No se duplican las 54 estructuras: la notación (`tex`, `expresion`, los
 * símbolos) es universal y solo cambian los NOMBRES. Aquí viven esos nombres y
 * `catalogo.ts` arma el catálogo traducido aplicándolos. Los de variable van en
 * un diccionario global porque se repiten mucho («masa» sale en once fórmulas).
 *
 * Lo que no esté traducido se queda en español antes que desaparecer.
 */
import type { AreaFabrica } from './constantes'

export const AREAS_IT: Record<AreaFabrica, string> = {
  matematicas: 'Matematica',
  fisica: 'Fisica',
  quimica: 'Chimica',
}

export const GRUPOS_IT: Record<string, string> = {
  'Geometría': 'Geometria',
  'Álgebra': 'Algebra',
  'Sucesiones': 'Successioni',
  'Trigonometría': 'Trigonometria',
  'Finanzas': 'Finanza',
  'Cinemática': 'Cinematica',
  'Dinámica': 'Dinamica',
  'Energía': 'Energia',
  'Ondas': 'Onde',
  'Electricidad': 'Elettricità',
  'Gases': 'Gas',
  'Disoluciones': 'Soluzioni',
  'Estequiometría': 'Stechiometria',
  'Termoquímica': 'Termochimica',
}

/** Nombre de cada fórmula, por slug. */
export const FORMULAS_IT: Record<string, string> = {
  // Matemáticas
  'area-circulo': 'Area del cerchio',
  circunferencia: 'Circonferenza',
  'area-triangulo': 'Area del triangolo',
  'area-trapecio': 'Area del trapezio',
  'volumen-cilindro': 'Volume del cilindro',
  'volumen-esfera': 'Volume della sfera',
  'volumen-cono': 'Volume del cono',
  pitagoras: 'Teorema di Pitagora',
  'formula-general': 'Formula risolutiva (radice positiva)',
  discriminante: 'Discriminante',
  pendiente: 'Coefficiente angolare di una retta',
  'distancia-puntos': 'Distanza tra due punti',
  'cambio-base': 'Cambio di base del logaritmo',
  'termino-aritmetica': 'Termine n-esimo di una successione aritmetica',
  'suma-geometrica': 'Somma di una successione geometrica',
  'ley-senos': 'Teorema dei seni',
  'ley-cosenos': 'Teorema del coseno',
  'interes-compuesto': 'Interesse composto',
  // Física
  'velocidad-media': 'Velocità media',
  'mrua-velocidad': 'Velocità con accelerazione costante',
  'mrua-posicion': 'Posizione con accelerazione costante',
  torricelli: 'Equazione di Torricelli',
  'alcance-tiro': 'Gittata del moto parabolico',
  'segunda-ley': 'Secondo principio della dinamica',
  peso: 'Peso',
  friccion: 'Forza di attrito',
  hooke: 'Legge di Hooke',
  'energia-cinetica': 'Energia cinetica',
  'energia-potencial': 'Energia potenziale gravitazionale',
  trabajo: 'Lavoro',
  potencia: 'Potenza',
  'periodo-pendulo': 'Periodo del pendolo semplice',
  'velocidad-onda': "Velocità dell'onda",
  presion: 'Pressione',
  'ley-ohm': 'Legge di Ohm',
  'potencia-electrica': 'Potenza elettrica',
  // Química
  'gas-ideal': 'Legge dei gas ideali (pressione)',
  boyle: 'Legge di Boyle',
  charles: 'Legge di Charles',
  'gay-lussac': 'Legge di Gay-Lussac',
  molaridad: 'Molarità',
  molalidad: 'Molalità',
  dilucion: 'Diluizione',
  'porcentaje-masa': 'Percentuale in massa',
  ph: 'pH',
  poh: 'pOH dal pH',
  moles: 'Moli a partire dalla massa',
  'masa-de-moles': 'Massa a partire dalle moli',
  'numero-particulas': 'Numero di particelle',
  rendimiento: 'Resa della reazione',
  'calor-sensible': 'Calore sensibile',
  'calor-latente': 'Calore latente',
  densidad: 'Densità',
  'entalpia-reaccion': 'Entalpia di reazione',
}

/** Nombres de variable, por su texto en español. */
export const VARIABLES_IT: Record<string, string> = {
  radio: 'raggio',
  base: 'base',
  altura: 'altezza',
  'base mayor': 'base maggiore',
  'base menor': 'base minore',
  cateto: 'cateto',
  'coeficiente cuadrático': 'coefficiente quadratico',
  'coeficiente lineal': 'coefficiente lineare',
  'término independiente': 'termine noto',
  'x del primer punto': 'x del primo punto',
  'y del primer punto': 'y del primo punto',
  'x del segundo punto': 'x del secondo punto',
  'y del segundo punto': 'y del secondo punto',
  argumento: 'argomento',
  'primer término': 'primo termine',
  posición: 'posizione',
  diferencia: 'ragione',
  razón: 'ragione',
  'número de términos': 'numero di termini',
  'lado conocido': 'lato noto',
  lado: 'lato',
  'ángulo opuesto a a': 'angolo opposto ad a',
  'ángulo opuesto a b': 'angolo opposto a b',
  'ángulo entre a y b': 'angolo tra a e b',
  'capital inicial': 'capitale iniziale',
  'tasa anual (0.08 = 8 %)': 'tasso annuale (0.08 = 8 %)',
  'capitalizaciones al año': "capitalizzazioni all'anno",
  'años': 'anni',
  distancia: 'distanza',
  tiempo: 'tempo',
  'velocidad inicial': 'velocità iniziale',
  aceleración: 'accelerazione',
  'posición inicial': 'posizione iniziale',
  desplazamiento: 'spostamento',
  'ángulo de lanzamiento': 'angolo di lancio',
  gravedad: 'gravità',
  masa: 'massa',
  'coeficiente de fricción': 'coefficiente di attrito',
  'fuerza normal': 'forza normale',
  'constante del resorte': 'costante elastica',
  deformación: 'deformazione',
  velocidad: 'velocità',
  fuerza: 'forza',
  'ángulo entre F y d': 'angolo tra F e d',
  trabajo: 'lavoro',
  longitud: 'lunghezza',
  'longitud de onda': "lunghezza d'onda",
  frecuencia: 'frequenza',
  'área': 'area',
  corriente: 'corrente',
  resistencia: 'resistenza',
  voltaje: 'tensione',
  moles: 'moli',
  'constante de los gases': 'costante dei gas',
  temperatura: 'temperatura',
  volumen: 'volume',
  'presión inicial': 'pressione iniziale',
  'volumen inicial': 'volume iniziale',
  'volumen final': 'volume finale',
  'temperatura inicial': 'temperatura iniziale',
  'temperatura final': 'temperatura finale',
  'moles de soluto': 'moli di soluto',
  'volumen de disolución': 'volume della soluzione',
  'masa de disolvente': 'massa del solvente',
  'concentración inicial': 'concentrazione iniziale',
  'masa de soluto': 'massa del soluto',
  'masa total': 'massa totale',
  'concentración de H⁺': 'concentrazione di H⁺',
  'pH de la disolución': 'pH della soluzione',
  'masa molar': 'massa molare',
  'número de Avogadro': 'numero di Avogadro',
  'producto obtenido': 'prodotto ottenuto',
  'producto teórico': 'prodotto teorico',
  'calor específico': 'calore specifico',
  'cambio de temperatura': 'variazione di temperatura',
  'calor latente': 'calore latente',
  'entalpía de los productos': 'entalpia dei prodotti',
  'entalpía de los reactivos': 'entalpia dei reagenti',
}

/** Unidades escritas con palabras (las de símbolo son universales). */
export const UNIDADES_IT: Record<string, string> = { 'años': 'anni' }
