/**
 * El formulario de fábrica en francés.
 *
 * No se duplican las 54 estructuras: la notación (`tex`, `expresion`, los
 * símbolos) es universal y solo cambian los NOMBRES. Aquí viven esos nombres y
 * `catalogo.ts` arma el catálogo traducido aplicándolos. Los de variable van en
 * un diccionario global porque se repiten mucho («masa» sale en once fórmulas).
 *
 * Lo que no esté traducido se queda en español antes que desaparecer.
 */
import type { AreaFabrica } from './constantes'

export const AREAS_FR: Record<AreaFabrica, string> = {
  matematicas: 'Mathématiques',
  fisica: 'Physique',
  quimica: 'Chimie',
}

export const GRUPOS_FR: Record<string, string> = {
  'Geometría': 'Géométrie',
  'Álgebra': 'Algèbre',
  'Sucesiones': 'Suites',
  'Trigonometría': 'Trigonométrie',
  'Finanzas': 'Finance',
  'Cinemática': 'Cinématique',
  'Dinámica': 'Dynamique',
  'Energía': 'Énergie',
  'Ondas': 'Ondes',
  'Electricidad': 'Électricité',
  'Gases': 'Gaz',
  'Disoluciones': 'Solutions',
  'Estequiometría': 'Stœchiométrie',
  'Termoquímica': 'Thermochimie',
}

/** Nombre de cada fórmula, por slug. */
export const FORMULAS_FR: Record<string, string> = {
  // Matemáticas
  'area-circulo': 'Aire du cercle',
  circunferencia: 'Circonférence',
  'area-triangulo': 'Aire du triangle',
  'area-trapecio': 'Aire du trapèze',
  'volumen-cilindro': 'Volume du cylindre',
  'volumen-esfera': 'Volume de la sphère',
  'volumen-cono': 'Volume du cône',
  pitagoras: 'Théorème de Pythagore',
  'formula-general': 'Formule du second degré (racine positive)',
  discriminante: 'Discriminant',
  pendiente: "Pente d'une droite",
  'distancia-puntos': 'Distance entre deux points',
  'cambio-base': 'Changement de base du logarithme',
  'termino-aritmetica': "Terme général d'une suite arithmétique",
  'suma-geometrica': "Somme d'une suite géométrique",
  'ley-senos': 'Loi des sinus',
  'ley-cosenos': 'Loi des cosinus',
  'interes-compuesto': 'Intérêts composés',
  // Física
  'velocidad-media': 'Vitesse moyenne',
  'mrua-velocidad': 'Vitesse à accélération constante',
  'mrua-posicion': 'Position à accélération constante',
  torricelli: 'Équation de Torricelli',
  'alcance-tiro': "Portée d'un tir parabolique",
  'segunda-ley': 'Deuxième loi de Newton',
  peso: 'Poids',
  friccion: 'Force de frottement',
  hooke: 'Loi de Hooke',
  'energia-cinetica': 'Énergie cinétique',
  'energia-potencial': 'Énergie potentielle de pesanteur',
  trabajo: 'Travail',
  potencia: 'Puissance',
  'periodo-pendulo': 'Période du pendule simple',
  'velocidad-onda': "Vitesse d'une onde",
  presion: 'Pression',
  'ley-ohm': "Loi d'Ohm",
  'potencia-electrica': 'Puissance électrique',
  // Química
  'gas-ideal': 'Loi des gaz parfaits (pression)',
  boyle: 'Loi de Boyle-Mariotte',
  charles: 'Loi de Charles',
  'gay-lussac': 'Loi de Gay-Lussac',
  molaridad: 'Molarité',
  molalidad: 'Molalité',
  dilucion: 'Dilution',
  'porcentaje-masa': 'Pourcentage massique',
  ph: 'pH',
  poh: 'pOH à partir du pH',
  moles: 'Moles à partir de la masse',
  'masa-de-moles': 'Masse à partir des moles',
  'numero-particulas': 'Nombre de particules',
  rendimiento: 'Rendement de la réaction',
  'calor-sensible': 'Chaleur sensible',
  'calor-latente': 'Chaleur latente',
  densidad: 'Densité',
  'entalpia-reaccion': 'Enthalpie de réaction',
}

/** Nombres de variable, por su texto en español. */
export const VARIABLES_FR: Record<string, string> = {
  radio: 'rayon',
  base: 'base',
  altura: 'hauteur',
  'base mayor': 'grande base',
  'base menor': 'petite base',
  cateto: "côté de l'angle droit",
  'coeficiente cuadrático': 'coefficient quadratique',
  'coeficiente lineal': 'coefficient linéaire',
  'término independiente': 'terme constant',
  'x del primer punto': 'x du premier point',
  'y del primer punto': 'y du premier point',
  'x del segundo punto': 'x du second point',
  'y del segundo punto': 'y du second point',
  argumento: 'argument',
  'primer término': 'premier terme',
  posición: 'position',
  diferencia: 'raison',
  razón: 'raison',
  'número de términos': 'nombre de termes',
  'lado conocido': 'côté connu',
  lado: 'côté',
  'ángulo opuesto a a': 'angle opposé à a',
  'ángulo opuesto a b': 'angle opposé à b',
  'ángulo entre a y b': 'angle entre a et b',
  'capital inicial': 'capital initial',
  'tasa anual (0.08 = 8 %)': 'taux annuel (0.08 = 8 %)',
  'capitalizaciones al año': 'capitalisations par an',
  'años': 'ans',
  distancia: 'distance',
  tiempo: 'temps',
  'velocidad inicial': 'vitesse initiale',
  aceleración: 'accélération',
  'posición inicial': 'position initiale',
  desplazamiento: 'déplacement',
  'ángulo de lanzamiento': 'angle de lancement',
  gravedad: 'gravité',
  masa: 'masse',
  'coeficiente de fricción': 'coefficient de frottement',
  'fuerza normal': 'force normale',
  'constante del resorte': 'constante du ressort',
  deformación: 'déformation',
  velocidad: 'vitesse',
  fuerza: 'force',
  'ángulo entre F y d': 'angle entre F et d',
  trabajo: 'travail',
  longitud: 'longueur',
  'longitud de onda': "longueur d'onde",
  frecuencia: 'fréquence',
  'área': 'aire',
  corriente: 'courant',
  resistencia: 'résistance',
  voltaje: 'tension',
  moles: 'moles',
  'constante de los gases': 'constante des gaz',
  temperatura: 'température',
  volumen: 'volume',
  'presión inicial': 'pression initiale',
  'volumen inicial': 'volume initial',
  'volumen final': 'volume final',
  'temperatura inicial': 'température initiale',
  'temperatura final': 'température finale',
  'moles de soluto': 'moles de soluté',
  'volumen de disolución': 'volume de la solution',
  'masa de disolvente': 'masse de solvant',
  'concentración inicial': 'concentration initiale',
  'masa de soluto': 'masse de soluté',
  'masa total': 'masse totale',
  'concentración de H⁺': 'concentration en H⁺',
  'pH de la disolución': 'pH de la solution',
  'masa molar': 'masse molaire',
  'número de Avogadro': "nombre d'Avogadro",
  'producto obtenido': 'produit obtenu',
  'producto teórico': 'produit théorique',
  'calor específico': 'chaleur spécifique',
  'cambio de temperatura': 'variation de température',
  'calor latente': 'chaleur latente',
  'entalpía de los productos': 'enthalpie des produits',
  'entalpía de los reactivos': 'enthalpie des réactifs',
}

/** Unidades escritas con palabras (las de símbolo son universales). */
export const UNIDADES_FR: Record<string, string> = { 'años': 'ans' }
