/**
 * El formulario de fábrica en polaco.
 *
 * No se duplican las 54 estructuras: la notación (`tex`, `expresion`, los
 * símbolos) es universal y solo cambian los NOMBRES. Aquí viven esos nombres y
 * `catalogo.ts` arma el catálogo traducido aplicándolos. Los de variable van en
 * un diccionario global porque se repiten mucho («masa» sale en once fórmulas).
 *
 * Lo que no esté traducido se queda en español antes que desaparecer.
 */
import type { AreaFabrica } from './constantes'

export const AREAS_PL: Record<AreaFabrica, string> = {
  matematicas: 'Matematyka',
  fisica: 'Fizyka',
  quimica: 'Chemia',
}

export const GRUPOS_PL: Record<string, string> = {
  'Geometría': 'Geometria',
  'Álgebra': 'Algebra',
  'Sucesiones': 'Ciągi',
  'Trigonometría': 'Trygonometria',
  'Finanzas': 'Finanse',
  'Cinemática': 'Kinematyka',
  'Dinámica': 'Dynamika',
  'Energía': 'Energia',
  'Ondas': 'Fale',
  'Electricidad': 'Elektryczność',
  'Gases': 'Gazy',
  'Disoluciones': 'Roztwory',
  'Estequiometría': 'Stechiometria',
  'Termoquímica': 'Termochemia',
}

/** Nombre de cada fórmula, por slug. */
export const FORMULAS_PL: Record<string, string> = {
  // Matemáticas
  'area-circulo': 'Pole koła',
  circunferencia: 'Obwód koła',
  'area-triangulo': 'Pole trójkąta',
  'area-trapecio': 'Pole trapezu',
  'volumen-cilindro': 'Objętość walca',
  'volumen-esfera': 'Objętość kuli',
  'volumen-cono': 'Objętość stożka',
  pitagoras: 'Twierdzenie Pitagorasa',
  'formula-general': 'Wzór na pierwiastki równania kwadratowego (pierwiastek dodatni)',
  discriminante: 'Wyróżnik',
  pendiente: 'Współczynnik kierunkowy prostej',
  'distancia-puntos': 'Odległość między dwoma punktami',
  'cambio-base': 'Zamiana podstawy logarytmu',
  'termino-aritmetica': 'N-ty wyraz ciągu arytmetycznego',
  'suma-geometrica': 'Suma ciągu geometrycznego',
  'ley-senos': 'Twierdzenie sinusów',
  'ley-cosenos': 'Twierdzenie cosinusów',
  'interes-compuesto': 'Procent składany',
  // Física
  'velocidad-media': 'Prędkość średnia',
  'mrua-velocidad': 'Prędkość przy stałym przyspieszeniu',
  'mrua-posicion': 'Położenie przy stałym przyspieszeniu',
  torricelli: 'Równanie Torricellego',
  'alcance-tiro': 'Zasięg rzutu ukośnego',
  'segunda-ley': 'Druga zasada dynamiki Newtona',
  peso: 'Ciężar',
  friccion: 'Siła tarcia',
  hooke: "Prawo Hooke'a",
  'energia-cinetica': 'Energia kinetyczna',
  'energia-potencial': 'Grawitacyjna energia potencjalna',
  trabajo: 'Praca',
  potencia: 'Moc',
  'periodo-pendulo': 'Okres wahadła matematycznego',
  'velocidad-onda': 'Prędkość fali',
  presion: 'Ciśnienie',
  'ley-ohm': 'Prawo Ohma',
  'potencia-electrica': 'Moc elektryczna',
  // Química
  'gas-ideal': 'Prawo gazu doskonałego (ciśnienie)',
  boyle: "Prawo Boyle'a",
  charles: 'Prawo Charlesa',
  'gay-lussac': 'Prawo Gay-Lussaca',
  molaridad: 'Stężenie molowe',
  molalidad: 'Stężenie molalne',
  dilucion: 'Rozcieńczanie',
  'porcentaje-masa': 'Procent masowy',
  ph: 'pH',
  poh: 'pOH na podstawie pH',
  moles: 'Liczba moli na podstawie masy',
  'masa-de-moles': 'Masa na podstawie liczby moli',
  'numero-particulas': 'Liczba cząstek',
  rendimiento: 'Wydajność reakcji',
  'calor-sensible': 'Ciepło jawne',
  'calor-latente': 'Ciepło utajone',
  densidad: 'Gęstość',
  'entalpia-reaccion': 'Entalpia reakcji',
}

/** Nombres de variable, por su texto en español. */
export const VARIABLES_PL: Record<string, string> = {
  radio: 'promień',
  base: 'podstawa',
  altura: 'wysokość',
  'base mayor': 'dłuższa podstawa',
  'base menor': 'krótsza podstawa',
  cateto: 'przyprostokątna',
  'coeficiente cuadrático': 'współczynnik kwadratowy',
  'coeficiente lineal': 'współczynnik liniowy',
  'término independiente': 'wyraz wolny',
  'x del primer punto': 'x pierwszego punktu',
  'y del primer punto': 'y pierwszego punktu',
  'x del segundo punto': 'x drugiego punktu',
  'y del segundo punto': 'y drugiego punktu',
  argumento: 'argument',
  'primer término': 'pierwszy wyraz',
  posición: 'pozycja',
  diferencia: 'różnica ciągu',
  razón: 'iloraz ciągu',
  'número de términos': 'liczba wyrazów',
  'lado conocido': 'znany bok',
  lado: 'bok',
  'ángulo opuesto a a': 'kąt naprzeciw a',
  'ángulo opuesto a b': 'kąt naprzeciw b',
  'ángulo entre a y b': 'kąt między a i b',
  'capital inicial': 'kapitał początkowy',
  'tasa anual (0.08 = 8 %)': 'stopa roczna (0.08 = 8 %)',
  'capitalizaciones al año': 'liczba kapitalizacji w roku',
  'años': 'lat',
  distancia: 'odległość',
  tiempo: 'czas',
  'velocidad inicial': 'prędkość początkowa',
  aceleración: 'przyspieszenie',
  'posición inicial': 'położenie początkowe',
  desplazamiento: 'przemieszczenie',
  'ángulo de lanzamiento': 'kąt wyrzutu',
  gravedad: 'przyspieszenie ziemskie',
  masa: 'masa',
  'coeficiente de fricción': 'współczynnik tarcia',
  'fuerza normal': 'siła normalna',
  'constante del resorte': 'stała sprężystości',
  deformación: 'odkształcenie',
  velocidad: 'prędkość',
  fuerza: 'siła',
  'ángulo entre F y d': 'kąt między F i d',
  trabajo: 'praca',
  longitud: 'długość',
  'longitud de onda': 'długość fali',
  frecuencia: 'częstotliwość',
  'área': 'powierzchnia',
  corriente: 'natężenie prądu',
  resistencia: 'opór elektryczny',
  voltaje: 'napięcie',
  moles: 'liczba moli',
  'constante de los gases': 'stała gazowa',
  temperatura: 'temperatura',
  volumen: 'objętość',
  'presión inicial': 'ciśnienie początkowe',
  'volumen inicial': 'objętość początkowa',
  'volumen final': 'objętość końcowa',
  'temperatura inicial': 'temperatura początkowa',
  'temperatura final': 'temperatura końcowa',
  'moles de soluto': 'liczba moli substancji rozpuszczonej',
  'volumen de disolución': 'objętość roztworu',
  'masa de disolvente': 'masa rozpuszczalnika',
  'concentración inicial': 'stężenie początkowe',
  'masa de soluto': 'masa substancji rozpuszczonej',
  'masa total': 'masa całkowita',
  'concentración de H⁺': 'stężenie H⁺',
  'pH de la disolución': 'pH roztworu',
  'masa molar': 'masa molowa',
  'número de Avogadro': 'liczba Avogadra',
  'producto obtenido': 'wydajność rzeczywista',
  'producto teórico': 'wydajność teoretyczna',
  'calor específico': 'ciepło właściwe',
  'cambio de temperatura': 'zmiana temperatury',
  'calor latente': 'ciepło utajone',
  'entalpía de los productos': 'entalpia produktów',
  'entalpía de los reactivos': 'entalpia substratów',
}

/** Unidades escritas con palabras (las de símbolo son universales). */
export const UNIDADES_PL: Record<string, string> = { 'años': 'lat' }
