/**
 * El formulario de fábrica en portugués (Brasil).
 *
 * No se duplican las 54 estructuras: la notación (`tex`, `expresion`, los
 * símbolos) es universal y solo cambian los NOMBRES. Aquí viven esos nombres y
 * `catalogo.ts` arma el catálogo traducido aplicándolos. Los de variable van en
 * un diccionario global porque se repiten mucho («masa» sale en once fórmulas).
 *
 * Lo que no esté traducido se queda en español antes que desaparecer.
 */
import type { AreaFabrica } from './constantes'

export const AREAS_PT: Record<AreaFabrica, string> = {
  matematicas: 'Matemática',
  fisica: 'Física',
  quimica: 'Química',
}

export const GRUPOS_PT: Record<string, string> = {
  'Geometría': 'Geometria',
  'Álgebra': 'Álgebra',
  'Sucesiones': 'Sequências',
  'Trigonometría': 'Trigonometria',
  'Finanzas': 'Finanças',
  'Cinemática': 'Cinemática',
  'Dinámica': 'Dinâmica',
  'Energía': 'Energia',
  'Ondas': 'Ondas',
  'Electricidad': 'Eletricidade',
  'Gases': 'Gases',
  'Disoluciones': 'Soluções',
  'Estequiometría': 'Estequiometria',
  'Termoquímica': 'Termoquímica',
}

/** Nombre de cada fórmula, por slug. */
export const FORMULAS_PT: Record<string, string> = {
  // Matemáticas
  'area-circulo': 'Área do círculo',
  circunferencia: 'Circunferência',
  'area-triangulo': 'Área do triângulo',
  'area-trapecio': 'Área do trapézio',
  'volumen-cilindro': 'Volume do cilindro',
  'volumen-esfera': 'Volume da esfera',
  'volumen-cono': 'Volume do cone',
  pitagoras: 'Teorema de Pitágoras',
  'formula-general': 'Fórmula geral (raiz positiva)',
  discriminante: 'Discriminante',
  pendiente: 'Coeficiente angular da reta',
  'distancia-puntos': 'Distância entre dois pontos',
  'cambio-base': 'Mudança de base do logaritmo',
  'termino-aritmetica': 'Termo geral de uma progressão aritmética',
  'suma-geometrica': 'Soma de uma progressão geométrica',
  'ley-senos': 'Lei dos senos',
  'ley-cosenos': 'Lei dos cossenos',
  'interes-compuesto': 'Juros compostos',
  // Física
  'velocidad-media': 'Velocidade média',
  'mrua-velocidad': 'Velocidade com aceleração constante',
  'mrua-posicion': 'Posição com aceleração constante',
  torricelli: 'Equação de Torricelli',
  'alcance-tiro': 'Alcance do lançamento oblíquo',
  'segunda-ley': 'Segunda lei de Newton',
  peso: 'Peso',
  friccion: 'Força de atrito',
  hooke: 'Lei de Hooke',
  'energia-cinetica': 'Energia cinética',
  'energia-potencial': 'Energia potencial gravitacional',
  trabajo: 'Trabalho',
  potencia: 'Potência',
  'periodo-pendulo': 'Período do pêndulo simples',
  'velocidad-onda': 'Velocidade da onda',
  presion: 'Pressão',
  'ley-ohm': 'Lei de Ohm',
  'potencia-electrica': 'Potência elétrica',
  // Química
  'gas-ideal': 'Lei dos gases ideais (pressão)',
  boyle: 'Lei de Boyle',
  charles: 'Lei de Charles',
  'gay-lussac': 'Lei de Gay-Lussac',
  molaridad: 'Molaridade',
  molalidad: 'Molalidade',
  dilucion: 'Diluição',
  'porcentaje-masa': 'Porcentagem em massa',
  ph: 'pH',
  poh: 'pOH a partir do pH',
  moles: 'Mols a partir da massa',
  'masa-de-moles': 'Massa a partir dos mols',
  'numero-particulas': 'Número de partículas',
  rendimiento: 'Rendimento da reação',
  'calor-sensible': 'Calor sensível',
  'calor-latente': 'Calor latente',
  densidad: 'Densidade',
  'entalpia-reaccion': 'Entalpia da reação',
}

/** Nombres de variable, por su texto en español. */
export const VARIABLES_PT: Record<string, string> = {
  radio: 'raio',
  base: 'base',
  altura: 'altura',
  'base mayor': 'base maior',
  'base menor': 'base menor',
  cateto: 'cateto',
  'coeficiente cuadrático': 'coeficiente quadrático',
  'coeficiente lineal': 'coeficiente linear',
  'término independiente': 'termo independente',
  'x del primer punto': 'x do primeiro ponto',
  'y del primer punto': 'y do primeiro ponto',
  'x del segundo punto': 'x do segundo ponto',
  'y del segundo punto': 'y do segundo ponto',
  argumento: 'argumento',
  'primer término': 'primeiro termo',
  posición: 'posição',
  diferencia: 'diferença comum',
  razón: 'razão comum',
  'número de términos': 'número de termos',
  'lado conocido': 'lado conhecido',
  lado: 'lado',
  'ángulo opuesto a a': 'ângulo oposto a a',
  'ángulo opuesto a b': 'ângulo oposto a b',
  'ángulo entre a y b': 'ângulo entre a e b',
  'capital inicial': 'capital inicial',
  'tasa anual (0.08 = 8 %)': 'taxa anual (0.08 = 8 %)',
  'capitalizaciones al año': 'capitalizações por ano',
  'años': 'anos',
  distancia: 'distância',
  tiempo: 'tempo',
  'velocidad inicial': 'velocidade inicial',
  aceleración: 'aceleração',
  'posición inicial': 'posição inicial',
  desplazamiento: 'deslocamento',
  'ángulo de lanzamiento': 'ângulo de lançamento',
  gravedad: 'gravidade',
  masa: 'massa',
  'coeficiente de fricción': 'coeficiente de atrito',
  'fuerza normal': 'força normal',
  'constante del resorte': 'constante da mola',
  deformación: 'deformação',
  velocidad: 'velocidade',
  fuerza: 'força',
  'ángulo entre F y d': 'ângulo entre F e d',
  trabajo: 'trabalho',
  longitud: 'comprimento',
  'longitud de onda': 'comprimento de onda',
  frecuencia: 'frequência',
  'área': 'área',
  corriente: 'corrente',
  resistencia: 'resistência',
  voltaje: 'tensão',
  moles: 'mols',
  'constante de los gases': 'constante dos gases',
  temperatura: 'temperatura',
  volumen: 'volume',
  'presión inicial': 'pressão inicial',
  'volumen inicial': 'volume inicial',
  'volumen final': 'volume final',
  'temperatura inicial': 'temperatura inicial',
  'temperatura final': 'temperatura final',
  'moles de soluto': 'mols de soluto',
  'volumen de disolución': 'volume da solução',
  'masa de disolvente': 'massa de solvente',
  'concentración inicial': 'concentração inicial',
  'masa de soluto': 'massa de soluto',
  'masa total': 'massa total',
  'concentración de H⁺': 'concentração de H⁺',
  'pH de la disolución': 'pH da solução',
  'masa molar': 'massa molar',
  'número de Avogadro': 'número de Avogadro',
  'producto obtenido': 'produto obtido',
  'producto teórico': 'produto teórico',
  'calor específico': 'calor específico',
  'cambio de temperatura': 'variação de temperatura',
  'calor latente': 'calor latente',
  'entalpía de los productos': 'entalpia dos produtos',
  'entalpía de los reactivos': 'entalpia dos reagentes',
}

/** Unidades escritas con palabras (las de símbolo son universales). */
export const UNIDADES_PT: Record<string, string> = { 'años': 'anos' }
