/**
 * El formulario de fábrica en neerlandés.
 *
 * No se duplican las 54 estructuras: la notación (`tex`, `expresion`, los
 * símbolos) es universal y solo cambian los NOMBRES. Aquí viven esos nombres y
 * `catalogo.ts` arma el catálogo traducido aplicándolos. Los de variable van en
 * un diccionario global porque se repiten mucho («masa» sale en once fórmulas).
 *
 * Lo que no esté traducido se queda en español antes que desaparecer.
 */
import type { AreaFabrica } from './constantes'

export const AREAS_NL: Record<AreaFabrica, string> = {
  matematicas: 'Wiskunde',
  fisica: 'Natuurkunde',
  quimica: 'Scheikunde',
}

export const GRUPOS_NL: Record<string, string> = {
  'Geometría': 'Meetkunde',
  'Álgebra': 'Algebra',
  'Sucesiones': 'Rijen',
  'Trigonometría': 'Goniometrie',
  'Finanzas': 'Financiën',
  'Cinemática': 'Kinematica',
  'Dinámica': 'Dynamica',
  'Energía': 'Energie',
  'Ondas': 'Golven',
  'Electricidad': 'Elektriciteit',
  'Gases': 'Gassen',
  'Disoluciones': 'Oplossingen',
  'Estequiometría': 'Stoichiometrie',
  'Termoquímica': 'Thermochemie',
}

/** Nombre de cada fórmula, por slug. */
export const FORMULAS_NL: Record<string, string> = {
  // Matemáticas
  'area-circulo': 'Oppervlakte van een cirkel',
  circunferencia: 'Omtrek van een cirkel',
  'area-triangulo': 'Oppervlakte van een driehoek',
  'area-trapecio': 'Oppervlakte van een trapezium',
  'volumen-cilindro': 'Volume van een cilinder',
  'volumen-esfera': 'Volume van een bol',
  'volumen-cono': 'Volume van een kegel',
  pitagoras: 'Stelling van Pythagoras',
  'formula-general': 'Abc-formule (positieve wortel)',
  discriminante: 'Discriminant',
  pendiente: 'Richtingscoëfficiënt van een lijn',
  'distancia-puntos': 'Afstand tussen twee punten',
  'cambio-base': 'Grondtalverandering van de logaritme',
  'termino-aritmetica': 'N-de term van een rekenkundige rij',
  'suma-geometrica': 'Som van een meetkundige rij',
  'ley-senos': 'Sinusregel',
  'ley-cosenos': 'Cosinusregel',
  'interes-compuesto': 'Samengestelde rente',
  // Física
  'velocidad-media': 'Gemiddelde snelheid',
  'mrua-velocidad': 'Snelheid bij constante versnelling',
  'mrua-posicion': 'Positie bij constante versnelling',
  torricelli: 'Vergelijking van Torricelli',
  'alcance-tiro': 'Bereik van de schuine worp',
  'segunda-ley': 'Tweede wet van Newton',
  peso: 'Gewicht',
  friccion: 'Wrijvingskracht',
  hooke: 'Wet van Hooke',
  'energia-cinetica': 'Kinetische energie',
  'energia-potencial': 'Zwaarte-energie',
  trabajo: 'Arbeid',
  potencia: 'Vermogen',
  'periodo-pendulo': 'Periode van een enkelvoudige slinger',
  'velocidad-onda': 'Golfsnelheid',
  presion: 'Druk',
  'ley-ohm': 'Wet van Ohm',
  'potencia-electrica': 'Elektrisch vermogen',
  // Química
  'gas-ideal': 'Ideale gaswet (druk)',
  boyle: 'Wet van Boyle',
  charles: 'Wet van Charles',
  'gay-lussac': 'Wet van Gay-Lussac',
  molaridad: 'Molariteit',
  molalidad: 'Molaliteit',
  dilucion: 'Verdunning',
  'porcentaje-masa': 'Massapercentage',
  ph: 'pH',
  poh: 'pOH uit pH',
  moles: 'Aantal mol uit massa',
  'masa-de-moles': 'Massa uit aantal mol',
  'numero-particulas': 'Aantal deeltjes',
  rendimiento: 'Rendement van de reactie',
  'calor-sensible': 'Voelbare warmte',
  'calor-latente': 'Latente warmte',
  densidad: 'Dichtheid',
  'entalpia-reaccion': 'Reactie-enthalpie',
}

/** Nombres de variable, por su texto en español. */
export const VARIABLES_NL: Record<string, string> = {
  radio: 'straal',
  base: 'basis',
  altura: 'hoogte',
  'base mayor': 'grote basis',
  'base menor': 'kleine basis',
  cateto: 'rechthoekszijde',
  'coeficiente cuadrático': 'kwadratische coëfficiënt',
  'coeficiente lineal': 'lineaire coëfficiënt',
  'término independiente': 'constante term',
  'x del primer punto': 'x van het eerste punt',
  'y del primer punto': 'y van het eerste punt',
  'x del segundo punto': 'x van het tweede punt',
  'y del segundo punto': 'y van het tweede punt',
  argumento: 'argument',
  'primer término': 'eerste term',
  posición: 'positie',
  diferencia: 'verschil',
  razón: 'reden',
  'número de términos': 'aantal termen',
  'lado conocido': 'bekende zijde',
  lado: 'zijde',
  'ángulo opuesto a a': 'hoek tegenover a',
  'ángulo opuesto a b': 'hoek tegenover b',
  'ángulo entre a y b': 'hoek tussen a en b',
  'capital inicial': 'beginkapitaal',
  'tasa anual (0.08 = 8 %)': 'jaarlijkse rente (0.08 = 8 %)',
  'capitalizaciones al año': 'kapitalisaties per jaar',
  'años': 'jaar',
  distancia: 'afstand',
  tiempo: 'tijd',
  'velocidad inicial': 'beginsnelheid',
  aceleración: 'versnelling',
  'posición inicial': 'beginpositie',
  desplazamiento: 'verplaatsing',
  'ángulo de lanzamiento': 'lanceerhoek',
  gravedad: 'valversnelling',
  masa: 'massa',
  'coeficiente de fricción': 'wrijvingscoëfficiënt',
  'fuerza normal': 'normaalkracht',
  'constante del resorte': 'veerconstante',
  deformación: 'vervorming',
  velocidad: 'snelheid',
  fuerza: 'kracht',
  'ángulo entre F y d': 'hoek tussen F en d',
  trabajo: 'arbeid',
  longitud: 'lengte',
  'longitud de onda': 'golflengte',
  frecuencia: 'frequentie',
  'área': 'oppervlakte',
  corriente: 'stroomsterkte',
  resistencia: 'weerstand',
  voltaje: 'spanning',
  moles: 'mol',
  'constante de los gases': 'gasconstante',
  temperatura: 'temperatuur',
  volumen: 'volume',
  'presión inicial': 'begindruk',
  'volumen inicial': 'beginvolume',
  'volumen final': 'eindvolume',
  'temperatura inicial': 'begintemperatuur',
  'temperatura final': 'eindtemperatuur',
  'moles de soluto': 'mol opgeloste stof',
  'volumen de disolución': 'volume van de oplossing',
  'masa de disolvente': 'massa van het oplosmiddel',
  'concentración inicial': 'beginconcentratie',
  'masa de soluto': 'massa opgeloste stof',
  'masa total': 'totale massa',
  'concentración de H⁺': 'concentratie H⁺',
  'pH de la disolución': 'pH van de oplossing',
  'masa molar': 'molaire massa',
  'número de Avogadro': 'getal van Avogadro',
  'producto obtenido': 'werkelijke opbrengst',
  'producto teórico': 'theoretische opbrengst',
  'calor específico': 'soortelijke warmte',
  'cambio de temperatura': 'temperatuurverandering',
  'calor latente': 'latente warmte',
  'entalpía de los productos': 'enthalpie van de producten',
  'entalpía de los reactivos': 'enthalpie van de reactanten',
}

/** Unidades escritas con palabras (las de símbolo son universales). */
export const UNIDADES_NL: Record<string, string> = { 'años': 'jaar' }
