/**
 * El formulario de fábrica en chino simplificado.
 *
 * No se duplican las 54 estructuras: la notación (`tex`, `expresion`, los
 * símbolos) es universal y solo cambian los NOMBRES. Aquí viven esos nombres y
 * `catalogo.ts` arma el catálogo traducido aplicándolos. Los de variable van en
 * un diccionario global porque se repiten mucho («masa» sale en once fórmulas).
 *
 * Lo que no esté traducido se queda en español antes que desaparecer.
 */
import type { AreaFabrica } from './constantes'

export const AREAS_ZH: Record<AreaFabrica, string> = {
  matematicas: '数学',
  fisica: '物理',
  quimica: '化学',
}

export const GRUPOS_ZH: Record<string, string> = {
  'Geometría': '几何',
  'Álgebra': '代数',
  'Sucesiones': '数列',
  'Trigonometría': '三角学',
  'Finanzas': '金融',
  'Cinemática': '运动学',
  'Dinámica': '动力学',
  'Energía': '能量',
  'Ondas': '波动',
  'Electricidad': '电学',
  'Gases': '气体',
  'Disoluciones': '溶液',
  'Estequiometría': '化学计量',
  'Termoquímica': '热化学',
}

/** Nombre de cada fórmula, por slug. */
export const FORMULAS_ZH: Record<string, string> = {
  // Matemáticas
  'area-circulo': '圆的面积',
  circunferencia: '圆周长',
  'area-triangulo': '三角形的面积',
  'area-trapecio': '梯形的面积',
  'volumen-cilindro': '圆柱的体积',
  'volumen-esfera': '球的体积',
  'volumen-cono': '圆锥的体积',
  pitagoras: '勾股定理',
  'formula-general': '求根公式（正根）',
  discriminante: '判别式',
  pendiente: '直线的斜率',
  'distancia-puntos': '两点间的距离',
  'cambio-base': '对数换底公式',
  'termino-aritmetica': '等差数列的通项公式',
  'suma-geometrica': '等比数列的求和公式',
  'ley-senos': '正弦定理',
  'ley-cosenos': '余弦定理',
  'interes-compuesto': '复利',
  // Física
  'velocidad-media': '平均速度',
  'mrua-velocidad': '匀加速直线运动的速度',
  'mrua-posicion': '匀加速直线运动的位置',
  torricelli: '托里拆利公式',
  'alcance-tiro': '斜抛运动的射程',
  'segunda-ley': '牛顿第二定律',
  peso: '重力',
  friccion: '摩擦力',
  hooke: '胡克定律',
  'energia-cinetica': '动能',
  'energia-potencial': '重力势能',
  trabajo: '功',
  potencia: '功率',
  'periodo-pendulo': '单摆的周期',
  'velocidad-onda': '波速',
  presion: '压强',
  'ley-ohm': '欧姆定律',
  'potencia-electrica': '电功率',
  // Química
  'gas-ideal': '理想气体状态方程（压强）',
  boyle: '玻意耳定律',
  charles: '查理定律',
  'gay-lussac': '盖·吕萨克定律',
  molaridad: '摩尔浓度',
  molalidad: '质量摩尔浓度',
  dilucion: '稀释',
  'porcentaje-masa': '质量分数',
  ph: 'pH',
  poh: '由pH求pOH',
  moles: '由质量求摩尔数',
  'masa-de-moles': '由摩尔数求质量',
  'numero-particulas': '粒子数',
  rendimiento: '反应产率',
  'calor-sensible': '显热',
  'calor-latente': '潜热',
  densidad: '密度',
  'entalpia-reaccion': '反应焓变',
}

/** Nombres de variable, por su texto en español. */
export const VARIABLES_ZH: Record<string, string> = {
  radio: '半径',
  base: '底',
  altura: '高',
  'base mayor': '下底',
  'base menor': '上底',
  cateto: '直角边',
  'coeficiente cuadrático': '二次项系数',
  'coeficiente lineal': '一次项系数',
  'término independiente': '常数项',
  'x del primer punto': '第一个点的x',
  'y del primer punto': '第一个点的y',
  'x del segundo punto': '第二个点的x',
  'y del segundo punto': '第二个点的y',
  argumento: '真数',
  'primer término': '首项',
  posición: '序号',
  diferencia: '公差',
  razón: '公比',
  'número de términos': '项数',
  'lado conocido': '已知边',
  lado: '边',
  'ángulo opuesto a a': '边a的对角',
  'ángulo opuesto a b': '边b的对角',
  'ángulo entre a y b': '边a与边b之间的夹角',
  'capital inicial': '本金',
  'tasa anual (0.08 = 8 %)': '年利率 (0.08 = 8%)',
  'capitalizaciones al año': '每年复利次数',
  'años': '年',
  distancia: '距离',
  tiempo: '时间',
  'velocidad inicial': '初速度',
  aceleración: '加速度',
  'posición inicial': '初始位置',
  desplazamiento: '位移',
  'ángulo de lanzamiento': '发射角',
  gravedad: '重力加速度',
  masa: '质量',
  'coeficiente de fricción': '摩擦系数',
  'fuerza normal': '支持力',
  'constante del resorte': '弹簧常数',
  deformación: '形变量',
  velocidad: '速度',
  fuerza: '力',
  'ángulo entre F y d': '力F与位移d之间的夹角',
  trabajo: '功',
  longitud: '长度',
  'longitud de onda': '波长',
  frecuencia: '频率',
  'área': '面积',
  corriente: '电流',
  resistencia: '电阻',
  voltaje: '电压',
  moles: '摩尔数',
  'constante de los gases': '气体常数',
  temperatura: '温度',
  volumen: '体积',
  'presión inicial': '初始压强',
  'volumen inicial': '初始体积',
  'volumen final': '最终体积',
  'temperatura inicial': '初始温度',
  'temperatura final': '最终温度',
  'moles de soluto': '溶质的摩尔数',
  'volumen de disolución': '溶液的体积',
  'masa de disolvente': '溶剂的质量',
  'concentración inicial': '初始浓度',
  'masa de soluto': '溶质的质量',
  'masa total': '总质量',
  'concentración de H⁺': '氢离子浓度',
  'pH de la disolución': '溶液的pH',
  'masa molar': '摩尔质量',
  'número de Avogadro': '阿伏加德罗常数',
  'producto obtenido': '实际产量',
  'producto teórico': '理论产量',
  'calor específico': '比热容',
  'cambio de temperatura': '温度变化',
  'calor latente': '潜热',
  'entalpía de los productos': '生成物的焓',
  'entalpía de los reactivos': '反应物的焓',
}

/** Unidades escritas con palabras (las de símbolo son universales). */
export const UNIDADES_ZH: Record<string, string> = { 'años': '年' }
