/**
 * El formulario de fábrica en japonés.
 *
 * No se duplican las 54 estructuras: la notación (`tex`, `expresion`, los
 * símbolos) es universal y solo cambian los NOMBRES. Aquí viven esos nombres y
 * `catalogo.ts` arma el catálogo traducido aplicándolos. Los de variable van en
 * un diccionario global porque se repiten mucho («masa» sale en once fórmulas).
 *
 * Lo que no esté traducido se queda en español antes que desaparecer.
 */
import type { AreaFabrica } from './constantes'

export const AREAS_JA: Record<AreaFabrica, string> = {
  matematicas: '数学',
  fisica: '物理',
  quimica: '化学',
}

export const GRUPOS_JA: Record<string, string> = {
  'Geometría': '幾何',
  'Álgebra': '代数',
  'Sucesiones': '数列',
  'Trigonometría': '三角法',
  'Finanzas': '金融',
  'Cinemática': '運動学',
  'Dinámica': '動力学',
  'Energía': 'エネルギー',
  'Ondas': '波動',
  'Electricidad': '電気',
  'Gases': '気体',
  'Disoluciones': '溶液',
  'Estequiometría': '化学量論',
  'Termoquímica': '熱化学',
}

/** Nombre de cada fórmula, por slug. */
export const FORMULAS_JA: Record<string, string> = {
  // Matemáticas
  'area-circulo': '円の面積',
  circunferencia: '円周',
  'area-triangulo': '三角形の面積',
  'area-trapecio': '台形の面積',
  'volumen-cilindro': '円柱の体積',
  'volumen-esfera': '球の体積',
  'volumen-cono': '円錐の体積',
  pitagoras: '三平方の定理',
  'formula-general': '解の公式（正の解）',
  discriminante: '判別式',
  pendiente: '直線の傾き',
  'distancia-puntos': '2点間の距離',
  'cambio-base': '対数の底の変換',
  'termino-aritmetica': '等差数列の一般項',
  'suma-geometrica': '等比数列の和',
  'ley-senos': '正弦定理',
  'ley-cosenos': '余弦定理',
  'interes-compuesto': '複利',
  // Física
  'velocidad-media': '平均速度',
  'mrua-velocidad': '等加速度直線運動の速度',
  'mrua-posicion': '等加速度直線運動の位置',
  torricelli: 'トリチェリの式',
  'alcance-tiro': '斜方投射の飛距離',
  'segunda-ley': 'ニュートンの運動方程式',
  peso: '重力',
  friccion: '摩擦力',
  hooke: 'フックの法則',
  'energia-cinetica': '運動エネルギー',
  'energia-potencial': '重力による位置エネルギー',
  trabajo: '仕事',
  potencia: '仕事率',
  'periodo-pendulo': '単振り子の周期',
  'velocidad-onda': '波の速さ',
  presion: '圧力',
  'ley-ohm': 'オームの法則',
  'potencia-electrica': '電力',
  // Química
  'gas-ideal': '理想気体の状態方程式（圧力）',
  boyle: 'ボイルの法則',
  charles: 'シャルルの法則',
  'gay-lussac': 'ゲイ・リュサックの法則',
  molaridad: 'モル濃度',
  molalidad: '質量モル濃度',
  dilucion: '希釈',
  'porcentaje-masa': '質量パーセント濃度',
  ph: 'pH',
  poh: 'pHからのpOH',
  moles: '質量からのモル数',
  'masa-de-moles': 'モル数からの質量',
  'numero-particulas': '粒子の数',
  rendimiento: '反応の収率',
  'calor-sensible': '顕熱',
  'calor-latente': '潜熱',
  densidad: '密度',
  'entalpia-reaccion': '反応エンタルピー変化',
}

/** Nombres de variable, por su texto en español. */
export const VARIABLES_JA: Record<string, string> = {
  radio: '半径',
  base: '底',
  altura: '高さ',
  'base mayor': '下底',
  'base menor': '上底',
  cateto: '直角を挟む辺',
  'coeficiente cuadrático': '2次の係数',
  'coeficiente lineal': '1次の係数',
  'término independiente': '定数項',
  'x del primer punto': '1点目のx',
  'y del primer punto': '1点目のy',
  'x del segundo punto': '2点目のx',
  'y del segundo punto': '2点目のy',
  argumento: '真数',
  'primer término': '初項',
  posición: '項番号',
  diferencia: '公差',
  razón: '公比',
  'número de términos': '項数',
  'lado conocido': '既知の辺',
  lado: '辺',
  'ángulo opuesto a a': '辺aの対角',
  'ángulo opuesto a b': '辺bの対角',
  'ángulo entre a y b': '辺aと辺bの間の角',
  'capital inicial': '元金',
  'tasa anual (0.08 = 8 %)': '年利率 (0.08 = 8%)',
  'capitalizaciones al año': '年間の複利計算回数',
  'años': '年',
  distancia: '距離',
  tiempo: '時間',
  'velocidad inicial': '初速度',
  aceleración: '加速度',
  'posición inicial': '初期位置',
  desplazamiento: '変位',
  'ángulo de lanzamiento': '打ち出し角',
  gravedad: '重力加速度',
  masa: '質量',
  'coeficiente de fricción': '摩擦係数',
  'fuerza normal': '垂直抗力',
  'constante del resorte': 'ばね定数',
  deformación: '変形量',
  velocidad: '速度',
  fuerza: '力',
  'ángulo entre F y d': '力Fと変位dの間の角',
  trabajo: '仕事',
  longitud: '長さ',
  'longitud de onda': '波長',
  frecuencia: '振動数',
  'área': '面積',
  corriente: '電流',
  resistencia: '抵抗',
  voltaje: '電圧',
  moles: 'モル数',
  'constante de los gases': '気体定数',
  temperatura: '温度',
  volumen: '体積',
  'presión inicial': '初期圧力',
  'volumen inicial': '初期体積',
  'volumen final': '最終体積',
  'temperatura inicial': '初期温度',
  'temperatura final': '最終温度',
  'moles de soluto': '溶質のモル数',
  'volumen de disolución': '溶液の体積',
  'masa de disolvente': '溶媒の質量',
  'concentración inicial': '初期濃度',
  'masa de soluto': '溶質の質量',
  'masa total': '総質量',
  'concentración de H⁺': '水素イオン濃度',
  'pH de la disolución': '溶液のpH',
  'masa molar': 'モル質量',
  'número de Avogadro': 'アボガドロ定数',
  'producto obtenido': '実収量',
  'producto teórico': '理論収量',
  'calor específico': '比熱',
  'cambio de temperatura': '温度変化',
  'calor latente': '潜熱',
  'entalpía de los productos': '生成物のエンタルピー',
  'entalpía de los reactivos': '反応物のエンタルピー',
}

/** Unidades escritas con palabras (las de símbolo son universales). */
export const UNIDADES_JA: Record<string, string> = { 'años': '年' }
