/**
 * El formulario de fábrica en alemán.
 *
 * No se duplican las 54 estructuras: la notación (`tex`, `expresion`, los
 * símbolos) es universal y solo cambian los NOMBRES. Aquí viven esos nombres y
 * `catalogo.ts` arma el catálogo traducido aplicándolos. Los de variable van en
 * un diccionario global porque se repiten mucho («masa» sale en once fórmulas).
 *
 * Lo que no esté traducido se queda en español antes que desaparecer.
 */
import type { AreaFabrica } from './constantes'

export const AREAS_DE: Record<AreaFabrica, string> = {
  matematicas: 'Mathematik',
  fisica: 'Physik',
  quimica: 'Chemie',
}

export const GRUPOS_DE: Record<string, string> = {
  'Geometría': 'Geometrie',
  'Álgebra': 'Algebra',
  'Sucesiones': 'Folgen',
  'Trigonometría': 'Trigonometrie',
  'Finanzas': 'Finanzen',
  'Cinemática': 'Kinematik',
  'Dinámica': 'Dynamik',
  'Energía': 'Energie',
  'Ondas': 'Wellen',
  'Electricidad': 'Elektrizität',
  'Gases': 'Gase',
  'Disoluciones': 'Lösungen',
  'Estequiometría': 'Stöchiometrie',
  'Termoquímica': 'Thermochemie',
}

/** Nombre de cada fórmula, por slug. */
export const FORMULAS_DE: Record<string, string> = {
  // Matemáticas
  'area-circulo': 'Kreisfläche',
  circunferencia: 'Umfang',
  'area-triangulo': 'Dreiecksfläche',
  'area-trapecio': 'Trapezfläche',
  'volumen-cilindro': 'Zylindervolumen',
  'volumen-esfera': 'Kugelvolumen',
  'volumen-cono': 'Kegelvolumen',
  pitagoras: 'Satz des Pythagoras',
  'formula-general': 'Mitternachtsformel (positive Lösung)',
  discriminante: 'Diskriminante',
  pendiente: 'Steigung einer Geraden',
  'distancia-puntos': 'Abstand zweier Punkte',
  'cambio-base': 'Basiswechsel des Logarithmus',
  'termino-aritmetica': 'n-tes Glied einer arithmetischen Folge',
  'suma-geometrica': 'Summe einer geometrischen Folge',
  'ley-senos': 'Sinussatz',
  'ley-cosenos': 'Kosinussatz',
  'interes-compuesto': 'Zinseszins',
  // Física
  'velocidad-media': 'Durchschnittsgeschwindigkeit',
  'mrua-velocidad': 'Geschwindigkeit bei konstanter Beschleunigung',
  'mrua-posicion': 'Ort bei konstanter Beschleunigung',
  torricelli: 'Torricelli-Gleichung',
  'alcance-tiro': 'Wurfweite beim schrägen Wurf',
  'segunda-ley': 'Zweites Newtonsches Gesetz',
  peso: 'Gewichtskraft',
  friccion: 'Reibungskraft',
  hooke: 'Hookesches Gesetz',
  'energia-cinetica': 'Kinetische Energie',
  'energia-potencial': 'Potenzielle Energie (Gravitation)',
  trabajo: 'Arbeit',
  potencia: 'Leistung',
  'periodo-pendulo': 'Schwingungsdauer des Fadenpendels',
  'velocidad-onda': 'Wellengeschwindigkeit',
  presion: 'Druck',
  'ley-ohm': 'Ohmsches Gesetz',
  'potencia-electrica': 'Elektrische Leistung',
  // Química
  'gas-ideal': 'Ideales Gasgesetz (Druck)',
  boyle: 'Gesetz von Boyle-Mariotte',
  charles: 'Gesetz von Charles',
  'gay-lussac': 'Gesetz von Gay-Lussac',
  molaridad: 'Molarität',
  molalidad: 'Molalität',
  dilucion: 'Verdünnung',
  'porcentaje-masa': 'Massenprozent',
  ph: 'pH-Wert',
  poh: 'pOH aus dem pH-Wert',
  moles: 'Stoffmenge aus der Masse',
  'masa-de-moles': 'Masse aus der Stoffmenge',
  'numero-particulas': 'Anzahl der Teilchen',
  rendimiento: 'Reaktionsausbeute',
  'calor-sensible': 'Sensible Wärme',
  'calor-latente': 'Latente Wärme',
  densidad: 'Dichte',
  'entalpia-reaccion': 'Reaktionsenthalpie',
}

/** Nombres de variable, por su texto en español. */
export const VARIABLES_DE: Record<string, string> = {
  radio: 'Radius',
  base: 'Basis',
  altura: 'Höhe',
  'base mayor': 'große Basis',
  'base menor': 'kleine Basis',
  cateto: 'Kathete',
  'coeficiente cuadrático': 'quadratischer Koeffizient',
  'coeficiente lineal': 'linearer Koeffizient',
  'término independiente': 'konstantes Glied',
  'x del primer punto': 'x des ersten Punkts',
  'y del primer punto': 'y des ersten Punkts',
  'x del segundo punto': 'x des zweiten Punkts',
  'y del segundo punto': 'y des zweiten Punkts',
  argumento: 'Argument',
  'primer término': 'erstes Glied',
  posición: 'Position',
  diferencia: 'gemeinsame Differenz',
  razón: 'gemeinsamer Quotient',
  'número de términos': 'Anzahl der Glieder',
  'lado conocido': 'bekannte Seite',
  lado: 'Seite',
  'ángulo opuesto a a': 'Winkel gegenüber a',
  'ángulo opuesto a b': 'Winkel gegenüber b',
  'ángulo entre a y b': 'Winkel zwischen a und b',
  'capital inicial': 'Anfangskapital',
  'tasa anual (0.08 = 8 %)': 'Jahreszins (0.08 = 8 %)',
  'capitalizaciones al año': 'Zinsperioden pro Jahr',
  'años': 'Jahre',
  distancia: 'Strecke',
  tiempo: 'Zeit',
  'velocidad inicial': 'Anfangsgeschwindigkeit',
  aceleración: 'Beschleunigung',
  'posición inicial': 'Anfangsposition',
  desplazamiento: 'Verschiebung',
  'ángulo de lanzamiento': 'Abwurfwinkel',
  gravedad: 'Erdbeschleunigung',
  masa: 'Masse',
  'coeficiente de fricción': 'Reibungskoeffizient',
  'fuerza normal': 'Normalkraft',
  'constante del resorte': 'Federkonstante',
  deformación: 'Auslenkung',
  velocidad: 'Geschwindigkeit',
  fuerza: 'Kraft',
  'ángulo entre F y d': 'Winkel zwischen F und d',
  trabajo: 'Arbeit',
  longitud: 'Länge',
  'longitud de onda': 'Wellenlänge',
  frecuencia: 'Frequenz',
  'área': 'Fläche',
  corriente: 'Stromstärke',
  resistencia: 'Widerstand',
  voltaje: 'Spannung',
  moles: 'Stoffmenge',
  'constante de los gases': 'Gaskonstante',
  temperatura: 'Temperatur',
  volumen: 'Volumen',
  'presión inicial': 'Anfangsdruck',
  'volumen inicial': 'Anfangsvolumen',
  'volumen final': 'Endvolumen',
  'temperatura inicial': 'Anfangstemperatur',
  'temperatura final': 'Endtemperatur',
  'moles de soluto': 'Stoffmenge des gelösten Stoffs',
  'volumen de disolución': 'Volumen der Lösung',
  'masa de disolvente': 'Masse des Lösungsmittels',
  'concentración inicial': 'Anfangskonzentration',
  'masa de soluto': 'Masse des gelösten Stoffs',
  'masa total': 'Gesamtmasse',
  'concentración de H⁺': 'H⁺-Konzentration',
  'pH de la disolución': 'pH-Wert der Lösung',
  'masa molar': 'molare Masse',
  'número de Avogadro': 'Avogadro-Konstante',
  'producto obtenido': 'tatsächliche Ausbeute',
  'producto teórico': 'theoretische Ausbeute',
  'calor específico': 'spezifische Wärmekapazität',
  'cambio de temperatura': 'Temperaturänderung',
  'calor latente': 'latente Wärme',
  'entalpía de los productos': 'Enthalpie der Produkte',
  'entalpía de los reactivos': 'Enthalpie der Edukte',
}

/** Unidades escritas con palabras (las de símbolo son universales). */
export const UNIDADES_DE: Record<string, string> = { 'años': 'Jahre' }
