/**
 * El formulario de fábrica en hindi.
 *
 * No se duplican las 54 estructuras: la notación (`tex`, `expresion`, los
 * símbolos) es universal y solo cambian los NOMBRES. Aquí viven esos nombres y
 * `catalogo.ts` arma el catálogo traducido aplicándolos. Los de variable van en
 * un diccionario global porque se repiten mucho («masa» sale en once fórmulas).
 *
 * Lo que no esté traducido se queda en español antes que desaparecer.
 */
import type { AreaFabrica } from './constantes'

export const AREAS_HI: Record<AreaFabrica, string> = {
  matematicas: 'गणित',
  fisica: 'भौतिकी',
  quimica: 'रसायन विज्ञान',
}

export const GRUPOS_HI: Record<string, string> = {
  'Geometría': 'ज्यामिति',
  'Álgebra': 'बीजगणित',
  'Sucesiones': 'अनुक्रम',
  'Trigonometría': 'त्रिकोणमिति',
  'Finanzas': 'वित्त',
  'Cinemática': 'गतिकी',
  'Dinámica': 'बलगतिकी',
  'Energía': 'ऊर्जा',
  'Ondas': 'तरंगें',
  'Electricidad': 'विद्युत',
  'Gases': 'गैसें',
  'Disoluciones': 'विलयन',
  'Estequiometría': 'रससमीकरणमिति',
  'Termoquímica': 'ऊष्मारसायन',
}

/** Nombre de cada fórmula, por slug. */
export const FORMULAS_HI: Record<string, string> = {
  // Matemáticas
  'area-circulo': 'वृत्त का क्षेत्रफल',
  circunferencia: 'वृत्त की परिधि',
  'area-triangulo': 'त्रिभुज का क्षेत्रफल',
  'area-trapecio': 'समलंब का क्षेत्रफल',
  'volumen-cilindro': 'बेलन का आयतन',
  'volumen-esfera': 'गोले का आयतन',
  'volumen-cono': 'शंकु का आयतन',
  pitagoras: 'पाइथागोरस प्रमेय',
  'formula-general': 'द्विघात सूत्र (धनात्मक मूल)',
  discriminante: 'विविक्तकर',
  pendiente: 'रेखा का ढाल',
  'distancia-puntos': 'दो बिंदुओं के बीच की दूरी',
  'cambio-base': 'लघुगणक के आधार में परिवर्तन',
  'termino-aritmetica': 'समांतर श्रेढ़ी का n-वां पद',
  'suma-geometrica': 'गुणोत्तर श्रेढ़ी का योग',
  'ley-senos': 'ज्या नियम',
  'ley-cosenos': 'कोज्या नियम',
  'interes-compuesto': 'चक्रवृद्धि ब्याज',
  // Física
  'velocidad-media': 'औसत वेग',
  'mrua-velocidad': 'नियत त्वरण में वेग',
  'mrua-posicion': 'नियत त्वरण में स्थिति',
  torricelli: 'टॉरिसेली का समीकरण',
  'alcance-tiro': 'प्रक्षेप्य गति का परास',
  'segunda-ley': 'न्यूटन का द्वितीय नियम',
  peso: 'भार',
  friccion: 'घर्षण बल',
  hooke: 'हुक का नियम',
  'energia-cinetica': 'गतिज ऊर्जा',
  'energia-potencial': 'गुरुत्वीय स्थितिज ऊर्जा',
  trabajo: 'कार्य',
  potencia: 'शक्ति',
  'periodo-pendulo': 'सरल लोलक का आवर्तकाल',
  'velocidad-onda': 'तरंग का वेग',
  presion: 'दाब',
  'ley-ohm': 'ओम का नियम',
  'potencia-electrica': 'विद्युत शक्ति',
  // Química
  'gas-ideal': 'आदर्श गैस नियम (दाब)',
  boyle: 'बॉयल का नियम',
  charles: 'चार्ल्स का नियम',
  'gay-lussac': 'गे-लुसाक का नियम',
  molaridad: 'मोलरता',
  molalidad: 'मोललता',
  dilucion: 'तनुकरण',
  'porcentaje-masa': 'द्रव्यमान प्रतिशत',
  ph: 'pH',
  poh: 'pH से pOH',
  moles: 'द्रव्यमान से मोलों की संख्या',
  'masa-de-moles': 'मोलों से द्रव्यमान',
  'numero-particulas': 'कणों की संख्या',
  rendimiento: 'अभिक्रिया की उपज',
  'calor-sensible': 'संवेद्य ऊष्मा',
  'calor-latente': 'गुप्त ऊष्मा',
  densidad: 'घनत्व',
  'entalpia-reaccion': 'अभिक्रिया की एन्थैल्पी',
}

/** Nombres de variable, por su texto en español. */
export const VARIABLES_HI: Record<string, string> = {
  radio: 'त्रिज्या',
  base: 'आधार',
  altura: 'ऊंचाई',
  'base mayor': 'बड़ा आधार',
  'base menor': 'छोटा आधार',
  cateto: 'भुजा',
  'coeficiente cuadrático': 'द्विघात गुणांक',
  'coeficiente lineal': 'रैखिक गुणांक',
  'término independiente': 'अचर पद',
  'x del primer punto': 'पहले बिंदु का x',
  'y del primer punto': 'पहले बिंदु का y',
  'x del segundo punto': 'दूसरे बिंदु का x',
  'y del segundo punto': 'दूसरे बिंदु का y',
  argumento: 'मान',
  'primer término': 'प्रथम पद',
  posición: 'स्थिति',
  diferencia: 'सार्व अंतर',
  razón: 'सार्व अनुपात',
  'número de términos': 'पदों की संख्या',
  'lado conocido': 'ज्ञात भुजा',
  lado: 'भुजा',
  'ángulo opuesto a a': 'a के सम्मुख कोण',
  'ángulo opuesto a b': 'b के सम्मुख कोण',
  'ángulo entre a y b': 'a और b के बीच का कोण',
  'capital inicial': 'मूलधन',
  'tasa anual (0.08 = 8 %)': 'वार्षिक दर (0.08 = 8 %)',
  'capitalizaciones al año': 'प्रति वर्ष चक्रवृद्धि की संख्या',
  'años': 'वर्ष',
  distancia: 'दूरी',
  tiempo: 'समय',
  'velocidad inicial': 'प्रारंभिक वेग',
  aceleración: 'त्वरण',
  'posición inicial': 'प्रारंभिक स्थिति',
  desplazamiento: 'विस्थापन',
  'ángulo de lanzamiento': 'प्रक्षेपण कोण',
  gravedad: 'गुरुत्वीय त्वरण',
  masa: 'द्रव्यमान',
  'coeficiente de fricción': 'घर्षण गुणांक',
  'fuerza normal': 'अभिलंब बल',
  'constante del resorte': 'स्प्रिंग नियतांक',
  deformación: 'विरूपण',
  velocidad: 'वेग',
  fuerza: 'बल',
  'ángulo entre F y d': 'F और d के बीच का कोण',
  trabajo: 'कार्य',
  longitud: 'लंबाई',
  'longitud de onda': 'तरंगदैर्घ्य',
  frecuencia: 'आवृत्ति',
  'área': 'क्षेत्रफल',
  corriente: 'विद्युत धारा',
  resistencia: 'प्रतिरोध',
  voltaje: 'वोल्टता',
  moles: 'मोलों की संख्या',
  'constante de los gases': 'गैस स्थिरांक',
  temperatura: 'ताप',
  volumen: 'आयतन',
  'presión inicial': 'प्रारंभिक दाब',
  'volumen inicial': 'प्रारंभिक आयतन',
  'volumen final': 'अंतिम आयतन',
  'temperatura inicial': 'प्रारंभिक ताप',
  'temperatura final': 'अंतिम ताप',
  'moles de soluto': 'विलेय के मोलों की संख्या',
  'volumen de disolución': 'विलयन का आयतन',
  'masa de disolvente': 'विलायक का द्रव्यमान',
  'concentración inicial': 'प्रारंभिक सांद्रता',
  'masa de soluto': 'विलेय का द्रव्यमान',
  'masa total': 'कुल द्रव्यमान',
  'concentración de H⁺': 'H⁺ की सांद्रता',
  'pH de la disolución': 'विलयन का pH',
  'masa molar': 'मोलर द्रव्यमान',
  'número de Avogadro': 'आवोगाद्रो संख्या',
  'producto obtenido': 'वास्तविक उपज',
  'producto teórico': 'सैद्धांतिक उपज',
  'calor específico': 'विशिष्ट ऊष्मा धारिता',
  'cambio de temperatura': 'ताप परिवर्तन',
  'calor latente': 'गुप्त ऊष्मा',
  'entalpía de los productos': 'उत्पादों की एन्थैल्पी',
  'entalpía de los reactivos': 'अभिकारकों की एन्थैल्पी',
}

/** Unidades escritas con palabras (las de símbolo son universales). */
export const UNIDADES_HI: Record<string, string> = { 'años': 'वर्ष' }
