import type { PorIdioma } from '../../core/i18n/porIdioma'
/**
 * El programa «clásicos de ciencia ficción por ver» de Pep@, escrito a mano.
 *
 * Va aparte del contenido generado a propósito: el generador trocea el año en
 * dos llamadas y solo sabe concatenar arrays de primer nivel, así que un
 * objeto como este llegaba siempre a medias. Son diez títulos canónicos —
 * escribirlos cuesta menos que pelearse con el troceo.
 */
export interface ItemPrograma {
  titulo: string
  detalle: string
}

export const PROGRAMA_DEMO: PorIdioma<{ nombre: string; items: ItemPrograma[] }> = {
  es: {
    nombre: 'Clásicos de ciencia ficción pendientes',
    items: [
      { titulo: 'Solaris (1972)', detalle: 'Me la recomendaron cuando dije que Blade Runner me había dejado triste.' },
      { titulo: 'Stalker (1979)', detalle: 'Dicen que es lenta y que ese es justo el punto.' },
      { titulo: '2001: Una odisea del espacio', detalle: 'La he visto a trozos en clase de física; toca completa y sin pausas.' },
      { titulo: 'Metrópolis (1927)', detalle: 'Todo lo que me gusta del género sale de aquí, y no la he visto.' },
      { titulo: 'Primer (2004)', detalle: 'Rodada con casi nada de presupuesto; quiero ver hasta dónde llega la idea.' },
      { titulo: 'La llegada', detalle: 'Va de cómo el idioma te cambia la cabeza. Justo ahora que estudio uno.' },
      { titulo: 'Gattaca', detalle: 'Me la puso mi profesor de laboratorio como ejemplo de ética.' },
      { titulo: 'Akira', detalle: 'Después de Japón tengo pendiente el anime que todo el mundo cita.' },
      { titulo: 'Contact', detalle: 'Sagan otra vez: si el libro me gustó, la película debería.' },
      { titulo: 'Moon (2009)', detalle: 'Una sola persona, una base y una idea. Suena a mi tipo de película.' },
    ],
  },
  en: {
    nombre: 'Sci-fi classics to watch',
    items: [
      { titulo: 'Solaris (1972)', detalle: 'Someone recommended it when I said Blade Runner had left me sad.' },
      { titulo: 'Stalker (1979)', detalle: 'They say it is slow and that this is exactly the point.' },
      { titulo: '2001: A Space Odyssey', detalle: 'I have seen bits of it in physics class; time to watch it whole.' },
      { titulo: 'Metropolis (1927)', detalle: 'Everything I love about the genre comes from here, and I have not seen it.' },
      { titulo: 'Primer (2004)', detalle: 'Shot on almost no budget; I want to see how far the idea goes.' },
      { titulo: 'Arrival', detalle: 'It is about how language rewires you. Right while I am learning one.' },
      { titulo: 'Gattaca', detalle: 'My lab professor showed it to us as an ethics case.' },
      { titulo: 'Akira', detalle: 'After Japan I owe myself the anime everyone quotes.' },
      { titulo: 'Contact', detalle: 'Sagan again: if I liked the book, the film should land.' },
      { titulo: 'Moon (2009)', detalle: 'One person, one base, one idea. Sounds like my kind of film.' },
    ],
  },
  pt: {
    nombre: 'Clássicos de ficção científica pendentes',
    items: [
      { titulo: 'Solaris (1972)', detalle: 'Recomendaram quando eu disse que Blade Runner tinha me deixado triste.' },
      { titulo: 'Stalker (1979)', detalle: 'Dizem que é lento e que esse é exatamente o ponto.' },
      { titulo: '2001: Uma Odisseia no Espaço', detalle: 'Já vi pedaços dele na aula de física; hora de assistir inteiro e sem pausas.' },
      { titulo: 'Metropolis (1927)', detalle: 'Tudo que eu amo no gênero vem daqui, e eu nunca vi.' },
      { titulo: 'Primer (2004)', detalle: 'Filmado com quase nenhum orçamento; quero ver até onde a ideia vai.' },
      { titulo: 'A Chegada', detalle: 'É sobre como o idioma muda sua cabeça. Bem na hora em que estou estudando um.' },
      { titulo: 'Gattaca', detalle: 'Meu professor de laboratório mostrou como exemplo de ética.' },
      { titulo: 'Akira', detalle: 'Depois do Japão, falta assistir ao anime que todo mundo cita.' },
      { titulo: 'Contato', detalle: 'Sagan de novo: se gostei do livro, o filme deve entregar.' },
      { titulo: 'Moon (2009)', detalle: 'Uma pessoa só, uma base e uma ideia. Parece o tipo de filme que eu gosto.' },
    ],
  },
  fr: {
    nombre: 'Classiques de science-fiction à voir',
    items: [
      { titulo: 'Solaris (1972)', detalle: "On me l'a conseillé le jour où j'ai dit que Blade Runner m'avait laissé un goût triste." },
      { titulo: 'Stalker (1979)', detalle: "On dit que c'est lent et que c'est justement le but." },
      { titulo: "2001 : l'Odyssée de l'espace", detalle: 'Vu par bouts en cours de physique ; il est temps de le voir en entier, sans pause.' },
      { titulo: 'Metropolis (1927)', detalle: "Tout ce que j'aime dans ce genre vient de là, et je ne l'ai jamais vu." },
      { titulo: 'Primer (2004)', detalle: "Tourné avec presque aucun budget ; je veux voir jusqu'où l'idée va." },
      { titulo: 'Premier Contact', detalle: "Ça parle de comment la langue change ta façon de penser. Juste au moment où j'en apprends une." },
      { titulo: 'Gattaca', detalle: "Mon prof de labo l'a montré comme exemple d'éthique." },
      { titulo: 'Akira', detalle: 'Après le Japon, il me reste cet anime que tout le monde cite.' },
      { titulo: 'Contact', detalle: "Sagan encore : si le livre m'a plu, le film devrait aussi." },
      { titulo: 'Moon (2009)', detalle: "Une seule personne, une base et une idée. Ça ressemble au genre de film que j'aime." },
    ],
  },
  de: {
    nombre: 'Ausstehende Science-Fiction-Klassiker',
    items: [
      { titulo: 'Solaris (1972)', detalle: 'Jemand hat ihn mir empfohlen, als ich sagte, dass mich Blade Runner traurig gemacht hat.' },
      { titulo: 'Stalker (1979)', detalle: 'Man sagt, er sei langsam, und genau das sei der Punkt.' },
      { titulo: '2001: Odyssee im Weltraum', detalle: 'Ich habe ihn in Bruchstücken im Physikunterricht gesehen; Zeit, ihn ganz und ohne Pause zu sehen.' },
      { titulo: 'Metropolis (1927)', detalle: 'Alles, was ich am Genre liebe, kommt von hier, und ich habe ihn noch nie gesehen.' },
      { titulo: 'Primer (2004)', detalle: 'Mit fast keinem Budget gedreht; ich will sehen, wie weit die Idee trägt.' },
      { titulo: 'Arrival', detalle: 'Es geht darum, wie Sprache das Denken verändert. Genau jetzt, wo ich eine lerne.' },
      { titulo: 'Gattaca', detalle: 'Mein Laborprofessor hat ihn als Beispiel für Ethik gezeigt.' },
      { titulo: 'Akira', detalle: 'Nach Japan schulde ich mir noch den Anime, den alle zitieren.' },
      { titulo: 'Contact', detalle: 'Wieder Sagan: Wenn mir das Buch gefallen hat, sollte es auch der Film.' },
      { titulo: 'Moon (2009)', detalle: 'Eine einzige Person, eine Basis und eine Idee. Klingt nach meiner Art Film.' },
    ],
  },
  it: {
    nombre: 'Classici di fantascienza da vedere',
    items: [
      { titulo: 'Solaris (1972)', detalle: "Me l'hanno consigliato quando ho detto che Blade Runner mi aveva lasciato triste." },
      { titulo: 'Stalker (1979)', detalle: 'Dicono che sia lento e che il punto sia proprio quello.' },
      { titulo: '2001: Odissea nello spazio', detalle: "L'ho visto a pezzi a fisica; è ora di vederlo intero e senza pause." },
      { titulo: 'Metropolis (1927)', detalle: "Tutto quello che amo di questo genere viene da qui, e non l'ho mai visto." },
      { titulo: 'Primer (2004)', detalle: "Girato con un budget quasi nullo: voglio vedere fin dove arriva l'idea." },
      { titulo: 'Arrival', detalle: 'Parla di come la lingua ti cambia la testa. Proprio ora che ne sto studiando una.' },
      { titulo: 'Gattaca', detalle: "Me l'ha fatto vedere il mio professore di laboratorio come esempio di etica." },
      { titulo: 'Akira', detalle: "Dopo il Giappone, mi manca ancora l'anime che citano tutti." },
      { titulo: 'Contact', detalle: 'Sagan di nuovo: se mi è piaciuto il libro, dovrebbe piacermi anche il film.' },
      { titulo: 'Moon (2009)', detalle: "Una sola persona, una base e un'idea. Sembra il genere di film che mi piace." },
    ],
  },
  ja: {
    nombre: 'まだ観ていないSFクラシック',
    items: [
      { titulo: 'ソラリス (1972)', detalle: 'ブレードランナーで切なくなったと話したら、勧めてもらった一本です。' },
      { titulo: 'ストーカー (1979)', detalle: '遅いと言われていますが、それこそが狙いなのだそうです。' },
      { titulo: '2001年宇宙の旅', detalle: '物理の授業で断片だけ観ました。今度こそ通しで、一時停止なしで。' },
      { titulo: 'メトロポリス (1927)', detalle: 'このジャンルで好きなものは全部ここから来ているのに、まだ観ていません。' },
      { titulo: 'プライマー (2004)', detalle: 'ほぼ予算ゼロで撮られた作品。アイデアだけでどこまで行けるのか見たいです。' },
      { titulo: 'メッセージ', detalle: '言語が頭の中を変えていく話。ちょうど一つ学んでいる今にぴったりです。' },
      { titulo: 'ガタカ', detalle: '実験の先生が倫理の例として見せてくれました。' },
      { titulo: 'AKIRA', detalle: 'みんなが引き合いに出す伝説のアニメ。そろそろ観ないといけません。' },
      { titulo: 'コンタクト', detalle: 'またセーガン。原作が良かったのだから、映画も良いはずです。' },
      { titulo: '月に囚われた男 (2009)', detalle: '一人と基地一つとアイデア一つ。私好みの映画の予感がします。' },
    ],
  },
  zh: {
    nombre: '待看的科幻经典',
    items: [
      { titulo: '索拉里斯 (1972)', detalle: '我说《银翼杀手》让我难过之后，有人推荐了它。' },
      { titulo: '潜行者 (1979)', detalle: '都说它节奏慢，而慢正是它的意义所在。' },
      { titulo: '2001太空漫游', detalle: '物理课上只看过片段，该完整不暂停地看一遍了。' },
      { titulo: '大都会 (1927)', detalle: '我喜欢这个类型的一切都源于它，我却还没看过。' },
      { titulo: 'Primer (2004)', detalle: '几乎零成本拍出来的，想看看一个点子能走多远。' },
      { titulo: '降临', detalle: '讲语言如何改变思维。正好我在学一门语言。' },
      { titulo: '千钧一发', detalle: '实验课老师拿它当伦理学的例子。' },
      { titulo: '阿基拉', detalle: '从日本回来后，欠自己一部人人都引用的动画。' },
      { titulo: '超时空接触', detalle: '又是萨根：书我喜欢，电影应该也不会差。' },
      { titulo: '月球 (2009)', detalle: '一个人、一个基地、一个点子。听起来就是我的菜。' },
    ],
  },
  ko: {
    nombre: '아직 못 본 SF 고전',
    items: [
      { titulo: '솔라리스 (1972)', detalle: '블레이드 러너를 보고 울적했다고 했더니 추천받은 영화예요.' },
      { titulo: '스토커 (1979)', detalle: '느리다는데, 바로 그게 핵심이라고 해요.' },
      { titulo: '2001 스페이스 오디세이', detalle: '물리 시간에 조각조각 봤어요. 이제 처음부터 끝까지, 멈추지 않고요.' },
      { titulo: '메트로폴리스 (1927)', detalle: '이 장르에서 좋아하는 모든 게 여기서 나왔는데 아직 못 봤어요.' },
      { titulo: '프라이머 (2004)', detalle: '거의 무예산으로 찍었다는데, 아이디어 하나로 어디까지 가는지 보고 싶어요.' },
      { titulo: '컨택트 (2016)', detalle: '언어가 생각을 바꾼다는 이야기. 마침 하나 배우는 중이라 더 끌려요.' },
      { titulo: '가타카', detalle: '실험 교수님이 윤리 사례로 보여 주셨어요.' },
      { titulo: '아키라', detalle: '일본에 다녀온 뒤로, 다들 인용하는 그 애니메이션이 숙제로 남았어요.' },
      { titulo: '콘택트 (1997)', detalle: '또 세이건. 책이 좋았으니 영화도 좋겠죠.' },
      { titulo: '더 문 (2009)', detalle: '한 사람, 기지 하나, 아이디어 하나. 딱 제 취향의 영화 같아요.' },
    ],
  },
  ru: {
    nombre: 'Классика научной фантастики к просмотру',
    items: [
      { titulo: 'Солярис (1972)', detalle: 'Мне его посоветовали после моих слов, что «Бегущий по лезвию» навёл на меня грусть.' },
      { titulo: 'Сталкер (1979)', detalle: 'Говорят, он медленный — и в этом весь смысл.' },
      { titulo: '2001: Космическая одиссея', detalle: 'Кусками смотрели на физике; пора целиком и без пауз.' },
      { titulo: 'Метрополис (1927)', detalle: 'Всё, что я люблю в жанре, растёт отсюда, а до самого фильма руки так и не дошли.' },
      { titulo: 'Детонатор (2004)', detalle: 'Снят почти без бюджета; хочу увидеть, как далеко уходит сама идея.' },
      { titulo: 'Прибытие', detalle: 'О том, как язык перестраивает голову. Как раз сейчас, когда учу новый.' },
      { titulo: 'Гаттака', detalle: 'Преподаватель по лабораторным показывал его как пример об этике.' },
      { titulo: 'Акира', detalle: 'После Японии за мной остался долг — аниме, которое цитируют все.' },
      { titulo: 'Контакт', detalle: 'Снова Саган: раз книга понравилась, фильм должен зайти.' },
      { titulo: 'Луна 2112 (2009)', detalle: 'Один человек, одна база, одна идея. Похоже на моё кино.' },
    ],
  },
  hi: {
    nombre: 'देखने के लिए बाक़ी साइंस फ़िक्शन क्लासिक्स',
    items: [
      { titulo: 'Solaris (1972)', detalle: 'जब मैंने कहा कि Blade Runner ने मुझे उदास कर दिया, तो किसी ने यह फ़िल्म सुझाई।' },
      { titulo: 'Stalker (1979)', detalle: 'कहते हैं धीमी है, और यही तो असल बात है।' },
      { titulo: '2001: A Space Odyssey', detalle: 'फ़िज़िक्स की क्लास में टुकड़ों में देखी है; अब पूरी और बिना रुके देखनी है।' },
      { titulo: 'Metropolis (1927)', detalle: 'इस जॉनर की जो भी चीज़ मुझे पसंद है, सब यहीं से निकली है, और यही फ़िल्म नहीं देखी।' },
      { titulo: 'Primer (2004)', detalle: 'लगभग बिना बजट के बनी; देखना है कि एक आइडिया कितनी दूर जाता है।' },
      { titulo: 'Arrival', detalle: 'यह इस बारे में है कि भाषा सोच बदल देती है। ठीक उसी दौर में जब एक नई भाषा सीखना चल रहा है।' },
      { titulo: 'Gattaca', detalle: 'लैब के प्रोफ़ेसर ने नैतिकता की मिसाल के तौर पर दिखाई थी।' },
      { titulo: 'Akira', detalle: 'जापान से लौटकर वह एनीमे देखना बाक़ी है जिसका हवाला सब देते हैं।' },
      { titulo: 'Contact', detalle: 'फिर से सेगन: किताब पसंद आई थी, तो फ़िल्म भी जमनी चाहिए।' },
      { titulo: 'Moon (2009)', detalle: 'एक इंसान, एक बेस और एक आइडिया। लगता है यह मेरी पसंद की फ़िल्म है।' },
    ],
  },
  tr: {
    nombre: 'Bekleyen bilim kurgu klasikleri',
    items: [
      { titulo: 'Solaris (1972)', detalle: 'Blade Runner beni hüzünlendirdi dediğimde biri bunu önerdi.' },
      { titulo: 'Stalker (1979)', detalle: 'Yavaş diyorlar, mesele de tam olarak buymuş.' },
      { titulo: '2001: Bir Uzay Destanı', detalle: 'Fizik dersinde parça parça izledim; artık baştan sona, durmadan izleme vakti.' },
      { titulo: 'Metropolis (1927)', detalle: 'Bu türde sevdiğim her şey buradan çıkmış, bense hâlâ izlemedim.' },
      { titulo: 'Primer (2004)', detalle: 'Neredeyse sıfır bütçeyle çekilmiş; bir fikrin nereye kadar gidebildiğini görmek istiyorum.' },
      { titulo: 'Geliş', detalle: 'Dilin düşünceyi nasıl değiştirdiğini anlatıyor. Tam da bir dil öğrenirken.' },
      { titulo: 'Gattaca', detalle: 'Laboratuvar hocam etik örneği olarak izletmişti.' },
      { titulo: 'Akira', detalle: 'Japonya’dan sonra herkesin alıntıladığı o anime hâlâ borcum.' },
      { titulo: 'Mesaj (1997)', detalle: 'Yine Sagan: Kitabı sevdiysem filmi de sevmeliyim.' },
      { titulo: 'Moon (2009)', detalle: 'Tek kişi, tek üs, tek fikir. Tam benlik bir film gibi duruyor.' },
    ],
  },
  id: {
    nombre: 'Klasik fiksi ilmiah yang belum ditonton',
    items: [
      { titulo: 'Solaris (1972)', detalle: 'Direkomendasikan waktu aku bilang Blade Runner bikin sedih.' },
      { titulo: 'Stalker (1979)', detalle: 'Katanya lambat, dan justru itu intinya.' },
      { titulo: '2001: A Space Odyssey', detalle: 'Baru lihat potongannya di kelas fisika; saatnya nonton utuh tanpa jeda.' },
      { titulo: 'Metropolis (1927)', detalle: 'Semua yang kusuka dari genre ini lahir dari sini, dan aku belum menontonnya.' },
      { titulo: 'Primer (2004)', detalle: 'Dibuat nyaris tanpa biaya; penasaran sejauh mana idenya bisa melaju.' },
      { titulo: 'Arrival', detalle: 'Tentang bahasa yang mengubah cara berpikir. Pas sekali, aku sedang belajar satu.' },
      { titulo: 'Gattaca', detalle: 'Diputar dosen praktikum sebagai contoh etika.' },
      { titulo: 'Akira', detalle: 'Setelah Jepang, masih berutang menonton anime yang dikutip semua orang.' },
      { titulo: 'Contact', detalle: 'Sagan lagi: kalau bukunya kusuka, filmnya mestinya juga.' },
      { titulo: 'Moon (2009)', detalle: 'Satu orang, satu markas, satu ide. Kayaknya film seleraku banget.' },
    ],
  },
  pl: {
    nombre: 'Zaległa klasyka science fiction',
    items: [
      { titulo: 'Solaris (1972)', detalle: 'Polecono mi go po moich słowach, że Blade Runner zostawił mnie ze smutkiem.' },
      { titulo: 'Stalker (1979)', detalle: 'Podobno jest powolny i właśnie o to chodzi.' },
      { titulo: '2001: Odyseja kosmiczna', detalle: 'Widziane fragmentami na fizyce; czas obejrzeć całość bez pauz.' },
      { titulo: 'Metropolis (1927)', detalle: 'Wszystko, co kocham w tym gatunku, wyrasta stąd, a filmu wciąż nie znam.' },
      { titulo: 'Primer (2004)', detalle: 'Nakręcony prawie bez budżetu; chcę zobaczyć, jak daleko zajdzie sam pomysł.' },
      { titulo: 'Nowy początek', detalle: 'O tym, jak język przestawia głowę. Akurat teraz, gdy się jednego uczę.' },
      { titulo: 'Gattaca', detalle: 'Prowadzący laboratorium pokazał go jako przykład z etyki.' },
      { titulo: 'Akira', detalle: 'Po Japonii zostało mi w spadku anime, które cytują wszyscy.' },
      { titulo: 'Kontakt', detalle: 'Znowu Sagan: skoro książka mi się podobała, film też powinien.' },
      { titulo: 'Moon (2009)', detalle: 'Jedna osoba, jedna baza i jeden pomysł. Brzmi jak moje kino.' },
    ],
  },
  nl: {
    nombre: 'Nog te kijken sciencefictionklassiekers',
    items: [
      { titulo: 'Solaris (1972)', detalle: 'Aangeraden toen ik zei dat Blade Runner me verdrietig had achtergelaten.' },
      { titulo: 'Stalker (1979)', detalle: 'Ze zeggen dat hij traag is en dat dat precies de bedoeling is.' },
      { titulo: '2001: A Space Odyssey', detalle: 'In stukjes gezien bij natuurkunde; tijd om hem helemaal en zonder pauze te kijken.' },
      { titulo: 'Metropolis (1927)', detalle: 'Alles wat ik aan het genre mooi vind komt hiervandaan, en ik heb hem nooit gezien.' },
      { titulo: 'Primer (2004)', detalle: 'Gemaakt met bijna geen budget; ik wil zien hoe ver het idee reikt.' },
      { titulo: 'Arrival', detalle: 'Gaat over hoe taal je denken verandert. Precies nu ik er een leer.' },
      { titulo: 'Gattaca', detalle: 'Mijn labdocent liet hem zien als voorbeeld van ethiek.' },
      { titulo: 'Akira', detalle: 'Na Japan sta ik bij mezelf in het krijt voor de anime die iedereen citeert.' },
      { titulo: 'Contact', detalle: 'Weer Sagan: als het boek me beviel, moet de film dat ook doen.' },
      { titulo: 'Moon (2009)', detalle: 'Eén persoon, één basis en één idee. Klinkt als mijn soort film.' },
    ],
  },
  ar: {
    nombre: 'كلاسيكيات الخيال العلمي المعلّقة',
    items: [
      { titulo: 'Solaris (1972)', detalle: 'رُشِّح لي عندما قلت إن Blade Runner تركني في حزن.' },
      { titulo: 'Stalker (1979)', detalle: 'يقولون إنه بطيء، وإن هذا هو المقصود تمامًا.' },
      { titulo: '2001: A Space Odyssey', detalle: 'شاهدت مقاطع منه في حصة الفيزياء؛ حان وقت مشاهدته كاملًا دون توقف.' },
      { titulo: 'Metropolis (1927)', detalle: 'كل ما أحبه في هذا النوع خرج من هنا، ولم أشاهده بعد.' },
      { titulo: 'Primer (2004)', detalle: 'صُوِّر بميزانية تكاد تكون معدومة؛ أريد أن أرى إلى أين تصل الفكرة.' },
      { titulo: 'Arrival', detalle: 'عن اللغة وكيف تغيّر طريقة التفكير، في الوقت الذي أتعلم فيه لغة جديدة.' },
      { titulo: 'Gattaca', detalle: 'عرضه أستاذ المختبر مثالًا عن الأخلاقيات.' },
      { titulo: 'Akira', detalle: 'بعد اليابان، ما زال الأنمي الذي يستشهد به الجميع دَينًا عليّ.' },
      { titulo: 'Contact', detalle: 'ساغان مرة أخرى: إذا أعجبني الكتاب فالفيلم ينبغي أن يعجبني.' },
      { titulo: 'Moon (2009)', detalle: 'شخص واحد وقاعدة واحدة وفكرة واحدة. يبدو من نوع الأفلام الذي أحب.' },
    ],
  },
}
