// Generado por `npm run ejemplos:texto` — no lo edites a mano.
// Contenido del ejemplo de fábrica de entretenimiento, en los dos idiomas. Vive aparte
// de `dict.ts` a propósito: en cuanto se crea es dato del usuario, no interfaz.

export const TEXTOS_ENTRETENIMIENTO = {
  es: {
    peliTitulo: 'La última parada del 27',
    peliGenero: 'Drama',
    peliAutor: 'Nuria Balaguer',
    peliResena: 'La vi un martes sin esperar nada y me dejó tocada. El plano final en la parada vacía se me quedó dando vueltas toda la semana.',
    serieTitulo: 'Cinco pisos sin ascensor',
    serieGenero: 'Comedia dramática',
    serieResena: 'Voy por el capítulo cuatro y ya reconozco los ruidos del portal. La trama del hermano se me hace lenta, pero los diálogos la salvan.',
    libroTitulo: 'El invierno de los relojes lentos',
    libroGenero: 'Novela',
    libroAutor: 'Marisa Ontiveros',
    libroResena: 'Lo terminé en el tren de vuelta y cerré el libro sonriendo. Los capítulos cortos me ayudaron a no dejarlo a medias como otros años.',
    juegoTitulo: 'Faro Cero',
    juegoGenero: 'Aventura',
  },
  en: {
    peliTitulo: 'Last Stop on the 27',
    peliGenero: 'Drama',
    peliAutor: 'Nora Whitfield',
    peliResena: 'I put it on a random Tuesday expecting nothing and it wrecked me. That last shot of the empty bus stop followed me around all week.',
    serieTitulo: 'Fifth Floor, No Lift',
    serieGenero: 'Comedy drama',
    serieResena: 'I am four episodes in and I already know every creak of that stairwell. The brother\'s storyline drags, but the dialogue keeps me watching.',
    libroTitulo: 'The Winter of Slow Clocks',
    libroGenero: 'Literary fiction',
    libroAutor: 'Marissa Thorne',
    libroResena: 'I finished it on the train home and shut the cover grinning. The short chapters are the reason I actually got to the end this time.',
    juegoTitulo: 'Lighthouse Zero',
    juegoGenero: 'Puzzle adventure',
  },
  pt: {
    peliTitulo: 'A última parada do 27',
    peliGenero: 'Drama',
    peliAutor: 'Nuria Balaguer',
    peliResena: 'Vi numa terça sem esperar nada e fiquei tocada. A cena final na parada vazia ficou passando na minha cabeça a semana inteira.',
    serieTitulo: 'Cinco andares sem elevador',
    serieGenero: 'Comédia dramática',
    serieResena: 'Estou no episódio quatro e já reconheço os barulhos do prédio. A história do irmão fica meio lenta, mas os diálogos salvam.',
    libroTitulo: 'O inverno dos relógios lentos',
    libroGenero: 'Romance',
    libroAutor: 'Marisa Ontiveros',
    libroResena: 'Terminei no trem de volta e fechei o livro sorrindo. Os capítulos curtos me ajudaram a não deixar pela metade como em outros anos.',
    juegoTitulo: 'Farol Zero',
    juegoGenero: 'Aventura',
  },
  fr: {
    peliTitulo: 'Le dernier arrêt du 27',
    peliGenero: 'Drame',
    peliAutor: 'Nuria Balaguer',
    peliResena: 'Je l\'ai vu un mardi sans rien attendre et ça m\'a bouleversée. Le plan final sur l\'arrêt vide m\'a trotté dans la tête toute la semaine.',
    serieTitulo: 'Cinq étages sans ascenseur',
    serieGenero: 'Comédie dramatique',
    serieResena: 'J\'en suis à l\'épisode quatre et je reconnais déjà les bruits de l\'immeuble. L\'histoire du frère traîne un peu, mais les dialogues sauvent tout.',
    libroTitulo: 'L\'hiver des horloges lentes',
    libroGenero: 'Roman',
    libroAutor: 'Marisa Ontiveros',
    libroResena: 'Je l\'ai fini dans le train du retour et j\'ai refermé le livre en souriant. Les chapitres courts m\'ont aidée à ne pas l\'abandonner à mi-chemin comme les autres années.',
    juegoTitulo: 'Phare Zéro',
    juegoGenero: 'Aventure',
  },
  de: {
    peliTitulo: 'Die letzte Haltestelle der 27',
    peliGenero: 'Drama',
    peliAutor: 'Nuria Balaguer',
    peliResena: 'Ich habe ihn an einem Dienstag gesehen, ohne etwas zu erwarten, und er hat mich berührt. Die letzte Einstellung an der leeren Haltestelle ging mir die ganze Woche nicht aus dem Kopf.',
    serieTitulo: 'Fünf Stockwerke ohne Aufzug',
    serieGenero: 'Tragikomödie',
    serieResena: 'Ich bin bei Folge vier und erkenne schon die Geräusche im Treppenhaus. Die Handlung um den Bruder zieht sich, aber die Dialoge retten die Serie.',
    libroTitulo: 'Der Winter der langsamen Uhren',
    libroGenero: 'Roman',
    libroAutor: 'Marisa Ontiveros',
    libroResena: 'Ich habe es im Zug nach Hause zu Ende gelesen und das Buch lächelnd zugeklappt. Die kurzen Kapitel haben mir geholfen, es nicht wie in anderen Jahren halb liegen zu lassen.',
    juegoTitulo: 'Leuchtturm Null',
    juegoGenero: 'Abenteuer',
  },
  it: {
    peliTitulo: 'L\'ultima fermata del 27',
    peliGenero: 'Drammatico',
    peliAutor: 'Nuria Balaguer',
    peliResena: 'L\'ho visto un martedì senza aspettarmi niente e mi ha colpita. L\'inquadratura finale sulla fermata vuota mi è rimasta in testa tutta la settimana.',
    serieTitulo: 'Cinque piani senza ascensore',
    serieGenero: 'Commedia drammatica',
    serieResena: 'Sono al quarto episodio e riconosco già i rumori del portone. La trama del fratello si trascina un po\', ma i dialoghi la salvano.',
    libroTitulo: 'L\'inverno degli orologi lenti',
    libroGenero: 'Romanzo',
    libroAutor: 'Marisa Ontiveros',
    libroResena: 'L\'ho finito sul treno di ritorno e ho chiuso il libro sorridendo. I capitoli brevi mi hanno aiutata a non lasciarlo a metà come altri anni.',
    juegoTitulo: 'Faro Zero',
    juegoGenero: 'Avventura',
  },
  ja: {
    peliTitulo: '27番のラストストップ',
    peliGenero: 'ドラマ',
    peliAutor: 'ヌリア・バラゲール',
    peliResena: '何も期待せずに見た火曜日、心をぐっと掴まれました。誰もいないバス停の最後のカットが一週間頭から離れませんでした。',
    serieTitulo: 'エレベーターなしの5階',
    serieGenero: 'ヒューマンコメディ',
    serieResena: '第4話まで来て、もう建物の物音を覚えてしまいました。兄のストーリーは少し間延びしますが、会話がそれを救っています。',
    libroTitulo: '遅い時計の冬',
    libroGenero: '小説',
    libroAutor: 'マリサ・オンティベロス',
    libroResena: '帰りの電車で読み終えて、微笑みながら本を閉じました。章が短いおかげで、いつもの年みたいに途中で放り出さずにすみました。',
    juegoTitulo: 'ライトハウス・ゼロ',
    juegoGenero: 'アドベンチャー',
  },
  zh: {
    peliTitulo: '27路的最后一站',
    peliGenero: '剧情片',
    peliAutor: '努里娅·巴拉格尔',
    peliResena: '一个普通的周二看的,什么都没期待,结果被深深触动。空荡荡车站的最后一个镜头在脑子里转了一整周。',
    serieTitulo: '五楼没有电梯',
    serieGenero: '悲喜剧',
    serieResena: '看到第四集,已经能认出楼道里的各种声响了。哥哥那条线有点拖,但对白撑住了整部剧。',
    libroTitulo: '慢钟表的冬天',
    libroGenero: '小说',
    libroAutor: '玛丽萨·翁蒂韦罗斯',
    libroResena: '在回程的火车上看完,合上书的时候在笑。章节短,今年总算没有像往年那样看到一半就搁下。',
    juegoTitulo: '零号灯塔',
    juegoGenero: '冒险',
  },
  ko: {
    peliTitulo: '27번의 마지막 정류장',
    peliGenero: '드라마',
    peliAutor: '누리아 발라게르',
    peliResena: '아무 기대 없이 화요일에 봤는데 마음이 크게 흔들렸어요. 텅 빈 정류장의 마지막 장면이 일주일 내내 머릿속을 맴돌았어요.',
    serieTitulo: '엘리베이터 없는 5층',
    serieGenero: '트래지코미디',
    serieResena: '4화까지 봤는데 벌써 건물 소리가 다 익숙해요. 형제 이야기는 좀 늘어지지만 대사가 다 살려줘요.',
    libroTitulo: '느린 시계의 겨울',
    libroGenero: '소설',
    libroAutor: '마리사 온티베로스',
    libroResena: '돌아오는 기차에서 다 읽고 웃으면서 책을 덮었어요. 챕터가 짧아서 이번엔 예년처럼 중간에 그만두지 않았어요.',
    juegoTitulo: '라이트하우스 제로',
    juegoGenero: '어드벤처',
  },
  ru: {
    peliTitulo: 'Последняя остановка 27-го',
    peliGenero: 'Драма',
    peliAutor: 'Нурия Балагер',
    peliResena: 'Случайный вторник, никаких ожиданий — и всё перевернулось. Финальный кадр с пустой остановкой преследовал всю неделю.',
    serieTitulo: 'Пятый этаж без лифта',
    serieGenero: 'Трагикомедия',
    serieResena: 'Дошло до четвёртой серии, и уже узнаются все звуки подъезда. Линия брата тянется медленно, но диалоги вытягивают всё.',
    libroTitulo: 'Зима медленных часов',
    libroGenero: 'Роман',
    libroAutor: 'Мариса Онтиверос',
    libroResena: 'Дочитано в поезде по дороге домой, книга закрыта с улыбкой. Короткие главы помогли не бросить на середине, как в другие годы.',
    juegoTitulo: 'Маяк Ноль',
    juegoGenero: 'Приключение',
  },
  hi: {
    peliTitulo: '27 की आख़िरी स्टॉप',
    peliGenero: 'ड्रामा',
    peliAutor: 'नूरिया बालागेर',
    peliResena: 'बिना किसी उम्मीद के मंगलवार को देखी, और दिल छू गया। खाली स्टॉप वाला आख़िरी शॉट पूरे हफ़्ते दिमाग़ में घूमता रहा।',
    serieTitulo: 'बिना लिफ़्ट वाली पाँचवीं मंज़िल',
    serieGenero: 'ट्रैजिकॉमेडी',
    serieResena: 'चौथे एपिसोड तक पहुँचना हो गया है और इमारत की हर आवाज़ पहचान में आने लगी है। भाई वाली कहानी थोड़ी धीमी लगती है, पर संवाद उसे संभाल लेते हैं।',
    libroTitulo: 'धीमी घड़ियों की सर्दी',
    libroGenero: 'उपन्यास',
    libroAutor: 'मारिसा ओन्टिवेरोस',
    libroResena: 'वापसी की ट्रेन में ख़त्म हुई और मुस्कुराते हुए किताब बंद हुई। छोटे अध्यायों ने इस बार बीच में छोड़ने से बचा लिया, जैसा और सालों में होता था।',
    juegoTitulo: 'लाइटहाउस ज़ीरो',
    juegoGenero: 'एडवेंचर',
  },
  tr: {
    peliTitulo: '27\'nin son durağı',
    peliGenero: 'Dram',
    peliAutor: 'Nuria Balaguer',
    peliResena: 'Hiçbir şey beklemeden bir salı günü izledim ve beni derinden etkiledi. Boş durakta biten son sahne bütün hafta aklımdan çıkmadı.',
    serieTitulo: 'Asansörsüz beş kat',
    serieGenero: 'Dramatik komedi',
    serieResena: 'Dördüncü bölümdeyim ve binanın seslerini artık tanıyorum. Kardeşin hikâyesi biraz ağır ilerliyor ama diyaloglar diziyi kurtarıyor.',
    libroTitulo: 'Yavaş saatlerin kışı',
    libroGenero: 'Roman',
    libroAutor: 'Marisa Ontiveros',
    libroResena: 'Dönüş trenindeyken bitirdim ve kitabı gülümseyerek kapattım. Kısa bölümler, diğer yıllarda olduğu gibi yarım bırakmamı engelledi.',
    juegoTitulo: 'Fener Sıfır',
    juegoGenero: 'Macera',
  },
  id: {
    peliTitulo: 'Halte terakhir 27',
    peliGenero: 'Drama',
    peliAutor: 'Nuria Balaguer',
    peliResena: 'Nonton di hari Selasa tanpa ekspektasi apa-apa dan langsung kena. Adegan terakhir di halte kosong itu kepikiran terus sepanjang minggu.',
    serieTitulo: 'Lantai lima tanpa lift',
    serieGenero: 'Drama komedi',
    serieResena: 'Baru sampai episode empat dan sudah hafal suara-suara di gedung itu. Alur cerita si kakak agak lambat, tapi dialognya menyelamatkan semuanya.',
    libroTitulo: 'Musim dingin jam-jam lambat',
    libroGenero: 'Novel',
    libroAutor: 'Marisa Ontiveros',
    libroResena: 'Selesai baca pas di kereta pulang, dan nutup buku sambil senyum-senyum. Bab-babnya pendek jadi nggak berhenti di tengah jalan seperti tahun-tahun sebelumnya.',
    juegoTitulo: 'Mercusuar Nol',
    juegoGenero: 'Petualangan',
  },
  pl: {
    peliTitulo: 'Ostatni przystanek 27',
    peliGenero: 'Dramat',
    peliAutor: 'Nuria Balaguer',
    peliResena: 'Obejrzenie we wtorek bez żadnych oczekiwań, a mimo to duże wrażenie. Ostatnie ujęcie na pustym przystanku nie dawało spokoju przez cały tydzień.',
    serieTitulo: 'Piąte piętro bez windy',
    serieGenero: 'Tragikomedia',
    serieResena: 'Czwarty odcinek za sobą i już rozpoznawalne odgłosy klatki schodowej. Wątek brata trochę się dłuży, ale dialogi ratują całość.',
    libroTitulo: 'Zima wolnych zegarów',
    libroGenero: 'Powieść',
    libroAutor: 'Marisa Ontiveros',
    libroResena: 'Skończone w pociągu w drodze powrotnej, książka zamknięta z uśmiechem. Krótkie rozdziały pomogły nie porzucić lektury w połowie, jak w inne lata.',
    juegoTitulo: 'Latarnia Zero',
    juegoGenero: 'Przygodowa',
  },
  ar: {
    peliTitulo: 'المحطة الأخيرة للخط 27',
    peliGenero: 'دراما',
    peliAutor: 'نوريا بالاغير',
    peliResena: 'شاهدتُه يوم ثلاثاء دون أي توقعات وتركني متأثرًا. المشهد الأخير عند المحطة الفارغة ظل يدور في ذهني طوال الأسبوع.',
    serieTitulo: 'خمسة طوابق بلا مصعد',
    serieGenero: 'دراما كوميدية',
    serieResena: 'وصلتُ إلى الحلقة الرابعة وأصبحتُ أميّز أصوات العمارة. حبكة الأخ بطيئة بعض الشيء، لكن الحوارات تنقذ المسلسل.',
    libroTitulo: 'شتاء الساعات البطيئة',
    libroGenero: 'رواية',
    libroAutor: 'ماريسا أونتيبيروس',
    libroResena: 'أنهيتُه في قطار العودة وأغلقتُ الكتاب مبتسمًا. الفصول القصيرة ساعدتني على عدم تركه في المنتصف كما في سنوات أخرى.',
    juegoTitulo: 'المنارة صفر',
    juegoGenero: 'مغامرة',
  },
  nl: {
    peliTitulo: 'De laatste halte van lijn 27',
    peliGenero: 'Drama',
    peliAutor: 'Nuria Balaguer',
    peliResena: 'Op een dinsdag gekeken zonder iets te verwachten en het raakte me diep. Het laatste shot van de lege halte spookte de hele week door mijn hoofd.',
    serieTitulo: 'Vijfde verdieping zonder lift',
    serieGenero: 'Tragikomedie',
    serieResena: 'Bij aflevering vier en ik herken nu al alle geluiden van het portiek. Het verhaal van de broer sleept een beetje, maar de dialogen redden het.',
    libroTitulo: 'De winter van de trage klokken',
    libroGenero: 'Roman',
    libroAutor: 'Marisa Ontiveros',
    libroResena: 'Uitgelezen in de trein naar huis en het boek glimlachend dichtgeslagen. Dankzij de korte hoofdstukken liet ik het niet halverwege liggen, zoals andere jaren.',
    juegoTitulo: 'Vuurtoren Nul',
    juegoGenero: 'Avontuur',
  },
}
