import type { ManualTraducido } from './manualI18n'

/**
 * Las frases de ejemplo del manual de comandos en nl, indexadas por su
 * texto español de origen (ver `manualI18n.ts`).
 *
 * GENERADO por `npm run traducir:contenido` — no lo edites a mano.
 */
export const MANUAL_NL: ManualTraducido = {
  frases: {
    '[Corrí] {5 km} en {30 min}': '[Ik liep] {5 km} in {30 min}',
    '[@]{cocina} [comí] {una ensalada}': '[@]{cocina} [ik at] {een salade}',
    '[Abre] el {estudio de audio}': '[Open] de {audiostudio}',
    '[Abre] mis {canciones}': '[Open] mijn {nummers}',
    '[Abre] el {mezclador DJ}': '[Open] de {DJ-mixer}',
    '[Abre] la {galería de arte}': '[Open] de {kunstgalerie}',
    '[Abre] mis {dibujos}': '[Open] mijn {tekeningen}',
    '[Abre] mis {libros}': '[Open] mijn {boeken}',
    '[Abre] el {estudio de escritura}': '[Open] de {schrijfstudio}',
    '[Escribe un cuento] sobre {un faro en invierno} y [guárdalo en mis libros]': '[Schrijf een kort verhaal] over {een vuurtoren in de winter} en [sla het op in mijn boeken]',
    '[Guarda en mis libros] este texto: {Querido diario, hoy…}': '[Sla op in mijn boeken] deze tekst: {Lief dagboek, vandaag…}',
    '[Abre] el {editor de video}': '[Open] de {video-editor}',
    '[Abre] mis {videos}': "[Open] mijn {video's}",
    '[Abre] la {animación 3D}': '[Open] de {3D-animatie}',
    "[Abre] {mis archivos}": "[Open] {mijn bestanden}",
    "[Abre] los {archivos recientes}": "[Open] de {recente bestanden}",
    "[Abre] los {archivos del studio}": "[Open] de {studiobestanden}",
    "[Abre] la {papelera}": "[Open] de {prullenbak}",
    "[Abre] los {archivos destacados}": "[Open] de {bestanden met ster}",
    '[Tomé] {2 vasos} de [agua]': '[Ik dronk] {2 glazen} [water]',
    '[Me pesé]: {74 kg}': '[Ik heb me gewogen]: {74 kg}',
    'Inventa una [receta] {ligera con atún}': 'Bedenk een [recept] {licht, met tonijn}',
    'Arma una [dieta] {alta en proteína}': 'Stel een [dieet] samen {met veel eiwitten}',
    'Agrega {plátano y avena} a la [lista del súper]': 'Zet {bananen en havermout} op de [boodschappenlijst]',
    '[Corrí] {5 km}': '[Ik liep] {5 km}',
    '[Abre] {cardio}': '[Open] {cardio}',
    '[Haz] una {sentadilla}': '[Doe] een {squat}',
    'Registra mi sesión: {crossfit 40 min, intensidad alta}': 'Noteer mijn sessie: {crossfit 40 min, hoge intensiteit}',
    '[Arma una rutina] de {pecho y tríceps} de {45 min}': '[Stel een routine samen] voor {borst en triceps} van {45 min}',
    '[Dormí] {7 horas}, calidad {4/5}': '[Ik sliep] {7 uur}, kwaliteit {4/5}',
    '[Abre] {mi sueño}': '[Open] {mijn slaap}',
    '{Me acosté a las 23, desperté a las 7 y me levanté 2 veces}': '{Om 23 uur naar bed, om 7 uur wakker, twee keer opgestaan}',
    '[Recuerdo]: {tarde de juegos con mi hermana}': '[Herinnering]: {spelletjesmiddag met mijn zus}',
    'Anota esta anécdota: {hoy celebramos el cumple de mamá}': 'Noteer deze herinnering: {vandaag vierden we mama\'s verjaardag}',
    '[Cobré] {8000} de {la quincena}': '[Ik kreeg] {8000} van {het halfmaandelijkse loon}',
    '[Abre] los {gastos fijos}': '[Open] de {vaste lasten}',
    '{Pagué 250 de luz y 180 de agua}': '{Ik betaalde 250 voor licht en 180 voor water}',
    '[Resolver ecuación]': '[Vergelijking oplossen]',
    '[Convertir unidades]': '[Eenheden omrekenen]',
    '[Abre] las {matrices}': '[Open] de {matrices}',
    '[Sistema de ecuaciones]': '[Stelsel vergelijkingen]',
    '[Convertir a binario]': '[Omzetten naar binair]',
    '[Propina]': '[Fooi]',
    '[Regla de tres]': '[Regel van drie]',
    '[Estudié] {historia romana} {30 min}': '[Ik studeerde] {Romeinse geschiedenis} {30 min}',
    'Apunta que aprendí: {los ríos de Europa}': 'Noteer wat ik leerde: {de rivieren van Europa}',
    '[Vi la película] {Dune}': '[Ik zag de film] {Dune}',
    '[Quiero jugar] la {viborita}': '[Ik wil] {snake} [spelen]',
    '[Juega] {tetris}': '[Speel] {tetris}',
    'Apunta {la serie Dark} como pendiente': 'Zet {de serie Dark} op mijn kijklijst',
    '[Abre] {por conocer}': '[Open] {nog te zien}',
    '[Abre] las {rutas}': '[Open] de {routes}',
    '[Visité] {Oaxaca}': '[Ik bezocht] {Oaxaca}',
    'Quiero conocer {Japón}': 'Ik wil naar {Japan}',
    '[Visité] {Roma}: {la fontana de noche es mágica}': '[Ik bezocht] {Rome}: {de fontein is \'s nachts magisch}',
    '[Medité] {10 min}': '[Ik mediteerde] {10 min}',
    '[Abre] el {resumen del garage}': '[Open] het {overzicht van de garage}',
    '[Abre] {mis vehículos}': '[Open] {mijn voertuigen}',
    '[Abre] las {efemérides}': '[Open] {vandaag in de geschiedenis}',
    '[Abre] {mis hobbies}': '[Open] {mijn hobby\'s}',
    '[Dibuja un diagrama de flujo] de {cómo hacer pan}': '[Teken een stroomschema] van {hoe je brood bakt}',
    '[Haz un esquema] de {lo que me acabas de explicar}': '[Maak een schema] van {wat je me net hebt uitgelegd}',
    '[Agenda] una {junta con el cliente} el {martes a las 10}': '[Plan] een {afspraak met de klant} op {dinsdag om 10}',
    '[Apunta el pendiente] {mandar la cotización}': '[Noteer de taak] {de offerte versturen}',
    '[Recuérdame] tomar {ibuprofeno} a las {8 y a las 20}': '[Herinner me] eraan om {8 en om 20} {ibuprofen} te nemen',
    '[Abre] el {tutor}': '[Open] de {tutor}',
    '[Abre] el {progreso de idiomas}': '[Open] de {voortgang van talen}',
    '[Corre una carrera] de {3 vueltas}': '[Rij een race] van {3 ronden}',
    '[Juguemos] {paintball}': '[Laten we] {paintball} [spelen]',
    '[Juguemos paintball] {2v2}': '[Laten we paintball spelen] {2v2}',
    '[Reta] a {Luna} a un paintball {1v1}': '[Daag] {Luna} uit voor een paintball {1v1}',
    '[Sal] del {paintball}': '[Stop] met de {paintball}',
    '[Abre] la {agenda de hoy}': '[Open] de {agenda van vandaag}',
    '[Abre] {mi semana}': '[Open] {mijn week}',
    '[Crea una rutina] de mañana: {agua, estiramiento y gratitud} a las {7:00}': '[Maak een routine] voor \'s ochtends: {water, rekken en dankbaarheid} om {7:00}',
    '[Crea una rutina] de {lunes y miércoles}: {correr 20 min}': '[Maak een routine] voor {maandag en woensdag}: {20 min hardlopen}',
    '[Enséñame] las {rutinas}': '[Laat me] de {routines} zien',
    '[Crea] una {lámpara}': '[Maak] een {lamp}',
    '[Gira el último objeto]': '[Draai het laatste object]',
    '[Quita el último objeto]': '[Haal het laatste object weg]',
    '[Genera en 3D] {un dragón morado}': '[Genereer in 3D] {een paarse draak}',
    '[Crea una imagen] de {un atardecer en la playa}': '[Maak een afbeelding] van {een zonsondergang op het strand}',
    '[Bájame]': '[Laat me eraf]',
    '[Vista en] {primera persona}': '[Beeld in] {eerste persoon}',
    '[Quita el tema]': '[Haal het thema weg]',
    '[Música] {chiptune}': '[Muziek] {chiptune}',
    '[Volumen] al {40%}': '[Volume] op {40%}',
    '[Apaga la música]': '[Zet de muziek uit]',
    '[Tema de interfaz] {neón}': '[Interfacethema] {neon}',
    '[Tipografía] {serif}': '[Lettertype] {serif}',
    '[Estilo de la interfaz] {pixel}': '[Interfacestijl] {pixel}',
    '[Transparencia] al {40%}': '[Transparantie] op {40%}',
    '[Apaga los efectos]': '[Zet de effecten uit]',
    '[Crea un cuarto] llamado {Estudio}': '[Maak een kamer] met de naam {Studio}',
    '[Avísame] de mis {rutinas}': '[Waarschuw me] over mijn {routines}',
    '[Avísame de mis metas] a las {21:00}': '[Herinner me aan mijn doelen] om {21:00}',
    '[Apaga los avisos]': '[Zet de meldingen uit]',
    '[Descarga un respaldo] de mis datos': '[Download een back-up] van mijn gegevens',
    '[Vuelve a ver la bienvenida]': '[Laat het welkom opnieuw zien]',
    '[Abre las configuraciones]': '[Open de instellingen]',
    '[Abre] mi {cuenta}': '[Open] mijn {account}',
    '[Recuerda que] {soy vegetariano}': '[Onthoud dat] {ik vegetariër ben}',
    '[@]{cocina} {ensalada de la comida}': '[@]{cocina} {salade voor de lunch}',
    '[Cómo funciona] el {editor}': '[Hoe werkt] de {editor}',
    '[Cómo funciona] el {chat}': '[Hoe werkt] de {chat}',
    '[Para qué sirve] la {cámara}': '[Waar dient] de {camera} [voor]',
    '[Abre] {ejemplo.com}': '[Open] {voorbeeld.nl}',
    '[Busca en internet] {recetas de pan}': '[Zoek op internet] {brood recepten}',
    '[Historial]': '[Geschiedenis]',
    '[Sitios]': '[Sites]',
    '[Tiempo en internet]': '[Tijd online]',
    '[Cómo llegar]': '[Route]',
    '[Amigos]': '[Vrienden]',
    '[Jugar] {paintball} [con] {@ana}': '[Speel] {paintball} [met] {@ana}',
    '{Tenis} {@ana}': '{Tennis} {@ana}',
    '[Comí] {pollo con arroz} en la {cena}': '[Ik at] {kip met rijst} als {avondeten}',
    '[Abre] el {recetario}': '[Open] het {receptenboek}',
    '[Abre] la {lista del súper}': '[Open] de {boodschappenlijst}',
    '[Abre] el {diario de comidas}': '[Open] het {eetdagboek}',
    '[Abre] la {dieta}': '[Open] het {dieet}',
    '[Abre] las {metas de nutrición}': '[Open] de {voedingsdoelen}',
    '[Entrené] {pierna} {45 min}': '[Ik trainde] {benen}, {45 min}',
    '[Abre] el {plan de ejercicio}': '[Open] het {trainingsschema}',
    '[Abre] {fuerza}': '[Open] {krachttraining}',
    '[Abre] {flexibilidad}': '[Open] {flexibiliteit}',
    '[Abre] las {metas de ejercicio}': '[Open] de {trainingsdoelen}',
    '[Muéstrame] cómo se hace el {press banca}': '[Laat me zien] hoe je {bankdrukken} doet',
    '[Arma una rutina] de {estiramientos} para {la espalda baja}': '[Stel een routine samen] met {rekoefeningen} voor {de onderrug}',
    '[Abre] el {despertador}': '[Open] de {wekker}',
    '[Abre] mis {anécdotas}': '[Open] mijn {herinneringen}',
    '[Abre] el {calendario de ánimo}': '[Open] de {stemmingskalender}',
    '[Gasté] {500} en {el súper}': '[Ik besteedde] {500} aan {boodschappen}',
    '[Abre] el {balance}': '[Open] de {kasstroom}',
    '[Abre] los {movimientos}': '[Open] de {transacties}',
    '[Abre] las {metas de ahorro}': '[Open] de {spaardoelen}',
    '[Abre] las {divisas}': "[Open] de {valuta's}",
    '[Abre] las {criptomonedas}': "[Open] de {cryptovaluta's}",
    '[Abre] las {materias primas}': '[Open] de {grondstoffen}',
    '[Abre] el {formulario}': '[Open] het {formuleboek}',
    '[Abre] la {calculadora}': '[Open] de {rekenmachine}',
    '[Abre] el {graficador}': '[Open] de {grafieken}',
    '[Abre] las {hojas de cálculo}': '[Open] de {spreadsheets}',
    '[Abre] las {charlas}': '[Open] de {chats}',
    '[Abre] la {enciclopedia}': '[Open] de {encyclopedie}',
    '[Abre] la {sesión de estudio}': '[Open] de {studiesessie}',
    '[Abre] el {resumen de estudio}': '[Open] het {studieoverzicht}',
    '[Jugué] {ajedrez} con mi hermano': '[Ik speelde] {schaak} met mijn broer',
    '[Abre] el {archivo}': '[Open] het {archief}',
    '[Abre] la {mesa de juegos}': '[Open] de {bordspellen}',
    '[Juega] una partida de {ajedrez}': '[Speel] een potje {schaak}',
    '[Abre] el {mapamundi}': '[Open] de {wereldkaart}',
    '[Abre] la {bitácora de viajes}': '[Open] het {reislogboek}',
    '[@]{jardin} [agradezco] {mi salud, mi familia y el café}': '[@]{jardin} [ik ben dankbaar voor] {mijn gezondheid, mijn familie en koffie}',
    '[Abre] la {meditación}': '[Open] de {meditatie}',
    '[Abre] la {respiración}': '[Open] de {ademhaling}',
    '[Abre] los {agradecimientos}': '[Open] de {dankbaarheid}',
    '[Abre] los {titulares}': '[Open] de {koppen}',
    'Avancé en mi [proyecto] de {acuarela} {40 min}': 'Ik werkte {40 min} aan mijn [project] met {aquarel}',
    'Practiqué {guitarra} {25 min}': 'Ik oefende {25 min} {gitaar}',
    '[Abre] mis {mapas mentales}': '[Open] mijn {mindmaps}',
    '[Abre] los {mapas conceptuales}': '[Open] de {conceptkaarten}',
    '[Hazme un mapa mental] de {la fotosíntesis}': '[Maak een mindmap voor me] over {fotosynthese}',
    '[Compara] {café} y {té} en un mapa': '[Vergelijk] {koffie} en {thee} in een conceptkaart',
    '[Tengo cita] con el {dentista} el {14 a las 5}': '[Ik heb een afspraak] bij de {tandarts} op de {14e om 17.00 uur}',
    '[Guarda el contacto] de {Ana}: {5512345678}, cumple el {3 de mayo}': '[Bewaar het contact] van {Anna}: {5512345678}, jarig op {3 mei}',
    '[Abre] mis {pendientes}': '[Open] mijn {taken}',
    '[Abre] mis {citas médicas}': '[Open] mijn {doktersafspraken}',
    '[Abre] mis {contactos}': '[Open] mijn {contacten}',
    '[Vocab] {inglés}: {dog} = {perro}': '[Woordjes] {Engels}: {dog} = {hond}',
    '[Abre] el {repaso}': '[Open] de {herhaling}',
    '[Abre] el {temario}': '[Open] het {leerplan}',
    '[Repasé] {francés} {15 min}': '[Ik herhaalde] {15 min} {Frans}',
    'Aprendí en {alemán}: {Hund} = {perro}': 'Ik leerde in het {Duits}: {Hund} = {hond}',
    '[Construye] un {huerto}': '[Bouw] een {moestuin}',
    '[Quiero sembrar] {zanahorias}': 'Ik wil {wortels} [zaaien]',
    '[Siembra] {maíz} en el huerto': '[Zaai] {maïs} in de moestuin',
    '[Pon] un {aspersor} en el huerto': '[Zet] een {sproeier} in de moestuin',
    '[Riega] el {huerto}': '[Sproei] de {moestuin}',
    '[Cosecha] el {huerto}': '[Oogst] de {moestuin}',
    '[Llévame] al {huerto}': '[Breng me] naar de {moestuin}',
    '[Haz] un {corral}': '[Maak] een {hok}',
    '[Pon] {vacas} en la granja': '[Zet] {koeien} op de boerderij',
    '[Alimenta] a los {animales}': '[Voer] de {dieren}',
    '[Mima] a los {animales}': '[Aai] de {dieren}',
    '[Cura] a los {animales}': '[Genees] de {dieren}',
    '[Limpia] los {corrales}': '[Maak] de {hokken} schoon',
    '[Llévame] a la {granja}': '[Breng me] naar de {boerderij}',
    '[Pon] una {pista de carreras}': '[Plaats] een {racebaan}',
    '[Traza] las {vías del tren}': '[Leg] de {treinrails}',
    '[Construye] una {montaña rusa}': '[Bouw] een {achtbaan}',
    '[Pon] la {meta} de la pista': '[Zet] de {finish} op de baan',
    '[Borra] la {pista}': '[Verwijder] de {racebaan}',
    '[Hagamos una carrera] {contra} un asistente': '[Laten we een race rijden] {tegen} een assistent',
    '[Corre una carrera] {fácil} de {5 vueltas}': '[Rij een race] van {5 ronden} op {makkelijk}',
    '[Quiero montar] el {tren}': 'Ik wil met de {trein} [rijden]',
    '[Quiero montar] la {montaña rusa}': 'Ik wil met de {achtbaan} [rijden]',
    '[Llévame] a la {meta}': '[Breng me] naar de {finish}',
    '[Paintball] campal en {difícil}': '[Paintball], iedereen tegen iedereen, op {moeilijk}',
    '[Pon] una {cancha de fútbol}': '[Plaats] een {voetbalveld}',
    '[Pon] una {cancha de tenis} {azul}': '[Plaats] een {blauwe} {tennisbaan}',
    '[Crea] una {cancha de básquet}': '[Maak] een {basketbalveld}',
    '[Pon] un {campo de béisbol}': '[Plaats] een {honkbalveld}',
    '[Llévame] a la {cancha}': '[Breng me] naar het {veld}',
    '[Abre] el {cronograma}': '[Open] de {planning}',
    '[Renombra] la {cocina} a {Oficina}': '[Hernoem] de {keuken} naar {Kantoor}',
    '[Cambia el ícono] de la {cocina} a {🍳}': '[Verander het icoon] van de {keuken} naar {🍳}',
    '[Pon] la {cocina} en categoría {cuerpo}': '[Zet] de {keuken} in de categorie {Lichaam}',
    '[Agrega] la {biblioteca} al mapa': '[Plaats] de {bibliotheek} op de kaart',
    '[Elimina] la {cocina}': '[Verwijder] de {keuken}',
    '[Abre] la {cocina}': '[Open] de {keuken}',
    '[Pinta] la {cocina} de {azul}': '[Verf] de {keuken} {blauw}',
    '[Piso] de la {cocina} de {madera}': 'Geef de {keuken} een [vloer] van {hout}',
    '[Piso] de la {cocina} {rojo}': 'Geef de {keuken} een [vloer] in {rood}',
    '[Techo] de la {cocina} de {tejas rojas}': 'Geef de {keuken} een [dak] van {rode dakpannen}',
    '[Techo a dos aguas] en la {cocina}': 'Zet een [zadeldak] op de {keuken}',
    '[Haz] la {cocina} {redonda}': '[Maak] de {keuken} {rond}',
    '[Agranda] la {cocina}': '[Vergroot] de {keuken}',
    '[Encoge] la {cocina}': '[Verklein] de {keuken}',
    '[Mueve] la {cocina} a la {derecha}': '[Verschuif] de {keuken} naar {rechts}',
    '[Abre el muro] {norte} de la {cocina}': '[Open de muur] aan de {noordkant} van de {keuken}',
    '[Pon una puerta] {corredera} en el muro {sur} de la {cocina}': '[Plaats een deur] in de muur aan de {zuidkant} van de {keuken}, als {schuifdeur}',
    '[Pon] {ladrillo} en el muro {este} de la {cocina}': '[Maak] de muur aan de {oostkant} van de {keuken} van {baksteen}',
    '[Haz más grueso] el muro {norte} de la {cocina}': '[Maak de muur dikker] aan de {noordkant} van de {keuken}',
    '[Apila] la {sala} sobre la {cocina}': '[Stapel] de {woonkamer} op de {keuken}',
    '[Agranda el mapa] hacia el {este}': '[Vergroot de kaart] naar het {oosten}',
    '[Pinta el último objeto] de {rojo}': '[Verf het laatste object] {rood}',
    '[Haz el último objeto] más {grande}': '[Maak het laatste object] {groter}',
    '[Agrupa los objetos] de la {cocina}': '[Groepeer de objecten] in de {keuken}',
    '[Genera en 3D] {una fuente de piedra} estilo {minimalista}': '[Genereer in 3D] {een stenen fontein} in {minimalistische} stijl',
    '[Ponme] {sombrero} {rojo}': '[Zet] me een {rode} {hoed} op',
    '[Quítame] los {lentes}': '[Doe] mijn {bril} af',
    '[Pinta el torso] del [avatar] de {verde}': '[Verf het bovenlijf] van de [avatar] {groen}',
    '[Haz el avatar] más {grande}': '[Maak de avatar] {groter}',
    '[Móntame] en la {bici}': '[Zet me] op de {fiets}',
    '[Quiero conducir] el {auto}': 'Ik wil de {auto} [besturen]',
    '[Vista] {isométrica}': '{Isometrisch} [beeld]',
    '[Cambia el tema] a {navidad}': '[Verander het thema] naar {kerst}',
    '[Fondo] {nieve}': '[Achtergrond] {sneeuw}',
    '[Pon música] {relajante}': '[Zet muziek aan] {om te ontspannen}',
    '[Abre] mi {resumen semanal}': '[Open] mijn {weekoverzicht}',
    '[Abre] mi {resumen mensual}': '[Open] mijn {maandoverzicht}',
    '[Modo] {oscuro}': '{Donkere} [modus]',
    '[Apariencia] {transparente}': '[Weergave] {transparant}',
    '[Cambia el idioma] a {inglés}': '[Verander de taal] naar {Engels}',
    '[Pon iconos] {profesionales}': '[Gebruik iconen] in {professionele} stijl',
    '[Estilo] {cómic}': '[Stijl] {comic}',
    '[Cómo funciona] la {cocina}': '[Hoe werkt] de {keuken}',
    '[Cómo funciona] la {rueda de herramientas}': '[Hoe werkt] het {gereedschapswiel}',
    '[Qué hace] el {inventario}': '[Wat doet] de {inventaris}',
    '[Tutorial de] {ejercicio}': '[Tutorial van] {Gym}',
    '[Tutorial de] la {biblioteca}': '[Tutorial van] de {bibliotheek}',
    '[Tutorial] {general}': '{Algemene} [tutorial]',
  },
  atajos: {
    'Caminar (también con las flechas)': 'Lopen (ook met de pijltjestoetsen)',
    'Correr (se queda puesto hasta volver a pulsar)': 'Rennen (blijft aan tot je nog eens drukt)',
    'Saltar': 'Springen',
    'Agacharse (mantener pulsado)': 'Bukken (ingedrukt houden)',
    'Lo que tengas delante: entrar al cuarto, subirte o bajarte del vehículo, cambiar de nivel': 'Wat er voor je staat: de kamer in, op of van het voertuig, van niveau wisselen',
    'Levantar la mano derecha / izquierda': 'Rechter- / linkerhand opsteken',
    'Bailar': 'Dansen',
    'Mortal': 'Salto',
    'Abrir la rueda de herramientas': 'Het gereedschapswiel openen',
    'Abrir el chat y escribir': 'De chat openen en typen',
    'Cambiar de vista: isométrica, tercera y primera persona': 'Van beeld wisselen: isometrisch, derde en eerste persoon',
    'Esconder o mostrar el HUD': 'De HUD verbergen of tonen',
    'Cerrar lo que esté abierto': 'Sluiten wat openstaat',
    'Conduciendo el OVNI: subir y bajar. En los demás vehículos, Espacio derrapa': 'In de ufo: omhoog en omlaag. In andere voertuigen laat Spatie je driften',
  },
  teclas: {
    'Mayús': 'Shift',
    'Espacio': 'Spatie',
    'Espacio · Mayús': 'Spatie · Shift',
  },
}
