import type { ManualTraducido } from './manualI18n'

/**
 * Las frases de ejemplo del manual de comandos en tr, indexadas por su
 * texto español de origen (ver `manualI18n.ts`).
 *
 * GENERADO por `npm run traducir:contenido` — no lo edites a mano.
 */
export const MANUAL_TR: ManualTraducido = {
  frases: {
    '[Corrí] {5 km} en {30 min}': '{5 km} {30 dakikada} [koştum]',
    '[@]{cocina} [comí] {una ensalada}': '[@]{cocina} {bir salata} [yedim]',
    '[Abre] el {estudio de audio}': '{Ses stüdyosunu} [aç]',
    '[Abre] mis {canciones}': '{Şarkılarımı} [aç]',
    '[Abre] el {mezclador DJ}': '{DJ mikserini} [aç]',
    '[Abre] la {galería de arte}': '{Sanat galerisini} [aç]',
    '[Abre] mis {dibujos}': '{Çizimlerimi} [aç]',
    '[Abre] mis {libros}': '{Kitaplarımı} [aç]',
    '[Abre] el {estudio de escritura}': '{Yazı stüdyosunu} [aç]',
    '[Escribe un cuento] sobre {un faro en invierno} y [guárdalo en mis libros]': '{Kışın bir deniz feneri} hakkında [bir öykü yaz] ve [kitaplarıma kaydet]',
    '[Guarda en mis libros] este texto: {Querido diario, hoy…}': 'Bu metni [kitaplarıma kaydet]: {Sevgili günlük, bugün…}',
    '[Abre] el {editor de video}': '{Video editörünü} [aç]',
    '[Abre] mis {videos}': '{Videolarımı} [aç]',
    '[Abre] la {animación 3D}': '{3D animasyonu} [aç]',
    "[Abre] {mis archivos}": "{Dosyalarımı} [aç]",
    "[Abre] los {archivos recientes}": "{Son dosyaları} [aç]",
    "[Abre] los {archivos del studio}": "{Studio dosyalarını} [aç]",
    "[Abre] la {papelera}": "{Çöp kutusunu} [aç]",
    "[Abre] los {archivos destacados}": "{Yıldızlı dosyaları} [aç]",
    '[Tomé] {2 vasos} de [agua]': '{2 bardak} [su] [içtim]',
    '[Me pesé]: {74 kg}': '[Tartıldım]: {74 kg}',
    '[Abre] el {recetario}': '{Tarif defterini} [aç]',
    '[Abre] la {lista del súper}': '{Alışveriş listesini} [aç]',
    '[Abre] el {diario de comidas}': '{Yemek günlüğünü} [aç]',
    '[Abre] las {metas de nutrición}': '{Beslenme hedeflerini} [aç]',
    'Inventa una [receta] {ligera con atún}': '{Ton balıklı, hafif} bir [tarif] uydur',
    'Arma una [dieta] {alta en proteína}': '{Proteini yüksek} bir [diyet] hazırla',
    'Agrega {plátano y avena} a la [lista del súper]': '[Alışveriş listesine] {muz ve yulaf} ekle',
    '[Corrí] {5 km}': '{5 km} [koştum]',
    '[Abre] el {plan de ejercicio}': '{Egzersiz planını} [aç]',
    '[Abre] las {metas de ejercicio}': '{Egzersiz hedeflerini} [aç]',
    '[Muéstrame] cómo se hace el {press banca}': '{Bench press} nasıl yapılır [göster]',
    '[Haz] una {sentadilla}': 'Bir {squat} [yap]',
    'Registra mi sesión: {crossfit 40 min, intensidad alta}': 'Seansımı kaydet: {crossfit 40 dk, yüksek tempo}',
    '[Arma una rutina] de {pecho y tríceps} de {45 min}': '{Göğüs ve arka kol} için {45 dk}lık bir [rutin hazırla]',
    '[Dormí] {7 horas}, calidad {4/5}': '{7 saat} [uyudum], kalite {4/5}',
    '[Abre] el {despertador}': '{Çalar saati} [aç]',
    '{Me acosté a las 23, desperté a las 7 y me levanté 2 veces}': '{23\'te yattım, 7\'de uyandım, 2 kez kalktım}',
    '[Recuerdo]: {tarde de juegos con mi hermana}': '[Anı]: {kız kardeşimle oyun akşamı}',
    '[Abre] el {calendario de ánimo}': '{Ruh hali takvimini} [aç]',
    'Anota esta anécdota: {hoy celebramos el cumple de mamá}': 'Bu anıyı kaydet: {bugün annemin doğum gününü kutladık}',
    '[Cobré] {8000} de {la quincena}': '{Maaştan} {8000} [aldım]',
    '[Abre] los {gastos fijos}': '{Sabit giderleri} [aç]',
    '[Abre] las {metas de ahorro}': '{Birikim hedeflerini} [aç]',
    '{Pagué 250 de luz y 180 de agua}': '{250 elektrik, 180 su ödedim}',
    '[Abre] el {formulario}': '{Formül defterini} [aç]',
    '[Resolver ecuación]': '[Denklem çöz]',
    '[Convertir unidades]': '[Birim çevir]',
    '[Sistema de ecuaciones]': '[Denklem sistemi]',
    '[Convertir a binario]': '[İkiliye çevir]',
    '[Propina]': '[Bahşiş]',
    '[Regla de tres]': '[Orantı hesabı]',
    '[Estudié] {historia romana} {30 min}': '{30 dk} {Roma tarihi} [çalıştım]',
    '[Abre] la {sesión de estudio}': '{Çalışma seansını} [aç]',
    '[Abre] el {resumen de estudio}': '{Çalışma özetini} [aç]',
    'Apunta que aprendí: {los ríos de Europa}': 'Öğrendiğimi not al: {Avrupa\'nın nehirleri}',
    '[Vi la película] {Dune}': '{Dune} [filmini izledim]',
    '[Abre] la {mesa de juegos}': '{Oyun masasını} [aç]',
    'Apunta {la serie Dark} como pendiente': '{Dark dizisini} izlenecekler listeme ekle',
    '[Abre] el {mapamundi}': '{Dünya haritasını} [aç]',
    '[Abre] la {bitácora de viajes}': '{Gezi seyir defterini} [aç]',
    '[Visité] {Oaxaca}': '{Oaxaca}\'ya [gittim]',
    '[Abre] {por conocer}': '{Görmek istediklerimi} [aç]',
    '[Medité] {10 min}': '{10 dk} [meditasyon yaptım]',
    '[@]{jardin} [agradezco] {mi salud, mi familia y el café}': '[@]{jardin} {sağlığım, ailem ve kahve} için [şükrediyorum]',
    '[Abre] el {resumen del garage}': '{Garaj özetini} [aç]',
    '[Abre] {mis vehículos}': '{Araçlarımı} [aç]',
    '[Abre] las {efemérides}': '{Tarihte bugünü} [aç]',
    '[Abre] mis {mapas mentales}': '{Zihin haritalarımı} [aç]',
    '[Abre] los {mapas conceptuales}': '{Kavram haritalarını} [aç]',
    '[Dibuja un diagrama de flujo] de {cómo hacer pan}': '{Ekmek nasıl yapılır} [akış şeması çiz]',
    '[Haz un esquema] de {lo que me acabas de explicar}': '{Az önce anlattığının} [şemasını yap]',
    '[Agenda] una {junta con el cliente} el {martes a las 10}': '{Salı saat 10\'a} bir {müşteri toplantısı} [planla]',
    '[Apunta el pendiente] {mandar la cotización}': '{Teklifi gönder} [görevini not al]',
    '[Recuérdame] tomar {ibuprofeno} a las {8 y a las 20}': '{8\'de ve 20\'de} {ibuprofen} almayı [hatırlat]',
    '[Abre] mis {pendientes}': '{Görevlerimi} [aç]',
    '[Abre] mis {citas médicas}': '{Doktor randevularımı} [aç]',
    '[Abre] el {progreso de idiomas}': '{Dil ilerlememi} [aç]',
    '[Construye] un {huerto}': 'Bir {sebze bahçesi} [kur]',
    '[Pon] una {pista de carreras}': 'Bir {yarış pisti} [koy]',
    '[Traza] las {vías del tren}': '{Tren raylarını} [döşe]',
    '[Construye] una {montaña rusa}': 'Bir {hız treni} [kur]',
    '[Pon] la {meta} de la pista': 'Pistin {bitiş çizgisini} [koy]',
    '[Corre una carrera] de {3 vueltas}': '{3 turluk} [bir yarış yap]',
    '[Quiero montar] la {montaña rusa}': '{Hız trenine} [binmek istiyorum]',
    '[Llévame] a la {meta}': '[Beni] {bitiş çizgisine} [götür]',
    '[Pon] una {cancha de fútbol}': 'Bir {futbol sahası} [koy]',
    '[Juguemos paintball] {2v2}': '{2v2} [paintball oynayalım]',
    '[Reta] a {Luna} a un paintball {1v1}': '{Luna}\'yı {1v1} paintball\'a [davet et]',
    '[Crea] una {cancha de básquet}': 'Bir {basketbol sahası} [oluştur]',
    '[Pon] un {campo de béisbol}': 'Bir {beyzbol sahası} [ekle]',
    '[Abre] la {agenda de hoy}': '{Bugünün ajandasını} [aç]',
    '[Abre] {mi semana}': '{Haftamı} [aç]',
    '[Crea una rutina] de mañana: {agua, estiramiento y gratitud} a las {7:00}': 'Sabahlar için [bir rutin oluştur]: {7:00}\'de {su, esneme ve şükran}',
    '[Crea una rutina] de {lunes y miércoles}: {correr 20 min}': '{Pazartesi ve çarşamba} için [bir rutin oluştur]: {20 dakika koşu}',
    '[Gira el último objeto]': '[Son nesneyi döndür]',
    '[Quita el último objeto]': '[Son nesneyi kaldır]',
    '[Genera en 3D] {un dragón morado}': '{Mor bir ejderha} [3B oluştur]',
    '[Crea una imagen] de {un atardecer en la playa}': '{Sahilde gün batımı} [görseli oluştur]',
    '[Bájame]': '[İndir beni]',
    '[Vista en] {primera persona}': '{Birinci şahıs} [görünümü]',
    '[Quita el tema]': '[Temayı kaldır]',
    '[Volumen] al {40%}': '[Ses] {%40}\'a',
    '[Apaga la música]': '[Müziği kapat]',
    '[Abre] mi {resumen semanal}': '{Haftalık özetimi} [aç]',
    '[Abre] mi {resumen mensual}': '{Aylık özetimi} [aç]',
    '[Transparencia] al {40%}': '[Saydamlık] {%40}\'a',
    '[Apaga los efectos]': '[Efektleri kapat]',
    '[Música] {chiptune}': '[Müzik] {chiptune}',
    '[Avísame de mis metas] a las {21:00}': '{21:00}\'de [hedeflerimi hatırlat]',
    '[Apaga los avisos]': '[Bildirimleri kapat]',
    '[Descarga un respaldo] de mis datos': 'Verilerimin [yedeğini indir]',
    '[Vuelve a ver la bienvenida]': '[Karşılamayı tekrar göster]',
    '[Abre las configuraciones]': '[Ayarları aç]',
    '[@]{cocina} {ensalada de la comida}': '[@]{cocina} {öğle yemeğine salata}',
    '[Cómo funciona] la {rueda de herramientas}': '{Araç çarkı} [nasıl çalışır]',
    '[Abre] {ejemplo.com}': '[Aç] {ornek.com}',
    '[Busca en internet] {recetas de pan}': '[İnternette ara] {ekmek tarifleri}',
    '[Historial]': '[Geçmiş]',
    '[Sitios]': '[Siteler]',
    '[Tiempo en internet]': '[İnternet süresi]',
    '[Cómo llegar]': '[Yol tarifi]',
    '[Amigos]': '[Arkadaşlar]',
    '[Jugar] {paintball} [con] {@ana}': '{@ana} [ile] {paintball} [oyna]',
  },
  atajos: {
    'Caminar (también con las flechas)': 'Yürü (ok tuşlarıyla da olur)',
    'Correr (se queda puesto hasta volver a pulsar)': 'Koş (tekrar basana kadar açık kalır)',
    'Saltar': 'Zıpla',
    'Agacharse (mantener pulsado)': 'Eğil (basılı tut)',
    'Lo que tengas delante: entrar al cuarto, subirte o bajarte del vehículo, cambiar de nivel': 'Önünde ne varsa: odaya gir, araca bin ya da in, kat değiştir',
    'Levantar la mano derecha / izquierda': 'Sağ / sol elini kaldır',
    'Bailar': 'Dans et',
    'Mortal': 'Takla',
    'Abrir la rueda de herramientas': 'Alet çarkını aç',
    'Abrir el chat y escribir': 'Sohbeti aç ve yaz',
    'Cambiar de vista: isométrica, tercera y primera persona': 'Görünümü değiştir: izometrik, üçüncü ve birinci şahıs',
    'Esconder o mostrar el HUD': 'HUD\'u gizle ya da göster',
    'Cerrar lo que esté abierto': 'Açık olan neyse kapat',
    'Conduciendo el OVNI: subir y bajar. En los demás vehículos, Espacio derrapa': 'UFO\'yu kullanırken: yüksel ve alçal. Diğer araçlarda Boşluk tuşu drift yaptırır',
  },
  teclas: {
    'Mayús': 'Shift',
    'Espacio': 'Boşluk',
    'Espacio · Mayús': 'Boşluk · Shift',
  },
}
