import type { ManualTraducido } from './manualI18n'

/**
 * Las frases de ejemplo del manual de comandos en ru, indexadas por su
 * texto español de origen (ver `manualI18n.ts`).
 *
 * GENERADO por `npm run traducir:contenido` — no lo edites a mano.
 */
export const MANUAL_RU: ManualTraducido = {
  frases: {
    '[Corrí] {5 km} en {30 min}': '[Пробежал] {5 км} за {30 мин}',
    '[@]{cocina} [comí] {una ensalada}': '[@]{cocina} [съел] {салат}',
    '[Abre] el {estudio de audio}': '[Открой] {аудиостудию}',
    '[Abre] mis {canciones}': '[Открой] мои {песни}',
    '[Abre] el {mezclador DJ}': '[Открой] {DJ-микшер}',
    '[Abre] la {galería de arte}': '[Открой] {галерею}',
    '[Abre] mis {dibujos}': '[Открой] мои {рисунки}',
    '[Abre] mis {libros}': '[Открой] мои {книги}',
    '[Abre] el {estudio de escritura}': '[Открой] {студию письма}',
    '[Escribe un cuento] sobre {un faro en invierno} y [guárdalo en mis libros]': '[Напиши рассказ] о {маяке зимой} и [сохрани его в мои книги]',
    '[Guarda en mis libros] este texto: {Querido diario, hoy…}': '[Сохрани в мои книги] этот текст: {Дорогой дневник, сегодня…}',
    '[Abre] el {editor de video}': '[Открой] {видеоредактор}',
    '[Abre] mis {videos}': '[Открой] мои {видео}',
    '[Abre] la {animación 3D}': '[Открой] {3D-анимацию}',
    "[Abre] {mis archivos}": "[Открой] {мои файлы}",
    "[Abre] los {archivos recientes}": "[Открой] {недавние файлы}",
    "[Abre] los {archivos del studio}": "[Открой] {файлы студии}",
    "[Abre] la {papelera}": "[Открой] {корзину}",
    "[Abre] los {archivos destacados}": "[Открой] {помеченные файлы}",
    '[Tomé] {2 vasos} de [agua]': '[Выпил] {2 стакана} [воды]',
    '[Me pesé]: {74 kg}': '[Взвесился]: {74 кг}',
    '[Abre] el {recetario}': '[Открой] {книгу рецептов}',
    '[Abre] la {lista del súper}': '[Открой] {список покупок}',
    '[Abre] el {diario de comidas}': '[Открой] {дневник питания}',
    '[Abre] las {metas de nutrición}': '[Открой] {цели по питанию}',
    'Inventa una [receta] {ligera con atún}': 'Придумай [рецепт] {лёгкий, с тунцом}',
    'Arma una [dieta] {alta en proteína}': 'Составь [диету] {с высоким содержанием белка}',
    'Agrega {plátano y avena} a la [lista del súper]': 'Добавь {бананы и овсянку} в [список покупок]',
    '[Corrí] {5 km}': '[Пробежал] {5 км}',
    '[Abre] el {plan de ejercicio}': '[Открой] {план тренировок}',
    '[Abre] las {metas de ejercicio}': '[Открой] {цели по тренировкам}',
    '[Muéstrame] cómo se hace el {press banca}': '[Покажи], как делать {жим лёжа}',
    'Registra mi sesión: {crossfit 40 min, intensidad alta}': 'Запиши мою тренировку: {кроссфит 40 мин, высокая интенсивность}',
    '[Arma una rutina] de {pecho y tríceps} de {45 min}': '[Составь рутину] на {грудь и трицепс} на {45 мин}',
    '[Dormí] {7 horas}, calidad {4/5}': '[Спал] {7 часов}, качество {4/5}',
    '[Abre] el {despertador}': '[Открой] {будильник}',
    '[Abre] {mi sueño}': '[Открой] {мой сон}',
    '{Me acosté a las 23, desperté a las 7 y me levanté 2 veces}': '{Лёг в 23, проснулся в 7, вставал 2 раза}',
    '[Recuerdo]: {tarde de juegos con mi hermana}': '[Воспоминание]: {вечер настолок с сестрой}',
    '[Abre] el {calendario de ánimo}': '[Открой] {календарь настроения}',
    'Anota esta anécdota: {hoy celebramos el cumple de mamá}': 'Запиши это воспоминание: {сегодня отмечали мамин день рождения}',
    '[Cobré] {8000} de {la quincena}': '[Получил] {8000} {зарплаты за полмесяца}',
    '[Abre] los {gastos fijos}': '[Открой] {постоянные расходы}',
    '[Abre] las {metas de ahorro}': '[Открой] {цели по накоплениям}',
    '{Pagué 250 de luz y 180 de agua}': '{Заплатил 250 за свет и 180 за воду}',
    '[Abre] el {formulario}': '[Открой] {справочник формул}',
    '[Resolver ecuación]': '[Решить уравнение]',
    '[Convertir unidades]': '[Перевести единицы]',
    '[Sistema de ecuaciones]': '[Система уравнений]',
    '[Convertir a binario]': '[Перевести в двоичную]',
    '[Propina]': '[Чаевые]',
    '[Regla de tres]': '[Пропорция]',
    '[Estudié] {historia romana} {30 min}': '[Изучал] {историю Рима} {30 мин}',
    '[Abre] la {sesión de estudio}': '[Открой] {учебную сессию}',
    '[Abre] el {resumen de estudio}': '[Открой] {итоги учёбы}',
    'Apunta que aprendí: {los ríos de Europa}': 'Запиши, что я выучил: {реки Европы}',
    '[Abre] la {mesa de juegos}': '[Открой] {игровой стол}',
    'Apunta {la serie Dark} como pendiente': 'Запиши {сериал Dark} в список к просмотру',
    '[Abre] el {mapamundi}': '[Открой] {карту мира}',
    '[Abre] {por conocer}': '[Открой] {список желаний}',
    '[Abre] la {bitácora de viajes}': '[Открой] {путевой дневник}',
    '[Medité] {10 min}': '[Медитация] {10 мин}',
    '[Abre] el {resumen del garage}': '[Открой] {сводку по гаражу}',
    '[Abre] {mis vehículos}': '[Открой] {мои машины}',
    '[Abre] las {efemérides}': '[Открой] {этот день в истории}',
    '[Abre] {mis hobbies}': '[Открой] {мои хобби}',
    '[Abre] mis {mapas mentales}': '[Открой] мои {ментальные карты}',
    '[Abre] los {mapas conceptuales}': '[Открой] {концептуальные карты}',
    '[Dibuja un diagrama de flujo] de {cómo hacer pan}': '[Нарисуй блок-схему] {как испечь хлеб}',
    '[Haz un esquema] de {lo que me acabas de explicar}': '[Сделай схему] {того, что ты только что объяснил}',
    '[Agenda] una {junta con el cliente} el {martes a las 10}': '[Запланируй] {встречу с клиентом} на {вторник в 10}',
    '[Apunta el pendiente] {mandar la cotización}': '[Запиши задачу] {отправить смету}',
    '[Abre] mis {pendientes}': '[Открой] мои {задачи}',
    '[Abre] mis {citas médicas}': '[Открой] мои {приёмы у врача}',
    '[Abre] el {progreso de idiomas}': '[Открой] {прогресс по языкам}',
    '[Construye] un {huerto}': '[Построй] {огород}',
    '[Pon] una {pista de carreras}': '[Поставь] {гоночную трассу}',
    '[Traza] las {vías del tren}': '[Проложи] {железную дорогу}',
    '[Construye] una {montaña rusa}': '[Построй] {американские горки}',
    '[Pon] la {meta} de la pista': '[Поставь] {финиш} на трассе',
    '[Corre una carrera] de {3 vueltas}': '[Устрой гонку] на {3 круга}',
    '[Quiero montar] la {montaña rusa}': '[Хочу прокатиться] на {американских горках}',
    '[Llévame] a la {meta}': '[Отведи меня] к {финишу}',
    '[Pon] una {cancha de fútbol}': '[Поставь] {футбольную площадку}',
    '[@]{jardin} [agradezco] {mi salud, mi familia y el café}': '[@]{jardin} [благодарность за] {здоровье, семью и кофе}',
    '[Crea] una {cancha de básquet}': '[Создай] {баскетбольную площадку}',
    '[Pon] un {campo de béisbol}': '[Добавь] {бейсбольное поле}',
    '[Abre] la {agenda de hoy}': '[Открой] {повестку на сегодня}',
    '[Abre] {mi semana}': '[Открой] {мою неделю}',
    '[Crea una rutina] de mañana: {agua, estiramiento y gratitud} a las {7:00}': '[Создай рутину] на утро: {вода, растяжка и благодарность} в {7:00}',
    '[Crea una rutina] de {lunes y miércoles}: {correr 20 min}': '[Создай рутину] на {понедельник и среду}: {пробежка 20 мин}',
    '[Gira el último objeto]': '[Поверни последний объект]',
    '[Quita el último objeto]': '[Убери последний объект]',
    '[Genera en 3D] {un dragón morado}': '[Сгенерируй в 3D] {фиолетового дракона}',
    '[Crea una imagen] de {un atardecer en la playa}': '[Создай картинку] с {закатом на пляже}',
    '[Bájame]': '[Ссади меня]',
    '[Vista en] {primera persona}': '[Вид от] {первого лица}',
    '[Quita el tema]': '[Убери тему]',
    '[Volumen] al {40%}': '[Громкость] на {40%}',
    '[Apaga la música]': '[Выключи музыку]',
    '[Abre] mi {resumen semanal}': '[Открой] мою {сводку за неделю}',
    '[Abre] mi {resumen mensual}': '[Открой] мою {сводку за месяц}',
    '[Transparencia] al {40%}': '[Прозрачность] на {40%}',
    '[Apaga los efectos]': '[Выключи эффекты]',
    '[Avísame de mis metas] a las {21:00}': '[Напоминай мне о целях] в {21:00}',
    '[Apaga los avisos]': '[Выключи уведомления]',
    '[Descarga un respaldo] de mis datos': '[Скачай резервную копию] моих данных',
    '[Vuelve a ver la bienvenida]': '[Покажи приветствие снова]',
    '[Abre las configuraciones]': '[Открой настройки]',
    '[Recuerda que] {soy vegetariano}': '[Запомни, что] {я не ем мясо}',
    '[Cómo funciona] la {rueda de herramientas}': '[Как работает] {колесо инструментов}',
    '[@]{cocina} {ensalada de la comida}': '[@]{cocina} {салат на обед}',
    '[Abre] {ejemplo.com}': '[Открой] {example.com}',
    '[Busca en internet] {recetas de pan}': '[Поищи в интернете] {рецепты хлеба}',
    '[Historial]': '[История]',
    '[Sitios]': '[Сайты]',
    '[Tiempo en internet]': '[Время в интернете]',
    '[Cómo llegar]': '[Как добраться]',
    '[Amigos]': '[Друзья]',
    '[Comí] {pollo con arroz} en la {cena}': '[Съел] {курицу с рисом} на {ужин}',
    '[Abre] la {dieta}': '[Открой] {диету}',
    '[Entrené] {pierna} {45 min}': '[Тренировал] {ноги} {45 мин}',
    '[Abre] {fuerza}': '[Открой] {силовые}',
    '[Abre] {cardio}': '[Открой] {выносливость}',
    '[Abre] {flexibilidad}': '[Открой] {гибкость}',
    '[Haz] una {sentadilla}': '[Сделай] {приседание}',
    '[Arma una rutina] de {estiramientos} para {la espalda baja}': '[Составь рутину] на {растяжку} для {поясницы}',
    '[Abre] mis {anécdotas}': '[Открой] мои {воспоминания}',
    '[Gasté] {500} en {el súper}': '[Потратил] {500} на {продукты}',
    '[Abre] el {balance}': '[Открой] {денежный поток}',
    '[Abre] los {movimientos}': '[Открой] {операции}',
    '[Abre] las {divisas}': '[Открой] {форекс}',
    '[Abre] las {criptomonedas}': '[Открой] {крипто}',
    '[Abre] las {materias primas}': '[Открой] {сырьё}',
    '[Abre] la {calculadora}': '[Открой] {калькулятор}',
    '[Abre] el {graficador}': '[Открой] {графики}',
    '[Abre] las {hojas de cálculo}': '[Открой] {таблицы}',
    '[Abre] las {matrices}': '[Открой] {матрицы}',
    '[Abre] las {charlas}': '[Открой] {чаты}',
    '[Abre] la {enciclopedia}': '[Открой] {энциклопедию}',
    '[Vi la película] {Dune}': '[Посмотрел фильм] {Дюна}',
    '[Jugué] {ajedrez} con mi hermano': '[Сыграл в] {шахматы} с братом',
    '[Abre] el {archivo}': '[Открой] {архив}',
    '[Quiero jugar] la {viborita}': '[Хочу сыграть в] {змейку}',
    '[Juega] {tetris}': '[Запусти] {тетрис}',
    '[Juega] una partida de {ajedrez}': '[Запусти] партию в {шахматы}',
    '[Abre] las {rutas}': '[Открой] {маршруты}',
    '[Visité] {Oaxaca}': '[Побывал в] {Стамбуле}',
    'Quiero conocer {Japón}': 'Хочу побывать в {Японии}',
    '[Visité] {Roma}: {la fontana de noche es mágica}': '[Побывал в] {Риме}: {ночью фонтан просто волшебный}',
    '[Abre] la {meditación}': '[Открой] {медитацию}',
    '[Abre] la {respiración}': '[Открой] {дыхание}',
    '[Abre] los {agradecimientos}': '[Открой] {благодарность}',
    '[Abre] los {titulares}': '[Открой] {заголовки}',
    'Avancé en mi [proyecto] de {acuarela} {40 min}': 'Поработал над своим [проектом] по {акварели} {40 мин}',
    'Practiqué {guitarra} {25 min}': 'Позанимался на {гитаре} {25 мин}',
    '[Hazme un mapa mental] de {la fotosíntesis}': '[Сделай мне ментальную карту] о {фотосинтезе}',
    '[Compara] {café} y {té} en un mapa': '[Сравни] {кофе} и {чай} в виде карты',
    '[Tengo cita] con el {dentista} el {14 a las 5}': '[У меня приём] у {стоматолога} {14-го в 5}',
    '[Recuérdame] tomar {ibuprofeno} a las {8 y a las 20}': '[Напоминай мне] принимать {ибупрофен} в {8:00 и 20:00}',
    '[Guarda el contacto] de {Ana}: {5512345678}, cumple el {3 de mayo}': '[Сохрани контакт] {Анна}: {9161234567}, день рождения {3 мая}',
    '[Abre] mis {contactos}': '[Открой] мои {контакты}',
    '[Vocab] {inglés}: {dog} = {perro}': '[Слова] {английский}: {dog} = {собака}',
    '[Abre] el {tutor}': '[Открой] {репетитора}',
    '[Abre] el {repaso}': '[Открой] {повторение}',
    '[Abre] el {temario}': '[Открой] {учебную программу}',
    '[Repasé] {francés} {15 min}': '[Повторял] {французский} {15 мин}',
    'Aprendí en {alemán}: {Hund} = {perro}': 'Выучил по-{немецки}: {Hund} = {собака}',
    '[Quiero sembrar] {zanahorias}': '[Хочу посадить] {морковь}',
    '[Siembra] {maíz} en el huerto': '[Посади] {кукурузу} на огороде',
    '[Pon] un {aspersor} en el huerto': '[Поставь] {разбрызгиватель} на огороде',
    '[Riega] el {huerto}': '[Полей] {огород}',
    '[Cosecha] el {huerto}': '[Собери урожай] с {огорода}',
    '[Llévame] al {huerto}': '[Отведи меня] на {огород}',
    '[Haz] un {corral}': '[Сделай] {загон}',
    '[Pon] {vacas} en la granja': '[Добавь] {коров} на ферму',
    '[Alimenta] a los {animales}': '[Накорми] {животных}',
    '[Mima] a los {animales}': '[Приласкай] {животных}',
    '[Cura] a los {animales}': '[Вылечи] {животных}',
    '[Limpia] los {corrales}': '[Почисти] {загоны}',
    '[Llévame] a la {granja}': '[Отведи меня] на {ферму}',
    '[Borra] la {pista}': '[Удали] {трассу}',
    '[Hagamos una carrera] {contra} un asistente': '[Давай устроим гонку] {против} помощника',
    '[Corre una carrera] {fácil} de {5 vueltas}': '[Устрой гонку] {лёгкой} сложности на {5 кругов}',
    '[Quiero montar] el {tren}': '[Хочу прокатиться] на {поезде}',
    '[Juguemos] {paintball}': '[Давай сыграем в] {пейнтбол}',
    '[Juguemos paintball] {2v2}': '[Давай сыграем в пейнтбол] {2 на 2}',
    '[Reta] a {Luna} a un paintball {1v1}': '[Вызови] {Луну} на пейнтбол {1 на 1}',
    '[Paintball] campal en {difícil}': '[Пейнтбол] «все против всех» на {сложном}',
    '[Sal] del {paintball}': '[Выйди] из {пейнтбола}',
    '[Pon] una {cancha de tenis} {azul}': '[Поставь] {синюю} {теннисную площадку}',
    '[Llévame] a la {cancha}': '[Отведи меня] на {площадку}',
    '[Abre] el {cronograma}': '[Открой] {расписание}',
    '[Enséñame] las {rutinas}': '[Покажи мне] {рутины}',
    '[Crea un cuarto] llamado {Estudio}': '[Создай комнату] с названием {Кабинет}',
    '[Renombra] la {cocina} a {Oficina}': '[Переименуй] {кухню} в {Офис}',
    '[Cambia el ícono] de la {cocina} a {🍳}': '[Смени иконку] {кухни} на {🍳}',
    '[Pon] la {cocina} en categoría {cuerpo}': '[Перенеси] {кухню} в категорию {тело}',
    '[Agrega] la {biblioteca} al mapa': '[Добавь] {библиотеку} на карту',
    '[Elimina] la {cocina}': '[Удали] {кухню}',
    '[Abre] la {cocina}': '[Открой] {кухню}',
    '[Pinta] la {cocina} de {azul}': '[Покрась] {кухню} в {синий}',
    '[Piso] de la {cocina} de {madera}': '[Пол] в {кухне} — {дерево}',
    '[Piso] de la {cocina} {rojo}': '[Пол] в {кухне} — {красный}',
    '[Techo] de la {cocina} de {tejas rojas}': '[Крыша] над {кухней} — {красная черепица}',
    '[Techo a dos aguas] en la {cocina}': '[Двускатная крыша] на {кухне}',
    '[Haz] la {cocina} {redonda}': '[Сделай] {кухню} {круглой}',
    '[Agranda] la {cocina}': '[Увеличь] {кухню}',
    '[Encoge] la {cocina}': '[Уменьши] {кухню}',
    '[Mueve] la {cocina} a la {derecha}': '[Передвинь] {кухню} {вправо}',
    '[Abre el muro] {norte} de la {cocina}': '[Открой стену] с {северной} стороны {кухни}',
    '[Pon una puerta] {corredera} en el muro {sur} de la {cocina}': '[Поставь дверь] {раздвижного} типа в {южной} стене {кухни}',
    '[Pon] {ladrillo} en el muro {este} de la {cocina}': '[Сделай] {восточную} стену {кухни} {кирпичной}',
    '[Haz más grueso] el muro {norte} de la {cocina}': '[Сделай толще] {северную} стену {кухни}',
    '[Apila] la {sala} sobre la {cocina}': '[Поставь] {гостиную} над {кухней}',
    '[Agranda el mapa] hacia el {este}': '[Расширь карту] на {восток}',
    '[Crea] una {lámpara}': '[Создай] {лампу}',
    '[Pinta el último objeto] de {rojo}': '[Покрась последний объект] в {красный}',
    '[Haz el último objeto] más {grande}': '[Сделай последний объект] {больше}',
    '[Agrupa los objetos] de la {cocina}': '[Сгруппируй объекты] {кухни}',
    '[Genera en 3D] {una fuente de piedra} estilo {minimalista}': '[Сгенерируй в 3D] {каменный фонтан} в стиле {минимализма}',
    '[Ponme] {sombrero} {rojo}': '[Надень мне] {красную} {шляпу}',
    '[Quítame] los {lentes}': '[Сними с меня] {очки}',
    '[Pinta el torso] del [avatar] de {verde}': '[Покрась туловище] [аватара] в {зелёный}',
    '[Haz el avatar] más {grande}': '[Сделай аватар] {больше}',
    '[Móntame] en la {bici}': '[Посади меня] на {велосипед}',
    '[Quiero conducir] el {auto}': '[Хочу сесть за руль] {машины}',
    '[Vista] {isométrica}': '[Вид] {изометрия}',
    '[Cambia el tema] a {navidad}': '[Смени тему] на {Рождество}',
    '[Fondo] {nieve}': '[Фон] {снег}',
    '[Pon música] {relajante}': '[Включи музыку] для {расслабления}',
    '[Música] {chiptune}': '[Музыка] {chiptune}',
    '[Modo] {oscuro}': '[Режим] {тёмный}',
    '[Apariencia] {transparente}': '[Оформление] {прозрачное}',
    '[Cambia el idioma] a {inglés}': '[Смени язык] на {английский}',
    '[Tema de interfaz] {neón}': '[Тема интерфейса] {неон}',
    '[Tipografía] {serif}': '[Шрифт] {серифный}',
    '[Estilo de la interfaz] {pixel}': '[Стиль интерфейса] {пиксель}',
    '[Pon iconos] {profesionales}': '[Поставь иконки] {профессионального} стиля',
    '[Estilo] {cómic}': '[Стиль] {комикс}',
    '[Avísame] de mis {rutinas}': '[Напоминай мне] о моих {рутинах}',
    '[Abre] mi {cuenta}': '[Открой] мой {аккаунт}',
    '[Cómo funciona] la {cocina}': '[Как работает] {кухня}',
    '[Cómo funciona] el {editor}': '[Как работает] {редактор}',
    '[Cómo funciona] el {chat}': '[Как работает] {чат}',
    '[Qué hace] el {inventario}': '[Что делает] {инвентарь}',
    '[Para qué sirve] la {cámara}': '[Для чего нужна] {камера}',
    '[Tutorial de] {ejercicio}': '[Обучение по] {спортзалу}',
    '[Tutorial de] la {biblioteca}': '[Обучение по] {библиотеке}',
    '[Tutorial] {general}': '{Общее} [обучение]',
  },
  atajos: {
    'Caminar (también con las flechas)': 'Ходить (можно и стрелками)',
    'Correr (se queda puesto hasta volver a pulsar)': 'Бежать (остаётся включённым, пока не нажмёшь снова)',
    'Saltar': 'Прыжок',
    'Agacharse (mantener pulsado)': 'Присесть (удерживай)',
    'Lo que tengas delante: entrar al cuarto, subirte o bajarte del vehículo, cambiar de nivel': 'То, что перед тобой: войти в комнату, сесть в транспорт или выйти, сменить этаж',
    'Levantar la mano derecha / izquierda': 'Поднять правую / левую руку',
    'Bailar': 'Танцевать',
    'Mortal': 'Сальто',
    'Abrir la rueda de herramientas': 'Открыть колесо инструментов',
    'Abrir el chat y escribir': 'Открыть чат и писать',
    'Cambiar de vista: isométrica, tercera y primera persona': 'Сменить вид: изометрия, от третьего и от первого лица',
    'Esconder o mostrar el HUD': 'Скрыть или показать HUD',
    'Cerrar lo que esté abierto': 'Закрыть то, что открыто',
    'Conduciendo el OVNI: subir y bajar. En los demás vehículos, Espacio derrapa': 'За штурвалом НЛО: вверх и вниз. В остальном транспорте Пробел — занос',
  },
  teclas: {
    'Mayús': 'Shift',
    'Espacio': 'Пробел',
    'Espacio · Mayús': 'Пробел · Shift',
  },
}
