import type { ManualTraducido } from './manualI18n'

/**
 * Las frases de ejemplo del manual de comandos en ja, indexadas por su
 * texto español de origen (ver `manualI18n.ts`).
 *
 * GENERADO por `npm run traducir:contenido` — no lo edites a mano.
 */
export const MANUAL_JA: ManualTraducido = {
  frases: {
    '[Corrí] {5 km} en {30 min}': '{5 km}を{30分}で[走りました]',
    '[@]{cocina} [comí] {una ensalada}': '[@]{cocina} {サラダ}を[食べました]',
    '[Abre] el {estudio de audio}': '{オーディオスタジオ}を[開いて]',
    '[Abre] mis {canciones}': '{曲}を[開いて]',
    '[Abre] el {mezclador DJ}': '{DJミキサー}を[開いて]',
    '[Abre] la {galería de arte}': '{アートギャラリー}を[開いて]',
    '[Abre] mis {dibujos}': '{絵}を[開いて]',
    '[Abre] mis {libros}': '{本}を[開いて]',
    '[Abre] el {estudio de escritura}': '{執筆スタジオ}を[開いて]',
    '[Escribe un cuento] sobre {un faro en invierno} y [guárdalo en mis libros]': '{冬の灯台}についての[短編を書いて]、[本に保存して]',
    '[Guarda en mis libros] este texto: {Querido diario, hoy…}': 'この文章を[本に保存して]：{日記さん、今日は…}',
    '[Abre] el {editor de video}': '{動画エディタ}を[開いて]',
    '[Abre] mis {videos}': '{動画}を[開いて]',
    '[Abre] la {animación 3D}': '{3Dアニメーション}を[開いて]',
    '[Tomé] {2 vasos} de [agua]': '[水]を{2杯}[飲みました]',
    '[Me pesé]: {74 kg}': '[体重を測りました]：{74 kg}',
    '[Abre] el {recetario}': '{レシピ帳}を[開いて]',
    '[Abre] la {lista del súper}': '{買い物リスト}を[開いて]',
    '[Abre] el {diario de comidas}': '{食事日記}を[開いて]',
    '[Abre] las {metas de nutrición}': '{栄養の目標}を[開いて]',
    'Inventa una [receta] {ligera con atún}': '{ツナを使った軽めの}[レシピ]を考えて',
    'Arma una [dieta] {alta en proteína}': '{高たんぱくの}[食事プラン]を作って',
    'Agrega {plátano y avena} a la [lista del súper]': '[買い物リスト]に{バナナとオートミール}を追加して',
    '[Corrí] {5 km}': '{5 km}[走りました]',
    '[Abre] el {plan de ejercicio}': '{運動プラン}を[開いて]',
    '[Abre] las {metas de ejercicio}': '{運動の目標}を[開いて]',
    '[Muéstrame] cómo se hace el {press banca}': '{ベンチプレス}のやり方を[見せて]',
    'Registra mi sesión: {crossfit 40 min, intensidad alta}': '今日のセッションを記録して：{クロスフィット40分、強度high}',
    '[Arma una rutina] de {pecho y tríceps} de {45 min}': '{胸と三頭}の{45分}の[ルーティンを作って]',
    '[Dormí] {7 horas}, calidad {4/5}': '{7時間}[寝ました]、質は{4/5}',
    '[Abre] el {despertador}': '{目覚まし}を[開いて]',
    '[Abre] {mi sueño}': '{睡眠の記録}を[開いて]',
    '{Me acosté a las 23, desperté a las 7 y me levanté 2 veces}': '{23時に寝て、7時に起きて、途中で2回起きました}',
    '[Recuerdo]: {tarde de juegos con mi hermana}': '[思い出]：{妹とボードゲームをした午後}',
    '[Abre] el {calendario de ánimo}': '{気分カレンダー}を[開いて]',
    'Anota esta anécdota: {hoy celebramos el cumple de mamá}': 'この思い出を書き留めて：{今日は母の誕生日を祝いました}',
    '[Cobré] {8000} de {la quincena}': '{給料}で{8000}[受け取りました]',
    '[Abre] los {gastos fijos}': '{固定費}を[開いて]',
    '[Abre] las {metas de ahorro}': '{貯金の目標}を[開いて]',
    '{Pagué 250 de luz y 180 de agua}': '{電気代を250、水道代を180払いました}',
    '[Abre] el {formulario}': '{公式集}を[開いて]',
    '[Resolver ecuación]': '[方程式を解く]',
    '[Convertir unidades]': '[単位を変換]',
    '[Sistema de ecuaciones]': '[連立方程式]',
    '[Convertir a binario]': '[2進数に変換]',
    '[Propina]': '[チップ計算]',
    '[Regla de tres]': '[比例計算]',
    '[Estudié] {historia romana} {30 min}': '{ローマ史}を{30分}[勉強しました]',
    '[Abre] la {sesión de estudio}': '{学習セッション}を[開いて]',
    '[Abre] el {resumen de estudio}': '{学習のまとめ}を[開いて]',
    'Apunta que aprendí: {los ríos de Europa}': '学んだことを書き留めて：{ヨーロッパの川}',
    '[Abre] la {mesa de juegos}': '{ゲームテーブル}を[開いて]',
    'Apunta {la serie Dark} como pendiente': '{ドラマのDark}を見たいリストに入れて',
    '[Abre] el {mapamundi}': '{世界マップ}を[開いて]',
    '[Abre] {por conocer}': '{行ってみたい場所}を[開いて]',
    '[Abre] la {bitácora de viajes}': '{旅日記}を[開いて]',
    '[Medité] {10 min}': '{10分}[瞑想しました]',
    '[@]{jardin} [agradezco] {mi salud, mi familia y el café}': '[@]{jardin} {健康と家族とコーヒー}[に感謝します]',
    '[Abre] el {resumen del garage}': '{ガレージのまとめ}を[開いて]',
    '[Abre] {mis vehículos}': '{愛車一覧}を[開いて]',
    '[Abre] las {efemérides}': '{今日の出来事}を[開いて]',
    '[Abre] {mis hobbies}': '{趣味の部屋}を[開いて]',
    '[Abre] mis {mapas mentales}': '{マインドマップ}を[開いて]',
    '[Abre] los {mapas conceptuales}': '{概念マップ}を[開いて]',
    '[Dibuja un diagrama de flujo] de {cómo hacer pan}': '{パンの作り方}の[フローチャートを描いて]',
    '[Haz un esquema] de {lo que me acabas de explicar}': '{今の説明}を[図にして]',
    '[Agenda] una {junta con el cliente} el {martes a las 10}': '{火曜10時}に{クライアントとの打ち合わせ}を[予定に入れて]',
    '[Apunta el pendiente] {mandar la cotización}': '{見積もりを送る}を[やることに追加して]',
    '[Abre] mis {pendientes}': '{やること}を[開いて]',
    '[Abre] mis {citas médicas}': '{通院の予定}を[開いて]',
    '[Abre] el {progreso de idiomas}': '{語学の進み具合}を[開いて]',
    '[Construye] un {huerto}': '{菜園}を[作って]',
    '[Pon] una {pista de carreras}': '{レースコース}を[置いて]',
    '[Traza] las {vías del tren}': '{線路}を[敷いて]',
    '[Construye] una {montaña rusa}': '{ジェットコースター}を[作って]',
    '[Pon] la {meta} de la pista': 'コースの{ゴール}を[置いて]',
    '[Corre una carrera] de {3 vueltas}': '{3周}の[レースをして]',
    '[Quiero montar] la {montaña rusa}': '{ジェットコースター}に[乗りたいです]',
    '[Llévame] a la {meta}': '{ゴール}へ[連れていって]',
    '[Juguemos paintball] {2v2}': '{2v2}で[ペイントボールをやろう]',
    '[Pon] una {cancha de fútbol}': '{サッカーコート}を[置いて]',
    '[Crea] una {cancha de básquet}': '{バスケのコート}を[作って]',
    '[Pon] un {campo de béisbol}': '{野球場}を[置いて]',
    '[Abre] la {agenda de hoy}': '{今日の予定}を[開いて]',
    '[Abre] {mi semana}': '{今週}を[開いて]',
    '[Crea una rutina] de mañana: {agua, estiramiento y gratitud} a las {7:00}': '朝の[ルーティンを作って]：{7:00}に{水、ストレッチ、感謝}',
    '[Crea una rutina] de {lunes y miércoles}: {correr 20 min}': '{月曜と水曜}の[ルーティンを作って]：{20分ランニング}',
    '[Gira el último objeto]': '[最後のオブジェクトを回して]',
    '[Quita el último objeto]': '[最後のオブジェクトを消して]',
    '[Genera en 3D] {un dragón morado}': '{紫のドラゴン}を[3Dで作って]',
    '[Crea una imagen] de {un atardecer en la playa}': '{ビーチの夕暮れ}の[画像を作って]',
    '[Bájame]': '[降ろして]',
    '[Vista en] {primera persona}': '{一人称}[視点に]',
    '[Quita el tema]': '[テーマを外して]',
    '[Volumen] al {40%}': '[音量]を{40%}に',
    '[Apaga la música]': '[音楽を止めて]',
    '[Abre] mi {resumen semanal}': '{週のまとめ}を[開いて]',
    '[Abre] mi {resumen mensual}': '{月のまとめ}を[開いて]',
    '[Transparencia] al {40%}': '[透明度]を{40%}に',
    '[Apaga los efectos]': '[エフェクトを切って]',
    '[Avísame de mis metas] a las {21:00}': '{21:00}に[目標を知らせてください]',
    '[Apaga los avisos]': '[通知をオフにして]',
    '[Descarga un respaldo] de mis datos': 'データの[バックアップをダウンロードして]',
    '[Vuelve a ver la bienvenida]': '[ようこそ画面をもう一度見せて]',
    '[Abre las configuraciones]': '[設定を開いて]',
    '[Recuerda que] {soy vegetariano}': '{ベジタリアンです}と[覚えておいて]',
    '[Cómo funciona] la {rueda de herramientas}': '{ツールホイール}は[どう使いますか]',
    '[@]{cocina} {ensalada de la comida}': '[@]{cocina} {昼食のサラダ}',
  },
  atajos: {
    'Caminar (también con las flechas)': '歩く（矢印キーでも）',
    'Correr (se queda puesto hasta volver a pulsar)': '走る（もう一度押すまで続きます）',
    'Saltar': 'ジャンプ',
    'Agacharse (mantener pulsado)': 'しゃがむ（押しっぱなし）',
    'Lo que tengas delante: entrar al cuarto, subirte o bajarte del vehículo, cambiar de nivel': '目の前のもの：部屋に入る、乗り物に乗り降りする、階を変える',
    'Levantar la mano derecha / izquierda': '右手／左手を上げる',
    'Bailar': '踊る',
    'Mortal': 'バク宙',
    'Abrir la rueda de herramientas': 'ツールホイールを開く',
    'Abrir el chat y escribir': 'チャットを開いて入力する',
    'Cambiar de vista: isométrica, tercera y primera persona': '視点を切り替える：アイソメトリック、三人称、一人称',
    'Esconder o mostrar el HUD': 'HUDを隠す／表示する',
    'Cerrar lo que esté abierto': '開いているものを閉じる',
    'Conduciendo el OVNI: subir y bajar. En los demás vehículos, Espacio derrapa': 'UFOの操縦中：上昇と下降。ほかの乗り物では、スペースでドリフト',
  },
  teclas: {
    'Mayús': 'Shift',
    'Espacio': 'Space',
    'Espacio · Mayús': 'Space · Shift',
  },
}
