import type { ManualTraducido } from './manualI18n'

/**
 * Las frases de ejemplo del manual de comandos en zh, indexadas por su
 * texto español de origen (ver `manualI18n.ts`).
 *
 * GENERADO por `npm run traducir:contenido` — no lo edites a mano.
 */
export const MANUAL_ZH: ManualTraducido = {
  frases: {
    '[Tomé] {2 vasos} de [agua]': '[我喝了]{2杯}[水]',
    '[Me pesé]: {74 kg}': '[我称了体重]：{74公斤}',
    '[Abre] el {recetario}': '[打开]{食谱本}',
    '[Abre] la {lista del súper}': '[打开]{购物清单}',
    '[Abre] el {diario de comidas}': '[打开]{饮食日记}',
    '[Abre] las {metas de nutrición}': '[打开]{营养目标}',
    'Inventa una [receta] {ligera con atún}': '想一道{清淡的金枪鱼}[菜谱]',
    'Arma una [dieta] {alta en proteína}': '帮我配一份{高蛋白}的[食谱计划]',
    'Agrega {plátano y avena} a la [lista del súper]': '把{香蕉和燕麦}加到[购物清单]',
    '[Corrí] {5 km}': '[我跑了]{5公里}',
    '[Abre] el {plan de ejercicio}': '[打开]{运动计划}',
    '[Abre] las {metas de ejercicio}': '[打开]{运动目标}',
    '[Muéstrame] cómo se hace el {press banca}': '[教教我]{卧推}怎么做',
    'Registra mi sesión: {crossfit 40 min, intensidad alta}': '记一下我的训练：{crossfit 40分钟，强度高}',
    '[Arma una rutina] de {pecho y tríceps} de {45 min}': '[安排一套]{胸和三头}的日常安排，{45分钟}',
    '[Dormí] {7 horas}, calidad {4/5}': '[我睡了]{7小时}，质量{4/5}',
    '[Abre] el {despertador}': '[打开]{闹钟}',
    '[Abre] {mi sueño}': '[打开]{我的睡眠}',
    '{Me acosté a las 23, desperté a las 7 y me levanté 2 veces}': '{我23点上床，7点醒，中间起来了2次}',
    '[Recuerdo]: {tarde de juegos con mi hermana}': '[回忆]：{和妹妹玩了一下午桌游}',
    '[Abre] el {calendario de ánimo}': '[打开]{心情日历}',
    'Anota esta anécdota: {hoy celebramos el cumple de mamá}': '记下这段回忆：{今天给妈妈过生日}',
    '[Cobré] {8000} de {la quincena}': '[我收到]{这半个月}的{8000}',
    '[Abre] los {gastos fijos}': '[打开]{固定支出}',
    '[Abre] las {metas de ahorro}': '[打开]{储蓄目标}',
    '{Pagué 250 de luz y 180 de agua}': '{我交了250电费和180水费}',
    '[Abre] el {formulario}': '[打开]{公式手册}',
    '[Resolver ecuación]': '[解方程]',
    '[Convertir unidades]': '[单位换算]',
    '[Sistema de ecuaciones]': '[方程组]',
    '[Convertir a binario]': '[转成二进制]',
    '[Propina]': '[小费]',
    '[Regla de tres]': '[三数法]',
    '[Estudié] {historia romana} {30 min}': '[我学了]{罗马史}{30分钟}',
    '[Abre] la {sesión de estudio}': '[打开]{学习时段}',
    '[Abre] el {resumen de estudio}': '[打开]{学习小结}',
    'Apunta que aprendí: {los ríos de Europa}': '记一下我学到的：{欧洲的河流}',
    '[Abre] la {mesa de juegos}': '[打开]{游戏桌}',
    'Apunta {la serie Dark} como pendiente': '把{剧集《暗黑》}记成待看',
    '[Abre] el {mapamundi}': '[打开]{世界地图}',
    '[Abre] {por conocer}': '[打开]{想去的地方}',
    '[Abre] la {bitácora de viajes}': '[打开]{旅行日志}',
    '[Medité] {10 min}': '[我冥想了]{10分钟}',
    '[@]{jardin} [agradezco] {mi salud, mi familia y el café}': '[@]{jardin} [我感谢]{我的健康、我的家人和咖啡}',
    '[Abre] el {resumen del garage}': '[打开]{车库概览}',
    '[Abre] {mis vehículos}': '[打开]{我的车辆}',
    '[Abre] las {efemérides}': '[打开]{历史上的今天}',
    '[Abre] {mis hobbies}': '[打开]{我的爱好}',
    '[Abre] mis {mapas mentales}': '[打开]我的{思维导图}',
    '[Abre] los {mapas conceptuales}': '[打开]{概念图}',
    '[Dibuja un diagrama de flujo] de {cómo hacer pan}': '[画一张流程图]，讲{怎么做面包}',
    '[Haz un esquema] de {lo que me acabas de explicar}': '[做一张图]，讲{你刚才给我讲的内容}',
    '[Agenda] una {junta con el cliente} el {martes a las 10}': '[安排]一个{和客户的会}，{周二十点}',
    '[Apunta el pendiente] {mandar la cotización}': '[记一条待办]：{把报价发出去}',
    '[Abre] mis {pendientes}': '[打开]我的{待办}',
    '[Abre] mis {citas médicas}': '[打开]我的{就医预约}',
    '[Abre] el {progreso de idiomas}': '[打开]{语言进度}',
    '[Construye] un {huerto}': '[建]一个{菜园}',
    '[Pon] una {pista de carreras}': '[放]一条{赛道}',
    '[Traza] las {vías del tren}': '[铺]{火车轨道}',
    '[Construye] una {montaña rusa}': '[建]一座{过山车}',
    '[Pon] la {meta} de la pista': '[放]赛道的{终点线}',
    '[Corre una carrera] de {3 vueltas}': '[跑一场]{3圈}的[比赛]',
    '[Quiero montar] la {montaña rusa}': '[我想坐]{过山车}',
    '[Llévame] a la {meta}': '[带我去]{终点线}',
    '[Juguemos paintball] {2v2}': '[我们来玩彩弹]{2v2}',
    '[Reta] a {Luna} a un paintball {1v1}': '[约]{Luna}打一场{1v1}彩弹',
    '[Pon] una {cancha de fútbol}': '[放]一个{足球场}',
    '[Crea] una {cancha de básquet}': '[建一个]{篮球场}',
    '[Pon] un {campo de béisbol}': '[放一个]{棒球场}',
    '[Abre] la {agenda de hoy}': '[打开]{今天的日程}',
    '[Abre] {mi semana}': '[打开]{我的一周}',
    '[Crea una rutina] de mañana: {agua, estiramiento y gratitud} a las {7:00}': '[创建一个早晨的日常安排]：{7:00}做{喝水、拉伸和感恩}',
    '[Crea una rutina] de {lunes y miércoles}: {correr 20 min}': '[创建一个日常安排]：{周一和周三}{跑步20分钟}',
    '[Gira el último objeto]': '[旋转最后一个物件]',
    '[Quita el último objeto]': '[删掉最后一个物件]',
    '[Genera en 3D] {un dragón morado}': '[用3D生成]{一条紫色的龙}',
    '[Crea una imagen] de {un atardecer en la playa}': '[生成一张图]：{海边的日落}',
    '[Bájame]': '[让我下来]',
    '[Vista en] {primera persona}': '{第一人称}[视角]',
    '[Quita el tema]': '[去掉主题]',
    '[Volumen] al {40%}': '[音量]调到{40%}',
    '[Apaga la música]': '[关掉音乐]',
    '[Abre] mi {resumen semanal}': '[打开]我的{每周小结}',
    '[Abre] mi {resumen mensual}': '[打开]我的{每月小结}',
    '[Transparencia] al {40%}': '[透明度]调到{40%}',
    '[Apaga los efectos]': '[关掉特效]',
    '[Avísame de mis metas] a las {21:00}': '{21:00}[提醒我我的目标]',
    '[Apaga los avisos]': '[关掉通知]',
    '[Descarga un respaldo] de mis datos': '我的数据，[下载一份备份]',
    '[Vuelve a ver la bienvenida]': '[再看一次欢迎菜单]',
    '[Abre las configuraciones]': '[打开设置]',
    '[Recuerda que] {soy vegetariano}': '[记住]{我吃素}',
    '[@]{cocina} {ensalada de la comida}': '[@]{cocina} {午餐吃沙拉}',
    '[Cómo funciona] la {rueda de herramientas}': '{工具轮盘}[怎么用]',
  },
  atajos: {
    'Caminar (también con las flechas)': '走路（方向键也可以）',
    'Correr (se queda puesto hasta volver a pulsar)': '跑步（一直保持，再按一次取消）',
    'Saltar': '跳跃',
    'Agacharse (mantener pulsado)': '蹲下（按住）',
    'Lo que tengas delante: entrar al cuarto, subirte o bajarte del vehículo, cambiar de nivel': '跟眼前的东西互动：进房间、上下载具、换楼层',
    'Levantar la mano derecha / izquierda': '举右手／左手',
    'Bailar': '跳舞',
    'Mortal': '后空翻',
    'Abrir la rueda de herramientas': '打开工具轮盘',
    'Abrir el chat y escribir': '打开聊天并输入',
    'Cambiar de vista: isométrica, tercera y primera persona': '切换视角：等距、第三人称和第一人称',
    'Esconder o mostrar el HUD': '隐藏或显示 HUD',
    'Cerrar lo que esté abierto': '关掉当前打开的东西',
    'Conduciendo el OVNI: subir y bajar. En los demás vehículos, Espacio derrapa': '开飞碟时：上升和下降。其他载具里，空格键是漂移',
  },
  teclas: {
    'Mayús': 'Shift',
    'Espacio': '空格',
    'Espacio · Mayús': '空格 · Shift',
  },
}
