import type { ManualTraducido } from './manualI18n'

/**
 * Las frases de ejemplo del manual de comandos en pt, indexadas por su
 * texto español de origen (ver `manualI18n.ts`).
 *
 * GENERADO por `npm run traducir:contenido` — no lo edites a mano.
 */
export const MANUAL_PT: ManualTraducido = {
  frases: {
    '[Corrí] {5 km} en {30 min}': '[Corri] {5 km} em {30 min}',
    '[@]{cocina} [comí] {una ensalada}': '[@]{cocina} [comi] {uma salada}',
    '[Abre] el {estudio de audio}': '[Abra] o {estúdio de áudio}',
    '[Abre] mis {canciones}': '[Abra] minhas {músicas}',
    '[Abre] el {mezclador DJ}': '[Abra] o {mixer DJ}',
    '[Abre] la {galería de arte}': '[Abra] a {galeria de arte}',
    '[Abre] mis {dibujos}': '[Abra] meus {desenhos}',
    '[Abre] mis {libros}': '[Abra] meus {livros}',
    '[Abre] el {estudio de escritura}': '[Abra] o {estúdio de escrita}',
    '[Escribe un cuento] sobre {un faro en invierno} y [guárdalo en mis libros]': '[Escreva um conto] sobre {um farol no inverno} e [salve nos meus livros]',
    '[Guarda en mis libros] este texto: {Querido diario, hoy…}': '[Salve nos meus livros] este texto: {Querido diário, hoje…}',
    '[Abre] el {editor de video}': '[Abra] o {editor de vídeo}',
    '[Abre] mis {videos}': '[Abra] meus {vídeos}',
    '[Abre] la {animación 3D}': '[Abra] a {animação 3D}',
    "[Abre] {mis archivos}": "[Abra] {meus arquivos}",
    "[Abre] los {archivos recientes}": "[Abra] os {arquivos recentes}",
    "[Abre] los {archivos del studio}": "[Abra] os {arquivos do studio}",
    "[Abre] la {papelera}": "[Abra] a {lixeira}",
    "[Abre] los {archivos destacados}": "[Abra] os {arquivos com estrela}",
    '[Tomé] {2 vasos} de [agua]': '[Bebi] {2 copos} de [água]',
    '[Me pesé]: {74 kg}': '[Me pesei]: {74 kg}',
    '[Abre] el {recetario}': '[Abra] o {livro de receitas}',
    '[Abre] la {lista del súper}': '[Abra] a {lista de compras}',
    '[Abre] el {diario de comidas}': '[Abra] o {diário de refeições}',
    '[Abre] las {metas de nutrición}': '[Abra] as {metas de nutrição}',
    'Inventa una [receta] {ligera con atún}': 'Invente uma [receita] {leve com atum}',
    'Arma una [dieta] {alta en proteína}': 'Monte uma [dieta] {rica em proteína}',
    'Agrega {plátano y avena} a la [lista del súper]': 'Adicione {banana e aveia} à [lista de compras]',
    '[Corrí] {5 km}': '[Corri] {5 km}',
    '[Abre] el {plan de ejercicio}': '[Abra] o {plano de exercícios}',
    '[Abre] {cardio}': '[Abra] {cardio}',
    '[Abre] las {metas de ejercicio}': '[Abra] as {metas de exercício}',
    'Registra mi sesión: {crossfit 40 min, intensidad alta}': 'Registre minha sessão: {crossfit 40 min, intensidade alta}',
    '[Arma una rutina] de {pecho y tríceps} de {45 min}': '[Monte uma rotina] de {peito e tríceps} de {45 min}',
    '[Dormí] {7 horas}, calidad {4/5}': '[Dormi] {7 horas}, qualidade {4/5}',
    '[Abre] {mi sueño}': '[Abra] {meu sono}',
    '{Me acosté a las 23, desperté a las 7 y me levanté 2 veces}': '{Deitei às 23, acordei às 7 e levantei 2 vezes}',
    '[Recuerdo]: {tarde de juegos con mi hermana}': '[Memória]: {tarde de jogos com minha irmã}',
    '[Abre] el {calendario de ánimo}': '[Abra] o {calendário de humor}',
    'Anota esta anécdota: {hoy celebramos el cumple de mamá}': 'Anote esta memória: {hoje comemoramos o aniversário da minha mãe}',
    '[Abre] los {gastos fijos}': '[Abra] os {gastos fixos}',
    '[Abre] las {metas de ahorro}': '[Abra] as {metas de poupança}',
    '[Abre] las {materias primas}': '[Abra] as {commodities}',
    '{Pagué 250 de luz y 180 de agua}': '{Paguei 250 de luz e 180 de água}',
    '[Abre] el {formulario}': '[Abra] o {formulário}',
    '[Resolver ecuación]': '[Resolver equação]',
    '[Convertir unidades]': '[Converter unidades]',
    '[Sistema de ecuaciones]': '[Sistema de equações]',
    '[Convertir a binario]': '[Converter para binário]',
    '[Propina]': '[Gorjeta]',
    '[Regla de tres]': '[Regra de três]',
    '[Estudié] {historia romana} {30 min}': '[Estudei] {história romana} {30 min}',
    '[Abre] la {sesión de estudio}': '[Abra] a {sessão de estudo}',
    '[Abre] el {resumen de estudio}': '[Abra] o {resumo de estudo}',
    'Apunta que aprendí: {los ríos de Europa}': 'Anote o que aprendi: {os rios da Europa}',
    '[Abre] la {mesa de juegos}': '[Abra] a {mesa de jogos}',
    '[Quiero jugar] la {viborita}': '[Quero jogar] {snake}',
    '[Juega] {tetris}': '[Jogue] {tetris}',
    'Apunta {la serie Dark} como pendiente': 'Anote {a série Dark} como pendente',
    '[Abre] el {mapamundi}': '[Abra] o {mapa-múndi}',
    '[Abre] {por conocer}': '[Abra] {a conhecer}',
    '[Abre] la {bitácora de viajes}': '[Abra] o {diário de bordo de viagens}',
    '[Visité] {Oaxaca}': '[Visitei] {Oaxaca}',
    '[Medité] {10 min}': '[Meditei] {10 min}',
    '[Abre] el {resumen del garage}': '[Abra] o {resumo da garagem}',
    '[Abre] {mis vehículos}': '[Abra] {meus veículos}',
    '[Abre] las {efemérides}': '[Abra] as {efemérides}',
    '[Abre] {mis hobbies}': '[Abra] {meus hobbies}',
    '[Abre] mis {mapas mentales}': '[Abra] meus {mapas mentais}',
    '[Abre] los {mapas conceptuales}': '[Abra] os {mapas conceituais}',
    '[Dibuja un diagrama de flujo] de {cómo hacer pan}': '[Desenhe um fluxograma] de {como fazer pão}',
    '[Haz un esquema] de {lo que me acabas de explicar}': '[Faça um esquema] do {que você acabou de me explicar}',
    '[Agenda] una {junta con el cliente} el {martes a las 10}': '[Agende] uma {reunião com o cliente} na {terça às 10}',
    '[Apunta el pendiente] {mandar la cotización}': '[Anote a pendência] {enviar o orçamento}',
    '[Abre] mis {pendientes}': '[Abra] minhas {pendências}',
    '[Abre] mis {citas médicas}': '[Abra] minhas {consultas médicas}',
    '[Abre] el {tutor}': '[Abra] o {tutor}',
    '[Abre] el {progreso de idiomas}': '[Abra] o {progresso de idiomas}',
    '[Pon] una {pista de carreras}': '[Coloque] uma {pista de corrida}',
    '[Traza] las {vías del tren}': '[Trace] os {trilhos do trem}',
    '[Construye] una {montaña rusa}': '[Construa] uma {montanha-russa}',
    '[Pon] la {meta} de la pista': '[Coloque] a {linha de chegada} da pista',
    '[Corre una carrera] de {3 vueltas}': '[Faça uma corrida] de {3 voltas}',
    '[Quiero montar] la {montaña rusa}': '[Quero andar] na {montanha-russa}',
    '[Llévame] a la {meta}': '[Me leve] à {linha de chegada}',
    '[Juguemos] {paintball}': '[Vamos jogar] {paintball}',
    '[Juguemos paintball] {2v2}': '[Vamos jogar paintball] {2v2}',
    '[Reta] a {Luna} a un paintball {1v1}': '[Desafie] a {Luna} para um paintball {1v1}',
    '[Sal] del {paintball}': '[Saia] do {paintball}',
    '[Pon] una {cancha de fútbol}': '[Coloque] um {campo de futebol}',
    '[@]{jardin} [agradezco] {mi salud, mi familia y el café}': '[@]{jardin} [agradeço] {minha saúde, minha família e o café}',
    '[Crea] una {cancha de básquet}': '[Crie] uma {quadra de basquete}',
    '[Pon] un {campo de béisbol}': '[Coloque] um {campo de beisebol}',
    '[Abre] la {agenda de hoy}': '[Abra] a {agenda de hoje}',
    '[Abre] {mi semana}': '[Abra] {minha semana}',
    '[Crea una rutina] de mañana: {agua, estiramiento y gratitud} a las {7:00}': '[Crie uma rotina] de manhã: {água, alongamento e gratidão} às {7:00}',
    '[Crea una rutina] de {lunes y miércoles}: {correr 20 min}': '[Crie uma rotina] de {segunda e quarta}: {correr 20 min}',
    '[Gira el último objeto]': '[Gire o último objeto]',
    '[Quita el último objeto]': '[Tire o último objeto]',
    '[Genera en 3D] {un dragón morado}': '[Gere em 3D] {um dragão roxo}',
    '[Crea una imagen] de {un atardecer en la playa}': '[Crie uma imagem] de {um pôr do sol na praia}',
    '[Móntame] en la {bici}': '[Me coloque] na {bike}',
    '[Bájame]': '[Me tire daí]',
    '[Vista en] {primera persona}': '[Visão em] {primeira pessoa}',
    '[Quita el tema]': '[Tire o tema]',
    '[Música] {chiptune}': '[Música] {chiptune}',
    '[Volumen] al {40%}': '[Volume] em {40%}',
    '[Apaga la música]': '[Desligue a música]',
    '[Abre] mi {resumen semanal}': '[Abra] meu {resumo semanal}',
    '[Abre] mi {resumen mensual}': '[Abra] meu {resumo mensal}',
    '[Tema de interfaz] {neón}': '[Tema da interface] {neon}',
    '[Estilo de la interfaz] {pixel}': '[Estilo da interface] {pixel}',
    '[Transparencia] al {40%}': '[Transparência] em {40%}',
    '[Apaga los efectos]': '[Desligue os efeitos]',
    '[Avísame de mis metas] a las {21:00}': '[Me lembre das minhas metas] às {21:00}',
    '[Apaga los avisos]': '[Desligue os avisos]',
    '[Descarga un respaldo] de mis datos': '[Baixe um backup] dos meus dados',
    '[Vuelve a ver la bienvenida]': '[Mostre as boas-vindas de novo]',
    '[Abre las configuraciones]': '[Abra as configurações]',
    '[Recuerda que] {soy vegetariano}': '[Lembre que] {sou vegetariano}',
    '[Cómo funciona] el {editor}': '[Como funciona] o {editor}',
    '[Cómo funciona] la {rueda de herramientas}': '[Como funciona] a {roda de ferramentas}',
    '[Cómo funciona] el {chat}': '[Como funciona] o {chat}',
    '[@]{cocina} {ensalada de la comida}': '[@]{cocina} {salada do almoço}',
    '[Tipografía] {serif}': '[Tipografia] {serif}',
    '[Abre] {ejemplo.com}': '[Abra] {exemplo.com}',
    '[Busca en internet] {recetas de pan}': '[Busque na internet] {receitas de pão}',
    '[Historial]': '[Histórico]',
    '[Sitios]': '[Sites]',
    '[Tiempo en internet]': '[Tempo na internet]',
    '[Cómo llegar]': '[Como chegar]',
    '[Amigos]': '[Amigos]',
    '[Jugar] {paintball} [con] {@ana}': '[Jogar] {paintball} [com] {@ana}',
    '[Comí] {pollo con arroz} en la {cena}': '[Comi] {frango com arroz} no {jantar}',
    '[Abre] la {dieta}': '[Abra] a {dieta}',
    '[Entrené] {pierna} {45 min}': '[Treinei] {perna} {45 min}',
    '[Abre] {fuerza}': '[Abra] {força}',
    '[Abre] {flexibilidad}': '[Abra] {flexibilidade}',
    '[Muéstrame] cómo se hace el {press banca}': '[Me mostre] como se faz o {supino reto}',
    '[Haz] una {sentadilla}': '[Faça] um {agachamento}',
    '[Arma una rutina] de {estiramientos} para {la espalda baja}': '[Monte uma rotina] de {alongamentos} para {a lombar}',
    '[Abre] el {despertador}': '[Abra] o {despertador}',
    '[Abre] mis {anécdotas}': '[Abra] meu {diário}',
    '[Gasté] {500} en {el súper}': '[Gastei] {500} no {mercado}',
    '[Cobré] {8000} de {la quincena}': '[Recebi] {8000} de {salário}',
    '[Abre] el {balance}': '[Abra] o {fluxo de caixa}',
    '[Abre] los {movimientos}': '[Abra] os {movimentos}',
    '[Abre] las {divisas}': '[Abra] o {forex}',
    '[Abre] las {criptomonedas}': '[Abra] as {criptomoedas}',
    '[Abre] la {calculadora}': '[Abra] a {calculadora}',
    '[Abre] el {graficador}': '[Abra] o {gráfico}',
    '[Abre] las {hojas de cálculo}': '[Abra] as {planilhas}',
    '[Abre] las {matrices}': '[Abra] as {matrizes}',
    '[Abre] las {charlas}': '[Abra] as {conversas}',
    '[Abre] la {enciclopedia}': '[Abra] a {enciclopédia}',
    '[Vi la película] {Dune}': '[Assisti ao filme] {Duna}',
    '[Jugué] {ajedrez} con mi hermano': '[Joguei] {xadrez} com meu irmão',
    '[Abre] el {archivo}': '[Abra] o {arquivo}',
    '[Juega] una partida de {ajedrez}': '[Jogue] uma partida de {xadrez}',
    '[Abre] las {rutas}': '[Abra] as {rotas}',
    'Quiero conocer {Japón}': 'Quero conhecer {o Japão}',
    '[Visité] {Roma}: {la fontana de noche es mágica}': '[Visitei] {Roma}: {a Fontana de Trevi à noite é mágica}',
    '[Abre] la {meditación}': '[Abra] a {meditação}',
    '[Abre] la {respiración}': '[Abra] a {respiração}',
    '[Abre] los {agradecimientos}': '[Abra] a {gratidão}',
    '[Abre] los {titulares}': '[Abra] as {manchetes}',
    'Avancé en mi [proyecto] de {acuarela} {40 min}': 'Avancei no meu [projeto] de {aquarela} {40 min}',
    'Practiqué {guitarra} {25 min}': 'Pratiquei {violão} {25 min}',
    '[Hazme un mapa mental] de {la fotosíntesis}': '[Me faça um mapa mental] sobre {a fotossíntese}',
    '[Compara] {café} y {té} en un mapa': '[Compare] {café} e {chá} em um mapa',
    '[Tengo cita] con el {dentista} el {14 a las 5}': '[Tenho consulta] com o {dentista} no {dia 14 às 17h}',
    '[Recuérdame] tomar {ibuprofeno} a las {8 y a las 20}': '[Me lembre] de tomar {ibuprofeno} às {8h e às 20h}',
    '[Guarda el contacto] de {Ana}: {5512345678}, cumple el {3 de mayo}': '[Salve o contato] de {Ana}: {11912345678}, aniversário em {3 de maio}',
    '[Abre] mis {contactos}': '[Abra] meus {contatos}',
    '[Vocab] {inglés}: {dog} = {perro}': '[Vocab] {inglês}: {dog} = {cachorro}',
    '[Abre] el {repaso}': '[Abra] a {revisão}',
    '[Abre] el {temario}': '[Abra] o {programa}',
    '[Repasé] {francés} {15 min}': '[Revisei] {francês} {15 min}',
    'Aprendí en {alemán}: {Hund} = {perro}': 'Aprendi em {alemão}: {Hund} = {cachorro}',
    '[Construye] un {huerto}': '[Construa] uma {horta}',
    '[Quiero sembrar] {zanahorias}': '[Quero plantar] {cenouras}',
    '[Siembra] {maíz} en el huerto': '[Plante] {milho} na horta',
    '[Pon] un {aspersor} en el huerto': '[Coloque] um {aspersor} na horta',
    '[Riega] el {huerto}': '[Regue] a {horta}',
    '[Cosecha] el {huerto}': '[Colha] a {horta}',
    '[Llévame] al {huerto}': '[Me leve] até a {horta}',
    '[Haz] un {corral}': '[Faça] um {cercado}',
    '[Pon] {vacas} en la granja': '[Coloque] {vacas} na fazenda',
    '[Alimenta] a los {animales}': '[Alimente] os {animais}',
    '[Mima] a los {animales}': '[Faça carinho] nos {animais}',
    '[Cura] a los {animales}': '[Cure] os {animais}',
    '[Limpia] los {corrales}': '[Limpe] os {cercados}',
    '[Llévame] a la {granja}': '[Me leve] até a {fazenda}',
    '[Borra] la {pista}': '[Apague] a {pista}',
    '[Hagamos una carrera] {contra} un asistente': '[Vamos fazer uma corrida] {contra} um assistente',
    '[Corre una carrera] {fácil} de {5 vueltas}': '[Faça uma corrida] {fácil} de {5 voltas}',
    '[Quiero montar] el {tren}': '[Quero andar] de {trem}',
    '[Paintball] campal en {difícil}': '[Paintball] todos contra todos no modo {difícil}',
    '[Pon] una {cancha de tenis} {azul}': '[Coloque] uma {quadra de tênis} {azul}',
    '[Llévame] a la {cancha}': '[Me leve] até a {quadra}',
    '[Abre] el {cronograma}': '[Abra] o {cronograma}',
    '[Enséñame] las {rutinas}': '[Me mostre] as {rotinas}',
    '[Crea un cuarto] llamado {Estudio}': '[Crie um cômodo] chamado {Estúdio}',
    '[Renombra] la {cocina} a {Oficina}': '[Renomeie] a {cozinha} para {Escritório}',
    '[Cambia el ícono] de la {cocina} a {🍳}': '[Mude o ícone] da {cozinha} para {🍳}',
    '[Pon] la {cocina} en categoría {cuerpo}': '[Coloque] a {cozinha} na categoria {corpo}',
    '[Agrega] la {biblioteca} al mapa': '[Adicione] a {biblioteca} ao mapa',
    '[Elimina] la {cocina}': '[Exclua] a {cozinha}',
    '[Abre] la {cocina}': '[Abra] a {cozinha}',
    '[Pinta] la {cocina} de {azul}': '[Pinte] a {cozinha} de {azul}',
    '[Piso] de la {cocina} de {madera}': '[Piso] da {cozinha} de {madeira}',
    '[Piso] de la {cocina} {rojo}': '[Piso] da {cozinha} {vermelho}',
    '[Techo] de la {cocina} de {tejas rojas}': '[Telhado] da {cozinha} de {telhas vermelhas}',
    '[Techo a dos aguas] en la {cocina}': '[Telhado de duas águas] na {cozinha}',
    '[Haz] la {cocina} {redonda}': '[Deixe] a {cozinha} {redonda}',
    '[Agranda] la {cocina}': '[Aumente] a {cozinha}',
    '[Encoge] la {cocina}': '[Reduza] a {cozinha}',
    '[Mueve] la {cocina} a la {derecha}': '[Mova] a {cozinha} para a {direita}',
    '[Abre el muro] {norte} de la {cocina}': '[Abra a parede] {norte} da {cozinha}',
    '[Pon una puerta] {corredera} en el muro {sur} de la {cocina}': '[Coloque uma porta] {de correr} na parede {sul} da {cozinha}',
    '[Pon] {ladrillo} en el muro {este} de la {cocina}': '[Coloque] {tijolo} na parede {leste} da {cozinha}',
    '[Haz más grueso] el muro {norte} de la {cocina}': '[Deixe mais grossa] a parede {norte} da {cozinha}',
    '[Apila] la {sala} sobre la {cocina}': '[Empilhe] a {sala} sobre a {cozinha}',
    '[Agranda el mapa] hacia el {este}': '[Aumente o mapa] para o {leste}',
    '[Crea] una {lámpara}': '[Crie] uma {lâmpada}',
    '[Pinta el último objeto] de {rojo}': '[Pinte o último objeto] de {vermelho}',
    '[Haz el último objeto] más {grande}': '[Deixe o último objeto] {maior}',
    '[Agrupa los objetos] de la {cocina}': '[Agrupe os objetos] da {cozinha}',
    '[Genera en 3D] {una fuente de piedra} estilo {minimalista}': '[Gere em 3D] {uma fonte de pedra} em estilo {minimalista}',
    '[Ponme] {sombrero} {rojo}': '[Me coloque] um {chapéu} {vermelho}',
    '[Quítame] los {lentes}': '[Tire] meus {óculos}',
    '[Pinta el torso] del [avatar] de {verde}': '[Pinte o torso] do [avatar] de {verde}',
    '[Haz el avatar] más {grande}': '[Deixe o avatar] {maior}',
    '[Quiero conducir] el {auto}': '[Quero dirigir] o {carro}',
    '[Vista] {isométrica}': '[Visão] {isométrica}',
    '[Cambia el tema] a {navidad}': '[Mude o tema] para {Natal}',
    '[Fondo] {nieve}': '[Fundo] {neve}',
    '[Pon música] {relajante}': '[Toque música] {relaxante}',
    '[Modo] {oscuro}': '[Modo] {escuro}',
    '[Apariencia] {transparente}': '[Aparência] {transparente}',
    '[Cambia el idioma] a {inglés}': '[Mude o idioma] para {inglês}',
    '[Pon iconos] {profesionales}': '[Use ícones] {profissionais}',
    '[Estilo] {cómic}': '[Estilo] {quadrinhos}',
    '[Avísame] de mis {rutinas}': '[Me avise] das minhas {rotinas}',
    '[Abre] mi {cuenta}': '[Abra] minha {conta}',
    '[Cómo funciona] la {cocina}': '[Como funciona] a {cozinha}',
    '[Qué hace] el {inventario}': '[O que faz] o {inventário}',
    '[Para qué sirve] la {cámara}': '[Para que serve] a {câmera}',
    '[Tutorial de] {ejercicio}': '[Tutorial da] {academia}',
    '[Tutorial de] la {biblioteca}': '[Tutorial da] {biblioteca}',
    '[Tutorial] {general}': '[Tutorial] {geral}',
  },
  atajos: {
    'Caminar (también con las flechas)': 'Andar (também com as setas)',
    'Correr (se queda puesto hasta volver a pulsar)': 'Correr (fica ativo até apertar de novo)',
    'Saltar': 'Pular',
    'Agacharse (mantener pulsado)': 'Agachar (segurar)',
    'Lo que tengas delante: entrar al cuarto, subirte o bajarte del vehículo, cambiar de nivel': 'O que estiver na sua frente: entrar no cômodo, subir ou descer do veículo, mudar de nível',
    'Levantar la mano derecha / izquierda': 'Levantar a mão direita / esquerda',
    'Bailar': 'Dançar',
    'Mortal': 'Salto mortal',
    'Abrir la rueda de herramientas': 'Abrir a roda de ferramentas',
    'Abrir el chat y escribir': 'Abrir o chat e escrever',
    'Cambiar de vista: isométrica, tercera y primera persona': 'Mudar de vista: isométrica, terceira e primeira pessoa',
    'Esconder o mostrar el HUD': 'Esconder ou mostrar o HUD',
    'Cerrar lo que esté abierto': 'Fechar o que estiver aberto',
    'Conduciendo el OVNI: subir y bajar. En los demás vehículos, Espacio derrapa': 'Pilotando o OVNI: subir e descer. Nos outros veículos, Espaço derrapa',
  },
  teclas: {
    'Mayús': 'Shift',
    'Espacio': 'Espaço',
    'Espacio · Mayús': 'Espaço · Shift',
  },
}
