import type { ManualTraducido } from './manualI18n'

/**
 * Las frases de ejemplo del manual de comandos en ar, indexadas por su
 * texto español de origen (ver `manualI18n.ts`).
 *
 * GENERADO por `npm run traducir:contenido` — no lo edites a mano.
 */
export const MANUAL_AR: ManualTraducido = {
  frases: {
    '[Corrí] {5 km} en {30 min}': '[ركضت] {5 كم} في {30 دقيقة}',
    '[@]{cocina} [comí] {una ensalada}': '[@]{cocina} [أكلت] {سلطة}',
    '[Abre] el {estudio de audio}': '[افتح] {استوديو الصوت}',
    '[Abre] mis {canciones}': '[افتح] {أغانيّ}',
    '[Abre] el {mezclador DJ}': '[افتح] {خلّاط الدي جي}',
    '[Abre] la {galería de arte}': '[افتح] {معرض الفن}',
    '[Abre] mis {dibujos}': '[افتح] {رسوماتي}',
    '[Abre] mis {libros}': '[افتح] {كتبي}',
    '[Abre] el {estudio de escritura}': '[افتح] {استوديو الكتابة}',
    '[Escribe un cuento] sobre {un faro en invierno} y [guárdalo en mis libros]': '[اكتب قصة قصيرة] عن {منارة في الشتاء} و[احفظها في كتبي]',
    '[Guarda en mis libros] este texto: {Querido diario, hoy…}': '[احفظ في كتبي] هذا النص: {عزيزتي المذكرات، اليوم…}',
    '[Abre] el {editor de video}': '[افتح] {محرّر الفيديو}',
    '[Abre] mis {videos}': '[افتح] {فيديوهاتي}',
    '[Abre] la {animación 3D}': '[افتح] {الرسوم المتحركة ثلاثية الأبعاد}',
    "[Abre] {mis archivos}": "[افتح] {ملفاتي}",
    "[Abre] los {archivos recientes}": "[افتح] {الملفات الأخيرة}",
    "[Abre] los {archivos del studio}": "[افتح] {ملفات الاستوديو}",
    "[Abre] la {papelera}": "[افتح] {سلة المهملات}",
    "[Abre] los {archivos destacados}": "[افتح] {الملفات المميّزة بنجمة}",
    '[Tomé] {2 vasos} de [agua]': '[شربت] {كوبين} من [الماء]',
    '[Me pesé]: {74 kg}': '[وزنت نفسي]: {74 كغ}',
    '[Abre] el {recetario}': '[افتح] {كتاب الوصفات}',
    '[Abre] la {lista del súper}': '[افتح] {قائمة التسوق}',
    '[Abre] el {diario de comidas}': '[افتح] {يوميات الطعام}',
    '[Abre] las {metas de nutrición}': '[افتح] {أهداف التغذية}',
    'Inventa una [receta] {ligera con atún}': 'ابتكر [وصفة] {خفيفة بالتونة}',
    'Arma una [dieta] {alta en proteína}': 'جهّز [نظامًا غذائيًا] {عالي البروتين}',
    'Agrega {plátano y avena} a la [lista del súper]': 'أضف {موز وشوفان} إلى [قائمة التسوق]',
    '[Corrí] {5 km}': '[ركضت] {5 كم}',
    '[Abre] el {plan de ejercicio}': '[افتح] {خطة التمرين}',
    '[Abre] las {metas de ejercicio}': '[افتح] {أهداف التمرين}',
    '[Muéstrame] cómo se hace el {press banca}': '[أرني] كيف يُؤدى {ضغط البنش}',
    'Registra mi sesión: {crossfit 40 min, intensidad alta}': 'سجّل جلستي: {كروسفيت 40 دقيقة، شدة عالية}',
    '[Arma una rutina] de {pecho y tríceps} de {45 min}': '[جهّز روتينًا] لـ{الصدر والترايسبس} مدته {45 دقيقة}',
    '[Dormí] {7 horas}, calidad {4/5}': '[نمت] {7 ساعات}، الجودة {4/5}',
    '[Abre] el {despertador}': '[افتح] {المنبّه}',
    '[Abre] {mi sueño}': '[افتح] {نومي}',
    '{Me acosté a las 23, desperté a las 7 y me levanté 2 veces}': '{نمت الساعة 23 واستيقظت الساعة 7 ونهضت مرتين}',
    '[Recuerdo]: {tarde de juegos con mi hermana}': '[ذكرى]: {أمسية ألعاب مع أختي}',
    '[Abre] el {calendario de ánimo}': '[افتح] {تقويم المزاج}',
    'Anota esta anécdota: {hoy celebramos el cumple de mamá}': 'دوّن هذه الذكرى: {احتفلنا اليوم بعيد ميلاد أمي}',
    '[Cobré] {8000} de {la quincena}': '[قبضت] {8000} من {راتب نصف الشهر}',
    '[Abre] los {gastos fijos}': '[افتح] {المصاريف الثابتة}',
    '[Abre] las {metas de ahorro}': '[افتح] {أهداف الادخار}',
    '{Pagué 250 de luz y 180 de agua}': '{دفعت 250 كهرباء و180 ماء}',
    '[Abre] el {formulario}': '[افتح] {كتاب المعادلات}',
    '[Resolver ecuación]': '[حل معادلة]',
    '[Convertir unidades]': '[تحويل الوحدات]',
    '[Sistema de ecuaciones]': '[نظام معادلات]',
    '[Convertir a binario]': '[التحويل إلى ثنائي]',
    '[Propina]': '[البقشيش]',
    '[Regla de tres]': '[قاعدة الثلاثة]',
    '[Estudié] {historia romana} {30 min}': '[درست] {التاريخ الروماني} {30 دقيقة}',
    '[Abre] la {sesión de estudio}': '[افتح] {جلسة الدراسة}',
    '[Abre] el {resumen de estudio}': '[افتح] {ملخص الدراسة}',
    'Apunta que aprendí: {los ríos de Europa}': 'دوّن ما تعلمته: {أنهار أوروبا}',
    '[Abre] la {mesa de juegos}': '[افتح] {طاولة الألعاب}',
    'Apunta {la serie Dark} como pendiente': 'دوّن {مسلسل دارك} في قائمة المشاهدة',
    '[Abre] el {mapamundi}': '[افتح] {خريطة العالم}',
    '[Abre] {por conocer}': '[افتح] {أماكن أودّ زيارتها}',
    '[Abre] la {bitácora de viajes}': '[افتح] {يوميات الرحلة}',
    '[Medité] {10 min}': '[تأملتُ] {10 دقائق}',
    '[@]{jardin} [agradezco] {mi salud, mi familia y el café}': '[@]{jardin} [أمتنّ لـ] {صحتي وعائلتي والقهوة}',
    '[Abre] el {resumen del garage}': '[افتح] {ملخص الكراج}',
    '[Abre] {mis vehículos}': '[افتح] {مركباتي}',
    '[Abre] las {efemérides}': '[افتح] {في مثل هذا اليوم}',
    '[Abre] {mis hobbies}': '[افتح] {هواياتي}',
    '[Abre] mis {mapas mentales}': '[افتح] {خرائطي الذهنية}',
    '[Abre] los {mapas conceptuales}': '[افتح] {الخرائط المفاهيمية}',
    '[Dibuja un diagrama de flujo] de {cómo hacer pan}': '[ارسم مخطط تدفق] لـ{كيفية خبز الخبز}',
    '[Haz un esquema] de {lo que me acabas de explicar}': '[اعمل مخططًا] لـ{ما شرحته لي للتو}',
    '[Agenda] una {junta con el cliente} el {martes a las 10}': '[حدّد موعد] {اجتماع مع العميل} يوم {الثلاثاء الساعة 10}',
    '[Apunta el pendiente] {mandar la cotización}': '[سجّل مهمة] {إرسال عرض السعر}',
    '[Abre] mis {pendientes}': '[افتح] {مهامي}',
    '[Abre] mis {citas médicas}': '[افتح] {مواعيدي الطبية}',
    '[Abre] el {progreso de idiomas}': '[افتح] {تقدّم اللغات}',
    '[Construye] un {huerto}': '[ابنِ] {حديقة خضروات}',
    '[Pon] una {pista de carreras}': '[ضع] {مضمار سباق}',
    '[Traza] las {vías del tren}': '[مدّ] {سكة القطار}',
    '[Construye] una {montaña rusa}': '[ابنِ] {أفعوانية}',
    '[Pon] la {meta} de la pista': '[ضع] {خط النهاية} في المضمار',
    '[Corre una carrera] de {3 vueltas}': '[أجرِ سباقًا] من {3 لفّات}',
    '[Quiero montar] la {montaña rusa}': '[أريد ركوب] {الأفعوانية}',
    '[Llévame] a la {meta}': '[خذني] إلى {خط النهاية}',
    '[Pon] una {cancha de fútbol}': '[ضع] {ملعب كرة قدم}',
    '[Crea] una {cancha de básquet}': '[أنشئ] {ملعب كرة سلة}',
    '[Pon] un {campo de béisbol}': '[أضف] {ملعب بيسبول}',
    '[Abre] la {agenda de hoy}': '[افتح] {أجندة اليوم}',
    '[Abre] {mi semana}': '[افتح] {أسبوعي}',
    '[Crea una rutina] de mañana: {agua, estiramiento y gratitud} a las {7:00}': '[أنشئ روتينًا] صباحيًا: {ماء وتمدد وامتنان} في {7:00}',
    '[Crea una rutina] de {lunes y miércoles}: {correr 20 min}': '[أنشئ روتينًا] لـ{الاثنين والأربعاء}: {جري 20 دقيقة}',
    '[Gira el último objeto]': '[أدر آخر عنصر]',
    '[Quita el último objeto]': '[أزل آخر عنصر]',
    '[Genera en 3D] {un dragón morado}': '[أنشئ بالأبعاد الثلاثية] {تنينًا بنفسجيًا}',
    '[Crea una imagen] de {un atardecer en la playa}': '[أنشئ صورة] لـ{غروب على الشاطئ}',
    '[Bájame]': '[أنزلني]',
    '[Vista en] {primera persona}': '[عرض بمنظور] {الشخص الأول}',
    '[Quita el tema]': '[أزل الثيم]',
    '[Volumen] al {40%}': '[الصوت] على {40%}',
    '[Apaga la música]': '[أطفئ الموسيقى]',
    '[Abre] mi {resumen semanal}': '[افتح] {ملخصي الأسبوعي}',
    '[Abre] mi {resumen mensual}': '[افتح] {ملخصي الشهري}',
    '[Transparencia] al {40%}': '[الشفافية] على {40%}',
    '[Apaga los efectos]': '[أطفئ المؤثرات]',
    '[Avísame de mis metas] a las {21:00}': '[نبّهني بأهدافي] الساعة {21:00}',
    '[Apaga los avisos]': '[أوقف التنبيهات]',
    '[Descarga un respaldo] de mis datos': '[نزّل نسخة احتياطية] من بياناتي',
    '[Vuelve a ver la bienvenida]': '[أعد عرض قائمة الترحيب]',
    '[Abre las configuraciones]': '[افتح الإعدادات]',
    '[Recuerda que] {soy vegetariano}': '[تذكّر أنّي] {نباتي}',
    '[@]{cocina} {ensalada de la comida}': '[@]{cocina} {سلطة للغداء}',
    '[Cómo funciona] la {rueda de herramientas}': '[كيف تعمل] {عجلة الأدوات}',
    '[Abre] {ejemplo.com}': '[افتح] {example.com}',
    '[Busca en internet] {recetas de pan}': '[ابحث في الإنترنت عن] {وصفات الخبز}',
    '[Historial]': '[السجل]',
    '[Sitios]': '[المواقع]',
    '[Tiempo en internet]': '[وقت الإنترنت]',
    '[Cómo llegar]': '[الاتجاهات]',
    '[Amigos]': '[الأصدقاء]',
    '[Comí] {pollo con arroz} en la {cena}': '[أكلت] {دجاجًا بالأرز} على {العشاء}',
    '[Abre] la {dieta}': '[افتح] {الحمية}',
    '[Entrené] {pierna} {45 min}': '[تمرنت على] {الأرجل} لمدة {45 دقيقة}',
    '[Abre] {fuerza}': '[افتح] {القوة}',
    '[Abre] {cardio}': '[افتح] {الكارديو}',
    '[Abre] {flexibilidad}': '[افتح] {المرونة}',
    '[Haz] una {sentadilla}': '[نفّذ] {سكوات}',
    '[Arma una rutina] de {estiramientos} para {la espalda baja}': '[جهّز روتينًا] من {تمارين الإطالة} لـ{أسفل الظهر}',
    '[Abre] mis {anécdotas}': '[افتح] {حكاياتي}',
    '[Gasté] {500} en {el súper}': '[أنفقت] {500} في {السوبرماركت}',
    '[Abre] el {balance}': '[افتح] {التدفق النقدي}',
    '[Abre] los {movimientos}': '[افتح] {المعاملات}',
    '[Abre] las {divisas}': '[افتح] {العملات}',
    '[Abre] las {criptomonedas}': '[افتح] {العملات الرقمية}',
    '[Abre] las {materias primas}': '[افتح] {السلع}',
    '[Abre] la {calculadora}': '[افتح] {الآلة الحاسبة}',
    '[Abre] el {graficador}': '[افتح] {الرسم البياني}',
    '[Abre] las {hojas de cálculo}': '[افتح] {جداول البيانات}',
    '[Abre] las {matrices}': '[افتح] {المصفوفات}',
    '[Abre] las {charlas}': '[افتح] {المحادثات}',
    '[Abre] la {enciclopedia}': '[افتح] {الموسوعة}',
    '[Vi la película] {Dune}': '[شاهدت فيلم] {ديون}',
    '[Jugué] {ajedrez} con mi hermano': '[لعبت] {الشطرنج} مع أخي',
    '[Abre] el {archivo}': '[افتح] {الأرشيف}',
    '[Quiero jugar] la {viborita}': '[أريد لعب] {الثعبان}',
    '[Juega] {tetris}': '[العب] {تتريس}',
    '[Juega] una partida de {ajedrez}': '[العب] لعبة {شطرنج}',
    '[Abre] las {rutas}': '[افتح] {المسارات}',
    '[Visité] {Oaxaca}': '[زرت] {مراكش}',
    'Quiero conocer {Japón}': 'أريد زيارة {اليابان}',
    '[Visité] {Roma}: {la fontana de noche es mágica}': '[زرت] {روما}: {النافورة ليلًا ساحرة}',
    '[Abre] la {meditación}': '[افتح] {التأمل}',
    '[Abre] la {respiración}': '[افتح] {التنفس}',
    '[Abre] los {agradecimientos}': '[افتح] {الامتنان}',
    '[Abre] los {titulares}': '[افتح] {العناوين}',
    'Avancé en mi [proyecto] de {acuarela} {40 min}': 'تقدّمت في [مشروعي] لـ{الألوان المائية} لمدة {40 دقيقة}',
    'Practiqué {guitarra} {25 min}': 'تدرّبت على {الغيتار} لمدة {25 دقيقة}',
    '[Hazme un mapa mental] de {la fotosíntesis}': '[اصنع لي خريطة ذهنية] عن {البناء الضوئي}',
    '[Compara] {café} y {té} en un mapa': '[قارن] {القهوة} بـ{الشاي} في خريطة',
    '[Tengo cita] con el {dentista} el {14 a las 5}': '[لدي موعد] مع {طبيب الأسنان} في {الـ14 الساعة 5}',
    '[Recuérdame] tomar {ibuprofeno} a las {8 y a las 20}': '[ذكّرني] بتناول {الإيبوبروفين} الساعة {8 و20}',
    '[Guarda el contacto] de {Ana}: {5512345678}, cumple el {3 de mayo}': '[احفظ جهة اتصال] {سارة}: {5512345678}، عيد ميلادها في {3 مايو}',
    '[Abre] mis {contactos}': '[افتح] {جهات اتصالي}',
    '[Vocab] {inglés}: {dog} = {perro}': '[مفردات] {الإنجليزية}: {dog} = {كلب}',
    '[Abre] el {tutor}': '[افتح] {المعلّم}',
    '[Abre] el {repaso}': '[افتح] {المراجعة}',
    '[Abre] el {temario}': '[افتح] {المنهج}',
    '[Repasé] {francés} {15 min}': '[راجعت] {الفرنسية} {15 دقيقة}',
    'Aprendí en {alemán}: {Hund} = {perro}': 'تعلّمت في {الألمانية}: {Hund} = {كلب}',
    '[Quiero sembrar] {zanahorias}': '[أريد زراعة] {الجزر}',
    '[Siembra] {maíz} en el huerto': '[ازرع] {الذرة} في حديقة الخضروات',
    '[Pon] un {aspersor} en el huerto': '[ضع] {رشّاشًا} في حديقة الخضروات',
    '[Riega] el {huerto}': '[اسقِ] {حديقة الخضروات}',
    '[Cosecha] el {huerto}': '[احصد] {حديقة الخضروات}',
    '[Llévame] al {huerto}': '[خذني] إلى {حديقة الخضروات}',
    '[Haz] un {corral}': '[أنشئ] {حظيرة}',
    '[Pon] {vacas} en la granja': '[ضع] {أبقارًا} في المزرعة',
    '[Alimenta] a los {animales}': '[أطعم] {الحيوانات}',
    '[Mima] a los {animales}': '[داعب] {الحيوانات}',
    '[Cura] a los {animales}': '[عالج] {الحيوانات}',
    '[Limpia] los {corrales}': '[نظّف] {الحظائر}',
    '[Llévame] a la {granja}': '[خذني] إلى {المزرعة}',
    '[Borra] la {pista}': '[احذف] {المضمار}',
    '[Hagamos una carrera] {contra} un asistente': '[لنتسابق] {ضد} مساعد',
    '[Corre una carrera] {fácil} de {5 vueltas}': '[أجرِ سباقًا] {سهلًا} من {5 لفّات}',
    '[Quiero montar] el {tren}': '[أريد ركوب] {القطار}',
    '[Juguemos] {paintball}': '[لنلعب] {بينتبول}',
    '[Juguemos paintball] {2v2}': '[لنلعب بينتبول] {2v2}',
    '[Reta] a {Luna} a un paintball {1v1}': '[تحدَّ] {لونا} في مباراة بينتبول {1v1}',
    '[Paintball] campal en {difícil}': '[بينتبول] معركة جماعية بمستوى {صعب}',
    '[Sal] del {paintball}': '[اخرج] من {البينتبول}',
    '[Pon] una {cancha de tenis} {azul}': '[ضع] {ملعب تنس} {أزرق}',
    '[Llévame] a la {cancha}': '[خذني] إلى {الملعب}',
    '[Abre] el {cronograma}': '[افتح] {الجدول الزمني}',
    '[Enséñame] las {rutinas}': '[أرني] {الروتينات}',
    '[Crea un cuarto] llamado {Estudio}': '[أنشئ غرفة] باسم {الاستوديو}',
    '[Renombra] la {cocina} a {Oficina}': '[أعد تسمية] {المطبخ} إلى {المكتب}',
    '[Cambia el ícono] de la {cocina} a {🍳}': '[غيّر أيقونة] {المطبخ} إلى {🍳}',
    '[Pon] la {cocina} en categoría {cuerpo}': '[ضع] {المطبخ} في فئة {الجسد}',
    '[Agrega] la {biblioteca} al mapa': '[أضف] {المكتبة} إلى الخريطة',
    '[Elimina] la {cocina}': '[احذف] {المطبخ}',
    '[Abre] la {cocina}': '[افتح] {المطبخ}',
    '[Pinta] la {cocina} de {azul}': '[لوّن] {المطبخ} بـ{الأزرق}',
    '[Piso] de la {cocina} de {madera}': '[أرضية] {المطبخ} من {الخشب}',
    '[Piso] de la {cocina} {rojo}': '[أرضية] {المطبخ} {حمراء}',
    '[Techo] de la {cocina} de {tejas rojas}': '[سقف] {المطبخ} من {القرميد الأحمر}',
    '[Techo a dos aguas] en la {cocina}': '[سقف جملوني] على {المطبخ}',
    '[Haz] la {cocina} {redonda}': '[اجعل] {المطبخ} {دائريًا}',
    '[Agranda] la {cocina}': '[كبّر] {المطبخ}',
    '[Encoge] la {cocina}': '[صغّر] {المطبخ}',
    '[Mueve] la {cocina} a la {derecha}': '[حرّك] {المطبخ} إلى {اليمين}',
    '[Abre el muro] {norte} de la {cocina}': '[افتح الجدار] {الشمالي} لـ{المطبخ}',
    '[Pon una puerta] {corredera} en el muro {sur} de la {cocina}': '[ضع بابًا] {منزلقًا} في الجدار {الجنوبي} لـ{المطبخ}',
    '[Pon] {ladrillo} en el muro {este} de la {cocina}': '[ضع] {الطوب} على الجدار {الشرقي} لـ{المطبخ}',
    '[Haz más grueso] el muro {norte} de la {cocina}': '[زد سُمك] الجدار {الشمالي} لـ{المطبخ}',
    '[Apila] la {sala} sobre la {cocina}': '[ضع] {غرفة المعيشة} فوق {المطبخ}',
    '[Agranda el mapa] hacia el {este}': '[وسّع الخريطة] نحو {الشرق}',
    '[Crea] una {lámpara}': '[أنشئ] {مصباحًا}',
    '[Pinta el último objeto] de {rojo}': '[لوّن آخر عنصر] بـ{الأحمر}',
    '[Haz el último objeto] más {grande}': '[اجعل آخر عنصر] {أكبر}',
    '[Agrupa los objetos] de la {cocina}': '[جمّع العناصر] داخل {المطبخ}',
    '[Genera en 3D] {una fuente de piedra} estilo {minimalista}': '[أنشئ بالأبعاد الثلاثية] {نافورة حجرية} بأسلوب {مينيمالي}',
    '[Ponme] {sombrero} {rojo}': '[ألبسني] {قبعة} {حمراء}',
    '[Quítame] los {lentes}': '[انزع عني] {النظارات}',
    '[Pinta el torso] del [avatar] de {verde}': '[لوّن جذع] [الأفاتار] بـ{الأخضر}',
    '[Haz el avatar] más {grande}': '[اجعل الأفاتار] {أكبر}',
    '[Móntame] en la {bici}': '[أركبني] على {الدراجة}',
    '[Quiero conducir] el {auto}': '[أريد قيادة] {السيارة}',
    '[Vista] {isométrica}': '[عرض] {متساوي القياس}',
    '[Cambia el tema] a {navidad}': '[غيّر الثيم] إلى {عيد الميلاد}',
    '[Fondo] {nieve}': '[الخلفية] {ثلج}',
    '[Pon música] {relajante}': '[شغّل موسيقى] {هادئة}',
    '[Música] {chiptune}': '[الموسيقى] {تشيبتون}',
    '[Modo] {oscuro}': '[الوضع] {داكن}',
    '[Apariencia] {transparente}': '[المظهر] {شفاف}',
    '[Cambia el idioma] a {inglés}': '[غيّر اللغة] إلى {الإنجليزية}',
    '[Tema de interfaz] {neón}': '[سمة الواجهة] {نيون}',
    '[Tipografía] {serif}': '[الخط] {سيريف}',
    '[Estilo de la interfaz] {pixel}': '[نمط الواجهة] {بكسل}',
    '[Pon iconos] {profesionales}': '[استخدم أيقونات] {احترافية}',
    '[Estilo] {cómic}': '[النمط] {كوميك}',
    '[Avísame] de mis {rutinas}': '[نبّهني] بـ{روتيناتي}',
    '[Abre] mi {cuenta}': '[افتح] {حسابي}',
    '[Cómo funciona] la {cocina}': '[كيف يعمل] {المطبخ}',
    '[Cómo funciona] el {editor}': '[كيف يعمل] {المحرر}',
    '[Cómo funciona] el {chat}': '[كيف تعمل] {الدردشة}',
    '[Qué hace] el {inventario}': '[ماذا يفعل] {المخزون}',
    '[Para qué sirve] la {cámara}': '[ما فائدة] {الكاميرا}',
    '[Tutorial de] {ejercicio}': '[شرح] {صالة الرياضة}',
    '[Tutorial de] la {biblioteca}': '[شرح] {المكتبة}',
    '[Tutorial] {general}': '[شرح] {عام}',
  },
  atajos: {
    'Caminar (también con las flechas)': 'المشي (وبمفاتيح الأسهم أيضًا)',
    'Correr (se queda puesto hasta volver a pulsar)': 'الجري (يبقى مفعّلًا حتى الضغط مرة أخرى)',
    'Saltar': 'القفز',
    'Agacharse (mantener pulsado)': 'الانحناء (مع الاستمرار في الضغط)',
    'Lo que tengas delante: entrar al cuarto, subirte o bajarte del vehículo, cambiar de nivel': 'ما أمامك: دخول الغرفة، ركوب المركبة أو النزول منها، تغيير المستوى',
    'Levantar la mano derecha / izquierda': 'رفع اليد اليمنى / اليسرى',
    'Bailar': 'الرقص',
    'Mortal': 'شقلبة خلفية',
    'Abrir la rueda de herramientas': 'فتح عجلة الأدوات',
    'Abrir el chat y escribir': 'فتح المحادثة والكتابة',
    'Cambiar de vista: isométrica, tercera y primera persona': 'تغيير المنظور: متساوي القياس، وثالث، وأول شخص',
    'Esconder o mostrar el HUD': 'إخفاء واجهة المعلومات أو إظهارها',
    'Cerrar lo que esté abierto': 'إغلاق ما هو مفتوح',
    'Conduciendo el OVNI: subir y bajar. En los demás vehículos, Espacio derrapa': 'عند قيادة الطبق الطائر: الصعود والهبوط. في بقية المركبات، المسافة للانزلاق',
  },
  teclas: {
    'Mayús': 'Shift',
    'Espacio': 'مسافة',
    'Espacio · Mayús': 'مسافة · Shift',
  },
}
