import type { ManualTraducido } from './manualI18n'

/**
 * Las frases de ejemplo del manual de comandos en nl, indexadas por su
 * texto español de origen (ver `manualI18n.ts`).
 *
 * GENERADO por `npm run traducir:contenido` — no lo edites a mano.
 */
export const MANUAL_NL: ManualTraducido = {
  frases: {
    '[Corrí] {5 km} en {30 min}': '[Ik liep] {5 km} in {30 min}',
    '[@]{cocina} [comí] {una ensalada}': '[@]{cocina} [ik at] {een salade}',
    '[Abre] el {estudio de audio}': '[Open] de {audiostudio}',
    '[Abre] mis {canciones}': '[Open] mijn {nummers}',
    '[Abre] el {mezclador DJ}': '[Open] de {DJ-mixer}',
    '[Abre] la {galería de arte}': '[Open] de {kunstgalerie}',
    '[Abre] mis {dibujos}': '[Open] mijn {tekeningen}',
    '[Abre] mis {libros}': '[Open] mijn {boeken}',
    '[Abre] el {estudio de escritura}': '[Open] de {schrijfstudio}',
    '[Escribe un cuento] sobre {un faro en invierno} y [guárdalo en mis libros]': '[Schrijf een kort verhaal] over {een vuurtoren in de winter} en [sla het op in mijn boeken]',
    '[Guarda en mis libros] este texto: {Querido diario, hoy…}': '[Sla op in mijn boeken] deze tekst: {Lief dagboek, vandaag…}',
    '[Abre] el {editor de video}': '[Open] de {video-editor}',
    '[Abre] mis {videos}': "[Open] mijn {video's}",
    '[Abre] la {animación 3D}': '[Open] de {3D-animatie}',
    "[Abre] {mis archivos}": "[Open] {mijn bestanden}",
    "[Abre] los {archivos recientes}": "[Open] de {recente bestanden}",
    "[Abre] los {archivos del studio}": "[Open] de {studiobestanden}",
    "[Abre] la {papelera}": "[Open] de {prullenbak}",
    "[Abre] los {archivos destacados}": "[Open] de {bestanden met ster}",
    '[Tomé] {2 vasos} de [agua]': '[Ik dronk] {2 glazen} [water]',
    '[Me pesé]: {74 kg}': '[Ik heb me gewogen]: {74 kg}',
    'Inventa una [receta] {ligera con atún}': 'Bedenk een [recept] {licht, met tonijn}',
    'Arma una [dieta] {alta en proteína}': 'Stel een [dieet] samen {met veel eiwitten}',
    'Agrega {plátano y avena} a la [lista del súper]': 'Zet {bananen en havermout} op de [boodschappenlijst]',
    '[Corrí] {5 km}': '[Ik liep] {5 km}',
    '[Abre] {cardio}': '[Open] {cardio}',
    '[Haz] una {sentadilla}': '[Doe] een {squat}',
    'Registra mi sesión: {crossfit 40 min, intensidad alta}': 'Noteer mijn sessie: {crossfit 40 min, hoge intensiteit}',
    '[Arma una rutina] de {pecho y tríceps} de {45 min}': '[Stel een routine samen] voor {borst en triceps} van {45 min}',
    '[Dormí] {7 horas}, calidad {4/5}': '[Ik sliep] {7 uur}, kwaliteit {4/5}',
    '[Abre] {mi sueño}': '[Open] {mijn slaap}',
    '{Me acosté a las 23, desperté a las 7 y me levanté 2 veces}': '{Om 23 uur naar bed, om 7 uur wakker, twee keer opgestaan}',
    '[Recuerdo]: {tarde de juegos con mi hermana}': '[Herinnering]: {spelletjesmiddag met mijn zus}',
    'Anota esta anécdota: {hoy celebramos el cumple de mamá}': 'Noteer deze herinnering: {vandaag vierden we mama\'s verjaardag}',
    '[Cobré] {8000} de {la quincena}': '[Ik kreeg] {8000} van {het halfmaandelijkse loon}',
    '[Abre] los {gastos fijos}': '[Open] de {vaste lasten}',
    '{Pagué 250 de luz y 180 de agua}': '{Ik betaalde 250 voor licht en 180 voor water}',
    '[Resolver ecuación]': '[Vergelijking oplossen]',
    '[Convertir unidades]': '[Eenheden omrekenen]',
    '[Abre] las {matrices}': '[Open] de {matrices}',
    '[Sistema de ecuaciones]': '[Stelsel vergelijkingen]',
    '[Convertir a binario]': '[Omzetten naar binair]',
    '[Propina]': '[Fooi]',
    '[Regla de tres]': '[Regel van drie]',
    '[Estudié] {historia romana} {30 min}': '[Ik studeerde] {Romeinse geschiedenis} {30 min}',
    'Apunta que aprendí: {los ríos de Europa}': 'Noteer wat ik leerde: {de rivieren van Europa}',
    '[Vi la película] {Dune}': '[Ik zag de film] {Dune}',
    '[Quiero jugar] la {viborita}': '[Ik wil] {snake} [spelen]',
    '[Juega] {tetris}': '[Speel] {tetris}',
    'Apunta {la serie Dark} como pendiente': 'Zet {de serie Dark} op mijn kijklijst',
    '[Abre] {por conocer}': '[Open] {nog te zien}',
    '[Abre] las {rutas}': '[Open] de {routes}',
    '[Visité] {Oaxaca}': '[Ik bezocht] {Oaxaca}',
    'Quiero conocer {Japón}': 'Ik wil naar {Japan}',
    '[Visité] {Roma}: {la fontana de noche es mágica}': '[Ik bezocht] {Rome}: {de fontein is \'s nachts magisch}',
    '[Medité] {10 min}': '[Ik mediteerde] {10 min}',
    '[Abre] el {resumen del garage}': '[Open] het {overzicht van de garage}',
    '[Abre] {mis vehículos}': '[Open] {mijn voertuigen}',
    '[Abre] las {efemérides}': '[Open] {vandaag in de geschiedenis}',
    '[Abre] {mis hobbies}': '[Open] {mijn hobby\'s}',
    '[Dibuja un diagrama de flujo] de {cómo hacer pan}': '[Teken een stroomschema] van {hoe je brood bakt}',
    '[Haz un esquema] de {lo que me acabas de explicar}': '[Maak een schema] van {wat je me net hebt uitgelegd}',
    '[Agenda] una {junta con el cliente} el {martes a las 10}': '[Plan] een {afspraak met de klant} op {dinsdag om 10}',
    '[Apunta el pendiente] {mandar la cotización}': '[Noteer de taak] {de offerte versturen}',
    '[Recuérdame] tomar {ibuprofeno} a las {8 y a las 20}': '[Herinner me] eraan om {8 en om 20} {ibuprofen} te nemen',
    '[Abre] el {tutor}': '[Open] de {tutor}',
    '[Abre] el {progreso de idiomas}': '[Open] de {voortgang van talen}',
    '[Corre una carrera] de {3 vueltas}': '[Rij een race] van {3 ronden}',
    '[Juguemos] {paintball}': '[Laten we] {paintball} [spelen]',
    '[Juguemos paintball] {2v2}': '[Laten we paintball spelen] {2v2}',
    '[Reta] a {Luna} a un paintball {1v1}': '[Daag] {Luna} uit voor een paintball {1v1}',
    '[Sal] del {paintball}': '[Stop] met de {paintball}',
    '[Abre] la {agenda de hoy}': '[Open] de {agenda van vandaag}',
    '[Abre] {mi semana}': '[Open] {mijn week}',
    '[Crea una rutina] de mañana: {agua, estiramiento y gratitud} a las {7:00}': '[Maak een routine] voor \'s ochtends: {water, rekken en dankbaarheid} om {7:00}',
    '[Crea una rutina] de {lunes y miércoles}: {correr 20 min}': '[Maak een routine] voor {maandag en woensdag}: {20 min hardlopen}',
    '[Enséñame] las {rutinas}': '[Laat me] de {routines} zien',
    '[Crea] una {lámpara}': '[Maak] een {lamp}',
    '[Gira el último objeto]': '[Draai het laatste object]',
    '[Quita el último objeto]': '[Haal het laatste object weg]',
    '[Genera en 3D] {un dragón morado}': '[Genereer in 3D] {een paarse draak}',
    '[Crea una imagen] de {un atardecer en la playa}': '[Maak een afbeelding] van {een zonsondergang op het strand}',
    '[Bájame]': '[Laat me eraf]',
    '[Vista en] {primera persona}': '[Beeld in] {eerste persoon}',
    '[Quita el tema]': '[Haal het thema weg]',
    '[Música] {chiptune}': '[Muziek] {chiptune}',
    '[Volumen] al {40%}': '[Volume] op {40%}',
    '[Apaga la música]': '[Zet de muziek uit]',
    '[Tema de interfaz] {neón}': '[Interfacethema] {neon}',
    '[Tipografía] {serif}': '[Lettertype] {serif}',
    '[Estilo de la interfaz] {pixel}': '[Interfacestijl] {pixel}',
    '[Transparencia] al {40%}': '[Transparantie] op {40%}',
    '[Apaga los efectos]': '[Zet de effecten uit]',
    '[Crea un cuarto] llamado {Estudio}': '[Maak een kamer] met de naam {Studio}',
    '[Avísame] de mis {rutinas}': '[Waarschuw me] over mijn {routines}',
    '[Avísame de mis metas] a las {21:00}': '[Herinner me aan mijn doelen] om {21:00}',
    '[Apaga los avisos]': '[Zet de meldingen uit]',
    '[Descarga un respaldo] de mis datos': '[Download een back-up] van mijn gegevens',
    '[Vuelve a ver la bienvenida]': '[Laat het welkom opnieuw zien]',
    '[Abre las configuraciones]': '[Open de instellingen]',
    '[Abre] mi {cuenta}': '[Open] mijn {account}',
    '[Recuerda que] {soy vegetariano}': '[Onthoud dat] {ik vegetariër ben}',
    '[@]{cocina} {ensalada de la comida}': '[@]{cocina} {salade voor de lunch}',
    '[Cómo funciona] el {editor}': '[Hoe werkt] de {editor}',
    '[Cómo funciona] el {chat}': '[Hoe werkt] de {chat}',
    '[Para qué sirve] la {cámara}': '[Waar dient] de {camera} [voor]',
    '[Abre] {ejemplo.com}': '[Open] {voorbeeld.nl}',
    '[Busca en internet] {recetas de pan}': '[Zoek op internet] {brood recepten}',
    '[Historial]': '[Geschiedenis]',
    '[Sitios]': '[Sites]',
    '[Tiempo en internet]': '[Tijd online]',
    '[Cómo llegar]': '[Route]',
    '[Amigos]': '[Vrienden]',
    '[Jugar] {paintball} [con] {@ana}': '[Speel] {paintball} [met] {@ana}',
    '{Tenis} {@ana}': '{Tennis} {@ana}',
  },
  atajos: {
    'Caminar (también con las flechas)': 'Lopen (ook met de pijltjestoetsen)',
    'Correr (se queda puesto hasta volver a pulsar)': 'Rennen (blijft aan tot je nog eens drukt)',
    'Saltar': 'Springen',
    'Agacharse (mantener pulsado)': 'Bukken (ingedrukt houden)',
    'Lo que tengas delante: entrar al cuarto, subirte o bajarte del vehículo, cambiar de nivel': 'Wat er voor je staat: de kamer in, op of van het voertuig, van niveau wisselen',
    'Levantar la mano derecha / izquierda': 'Rechter- / linkerhand opsteken',
    'Bailar': 'Dansen',
    'Mortal': 'Salto',
    'Abrir la rueda de herramientas': 'Het gereedschapswiel openen',
    'Abrir el chat y escribir': 'De chat openen en typen',
    'Cambiar de vista: isométrica, tercera y primera persona': 'Van beeld wisselen: isometrisch, derde en eerste persoon',
    'Esconder o mostrar el HUD': 'De HUD verbergen of tonen',
    'Cerrar lo que esté abierto': 'Sluiten wat openstaat',
    'Conduciendo el OVNI: subir y bajar. En los demás vehículos, Espacio derrapa': 'In de ufo: omhoog en omlaag. In andere voertuigen laat Spatie je driften',
  },
  teclas: {
    'Mayús': 'Shift',
    'Espacio': 'Spatie',
    'Espacio · Mayús': 'Spatie · Shift',
  },
}
