import type { ManualTraducido } from './manualI18n'

/**
 * Las frases de ejemplo del manual de comandos en ar, indexadas por su
 * texto español de origen (ver `manualI18n.ts`).
 *
 * GENERADO por `npm run traducir:contenido` — no lo edites a mano.
 */
export const MANUAL_AR: ManualTraducido = {
  frases: {
    '[Tomé] {2 vasos} de [agua]': '[شربت] {كوبين} من [الماء]',
    '[Me pesé]: {74 kg}': '[وزنت نفسي]: {74 كغ}',
    '[Abre] el {recetario}': '[افتح] {كتاب الوصفات}',
    '[Abre] la {lista del súper}': '[افتح] {قائمة التسوق}',
    '[Abre] el {diario de comidas}': '[افتح] {يوميات الطعام}',
    '[Abre] las {metas de nutrición}': '[افتح] {أهداف التغذية}',
    'Inventa una [receta] {ligera con atún}': 'ابتكر [وصفة] {خفيفة بالتونة}',
    'Arma una [dieta] {alta en proteína}': 'جهّز [نظامًا غذائيًا] {عالي البروتين}',
    'Agrega {plátano y avena} a la [lista del súper]': 'أضف {موز وشوفان} إلى [قائمة التسوق]',
    '[Corrí] {5 km}': '[ركضت] {5 كم}',
    '[Abre] el {plan de ejercicio}': '[افتح] {خطة التمرين}',
    '[Abre] las {metas de ejercicio}': '[افتح] {أهداف التمرين}',
    '[Muéstrame] cómo se hace el {press banca}': '[أرني] كيف يُؤدى {ضغط البنش}',
    'Registra mi sesión: {crossfit 40 min, intensidad alta}': 'سجّل جلستي: {كروسفيت 40 دقيقة، شدة عالية}',
    '[Arma una rutina] de {pecho y tríceps} de {45 min}': '[جهّز روتينًا] لـ{الصدر والترايسبس} مدته {45 دقيقة}',
    '[Dormí] {7 horas}, calidad {4/5}': '[نمت] {7 ساعات}، الجودة {4/5}',
    '[Abre] el {despertador}': '[افتح] {المنبّه}',
    '[Abre] {mi sueño}': '[افتح] {نومي}',
    '{Me acosté a las 23, desperté a las 7 y me levanté 2 veces}': '{نمت الساعة 23 واستيقظت الساعة 7 ونهضت مرتين}',
    '[Recuerdo]: {tarde de juegos con mi hermana}': '[ذكرى]: {أمسية ألعاب مع أختي}',
    '[Abre] el {calendario de ánimo}': '[افتح] {تقويم المزاج}',
    'Anota esta anécdota: {hoy celebramos el cumple de mamá}': 'دوّن هذه الذكرى: {احتفلنا اليوم بعيد ميلاد أمي}',
    '[Cobré] {8000} de {la quincena}': '[قبضت] {8000} من {راتب نصف الشهر}',
    '[Abre] los {gastos fijos}': '[افتح] {المصاريف الثابتة}',
    '[Abre] las {metas de ahorro}': '[افتح] {أهداف الادخار}',
    '{Pagué 250 de luz y 180 de agua}': '{دفعت 250 كهرباء و180 ماء}',
    '[Abre] el {formulario}': '[افتح] {كتاب المعادلات}',
    '[Resolver ecuación]': '[حل معادلة]',
    '[Convertir unidades]': '[تحويل الوحدات]',
    '[Sistema de ecuaciones]': '[نظام معادلات]',
    '[Convertir a binario]': '[التحويل إلى ثنائي]',
    '[Propina]': '[البقشيش]',
    '[Regla de tres]': '[قاعدة الثلاثة]',
    '[Estudié] {historia romana} {30 min}': '[درست] {التاريخ الروماني} {30 دقيقة}',
    '[Abre] la {sesión de estudio}': '[افتح] {جلسة الدراسة}',
    '[Abre] el {resumen de estudio}': '[افتح] {ملخص الدراسة}',
    'Apunta que aprendí: {los ríos de Europa}': 'دوّن ما تعلمته: {أنهار أوروبا}',
    '[Abre] la {mesa de juegos}': '[افتح] {طاولة الألعاب}',
    'Apunta {la serie Dark} como pendiente': 'دوّن {مسلسل دارك} في قائمة المشاهدة',
    '[Abre] el {mapamundi}': '[افتح] {خريطة العالم}',
    '[Abre] {por conocer}': '[افتح] {أماكن أودّ زيارتها}',
    '[Abre] la {bitácora de viajes}': '[افتح] {يوميات الرحلة}',
    '[Medité] {10 min}': '[تأملتُ] {10 دقائق}',
    '[@]{jardin} [agradezco] {mi salud, mi familia y el café}': '[@]{jardin} [أمتنّ لـ] {صحتي وعائلتي والقهوة}',
    '[Abre] el {resumen del garage}': '[افتح] {ملخص الكراج}',
    '[Abre] {mis vehículos}': '[افتح] {مركباتي}',
    '[Abre] las {efemérides}': '[افتح] {في مثل هذا اليوم}',
    '[Abre] {mis hobbies}': '[افتح] {هواياتي}',
    '[Abre] mis {mapas mentales}': '[افتح] {خرائطي الذهنية}',
    '[Abre] los {mapas conceptuales}': '[افتح] {الخرائط المفاهيمية}',
    '[Dibuja un diagrama de flujo] de {cómo hacer pan}': '[ارسم مخطط تدفق] لـ{كيفية خبز الخبز}',
    '[Haz un esquema] de {lo que me acabas de explicar}': '[اعمل مخططًا] لـ{ما شرحته لي للتو}',
    '[Agenda] una {junta con el cliente} el {martes a las 10}': '[حدّد موعد] {اجتماع مع العميل} يوم {الثلاثاء الساعة 10}',
    '[Apunta el pendiente] {mandar la cotización}': '[سجّل مهمة] {إرسال عرض السعر}',
    '[Abre] mis {pendientes}': '[افتح] {مهامي}',
    '[Abre] mis {citas médicas}': '[افتح] {مواعيدي الطبية}',
    '[Abre] el {progreso de idiomas}': '[افتح] {تقدّم اللغات}',
    '[Construye] un {huerto}': '[ابنِ] {حديقة خضروات}',
    '[Pon] una {pista de carreras}': '[ضع] {مضمار سباق}',
    '[Traza] las {vías del tren}': '[مدّ] {سكة القطار}',
    '[Construye] una {montaña rusa}': '[ابنِ] {أفعوانية}',
    '[Pon] la {meta} de la pista': '[ضع] {خط النهاية} في المضمار',
    '[Corre una carrera] de {3 vueltas}': '[أجرِ سباقًا] من {3 لفّات}',
    '[Quiero montar] la {montaña rusa}': '[أريد ركوب] {الأفعوانية}',
    '[Llévame] a la {meta}': '[خذني] إلى {خط النهاية}',
    '[Pon] una {cancha de fútbol}': '[ضع] {ملعب كرة قدم}',
    '[Crea] una {cancha de básquet}': '[أنشئ] {ملعب كرة سلة}',
    '[Pon] un {campo de béisbol}': '[أضف] {ملعب بيسبول}',
    '[Abre] la {agenda de hoy}': '[افتح] {أجندة اليوم}',
    '[Abre] {mi semana}': '[افتح] {أسبوعي}',
    '[Crea una rutina] de mañana: {agua, estiramiento y gratitud} a las {7:00}': '[أنشئ روتينًا] صباحيًا: {ماء وتمدد وامتنان} في {7:00}',
    '[Crea una rutina] de {lunes y miércoles}: {correr 20 min}': '[أنشئ روتينًا] لـ{الاثنين والأربعاء}: {جري 20 دقيقة}',
    '[Gira el último objeto]': '[أدر آخر عنصر]',
    '[Quita el último objeto]': '[أزل آخر عنصر]',
    '[Genera en 3D] {un dragón morado}': '[أنشئ بالأبعاد الثلاثية] {تنينًا بنفسجيًا}',
    '[Crea una imagen] de {un atardecer en la playa}': '[أنشئ صورة] لـ{غروب على الشاطئ}',
    '[Bájame]': '[أنزلني]',
    '[Vista en] {primera persona}': '[عرض بمنظور] {الشخص الأول}',
    '[Quita el tema]': '[أزل الثيم]',
    '[Volumen] al {40%}': '[الصوت] على {40%}',
    '[Apaga la música]': '[أطفئ الموسيقى]',
    '[Abre] mi {resumen semanal}': '[افتح] {ملخصي الأسبوعي}',
    '[Abre] mi {resumen mensual}': '[افتح] {ملخصي الشهري}',
    '[Transparencia] al {40%}': '[الشفافية] على {40%}',
    '[Apaga los efectos]': '[أطفئ المؤثرات]',
    '[Avísame de mis metas] a las {21:00}': '[نبّهني بأهدافي] الساعة {21:00}',
    '[Apaga los avisos]': '[أوقف التنبيهات]',
    '[Descarga un respaldo] de mis datos': '[نزّل نسخة احتياطية] من بياناتي',
    '[Vuelve a ver la bienvenida]': '[أعد عرض قائمة الترحيب]',
    '[Abre las configuraciones]': '[افتح الإعدادات]',
    '[Recuerda que] {soy vegetariano}': '[تذكّر أنّي] {نباتي}',
    '[@]{cocina} {ensalada de la comida}': '[@]{cocina} {سلطة للغداء}',
    '[Cómo funciona] la {rueda de herramientas}': '[كيف تعمل] {عجلة الأدوات}',
  },
  atajos: {
    'Caminar (también con las flechas)': 'المشي (وبمفاتيح الأسهم أيضًا)',
    'Correr (se queda puesto hasta volver a pulsar)': 'الجري (يبقى مفعّلًا حتى الضغط مرة أخرى)',
    'Saltar': 'القفز',
    'Agacharse (mantener pulsado)': 'الانحناء (مع الاستمرار في الضغط)',
    'Lo que tengas delante: entrar al cuarto, subirte o bajarte del vehículo, cambiar de nivel': 'ما أمامك: دخول الغرفة، ركوب المركبة أو النزول منها، تغيير المستوى',
    'Levantar la mano derecha / izquierda': 'رفع اليد اليمنى / اليسرى',
    'Bailar': 'الرقص',
    'Mortal': 'شقلبة خلفية',
    'Abrir la rueda de herramientas': 'فتح عجلة الأدوات',
    'Abrir el chat y escribir': 'فتح المحادثة والكتابة',
    'Cambiar de vista: isométrica, tercera y primera persona': 'تغيير المنظور: متساوي القياس، وثالث، وأول شخص',
    'Esconder o mostrar el HUD': 'إخفاء واجهة المعلومات أو إظهارها',
    'Cerrar lo que esté abierto': 'إغلاق ما هو مفتوح',
    'Conduciendo el OVNI: subir y bajar. En los demás vehículos, Espacio derrapa': 'عند قيادة الطبق الطائر: الصعود والهبوط. في بقية المركبات، المسافة للانزلاق',
  },
  teclas: {
    'Mayús': 'Shift',
    'Espacio': 'مسافة',
    'Espacio · Mayús': 'مسافة · Shift',
  },
}
