import type { ManualTraducido } from './manualI18n'

/**
 * Las frases de ejemplo del manual de comandos en de, indexadas por su
 * texto español de origen (ver `manualI18n.ts`).
 *
 * GENERADO por `npm run traducir:contenido` — no lo edites a mano.
 */
export const MANUAL_DE: ManualTraducido = {
  frases: {
    '[Corrí] {5 km} en {30 min}': '[Ich bin] {5 km} in {30 min} [gelaufen]',
    '[@]{cocina} [comí] {una ensalada}': '[@]{cocina} [ich habe] {einen Salat} [gegessen]',
    '[Abre] el {estudio de audio}': '[Öffne] das {Audiostudio}',
    '[Abre] mis {canciones}': '[Öffne] meine {Songs}',
    '[Abre] el {mezclador DJ}': '[Öffne] das {DJ-Mischpult}',
    '[Abre] la {galería de arte}': '[Öffne] die {Kunstgalerie}',
    '[Abre] mis {dibujos}': '[Öffne] meine {Zeichnungen}',
    '[Abre] mis {libros}': '[Öffne] meine {Bücher}',
    '[Abre] el {estudio de escritura}': '[Öffne] das {Schreibstudio}',
    '[Escribe un cuento] sobre {un faro en invierno} y [guárdalo en mis libros]': '[Schreib eine Kurzgeschichte] über {einen Leuchtturm im Winter} und [speicher sie in meinen Büchern]',
    '[Guarda en mis libros] este texto: {Querido diario, hoy…}': '[Speicher in meinen Büchern] diesen Text: {Liebes Tagebuch, heute…}',
    '[Abre] el {editor de video}': '[Öffne] den {Videoeditor}',
    '[Abre] mis {videos}': '[Öffne] meine {Videos}',
    '[Abre] la {animación 3D}': '[Öffne] die {3D-Animation}',
    '[Tomé] {2 vasos} de [agua]': '[Ich habe] {2 Gläser} [Wasser] [getrunken]',
    '[Me pesé]: {74 kg}': '[Ich habe mich gewogen]: {74 kg}',
    '[Abre] el {diario de comidas}': '[Öffne] das {Ernährungstagebuch}',
    '[Abre] las {metas de nutrición}': '[Öffne] die {Ernährungsziele}',
    'Inventa una [receta] {ligera con atún}': 'Denk dir ein [Rezept] aus, {leicht, mit Thunfisch}',
    'Arma una [dieta] {alta en proteína}': 'Stell eine [Ernährung] {mit viel Protein} zusammen',
    'Agrega {plátano y avena} a la [lista del súper]': 'Setz {Bananen und Haferflocken} auf die [Einkaufsliste]',
    '[Corrí] {5 km}': '[Ich bin] {5 km} [gelaufen]',
    '[Muéstrame] cómo se hace el {press banca}': '[Zeig mir], wie {Bankdrücken} geht',
    'Registra mi sesión: {crossfit 40 min, intensidad alta}': 'Trag meine Einheit ein: {Crossfit 40 Min, hohe Intensität}',
    '[Arma una rutina] de {pecho y tríceps} de {45 min}': '[Stell eine Routine] für {Brust und Trizeps} über {45 Min} [zusammen]',
    '[Dormí] {7 horas}, calidad {4/5}': '[Ich habe] {7 Stunden} [geschlafen], Qualität {4/5}',
    '[Abre] {mi sueño}': '[Öffne] {mein Schlafen}',
    '{Me acosté a las 23, desperté a las 7 y me levanté 2 veces}': '{Um 23 Uhr ins Bett, um 7 Uhr wach, zweimal aufgestanden}',
    '[Recuerdo]: {tarde de juegos con mi hermana}': '[Erinnerung]: {Spielenachmittag mit meiner Schwester}',
    'Anota esta anécdota: {hoy celebramos el cumple de mamá}': 'Notier diese Anekdote: {heute haben wir Mamas Geburtstag gefeiert}',
    '[Cobré] {8000} de {la quincena}': '[Ich habe] {8000} {vom Halbmonatslohn} [bekommen]',
    '{Pagué 250 de luz y 180 de agua}': '{Ich habe 250 Strom und 180 Wasser bezahlt}',
    '[Resolver ecuación]': '[Gleichung lösen]',
    '[Convertir unidades]': '[Einheiten umrechnen]',
    '[Sistema de ecuaciones]': '[Gleichungssystem]',
    '[Convertir a binario]': '[In Binär umrechnen]',
    '[Propina]': '[Trinkgeld]',
    '[Regla de tres]': '[Dreisatz]',
    '[Estudié] {historia romana} {30 min}': '[Ich habe] {römische Geschichte} {30 Min} [gelernt]',
    '[Abre] el {resumen de estudio}': '[Öffne] die {Lernübersicht}',
    'Apunta que aprendí: {los ríos de Europa}': 'Notier, was ich gelernt habe: {die Flüsse Europas}',
    '[Vi la película] {Dune}': '[Ich habe den Film] {Dune} [gesehen]',
    'Apunta {la serie Dark} como pendiente': 'Setz {die Serie Dark} auf meine Merkliste',
    '[Abre] la {bitácora de viajes}': '[Öffne] das {Reise-Logbuch}',
    '[Visité] {Oaxaca}': '[Ich war in] {Oaxaca}',
    'Quiero conocer {Japón}': 'Ich will nach {Japan}',
    '[Medité] {10 min}': '[Ich habe] {10 Min} [meditiert]',
    '[Abre] el {resumen del garage}': '[Öffne] die {Garagenübersicht}',
    '[Abre] {mis vehículos}': '[Öffne] {meine Fahrzeuge}',
    '[Abre] las {efemérides}': '[Öffne] {was heute geschah}',
    '[Abre] {mis hobbies}': '[Öffne] {meine Hobbys}',
    '[Dibuja un diagrama de flujo] de {cómo hacer pan}': '[Zeichne ein Flussdiagramm] zu {Brot backen}',
    '[Haz un esquema] de {lo que me acabas de explicar}': '[Mach ein Diagramm] von {dem, was du mir gerade erklärt hast}',
    '[Agenda] una {junta con el cliente} el {martes a las 10}': '[Plane] ein {Meeting mit dem Kunden} am {Dienstag um 10}',
    '[Apunta el pendiente] {mandar la cotización}': '[Notier die Aufgabe] {das Angebot schicken}',
    '[Construye] un {huerto}': '[Bau] einen {Gemüsegarten}',
    '[Corre una carrera] de {3 vueltas}': '[Fahr ein Rennen] über {3 Runden}',
    '[Juguemos paintball] {2v2}': '[Spielen wir Paintball] {2v2}',
    '[Reta] a {Luna} a un paintball {1v1}': '[Fordere] {Luna} zu einem Paintball {1v1} heraus',
    '[Pon] una {cancha de fútbol}': '[Setz] einen {Fußballplatz}',
    '[Abre] la {agenda de hoy}': '[Öffne] die {Agenda von heute}',
    '[Abre] {mi semana}': '[Öffne] {meine Woche}',
    '[Crea una rutina] de mañana: {agua, estiramiento y gratitud} a las {7:00}': '[Leg eine Routine an] für morgens: {Wasser, Dehnen und Dankbarkeit} um {7:00}',
    '[Crea una rutina] de {lunes y miércoles}: {correr 20 min}': '[Leg eine Routine an] für {Montag und Mittwoch}: {20 Min laufen}',
    '[Crea un cuarto] llamado {Estudio}': '[Leg einen Raum an] mit dem Namen {Studio}',
    '[Gira el último objeto]': '[Dreh das letzte Objekt]',
    '[Quita el último objeto]': '[Nimm das letzte Objekt weg]',
    '[Genera en 3D] {un dragón morado}': '[Generier in 3D] {einen lila Drachen}',
    '[Crea una imagen] de {un atardecer en la playa}': '[Mach ein Bild] von {einem Sonnenuntergang am Strand}',
    '[Bájame]': '[Lass mich runter]',
    '[Vista en] {primera persona}': '[Ansicht aus] der {Ich-Perspektive}',
    '[Quita el tema]': '[Nimm das Thema weg]',
    '[Volumen] al {40%}': '[Lautstärke] auf {40 %}',
    '[Apaga la música]': '[Mach die Musik aus]',
    '[Abre] mi {resumen semanal}': '[Öffne] meinen {Wochenrückblick}',
    '[Abre] mi {resumen mensual}': '[Öffne] meinen {Monatsrückblick}',
    '[Transparencia] al {40%}': '[Transparenz] auf {40 %}',
    '[Estilo] {cómic}': '{Comic}-[Stil]',
    '[Apaga los efectos]': '[Mach die Effekte aus]',
    '[Avísame de mis metas] a las {21:00}': '[Erinnere mich an meine Ziele] um {21:00}',
    '[Apaga los avisos]': '[Schalte die Hinweise aus]',
    '[Descarga un respaldo] de mis datos': '[Lade eine Sicherung] meiner Daten herunter',
    '[Vuelve a ver la bienvenida]': '[Zeig mir die Begrüßung noch mal]',
    '[Abre las configuraciones]': '[Öffne die Einstellungen]',
    '[Recuerda que] {soy vegetariano}': '[Merk dir, dass] {ich Vegetarier bin}',
    '[@]{cocina} {ensalada de la comida}': '[@]{cocina} {Salat zum Mittagessen}',
  },
  atajos: {
    'Caminar (también con las flechas)': 'Gehen (auch mit den Pfeiltasten)',
    'Correr (se queda puesto hasta volver a pulsar)': 'Rennen (bleibt an, bis du noch mal drückst)',
    'Saltar': 'Springen',
    'Agacharse (mantener pulsado)': 'Ducken (gedrückt halten)',
    'Lo que tengas delante: entrar al cuarto, subirte o bajarte del vehículo, cambiar de nivel': 'Was auch immer vor dir ist: den Raum betreten, aufs Fahrzeug steigen oder absteigen, die Etage wechseln',
    'Levantar la mano derecha / izquierda': 'Rechte / linke Hand heben',
    'Bailar': 'Tanzen',
    'Mortal': 'Salto',
    'Abrir la rueda de herramientas': 'Werkzeugrad öffnen',
    'Abrir el chat y escribir': 'Chat öffnen und schreiben',
    'Cambiar de vista: isométrica, tercera y primera persona': 'Ansicht wechseln: isometrisch, dritte und erste Person',
    'Esconder o mostrar el HUD': 'HUD ausblenden oder einblenden',
    'Cerrar lo que esté abierto': 'Schließen, was gerade offen ist',
    'Conduciendo el OVNI: subir y bajar. En los demás vehículos, Espacio derrapa': 'Im UFO: rauf und runter. In den anderen Fahrzeugen driftest du mit der Leertaste',
  },
  teclas: {
    'Mayús': 'Umschalt',
    'Espacio': 'Leertaste',
    'Espacio · Mayús': 'Leertaste · Umschalt',
  },
}
