import type { ManualTraducido } from './manualI18n'

/**
 * Las frases de ejemplo del manual de comandos en pt, indexadas por su
 * texto español de origen (ver `manualI18n.ts`).
 *
 * GENERADO por `npm run traducir:contenido` — no lo edites a mano.
 */
export const MANUAL_PT: ManualTraducido = {
  frases: {
    '[Tomé] {2 vasos} de [agua]': '[Bebi] {2 copos} de [água]',
    '[Me pesé]: {74 kg}': '[Me pesei]: {74 kg}',
    '[Abre] el {recetario}': '[Abra] o {livro de receitas}',
    '[Abre] la {lista del súper}': '[Abra] a {lista de compras}',
    '[Abre] el {diario de comidas}': '[Abra] o {diário de refeições}',
    '[Abre] las {metas de nutrición}': '[Abra] as {metas de nutrição}',
    'Inventa una [receta] {ligera con atún}': 'Invente uma [receita] {leve com atum}',
    'Arma una [dieta] {alta en proteína}': 'Monte uma [dieta] {rica em proteína}',
    'Agrega {plátano y avena} a la [lista del súper]': 'Adicione {banana e aveia} à [lista de compras]',
    '[Corrí] {5 km}': '[Corri] {5 km}',
    '[Abre] el {plan de ejercicio}': '[Abra] o {plano de exercícios}',
    '[Abre] {cardio}': '[Abra] {cardio}',
    '[Abre] las {metas de ejercicio}': '[Abra] as {metas de exercício}',
    'Registra mi sesión: {crossfit 40 min, intensidad alta}': 'Registre minha sessão: {crossfit 40 min, intensidade alta}',
    '[Arma una rutina] de {pecho y tríceps} de {45 min}': '[Monte uma rotina] de {peito e tríceps} de {45 min}',
    '[Dormí] {7 horas}, calidad {4/5}': '[Dormi] {7 horas}, qualidade {4/5}',
    '[Abre] {mi sueño}': '[Abra] {meu sono}',
    '{Me acosté a las 23, desperté a las 7 y me levanté 2 veces}': '{Deitei às 23, acordei às 7 e levantei 2 vezes}',
    '[Recuerdo]: {tarde de juegos con mi hermana}': '[Memória]: {tarde de jogos com minha irmã}',
    '[Abre] el {calendario de ánimo}': '[Abra] o {calendário de humor}',
    'Anota esta anécdota: {hoy celebramos el cumple de mamá}': 'Anote esta memória: {hoje comemoramos o aniversário da minha mãe}',
    '[Abre] los {gastos fijos}': '[Abra] os {gastos fixos}',
    '[Abre] las {metas de ahorro}': '[Abra] as {metas de poupança}',
    '[Abre] las {materias primas}': '[Abra] as {commodities}',
    '{Pagué 250 de luz y 180 de agua}': '{Paguei 250 de luz e 180 de água}',
    '[Abre] el {formulario}': '[Abra] o {formulário}',
    '[Resolver ecuación]': '[Resolver equação]',
    '[Convertir unidades]': '[Converter unidades]',
    '[Sistema de ecuaciones]': '[Sistema de equações]',
    '[Convertir a binario]': '[Converter para binário]',
    '[Propina]': '[Gorjeta]',
    '[Regla de tres]': '[Regra de três]',
    '[Estudié] {historia romana} {30 min}': '[Estudei] {história romana} {30 min}',
    '[Abre] la {sesión de estudio}': '[Abra] a {sessão de estudo}',
    '[Abre] el {resumen de estudio}': '[Abra] o {resumo de estudo}',
    'Apunta que aprendí: {los ríos de Europa}': 'Anote o que aprendi: {os rios da Europa}',
    '[Abre] la {mesa de juegos}': '[Abra] a {mesa de jogos}',
    '[Quiero jugar] la {viborita}': '[Quero jogar] {snake}',
    '[Juega] {tetris}': '[Jogue] {tetris}',
    'Apunta {la serie Dark} como pendiente': 'Anote {a série Dark} como pendente',
    '[Abre] el {mapamundi}': '[Abra] o {mapa-múndi}',
    '[Abre] {por conocer}': '[Abra] {a conhecer}',
    '[Abre] la {bitácora de viajes}': '[Abra] o {diário de bordo de viagens}',
    '[Visité] {Oaxaca}': '[Visitei] {Oaxaca}',
    '[Medité] {10 min}': '[Meditei] {10 min}',
    '[Abre] el {resumen del garage}': '[Abre] o {resumo da garagem}',
    '[Abre] {mis vehículos}': '[Abre] {meus veículos}',
    '[Abre] las {efemérides}': '[Abre] as {efemérides}',
    '[Abre] {mis hobbies}': '[Abre] {meus hobbies}',
    '[Abre] mis {mapas mentales}': '[Abre] meus {mapas mentais}',
    '[Abre] los {mapas conceptuales}': '[Abre] os {mapas conceituais}',
    '[Dibuja un diagrama de flujo] de {cómo hacer pan}': '[Desenha um fluxograma] de {como fazer pão}',
    '[Haz un esquema] de {lo que me acabas de explicar}': '[Faz um esquema] do {que você acabou de me explicar}',
    '[Agenda] una {junta con el cliente} el {martes a las 10}': '[Agenda] uma {reunião com o cliente} na {terça às 10}',
    '[Apunta el pendiente] {mandar la cotización}': '[Anota a pendência] {enviar o orçamento}',
    '[Abre] mis {pendientes}': '[Abre] minhas {pendências}',
    '[Abre] mis {citas médicas}': '[Abre] minhas {consultas médicas}',
    '[Abre] el {tutor}': '[Abre] o {tutor}',
    '[Abre] el {progreso de idiomas}': '[Abre] o {progresso de idiomas}',
    '[Pon] una {pista de carreras}': '[Põe] uma {pista de corrida}',
    '[Traza] las {vías del tren}': '[Traça] os {trilhos do trem}',
    '[Construye] una {montaña rusa}': '[Constrói] uma {montanha-russa}',
    '[Pon] la {meta} de la pista': '[Põe] a {linha de chegada} da pista',
    '[Corre una carrera] de {3 vueltas}': '[Faz uma corrida] de {3 voltas}',
    '[Quiero montar] la {montaña rusa}': '[Quero andar] na {montanha-russa}',
    '[Llévame] a la {meta}': '[Me leva] à {linha de chegada}',
    '[Juguemos] {paintball}': '[Vamos jogar] {paintball}',
    '[Juguemos paintball] {2v2}': '[Vamos jogar paintball] {2v2}',
    '[Reta] a {Luna} a un paintball {1v1}': '[Desafia] a {Luna} para um paintball {1v1}',
    '[Sal] del {paintball}': '[Sai] do {paintball}',
    '[Pon] una {cancha de fútbol}': '[Põe] um {campo de futebol}',
    '[@]{jardin} [agradezco] {mi salud, mi familia y el café}': '[@]{jardin} [agradeço] {minha saúde, minha família e o café}',
    '[Crea] una {cancha de básquet}': '[Crie] uma {quadra de basquete}',
    '[Pon] un {campo de béisbol}': '[Coloque] um {campo de beisebol}',
    '[Abre] la {agenda de hoy}': '[Abra] a {agenda de hoje}',
    '[Abre] {mi semana}': '[Abra] {minha semana}',
    '[Crea una rutina] de mañana: {agua, estiramiento y gratitud} a las {7:00}': '[Crie uma rotina] de manhã: {água, alongamento e gratidão} às {7:00}',
    '[Crea una rutina] de {lunes y miércoles}: {correr 20 min}': '[Crie uma rotina] de {segunda e quarta}: {correr 20 min}',
    '[Gira el último objeto]': '[Gire o último objeto]',
    '[Quita el último objeto]': '[Tire o último objeto]',
    '[Genera en 3D] {un dragón morado}': '[Gere em 3D] {um dragão roxo}',
    '[Crea una imagen] de {un atardecer en la playa}': '[Crie uma imagem] de {um pôr do sol na praia}',
    '[Móntame] en la {bici}': '[Me coloque] na {bike}',
    '[Bájame]': '[Me tire daí]',
    '[Vista en] {primera persona}': '[Visão em] {primeira pessoa}',
    '[Quita el tema]': '[Tire o tema]',
    '[Música] {chiptune}': '[Música] {chiptune}',
    '[Volumen] al {40%}': '[Volume] em {40%}',
    '[Apaga la música]': '[Desligue a música]',
    '[Abre] mi {resumen semanal}': '[Abra] meu {resumo semanal}',
    '[Abre] mi {resumen mensual}': '[Abra] meu {resumo mensal}',
    '[Tema de interfaz] {neón}': '[Tema da interface] {neon}',
    '[Estilo de la interfaz] {pixel}': '[Estilo da interface] {pixel}',
    '[Transparencia] al {40%}': '[Transparência] em {40%}',
    '[Apaga los efectos]': '[Desligue os efeitos]',
    '[Avísame de mis metas] a las {21:00}': '[Me lembre das minhas metas] às {21:00}',
    '[Apaga los avisos]': '[Desligue os avisos]',
    '[Descarga un respaldo] de mis datos': '[Baixe um backup] dos meus dados',
    '[Vuelve a ver la bienvenida]': '[Mostre as boas-vindas de novo]',
    '[Abre las configuraciones]': '[Abra as configurações]',
    '[Recuerda que] {soy vegetariano}': '[Lembre que] {sou vegetariano}',
    '[Cómo funciona] el {editor}': '[Como funciona] o {editor}',
    '[Cómo funciona] la {rueda de herramientas}': '[Como funciona] a {roda de ferramentas}',
    '[Cómo funciona] el {chat}': '[Como funciona] o {chat}',
    '[@]{cocina} {ensalada de la comida}': '[@]{cocina} {salada do almoço}',
  },
  atajos: {
    'Caminar (también con las flechas)': 'Andar (também com as setas)',
    'Correr (se queda puesto hasta volver a pulsar)': 'Correr (fica ativo até apertar de novo)',
    'Saltar': 'Pular',
    'Agacharse (mantener pulsado)': 'Agachar (segurar)',
    'Lo que tengas delante: entrar al cuarto, subirte o bajarte del vehículo, cambiar de nivel': 'O que estiver na sua frente: entrar no cômodo, subir ou descer do veículo, mudar de nível',
    'Levantar la mano derecha / izquierda': 'Levantar a mão direita / esquerda',
    'Bailar': 'Dançar',
    'Mortal': 'Salto mortal',
    'Abrir la rueda de herramientas': 'Abrir a roda de ferramentas',
    'Abrir el chat y escribir': 'Abrir o chat e escrever',
    'Cambiar de vista: isométrica, tercera y primera persona': 'Mudar de vista: isométrica, terceira e primeira pessoa',
    'Esconder o mostrar el HUD': 'Esconder ou mostrar o HUD',
    'Cerrar lo que esté abierto': 'Fechar o que estiver aberto',
    'Conduciendo el OVNI: subir y bajar. En los demás vehículos, Espacio derrapa': 'Pilotando o OVNI: subir e descer. Nos outros veículos, Espaço derrapa',
  },
  teclas: {
    'Mayús': 'Shift',
    'Espacio': 'Espaço',
    'Espacio · Mayús': 'Espaço · Shift',
  },
}
