import type { ManualTraducido } from './manualI18n'

/**
 * Las frases de ejemplo del manual de comandos en id, indexadas por su
 * texto español de origen (ver `manualI18n.ts`).
 *
 * GENERADO por `npm run traducir:contenido` — no lo edites a mano.
 */
export const MANUAL_ID: ManualTraducido = {
  frases: {
    '[Corrí] {5 km} en {30 min}': '[Aku lari] {5 km} dalam {30 menit}',
    '[@]{cocina} [comí] {una ensalada}': '[@]{cocina} [aku makan] {salad}',
    '[Abre] el {estudio de audio}': '[Buka] {studio audio}',
    '[Abre] mis {canciones}': '[Buka] {laguku}',
    '[Abre] el {mezclador DJ}': '[Buka] {mixer DJ}',
    '[Abre] la {galería de arte}': '[Buka] {galeri seni}',
    '[Abre] mis {dibujos}': '[Buka] {gambarku}',
    '[Abre] mis {libros}': '[Buka] {bukuku}',
    '[Abre] el {estudio de escritura}': '[Buka] {studio tulis}',
    '[Escribe un cuento] sobre {un faro en invierno} y [guárdalo en mis libros]': '[Tulis cerpen] tentang {mercusuar di musim dingin} dan [simpan di bukuku]',
    '[Guarda en mis libros] este texto: {Querido diario, hoy…}': '[Simpan di bukuku] teks ini: {Diary sayang, hari ini…}',
    '[Abre] el {editor de video}': '[Buka] {editor video}',
    '[Abre] mis {videos}': '[Buka] {videoku}',
    '[Abre] la {animación 3D}': '[Buka] {animasi 3D}',
    "[Abre] {mis archivos}": "[Buka] {berkasku}",
    "[Abre] los {archivos recientes}": "[Buka] {berkas terbaru}",
    "[Abre] los {archivos del studio}": "[Buka] {berkas studio}",
    "[Abre] la {papelera}": "[Buka] {sampah}",
    "[Abre] los {archivos destacados}": "[Buka] {berkas berbintang}",
    '[Tomé] {2 vasos} de [agua]': '[Aku minum] {2 gelas} [air]',
    '[Me pesé]: {74 kg}': '[Aku timbang badan]: {74 kg}',
    '[Abre] el {recetario}': '[Buka] {buku resep}',
    '[Abre] la {lista del súper}': '[Buka] {daftar belanja}',
    '[Abre] el {diario de comidas}': '[Buka] {catatan makan}',
    '[Abre] las {metas de nutrición}': '[Buka] {target nutrisi}',
    'Inventa una [receta] {ligera con atún}': 'Buatkan [resep] {ringan dengan tuna}',
    'Arma una [dieta] {alta en proteína}': 'Susun [pola makan] {tinggi protein}',
    'Agrega {plátano y avena} a la [lista del súper]': 'Tambahkan {pisang dan oat} ke [daftar belanja]',
    '[Corrí] {5 km}': '[Aku lari] {5 km}',
    '[Abre] el {plan de ejercicio}': '[Buka] {rencana olahraga}',
    '[Abre] las {metas de ejercicio}': '[Buka] {target olahraga}',
    '[Muéstrame] cómo se hace el {press banca}': '[Tunjukkan] cara melakukan {bench press}',
    '[Haz] una {sentadilla}': '[Lakukan] {squat}',
    'Registra mi sesión: {crossfit 40 min, intensidad alta}': 'Catat sesiku: {crossfit 40 menit, intensitas tinggi}',
    '[Arma una rutina] de {pecho y tríceps} de {45 min}': '[Susun rutinitas] {dada dan trisep} selama {45 menit}',
    '[Dormí] {7 horas}, calidad {4/5}': '[Aku tidur] {7 jam}, kualitas {4/5}',
    '{Me acosté a las 23, desperté a las 7 y me levanté 2 veces}': '{Aku tidur jam 23, bangun jam 7, dan terbangun 2 kali}',
    '[Recuerdo]: {tarde de juegos con mi hermana}': '[Kenangan]: {sore main board game bareng adikku}',
    '[Abre] el {calendario de ánimo}': '[Buka] {kalender suasana hati}',
    'Anota esta anécdota: {hoy celebramos el cumple de mamá}': 'Catat kenangan ini: {hari ini kami rayakan ulang tahun ibu}',
    '[Abre] los {gastos fijos}': '[Buka] {pengeluaran tetap}',
    '[Abre] las {metas de ahorro}': '[Buka] {target tabungan}',
    '{Pagué 250 de luz y 180 de agua}': '{Aku bayar 250 buat listrik dan 180 buat air}',
    '[Abre] el {formulario}': '[Buka] {buku rumus}',
    '[Resolver ecuación]': '[Selesaikan persamaan]',
    '[Convertir unidades]': '[Konversi satuan]',
    '[Sistema de ecuaciones]': '[Sistem persamaan]',
    '[Convertir a binario]': '[Konversi ke biner]',
    '[Propina]': '[Tip]',
    '[Regla de tres]': '[Aturan tiga]',
    '[Estudié] {historia romana} {30 min}': '[Aku belajar] {sejarah Romawi} {30 menit}',
    '[Abre] la {sesión de estudio}': '[Buka] {sesi belajar}',
    '[Abre] el {resumen de estudio}': '[Buka] {ringkasan belajar}',
    'Apunta que aprendí: {los ríos de Europa}': 'Catat yang aku pelajari: {sungai-sungai di Eropa}',
    '[Vi la película] {Dune}': '[Aku nonton film] {Dune}',
    '[Abre] la {mesa de juegos}': '[Buka] {meja permainan}',
    '[Juega] {tetris}': '[Main] {tetris}',
    'Apunta {la serie Dark} como pendiente': 'Catat {serial Dark} buat ditonton nanti',
    '[Abre] el {mapamundi}': '[Buka] {peta dunia}',
    '[Abre] {por conocer}': '[Buka] {ingin dikunjungi}',
    '[Abre] la {bitácora de viajes}': '[Buka] {jurnal perjalanan}',
    '[Visité] {Oaxaca}': '[Aku mengunjungi] {Oaxaca}',
    '[Abre] la {dieta}': '[Buka] {diet}',
    '[Cobré] {8000} de {la quincena}': '[Aku terima] {8000} dari {gaji dua mingguan}',
    '[Medité] {10 min}': '[Aku meditasi] {10 menit}',
    '[@]{jardin} [agradezco] {mi salud, mi familia y el café}': '[@]{jardin} [aku bersyukur untuk] {kesehatanku, keluargaku, dan kopi}',
    '[Abre] el {resumen del garage}': '[Buka] {ringkasan garasi}',
    '[Abre] las {efemérides}': '[Buka] {hari ini dalam sejarah}',
    '[Abre] mis {mapas mentales}': '[Buka] {peta pikiranku}',
    '[Abre] los {mapas conceptuales}': '[Buka] {peta konsep}',
    '[Dibuja un diagrama de flujo] de {cómo hacer pan}': '[Gambarkan diagram alur] {cara membuat roti}',
    '[Haz un esquema] de {lo que me acabas de explicar}': '[Buat skema] dari {yang baru kamu jelaskan}',
    '[Agenda] una {junta con el cliente} el {martes a las 10}': '[Jadwalkan] {rapat dengan klien} {Selasa jam 10}',
    '[Apunta el pendiente] {mandar la cotización}': '[Catat tugas] {kirim penawaran}',
    '[Recuérdame] tomar {ibuprofeno} a las {8 y a las 20}': '[Ingatkan aku] minum {ibuprofen} jam {8 dan jam 20}',
    '[Abre] mis {pendientes}': '[Buka] {daftar tugasku}',
    '[Abre] mis {citas médicas}': '[Buka] {jadwal dokterku}',
    '[Abre] el {tutor}': '[Buka] {tutor}',
    '[Abre] el {progreso de idiomas}': '[Buka] {progres bahasa}',
    '[Construye] un {huerto}': '[Bangun] {kebun sayur}',
    '[Pon] una {pista de carreras}': '[Pasang] {lintasan balap}',
    '[Traza] las {vías del tren}': '[Pasang] {rel kereta}',
    '[Construye] una {montaña rusa}': '[Bangun] {roller coaster}',
    '[Pon] la {meta} de la pista': '[Pasang] {garis finis} lintasan',
    '[Corre una carrera] de {3 vueltas}': '[Balapan] {3 putaran}',
    '[Quiero montar] la {montaña rusa}': '[Aku mau naik] {roller coaster}',
    '[Llévame] a la {meta}': '[Bawa aku] ke {garis finis}',
    '[Juguemos] {paintball}': '[Ayo main] {paintball}',
    '[Juguemos paintball] {2v2}': '[Ayo main paintball] {2v2}',
    '[Reta] a {Luna} a un paintball {1v1}': '[Tantang] {Luna} main paintball {1v1}',
    '[Sal] del {paintball}': '[Keluar] dari {paintball}',
    '[Pon] una {cancha de fútbol}': '[Pasang] {lapangan sepak bola}',
    '[Crea] una {cancha de básquet}': '[Buat] sebuah {lapangan basket}',
    '[Pon] un {campo de béisbol}': '[Tambahkan] sebuah {lapangan bisbol}',
    '[Abre] la {agenda de hoy}': '[Buka] {agenda hari ini}',
    '[Crea una rutina] de mañana: {agua, estiramiento y gratitud} a las {7:00}': '[Buat rutinitas] pagi: {air, peregangan, dan syukur} jam {7:00}',
    '[Crea una rutina] de {lunes y miércoles}: {correr 20 min}': '[Buat rutinitas] {Senin dan Rabu}: {lari 20 menit}',
    '[Crea un cuarto] llamado {Estudio}': '[Buat ruangan] bernama {Studio}',
    '[Gira el último objeto]': '[Putar objek terakhir]',
    '[Quita el último objeto]': '[Hapus objek terakhir]',
    '[Genera en 3D] {un dragón morado}': '[Buat dalam 3D] {seekor naga ungu}',
    '[Crea una imagen] de {un atardecer en la playa}': '[Buat gambar] {matahari terbenam di pantai}',
    '[Bájame]': '[Turunkan aku]',
    '[Vista en] {primera persona}': '[Tampilan] {orang pertama}',
    '[Quita el tema]': '[Hapus tema]',
    '[Música] {chiptune}': '[Musik] {chiptune}',
    '[Volumen] al {40%}': '[Volume] ke {40%}',
    '[Apaga la música]': '[Matikan musik]',
    '[Abre] mi {resumen semanal}': '[Buka] {rangkuman mingguanku}',
    '[Abre] mi {resumen mensual}': '[Buka] {rangkuman bulananku}',
    '[Tema de interfaz] {neón}': '[Tema antarmuka] {neon}',
    '[Tipografía] {serif}': '[Huruf] {serif}',
    '[Estilo de la interfaz] {pixel}': '[Gaya antarmuka] {pixel}',
    '[Transparencia] al {40%}': '[Transparansi] ke {40%}',
    '[Apaga los efectos]': '[Matikan efek]',
    '[Avísame de mis metas] a las {21:00}': '[Ingatkan aku soal targetku] jam {21:00}',
    '[Apaga los avisos]': '[Matikan notifikasi]',
    '[Descarga un respaldo] de mis datos': '[Unduh cadangan] dataku',
    '[Vuelve a ver la bienvenida]': '[Tampilkan lagi menu selamat datang]',
    '[Abre las configuraciones]': '[Buka pengaturan]',
    '[Recuerda que] {soy vegetariano}': '[Ingat kalau] {aku vegetarian}',
    '[Cómo funciona] el {editor}': '[Bagaimana cara kerja] {editor}',
    '[Cómo funciona] la {rueda de herramientas}': '[Bagaimana cara kerja] {roda alat}',
    '[Cómo funciona] el {chat}': '[Bagaimana cara kerja] {chat}',
    '[@]{cocina} {ensalada de la comida}': '[@]{cocina} {salad buat makan siang}',
    '[Abre] {ejemplo.com}': '[Buka] {contoh.com}',
    '[Busca en internet] {recetas de pan}': '[Cari di internet] {resep roti}',
    '[Historial]': '[Riwayat]',
    '[Sitios]': '[Situs]',
    '[Tiempo en internet]': '[Waktu di internet]',
    '[Cómo llegar]': '[Rute]',
    '[Amigos]': '[Teman]',
    '[Jugar] {paintball} [con] {@ana}': '[Main] {paintball} [dengan] {@ana}',
    '[Comí] {pollo con arroz} en la {cena}': '[Aku makan] {nasi ayam} waktu {makan malam}',
    '[Entrené] {pierna} {45 min}': '[Aku latihan] {kaki} {45 menit}',
    '[Abre] {fuerza}': '[Buka] {kekuatan}',
    '[Abre] {cardio}': '[Buka] {daya tahan}',
    '[Abre] {flexibilidad}': '[Buka] {fleksibilitas}',
    '[Arma una rutina] de {estiramientos} para {la espalda baja}': '[Susun rutinitas] {peregangan} untuk {punggung bawah}',
    '[Abre] el {despertador}': '[Buka] {alarm}',
    '[Abre] {mi sueño}': '[Buka] {tidurku}',
    '[Abre] mis {anécdotas}': '[Buka] {kenanganku}',
    '[Gasté] {500} en {el súper}': '[Aku menghabiskan] {500} di {supermarket}',
    '[Abre] el {balance}': '[Buka] {arus kas}',
    '[Abre] los {movimientos}': '[Buka] {transaksi}',
    '[Abre] las {divisas}': '[Buka] {forex}',
    '[Abre] las {criptomonedas}': '[Buka] {kripto}',
    '[Abre] las {materias primas}': '[Buka] {komoditas}',
    '[Abre] la {calculadora}': '[Buka] {kalkulator}',
    '[Abre] el {graficador}': '[Buka] {grafik}',
    '[Abre] las {hojas de cálculo}': '[Buka] {spreadsheet}',
    '[Abre] las {matrices}': '[Buka] {matriks}',
    '[Abre] las {charlas}': '[Buka] {obrolan}',
    '[Abre] la {enciclopedia}': '[Buka] {ensiklopedia}',
    '[Jugué] {ajedrez} con mi hermano': '[Aku main] {catur} bareng kakakku',
    '[Abre] el {archivo}': '[Buka] {arsip}',
    '[Quiero jugar] la {viborita}': '[Aku mau main] {game ular}',
    '[Juega] una partida de {ajedrez}': '[Mainkan] satu ronde {catur}',
    '[Abre] las {rutas}': '[Buka] {rute}',
    'Quiero conocer {Japón}': 'Aku ingin mengunjungi {Jepang}',
    '[Visité] {Roma}: {la fontana de noche es mágica}': '[Aku mengunjungi] {Roma}: {air mancurnya terasa magis di malam hari}',
    '[Abre] la {meditación}': '[Buka] {meditasi}',
    '[Abre] la {respiración}': '[Buka] {pernapasan}',
    '[Abre] los {agradecimientos}': '[Buka] {syukur}',
    '[Abre] {mis vehículos}': '[Buka] {kendaraanku}',
    '[Abre] los {titulares}': '[Buka] {berita utama}',
    'Avancé en mi [proyecto] de {acuarela} {40 min}': 'Aku melanjutkan [proyek] {cat air} selama {40 menit}',
    'Practiqué {guitarra} {25 min}': 'Aku latihan {gitar} {25 menit}',
    '[Abre] {mis hobbies}': '[Buka] {hobiku}',
    '[Hazme un mapa mental] de {la fotosíntesis}': '[Buatkan peta pikiran] tentang {fotosintesis}',
    '[Compara] {café} y {té} en un mapa': '[Bandingkan] {kopi} dan {teh} dalam sebuah peta',
    '[Tengo cita] con el {dentista} el {14 a las 5}': '[Aku ada janji] dengan {dokter gigi} tanggal {14 jam 5}',
    '[Guarda el contacto] de {Ana}: {5512345678}, cumple el {3 de mayo}': '[Simpan kontak] {Ana}: {081234567890}, ulang tahun {3 Mei}',
    '[Abre] mis {contactos}': '[Buka] {kontakku}',
    '[Vocab] {inglés}: {dog} = {perro}': '[Kosakata] {Inggris}: {dog} = {anjing}',
    '[Abre] el {repaso}': '[Buka] {tinjauan}',
    '[Abre] el {temario}': '[Buka] {silabus}',
    '[Repasé] {francés} {15 min}': '[Aku mengulang] {bahasa Prancis} {15 menit}',
    'Aprendí en {alemán}: {Hund} = {perro}': 'Aku belajar {bahasa Jerman}: {Hund} = {anjing}',
    '[Quiero sembrar] {zanahorias}': '[Aku mau menanam] {wortel}',
    '[Siembra] {maíz} en el huerto': '[Tanam] {jagung} di kebun sayur',
    '[Pon] un {aspersor} en el huerto': '[Pasang] {sprinkler} di kebun sayur',
    '[Riega] el {huerto}': '[Siram] {kebun sayur}',
    '[Cosecha] el {huerto}': '[Panen] {kebun sayur}',
    '[Llévame] al {huerto}': '[Bawa aku] ke {kebun sayur}',
    '[Haz] un {corral}': '[Buat] {kandang}',
    '[Pon] {vacas} en la granja': '[Taruh] {sapi} di peternakan',
    '[Alimenta] a los {animales}': '[Beri makan] {hewan}',
    '[Mima] a los {animales}': '[Elus] {hewan}',
    '[Cura] a los {animales}': '[Sembuhkan] {hewan}',
    '[Limpia] los {corrales}': '[Bersihkan] {kandang}',
    '[Llévame] a la {granja}': '[Bawa aku] ke {peternakan}',
    '[Borra] la {pista}': '[Hapus] {lintasan}',
    '[Hagamos una carrera] {contra} un asistente': '[Ayo balapan] {melawan} asisten',
    '[Corre una carrera] {fácil} de {5 vueltas}': '[Balapan] level {mudah} sebanyak {5 putaran}',
    '[Quiero montar] el {tren}': '[Aku mau naik] {kereta}',
    '[Paintball] campal en {difícil}': '[Paintball] semua lawan semua di level {sulit}',
    '[Pon] una {cancha de tenis} {azul}': '[Pasang] {lapangan tenis} {biru}',
    '[Llévame] a la {cancha}': '[Bawa aku] ke {lapangan}',
    '[Abre] {mi semana}': '[Buka] {jadwal mingguku}',
    '[Abre] el {cronograma}': '[Buka] {linimasa}',
    '[Enséñame] las {rutinas}': '[Tunjukkan] {rutinitas}',
    '[Renombra] la {cocina} a {Oficina}': '[Ganti nama] {dapur} jadi {Kantor}',
    '[Cambia el ícono] de la {cocina} a {🍳}': '[Ganti ikon] {dapur} jadi {🍳}',
    '[Pon] la {cocina} en categoría {cuerpo}': '[Masukkan] {dapur} ke kategori {tubuh}',
    '[Agrega] la {biblioteca} al mapa': '[Tambahkan] {perpustakaan} ke peta',
    '[Elimina] la {cocina}': '[Hapus] {dapur}',
    '[Abre] la {cocina}': '[Buka] {dapur}',
    '[Pinta] la {cocina} de {azul}': '[Cat] {dapur} warna {biru}',
    '[Piso] de la {cocina} de {madera}': '[Lantai] {dapur} dari {kayu}',
    '[Piso] de la {cocina} {rojo}': '[Lantai] {dapur} {merah}',
    '[Techo] de la {cocina} de {tejas rojas}': '[Atap] {dapur} dari {genteng merah}',
    '[Techo a dos aguas] en la {cocina}': '[Atap pelana] di {dapur}',
    '[Haz] la {cocina} {redonda}': '[Buat] {dapur} jadi {bulat}',
    '[Agranda] la {cocina}': '[Perbesar] {dapur}',
    '[Encoge] la {cocina}': '[Perkecil] {dapur}',
    '[Mueve] la {cocina} a la {derecha}': '[Geser] {dapur} ke {kanan}',
    '[Abre el muro] {norte} de la {cocina}': '[Buka dinding] {utara} di {dapur}',
    '[Pon una puerta] {corredera} en el muro {sur} de la {cocina}': '[Pasang pintu] {geser} di dinding {selatan} {dapur}',
    '[Pon] {ladrillo} en el muro {este} de la {cocina}': '[Pasang] {bata} di dinding {timur} {dapur}',
    '[Haz más grueso] el muro {norte} de la {cocina}': '[Tebalkan] dinding {utara} {dapur}',
    '[Apila] la {sala} sobre la {cocina}': '[Tumpuk] {ruang tamu} di atas {dapur}',
    '[Agranda el mapa] hacia el {este}': '[Perluas peta] ke arah {timur}',
    '[Crea] una {lámpara}': '[Buat] sebuah {lampu}',
    '[Pinta el último objeto] de {rojo}': '[Cat objek terakhir] warna {merah}',
    '[Haz el último objeto] más {grande}': '[Buat objek terakhir] jadi lebih {besar}',
    '[Agrupa los objetos] de la {cocina}': '[Kelompokkan objek] di {dapur}',
    '[Genera en 3D] {una fuente de piedra} estilo {minimalista}': '[Buat dalam 3D] {air mancur dari batu} gaya {minimalis}',
    '[Ponme] {sombrero} {rojo}': '[Pakaikan aku] {topi} {merah}',
    '[Quítame] los {lentes}': '[Lepaskan] {kacamataku}',
    '[Pinta el torso] del [avatar] de {verde}': '[Cat badan] [avatar] jadi {hijau}',
    '[Haz el avatar] más {grande}': '[Buat avatar] jadi lebih {besar}',
    '[Móntame] en la {bici}': '[Naikkan aku] ke {sepeda}',
    '[Quiero conducir] el {auto}': '[Aku mau mengendarai] {mobil}',
    '[Vista] {isométrica}': '[Tampilan] {isometrik}',
    '[Cambia el tema] a {navidad}': '[Ganti tema] ke {Natal}',
    '[Fondo] {nieve}': '[Latar belakang] {salju}',
    '[Pon música] {relajante}': '[Putar musik] {santai}',
    '[Modo] {oscuro}': '[Mode] {gelap}',
    '[Apariencia] {transparente}': '[Tampilan] {transparan}',
    '[Cambia el idioma] a {inglés}': '[Ganti bahasa] ke {Inggris}',
    '[Pon iconos] {profesionales}': '[Pasang ikon] {profesional}',
    '[Estilo] {cómic}': '[Gaya] {komik}',
    '[Avísame] de mis {rutinas}': '[Ingatkan aku] soal {rutinitasku}',
    '[Abre] mi {cuenta}': '[Buka] {akunku}',
    '[Cómo funciona] la {cocina}': '[Bagaimana cara kerja] {dapur}',
    '[Qué hace] el {inventario}': '[Apa fungsi] {inventaris}',
    '[Para qué sirve] la {cámara}': '[Apa kegunaan] {kamera}',
    '[Tutorial de] {ejercicio}': '[Tutorial] {Gym}',
    '[Tutorial de] la {biblioteca}': '[Tutorial] {Perpustakaan}',
    '[Tutorial] {general}': '[Tutorial] {umum}',
  },
  atajos: {
    'Caminar (también con las flechas)': 'Jalan (bisa juga pakai tombol panah)',
    'Correr (se queda puesto hasta volver a pulsar)': 'Lari (tetap aktif sampai kamu tekan lagi)',
    'Saltar': 'Lompat',
    'Agacharse (mantener pulsado)': 'Merunduk (tahan)',
    'Lo que tengas delante: entrar al cuarto, subirte o bajarte del vehículo, cambiar de nivel': 'Apa pun yang ada di depanmu: masuk ke ruangan, naik atau turun dari kendaraan, ganti lantai',
    'Levantar la mano derecha / izquierda': 'Angkat tangan kanan / kiri',
    'Bailar': 'Menari',
    'Mortal': 'Salto belakang',
    'Abrir la rueda de herramientas': 'Buka roda alat',
    'Abrir el chat y escribir': 'Buka chat dan ketik',
    'Cambiar de vista: isométrica, tercera y primera persona': 'Ganti sudut pandang: isometrik, orang ketiga, dan orang pertama',
    'Esconder o mostrar el HUD': 'Sembunyikan atau tampilkan HUD',
    'Cerrar lo que esté abierto': 'Tutup apa pun yang sedang terbuka',
    'Conduciendo el OVNI: subir y bajar. En los demás vehículos, Espacio derrapa': 'Saat mengemudikan UFO: naik dan turun. Di kendaraan lain, Spasi untuk ngedrift',
  },
  teclas: {
    'Mayús': 'Shift',
    'Espacio': 'Spasi',
    'Espacio · Mayús': 'Spasi · Shift',
  },
}
