import type { ManualTraducido } from './manualI18n'

/**
 * Las frases de ejemplo del manual de comandos en it, indexadas por su
 * texto español de origen (ver `manualI18n.ts`).
 *
 * GENERADO por `npm run traducir:contenido` — no lo edites a mano.
 */
export const MANUAL_IT: ManualTraducido = {
  frases: {
    '[Corrí] {5 km} en {30 min}': '[Ho corso] {5 km} in {30 min}',
    '[@]{cocina} [comí] {una ensalada}': "[@]{cocina} [ho mangiato] {un'insalata}",
    '[Abre] el {estudio de audio}': '[Apri] lo {studio audio}',
    '[Abre] mis {canciones}': '[Apri] le mie {canzoni}',
    '[Abre] el {mezclador DJ}': '[Apri] il {mixer DJ}',
    '[Abre] la {galería de arte}': "[Apri] la {galleria d'arte}",
    '[Abre] mis {dibujos}': '[Apri] i miei {disegni}',
    '[Abre] mis {libros}': '[Apri] i miei {libri}',
    '[Abre] el {estudio de escritura}': '[Apri] lo {studio di scrittura}',
    '[Escribe un cuento] sobre {un faro en invierno} y [guárdalo en mis libros]': "[Scrivi un racconto] su {un faro d'inverno} e [salvalo nei miei libri]",
    '[Guarda en mis libros] este texto: {Querido diario, hoy…}': '[Salva nei miei libri] questo testo: {Caro diario, oggi…}',
    '[Abre] el {editor de video}': "[Apri] l'{editor video}",
    '[Abre] mis {videos}': '[Apri] i miei {video}',
    '[Abre] la {animación 3D}': "[Apri] l'{animazione 3D}",
    "[Abre] {mis archivos}": "[Apri] {i miei file}",
    "[Abre] los {archivos recientes}": "[Apri] i {file recenti}",
    "[Abre] los {archivos del studio}": "[Apri] i {file dello studio}",
    "[Abre] la {papelera}": "[Apri] il {cestino}",
    "[Abre] los {archivos destacados}": "[Apri] i {file speciali}",
    '[Tomé] {2 vasos} de [agua]': '[Ho bevuto] {2 bicchieri} d\'[acqua]',
    '[Me pesé]: {74 kg}': '[Mi sono pesato]: {74 kg}',
    '[Abre] la {lista del súper}': '[Apri] la {lista della spesa}',
    '[Abre] el {diario de comidas}': '[Apri] il {diario dei pasti}',
    '[Abre] las {metas de nutrición}': '[Apri] gli {obiettivi di nutrizione}',
    'Inventa una [receta] {ligera con atún}': 'Inventa una [ricetta] {leggera con il tonno}',
    'Arma una [dieta] {alta en proteína}': 'Prepara una [dieta] {ricca di proteine}',
    'Agrega {plátano y avena} a la [lista del súper]': 'Aggiungi {banane e avena} alla [lista della spesa]',
    '[Corrí] {5 km}': '[Ho corso] {5 km}',
    '[Abre] el {plan de ejercicio}': '[Apri] il {piano di allenamento}',
    '[Abre] {cardio}': '[Apri] {cardio}',
    '[Abre] las {metas de ejercicio}': '[Apri] gli {obiettivi di allenamento}',
    '[Muéstrame] cómo se hace el {press banca}': '[Mostrami] come si fa la {panca piana}',
    '[Haz] una {sentadilla}': '[Fai] uno {squat}',
    'Registra mi sesión: {crossfit 40 min, intensidad alta}': 'Registra la mia sessione: {crossfit 40 min, intensità alta}',
    '[Arma una rutina] de {pecho y tríceps} de {45 min}': '[Prepara una routine] di {petto e tricipiti} da {45 min}',
    '[Dormí] {7 horas}, calidad {4/5}': '[Ho dormito] {7 ore}, qualità {4/5}',
    '[Abre] {mi sueño}': '[Apri] {il mio sonno}',
    '{Me acosté a las 23, desperté a las 7 y me levanté 2 veces}': '{Sono andato a letto alle 23, mi sono svegliato alle 7 e mi sono alzato 2 volte}',
    '[Recuerdo]: {tarde de juegos con mi hermana}': '[Ricordo]: {pomeriggio di giochi con mia sorella}',
    '[Abre] el {calendario de ánimo}': '[Apri] il {calendario dell\'umore}',
    'Anota esta anécdota: {hoy celebramos el cumple de mamá}': 'Segna questo ricordo: {oggi abbiamo festeggiato il compleanno di mamma}',
    '[Abre] los {gastos fijos}': '[Apri] le {spese fisse}',
    '[Abre] las {metas de ahorro}': '[Apri] gli {obiettivi di risparmio}',
    '{Pagué 250 de luz y 180 de agua}': '{Ho pagato 250 di luce e 180 di acqua}',
    '[Resolver ecuación]': '[Risolvi equazione]',
    '[Convertir unidades]': '[Converti unità]',
    '[Sistema de ecuaciones]': '[Sistema di equazioni]',
    '[Convertir a binario]': '[Converti in binario]',
    '[Propina]': '[Mancia]',
    '[Regla de tres]': '[Regola del tre]',
    '[Estudié] {historia romana} {30 min}': '[Ho studiato] {storia romana} {30 min}',
    '[Abre] la {sesión de estudio}': '[Apri] la {sessione di studio}',
    '[Abre] el {resumen de estudio}': '[Apri] il {riepilogo di studio}',
    'Apunta que aprendí: {los ríos de Europa}': 'Segna quello che ho imparato: {i fiumi d\'Europa}',
    '[Vi la película] {Dune}': '[Ho visto il film] {Dune}',
    '[Abre] la {mesa de juegos}': '[Apri] il {tavolo da gioco}',
    '[Quiero jugar] la {viborita}': '[Voglio giocare] a {snake}',
    '[Juega] {tetris}': '[Gioca] a {tetris}',
    'Apunta {la serie Dark} como pendiente': 'Segna {la serie Dark} tra le cose da vedere',
    '[Abre] {por conocer}': '[Apri] {da visitare}',
    '[Abre] la {bitácora de viajes}': '[Apri] il {diario di bordo dei viaggi}',
    '[Visité] {Oaxaca}': '[Ho visitato] {Oaxaca}',
    '[Medité] {10 min}': '[Ho meditato] {10 min}',
    '[Abre] el {resumen del garage}': '[Apri] il {riepilogo del garage}',
    '[Abre] {mis vehículos}': '[Apri] i {miei veicoli}',
    '[Abre] las {efemérides}': '[Apri] l\'{accadde oggi}',
    '[Abre] {mis hobbies}': '[Apri] i {miei hobby}',
    '[Abre] mis {mapas mentales}': '[Apri] le mie {mappe mentali}',
    '[Abre] los {mapas conceptuales}': '[Apri] le {mappe concettuali}',
    '[Dibuja un diagrama de flujo] de {cómo hacer pan}': '[Disegna un diagramma di flusso] su {come fare il pane}',
    '[Haz un esquema] de {lo que me acabas de explicar}': '[Fai uno schema] di {quello che mi hai appena spiegato}',
    '[Agenda] una {junta con el cliente} el {martes a las 10}': '[Fissa] una {riunione con il cliente} {martedì alle 10}',
    '[Apunta el pendiente] {mandar la cotización}': '[Segna la cosa da fare] {mandare il preventivo}',
    '[Abre] mis {pendientes}': '[Apri] le mie {cose da fare}',
    '[Abre] mis {citas médicas}': '[Apri] le mie {visite mediche}',
    '[Abre] el {tutor}': '[Apri] il {tutor}',
    '[Abre] el {progreso de idiomas}': '[Apri] i {progressi nelle lingue}',
    '[Pon] una {pista de carreras}': '[Metti] una {pista da corsa}',
    '[Traza] las {vías del tren}': '[Traccia] i {binari del treno}',
    '[Construye] una {montaña rusa}': '[Costruisci] delle {montagne russe}',
    '[Corre una carrera] de {3 vueltas}': '[Corri una gara] di {3 giri}',
    '[Quiero montar] la {montaña rusa}': '[Voglio salire sulle] {montagne russe}',
    '[Juguemos] {paintball}': '[Giochiamo a] {paintball}',
    '[Juguemos paintball] {2v2}': '[Giochiamo a paintball] {2v2}',
    '[Reta] a {Luna} a un paintball {1v1}': '[Sfida] {Luna} a paintball {1v1}',
    '[Sal] del {paintball}': '[Esci] dal {paintball}',
    '[Pon] una {cancha de fútbol}': '[Metti] un {campo da calcio}',
    '[@]{jardin} [agradezco] {mi salud, mi familia y el café}': '[@]{jardin} [ringrazio per] {la mia salute, la mia famiglia e il caffè}',
    '[Crea] una {cancha de básquet}': '[Crea] un {campo da basket}',
    '[Pon] un {campo de béisbol}': '[Metti] un {campo da baseball}',
    '[Abre] la {agenda de hoy}': '[Apri] l\'{agenda di oggi}',
    '[Abre] {mi semana}': '[Apri] {la mia settimana}',
    '[Crea una rutina] de mañana: {agua, estiramiento y gratitud} a las {7:00}': '[Crea una routine] del mattino: {acqua, stretching e gratitudine} alle {7:00}',
    '[Crea una rutina] de {lunes y miércoles}: {correr 20 min}': '[Crea una routine] per {lunedì e mercoledì}: {corsa di 20 min}',
    '[Crea un cuarto] llamado {Estudio}': '[Crea una stanza] chiamata {Studio}',
    '[Gira el último objeto]': '[Ruota l\'ultimo oggetto]',
    '[Quita el último objeto]': '[Togli l\'ultimo oggetto]',
    '[Genera en 3D] {un dragón morado}': '[Genera in 3D] {un drago viola}',
    '[Crea una imagen] de {un atardecer en la playa}': '[Crea un\'immagine] di {un tramonto sulla spiaggia}',
    '[Bájame]': '[Fammi scendere]',
    '[Vista en] {primera persona}': '[Vista in] {prima persona}',
    '[Quita el tema]': '[Togli il tema]',
    '[Música] {chiptune}': '[Musica] {chiptune}',
    '[Volumen] al {40%}': '[Volume] al {40%}',
    '[Apaga la música]': '[Spegni la musica]',
    '[Abre] mi {resumen semanal}': '[Apri] il mio {riepilogo settimanale}',
    '[Abre] mi {resumen mensual}': '[Apri] il mio {riepilogo mensile}',
    '[Tema de interfaz] {neón}': '[Tema dell\'interfaccia] {neon}',
    '[Tipografía] {serif}': '[Carattere] {serif}',
    '[Estilo de la interfaz] {pixel}': '[Stile dell\'interfaccia] {pixel}',
    '[Transparencia] al {40%}': '[Trasparenza] al {40%}',
    '[Apaga los efectos]': '[Spegni gli effetti]',
    '[Avísame de mis metas] a las {21:00}': '[Ricordami i miei obiettivi] alle {21:00}',
    '[Apaga los avisos]': '[Spegni gli avvisi]',
    '[Descarga un respaldo] de mis datos': '[Scarica un backup] dei miei dati',
    '[Vuelve a ver la bienvenida]': '[Rivedi il benvenuto]',
    '[Abre las configuraciones]': '[Apri le impostazioni]',
    '[Abre] mi {cuenta}': '[Apri] il mio {account}',
    '[Recuerda que] {soy vegetariano}': '[Ricorda che] {sono vegetariano}',
    '[@]{cocina} {ensalada de la comida}': '[@]{cocina} {insalata per pranzo}',
    '[Cómo funciona] el {editor}': '[Come funziona] l\'{editor}',
    '[Cómo funciona] la {rueda de herramientas}': '[Come funziona] la {ruota degli strumenti}',
    '[Cómo funciona] el {chat}': '[Come funziona] la {chat}',
    '[Abre] {ejemplo.com}': '[Apri] {esempio.com}',
    '[Busca en internet] {recetas de pan}': '[Cerca su internet] {ricette del pane}',
    '[Historial]': '[Cronologia]',
    '[Sitios]': '[Siti]',
    '[Tiempo en internet]': '[Tempo su internet]',
    '[Cómo llegar]': '[Come arrivare]',
    '[Amigos]': '[Amici]',
    '[Jugar] {paintball} [con] {@ana}': '[Giocare a] {paintball} [con] {@ana}',
    '{Tenis} {@ana}': '{Tennis} {@ana}',
  },
  atajos: {
    'Caminar (también con las flechas)': 'Camminare (anche con le frecce)',
    'Correr (se queda puesto hasta volver a pulsar)': 'Correre (resta attivo finché non premi di nuovo)',
    'Saltar': 'Saltare',
    'Agacharse (mantener pulsado)': 'Abbassarsi (tieni premuto)',
    'Lo que tengas delante: entrar al cuarto, subirte o bajarte del vehículo, cambiar de nivel': 'Quello che hai davanti: entrare nella stanza, salire o scendere dal veicolo, cambiare livello',
    'Levantar la mano derecha / izquierda': 'Alzare la mano destra / sinistra',
    'Bailar': 'Ballare',
    'Mortal': 'Salto mortale',
    'Abrir la rueda de herramientas': 'Aprire la ruota degli strumenti',
    'Abrir el chat y escribir': 'Aprire la chat e scrivere',
    'Cambiar de vista: isométrica, tercera y primera persona': 'Cambiare vista: isometrica, terza e prima persona',
    'Esconder o mostrar el HUD': 'Nascondere o mostrare l\'HUD',
    'Cerrar lo que esté abierto': 'Chiudere quello che è aperto',
    'Conduciendo el OVNI: subir y bajar. En los demás vehículos, Espacio derrapa': 'Alla guida dell\'UFO: salire e scendere. Negli altri veicoli, Spazio fa derapare',
  },
  teclas: {
    'Mayús': 'Maiusc',
    'Espacio': 'Spazio',
    'Espacio · Mayús': 'Spazio · Maiusc',
  },
}
