import type { ManualTraducido } from './manualI18n'

/**
 * Las frases de ejemplo del manual de comandos en ko, indexadas por su
 * texto español de origen (ver `manualI18n.ts`).
 *
 * GENERADO por `npm run traducir:contenido` — no lo edites a mano.
 */
export const MANUAL_KO: ManualTraducido = {
  frases: {
    '[Corrí] {5 km} en {30 min}': '{5 km}를 {30분}에 [뛰었어요]',
    '[@]{cocina} [comí] {una ensalada}': '[@]{cocina} {샐러드} [먹었어요]',
    '[Abre] el {estudio de audio}': '{오디오 스튜디오} [열어줘]',
    '[Abre] mis {canciones}': '내 {노래} [열어줘]',
    '[Abre] el {mezclador DJ}': '{DJ 믹서} [열어줘]',
    '[Abre] la {galería de arte}': '{아트 갤러리} [열어줘]',
    '[Abre] mis {dibujos}': '내 {그림} [열어줘]',
    '[Abre] mis {libros}': '내 {책} [열어줘]',
    '[Abre] el {estudio de escritura}': '{글쓰기 스튜디오} [열어줘]',
    '[Escribe un cuento] sobre {un faro en invierno} y [guárdalo en mis libros]': '{겨울의 등대}에 대한 [짧은 이야기를 써서] [내 책에 저장해줘]',
    '[Guarda en mis libros] este texto: {Querido diario, hoy…}': '이 글을 [내 책에 저장해줘]: {사랑하는 일기장아, 오늘은…}',
    '[Abre] el {editor de video}': '{영상 편집기} [열어줘]',
    '[Abre] mis {videos}': '내 {영상} [열어줘]',
    '[Abre] la {animación 3D}': '{3D 애니메이션} [열어줘]',
    '[Tomé] {2 vasos} de [agua]': '[물] {2잔} [마셨어요]',
    '[Me pesé]: {74 kg}': '[몸무게 쟀어요]: {74 kg}',
    '[Abre] el {recetario}': '{레시피 북} [열어줘]',
    '[Abre] la {lista del súper}': '{장보기 목록} [열어줘]',
    '[Abre] el {diario de comidas}': '{식사 일기} [열어줘]',
    '[Abre] las {metas de nutrición}': '{영양 목표} [열어줘]',
    'Inventa una [receta] {ligera con atún}': '{참치로 만드는 가벼운} [레시피] 하나 만들어줘',
    'Arma una [dieta] {alta en proteína}': '{단백질 많은} [식단] 짜줘',
    'Agrega {plátano y avena} a la [lista del súper]': '[장보기 목록]에 {바나나랑 귀리} 추가해줘',
    '[Corrí] {5 km}': '{5 km} [뛰었어요]',
    '[Abre] el {plan de ejercicio}': '{운동 계획} [열어줘]',
    '[Abre] las {metas de ejercicio}': '{운동 목표} [열어줘]',
    '[Muéstrame] cómo se hace el {press banca}': '{벤치프레스} 하는 법 [보여줘]',
    'Registra mi sesión: {crossfit 40 min, intensidad alta}': '오늘 운동 기록해줘: {크로스핏 40분, 고강도}',
    '[Arma una rutina] de {pecho y tríceps} de {45 min}': '{가슴과 삼두} {45분} [루틴 짜줘]',
    '[Dormí] {7 horas}, calidad {4/5}': '{7시간} [잤어요}, 수면의 질 {4/5}',
    '[Abre] el {despertador}': '{알람} [열어줘]',
    '[Abre] {mi sueño}': '{내 수면} [열어줘]',
    '{Me acosté a las 23, desperté a las 7 y me levanté 2 veces}': '{23시에 누웠고 7시에 일어났는데 중간에 두 번 깼어요}',
    '[Recuerdo]: {tarde de juegos con mi hermana}': '[추억]: {동생이랑 보드게임 하던 저녁}',
    '[Abre] el {calendario de ánimo}': '{기분 달력} [열어줘]',
    'Anota esta anécdota: {hoy celebramos el cumple de mamá}': '이 추억 적어줘: {오늘 엄마 생일을 축하했어요}',
    '[Cobré] {8000} de {la quincena}': '{보름치 급여} {8000} [받았어요]',
    '[Abre] los {gastos fijos}': '{고정 지출} [열어줘]',
    '[Abre] las {metas de ahorro}': '{저축 목표} [열어줘]',
    '{Pagué 250 de luz y 180 de agua}': '{전기료 250, 수도료 180 냈어요}',
    '[Abre] el {formulario}': '{공식집} [열어줘]',
    '[Resolver ecuación]': '[방정식 풀기]',
    '[Convertir unidades]': '[단위 변환]',
    '[Sistema de ecuaciones]': '[연립방정식]',
    '[Convertir a binario]': '[2진수로 변환]',
    '[Propina]': '[팁 계산]',
    '[Regla de tres]': '[비례식]',
    '[Estudié] {historia romana} {30 min}': '{로마사} {30분} [공부했어요]',
    '[Abre] la {sesión de estudio}': '{공부 세션} [열어줘]',
    '[Abre] el {resumen de estudio}': '{공부 요약} [열어줘]',
    'Apunta que aprendí: {los ríos de Europa}': '오늘 배운 거 적어줘: {유럽의 강들}',
    '[Abre] la {mesa de juegos}': '{게임 테이블} [열어줘]',
    'Apunta {la serie Dark} como pendiente': '{드라마 다크} 볼 목록에 적어줘',
    '[Abre] el {mapamundi}': '{세계 지도} [열어줘]',
    '[Abre] {por conocer}': '{가보고 싶은 곳} [열어줘]',
    '[Abre] la {bitácora de viajes}': '{여행 일지} [열어줘]',
    '[Medité] {10 min}': '{10분} [명상했어요]',
    '[@]{jardin} [agradezco] {mi salud, mi familia y el café}': '[@]{jardin} {내 건강, 가족, 그리고 커피}에 [감사해요]',
    '[Abre] el {resumen del garage}': '{차고 요약} [열어줘]',
    '[Abre] {mis vehículos}': '{내 차량} [열어줘]',
    '[Abre] las {efemérides}': '{오늘의 역사} [열어줘]',
    '[Abre] {mis hobbies}': '{내 취미} [열어줘]',
    '[Abre] mis {mapas mentales}': '내 {마인드맵} [열어줘]',
    '[Abre] los {mapas conceptuales}': '{개념 지도} [열어줘]',
    '[Dibuja un diagrama de flujo] de {cómo hacer pan}': '{빵 만드는 법} [순서도 그려줘]',
    '[Haz un esquema] de {lo que me acabas de explicar}': '{방금 설명해준 내용} [도식으로 정리해줘]',
    '[Agenda] una {junta con el cliente} el {martes a las 10}': '{화요일 10시}에 {고객 미팅} [잡아줘]',
    '[Apunta el pendiente] {mandar la cotización}': '{견적서 보내기} [할 일로 적어줘]',
    '[Abre] mis {pendientes}': '내 {할 일} [열어줘]',
    '[Abre] mis {citas médicas}': '내 {병원 예약} [열어줘]',
    '[Abre] el {progreso de idiomas}': '{언어 학습 진행률} [열어줘]',
    '[Construye] un {huerto}': '{텃밭} [만들어줘]',
    '[Pon] una {pista de carreras}': '{레이싱 트랙} [놔줘]',
    '[Traza] las {vías del tren}': '{기찻길} [깔아줘]',
    '[Construye] una {montaña rusa}': '{롤러코스터} [만들어줘]',
    '[Pon] la {meta} de la pista': '트랙 {결승선} [놔줘]',
    '[Corre una carrera] de {3 vueltas}': '{3바퀴} [경주하자]',
    '[Quiero montar] la {montaña rusa}': '{롤러코스터} [타고 싶어요]',
    '[Llévame] a la {meta}': '{결승선}으로 [데려가줘]',
    '[Pon] una {cancha de fútbol}': '{축구장} [놔줘]',
    '[Crea] una {cancha de básquet}': '{농구 코트}를 [만들어 주세요]',
    '[Pon] un {campo de béisbol}': '{야구장}을 [놓아 주세요]',
    '[Abre] la {agenda de hoy}': '{오늘 할 일}을 [열어 주세요]',
    '[Abre] {mi semana}': '{이번 주}를 [열어 주세요]',
    '[Crea una rutina] de mañana: {agua, estiramiento y gratitud} a las {7:00}': '아침 [루틴을 만들어 주세요]: {7:00}에 {물, 스트레칭, 감사}',
    '[Crea una rutina] de {lunes y miércoles}: {correr 20 min}': '{월요일과 수요일} [루틴을 만들어 주세요]: {20분 달리기}',
    '[Gira el último objeto]': '[마지막 오브젝트를 돌려 주세요]',
    '[Quita el último objeto]': '[마지막 오브젝트를 지워 주세요]',
    '[Genera en 3D] {un dragón morado}': '{보라색 용}을 [3D로 만들어 주세요]',
    '[Crea una imagen] de {un atardecer en la playa}': '{바닷가 노을} [이미지를 만들어 주세요]',
    '[Bájame]': '[내려 주세요]',
    '[Vista en] {primera persona}': '{1인칭} [시점]으로 해 주세요',
    '[Quita el tema]': '[테마를 없애 주세요]',
    '[Volumen] al {40%}': '[볼륨]을 {40%}로',
    '[Apaga la música]': '[음악 꺼 주세요]',
    '[Abre] mi {resumen semanal}': '{주간 요약}을 [열어 주세요]',
    '[Abre] mi {resumen mensual}': '{월간 요약}을 [열어 주세요]',
    '[Transparencia] al {40%}': '[투명도]를 {40%}로',
    '[Apaga los efectos]': '[이펙트를 꺼 주세요]',
    '[Avísame de mis metas] a las {21:00}': '{21:00}에 [목표를 알려주세요]',
    '[Apaga los avisos]': '[알림 꺼주세요]',
    '[Descarga un respaldo] de mis datos': '내 데이터 [백업을 내려받아 주세요]',
    '[Vuelve a ver la bienvenida]': '[환영 화면 다시 보여주세요]',
    '[Abre las configuraciones]': '[설정 열어주세요]',
    '[Recuerda que] {soy vegetariano}': '{저는 채식해요}라고 [기억해 주세요]',
    '[Cómo funciona] la {rueda de herramientas}': '{도구 휠}은 [어떻게 쓰나요]',
    '[@]{cocina} {ensalada de la comida}': '[@]{cocina} {점심 샐러드}',
    '[Abre] {ejemplo.com}': '{ejemplo.com} [열어 줘]',
    '[Busca en internet] {recetas de pan}': '{빵 레시피} [인터넷에서 찾아 줘]',
    '[Historial]': '[기록]',
    '[Sitios]': '[사이트]',
    '[Tiempo en internet]': '[인터넷 사용 시간]',
  },
  atajos: {
    'Caminar (también con las flechas)': '걷기 (방향키도 가능)',
    'Correr (se queda puesto hasta volver a pulsar)': '달리기 (다시 누를 때까지 유지)',
    'Saltar': '점프',
    'Agacharse (mantener pulsado)': '웅크리기 (누르고 있기)',
    'Lo que tengas delante: entrar al cuarto, subirte o bajarte del vehículo, cambiar de nivel': '앞에 있는 것: 방에 들어가기, 탈것에 타거나 내리기, 층 이동하기',
    'Levantar la mano derecha / izquierda': '오른손 / 왼손 들기',
    'Bailar': '춤추기',
    'Mortal': '백덤블링',
    'Abrir la rueda de herramientas': '도구 휠 열기',
    'Abrir el chat y escribir': '채팅 열고 입력하기',
    'Cambiar de vista: isométrica, tercera y primera persona': '시점 전환: 아이소메트릭, 3인칭, 1인칭',
    'Esconder o mostrar el HUD': 'HUD 숨기기 또는 보이기',
    'Cerrar lo que esté abierto': '열려 있는 창 닫기',
    'Conduciendo el OVNI: subir y bajar. En los demás vehículos, Espacio derrapa': 'UFO 조종 중: 상승과 하강. 다른 탈것에서는 스페이스로 드리프트',
  },
  teclas: {
    'Mayús': 'Shift',
    'Espacio': 'Space',
    'Espacio · Mayús': 'Space · Shift',
  },
}
