import type { ManualTraducido } from './manualI18n'

/**
 * Las frases de ejemplo del manual de comandos en zh, indexadas por su
 * texto español de origen (ver `manualI18n.ts`).
 *
 * GENERADO por `npm run traducir:contenido` — no lo edites a mano.
 */
export const MANUAL_ZH: ManualTraducido = {
  frases: {
    '[Corrí] {5 km} en {30 min}': '[我跑了]{5公里}，用时{30分钟}',
    '[@]{cocina} [comí] {una ensalada}': '[@]{cocina} [我吃了]{一份沙拉}',
    '[Abre] el {estudio de audio}': '[打开]{音频工作室}',
    '[Abre] mis {canciones}': '[打开]我的{歌曲}',
    '[Abre] el {mezclador DJ}': '[打开]{DJ混音台}',
    '[Abre] la {galería de arte}': '[打开]{艺术画廊}',
    '[Abre] mis {dibujos}': '[打开]我的{画作}',
    '[Abre] mis {libros}': '[打开]我的{书}',
    '[Abre] el {estudio de escritura}': '[打开]{写作工作室}',
    '[Escribe un cuento] sobre {un faro en invierno} y [guárdalo en mis libros]': '[写一篇短篇故事]，关于{冬天的灯塔}，并[保存到我的书里]',
    '[Guarda en mis libros] este texto: {Querido diario, hoy…}': '[把这段文字保存到我的书里]：{亲爱的日记，今天…}',
    '[Abre] el {editor de video}': '[打开]{视频编辑器}',
    '[Abre] mis {videos}': '[打开]我的{视频}',
    '[Abre] la {animación 3D}': '[打开]{3D动画}',
    "[Abre] {mis archivos}": "[打开]{我的文件}",
    "[Abre] los {archivos recientes}": "[打开]{最近的文件}",
    "[Abre] los {archivos del studio}": "[打开]{Studio 的文件}",
    "[Abre] la {papelera}": "[打开]{回收站}",
    "[Abre] los {archivos destacados}": "[打开]{加星标的文件}",
    '[Tomé] {2 vasos} de [agua]': '[我喝了]{2杯}[水]',
    '[Me pesé]: {74 kg}': '[我称了体重]：{74公斤}',
    '[Abre] el {recetario}': '[打开]{食谱本}',
    '[Abre] la {lista del súper}': '[打开]{购物清单}',
    '[Abre] el {diario de comidas}': '[打开]{饮食日记}',
    '[Abre] las {metas de nutrición}': '[打开]{营养目标}',
    'Inventa una [receta] {ligera con atún}': '想一道{清淡的金枪鱼}[菜谱]',
    'Arma una [dieta] {alta en proteína}': '帮我配一份{高蛋白}的[食谱计划]',
    'Agrega {plátano y avena} a la [lista del súper]': '把{香蕉和燕麦}加到[购物清单]',
    '[Corrí] {5 km}': '[我跑了]{5公里}',
    '[Abre] el {plan de ejercicio}': '[打开]{运动计划}',
    '[Abre] las {metas de ejercicio}': '[打开]{运动目标}',
    '[Muéstrame] cómo se hace el {press banca}': '[教教我]{卧推}怎么做',
    'Registra mi sesión: {crossfit 40 min, intensidad alta}': '记一下我的训练：{crossfit 40分钟，强度高}',
    '[Arma una rutina] de {pecho y tríceps} de {45 min}': '[安排一套]{胸和三头}的日常安排，{45分钟}',
    '[Dormí] {7 horas}, calidad {4/5}': '[我睡了]{7小时}，质量{4/5}',
    '[Abre] el {despertador}': '[打开]{闹钟}',
    '[Abre] {mi sueño}': '[打开]{我的睡眠}',
    '{Me acosté a las 23, desperté a las 7 y me levanté 2 veces}': '{我23点上床，7点醒，中间起来了2次}',
    '[Recuerdo]: {tarde de juegos con mi hermana}': '[回忆]：{和妹妹玩了一下午桌游}',
    '[Abre] el {calendario de ánimo}': '[打开]{心情日历}',
    'Anota esta anécdota: {hoy celebramos el cumple de mamá}': '记下这段回忆：{今天给妈妈过生日}',
    '[Cobré] {8000} de {la quincena}': '[我收到]{这半个月}的{8000}',
    '[Abre] los {gastos fijos}': '[打开]{固定支出}',
    '[Abre] las {metas de ahorro}': '[打开]{储蓄目标}',
    '{Pagué 250 de luz y 180 de agua}': '{我交了250电费和180水费}',
    '[Abre] el {formulario}': '[打开]{公式手册}',
    '[Resolver ecuación]': '[解方程]',
    '[Convertir unidades]': '[单位换算]',
    '[Sistema de ecuaciones]': '[方程组]',
    '[Convertir a binario]': '[转成二进制]',
    '[Propina]': '[小费]',
    '[Regla de tres]': '[三数法]',
    '[Estudié] {historia romana} {30 min}': '[我学了]{罗马史}{30分钟}',
    '[Abre] la {sesión de estudio}': '[打开]{学习时段}',
    '[Abre] el {resumen de estudio}': '[打开]{学习小结}',
    'Apunta que aprendí: {los ríos de Europa}': '记一下我学到的：{欧洲的河流}',
    '[Abre] la {mesa de juegos}': '[打开]{游戏桌}',
    'Apunta {la serie Dark} como pendiente': '把{剧集《暗黑》}记成待看',
    '[Abre] el {mapamundi}': '[打开]{世界地图}',
    '[Abre] {por conocer}': '[打开]{想去的地方}',
    '[Abre] la {bitácora de viajes}': '[打开]{旅行日志}',
    '[Medité] {10 min}': '[我冥想了]{10分钟}',
    '[@]{jardin} [agradezco] {mi salud, mi familia y el café}': '[@]{jardin} [我感谢]{我的健康、我的家人和咖啡}',
    '[Abre] el {resumen del garage}': '[打开]{车库概览}',
    '[Abre] {mis vehículos}': '[打开]{我的车辆}',
    '[Abre] las {efemérides}': '[打开]{历史上的今天}',
    '[Abre] {mis hobbies}': '[打开]{我的爱好}',
    '[Abre] mis {mapas mentales}': '[打开]我的{思维导图}',
    '[Abre] los {mapas conceptuales}': '[打开]{概念图}',
    '[Dibuja un diagrama de flujo] de {cómo hacer pan}': '[画一张流程图]，讲{怎么做面包}',
    '[Haz un esquema] de {lo que me acabas de explicar}': '[做一张图]，讲{你刚才给我讲的内容}',
    '[Agenda] una {junta con el cliente} el {martes a las 10}': '[安排]一个{和客户的会}，{周二十点}',
    '[Apunta el pendiente] {mandar la cotización}': '[记一条待办]：{把报价发出去}',
    '[Abre] mis {pendientes}': '[打开]我的{待办}',
    '[Abre] mis {citas médicas}': '[打开]我的{就医预约}',
    '[Abre] el {progreso de idiomas}': '[打开]{语言进度}',
    '[Construye] un {huerto}': '[建]一个{菜园}',
    '[Pon] una {pista de carreras}': '[放]一条{赛道}',
    '[Traza] las {vías del tren}': '[铺]{火车轨道}',
    '[Construye] una {montaña rusa}': '[建]一座{过山车}',
    '[Pon] la {meta} de la pista': '[放]赛道的{终点线}',
    '[Corre una carrera] de {3 vueltas}': '[跑一场]{3圈}的[比赛]',
    '[Quiero montar] la {montaña rusa}': '[我想坐]{过山车}',
    '[Llévame] a la {meta}': '[带我去]{终点线}',
    '[Juguemos paintball] {2v2}': '[我们来玩彩弹]{2v2}',
    '[Reta] a {Luna} a un paintball {1v1}': '[约]{Luna}打一场{1v1}彩弹',
    '[Pon] una {cancha de fútbol}': '[放]一个{足球场}',
    '[Crea] una {cancha de básquet}': '[建一个]{篮球场}',
    '[Pon] un {campo de béisbol}': '[放一个]{棒球场}',
    '[Abre] la {agenda de hoy}': '[打开]{今天的日程}',
    '[Abre] {mi semana}': '[打开]{我的一周}',
    '[Crea una rutina] de mañana: {agua, estiramiento y gratitud} a las {7:00}': '[创建一个早晨的日常安排]：{7:00}做{喝水、拉伸和感恩}',
    '[Crea una rutina] de {lunes y miércoles}: {correr 20 min}': '[创建一个日常安排]：{周一和周三}{跑步20分钟}',
    '[Gira el último objeto]': '[旋转最后一个物件]',
    '[Quita el último objeto]': '[删掉最后一个物件]',
    '[Genera en 3D] {un dragón morado}': '[用3D生成]{一条紫色的龙}',
    '[Crea una imagen] de {un atardecer en la playa}': '[生成一张图]：{海边的日落}',
    '[Bájame]': '[让我下来]',
    '[Vista en] {primera persona}': '{第一人称}[视角]',
    '[Quita el tema]': '[去掉主题]',
    '[Volumen] al {40%}': '[音量]调到{40%}',
    '[Apaga la música]': '[关掉音乐]',
    '[Abre] mi {resumen semanal}': '[打开]我的{每周小结}',
    '[Abre] mi {resumen mensual}': '[打开]我的{每月小结}',
    '[Transparencia] al {40%}': '[透明度]调到{40%}',
    '[Apaga los efectos]': '[关掉特效]',
    '[Avísame de mis metas] a las {21:00}': '{21:00}[提醒我我的目标]',
    '[Apaga los avisos]': '[关掉通知]',
    '[Descarga un respaldo] de mis datos': '我的数据，[下载一份备份]',
    '[Vuelve a ver la bienvenida]': '[再看一次欢迎菜单]',
    '[Abre las configuraciones]': '[打开设置]',
    '[Recuerda que] {soy vegetariano}': '[记住]{我吃素}',
    '[@]{cocina} {ensalada de la comida}': '[@]{cocina} {午餐吃沙拉}',
    '[Cómo funciona] la {rueda de herramientas}': '{工具轮盘}[怎么用]',
    '[Abre] {ejemplo.com}': '[打开] {ejemplo.com}',
    '[Busca en internet] {recetas de pan}': '[上网搜] {面包食谱}',
    '[Historial]': '[浏览记录]',
    '[Sitios]': '[网站]',
    '[Tiempo en internet]': '[上网时长]',
    '[Cómo llegar]': '[怎么走]',
    '[Amigos]': '[朋友]',
    '[Comí] {pollo con arroz} en la {cena}': '{晚饭}[我吃了]{鸡肉和米饭}',
    '[Abre] la {dieta}': '[打开]{饮食方案}',
    '[Entrené] {pierna} {45 min}': '[我练了]{45分钟}的{腿部}',
    '[Abre] {fuerza}': '[打开]{力量}',
    '[Abre] {cardio}': '[打开]{耐力}',
    '[Abre] {flexibilidad}': '[打开]{柔韧性}',
    '[Haz] una {sentadilla}': '[做]一个{深蹲}',
    '[Arma una rutina] de {estiramientos} para {la espalda baja}': '[安排一套]{拉伸}的日常安排，针对{下背部}',
    '[Abre] mis {anécdotas}': '[打开]我的{回忆}',
    '[Gasté] {500} en {el súper}': '我在{超市}[花了]{500}',
    '[Abre] el {balance}': '[打开]{现金流}',
    '[Abre] los {movimientos}': '[打开]{收支明细}',
    '[Abre] las {divisas}': '[打开]{外汇}',
    '[Abre] las {criptomonedas}': '[打开]{加密货币}',
    '[Abre] las {materias primas}': '[打开]{大宗商品}',
    '[Abre] la {calculadora}': '[打开]{计算器}',
    '[Abre] el {graficador}': '[打开]{图形}',
    '[Abre] las {hojas de cálculo}': '[打开]{电子表格}',
    '[Abre] las {matrices}': '[打开]{矩阵}',
    '[Abre] las {charlas}': '[打开]{聊天}',
    '[Abre] la {enciclopedia}': '[打开]{百科全书}',
    '[Vi la película] {Dune}': '[我看了电影]{《沙丘》}',
    '[Jugué] {ajedrez} con mi hermano': '我和弟弟[下了一盘]{国际象棋}',
    '[Abre] el {archivo}': '[打开]{档案}',
    '[Quiero jugar] la {viborita}': '[我想玩]{贪吃蛇}',
    '[Juega] {tetris}': '[玩]{俄罗斯方块}',
    '[Juega] una partida de {ajedrez}': '[来一盘]{国际象棋}',
    '[Abre] las {rutas}': '[打开]{路线}',
    '[Visité] {Oaxaca}': '[我去过]{成都}',
    'Quiero conocer {Japón}': '我想去{日本}看看',
    '[Visité] {Roma}: {la fontana de noche es mágica}': '[我去过]{罗马}：{特雷维喷泉夜晚太梦幻了}',
    '[Abre] la {meditación}': '[打开]{冥想}',
    '[Abre] la {respiración}': '[打开]{呼吸}',
    '[Abre] los {agradecimientos}': '[打开]{感恩}',
    '[Abre] los {titulares}': '[打开]{今日头条}',
    'Avancé en mi [proyecto] de {acuarela} {40 min}': '我在{水彩画}[项目]上花了{40分钟}',
    'Practiqué {guitarra} {25 min}': '我练了{25分钟}的{吉他}',
    '[Hazme un mapa mental] de {la fotosíntesis}': '[给我做一张思维导图]，主题是{光合作用}',
    '[Compara] {café} y {té} en un mapa': '[对比]{咖啡}和{茶}，做成一张导图',
    '[Tengo cita] con el {dentista} el {14 a las 5}': '[我约了]{牙医}，{14号下午5点}',
    '[Recuérdame] tomar {ibuprofeno} a las {8 y a las 20}': '[提醒我]在{8点和20点}吃{布洛芬}',
    '[Guarda el contacto] de {Ana}: {5512345678}, cumple el {3 de mayo}': '[保存联系人]{王芳}：{13812345678}，生日{5月3日}',
    '[Abre] mis {contactos}': '[打开]我的{联系人}',
    '[Vocab] {inglés}: {dog} = {perro}': '[词汇]{英语}：{dog} = {狗}',
    '[Abre] el {tutor}': '[打开]{会话老师}',
    '[Abre] el {repaso}': '[打开]{复习}',
    '[Abre] el {temario}': '[打开]{大纲}',
    '[Repasé] {francés} {15 min}': '[我复习了]{15分钟}的{法语}',
    'Aprendí en {alemán}: {Hund} = {perro}': '我学了{德语}单词：{Hund} = {狗}',
    '[Quiero sembrar] {zanahorias}': '[我想种]{胡萝卜}',
    '[Siembra] {maíz} en el huerto': '在菜园里[种]{玉米}',
    '[Pon] un {aspersor} en el huerto': '在菜园里[放]一个{喷灌器}',
    '[Riega] el {huerto}': '给{菜园}[浇水]',
    '[Cosecha] el {huerto}': '[收获]{菜园}',
    '[Llévame] al {huerto}': '[带我去]{菜园}',
    '[Haz] un {corral}': '[建]一个{围栏}',
    '[Pon] {vacas} en la granja': '在农场里[放]{奶牛}',
    '[Alimenta] a los {animales}': '给{动物}[喂食]',
    '[Mima] a los {animales}': '[抚摸]{动物}',
    '[Cura] a los {animales}': '[治疗]{动物}',
    '[Limpia] los {corrales}': '[清洁]{围栏}',
    '[Llévame] a la {granja}': '[带我去]{农场}',
    '[Borra] la {pista}': '[删掉]{赛道}',
    '[Hagamos una carrera] {contra} un asistente': '[我们来比赛吧]，{对战}一位助手',
    '[Corre una carrera] {fácil} de {5 vueltas}': '[跑一场]{简单}难度、{5圈}的比赛',
    '[Quiero montar] el {tren}': '[我想坐]{火车}',
    '[Juguemos] {paintball}': '[我们来玩]{彩弹}',
    '[Paintball] campal en {difícil}': '[彩弹]大乱斗，{困难}模式',
    '[Sal] del {paintball}': '[退出]{彩弹}',
    '[Pon] una {cancha de tenis} {azul}': '[放]一个{蓝色}的{网球场}',
    '[Llévame] a la {cancha}': '[带我去]{球场}',
    '[Abre] el {cronograma}': '[打开]{日程}',
    '[Enséñame] las {rutinas}': '[给我看]{日常安排}',
    '[Crea un cuarto] llamado {Estudio}': '[创建一个房间]，名叫{学习室}',
    '[Renombra] la {cocina} a {Oficina}': '把{厨房}[重命名]为{办公室}',
    '[Cambia el ícono] de la {cocina} a {🍳}': '把{厨房}的图标[改成]{🍳}',
    '[Pon] la {cocina} en categoría {cuerpo}': '把{厨房}[放进]{身体}分类',
    '[Agrega] la {biblioteca} al mapa': '把{图书馆}[加到]地图上',
    '[Elimina] la {cocina}': '[删除]{厨房}',
    '[Abre] la {cocina}': '[打开]{厨房}',
    '[Pinta] la {cocina} de {azul}': '把{厨房}[涂成]{蓝色}',
    '[Piso] de la {cocina} de {madera}': '{厨房}的[地板]换成{木地板}',
    '[Piso] de la {cocina} {rojo}': '{厨房}的[地板]换成{红色}',
    '[Techo] de la {cocina} de {tejas rojas}': '{厨房}的[屋顶]换成{红瓦}',
    '[Techo a dos aguas] en la {cocina}': '给{厨房}装[双坡屋顶]',
    '[Haz] la {cocina} {redonda}': '把{厨房}[改成]{圆形}',
    '[Agranda] la {cocina}': '[扩大]{厨房}',
    '[Encoge] la {cocina}': '[缩小]{厨房}',
    '[Mueve] la {cocina} a la {derecha}': '[移动]{厨房}到{右}边',
    '[Abre el muro] {norte} de la {cocina}': '[打通]{厨房}的{北}墙',
    '[Pon una puerta] {corredera} en el muro {sur} de la {cocina}': '在{厨房}的{南}墙上[装]{推拉门}',
    '[Pon] {ladrillo} en el muro {este} de la {cocina}': '把{厨房}的{东}墙[换成]{砖墙}',
    '[Haz más grueso] el muro {norte} de la {cocina}': '[加厚]{厨房}的{北}墙',
    '[Apila] la {sala} sobre la {cocina}': '把{客厅}[叠放]在{厨房}上面',
    '[Agranda el mapa] hacia el {este}': '向{东}[扩大地图]',
    '[Crea] una {lámpara}': '[创建]一盏{台灯}',
    '[Pinta el último objeto] de {rojo}': '[把最后一个物件涂成]{红色}',
    '[Haz el último objeto] más {grande}': '[让最后一个物件变得更]{大}',
    '[Agrupa los objetos] de la {cocina}': '[编组]{厨房}里的物件',
    '[Genera en 3D] {una fuente de piedra} estilo {minimalista}': '[用3D生成]{一座石头喷泉}，{极简}风格',
    '[Ponme] {sombrero} {rojo}': '[给我戴上]{红色}的{帽子}',
    '[Quítame] los {lentes}': '[帮我摘掉]{眼镜}',
    '[Pinta el torso] del [avatar] de {verde}': '把[虚拟形象]的躯干[涂成]{绿色}',
    '[Haz el avatar] más {grande}': '[让虚拟形象变得更]{大}',
    '[Móntame] en la {bici}': '[让我骑上]{自行车}',
    '[Quiero conducir] el {auto}': '[我想开]{汽车}',
    '[Vista] {isométrica}': '{等距}[视角]',
    '[Cambia el tema] a {navidad}': '[把主题换成]{圣诞}',
    '[Fondo] {nieve}': '[背景]换成{雪景}',
    '[Pon música] {relajante}': '[放点音乐]，要{舒缓}的',
    '[Música] {chiptune}': '[音乐]换成{芯片音乐}',
    '[Modo] {oscuro}': '[模式]切换到{深色}',
    '[Apariencia] {transparente}': '[外观]切换到{透明}',
    '[Cambia el idioma] a {inglés}': '[把语言切换成]{英语}',
    '[Tema de interfaz] {neón}': '[界面主题]换成{霓虹}',
    '[Tipografía] {serif}': '[字体]换成{衬线}',
    '[Estilo de la interfaz] {pixel}': '[界面风格]换成{像素}',
    '[Pon iconos] {profesionales}': '[把图标换成]{专业}样式',
    '[Estilo] {cómic}': '[风格]换成{漫画}',
    '[Avísame] de mis {rutinas}': '[提醒我]{日常安排}',
    '[Abre] mi {cuenta}': '[打开]我的{账户}',
    '[Cómo funciona] la {cocina}': '{厨房}[怎么用]',
    '[Cómo funciona] el {editor}': '{编辑器}[怎么用]',
    '[Cómo funciona] el {chat}': '{聊天}[怎么用]',
    '[Qué hace] el {inventario}': '{物品栏}[是做什么的]',
    '[Para qué sirve] la {cámara}': '{镜头}[有什么用]',
    '[Tutorial de] {ejercicio}': '{健身房}[教程]',
    '[Tutorial de] la {biblioteca}': '{图书馆}[教程]',
    '[Tutorial] {general}': '{整体}[教程]',
  },
  atajos: {
    'Caminar (también con las flechas)': '走路（方向键也可以）',
    'Correr (se queda puesto hasta volver a pulsar)': '跑步（一直保持，再按一次取消）',
    'Saltar': '跳跃',
    'Agacharse (mantener pulsado)': '蹲下（按住）',
    'Lo que tengas delante: entrar al cuarto, subirte o bajarte del vehículo, cambiar de nivel': '跟眼前的东西互动：进房间、上下载具、换楼层',
    'Levantar la mano derecha / izquierda': '举右手／左手',
    'Bailar': '跳舞',
    'Mortal': '后空翻',
    'Abrir la rueda de herramientas': '打开工具轮盘',
    'Abrir el chat y escribir': '打开聊天并输入',
    'Cambiar de vista: isométrica, tercera y primera persona': '切换视角：等距、第三人称和第一人称',
    'Esconder o mostrar el HUD': '隐藏或显示 HUD',
    'Cerrar lo que esté abierto': '关掉当前打开的东西',
    'Conduciendo el OVNI: subir y bajar. En los demás vehículos, Espacio derrapa': '开飞碟时：上升和下降。其他载具里，空格键是漂移',
  },
  teclas: {
    'Mayús': 'Shift',
    'Espacio': '空格',
    'Espacio · Mayús': '空格 · Shift',
  },
}
