import type { ManualTraducido } from './manualI18n'

/**
 * Las frases de ejemplo del manual de comandos en fr, indexadas por su
 * texto español de origen (ver `manualI18n.ts`).
 *
 * GENERADO por `npm run traducir:contenido` — no lo edites a mano.
 */
export const MANUAL_FR: ManualTraducido = {
  frases: {
    '[Tomé] {2 vasos} de [agua]': '[J\'ai bu] {2 verres} d\'[eau]',
    '[Me pesé]: {74 kg}': '[Je me suis pesé] : {74 kg}',
    '[Abre] el {recetario}': '[Ouvre] le {livre de recettes}',
    '[Abre] la {lista del súper}': '[Ouvre] la {liste de courses}',
    '[Abre] el {diario de comidas}': '[Ouvre] le {journal des repas}',
    '[Abre] las {metas de nutrición}': '[Ouvre] les {objectifs de nutrition}',
    'Inventa una [receta] {ligera con atún}': 'Invente une [recette] {légère, au thon}',
    'Arma una [dieta] {alta en proteína}': 'Monte un [régime] {riche en protéines}',
    'Agrega {plátano y avena} a la [lista del súper]': 'Ajoute {des bananes et des flocons d\'avoine} à la [liste de courses]',
    '[Corrí] {5 km}': '[J\'ai couru] {5 km}',
    '[Abre] el {plan de ejercicio}': '[Ouvre] le {plan d\'entraînement}',
    '[Abre] {cardio}': '[Ouvre] {cardio}',
    '[Abre] las {metas de ejercicio}': '[Ouvre] les {objectifs d\'entraînement}',
    '[Muéstrame] cómo se hace el {press banca}': '[Montre-moi] comment faire le {développé couché}',
    '[Haz] una {sentadilla}': '[Fais] un {squat}',
    'Registra mi sesión: {crossfit 40 min, intensidad alta}': 'Enregistre ma séance : {crossfit 40 min, intensité élevée}',
    '[Arma una rutina] de {pecho y tríceps} de {45 min}': '[Monte une routine] {pectoraux et triceps} de {45 min}',
    '[Dormí] {7 horas}, calidad {4/5}': '[J\'ai dormi] {7 heures}, qualité {4/5}',
    '[Abre] el {despertador}': '[Ouvre] le {réveil}',
    '[Abre] {mi sueño}': '[Ouvre] {mon sommeil}',
    '{Me acosté a las 23, desperté a las 7 y me levanté 2 veces}': '{Couché à 23 h, réveillé à 7 h, levé 2 fois}',
    '[Recuerdo]: {tarde de juegos con mi hermana}': '[Souvenir] : {après-midi jeux avec ma sœur}',
    '[Abre] el {calendario de ánimo}': '[Ouvre] le {calendrier d\'humeur}',
    'Anota esta anécdota: {hoy celebramos el cumple de mamá}': 'Note cette anecdote : {aujourd\'hui on a fêté l\'anniversaire de maman}',
    '[Cobré] {8000} de {la quincena}': '[J\'ai touché] {8000} de {la quinzaine}',
    '[Abre] los {gastos fijos}': '[Ouvre] les {dépenses fixes}',
    '[Abre] las {metas de ahorro}': '[Ouvre] les {objectifs d\'épargne}',
    '{Pagué 250 de luz y 180 de agua}': '{J\'ai payé 250 d\'électricité et 180 d\'eau}',
    '[Resolver ecuación]': '[Résoudre une équation]',
    '[Convertir unidades]': '[Convertir des unités]',
    '[Abre] las {matrices}': '[Ouvre] les {matrices}',
    '[Sistema de ecuaciones]': '[Système d\'équations]',
    '[Convertir a binario]': '[Convertir en binaire]',
    '[Propina]': '[Pourboire]',
    '[Regla de tres]': '[Règle de trois]',
    '[Estudié] {historia romana} {30 min}': '[J\'ai étudié] {l\'histoire romaine} {30 min}',
    '[Abre] la {sesión de estudio}': '[Ouvre] la {séance d\'étude}',
    '[Abre] el {resumen de estudio}': '[Ouvre] le {résumé d\'étude}',
    'Apunta que aprendí: {los ríos de Europa}': 'Note ce que j\'ai appris : {les fleuves d\'Europe}',
    '[Vi la película] {Dune}': '[J\'ai vu le film] {Dune}',
    '[Abre] la {mesa de juegos}': '[Ouvre] la {table de jeux}',
    '[Juega] {tetris}': '[Joue] à {tetris}',
    'Apunta {la serie Dark} como pendiente': 'Note {la série Dark} comme à voir',
    '[Abre] {por conocer}': '[Ouvre] {à découvrir}',
    '[Abre] la {bitácora de viajes}': '[Ouvre] le {journal de bord de voyage}',
    '[Visité] {Oaxaca}': '[J\'ai visité] {Oaxaca}',
    '[Abre] el {mapamundi}': '[Ouvre] le {planisphère}',
    '[Visité] {Roma}: {la fontana de noche es mágica}': '[J’ai visité] {Rome} : {la fontaine de nuit, c’est magique}',
    '[Medité] {10 min}': '[J’ai médité] {10 min}',
    '[@]{jardin} [agradezco] {mi salud, mi familia y el café}': '[@]{jardin} [je remercie pour] {ma santé, ma famille et le café}',
    '[Abre] el {resumen del garage}': '[Ouvre] le {résumé du garage}',
    '[Abre] {mis vehículos}': '[Ouvre] {mes véhicules}',
    '[Abre] las {efemérides}': '[Ouvre] les {éphémérides}',
    '[Abre] {mis hobbies}': '[Ouvre] {mes loisirs}',
    '[Abre] mis {mapas mentales}': '[Ouvre] mes {cartes mentales}',
    '[Abre] los {mapas conceptuales}': '[Ouvre] les {cartes conceptuelles}',
    '[Dibuja un diagrama de flujo] de {cómo hacer pan}': '[Dessine un organigramme] de {comment faire du pain}',
    '[Haz un esquema] de {lo que me acabas de explicar}': '[Fais un schéma] de {ce que tu viens de m’expliquer}',
    '[Agenda] una {junta con el cliente} el {martes a las 10}': '[Planifie] une {réunion avec le client} {mardi à 10 h}',
    '[Apunta el pendiente] {mandar la cotización}': '[Note la tâche] {envoyer le devis}',
    '[Abre] mis {pendientes}': '[Ouvre] mes {tâches}',
    '[Abre] mis {citas médicas}': '[Ouvre] mes {rendez-vous médicaux}',
    '[Abre] mis {contactos}': '[Ouvre] mes {contacts}',
    '[Abre] el {progreso de idiomas}': '[Ouvre] les {progrès en langues}',
    '[Pon] una {pista de carreras}': '[Mets] une {piste de course}',
    '[Traza] las {vías del tren}': '[Trace] les {rails du train}',
    '[Construye] una {montaña rusa}': '[Construis] des {montagnes russes}',
    '[Pon] la {meta} de la pista': '[Place] la {ligne d’arrivée} de la piste',
    '[Corre una carrera] de {3 vueltas}': '[Fais une course] de {3 tours}',
    '[Quiero montar] el {tren}': '[Je veux monter] dans le {train}',
    '[Quiero montar] la {montaña rusa}': '[Je veux monter] dans les {montagnes russes}',
    '[Llévame] a la {meta}': '[Emmène-moi] à la {ligne d’arrivée}',
    '[Juguemos] {paintball}': '[Jouons] au {paintball}',
    '[Sal] del {paintball}': '[Quitte] le {paintball}',
    '[Pon] una {cancha de fútbol}': '[Mets] un {terrain de foot}',
    '[Juguemos paintball] {2v2}': '[Jouons au paintball] en {2v2}',
    '[Reta] a {Luna} a un paintball {1v1}': '[Défie] {Luna} à un paintball {1v1}',
    '[Crea] una {cancha de básquet}': '[Crée] un {terrain de basket}',
    '[Pon] un {campo de béisbol}': '[Mets] un {terrain de baseball}',
    '[Abre] la {agenda de hoy}': '[Ouvre] l\'{agenda du jour}',
    '[Abre] {mi semana}': '[Ouvre] {ma semaine}',
    '[Crea una rutina] de mañana: {agua, estiramiento y gratitud} a las {7:00}': '[Crée une routine] du matin : {eau, étirements et gratitude} à {7:00}',
    '[Crea una rutina] de {lunes y miércoles}: {correr 20 min}': '[Crée une routine] le {lundi et le mercredi} : {courir 20 min}',
    '[Enséñame] las {rutinas}': '[Montre-moi] les {routines}',
    '[Crea un cuarto] llamado {Estudio}': '[Crée une pièce] qui s\'appelle {Studio}',
    '[Gira el último objeto]': '[Fais tourner le dernier objet]',
    '[Quita el último objeto]': '[Enlève le dernier objet]',
    '[Genera en 3D] {un dragón morado}': '[Génère en 3D] {un dragon violet}',
    '[Crea una imagen] de {un atardecer en la playa}': '[Crée une image] d\'{un coucher de soleil sur la plage}',
    '[Bájame]': '[Fais-moi descendre]',
    '[Vista en] {primera persona}': '[Vue à la] {première personne}',
    '[Quita el tema]': '[Enlève le thème]',
    '[Música] {chiptune}': '[Musique] {chiptune}',
    '[Volumen] al {40%}': '[Volume] à {40%}',
    '[Apaga la música]': '[Coupe la musique]',
    '[Abre] mi {resumen semanal}': '[Ouvre] mon {résumé de la semaine}',
    '[Abre] mi {resumen mensual}': '[Ouvre] mon {résumé du mois}',
    '[Tipografía] {serif}': '[Police] {serif}',
    '[Estilo de la interfaz] {pixel}': '[Style de l\'interface] {pixel}',
    '[Transparencia] al {40%}': '[Transparence] à {40%}',
    '[Apaga los efectos]': '[Coupe les effets]',
    '[Avísame] de mis {rutinas}': '[Préviens-moi] de mes {routines}',
    '[Avísame de mis metas] a las {21:00}': '[Rappelle-moi mes objectifs] à {21:00}',
    '[Apaga los avisos]': '[Coupe les notifications]',
    '[Descarga un respaldo] de mis datos': '[Télécharge une sauvegarde] de mes données',
    '[Vuelve a ver la bienvenida]': '[Remontre-moi la bienvenue]',
    '[Abre las configuraciones]': '[Ouvre les réglages]',
    '[Recuerda que] {soy vegetariano}': '[Retiens que] {je suis végétarien}',
    '[Cómo funciona] la {rueda de herramientas}': '[Comment marche] la {roue des outils}',
    '[Cómo funciona] el {chat}': '[Comment marche] le {chat}',
    '[@]{cocina} {ensalada de la comida}': '[@]{cocina} {salade pour le déjeuner}',
  },
  atajos: {
    'Caminar (también con las flechas)': 'Marcher (aussi avec les flèches)',
    'Correr (se queda puesto hasta volver a pulsar)': 'Courir (reste activé jusqu’à ce que tu appuies de nouveau)',
    'Saltar': 'Sauter',
    'Agacharse (mantener pulsado)': 'S’accroupir (maintenir appuyé)',
    'Lo que tengas delante: entrar al cuarto, subirte o bajarte del vehículo, cambiar de nivel': 'Ce que tu as devant toi : entrer dans la pièce, monter ou descendre du véhicule, changer de niveau',
    'Levantar la mano derecha / izquierda': 'Lever la main droite / gauche',
    'Bailar': 'Danser',
    'Mortal': 'Salto arrière',
    'Abrir la rueda de herramientas': 'Ouvrir la roue des outils',
    'Abrir el chat y escribir': 'Ouvrir le chat et écrire',
    'Cambiar de vista: isométrica, tercera y primera persona': 'Changer de vue : isométrique, troisième et première personne',
    'Esconder o mostrar el HUD': 'Masquer ou afficher le HUD',
    'Cerrar lo que esté abierto': 'Fermer ce qui est ouvert',
    'Conduciendo el OVNI: subir y bajar. En los demás vehículos, Espacio derrapa': 'Aux commandes de l’OVNI : monter et descendre. Dans les autres véhicules, Espace fait déraper',
  },
  teclas: {
    'Mayús': 'Maj',
    'Espacio': 'Espace',
    'Espacio · Mayús': 'Espace · Maj',
  },
}
