import type { ManualTraducido } from './manualI18n'

/**
 * Las frases de ejemplo del manual de comandos en hi, indexadas por su
 * texto español de origen (ver `manualI18n.ts`).
 *
 * GENERADO por `npm run traducir:contenido` — no lo edites a mano.
 */
export const MANUAL_HI: ManualTraducido = {
  frases: {
    '[Corrí] {5 km} en {30 min}': '{5 किमी} {30 मिनट} में [दौड़ा]',
    '[@]{cocina} [comí] {una ensalada}': '[@]{cocina} {एक सलाद} [खाया]',
    '[Abre] el {estudio de audio}': '{ऑडियो स्टूडियो} [खोलो]',
    '[Abre] mis {canciones}': 'मेरे {गाने} [खोलो]',
    '[Abre] el {mezclador DJ}': '{DJ मिक्सर} [खोलो]',
    '[Abre] la {galería de arte}': '{आर्ट गैलरी} [खोलो]',
    '[Abre] mis {dibujos}': 'मेरे {चित्र} [खोलो]',
    '[Abre] mis {libros}': 'मेरी {किताबें} [खोलो]',
    '[Abre] el {estudio de escritura}': '{लेखन स्टूडियो} [खोलो]',
    '[Escribe un cuento] sobre {un faro en invierno} y [guárdalo en mis libros]': '{सर्दियों के एक लाइटहाउस} पर [एक छोटी कहानी लिखो] और [मेरी किताबों में सहेजो]',
    '[Guarda en mis libros] este texto: {Querido diario, hoy…}': 'यह पाठ [मेरी किताबों में सहेजो]: {प्यारी डायरी, आज…}',
    '[Abre] el {editor de video}': '{वीडियो संपादक} [खोलो]',
    '[Abre] mis {videos}': 'मेरे {वीडियो} [खोलो]',
    '[Abre] la {animación 3D}': '{3D एनिमेशन} [खोलो]',
    "[Abre] {mis archivos}": "{मेरी फ़ाइलें} [खोलो]",
    "[Abre] los {archivos recientes}": "{हाल की फ़ाइलें} [खोलो]",
    "[Abre] los {archivos del studio}": "{स्टूडियो की फ़ाइलें} [खोलो]",
    "[Abre] la {papelera}": "{ट्रैश} [खोलो]",
    "[Abre] los {archivos destacados}": "{तारांकित फ़ाइलें} [खोलो]",
    '[Tomé] {2 vasos} de [agua]': '[पिया] {2 गिलास} [पानी]',
    '[Me pesé]: {74 kg}': '[वज़न किया]: {74 किलो}',
    '[Abre] el {recetario}': '{रेसिपी बुक} [खोलो]',
    '[Abre] la {lista del súper}': '{सौदे की सूची} [खोलो]',
    '[Abre] el {diario de comidas}': '{खाने की डायरी} [खोलो]',
    '[Abre] las {metas de nutrición}': '{पोषण के लक्ष्य} [खोलो]',
    'Inventa una [receta] {ligera con atún}': 'कोई [रेसिपी] सोचो, {हल्की, टूना वाली}',
    'Arma una [dieta] {alta en proteína}': '{प्रोटीन से भरपूर} [डाइट] बनाओ',
    'Agrega {plátano y avena} a la [lista del súper]': '[सौदे की सूची] में {केला और ओट्स} जोड़ो',
    '[Corrí] {5 km}': '{5 किमी} [दौड़ा]',
    '[Abre] el {plan de ejercicio}': '{कसरत की योजना} [खोलो]',
    '[Abre] las {metas de ejercicio}': '{कसरत के लक्ष्य} [खोलो]',
    '[Muéstrame] cómo se hace el {press banca}': '{बेंच प्रेस} कैसे करते हैं, [दिखाओ]',
    'Registra mi sesión: {crossfit 40 min, intensidad alta}': 'मेरा सेशन दर्ज करो: {क्रॉसफ़िट 40 मिनट, तेज़ तीव्रता}',
    '[Arma una rutina] de {pecho y tríceps} de {45 min}': '{45 मिनट} की {छाती और ट्राइसेप्स} की [दिनचर्या बनाओ]',
    '[Dormí] {7 horas}, calidad {4/5}': '{7 घंटे} [सोया], क्वालिटी {4/5}',
    '[Abre] el {despertador}': '{अलार्म} [खोलो]',
    '[Abre] {mi sueño}': '{मेरी नींद} [खोलो]',
    '{Me acosté a las 23, desperté a las 7 y me levanté 2 veces}': '{23 बजे सोया, 7 बजे उठा, बीच में 2 बार उठना पड़ा}',
    '[Recuerdo]: {tarde de juegos con mi hermana}': '[याद]: {बहन के साथ खेलों वाली शाम}',
    '[Abre] el {calendario de ánimo}': '{मूड कैलेंडर} [खोलो]',
    'Anota esta anécdota: {hoy celebramos el cumple de mamá}': 'यह याद सहेजो: {आज मम्मी का जन्मदिन मनाया}',
    '[Cobré] {8000} de {la quincena}': '{पखवाड़े} के {8000} [मिले]',
    '[Abre] los {gastos fijos}': '{तय ख़र्चे} [खोलो]',
    '[Abre] las {metas de ahorro}': '{बचत के लक्ष्य} [खोलो]',
    '{Pagué 250 de luz y 180 de agua}': '{बिजली के 250 और पानी के 180 भरे}',
    '[Abre] el {formulario}': '{फ़ॉर्मूला बुक} [खोलो]',
    '[Resolver ecuación]': '[समीकरण हल करो]',
    '[Convertir unidades]': '[इकाइयाँ बदलो]',
    '[Sistema de ecuaciones]': '[समीकरण निकाय]',
    '[Convertir a binario]': '[बाइनरी में बदलो]',
    '[Propina]': '[टिप]',
    '[Regla de tres]': '[ऐकिक नियम]',
    '[Estudié] {historia romana} {30 min}': '{30 मिनट} {रोमन इतिहास} [पढ़ा]',
    '[Abre] la {sesión de estudio}': '{पढ़ाई का सेशन} [खोलो]',
    '[Abre] el {resumen de estudio}': '{पढ़ाई का सारांश} [खोलो]',
    'Apunta que aprendí: {los ríos de Europa}': 'लिख लो कि मैंने क्या सीखा: {यूरोप की नदियाँ}',
    '[Abre] la {mesa de juegos}': '{खेल की मेज़} [खोलो]',
    'Apunta {la serie Dark} como pendiente': '{सीरीज़ डार्क} को देखने की सूची में लिख लो',
    '[Abre] el {mapamundi}': '{विश्व का नक्शा} [खोलो]',
    '[Abre] {por conocer}': '{जहाँ जाना है} [खोलो]',
    '[Abre] la {bitácora de viajes}': '{सफ़रनामा} [खोलो]',
    '[Medité] {10 min}': '[ध्यान किया] {10 मिनट}',
    '[@]{jardin} [agradezco] {mi salud, mi familia y el café}': '[@]{jardin} [शुक्रगुज़ार हूँ] {अपनी सेहत, अपने परिवार और कॉफ़ी के लिए}',
    '[Abre] el {resumen del garage}': '{गैराज का सारांश} [खोलो]',
    '[Abre] {mis vehículos}': '{मेरी गाड़ियाँ} [खोलो]',
    '[Abre] las {efemérides}': '{आज के दिन} [खोलो]',
    '[Abre] {mis hobbies}': '{मेरे शौक} [खोलो]',
    '[Abre] mis {mapas mentales}': 'मेरे {माइंड मैप} [खोलो]',
    '[Abre] los {mapas conceptuales}': '{कॉन्सेप्ट मैप} [खोलो]',
    '[Dibuja un diagrama de flujo] de {cómo hacer pan}': '{ब्रेड कैसे बनती है} इसका [फ़्लोचार्ट बना दो]',
    '[Haz un esquema] de {lo que me acabas de explicar}': '{जो अभी समझाया} उसका [एक चित्र बना दो]',
    '[Agenda] una {junta con el cliente} el {martes a las 10}': '{मंगलवार 10 बजे} {क्लाइंट के साथ मीटिंग} [तय करो]',
    '[Apunta el pendiente] {mandar la cotización}': '[काम लिख लो]: {कोटेशन भेजना है}',
    '[Abre] mis {pendientes}': 'मेरे {काम} [खोलो]',
    '[Abre] mis {citas médicas}': 'मेरे {डॉक्टर के अपॉइंटमेंट} [खोलो]',
    '[Abre] el {progreso de idiomas}': '{भाषाओं की प्रगति} [खोलो]',
    '[Construye] un {huerto}': 'एक {सब्ज़ी बगीचा} [बनाओ]',
    '[Pon] una {pista de carreras}': 'एक {रेस ट्रैक} [लगाओ]',
    '[Traza] las {vías del tren}': '{रेल की पटरी} [बिछाओ]',
    '[Construye] una {montaña rusa}': 'एक {रोलर कोस्टर} [बनाओ]',
    '[Pon] la {meta} de la pista': 'ट्रैक की {फ़िनिश लाइन} [लगाओ]',
    '[Corre una carrera] de {3 vueltas}': '{3 चक्कर} की [रेस कराओ]',
    '[Quiero montar] la {montaña rusa}': '[मुझे बैठना है] {रोलर कोस्टर} पर',
    '[Llévame] a la {meta}': '[मुझे ले चलो] {फ़िनिश लाइन} तक',
    '[Juguemos paintball] {2v2}': '[पेंटबॉल खेलते हैं] {2v2}',
    '[Pon] una {cancha de fútbol}': 'एक {फ़ुटबॉल मैदान} [लगाओ]',
    '[Crea] una {cancha de básquet}': 'एक {बास्केटबॉल मैदान} [बनाओ]',
    '[Pon] un {campo de béisbol}': 'एक {बेसबॉल मैदान} [जोड़ो]',
    '[Abre] la {agenda de hoy}': '{आज की एजेंडा} [खोलो]',
    '[Abre] {mi semana}': '{मेरा हफ़्ता} [खोलो]',
    '[Crea una rutina] de mañana: {agua, estiramiento y gratitud} a las {7:00}': 'सुबह की [दिनचर्या बनाओ]: {7:00} बजे {पानी, स्ट्रेचिंग और आभार}',
    '[Crea una rutina] de {lunes y miércoles}: {correr 20 min}': '{सोमवार और बुधवार} की [दिनचर्या बनाओ]: {20 मिनट दौड़ना}',
    '[Gira el último objeto]': '[आख़िरी वस्तु घुमाओ]',
    '[Quita el último objeto]': '[आख़िरी वस्तु हटाओ]',
    '[Genera en 3D] {un dragón morado}': '{एक बैंगनी ड्रैगन} [3D में बनाओ]',
    '[Crea una imagen] de {un atardecer en la playa}': '{समुद्र तट पर ढलती शाम} की [तस्वीर बनाओ]',
    '[Bájame]': '[मुझे उतारो]',
    '[Vista en] {primera persona}': '{फ़र्स्ट पर्सन} [व्यू]',
    '[Quita el tema]': '[थीम हटाओ]',
    '[Volumen] al {40%}': '[आवाज़] {40%} पर',
    '[Apaga la música]': '[संगीत बंद करो]',
    '[Abre] mi {resumen semanal}': 'मेरा {हफ़्ते का सार} [खोलो]',
    '[Abre] mi {resumen mensual}': 'मेरा {महीने का सार} [खोलो]',
    '[Transparencia] al {40%}': '[पारदर्शिता] {40%} पर',
    '[Apaga los efectos]': '[इफ़ेक्ट बंद करो]',
    '[Avísame de mis metas] a las {21:00}': '{21:00} बजे [मेरे लक्ष्य याद दिलाएँ]',
    '[Apaga los avisos]': '[सूचनाएँ बंद करें]',
    '[Descarga un respaldo] de mis datos': 'मेरे डेटा का [बैकअप डाउनलोड करें]',
    '[Vuelve a ver la bienvenida]': '[स्वागत वाला मेन्यू फिर दिखाएँ]',
    '[Abre las configuraciones]': '[सेटिंग्स खोलें]',
    '[Recuerda que] {soy vegetariano}': '[याद रखें कि] {मैं शाकाहारी हूँ}',
    '[@]{cocina} {ensalada de la comida}': '[@]{cocina} {दोपहर के खाने में सलाद}',
    '[Cómo funciona] la {rueda de herramientas}': '{टूल व्हील} [कैसे काम करता है]',
    '[Abre] {ejemplo.com}': '[खोलें] {example.com}',
    '[Busca en internet] {recetas de pan}': '[इंटरनेट पर ढूँढें] {ब्रेड की रेसिपी}',
    '[Historial]': '[इतिहास]',
    '[Sitios]': '[साइटें]',
    '[Tiempo en internet]': '[ऑनलाइन समय]',
    '[Cómo llegar]': '[कैसे पहुँचें]',
    '[Amigos]': '[दोस्त]',
    '[Comí] {pollo con arroz} en la {cena}': '{रात के खाने} में {दाल-चावल} [खाया]',
    '[Abre] la {dieta}': '{डाइट} [खोलो]',
    '[Entrené] {pierna} {45 min}': '{45 मिनट} {पैरों} का [वर्कआउट किया]',
    '[Abre] {fuerza}': '{ताकत} [खोलो]',
    '[Abre] {cardio}': '{कार्डियो} [खोलो]',
    '[Abre] {flexibilidad}': '{लचीलापन} [खोलो]',
    '[Haz] una {sentadilla}': 'एक {स्क्वाट} [करो]',
    '[Arma una rutina] de {estiramientos} para {la espalda baja}': '{पीठ के निचले हिस्से} के लिए {स्ट्रेचिंग} की [दिनचर्या बनाओ]',
    '[Abre] mis {anécdotas}': 'मेरे {किस्से} [खोलो]',
    '[Gasté] {500} en {el súper}': '{किराने} पर {500} [ख़र्च किए]',
    '[Abre] el {balance}': '{नकदी प्रवाह} [खोलो]',
    '[Abre] los {movimientos}': '{लेन-देन} [खोलो]',
    '[Abre] las {divisas}': '{फ़ॉरेक्स} [खोलो]',
    '[Abre] las {criptomonedas}': '{क्रिप्टोकरेंसी} [खोलो]',
    '[Abre] las {materias primas}': '{कमोडिटी} [खोलो]',
    '[Abre] la {calculadora}': '{कैलकुलेटर} [खोलो]',
    '[Abre] el {graficador}': '{ग्राफ़} [खोलो]',
    '[Abre] las {hojas de cálculo}': '{स्प्रेडशीट} [खोलो]',
    '[Abre] las {matrices}': '{मैट्रिक्स} [खोलो]',
    '[Abre] las {charlas}': '{चैट} [खोलो]',
    '[Abre] la {enciclopedia}': '{विश्वकोश} [खोलो]',
    '[Vi la película] {Dune}': '{ड्यून} [फ़िल्म देखी]',
    '[Jugué] {ajedrez} con mi hermano': 'मेरे भाई के साथ {शतरंज} [खेला]',
    '[Abre] el {archivo}': '{संग्रह} [खोलो]',
    '[Quiero jugar] la {viborita}': 'मेरा {स्नेक गेम} [खेलने का मन है]',
    '[Juega] {tetris}': '{टेट्रिस} [खेलो]',
    '[Juega] una partida de {ajedrez}': '{शतरंज} की एक बाज़ी [खेलो]',
    '[Abre] las {rutas}': '{मार्ग} [खोलो]',
    '[Visité] {Oaxaca}': '{जयपुर} [घूम लिया]',
    'Quiero conocer {Japón}': 'मुझे {जापान} घूमना है',
    '[Visité] {Roma}: {la fontana de noche es mágica}': '{रोम} [घूम लिया]: {रात में फ़व्वारा जादुई लगता है}',
    '[Abre] la {meditación}': '{ध्यान} [खोलो]',
    '[Abre] la {respiración}': '{श्वास} [खोलो]',
    '[Abre] los {agradecimientos}': '{कृतज्ञता} [खोलो]',
    '[Abre] los {titulares}': '{सुर्ख़ियाँ} [खोलो]',
    'Avancé en mi [proyecto] de {acuarela} {40 min}': 'अपने {वॉटरकलर} [प्रोजेक्ट] में {40 मिनट} काम आगे बढ़ाया',
    'Practiqué {guitarra} {25 min}': '{गिटार} का {25 मिनट} अभ्यास किया',
    '[Hazme un mapa mental] de {la fotosíntesis}': 'मेरे लिए {प्रकाश संश्लेषण} का [माइंड मैप बना दो]',
    '[Compara] {café} y {té} en un mapa': 'एक मैप में {कॉफ़ी} और {चाय} की [तुलना करो]',
    '[Tengo cita] con el {dentista} el {14 a las 5}': '{डेंटिस्ट} से {14 तारीख़ को 5 बजे} [अपॉइंटमेंट है]',
    '[Recuérdame] tomar {ibuprofeno} a las {8 y a las 20}': 'मुझे {8 और 20 बजे} {आइबुप्रोफ़ेन} लेना [याद दिलाओ]',
    '[Guarda el contacto] de {Ana}: {5512345678}, cumple el {3 de mayo}': '{प्रिया} का [संपर्क सहेजो]: {5512345678}, जन्मदिन {3 मई} को',
    '[Abre] mis {contactos}': 'मेरे {संपर्क} [खोलो]',
    '[Vocab] {inglés}: {dog} = {perro}': '[शब्दावली] {अंग्रेज़ी}: {dog} = {कुत्ता}',
    '[Abre] el {tutor}': '{ट्यूटर} [खोलो]',
    '[Abre] el {repaso}': '{रिवीज़न} [खोलो]',
    '[Abre] el {temario}': '{पाठ्यक्रम} [खोलो]',
    '[Repasé] {francés} {15 min}': '{15 मिनट} {फ़्रेंच} का [रिवीज़न किया]',
    'Aprendí en {alemán}: {Hund} = {perro}': 'मैंने {जर्मन} में सीखा: {Hund} = {कुत्ता}',
    '[Quiero sembrar] {zanahorias}': 'मेरा {गाजर} [बोने का मन है]',
    '[Siembra] {maíz} en el huerto': 'सब्ज़ी बगीचे में {मक्का} [बोओ]',
    '[Pon] un {aspersor} en el huerto': 'सब्ज़ी बगीचे में एक {स्प्रिंकलर} [लगाओ]',
    '[Riega] el {huerto}': '{सब्ज़ी बगीचे} को [पानी दो]',
    '[Cosecha] el {huerto}': '{सब्ज़ी बगीचे} की [फ़सल काटो]',
    '[Llévame] al {huerto}': '[मुझे ले चलो] {सब्ज़ी बगीचे} तक',
    '[Haz] un {corral}': 'एक {बाड़ा} [बनाओ]',
    '[Pon] {vacas} en la granja': 'फ़ार्म में {गायें} [रखो]',
    '[Alimenta] a los {animales}': '{जानवरों} को [खाना खिलाओ]',
    '[Mima] a los {animales}': '{जानवरों} को [दुलार करो]',
    '[Cura] a los {animales}': '{जानवरों} का [इलाज करो]',
    '[Limpia] los {corrales}': '{बाड़ों} को [साफ़ करो]',
    '[Llévame] a la {granja}': '[मुझे ले चलो] {फ़ार्म} तक',
    '[Borra] la {pista}': '{ट्रैक} को [मिटाओ]',
    '[Hagamos una carrera] {contra} un asistente': 'चलो, एक सहायक {के ख़िलाफ़} [रेस लगाएँ]',
    '[Corre una carrera] {fácil} de {5 vueltas}': 'एक {आसान} {5 चक्कर} की [रेस कराओ]',
    '[Quiero montar] el {tren}': '[मुझे बैठना है] {ट्रेन} में',
    '[Juguemos] {paintball}': 'चलो {पेंटबॉल} [खेलते हैं]',
    '[Reta] a {Luna} a un paintball {1v1}': '{लूना} को {1v1} पेंटबॉल मैच की [चुनौती दो]',
    '[Paintball] campal en {difícil}': '{मुश्किल} स्तर पर [पेंटबॉल] की खुली भिड़ंत',
    '[Sal] del {paintball}': '{पेंटबॉल} से [बाहर निकलो]',
    '[Pon] una {cancha de tenis} {azul}': 'एक {नीला} {टेनिस कोर्ट} [लगाओ]',
    '[Llévame] a la {cancha}': '[मुझे ले चलो] {मैदान} तक',
    '[Abre] el {cronograma}': '{समय-सारणी} [खोलो]',
    '[Enséñame] las {rutinas}': 'मुझे {दिनचर्याएँ} [दिखाओ]',
    '[Crea un cuarto] llamado {Estudio}': '{स्टूडियो} नाम का [कमरा बनाओ]',
    '[Renombra] la {cocina} a {Oficina}': '{रसोई} का [नाम बदलकर] {ऑफ़िस} कर दो',
    '[Cambia el ícono] de la {cocina} a {🍳}': '{रसोई} का [आइकन बदलकर] {🍳} कर दो',
    '[Pon] la {cocina} en categoría {cuerpo}': '{रसोई} को {शरीर} श्रेणी में [रखो]',
    '[Agrega] la {biblioteca} al mapa': '{पुस्तकालय} को नक्शे में [जोड़ो]',
    '[Elimina] la {cocina}': '{रसोई} को [हटाओ]',
    '[Abre] la {cocina}': '{रसोई} [खोलो]',
    '[Pinta] la {cocina} de {azul}': '{रसोई} को {नीला} [रंग दो]',
    '[Piso] de la {cocina} de {madera}': '{रसोई} का [फ़र्श] {लकड़ी} का',
    '[Piso] de la {cocina} {rojo}': '{रसोई} का [फ़र्श] {लाल}',
    '[Techo] de la {cocina} de {tejas rojas}': '{रसोई} की [छत] {लाल खपरैल} की',
    '[Techo a dos aguas] en la {cocina}': '{रसोई} पर [दो ढलान वाली छत]',
    '[Haz] la {cocina} {redonda}': '{रसोई} को {गोल} [बनाओ]',
    '[Agranda] la {cocina}': '{रसोई} को [बड़ा करो]',
    '[Encoge] la {cocina}': '{रसोई} को [छोटा करो]',
    '[Mueve] la {cocina} a la {derecha}': '{रसोई} को {दाईं} ओर [खिसकाओ]',
    '[Abre el muro] {norte} de la {cocina}': '{रसोई} की {उत्तर} वाली [दीवार खोलो]',
    '[Pon una puerta] {corredera} en el muro {sur} de la {cocina}': '{रसोई} की {दक्षिण} वाली दीवार में {स्लाइडिंग} [दरवाज़ा लगाओ]',
    '[Pon] {ladrillo} en el muro {este} de la {cocina}': '{रसोई} की {पूर्व} वाली दीवार पर {ईंट} [लगाओ]',
    '[Haz más grueso] el muro {norte} de la {cocina}': '{रसोई} की {उत्तर} वाली दीवार [और मोटी करो]',
    '[Apila] la {sala} sobre la {cocina}': '{बैठक} को {रसोई} के [ऊपर रखो]',
    '[Agranda el mapa] hacia el {este}': '{पूर्व} की ओर [नक्शा बढ़ाओ]',
    '[Crea] una {lámpara}': 'एक {लैंप} [बनाओ]',
    '[Pinta el último objeto] de {rojo}': '{लाल} रंग से [आख़िरी वस्तु को रंग दो]',
    '[Haz el último objeto] más {grande}': '[आख़िरी वस्तु का आकार] {और बड़ा} करो',
    '[Agrupa los objetos] de la {cocina}': '{रसोई} की [वस्तुओं का ग्रुप बनाओ]',
    '[Genera en 3D] {una fuente de piedra} estilo {minimalista}': '{मिनिमलिस्ट} स्टाइल में {पत्थर का एक फ़व्वारा} [3D में बनाओ]',
    '[Ponme] {sombrero} {rojo}': 'मुझे {लाल} {टोपी} [पहनाओ]',
    '[Quítame] los {lentes}': 'मेरा {चश्मा} [उतार दो]',
    '[Pinta el torso] del [avatar] de {verde}': '{हरे} रंग से [अवतार] का [धड़ रंग दो]',
    '[Haz el avatar] más {grande}': '[अवतार का आकार] {और बड़ा} करो',
    '[Móntame] en la {bici}': 'मुझे {साइकिल} पर [बैठाओ]',
    '[Quiero conducir] el {auto}': 'मेरा {कार} [चलाने का मन है]',
    '[Vista] {isométrica}': '{आइसोमेट्रिक} [व्यू]',
    '[Cambia el tema] a {navidad}': '[थीम बदलकर] {क्रिसमस} कर दो',
    '[Fondo] {nieve}': '{बर्फ़} का [बैकग्राउंड]',
    '[Pon música] {relajante}': '{शांत} [संगीत चलाओ]',
    '[Música] {chiptune}': '{चिपट्यून} [संगीत]',
    '[Modo] {oscuro}': '{गहरा} [मोड]',
    '[Apariencia] {transparente}': '{पारदर्शी} [स्वरूप]',
    '[Cambia el idioma] a {inglés}': '[भाषा बदलकर] {अंग्रेज़ी} कर दो',
    '[Tema de interfaz] {neón}': '{नियॉन} [इंटरफ़ेस थीम]',
    '[Tipografía] {serif}': '{सेरिफ़} [फ़ॉन्ट]',
    '[Estilo de la interfaz] {pixel}': '{पिक्सेल} [इंटरफ़ेस शैली]',
    '[Pon iconos] {profesionales}': '{प्रोफ़ेशनल} [आइकन लगाओ]',
    '[Estilo] {cómic}': '{कॉमिक} [स्टाइल]',
    '[Avísame] de mis {rutinas}': 'मुझे मेरी {दिनचर्याएँ} [याद दिलाओ]',
    '[Abre] mi {cuenta}': 'मेरा {खाता} [खोलो]',
    '[Cómo funciona] la {cocina}': '{रसोई} [कैसे काम करती है]',
    '[Cómo funciona] el {editor}': '{एडिटर} [कैसे काम करता है]',
    '[Cómo funciona] el {chat}': '{चैट} [कैसे काम करती है]',
    '[Qué hace] el {inventario}': '{इन्वेंट्री} [क्या करती है]',
    '[Para qué sirve] la {cámara}': '{कैमरा} [किस काम आता है]',
    '[Tutorial de] {ejercicio}': '{जिम} का [ट्यूटोरियल दिखाओ]',
    '[Tutorial de] la {biblioteca}': '{पुस्तकालय} का [ट्यूटोरियल दिखाओ]',
    '[Tutorial] {general}': '{सामान्य} [ट्यूटोरियल दिखाओ]',
  },
  atajos: {
    'Caminar (también con las flechas)': 'चलना (तीर बटनों से भी)',
    'Correr (se queda puesto hasta volver a pulsar)': 'दौड़ना (दोबारा दबाने तक चालू रहता है)',
    'Saltar': 'कूदना',
    'Agacharse (mantener pulsado)': 'झुकना (दबाए रखें)',
    'Lo que tengas delante: entrar al cuarto, subirte o bajarte del vehículo, cambiar de nivel': 'सामने जो भी हो: कमरे में जाना, वाहन पर चढ़ना या उतरना, मंज़िल बदलना',
    'Levantar la mano derecha / izquierda': 'दायाँ / बायाँ हाथ उठाना',
    'Bailar': 'नाचना',
    'Mortal': 'कलाबाज़ी',
    'Abrir la rueda de herramientas': 'औज़ारों का चक्र खोलना',
    'Abrir el chat y escribir': 'चैट खोलकर लिखना',
    'Cambiar de vista: isométrica, tercera y primera persona': 'नज़र बदलना: आइसोमेट्रिक, तीसरा और पहला व्यक्ति',
    'Esconder o mostrar el HUD': 'HUD छिपाना या दिखाना',
    'Cerrar lo que esté abierto': 'जो भी खुला हो उसे बंद करना',
    'Conduciendo el OVNI: subir y bajar. En los demás vehículos, Espacio derrapa': 'UFO उड़ाते समय: ऊपर और नीचे। बाकी वाहनों में स्पेस से ड्रिफ़्ट',
  },
  teclas: {
    'Mayús': 'शिफ़्ट',
    'Espacio': 'स्पेस',
    'Espacio · Mayús': 'स्पेस · शिफ़्ट',
  },
}
