import type { ManualTraducido } from './manualI18n'

/**
 * Las frases de ejemplo del manual de comandos en de, indexadas por su
 * texto español de origen (ver `manualI18n.ts`).
 *
 * GENERADO por `npm run traducir:contenido` — no lo edites a mano.
 */
export const MANUAL_DE: ManualTraducido = {
  frases: {
    '[Corrí] {5 km} en {30 min}': '[Ich bin] {5 km} in {30 min} [gelaufen]',
    '[@]{cocina} [comí] {una ensalada}': '[@]{cocina} [ich habe] {einen Salat} [gegessen]',
    '[Abre] el {estudio de audio}': '[Öffne] das {Audiostudio}',
    '[Abre] mis {canciones}': '[Öffne] meine {Songs}',
    '[Abre] el {mezclador DJ}': '[Öffne] das {DJ-Mischpult}',
    '[Abre] la {galería de arte}': '[Öffne] die {Kunstgalerie}',
    '[Abre] mis {dibujos}': '[Öffne] meine {Zeichnungen}',
    '[Abre] mis {libros}': '[Öffne] meine {Bücher}',
    '[Abre] el {estudio de escritura}': '[Öffne] das {Schreibstudio}',
    '[Escribe un cuento] sobre {un faro en invierno} y [guárdalo en mis libros]': '[Schreib eine Kurzgeschichte] über {einen Leuchtturm im Winter} und [speicher sie in meinen Büchern]',
    '[Guarda en mis libros] este texto: {Querido diario, hoy…}': '[Speicher in meinen Büchern] diesen Text: {Liebes Tagebuch, heute…}',
    '[Abre] el {editor de video}': '[Öffne] den {Videoeditor}',
    '[Abre] mis {videos}': '[Öffne] meine {Videos}',
    '[Abre] la {animación 3D}': '[Öffne] die {3D-Animation}',
    "[Abre] {mis archivos}": "[Öffne] {meine Dateien}",
    "[Abre] los {archivos recientes}": "[Öffne] die {letzten Dateien}",
    "[Abre] los {archivos del studio}": "[Öffne] die {Studio-Dateien}",
    "[Abre] la {papelera}": "[Öffne] den {Papierkorb}",
    "[Abre] los {archivos destacados}": "[Öffne] die {markierten Dateien}",
    '[Tomé] {2 vasos} de [agua]': '[Ich habe] {2 Gläser} [Wasser] [getrunken]',
    '[Me pesé]: {74 kg}': '[Ich habe mich gewogen]: {74 kg}',
    '[Abre] el {diario de comidas}': '[Öffne] das {Ernährungstagebuch}',
    '[Abre] las {metas de nutrición}': '[Öffne] die {Ernährungsziele}',
    'Inventa una [receta] {ligera con atún}': 'Denk dir ein [Rezept] aus, {leicht, mit Thunfisch}',
    'Arma una [dieta] {alta en proteína}': 'Stell eine [Ernährung] {mit viel Protein} zusammen',
    'Agrega {plátano y avena} a la [lista del súper]': 'Setz {Bananen und Haferflocken} auf die [Einkaufsliste]',
    '[Corrí] {5 km}': '[Ich bin] {5 km} [gelaufen]',
    '[Muéstrame] cómo se hace el {press banca}': '[Zeig mir], wie {Bankdrücken} geht',
    'Registra mi sesión: {crossfit 40 min, intensidad alta}': 'Trag meine Einheit ein: {Crossfit 40 Min, hohe Intensität}',
    '[Arma una rutina] de {pecho y tríceps} de {45 min}': '[Stell eine Routine] für {Brust und Trizeps} über {45 Min} [zusammen]',
    '[Dormí] {7 horas}, calidad {4/5}': '[Ich habe] {7 Stunden} [geschlafen], Qualität {4/5}',
    '[Abre] {mi sueño}': '[Öffne] {mein Schlafen}',
    '{Me acosté a las 23, desperté a las 7 y me levanté 2 veces}': '{Um 23 Uhr ins Bett, um 7 Uhr wach, zweimal aufgestanden}',
    '[Recuerdo]: {tarde de juegos con mi hermana}': '[Erinnerung]: {Spielenachmittag mit meiner Schwester}',
    'Anota esta anécdota: {hoy celebramos el cumple de mamá}': 'Notier diese Anekdote: {heute haben wir Mamas Geburtstag gefeiert}',
    '[Cobré] {8000} de {la quincena}': '[Ich habe] {8000} {vom Halbmonatslohn} [bekommen]',
    '{Pagué 250 de luz y 180 de agua}': '{Ich habe 250 Strom und 180 Wasser bezahlt}',
    '[Resolver ecuación]': '[Gleichung lösen]',
    '[Convertir unidades]': '[Einheiten umrechnen]',
    '[Sistema de ecuaciones]': '[Gleichungssystem]',
    '[Convertir a binario]': '[In Binär umrechnen]',
    '[Propina]': '[Trinkgeld]',
    '[Regla de tres]': '[Dreisatz]',
    '[Estudié] {historia romana} {30 min}': '[Ich habe] {römische Geschichte} {30 Min} [gelernt]',
    '[Abre] el {resumen de estudio}': '[Öffne] die {Lernübersicht}',
    'Apunta que aprendí: {los ríos de Europa}': 'Notier, was ich gelernt habe: {die Flüsse Europas}',
    '[Vi la película] {Dune}': '[Ich habe den Film] {Dune} [gesehen]',
    'Apunta {la serie Dark} como pendiente': 'Setz {die Serie Dark} auf meine Merkliste',
    '[Abre] la {bitácora de viajes}': '[Öffne] das {Reise-Logbuch}',
    '[Visité] {Oaxaca}': '[Ich war in] {Oaxaca}',
    'Quiero conocer {Japón}': 'Ich will nach {Japan}',
    '[Medité] {10 min}': '[Ich habe] {10 Min} [meditiert]',
    '[Abre] el {resumen del garage}': '[Öffne] die {Garagenübersicht}',
    '[Abre] {mis vehículos}': '[Öffne] {meine Fahrzeuge}',
    '[Abre] las {efemérides}': '[Öffne] {was heute geschah}',
    '[Abre] {mis hobbies}': '[Öffne] {meine Hobbys}',
    '[Dibuja un diagrama de flujo] de {cómo hacer pan}': '[Zeichne ein Flussdiagramm] zu {Brot backen}',
    '[Haz un esquema] de {lo que me acabas de explicar}': '[Mach ein Diagramm] von {dem, was du mir gerade erklärt hast}',
    '[Agenda] una {junta con el cliente} el {martes a las 10}': '[Plane] ein {Meeting mit dem Kunden} am {Dienstag um 10}',
    '[Apunta el pendiente] {mandar la cotización}': '[Notier die Aufgabe] {das Angebot schicken}',
    '[Construye] un {huerto}': '[Bau] einen {Gemüsegarten}',
    '[Corre una carrera] de {3 vueltas}': '[Fahr ein Rennen] über {3 Runden}',
    '[Juguemos paintball] {2v2}': '[Spielen wir Paintball] {2v2}',
    '[Reta] a {Luna} a un paintball {1v1}': '[Fordere] {Luna} zu einem Paintball {1v1} heraus',
    '[Pon] una {cancha de fútbol}': '[Setz] einen {Fußballplatz}',
    '[Abre] la {agenda de hoy}': '[Öffne] die {Agenda von heute}',
    '[Abre] {mi semana}': '[Öffne] {meine Woche}',
    '[Crea una rutina] de mañana: {agua, estiramiento y gratitud} a las {7:00}': '[Leg eine Routine an] für morgens: {Wasser, Dehnen und Dankbarkeit} um {7:00}',
    '[Crea una rutina] de {lunes y miércoles}: {correr 20 min}': '[Leg eine Routine an] für {Montag und Mittwoch}: {20 Min laufen}',
    '[Crea un cuarto] llamado {Estudio}': '[Leg einen Raum an] mit dem Namen {Studio}',
    '[Gira el último objeto]': '[Dreh das letzte Objekt]',
    '[Quita el último objeto]': '[Nimm das letzte Objekt weg]',
    '[Genera en 3D] {un dragón morado}': '[Generier in 3D] {einen lila Drachen}',
    '[Crea una imagen] de {un atardecer en la playa}': '[Mach ein Bild] von {einem Sonnenuntergang am Strand}',
    '[Bájame]': '[Lass mich runter]',
    '[Vista en] {primera persona}': '[Ansicht aus] der {Ich-Perspektive}',
    '[Quita el tema]': '[Nimm das Thema weg]',
    '[Volumen] al {40%}': '[Lautstärke] auf {40 %}',
    '[Apaga la música]': '[Mach die Musik aus]',
    '[Abre] mi {resumen semanal}': '[Öffne] meinen {Wochenrückblick}',
    '[Abre] mi {resumen mensual}': '[Öffne] meinen {Monatsrückblick}',
    '[Transparencia] al {40%}': '[Transparenz] auf {40 %}',
    '[Estilo] {cómic}': '{Comic}-[Stil]',
    '[Apaga los efectos]': '[Mach die Effekte aus]',
    '[Avísame de mis metas] a las {21:00}': '[Erinnere mich an meine Ziele] um {21:00}',
    '[Apaga los avisos]': '[Schalte die Hinweise aus]',
    '[Descarga un respaldo] de mis datos': '[Lade eine Sicherung] meiner Daten herunter',
    '[Vuelve a ver la bienvenida]': '[Zeig mir die Begrüßung noch mal]',
    '[Abre las configuraciones]': '[Öffne die Einstellungen]',
    '[Recuerda que] {soy vegetariano}': '[Merk dir, dass] {ich Vegetarier bin}',
    '[@]{cocina} {ensalada de la comida}': '[@]{cocina} {Salat zum Mittagessen}',
    '[Abre] {ejemplo.com}': '[Öffne] {beispiel.de}',
    '[Busca en internet] {recetas de pan}': '[Such im Internet] {Brotrezepte}',
    '[Historial]': '[Verlauf]',
    '[Sitios]': '[Seiten]',
    '[Tiempo en internet]': '[Zeit im Internet]',
    '[Cómo llegar]': '[Route]',
    '[Amigos]': '[Freunde]',
    '{Tenis} {@ana}': '{Tennis} {@ana}',
    '[Comí] {pollo con arroz} en la {cena}': 'Ich habe {Hähnchen mit Reis} zum {Abendessen} [gegessen]',
    '[Abre] el {recetario}': '[Öffne] die {Rezepte}',
    '[Abre] la {lista del súper}': '[Öffne] die {Einkaufsliste}',
    '[Abre] la {dieta}': '[Öffne] die {Diät}',
    '[Entrené] {pierna} {45 min}': 'Ich habe {45 Min} {Beine} [trainiert]',
    '[Abre] el {plan de ejercicio}': '[Öffne] den {Trainingsplan}',
    '[Abre] {fuerza}': '[Öffne] das {Krafttraining}',
    '[Abre] {cardio}': '[Öffne] {Cardio}',
    '[Abre] {flexibilidad}': '[Öffne] die {Beweglichkeit}',
    '[Abre] las {metas de ejercicio}': '[Öffne] die {Trainingsziele}',
    '[Haz] una {sentadilla}': '[Mach] eine {Kniebeuge}',
    '[Arma una rutina] de {estiramientos} para {la espalda baja}': '[Erstelle eine Routine] aus {Dehnübungen} für {den unteren Rücken}',
    '[Abre] el {despertador}': '[Öffne] den {Wecker}',
    '[Abre] mis {anécdotas}': '[Öffne] meine {Anekdoten}',
    '[Abre] el {calendario de ánimo}': '[Öffne] den {Stimmungskalender}',
    '[Gasté] {500} en {el súper}': 'Ich habe {500} im {Supermarkt} [ausgegeben]',
    '[Abre] el {balance}': '[Öffne] den {Cashflow}',
    '[Abre] los {gastos fijos}': '[Öffne] die {Fixkosten}',
    '[Abre] los {movimientos}': '[Öffne] die {Buchungen}',
    '[Abre] las {metas de ahorro}': '[Öffne] die {Sparziele}',
    '[Abre] las {divisas}': '[Öffne] die {Devisen}',
    '[Abre] las {criptomonedas}': '[Öffne] die {Kryptowährungen}',
    '[Abre] las {materias primas}': '[Öffne] die {Rohstoffe}',
    '[Abre] el {formulario}': '[Öffne] das {Formelbuch}',
    '[Abre] la {calculadora}': '[Öffne] den {Taschenrechner}',
    '[Abre] el {graficador}': '[Öffne] den {Funktionsplotter}',
    '[Abre] las {hojas de cálculo}': '[Öffne] die {Tabellen}',
    '[Abre] las {matrices}': '[Öffne] die {Matrizen}',
    '[Abre] las {charlas}': '[Öffne] die {Chats}',
    '[Abre] la {enciclopedia}': '[Öffne] die {Enzyklopädie}',
    '[Abre] la {sesión de estudio}': '[Öffne] die {Lernsitzung}',
    '[Jugué] {ajedrez} con mi hermano': 'Ich habe mit meinem Bruder {Schach} [gespielt]',
    '[Abre] el {archivo}': '[Öffne] das {Archiv}',
    '[Abre] la {mesa de juegos}': '[Öffne] die {Brettspiele}',
    '[Quiero jugar] la {viborita}': 'Ich will {Snake} [spielen]',
    '[Juega] {tetris}': '[Spiel] {Tetris}',
    '[Juega] una partida de {ajedrez}': '[Spiel] eine Partie {Schach}',
    '[Abre] el {mapamundi}': '[Öffne] die {Weltkarte}',
    '[Abre] {por conocer}': '[Öffne] den {Reiseplan}',
    '[Abre] las {rutas}': '[Öffne] die {Routen}',
    '[Visité] {Roma}: {la fontana de noche es mágica}': '[Ich war in] {Rom}: {der Brunnen ist nachts magisch}',
    '[@]{jardin} [agradezco] {mi salud, mi familia y el café}': '[@]{jardin} [ich bin dankbar für] {meine Gesundheit, meine Familie und den Kaffee}',
    '[Abre] la {meditación}': '[Öffne] die {Meditation}',
    '[Abre] la {respiración}': '[Öffne] die {Atmung}',
    '[Abre] los {agradecimientos}': '[Öffne] die {Dankbarkeit}',
    '[Abre] los {titulares}': '[Öffne] die {Schlagzeilen}',
    'Avancé en mi [proyecto] de {acuarela} {40 min}': 'Ich habe {40 Min} an meinem [Projekt] {Aquarell} gearbeitet',
    'Practiqué {guitarra} {25 min}': 'Ich habe {25 Min} {Gitarre} geübt',
    '[Abre] mis {mapas mentales}': '[Öffne] meine {Mindmaps}',
    '[Abre] los {mapas conceptuales}': '[Öffne] die {Konzeptkarten}',
    '[Hazme un mapa mental] de {la fotosíntesis}': '[Mach mir eine Mindmap] zum Thema {Photosynthese}',
    '[Compara] {café} y {té} en un mapa': '[Vergleiche] {Kaffee} und {Tee} in einer Konzeptkarte',
    '[Tengo cita] con el {dentista} el {14 a las 5}': '[Ich habe einen Termin] beim {Zahnarzt} am {14. um 17 Uhr}',
    '[Recuérdame] tomar {ibuprofeno} a las {8 y a las 20}': '[Erinnere mich] daran, {Ibuprofen} um {8 und 20 Uhr} zu nehmen',
    '[Guarda el contacto] de {Ana}: {5512345678}, cumple el {3 de mayo}': '[Speicher den Kontakt] von {Anna}: {5512345678}, Geburtstag am {3. Mai}',
    '[Abre] mis {pendientes}': '[Öffne] meine {Aufgaben}',
    '[Abre] mis {citas médicas}': '[Öffne] meine {Arzttermine}',
    '[Abre] mis {contactos}': '[Öffne] meine {Kontakte}',
    '[Vocab] {inglés}: {dog} = {perro}': '[Vokabeln] {Englisch}: {dog} = {Hund}',
    '[Abre] el {tutor}': '[Öffne] den {Tutor}',
    '[Abre] el {repaso}': '[Öffne] die {Wiederholung}',
    '[Abre] el {temario}': '[Öffne] den {Lehrplan}',
    '[Abre] el {progreso de idiomas}': '[Öffne] den {Sprachfortschritt}',
    '[Repasé] {francés} {15 min}': 'Ich habe {15 Min} {Französisch} [wiederholt]',
    'Aprendí en {alemán}: {Hund} = {perro}': 'Ich habe auf {Spanisch} gelernt: {perro} = {Hund}',
    '[Quiero sembrar] {zanahorias}': 'Ich will {Karotten} [pflanzen]',
    '[Siembra] {maíz} en el huerto': '[Pflanz] {Mais} in den Gemüsegarten',
    '[Pon] un {aspersor} en el huerto': '[Stell] einen {Sprinkler} in den Gemüsegarten',
    '[Riega] el {huerto}': '[Gieß] den {Gemüsegarten}',
    '[Cosecha] el {huerto}': '[Ernte] den {Gemüsegarten}',
    '[Llévame] al {huerto}': '[Bring mich] zum {Gemüsegarten}',
    '[Haz] un {corral}': '[Bau] ein {Gehege}',
    '[Pon] {vacas} en la granja': '[Setz] {Kühe} auf den Bauernhof',
    '[Alimenta] a los {animales}': '[Füttere] die {Tiere}',
    '[Mima] a los {animales}': '[Streichle] die {Tiere}',
    '[Cura] a los {animales}': '[Heile] die {Tiere}',
    '[Limpia] los {corrales}': '[Säubere] die {Gehege}',
    '[Llévame] a la {granja}': '[Bring mich] zum {Bauernhof}',
    '[Pon] una {pista de carreras}': '[Bau] eine {Rennstrecke}',
    '[Traza] las {vías del tren}': '[Verlege] die {Bahngleise}',
    '[Construye] una {montaña rusa}': '[Bau] eine {Achterbahn}',
    '[Pon] la {meta} de la pista': '[Setz] die {Ziellinie} auf die Strecke',
    '[Borra] la {pista}': '[Lösche] die {Rennstrecke}',
    '[Hagamos una carrera] {contra} un asistente': '[Fahren wir ein Rennen] {gegen} einen Assistenten',
    '[Corre una carrera] {fácil} de {5 vueltas}': '[Fahr ein Rennen] über {5 Runden} auf {leicht}',
    '[Quiero montar] el {tren}': 'Ich will mit dem {Zug} [fahren]',
    '[Quiero montar] la {montaña rusa}': 'Ich will mit der {Achterbahn} [fahren]',
    '[Llévame] a la {meta}': '[Bring mich] zur {Ziellinie}',
    '[Juguemos] {paintball}': '[Spielen wir] {Paintball}',
    '[Paintball] campal en {difícil}': '[Paintball], jeder gegen jeden, auf {schwer}',
    '[Sal] del {paintball}': '[Beende] das {Paintball}-Match',
    '[Pon] una {cancha de tenis} {azul}': '[Setz] einen {blauen} {Tennisplatz}',
    '[Crea] una {cancha de básquet}': '[Erstelle] einen {Basketballplatz}',
    '[Pon] un {campo de béisbol}': '[Setz] ein {Baseballfeld}',
    '[Llévame] a la {cancha}': '[Bring mich] zum {Platz}',
    '[Abre] el {cronograma}': '[Öffne] den {Zeitplan}',
    '[Enséñame] las {rutinas}': '[Zeig mir] die {Routinen}',
    '[Renombra] la {cocina} a {Oficina}': '[Ändere den Namen] der {Küche} in {Büro}',
    '[Cambia el ícono] de la {cocina} a {🍳}': '[Ändere das Symbol] der {Küche} auf {🍳}',
    '[Pon] la {cocina} en categoría {cuerpo}': '[Setz] die {Küche} in die Kategorie {Körper}',
    '[Agrega] la {biblioteca} al mapa': '[Platziere] die {Bibliothek} auf der Karte',
    '[Elimina] la {cocina}': '[Lösche] die {Küche}',
    '[Abre] la {cocina}': '[Öffne] die {Küche}',
    '[Pinta] la {cocina} de {azul}': '[Streich] die {Küche} {blau}',
    '[Piso] de la {cocina} de {madera}': 'Gib der {Küche} einen [Boden] aus {Holz}',
    '[Piso] de la {cocina} {rojo}': 'Gib der {Küche} einen [Boden] in {Rot}',
    '[Techo] de la {cocina} de {tejas rojas}': 'Gib der {Küche} ein [Dach] aus {roten Ziegeln}',
    '[Techo a dos aguas] en la {cocina}': 'Setz ein [Satteldach] auf die {Küche}',
    '[Haz] la {cocina} {redonda}': '[Mach] die {Küche} {rund}',
    '[Agranda] la {cocina}': '[Vergrößere] die {Küche}',
    '[Encoge] la {cocina}': '[Verkleinere] die {Küche}',
    '[Mueve] la {cocina} a la {derecha}': '[Schieb] die {Küche} nach {rechts}',
    '[Abre el muro] {norte} de la {cocina}': '[Öffne die Wand] im {Norden} der {Küche}',
    '[Pon una puerta] {corredera} en el muro {sur} de la {cocina}': '[Setz eine Tür] in die Wand im {Süden} der {Küche}, als {Schiebetür}',
    '[Pon] {ladrillo} en el muro {este} de la {cocina}': '[Mach] die Wand im {Osten} der {Küche} aus {Backstein}',
    '[Haz más grueso] el muro {norte} de la {cocina}': '[Verdicke] die Wand im {Norden} der {Küche}',
    '[Apila] la {sala} sobre la {cocina}': '[Stapel] das {Wohnzimmer} auf die {Küche}',
    '[Agranda el mapa] hacia el {este}': '[Vergrößere die Karte] nach {Osten}',
    '[Crea] una {lámpara}': '[Erstelle] eine {Lampe}',
    '[Pinta el último objeto] de {rojo}': '[Färb das letzte Objekt] {rot}',
    '[Haz el último objeto] más {grande}': '[Mach das letzte Objekt] {größer}',
    '[Agrupa los objetos] de la {cocina}': '[Gruppiere die Objekte] in der {Küche}',
    '[Genera en 3D] {una fuente de piedra} estilo {minimalista}': '[Generier in 3D] {einen Steinbrunnen} im {minimalistischen} Stil',
    '[Ponme] {sombrero} {rojo}': '[Setz] mir einen {roten} {Hut} auf',
    '[Quítame] los {lentes}': '[Nimm] mir die {Brille} ab',
    '[Pinta el torso] del [avatar] de {verde}': '[Färb den Oberkörper] des [Avatars] {grün}',
    '[Haz el avatar] más {grande}': '[Mach den Avatar] {größer}',
    '[Móntame] en la {bici}': '[Setz mich] aufs {Fahrrad}',
    '[Quiero conducir] el {auto}': 'Ich will das {Auto} [fahren]',
    '[Vista] {isométrica}': '{Isometrische} [Ansicht]',
    '[Cambia el tema] a {navidad}': '[Ändere das Thema] auf {Weihnachten}',
    '[Fondo] {nieve}': '[Hintergrund] {Schnee}',
    '[Pon música] {relajante}': '[Spiel Musik] {zum Entspannen}',
    '[Música] {chiptune}': '[Musik] {Chiptune}',
    '[Modo] {oscuro}': '{Dunkler} [Modus]',
    '[Apariencia] {transparente}': '[Erscheinungsbild] {transparent}',
    '[Cambia el idioma] a {inglés}': '[Wechsle die Sprache] auf {Englisch}',
    '[Tema de interfaz] {neón}': '[Oberflächendesign] {Neon}',
    '[Tipografía] {serif}': '[Schriftart] {Serif}',
    '[Estilo de la interfaz] {pixel}': '[Stil der Oberfläche] {Pixel}',
    '[Pon iconos] {profesionales}': '[Verwende Symbole] im {professionellen} Stil',
    '[Avísame] de mis {rutinas}': '[Benachrichtige mich] über meine {Routinen}',
    '[Abre] mi {cuenta}': '[Öffne] mein {Konto}',
    '[Cómo funciona] la {cocina}': '[Wie funktioniert] die {Küche}',
    '[Cómo funciona] el {editor}': '[Wie funktioniert] der {Editor}',
    '[Cómo funciona] la {rueda de herramientas}': '[Wie funktioniert] das {Werkzeugrad}',
    '[Cómo funciona] el {chat}': '[Wie funktioniert] der {Chat}',
    '[Qué hace] el {inventario}': '[Was macht] das {Inventar}',
    '[Para qué sirve] la {cámara}': '[Wozu dient] die {Kamera}',
    '[Tutorial de] {ejercicio}': '[Tutorial zu] {Fitness}',
    '[Tutorial de] la {biblioteca}': '[Tutorial zur] {Bibliothek}',
    '[Tutorial] {general}': '{Allgemeines} [Tutorial]',
  },
  atajos: {
    'Caminar (también con las flechas)': 'Gehen (auch mit den Pfeiltasten)',
    'Correr (se queda puesto hasta volver a pulsar)': 'Rennen (bleibt an, bis du noch mal drückst)',
    'Saltar': 'Springen',
    'Agacharse (mantener pulsado)': 'Ducken (gedrückt halten)',
    'Lo que tengas delante: entrar al cuarto, subirte o bajarte del vehículo, cambiar de nivel': 'Was auch immer vor dir ist: den Raum betreten, aufs Fahrzeug steigen oder absteigen, die Etage wechseln',
    'Levantar la mano derecha / izquierda': 'Rechte / linke Hand heben',
    'Bailar': 'Tanzen',
    'Mortal': 'Salto',
    'Abrir la rueda de herramientas': 'Werkzeugrad öffnen',
    'Abrir el chat y escribir': 'Chat öffnen und schreiben',
    'Cambiar de vista: isométrica, tercera y primera persona': 'Ansicht wechseln: isometrisch, dritte und erste Person',
    'Esconder o mostrar el HUD': 'HUD ausblenden oder einblenden',
    'Cerrar lo que esté abierto': 'Schließen, was gerade offen ist',
    'Conduciendo el OVNI: subir y bajar. En los demás vehículos, Espacio derrapa': 'Im UFO: rauf und runter. In den anderen Fahrzeugen driftest du mit der Leertaste',
  },
  teclas: {
    'Mayús': 'Umschalt',
    'Espacio': 'Leertaste',
    'Espacio · Mayús': 'Leertaste · Umschalt',
  },
}
