import type { ManualTraducido } from './manualI18n'

/**
 * Las frases de ejemplo del manual de comandos en pl, indexadas por su
 * texto español de origen (ver `manualI18n.ts`).
 *
 * GENERADO por `npm run traducir:contenido` — no lo edites a mano.
 */
export const MANUAL_PL: ManualTraducido = {
  frases: {
    '[Corrí] {5 km} en {30 min}': '[Przebiegłem] {5 km} w {30 min}',
    '[@]{cocina} [comí] {una ensalada}': '[@]{cocina} [zjadłem] {sałatkę}',
    '[Abre] el {estudio de audio}': '[Otwórz] {studio audio}',
    '[Abre] mis {canciones}': '[Otwórz] moje {piosenki}',
    '[Abre] el {mezclador DJ}': '[Otwórz] {mikser DJ}',
    '[Abre] la {galería de arte}': '[Otwórz] {galerię sztuki}',
    '[Abre] mis {dibujos}': '[Otwórz] moje {rysunki}',
    '[Abre] mis {libros}': '[Otwórz] moje {książki}',
    '[Abre] el {estudio de escritura}': '[Otwórz] {studio pisania}',
    '[Escribe un cuento] sobre {un faro en invierno} y [guárdalo en mis libros]': '[Napisz opowiadanie] o {latarni morskiej zimą} i [zapisz je w moich książkach]',
    '[Guarda en mis libros] este texto: {Querido diario, hoy…}': '[Zapisz w moich książkach] ten tekst: {Drogi pamiętniku, dziś…}',
    '[Abre] el {editor de video}': '[Otwórz] {edytor wideo}',
    '[Abre] mis {videos}': '[Otwórz] moje {filmy}',
    '[Abre] la {animación 3D}': '[Otwórz] {animację 3D}',
    "[Abre] {mis archivos}": "[Otwórz] {moje pliki}",
    "[Abre] los {archivos recientes}": "[Otwórz] {ostatnie pliki}",
    "[Abre] los {archivos del studio}": "[Otwórz] {pliki ze studia}",
    "[Abre] la {papelera}": "[Otwórz] {kosz}",
    "[Abre] los {archivos destacados}": "[Otwórz] {pliki z gwiazdką}",
    '[Tomé] {2 vasos} de [agua]': '[Piję] {2 szklanki} [wody]',
    '[Me pesé]: {74 kg}': '[Ważę]: {74 kg}',
    '[Abre] el {recetario}': '[Otwórz] {książkę kucharską}',
    '[Abre] la {lista del súper}': '[Otwórz] {listę zakupów}',
    '[Abre] el {diario de comidas}': '[Otwórz] {dziennik jedzenia}',
    '[Abre] las {metas de nutrición}': '[Otwórz] {cele żywieniowe}',
    'Inventa una [receta] {ligera con atún}': 'Wymyśl [przepis] {lekki, z tuńczykiem}',
    'Arma una [dieta] {alta en proteína}': 'Ułóż [dietę] {wysokobiałkową}',
    'Agrega {plátano y avena} a la [lista del súper]': 'Dodaj {banany i płatki owsiane} do [listy zakupów]',
    '[Corrí] {5 km}': '[Przebiegam] {5 km}',
    '[Abre] el {plan de ejercicio}': '[Otwórz] {plan treningowy}',
    '[Abre] {cardio}': '[Otwórz] {cardio}',
    '[Abre] las {metas de ejercicio}': '[Otwórz] {cele treningowe}',
    '[Muéstrame] cómo se hace el {press banca}': '[Pokaż mi], jak zrobić {wyciskanie na ławce}',
    'Registra mi sesión: {crossfit 40 min, intensidad alta}': 'Zapisz moją sesję: {crossfit 40 min, wysoka intensywność}',
    '[Arma una rutina] de {pecho y tríceps} de {45 min}': '[Ułóż rutynę] na {klatkę i triceps} na {45 min}',
    '[Dormí] {7 horas}, calidad {4/5}': '[Śpię] {7 godzin}, jakość {4/5}',
    '[Abre] {mi sueño}': '[Otwórz] {mój sen}',
    '{Me acosté a las 23, desperté a las 7 y me levanté 2 veces}': '{Kładę się o 23, budzę się o 7, wstaję 2 razy}',
    '[Recuerdo]: {tarde de juegos con mi hermana}': '[Wspomnienie]: {wieczór z grami planszowymi z siostrą}',
    '[Abre] el {calendario de ánimo}': '[Otwórz] {kalendarz nastroju}',
    'Anota esta anécdota: {hoy celebramos el cumple de mamá}': 'Zapisz to wspomnienie: {dziś świętowaliśmy urodziny mamy}',
    '[Cobré] {8000} de {la quincena}': '[Dostaję] {8000} z {wypłaty}',
    '[Abre] los {gastos fijos}': '[Otwórz] {stałe wydatki}',
    '[Abre] las {metas de ahorro}': '[Otwórz] {cele oszczędnościowe}',
    '{Pagué 250 de luz y 180 de agua}': '{Płacę 250 za prąd i 180 za wodę}',
    '[Abre] el {formulario}': '[Otwórz] {zbiór wzorów}',
    '[Resolver ecuación]': '[Rozwiąż równanie]',
    '[Convertir unidades]': '[Przelicz jednostki]',
    '[Sistema de ecuaciones]': '[Układ równań]',
    '[Convertir a binario]': '[Zamień na system dwójkowy]',
    '[Propina]': '[Napiwek]',
    '[Regla de tres]': '[Proporcja]',
    '[Estudié] {historia romana} {30 min}': '[Uczę się] {historii Rzymu} {30 min}',
    '[Abre] la {sesión de estudio}': '[Otwórz] {sesję nauki}',
    '[Abre] el {resumen de estudio}': '[Otwórz] {podsumowanie nauki}',
    'Apunta que aprendí: {los ríos de Europa}': 'Zapisz, czego się uczę: {rzeki Europy}',
    '[Abre] la {mesa de juegos}': '[Otwórz] {stół do gier}',
    '[Juega] {tetris}': '[Zagraj] w {tetris}',
    'Apunta {la serie Dark} como pendiente': 'Zapisz {serial Dark} do obejrzenia',
    '[Abre] el {mapamundi}': '[Otwórz] {mapę świata}',
    '[Abre] {por conocer}': '[Otwórz] {do odwiedzenia}',
    '[Abre] la {bitácora de viajes}': '[Otwórz] {dziennik podróży}',
    '[Medité] {10 min}': '[Medytacja] {10 min}',
    '[Abre] el {resumen del garage}': '[Otwórz] {podsumowanie garażu}',
    '[Abre] {mis vehículos}': '[Otwórz] {moje pojazdy}',
    '[Abre] {mis hobbies}': '[Otwórz] {moje hobby}',
    '[Abre] mis {mapas mentales}': '[Otwórz] moje {mapy myśli}',
    '[Abre] los {mapas conceptuales}': '[Otwórz] {mapy pojęciowe}',
    '[Dibuja un diagrama de flujo] de {cómo hacer pan}': '[Narysuj schemat blokowy] {jak upiec chleb}',
    '[Haz un esquema] de {lo que me acabas de explicar}': '[Zrób schemat] {tego, co mi właśnie wyjaśniłeś}',
    '[Agenda] una {junta con el cliente} el {martes a las 10}': '[Zaplanuj] {spotkanie z klientem} we {wtorek o 10}',
    '[Apunta el pendiente] {mandar la cotización}': '[Zapisz zadanie] {wysłać wycenę}',
    '[Abre] mis {citas médicas}': '[Otwórz] moje {wizyty lekarskie}',
    '[Abre] el {progreso de idiomas}': '[Otwórz] {postępy w językach}',
    '[Pon] una {pista de carreras}': '[Postaw] {tor wyścigowy}',
    '[Traza] las {vías del tren}': '[Poprowadź] {tory kolejowe}',
    '[Construye] una {montaña rusa}': '[Zbuduj] {kolejkę górską}',
    '[Pon] la {meta} de la pista': '[Postaw] {metę} na torze',
    '[Corre una carrera] de {3 vueltas}': '[Ścigajmy się] na {3 okrążenia}',
    '[Quiero montar] la {montaña rusa}': '[Chcę przejechać się] {kolejką górską}',
    '[Llévame] a la {meta}': '[Zabierz mnie] na {metę}',
    '[Juguemos] {paintball}': '[Zagrajmy] w {paintball}',
    '[Juguemos paintball] {2v2}': '[Zagrajmy w paintball] {2v2}',
    '[Pon] una {cancha de fútbol}': '[Postaw] {boisko do piłki nożnej}',
    '[@]{jardin} [agradezco] {mi salud, mi familia y el café}': '[@]{jardin} [wdzięczność za] {zdrowie, rodzinę i kawę}',
    '[Recuérdame] tomar {ibuprofeno} a las {8 y a las 20}': '[Przypominaj mi] brać {ibuprofen} o {8 i 20}',
    '[Crea] una {cancha de básquet}': '[Stwórz] {boisko do koszykówki}',
    '[Pon] un {campo de béisbol}': '[Dodaj] {boisko do baseballu}',
    '[Abre] la {agenda de hoy}': '[Otwórz] {dzisiejszy plan dnia}',
    '[Abre] {mi semana}': '[Otwórz] {mój tydzień}',
    '[Crea una rutina] de mañana: {agua, estiramiento y gratitud} a las {7:00}': '[Stwórz rutynę] na poranek: {woda, rozciąganie i wdzięczność} o {7:00}',
    '[Crea una rutina] de {lunes y miércoles}: {correr 20 min}': '[Stwórz rutynę] na {poniedziałki i środy}: {bieganie 20 min}',
    '[Gira el último objeto]': '[Obróć ostatni obiekt]',
    '[Quita el último objeto]': '[Usuń ostatni obiekt]',
    '[Genera en 3D] {un dragón morado}': '[Wygeneruj w 3D] {fioletowego smoka}',
    '[Crea una imagen] de {un atardecer en la playa}': '[Stwórz obraz] {zachodu słońca na plaży}',
    '[Bájame]': '[Zsadź mnie]',
    '[Quita el tema]': '[Usuń motyw]',
    '[Música] {chiptune}': '[Muzyka] {chiptune}',
    '[Volumen] al {40%}': '[Głośność] na {40%}',
    '[Apaga la música]': '[Wyłącz muzykę]',
    '[Abre] mi {resumen semanal}': '[Otwórz] moje {podsumowanie tygodnia}',
    '[Abre] mi {resumen mensual}': '[Otwórz] moje {podsumowanie miesiąca}',
    '[Tema de interfaz] {neón}': '[Motyw interfejsu] {neon}',
    '[Estilo de la interfaz] {pixel}': '[Styl interfejsu] {pixel}',
    '[Transparencia] al {40%}': '[Przezroczystość] na {40%}',
    '[Apaga los efectos]': '[Wyłącz efekty]',
    '[Vista en] {primera persona}': '[Widok z] {pierwszej osoby}',
    '[Avísame de mis metas] a las {21:00}': '[Przypominaj mi o moich celach] o {21:00}',
    '[Apaga los avisos]': '[Wyłącz powiadomienia]',
    '[Descarga un respaldo] de mis datos': '[Pobierz kopię zapasową] moich danych',
    '[Vuelve a ver la bienvenida]': '[Pokaż powitanie jeszcze raz]',
    '[Abre las configuraciones]': '[Otwórz ustawienia]',
    '[Recuerda que] {soy vegetariano}': '[Zapamiętaj, że] {jestem na diecie wegetariańskiej}',
    '[@]{cocina} {ensalada de la comida}': '[@]{cocina} {sałatka na obiad}',
    '[Cómo funciona] la {rueda de herramientas}': '[Jak działa] {koło narzędzi}',
    '[Abre] {ejemplo.com}': '[Otwórz] {przyklad.pl}',
    '[Busca en internet] {recetas de pan}': '[Poszukaj w internecie] {przepisy na chleb}',
    '[Historial]': '[Historia]',
    '[Sitios]': '[Strony]',
    '[Tiempo en internet]': '[Czas w internecie]',
    '[Cómo llegar]': '[Jak dojechać]',
    '[Amigos]': '[Znajomi]',
    '[Jugar] {paintball} [con] {@ana}': '[Zagrać w] {paintball} [z] {@ana}',
  },
  atajos: {
    'Caminar (también con las flechas)': 'Chodzenie (także strzałkami)',
    'Correr (se queda puesto hasta volver a pulsar)': 'Bieg (zostaje włączony do kolejnego naciśnięcia)',
    'Saltar': 'Skok',
    'Agacharse (mantener pulsado)': 'Kucanie (przytrzymaj)',
    'Lo que tengas delante: entrar al cuarto, subirte o bajarte del vehículo, cambiar de nivel': 'To, co masz przed sobą: wejść do pokoju, wsiąść lub wysiąść z pojazdu, zmienić poziom',
    'Levantar la mano derecha / izquierda': 'Podnieś prawą / lewą rękę',
    'Bailar': 'Taniec',
    'Mortal': 'Salto',
    'Abrir la rueda de herramientas': 'Otwórz koło narzędzi',
    'Abrir el chat y escribir': 'Otwórz czat i pisz',
    'Cambiar de vista: isométrica, tercera y primera persona': 'Zmiana widoku: izometryczny, trzecia i pierwsza osoba',
    'Esconder o mostrar el HUD': 'Ukryj lub pokaż HUD',
    'Cerrar lo que esté abierto': 'Zamknij to, co jest otwarte',
    'Conduciendo el OVNI: subir y bajar. En los demás vehículos, Espacio derrapa': 'Za sterami UFO: w górę i w dół. W innych pojazdach Spacja to poślizg',
  },
  teclas: {
    'Mayús': 'Shift',
    'Espacio': 'Spacja',
    'Espacio · Mayús': 'Spacja · Shift',
  },
}
