import { idiomasRepo, tarjetasIdiomaRepo, temasIdiomaRepo } from '../../core/data/repository'
import { fechaLocalISO, isoMasDias } from '../../core/fechaLocal'
import { fotoEjemplo } from '../_shared/ejemplos/fotos'
import {
  porIdioma,
  yaMaterializado,
  type PaqueteEjemplo,
  type PorIdioma,
} from '../_shared/ejemplos/tipos'
import { TEXTOS_IDIOMAS } from './ejemplos.data'

/**
 * Ejemplo de fábrica de idiomas: un idioma en A2 con seis tarjetas repartidas
 * por las cajas de Leitner y dos temas del temario.
 *
 * El idioma que se estudia depende del que habla el usuario: con la app en
 * español el ejemplo aprende inglés, y al revés. Las tarjetas no están todas en
 * la misma caja a propósito: así se ve de un vistazo que unas vuelven mañana y
 * otras dentro de dos semanas, que es de lo que va el repaso espaciado.
 */

const ID = 'idiomas.vocabulario'

/**
 * El idioma del ejemplo es siempre «el otro»: el que no habla la interfaz. Sin
 * entrada propia se aprende inglés, que es el respaldo del español.
 */
const OBJETIVO: PorIdioma<{ codigo: string; nombre: string; bandera: string }> = {
  es: { codigo: 'en-US', nombre: 'Inglés', bandera: '🇬🇧' },
  en: { codigo: 'es-ES', nombre: 'Spanish', bandera: '🇪🇸' },
  pt: { codigo: 'en-US', nombre: 'Inglês', bandera: '🇬🇧' },
  fr: { codigo: 'en-US', nombre: 'Anglais', bandera: '🇬🇧' },
  de: { codigo: 'en-US', nombre: 'Englisch', bandera: '🇬🇧' },
  it: { codigo: 'en-US', nombre: 'Inglese', bandera: '🇬🇧' },
  ja: { codigo: 'en-US', nombre: '英語', bandera: '🇬🇧' },
  zh: { codigo: 'en-US', nombre: '英语', bandera: '🇬🇧' },
  ko: { codigo: 'en-US', nombre: '영어', bandera: '🇬🇧' },
  ru: { codigo: 'en-US', nombre: 'Английский', bandera: '🇬🇧' },
  hi: { codigo: 'en-US', nombre: 'अंग्रेज़ी', bandera: '🇬🇧' },
  tr: { codigo: 'en-US', nombre: 'İngilizce', bandera: '🇬🇧' },
  id: { codigo: 'en-US', nombre: 'Bahasa Inggris', bandera: '🇬🇧' },
  pl: { codigo: 'en-US', nombre: 'Angielski', bandera: '🇬🇧' },
  nl: { codigo: 'en-US', nombre: 'Engels', bandera: '🇬🇧' },
  ar: { codigo: 'en-US', nombre: 'الإنجليزية', bandera: '🇬🇧' },
}

/**
 * Los textos de las tarjetas en los idiomas que `ejemplos.data.ts` no trae.
 *
 * Este cuarto queda FUERA del flujo automático de traducción: el término y su
 * frase de ejemplo son lo que se estudia, así que siguen en inglés en los
 * cuatro idiomas; solo viajan la glosa (que va SIEMPRE en el idioma de la
 * interfaz) y los dos temas del temario.
 */
const TEXTOS: PorIdioma<(typeof TEXTOS_IDIOMAS)['es']> = {
  ...TEXTOS_IDIOMAS,
  pt: {
    termino1: 'queue',
    traduccion1: 'a fila',
    ejemplo1: 'There was a long queue at the bakery on Sunday morning.',
    termino2: 'neighbour',
    traduccion2: 'o vizinho, a vizinha',
    ejemplo2: 'My neighbour keeps my keys when I travel.',
    termino3: 'to borrow',
    traduccion3: 'pegar emprestado',
    ejemplo3: 'Can I borrow your umbrella until Friday?',
    termino4: 'never mind',
    traduccion4: 'deixa pra lá, não tem problema',
    ejemplo4: 'The bus has gone? Never mind, we can walk.',
    termino5: 'kettle',
    traduccion5: 'a chaleira elétrica',
    ejemplo5: 'Put the kettle on and I\'ll make us some tea.',
    termino6: 'return ticket',
    traduccion6: 'a passagem de ida e volta',
    ejemplo6: 'One return ticket to Brighton, please.',
    tema1Titulo: 'Passado simples: verbos irregulares',
    tema1Desc: 'Contar o fim de semana com went, saw, ate e perguntar com did you...? sem se perder na ordem.',
    tema2Titulo: 'Comparativos e superlativos',
    tema2Desc: 'Comparar apartamentos, cidades e empregos: cheaper than, more expensive, the best of the three.',
  },
  fr: {
    termino1: 'queue',
    traduccion1: 'la file d’attente',
    ejemplo1: 'There was a long queue at the bakery on Sunday morning.',
    termino2: 'neighbour',
    traduccion2: 'le voisin, la voisine',
    ejemplo2: 'My neighbour keeps my keys when I travel.',
    termino3: 'to borrow',
    traduccion3: 'emprunter',
    ejemplo3: 'Can I borrow your umbrella until Friday?',
    termino4: 'never mind',
    traduccion4: 'tant pis, ce n’est pas grave',
    ejemplo4: 'The bus has gone? Never mind, we can walk.',
    termino5: 'kettle',
    traduccion5: 'la bouilloire',
    ejemplo5: 'Put the kettle on and I\'ll make us some tea.',
    termino6: 'return ticket',
    traduccion6: 'le billet aller-retour',
    ejemplo6: 'One return ticket to Brighton, please.',
    tema1Titulo: 'Prétérit : les verbes irréguliers',
    tema1Desc: 'Raconter ton week-end avec went, saw, ate et questionner avec did you...? sans mélanger l’ordre.',
    tema2Titulo: 'Comparatifs et superlatifs',
    tema2Desc: 'Comparer appartements, villes et boulots : cheaper than, more expensive, the best of the three.',
  },
  de: {
    termino1: 'queue',
    traduccion1: 'die Schlange, die Warteschlange',
    ejemplo1: 'There was a long queue at the bakery on Sunday morning.',
    termino2: 'neighbour',
    traduccion2: 'der Nachbar, die Nachbarin',
    ejemplo2: 'My neighbour keeps my keys when I travel.',
    termino3: 'to borrow',
    traduccion3: 'sich ausleihen',
    ejemplo3: 'Can I borrow your umbrella until Friday?',
    termino4: 'never mind',
    traduccion4: 'macht nichts, schon gut',
    ejemplo4: 'The bus has gone? Never mind, we can walk.',
    termino5: 'kettle',
    traduccion5: 'der Wasserkocher',
    ejemplo5: 'Put the kettle on and I\'ll make us some tea.',
    termino6: 'return ticket',
    traduccion6: 'die Rückfahrkarte',
    ejemplo6: 'One return ticket to Brighton, please.',
    tema1Titulo: 'Simple Past: unregelmäßige Verben',
    tema1Desc:
      'Das Wochenende mit went, saw, ate erzählen und mit did you...? fragen, ohne die Wortfolge zu verdrehen.',
    tema2Titulo: 'Komparativ und Superlativ',
    tema2Desc: 'Wohnungen, Städte und Jobs vergleichen: cheaper than, more expensive, the best of the three.',
  },
  it: {
    termino1: 'queue',
    traduccion1: 'la coda, la fila',
    ejemplo1: 'There was a long queue at the bakery on Sunday morning.',
    termino2: 'neighbour',
    traduccion2: 'il vicino, la vicina',
    ejemplo2: 'My neighbour keeps my keys when I travel.',
    termino3: 'to borrow',
    traduccion3: 'prendere in prestito',
    ejemplo3: 'Can I borrow your umbrella until Friday?',
    termino4: 'never mind',
    traduccion4: 'non fa niente, lascia stare',
    ejemplo4: 'The bus has gone? Never mind, we can walk.',
    termino5: 'kettle',
    traduccion5: 'il bollitore',
    ejemplo5: 'Put the kettle on and I\'ll make us some tea.',
    termino6: 'return ticket',
    traduccion6: 'il biglietto di andata e ritorno',
    ejemplo6: 'One return ticket to Brighton, please.',
    tema1Titulo: 'Past simple: verbi irregolari',
    tema1Desc: 'Raccontare il weekend con went, saw, ate e chiedere con did you...? senza sbagliare l’ordine.',
    tema2Titulo: 'Comparativi e superlativi',
    tema2Desc: 'Confrontare case, città e lavori: cheaper than, more expensive, the best of the three.',
  },
  ja: {
    termino1: 'queue',
    traduccion1: '列、行列',
    ejemplo1: 'There was a long queue at the bakery on Sunday morning.',
    termino2: 'neighbour',
    traduccion2: '隣人',
    ejemplo2: 'My neighbour keeps my keys when I travel.',
    termino3: 'to borrow',
    traduccion3: '借りる',
    ejemplo3: 'Can I borrow your umbrella until Friday?',
    termino4: 'never mind',
    traduccion4: '気にしないで、大丈夫',
    ejemplo4: 'The bus has gone? Never mind, we can walk.',
    termino5: 'kettle',
    traduccion5: 'やかん、電気ケトル',
    ejemplo5: 'Put the kettle on and I\'ll make us some tea.',
    termino6: 'return ticket',
    traduccion6: '往復切符',
    ejemplo6: 'One return ticket to Brighton, please.',
    tema1Titulo: '過去形:不規則動詞',
    tema1Desc: 'went、saw、ateを使って週末の出来事を話し、did you...?で質問します。語順に迷わないように。',
    tema2Titulo: '比較級と最上級',
    tema2Desc: 'アパート、街、仕事を比べます:cheaper than、more expensive、the best of the three。',
  },
  zh: {
    termino1: 'queue',
    traduccion1: '排队,队伍',
    ejemplo1: 'There was a long queue at the bakery on Sunday morning.',
    termino2: 'neighbour',
    traduccion2: '邻居',
    ejemplo2: 'My neighbour keeps my keys when I travel.',
    termino3: 'to borrow',
    traduccion3: '借',
    ejemplo3: 'Can I borrow your umbrella until Friday?',
    termino4: 'never mind',
    traduccion4: '没关系,不要紧',
    ejemplo4: 'The bus has gone? Never mind, we can walk.',
    termino5: 'kettle',
    traduccion5: '电水壶',
    ejemplo5: 'Put the kettle on and I\'ll make us some tea.',
    termino6: 'return ticket',
    traduccion6: '往返票',
    ejemplo6: 'One return ticket to Brighton, please.',
    tema1Titulo: '一般过去时:不规则动词',
    tema1Desc: '用went、saw、ate讲述周末,用did you...?提问,别搞乱语序。',
    tema2Titulo: '比较级和最高级',
    tema2Desc: '比较公寓、城市和工作:cheaper than、more expensive、the best of the three。',
  },
  ko: {
    termino1: 'queue',
    traduccion1: '줄, 대기줄',
    ejemplo1: 'There was a long queue at the bakery on Sunday morning.',
    termino2: 'neighbour',
    traduccion2: '이웃',
    ejemplo2: 'My neighbour keeps my keys when I travel.',
    termino3: 'to borrow',
    traduccion3: '빌리다',
    ejemplo3: 'Can I borrow your umbrella until Friday?',
    termino4: 'never mind',
    traduccion4: '신경 쓰지 마, 괜찮아',
    ejemplo4: 'The bus has gone? Never mind, we can walk.',
    termino5: 'kettle',
    traduccion5: '전기 주전자',
    ejemplo5: 'Put the kettle on and I\'ll make us some tea.',
    termino6: 'return ticket',
    traduccion6: '왕복표',
    ejemplo6: 'One return ticket to Brighton, please.',
    tema1Titulo: '과거형: 불규칙 동사',
    tema1Desc: 'went, saw, ate로 주말 이야기하고 did you...?로 질문해요. 어순 헷갈리지 않기.',
    tema2Titulo: '비교급과 최상급',
    tema2Desc: '아파트, 도시, 직장 비교하기: cheaper than, more expensive, the best of the three.',
  },
  ru: {
    termino1: 'queue',
    traduccion1: 'очередь',
    ejemplo1: 'There was a long queue at the bakery on Sunday morning.',
    termino2: 'neighbour',
    traduccion2: 'сосед, соседка',
    ejemplo2: 'My neighbour keeps my keys when I travel.',
    termino3: 'to borrow',
    traduccion3: 'одолжить, взять на время',
    ejemplo3: 'Can I borrow your umbrella until Friday?',
    termino4: 'never mind',
    traduccion4: 'неважно, ничего страшного',
    ejemplo4: 'The bus has gone? Never mind, we can walk.',
    termino5: 'kettle',
    traduccion5: 'чайник',
    ejemplo5: 'Put the kettle on and I\'ll make us some tea.',
    termino6: 'return ticket',
    traduccion6: 'билет туда и обратно',
    ejemplo6: 'One return ticket to Brighton, please.',
    tema1Titulo: 'Простое прошедшее время: неправильные глаголы',
    tema1Desc: 'Рассказывать о выходных с went, saw, ate и спрашивать с did you...?, не путаясь в порядке слов.',
    tema2Titulo: 'Сравнительная и превосходная степень',
    tema2Desc: 'Сравнивать квартиры, города и работу: cheaper than, more expensive, the best of the three.',
  },
  hi: {
    termino1: 'queue',
    traduccion1: 'लाइन, कतार',
    ejemplo1: 'There was a long queue at the bakery on Sunday morning.',
    termino2: 'neighbour',
    traduccion2: 'पड़ोसी',
    ejemplo2: 'My neighbour keeps my keys when I travel.',
    termino3: 'to borrow',
    traduccion3: 'उधार लेना',
    ejemplo3: 'Can I borrow your umbrella until Friday?',
    termino4: 'never mind',
    traduccion4: 'कोई बात नहीं, छोड़ो',
    ejemplo4: 'The bus has gone? Never mind, we can walk.',
    termino5: 'kettle',
    traduccion5: 'केतली',
    ejemplo5: 'Put the kettle on and I\'ll make us some tea.',
    termino6: 'return ticket',
    traduccion6: 'आने-जाने का टिकट',
    ejemplo6: 'One return ticket to Brighton, please.',
    tema1Titulo: 'सामान्य भूतकाल: अनियमित क्रियाएँ',
    tema1Desc: 'went, saw, ate से वीकेंड के बारे में बताना और did you...? से पूछना, बिना क्रम गड़बड़ाए।',
    tema2Titulo: 'तुलनात्मक और सर्वोत्तम रूप',
    tema2Desc: 'फ़्लैट, शहर और नौकरियों की तुलना करना: cheaper than, more expensive, the best of the three.',
  },
  tr: {
    termino1: 'queue',
    traduccion1: 'sıra, kuyruk',
    ejemplo1: 'There was a long queue at the bakery on Sunday morning.',
    termino2: 'neighbour',
    traduccion2: 'komşu',
    ejemplo2: 'My neighbour keeps my keys when I travel.',
    termino3: 'to borrow',
    traduccion3: 'ödünç almak',
    ejemplo3: 'Can I borrow your umbrella until Friday?',
    termino4: 'never mind',
    traduccion4: 'boş ver, önemli değil',
    ejemplo4: 'The bus has gone? Never mind, we can walk.',
    termino5: 'kettle',
    traduccion5: 'su ısıtıcısı',
    ejemplo5: 'Put the kettle on and I\'ll make us some tea.',
    termino6: 'return ticket',
    traduccion6: 'gidiş-dönüş bilet',
    ejemplo6: 'One return ticket to Brighton, please.',
    tema1Titulo: 'Geçmiş zaman: düzensiz fiiller',
    tema1Desc: 'went, saw, ate ile hafta sonunu anlatmak ve did you...? ile soru sormak, sırayı karıştırmadan.',
    tema2Titulo: 'Karşılaştırma ve üstünlük dereceleri',
    tema2Desc: 'Daireleri, şehirleri ve işleri karşılaştırmak: cheaper than, more expensive, the best of the three.',
  },
  id: {
    termino1: 'queue',
    traduccion1: 'antrean',
    ejemplo1: 'There was a long queue at the bakery on Sunday morning.',
    termino2: 'neighbour',
    traduccion2: 'tetangga',
    ejemplo2: 'My neighbour keeps my keys when I travel.',
    termino3: 'to borrow',
    traduccion3: 'meminjam',
    ejemplo3: 'Can I borrow your umbrella until Friday?',
    termino4: 'never mind',
    traduccion4: 'nggak apa-apa, nggak masalah',
    ejemplo4: 'The bus has gone? Never mind, we can walk.',
    termino5: 'kettle',
    traduccion5: 'ketel, teko listrik',
    ejemplo5: 'Put the kettle on and I\'ll make us some tea.',
    termino6: 'return ticket',
    traduccion6: 'tiket pulang-pergi',
    ejemplo6: 'One return ticket to Brighton, please.',
    tema1Titulo: 'Past simple: kata kerja tidak beraturan',
    tema1Desc: 'Cerita akhir pekan pakai went, saw, ate dan bertanya dengan did you...? tanpa bingung urutannya.',
    tema2Titulo: 'Comparative dan superlative',
    tema2Desc: 'Membandingkan apartemen, kota, dan pekerjaan: cheaper than, more expensive, the best of the three.',
  },
  pl: {
    termino1: 'queue',
    traduccion1: 'kolejka',
    ejemplo1: 'There was a long queue at the bakery on Sunday morning.',
    termino2: 'neighbour',
    traduccion2: 'sąsiad, sąsiadka',
    ejemplo2: 'My neighbour keeps my keys when I travel.',
    termino3: 'to borrow',
    traduccion3: 'pożyczyć (od kogoś)',
    ejemplo3: 'Can I borrow your umbrella until Friday?',
    termino4: 'never mind',
    traduccion4: 'nieważne, nic się nie stało',
    ejemplo4: 'The bus has gone? Never mind, we can walk.',
    termino5: 'kettle',
    traduccion5: 'czajnik elektryczny',
    ejemplo5: 'Put the kettle on and I\'ll make us some tea.',
    termino6: 'return ticket',
    traduccion6: 'bilet powrotny',
    ejemplo6: 'One return ticket to Brighton, please.',
    tema1Titulo: 'Czas przeszły: czasowniki nieregularne',
    tema1Desc: 'Opowiadanie o weekendzie z went, saw, ate i pytanie did you...?, bez mylenia szyku.',
    tema2Titulo: 'Stopień wyższy i najwyższy',
    tema2Desc: 'Porównywanie mieszkań, miast i pracy: cheaper than, more expensive, the best of the three.',
  },
  ar: {
    termino1: 'queue',
    traduccion1: 'الطابور، الصف',
    ejemplo1: 'There was a long queue at the bakery on Sunday morning.',
    termino2: 'neighbour',
    traduccion2: 'الجار، الجارة',
    ejemplo2: 'My neighbour keeps my keys when I travel.',
    termino3: 'to borrow',
    traduccion3: 'يستعير',
    ejemplo3: 'Can I borrow your umbrella until Friday?',
    termino4: 'never mind',
    traduccion4: 'لا بأس، لا يهم',
    ejemplo4: 'The bus has gone? Never mind, we can walk.',
    termino5: 'kettle',
    traduccion5: 'غلاية الماء الكهربائية',
    ejemplo5: 'Put the kettle on and I\'ll make us some tea.',
    termino6: 'return ticket',
    traduccion6: 'تذكرة ذهاب وإياب',
    ejemplo6: 'One return ticket to Brighton, please.',
    tema1Titulo: 'الماضي البسيط: الأفعال الشاذة',
    tema1Desc: 'سرد نهاية الأسبوع باستخدام went وsaw وate، والسؤال بـ did you...? دون تشويش الترتيب.',
    tema2Titulo: 'صيغتا التفضيل والتفوق',
    tema2Desc: 'مقارنة الشقق والمدن والوظائف: cheaper than وmore expensive وthe best of the three.',
  },
  nl: {
    termino1: 'queue',
    traduccion1: 'de rij',
    ejemplo1: 'There was a long queue at the bakery on Sunday morning.',
    termino2: 'neighbour',
    traduccion2: 'de buur, de buurvrouw',
    ejemplo2: 'My neighbour keeps my keys when I travel.',
    termino3: 'to borrow',
    traduccion3: 'lenen (van iemand)',
    ejemplo3: 'Can I borrow your umbrella until Friday?',
    termino4: 'never mind',
    traduccion4: 'laat maar, geeft niet',
    ejemplo4: 'The bus has gone? Never mind, we can walk.',
    termino5: 'kettle',
    traduccion5: 'de waterkoker',
    ejemplo5: 'Put the kettle on and I\'ll make us some tea.',
    termino6: 'return ticket',
    traduccion6: 'het retourtje',
    ejemplo6: 'One return ticket to Brighton, please.',
    tema1Titulo: 'Simple past: onregelmatige werkwoorden',
    tema1Desc: 'Het weekend vertellen met went, saw, ate en vragen met did you...?, zonder de volgorde te verwarren.',
    tema2Titulo: 'Vergrotende en overtreffende trap',
    tema2Desc: 'Appartementen, steden en banen vergelijken: cheaper than, more expensive, the best of the three.',
  },
}

/** Caja Leitner y cuándo vuelve cada tarjeta (negativo = vencida, toca repasarla). */
const TARJETAS: { n: 1 | 2 | 3 | 4 | 5 | 6; tipo: 'palabra' | 'frase' | 'expresion'; caja: number; proxima: number }[] =
  [
    { n: 1, tipo: 'palabra', caja: 3, proxima: 4 },
    { n: 2, tipo: 'palabra', caja: 1, proxima: -1 },
    { n: 3, tipo: 'palabra', caja: 2, proxima: 0 },
    { n: 4, tipo: 'expresion', caja: 0, proxima: -2 },
    { n: 5, tipo: 'palabra', caja: 5, proxima: 16 },
    { n: 6, tipo: 'frase', caja: 1, proxima: 1 },
  ]

export const ejemploIdiomas: PaqueteEjemplo = {
  id: ID,
  async materializar() {
    if (await yaMaterializado(ID, () => idiomasRepo.list())) return
    const T = porIdioma(TEXTOS)
    const lengua = porIdioma(OBJETIVO)
    const hoy = fechaLocalISO()
    const creado = `${isoMasDias(hoy, -21)}T10:00:00.000Z`

    const idiomaId = await idiomasRepo.add({ ...lengua, nivel: 'A2', creadoEn: creado, ejemploDe: ID })

    // Dos temas propios colgando del nivel A2 del temario. Van ANTES que las
    // tarjetas porque cada tarjeta nace ya clasificada en uno de ellos: el
    // vocabulario vive dentro del temario.
    const tema1 = `din-ej-${idiomaId}-1`
    const tema2 = `din-ej-${idiomaId}-2`
    await temasIdiomaRepo.add({
      temaId: tema1,
      idiomaId,
      nivel: 'A2',
      area: 'temas',
      padreId: null,
      titulo: T.tema1Titulo,
      descripcion: T.tema1Desc,
      creadoEn: creado,
      ejemploDe: ID,
    })
    await temasIdiomaRepo.add({
      temaId: tema2,
      idiomaId,
      nivel: 'A2',
      area: 'temas',
      padreId: null,
      titulo: T.tema2Titulo,
      descripcion: T.tema2Desc,
      creadoEn: creado,
      ejemploDe: ID,
    })

    const imagen = await fotoEjemplo('idiomas.tarjeta')
    for (const t of TARJETAS) {
      await tarjetasIdiomaRepo.add({
        idiomaId,
        termino: T[`termino${t.n}`],
        traduccion: T[`traduccion${t.n}`],
        ejemplo: T[`ejemplo${t.n}`],
        // La imagen mnemotécnica solo en una: es un extra, no la norma.
        imagen: t.n === 5 ? imagen : undefined,
        tipo: t.tipo,
        temaId: t.n <= 3 ? tema1 : tema2,
        nivel: 'A2',
        caja: t.caja,
        proximaISO: isoMasDias(hoy, t.proxima),
        ultimaISO: isoMasDias(hoy, -3),
        fuente: 'manual',
        creadoEn: creado,
        ejemploDe: ID,
      })
    }

  },
}
