// Generado por `npm run ejemplos:texto` — no lo edites a mano.
// Contenido del ejemplo de fábrica de idiomas, en los dos idiomas. Vive aparte
// de `dict.ts` a propósito: en cuanto se crea es dato del usuario, no interfaz.

export const TEXTOS_IDIOMAS = {
  es: {
    termino1: 'queue',
    traduccion1: 'cola, fila',
    ejemplo1: 'There was a long queue at the bakery on Sunday morning.',
    termino2: 'neighbour',
    traduccion2: 'vecino, vecina',
    ejemplo2: 'My neighbour keeps my keys when I travel.',
    termino3: 'to borrow',
    traduccion3: 'pedir prestado',
    ejemplo3: 'Can I borrow your umbrella until Friday?',
    termino4: 'never mind',
    traduccion4: 'da igual, no importa',
    ejemplo4: 'The bus has gone? Never mind, we can walk.',
    termino5: 'kettle',
    traduccion5: 'hervidor de agua',
    ejemplo5: 'Put the kettle on and I\'ll make us some tea.',
    termino6: 'return ticket',
    traduccion6: 'billete de ida y vuelta',
    ejemplo6: 'One return ticket to Brighton, please.',
    tema1Titulo: 'Pasado simple: verbos irregulares',
    tema1Desc: 'Contar el fin de semana con went, saw, ate y preguntar con did you...? sin liarte con el orden.',
    tema2Titulo: 'Comparativos y superlativos',
    tema2Desc: 'Comparar pisos, ciudades y trabajos: cheaper than, more expensive, the best of the three.',
  },
  en: {
    termino1: 'la cola',
    traduccion1: 'the queue, the line',
    ejemplo1: 'Había una cola larga en la panadería el domingo.',
    termino2: 'el vecino',
    traduccion2: 'the neighbour',
    ejemplo2: 'Mi vecino me guarda las llaves cuando viajo.',
    termino3: 'prestar',
    traduccion3: 'to lend',
    ejemplo3: '¿Me prestas tu paraguas hasta el viernes?',
    termino4: 'no pasa nada',
    traduccion4: 'it\'s fine, no worries',
    ejemplo4: 'Se ha ido el autobús, no pasa nada, vamos andando.',
    termino5: 'la sartén',
    traduccion5: 'the frying pan',
    ejemplo5: 'Pon la sartén al fuego, que hago una tortilla.',
    termino6: 'billete de ida y vuelta',
    traduccion6: 'return ticket',
    ejemplo6: 'Un billete de ida y vuelta a Sevilla, por favor.',
    tema1Titulo: 'Pretérito indefinido: irregulares',
    tema1Desc: 'Contar el fin de semana con fui, vi y comí, y preguntar ¿qué hiciste el sábado? sin dudar.',
    tema2Titulo: 'Comparativos y superlativos',
    tema2Desc: 'Comparar pisos, ciudades y trabajos: más barato que, mejor que, el más grande de los tres.',
  },
}
