import type {
  AreaAgenda,
  ContactoAgenda,
  EventoAgenda,
  Mascota,
  Medicamento,
} from '../../core/data/db'
import { fechaLocalISO, isoMasDias } from '../../core/fechaLocal'
import { porIdioma, type PorIdioma } from '../_shared/ejemplos/tipos'
import {
  borrarContacto,
  borrarEvento,
  borrarMascota,
  borrarMedicamento,
  guardarContacto,
  guardarCuidado,
  guardarEvento,
  guardarMascota,
  guardarMedicamento,
} from './crear'
import { nuevoId } from './ids'

/**
 * Ejemplo de fábrica de cada sección de la agenda.
 *
 * Se carga y se borra ENTERO desde la propia sección, y pasa por las mismas
 * altas y bajas que el usuario (`guardarEvento`, `borrarContacto`…): así el
 * ejemplo proyecta sus bloques al calendario igual que lo haría a mano, y al
 * borrarlo se los lleva consigo en vez de dejarlos huérfanos.
 *
 * Las fechas son RELATIVAS a hoy: un ejemplo fechado en el pasado no se ve en
 * el calendario y no enseña nada. El contenido va en los dos idiomas (es dato
 * del usuario en cuanto se crea, no interfaz: por eso no está en `dict.ts`).
 */

type Clave =
  | 'contrato'
  | 'textos'
  | 'hosting'
  | 'junta'
  | 'oficina'
  | 'cliente'
  | 'limpieza'
  | 'clinica'
  | 'doctora'
  | 'vitamina'
  | 'dosis'
  | 'ana'
  | 'amigos'
  | 'luis'
  | 'trabajo'
  | 'cafe'
  | 'cafeteria'
  | 'perro'
  | 'raza'
  | 'vacuna'
  | 'desparasitar'
  | 'veterinaria'
  | 'cotizacion'
  | 'dominio'
  | 'notaDominio'
  | 'maqueta'
  | 'antibiotico'
  | 'capsula'
  | 'analisis'
  | 'laboratorio'
  | 'gotas'
  | 'dosisGotas'
  | 'bano'
  | 'carmen'
  | 'familia'
  | 'direccion'
  | 'notasCarmen'
  | 'cena'

const TEXTOS: PorIdioma<Record<Clave, string>> = {
  es: {
    contrato: 'Firmar el contrato',
    textos: 'Escribir los textos',
    hosting: 'Cotizar el hosting',
    junta: 'Junta de arranque',
    oficina: 'Oficina',
    cliente: 'Marta (cliente)',
    limpieza: 'Limpieza dental',
    clinica: 'Clínica del centro',
    doctora: 'Dra. Ruiz',
    vitamina: 'Vitamina D',
    dosis: '1 pastilla',
    ana: 'Ana Torres',
    amigos: 'Amigos',
    luis: 'Luis Pérez',
    trabajo: 'Trabajo',
    cafe: 'Café con Ana',
    cafeteria: 'La cafetería de siempre',
    perro: 'Kira',
    raza: 'Labrador',
    vacuna: 'Vacuna anual',
    desparasitar: 'Desparasitación',
    veterinaria: 'Veterinaria del parque',
    cotizacion: 'Pedir cotización a la mudanza',
    dominio: 'Renovar el dominio',
    notaDominio: 'Ojo: la renovación automática está apagada.',
    maqueta: 'Entregar la maqueta',
    antibiotico: 'Antibiótico',
    capsula: '1 cápsula',
    analisis: 'Análisis de sangre',
    laboratorio: 'Laboratorio de la esquina',
    gotas: 'Gotas para el oído',
    dosisGotas: '3 gotas',
    bano: 'Baño',
    carmen: 'Carmen Ruiz',
    familia: 'Familia',
    direccion: 'Av. de los Olivos 42',
    notasCarmen: 'No le gusta el cilantro. Le encantan las plantas.',
    cena: 'Cena de cumpleaños',
  },
  en: {
    contrato: 'Sign the contract',
    textos: 'Write the copy',
    hosting: 'Get a hosting quote',
    junta: 'Kick-off meeting',
    oficina: 'The office',
    cliente: 'Marta (client)',
    limpieza: 'Dental cleaning',
    clinica: 'Clinic downtown',
    doctora: 'Dr. Ruiz',
    vitamina: 'Vitamin D',
    dosis: '1 pill',
    ana: 'Ana Torres',
    amigos: 'Friends',
    luis: 'Luis Pérez',
    trabajo: 'Work',
    cafe: 'Coffee with Ana',
    cafeteria: 'The usual coffee shop',
    perro: 'Kira',
    raza: 'Labrador',
    vacuna: 'Yearly shot',
    desparasitar: 'Deworming',
    veterinaria: 'The vet by the park',
    cotizacion: 'Ask the movers for a quote',
    dominio: 'Renew the domain',
    notaDominio: 'Heads up: auto-renewal is off.',
    maqueta: 'Hand in the mockup',
    antibiotico: 'Antibiotic',
    capsula: '1 capsule',
    analisis: 'Blood test',
    laboratorio: 'The lab around the corner',
    gotas: 'Ear drops',
    dosisGotas: '3 drops',
    bano: 'Bath',
    carmen: 'Carmen Ruiz',
    familia: 'Family',
    direccion: '42 Olive Avenue',
    notasCarmen: 'Hates cilantro. Loves plants.',
    cena: 'Birthday dinner',
  },
  pt: {
    contrato: 'Assinar o contrato',
    textos: 'Escrever os textos',
    hosting: 'Cotar a hospedagem',
    junta: 'Reunião de início',
    oficina: 'O escritório',
    cliente: 'Marta (cliente)',
    limpieza: 'Limpeza dental',
    clinica: 'Clínica do centro',
    doctora: 'Dra. Ruiz',
    vitamina: 'Vitamina D',
    dosis: '1 comprimido',
    ana: 'Ana Torres',
    amigos: 'Amigos',
    luis: 'Luis Pérez',
    trabajo: 'Trabalho',
    cafe: 'Café com Ana',
    cafeteria: 'O café de sempre',
    perro: 'Kira',
    raza: 'Labrador',
    vacuna: 'Vacina anual',
    desparasitar: 'Vermifugação',
    veterinaria: 'Veterinária do parque',
    cotizacion: 'Pedir orçamento da mudança',
    dominio: 'Renovar o domínio',
    notaDominio: 'Atenção: a renovação automática está desativada.',
    maqueta: 'Entregar o protótipo',
    antibiotico: 'Antibiótico',
    capsula: '1 cápsula',
    analisis: 'Exame de sangue',
    laboratorio: 'Laboratório da esquina',
    gotas: 'Gotas para o ouvido',
    dosisGotas: '3 gotas',
    bano: 'Banho',
    carmen: 'Carmen Ruiz',
    familia: 'Família',
    direccion: 'Av. das Oliveiras, 42',
    notasCarmen: 'Não gosta de coentro. Adora plantas.',
    cena: 'Jantar de aniversário',
  },
  fr: {
    contrato: 'Signer le contrat',
    textos: 'Rédiger les textes',
    hosting: "Demander un devis pour l'hébergement",
    junta: 'Réunion de lancement',
    oficina: 'Le bureau',
    cliente: 'Marta (cliente)',
    limpieza: 'Nettoyage dentaire',
    clinica: 'Clinique du centre-ville',
    doctora: 'Dr Ruiz',
    vitamina: 'Vitamine D',
    dosis: '1 comprimé',
    ana: 'Ana Torres',
    amigos: 'Amis',
    luis: 'Luis Pérez',
    trabajo: 'Travail',
    cafe: 'Café avec Ana',
    cafeteria: 'Le café habituel',
    perro: 'Kira',
    raza: 'Labrador',
    vacuna: 'Vaccin annuel',
    desparasitar: 'Vermifuge',
    veterinaria: 'Vétérinaire du parc',
    cotizacion: 'Demander un devis de déménagement',
    dominio: 'Renouveler le nom de domaine',
    notaDominio: 'Attention : le renouvellement automatique est désactivé.',
    maqueta: 'Livrer la maquette',
    antibiotico: 'Antibiotique',
    capsula: '1 gélule',
    analisis: 'Analyse de sang',
    laboratorio: 'Laboratoire du coin',
    gotas: 'Gouttes auriculaires',
    dosisGotas: '3 gouttes',
    bano: 'Bain',
    carmen: 'Carmen Ruiz',
    familia: 'Famille',
    direccion: 'Avenue des Oliviers 42',
    notasCarmen: "N'aime pas la coriandre. Adore les plantes.",
    cena: "Dîner d'anniversaire",
  },
  de: {
    contrato: 'Vertrag unterschreiben',
    textos: 'Texte schreiben',
    hosting: 'Hosting-Angebot einholen',
    junta: 'Auftaktbesprechung',
    oficina: 'Das Büro',
    cliente: 'Marta (Kundin)',
    limpieza: 'Zahnreinigung',
    clinica: 'Klinik in der Innenstadt',
    doctora: 'Dr. Ruiz',
    vitamina: 'Vitamin D',
    dosis: '1 Tablette',
    ana: 'Ana Torres',
    amigos: 'Freunde',
    luis: 'Luis Pérez',
    trabajo: 'Arbeit',
    cafe: 'Kaffee mit Ana',
    cafeteria: 'Das gewohnte Café',
    perro: 'Kira',
    raza: 'Labrador',
    vacuna: 'Jährliche Impfung',
    desparasitar: 'Entwurmung',
    veterinaria: 'Tierarztpraxis am Park',
    cotizacion: 'Angebot für den Umzug einholen',
    dominio: 'Domain verlängern',
    notaDominio: 'Achtung: Die automatische Verlängerung ist deaktiviert.',
    maqueta: 'Mockup liefern',
    antibiotico: 'Antibiotikum',
    capsula: '1 Kapsel',
    analisis: 'Blutuntersuchung',
    laboratorio: 'Labor um die Ecke',
    gotas: 'Ohrentropfen',
    dosisGotas: '3 Tropfen',
    bano: 'Baden',
    carmen: 'Carmen Ruiz',
    familia: 'Familie',
    direccion: 'Olivenallee 42',
    notasCarmen: 'Mag keinen Koriander. Liebt Pflanzen.',
    cena: 'Geburtstagsessen',
  },
  it: {
    contrato: 'Firmare il contratto',
    textos: 'Scrivere i testi',
    hosting: "Richiedere un preventivo per l'hosting",
    junta: 'Riunione di avvio',
    oficina: "L'ufficio",
    cliente: 'Marta (cliente)',
    limpieza: 'Pulizia dentale',
    clinica: 'Clinica del centro',
    doctora: 'Dott.ssa Ruiz',
    vitamina: 'Vitamina D',
    dosis: '1 compressa',
    ana: 'Ana Torres',
    amigos: 'Amici',
    luis: 'Luis Pérez',
    trabajo: 'Lavoro',
    cafe: 'Caffè con Ana',
    cafeteria: 'Il solito bar',
    perro: 'Kira',
    raza: 'Labrador',
    vacuna: 'Vaccino annuale',
    desparasitar: 'Sverminazione',
    veterinaria: 'Veterinaria del parco',
    cotizacion: 'Chiedere un preventivo per il trasloco',
    dominio: 'Rinnovare il dominio',
    notaDominio: 'Attenzione: il rinnovo automatico è disattivato.',
    maqueta: 'Consegnare il mockup',
    antibiotico: 'Antibiotico',
    capsula: '1 capsula',
    analisis: 'Analisi del sangue',
    laboratorio: "Laboratorio dietro l'angolo",
    gotas: 'Gocce per le orecchie',
    dosisGotas: '3 gocce',
    bano: 'Bagno',
    carmen: 'Carmen Ruiz',
    familia: 'Famiglia',
    direccion: 'Via degli Ulivi 42',
    notasCarmen: 'Non le piace il coriandolo. Adora le piante.',
    cena: 'Cena di compleanno',
  },
  ja: {
    contrato: '契約書にサインする',
    textos: '原稿を書く',
    hosting: 'ホスティングの見積もりを取る',
    junta: 'キックオフミーティング',
    oficina: 'オフィス',
    cliente: 'マルタ(クライアント)',
    limpieza: '歯のクリーニング',
    clinica: '中心街のクリニック',
    doctora: 'ルイス先生',
    vitamina: 'ビタミンD',
    dosis: '1錠',
    ana: 'アナ・トーレス',
    amigos: '友人',
    luis: 'ルイス・ペレス',
    trabajo: '仕事',
    cafe: 'アナとコーヒー',
    cafeteria: 'いつものカフェ',
    perro: 'キラ',
    raza: 'ラブラドール',
    vacuna: '年に一度のワクチン',
    desparasitar: '駆虫',
    veterinaria: '公園そばの動物病院',
    cotizacion: '引っ越し業者に見積もりを頼む',
    dominio: 'ドメインを更新する',
    notaDominio: '注意:自動更新はオフになっています。',
    maqueta: 'モックアップを納品する',
    antibiotico: '抗生物質',
    capsula: 'カプセル1錠',
    analisis: '血液検査',
    laboratorio: '角の検査ラボ',
    gotas: '耳の点耳薬',
    dosisGotas: '3滴',
    bano: 'シャンプー',
    carmen: 'カルメン・ルイス',
    familia: '家族',
    direccion: 'オリボス通り42番地',
    notasCarmen: 'パクチーが苦手です。植物が大好きです。',
    cena: '誕生日ディナー',
  },
  zh: {
    contrato: '签合同',
    textos: '写文案',
    hosting: '询价虚拟主机',
    junta: '启动会议',
    oficina: '办公室',
    cliente: '玛尔塔(客户)',
    limpieza: '洗牙',
    clinica: '市中心诊所',
    doctora: '鲁伊斯医生',
    vitamina: '维生素D',
    dosis: '1片',
    ana: '安娜·托雷斯',
    amigos: '朋友',
    luis: '路易斯·佩雷斯',
    trabajo: '工作',
    cafe: '和安娜喝咖啡',
    cafeteria: '老地方那家咖啡馆',
    perro: '基拉',
    raza: '拉布拉多',
    vacuna: '年度疫苗',
    desparasitar: '驱虫',
    veterinaria: '公园旁的宠物医院',
    cotizacion: '向搬家公司询价',
    dominio: '续费域名',
    notaDominio: '注意:自动续费已关闭。',
    maqueta: '交付原型图',
    antibiotico: '抗生素',
    capsula: '1粒胶囊',
    analisis: '验血',
    laboratorio: '街角的化验所',
    gotas: '滴耳液',
    dosisGotas: '3滴',
    bano: '洗澡',
    carmen: '卡门·鲁伊斯',
    familia: '家人',
    direccion: '橄榄树大道42号',
    notasCarmen: '不喜欢香菜,很喜欢植物。',
    cena: '生日晚餐',
  },
  ko: {
    contrato: '계약서에 서명하기',
    textos: '카피 작성하기',
    hosting: '호스팅 견적 받기',
    junta: '킥오프 미팅',
    oficina: '사무실',
    cliente: '마르타(고객)',
    limpieza: '스케일링',
    clinica: '시내 클리닉',
    doctora: '루이스 선생님',
    vitamina: '비타민 D',
    dosis: '1알',
    ana: '아나 토레스',
    amigos: '친구',
    luis: '루이스 페레스',
    trabajo: '직장',
    cafe: '아나와 커피',
    cafeteria: '늘 가던 카페',
    perro: '키라',
    raza: '래브라도',
    vacuna: '연례 백신',
    desparasitar: '구충',
    veterinaria: '공원 근처 동물병원',
    cotizacion: '이사 업체에 견적 요청하기',
    dominio: '도메인 갱신하기',
    notaDominio: '주의: 자동 갱신이 꺼져 있어요.',
    maqueta: '목업 전달하기',
    antibiotico: '항생제',
    capsula: '캡슐 1개',
    analisis: '혈액 검사',
    laboratorio: '모퉁이 검사실',
    gotas: '귀 물약',
    dosisGotas: '3방울',
    bano: '목욕',
    carmen: '카르멘 루이스',
    familia: '가족',
    direccion: '올리보스 거리 42번지',
    notasCarmen: '고수를 안 좋아해요. 식물을 정말 좋아해요.',
    cena: '생일 저녁 식사',
  },
  ru: {
    contrato: 'Подписать договор',
    textos: 'Написать тексты',
    hosting: 'Запросить смету на хостинг',
    junta: 'Стартовая встреча',
    oficina: 'Офис',
    cliente: 'Марта (клиент)',
    limpieza: 'Чистка зубов',
    clinica: 'Клиника в центре',
    doctora: 'Врач Руис',
    vitamina: 'Витамин D',
    dosis: '1 таблетка',
    ana: 'Анна Торрес',
    amigos: 'Друзья',
    luis: 'Луис Перес',
    trabajo: 'Работа',
    cafe: 'Кофе с Анной',
    cafeteria: 'Обычная кофейня',
    perro: 'Кира',
    raza: 'Лабрадор',
    vacuna: 'Ежегодная прививка',
    desparasitar: 'Обработка от паразитов',
    veterinaria: 'Ветклиника у парка',
    cotizacion: 'Запросить смету у грузчиков',
    dominio: 'Продлить домен',
    notaDominio: 'Важно: автопродление отключено.',
    maqueta: 'Сдать макет',
    antibiotico: 'Антибиотик',
    capsula: '1 капсула',
    analisis: 'Анализ крови',
    laboratorio: 'Лаборатория за углом',
    gotas: 'Ушные капли',
    dosisGotas: '3 капли',
    bano: 'Купание',
    carmen: 'Кармен Руис',
    familia: 'Семья',
    direccion: 'Аллея Олив, 42',
    notasCarmen: 'Не любит кинзу. Обожает растения.',
    cena: 'Праздничный ужин',
  },
  hi: {
    contrato: 'कॉन्ट्रैक्ट पर हस्ताक्षर करना',
    textos: 'टेक्स्ट लिखना',
    hosting: 'होस्टिंग का कोटेशन लेना',
    junta: 'किक-ऑफ़ मीटिंग',
    oficina: 'ऑफ़िस',
    cliente: 'मार्टा (क्लाइंट)',
    limpieza: 'डेंटल क्लीनिंग',
    clinica: 'शहर के बीच वाला क्लिनिक',
    doctora: 'डॉ. रुइज़',
    vitamina: 'विटामिन डी',
    dosis: '1 गोली',
    ana: 'आना तोरेस',
    amigos: 'दोस्त',
    luis: 'लुइस पेरेज़',
    trabajo: 'काम',
    cafe: 'आना के साथ कॉफ़ी',
    cafeteria: 'हमेशा वाली कैफ़े',
    perro: 'किरा',
    raza: 'लैब्राडोर',
    vacuna: 'सालाना वैक्सीन',
    desparasitar: 'डीवर्मिंग',
    veterinaria: 'पार्क वाला वेटरनरी क्लिनिक',
    cotizacion: 'मूवर्स से कोटेशन माँगना',
    dominio: 'डोमेन रिन्यू करना',
    notaDominio: 'ध्यान दें: ऑटो-रिन्यूअल बंद है।',
    maqueta: 'मॉकअप सौंपना',
    antibiotico: 'एंटीबायोटिक',
    capsula: '1 कैप्सूल',
    analisis: 'ब्लड टेस्ट',
    laboratorio: 'कोने वाली लैब',
    gotas: 'कान की बूँदें',
    dosisGotas: '3 बूँदें',
    bano: 'नहलाना',
    carmen: 'कारमेन रुइज़',
    familia: 'परिवार',
    direccion: 'एवेनिदा दे लॉस ओलिवोस 42',
    notasCarmen: 'धनिया पसंद नहीं है। पौधों से बहुत प्यार है।',
    cena: 'बर्थडे डिनर',
  },
  tr: {
    contrato: 'Sözleşmeyi imzalamak',
    textos: 'Metinleri yazmak',
    hosting: 'Hosting için teklif almak',
    junta: 'Başlangıç toplantısı',
    oficina: 'Ofis',
    cliente: 'Marta (müşteri)',
    limpieza: 'Diş temizliği',
    clinica: 'Şehir merkezindeki klinik',
    doctora: 'Dr. Ruiz',
    vitamina: 'D Vitamini',
    dosis: '1 tablet',
    ana: 'Ana Torres',
    amigos: 'Arkadaşlar',
    luis: 'Luis Pérez',
    trabajo: 'İş',
    cafe: 'Ana ile kahve',
    cafeteria: 'Her zamanki kafe',
    perro: 'Kira',
    raza: 'Labrador',
    vacuna: 'Yıllık aşı',
    desparasitar: 'İç ve dış parazit tedavisi',
    veterinaria: 'Parktaki veteriner',
    cotizacion: 'Nakliyeden teklif istemek',
    dominio: 'Alan adını yenilemek',
    notaDominio: 'Dikkat: otomatik yenileme kapalı.',
    maqueta: 'Maketi teslim etmek',
    antibiotico: 'Antibiyotik',
    capsula: '1 kapsül',
    analisis: 'Kan tahlili',
    laboratorio: 'Köşedeki laboratuvar',
    gotas: 'Kulak damlası',
    dosisGotas: '3 damla',
    bano: 'Banyo',
    carmen: 'Carmen Ruiz',
    familia: 'Aile',
    direccion: 'Zeytinlik Caddesi 42',
    notasCarmen: 'Kişniş sevmiyor. Bitkilere bayılıyor.',
    cena: 'Doğum günü yemeği',
  },
  id: {
    contrato: 'Menandatangani kontrak',
    textos: 'Menulis naskah',
    hosting: 'Minta penawaran hosting',
    junta: 'Rapat kick-off',
    oficina: 'Kantor',
    cliente: 'Marta (klien)',
    limpieza: 'Pembersihan gigi',
    clinica: 'Klinik di pusat kota',
    doctora: 'dr. Ruiz',
    vitamina: 'Vitamin D',
    dosis: '1 tablet',
    ana: 'Ana Torres',
    amigos: 'Teman-teman',
    luis: 'Luis Pérez',
    trabajo: 'Kerja',
    cafe: 'Ngopi sama Ana',
    cafeteria: 'Kafe langganan',
    perro: 'Kira',
    raza: 'Labrador',
    vacuna: 'Vaksin tahunan',
    desparasitar: 'Obat cacing',
    veterinaria: 'Dokter hewan dekat taman',
    cotizacion: 'Minta penawaran jasa pindahan',
    dominio: 'Perpanjang domain',
    notaDominio: 'Ingat: perpanjangan otomatis dimatikan.',
    maqueta: 'Menyerahkan mockup',
    antibiotico: 'Antibiotik',
    capsula: '1 kapsul',
    analisis: 'Tes darah',
    laboratorio: 'Lab di ujung jalan',
    gotas: 'Obat tetes telinga',
    dosisGotas: '3 tetes',
    bano: 'Mandi',
    carmen: 'Carmen Ruiz',
    familia: 'Keluarga',
    direccion: 'Jl. Zaitun No. 42',
    notasCarmen: 'Nggak suka ketumbar. Suka banget sama tanaman.',
    cena: 'Makan malam ulang tahun',
  },
  pl: {
    contrato: 'Podpisać umowę',
    textos: 'Napisać teksty',
    hosting: 'Zapytać o wycenę hostingu',
    junta: 'Spotkanie inauguracyjne',
    oficina: 'Biuro',
    cliente: 'Marta (klientka)',
    limpieza: 'Czyszczenie zębów',
    clinica: 'Klinika w centrum',
    doctora: 'Dr Ruiz',
    vitamina: 'Witamina D',
    dosis: '1 tabletka',
    ana: 'Ana Torres',
    amigos: 'Przyjaciele',
    luis: 'Luis Pérez',
    trabajo: 'Praca',
    cafe: 'Kawa z Aną',
    cafeteria: 'Zwykła kawiarnia',
    perro: 'Kira',
    raza: 'Labrador',
    vacuna: 'Coroczna szczepionka',
    desparasitar: 'Odrobaczanie',
    veterinaria: 'Weterynarz przy parku',
    cotizacion: 'Poprosić firmę przeprowadzkową o wycenę',
    dominio: 'Przedłużyć domenę',
    notaDominio: 'Uwaga: automatyczne odnawianie jest wyłączone.',
    maqueta: 'Dostarczyć makietę',
    antibiotico: 'Antybiotyk',
    capsula: '1 kapsułka',
    analisis: 'Badanie krwi',
    laboratorio: 'Laboratorium za rogiem',
    gotas: 'Krople do uszu',
    dosisGotas: '3 krople',
    bano: 'Kąpiel',
    carmen: 'Carmen Ruiz',
    familia: 'Rodzina',
    direccion: 'Aleja Oliwna 42',
    notasCarmen: 'Nie lubi kolendry. Uwielbia rośliny.',
    cena: 'Kolacja urodzinowa',
  },
  ar: {
    contrato: 'توقيع العقد',
    textos: 'كتابة النصوص',
    hosting: 'طلب عرض سعر للاستضافة',
    junta: 'اجتماع الانطلاق',
    oficina: 'المكتب',
    cliente: 'مارتا (عميلة)',
    limpieza: 'تنظيف الأسنان',
    clinica: 'عيادة وسط المدينة',
    doctora: 'د. رويز',
    vitamina: 'فيتامين د',
    dosis: 'قرص واحد',
    ana: 'آنا توريس',
    amigos: 'أصدقاء',
    luis: 'لويس بيريز',
    trabajo: 'العمل',
    cafe: 'قهوة مع آنا',
    cafeteria: 'المقهى المعتاد',
    perro: 'كيرا',
    raza: 'لابرادور',
    vacuna: 'التطعيم السنوي',
    desparasitar: 'إزالة الطفيليات',
    veterinaria: 'العيادة البيطرية بجانب الحديقة',
    cotizacion: 'طلب عرض سعر لشركة النقل',
    dominio: 'تجديد النطاق',
    notaDominio: 'تنبيه: التجديد التلقائي متوقف.',
    maqueta: 'تسليم النموذج الأولي',
    antibiotico: 'مضاد حيوي',
    capsula: 'كبسولة واحدة',
    analisis: 'تحليل الدم',
    laboratorio: 'المختبر في الزاوية',
    gotas: 'قطرة للأذن',
    dosisGotas: '3 قطرات',
    bano: 'الاستحمام',
    carmen: 'كارمن رويز',
    familia: 'العائلة',
    direccion: 'شارع الزيتون 42',
    notasCarmen: 'لا تحب الكزبرة. تحب النباتات كثيرًا.',
    cena: 'عشاء عيد الميلاد',
  },
  nl: {
    contrato: 'Het contract tekenen',
    textos: 'De teksten schrijven',
    hosting: 'Offerte voor hosting opvragen',
    junta: 'Kick-offvergadering',
    oficina: 'Het kantoor',
    cliente: 'Marta (klant)',
    limpieza: 'Gebitsreiniging',
    clinica: 'Kliniek in het centrum',
    doctora: 'Dr. Ruiz',
    vitamina: 'Vitamine D',
    dosis: '1 tablet',
    ana: 'Ana Torres',
    amigos: 'Vrienden',
    luis: 'Luis Pérez',
    trabajo: 'Werk',
    cafe: 'Koffie met Ana',
    cafeteria: 'Het vaste café',
    perro: 'Kira',
    raza: 'Labrador',
    vacuna: 'Jaarlijkse vaccinatie',
    desparasitar: 'Ontworming',
    veterinaria: 'De dierenarts bij het park',
    cotizacion: 'Offerte aanvragen bij de verhuizers',
    dominio: 'Domein verlengen',
    notaDominio: 'Let op: automatisch verlengen staat uit.',
    maqueta: 'De maquette inleveren',
    antibiotico: 'Antibioticum',
    capsula: '1 capsule',
    analisis: 'Bloedonderzoek',
    laboratorio: 'Het lab om de hoek',
    gotas: 'Oordruppels',
    dosisGotas: '3 druppels',
    bano: 'Bad',
    carmen: 'Carmen Ruiz',
    familia: 'Familie',
    direccion: 'Olijflaan 42',
    notasCarmen: 'Houdt niet van koriander. Dol op planten.',
    cena: 'Verjaardagsdiner',
  },
}

/** ¿Esta sección ya tiene su ejemplo cargado? */
export const hayEjemplo = (
  area: AreaAgenda,
  eventos: EventoAgenda[],
  contactos: ContactoAgenda[],
  medicinas: Medicamento[],
  mascotas: Mascota[] = [],
): boolean =>
  eventos.some((e) => e.ejemplo && e.area === area) ||
  (area === 'salud' && (medicinas.some((m) => m.ejemplo) || mascotas.some((m) => m.ejemplo))) ||
  (area === 'personas' && contactos.some((c) => c.ejemplo))

/** Carga el ejemplo de una sección. Las fechas cuelgan de hoy. */
export async function cargarEjemplo(area: AreaAgenda): Promise<void> {
  const T = porIdioma(TEXTOS)
  const hoy = fechaLocalISO()
  const enDias = (n: number) => isoMasDias(hoy, n)

  if (area === 'trabajo') {
    const base = { area: 'trabajo' as const, ejemplo: true }
    // Uno por columna del tablero: por hacer, en curso y hecho.
    await guardarEvento(null, { ...base, titulo: T.hosting, prioridad: 3 })
    await guardarEvento(null, { ...base, titulo: T.textos, prioridad: 1, enCurso: true })
    await guardarEvento(null, { ...base, titulo: T.contrato, prioridad: 2, hecho: true, hechoEn: hoy })
    await guardarEvento(null, { ...base, titulo: T.cotizacion, prioridad: 1 })
    // El que estrena las notas de la tarjeta.
    await guardarEvento(null, { ...base, titulo: T.dominio, prioridad: 2, notas: T.notaDominio })
    await guardarEvento(null, {
      ...base,
      titulo: T.junta,
      fecha: enDias(2),
      hora: '10:00',
      horaFin: '11:00',
      lugar: T.oficina,
      con: T.cliente,
    })
    // Uno ya entregado la semana pasada: estrena la columna «Hecho» con algo
    // que sí tuvo fecha.
    await guardarEvento(null, {
      ...base,
      titulo: T.maqueta,
      fecha: enDias(-4),
      hora: '13:00',
      hecho: true,
      hechoEn: enDias(-4),
    })
    return
  }

  if (area === 'salud') {
    await guardarEvento(null, {
      area: 'salud',
      ejemplo: true,
      titulo: T.limpieza,
      fecha: enDias(5),
      hora: '17:00',
      lugar: T.clinica,
      con: T.doctora,
    })
    // Una cita ya pasada para que el archivador tenga historial que plegar.
    await guardarEvento(null, {
      area: 'salud',
      ejemplo: true,
      titulo: T.analisis,
      fecha: enDias(-9),
      hora: '08:30',
      lugar: T.laboratorio,
      hecho: true,
      hechoEn: enDias(-9),
    })
    await guardarMedicamento(null, {
      nombre: T.vitamina,
      dosis: T.dosis,
      horas: ['09:00'],
      dias: [],
      fechaInicio: hoy,
      activo: true,
      ejemplo: true,
    })
    // El otro tipo de tratamiento: dos tomas al día y con fecha de fin.
    await guardarMedicamento(null, {
      nombre: T.antibiotico,
      dosis: T.capsula,
      horas: ['08:00', '20:00'],
      dias: [],
      fechaInicio: hoy,
      fechaFin: enDias(6),
      activo: true,
      ejemplo: true,
    })
    // Una mascota con lo que de verdad se olvida: la vacuna que toca una vez al
    // año, la desparasitación trimestral y la cita que ya está apalabrada.
    const mascotaId = nuevoId('ms')
    await guardarMascota({ mascId: mascotaId } as Mascota, {
      nombre: T.perro,
      especie: 'perro',
      raza: T.raza,
      nacimiento: `${Number(hoy.slice(0, 4)) - 3}${hoy.slice(4)}`,
      peso: 24,
      ejemplo: true,
    })
    await guardarCuidado(
      null,
      {
        mascotaId,
        tipo: 'vacuna',
        titulo: T.vacuna,
        fecha: enDias(12),
        hora: '10:00',
        cadaMeses: 12,
        activo: true,
        ejemplo: true,
      },
      T.perro,
    )
    await guardarCuidado(
      null,
      {
        mascotaId,
        tipo: 'desparasitacion',
        titulo: T.desparasitar,
        fecha: enDias(4),
        hora: '09:00',
        cadaMeses: 3,
        activo: true,
        ejemplo: true,
      },
      T.perro,
    )
    // Uno que ya se hizo: enseña la «última vez» y de dónde sale la próxima.
    await guardarCuidado(
      null,
      {
        mascotaId,
        tipo: 'bano',
        titulo: T.bano,
        fecha: enDias(9),
        hora: '12:00',
        cadaMeses: 1,
        ultima: enDias(-21),
        activo: true,
        ejemplo: true,
      },
      T.perro,
    )
    await guardarEvento(null, {
      area: 'salud',
      ejemplo: true,
      titulo: T.vacuna,
      fecha: enDias(12),
      hora: '10:00',
      lugar: T.veterinaria,
      mascotaId,
    })
    // Un tratamiento a nombre de la mascota: es lo que pinta su chip en la lista
    // y lo que deja ver para qué sirve el «¿para quién es?» del formulario.
    await guardarMedicamento(null, {
      nombre: T.gotas,
      dosis: T.dosisGotas,
      mascotaId,
      horas: ['08:00', '21:00'],
      dias: [],
      fechaInicio: hoy,
      fechaFin: enDias(4),
      activo: true,
      ejemplo: true,
    })
    return
  }

  // Personas: tres fichas (una por carpeta de relación) y dos planes con la misma
  // persona, uno por venir y otro ya pasado, para estrenar su historial.
  const contactoId = nuevoId('ct')
  // El cumpleaños se deja a la vuelta de la esquina para que se vea en el
  // calendario; el año es el de nacimiento y de ahí sale la edad que cumple.
  await guardarContacto({ contactoId } as ContactoAgenda, {
    nombre: T.ana,
    relacion: T.amigos,
    telefono: '555 123 4567',
    cumple: `1994${enDias(6).slice(4)}`,
    ejemplo: true,
  })
  await guardarContacto(null, { nombre: T.luis, relacion: T.trabajo, correo: 'luis@ejemplo.com', ejemplo: true })
  // La ficha completa: teléfono, correo, cumpleaños con su hora, dirección y notas.
  await guardarContacto(null, {
    nombre: T.carmen,
    relacion: T.familia,
    telefono: '555 987 6543',
    correo: 'carmen@ejemplo.com',
    cumple: `1961${enDias(20).slice(4)}`,
    horaCumple: '08:00',
    direccion: T.direccion,
    notas: T.notasCarmen,
    ejemplo: true,
  })
  await guardarEvento(null, {
    area: 'personas',
    ejemplo: true,
    titulo: T.cafe,
    fecha: enDias(3),
    hora: '18:00',
    lugar: T.cafeteria,
    contactoId,
  })
  await guardarEvento(null, {
    area: 'personas',
    ejemplo: true,
    titulo: T.cena,
    fecha: enDias(-12),
    hora: '21:00',
    contactoId,
    hecho: true,
    hechoEn: enDias(-12),
  })
}

/** Borra el ejemplo de una sección con lo que haya proyectado al calendario. */
export async function borrarEjemplo(
  area: AreaAgenda,
  eventos: EventoAgenda[],
  contactos: ContactoAgenda[],
  medicinas: Medicamento[],
  mascotas: Mascota[] = [],
): Promise<void> {
  for (const e of eventos.filter((x) => x.ejemplo && x.area === area)) await borrarEvento(e)
  if (area === 'salud') {
    for (const m of medicinas.filter((x) => x.ejemplo)) await borrarMedicamento(m)
    // La mascota se lleva sus cuidados (y con ellos sus bloques del calendario).
    for (const m of mascotas.filter((x) => x.ejemplo)) await borrarMascota(m)
  }
  if (area === 'personas') for (const c of contactos.filter((x) => x.ejemplo)) await borrarContacto(c)
}
