// Contenido del ejemplo de fábrica de video, por idioma. Vive aparte de
// `dict.ts` a propósito: en cuanto se crea es dato del usuario, no interfaz.
// La línea de tiempo (colores, tiempos y transiciones) la pone `ejemplos.ts`.

export const TEXTOS_VIDEO = {
  es: {
    proyecto: 'Domingo de mercado',
    titulo: 'Domingo de mercado',
    subtitulo: 'Cinco puestos y una lista',
    cierre: 'La próxima vez, con la bolsa grande',
    narracion1: 'Salimos a las nueve con la lista escrita y la intención de no comprar nada más.',
    narracion2: 'Volvimos con dos kilos de tomate, pan de ayer a mitad de precio y un ramo que nadie había pedido.',
  },
  en: {
    proyecto: 'Market Sunday',
    titulo: 'Market Sunday',
    subtitulo: 'Five stalls and a list',
    cierre: 'Next time, bring the big bag',
    narracion1: 'We left at nine with the list written down and every intention of sticking to it.',
    narracion2: 'We came back with two kilos of tomatoes, half-price bread from yesterday and flowers nobody asked for.',
  },
  pt: {
    proyecto: 'Domingo de feira',
    titulo: 'Domingo de feira',
    subtitulo: 'Cinco barracas e uma lista',
    cierre: 'Da próxima vez, com a sacola grande',
    narracion1: 'Saímos às nove com a lista escrita e a intenção de não comprar mais nada.',
    narracion2: 'Voltamos com dois quilos de tomate, pão de ontem pela metade do preço e um buquê que ninguém tinha pedido.',
  },
  fr: {
    proyecto: 'Dimanche au marché',
    titulo: 'Dimanche au marché',
    subtitulo: 'Cinq étals et une liste',
    cierre: 'La prochaine fois, on prend le grand sac',
    narracion1: 'On est partis à neuf heures avec la liste en main et la ferme intention de ne rien acheter d\'autre.',
    narracion2: 'On est revenus avec deux kilos de tomates, du pain de la veille à moitié prix et un bouquet que personne n\'avait demandé.',
  },
  de: {
    proyecto: 'Sonntagsmarkt',
    titulo: 'Sonntagsmarkt',
    subtitulo: 'Fünf Stände und eine Liste',
    cierre: 'Nächstes Mal mit der großen Tasche',
    narracion1: 'Wir sind um neun los, mit der geschriebenen Liste und dem festen Vorsatz, nichts anderes zu kaufen.',
    narracion2: 'Zurückgekommen sind wir mit zwei Kilo Tomaten, Brot vom Vortag zum halben Preis und einem Blumenstrauß, den niemand bestellt hatte.',
  },
  it: {
    proyecto: 'Domenica al mercato',
    titulo: 'Domenica al mercato',
    subtitulo: 'Cinque bancarelle e una lista',
    cierre: 'La prossima volta, con la borsa grande',
    narracion1: 'Siamo usciti alle nove con la lista scritta e l\'intenzione di non comprare altro.',
    narracion2: 'Siamo tornati con due chili di pomodori, pane di ieri a metà prezzo e un mazzo di fiori che nessuno aveva chiesto.',
  },
  ja: {
    proyecto: '日曜の朝市',
    titulo: '日曜の朝市',
    subtitulo: '屋台五つとメモ一枚',
    cierre: '次は大きいエコバッグで',
    narracion1: '9時に出発しました。買い物メモを書いて、他には何も買わないつもりでした。',
    narracion2: '戻ってきたときには、トマト2キロと半額の昨日のパン、それから誰も頼んでいない花束を持っていました。',
  },
  zh: {
    proyecto: '周日菜市场',
    titulo: '周日菜市场',
    subtitulo: '五个摊位,一张清单',
    cierre: '下次带大袋子来',
    narracion1: '我们九点出门,清单写好了,本打算什么都不多买。',
    narracion2: '回来时手里多了四斤西红柿、打折的隔夜面包,还有一束没人要的花。',
  },
  ko: {
    proyecto: '일요일 시장',
    titulo: '일요일 시장',
    subtitulo: '다섯 가게와 목록 하나',
    cierre: '다음엔 큰 장바구니로',
    narracion1: '아홉 시에 목록을 들고 나섰다. 그것 말고는 아무것도 사지 않을 생각이었다.',
    narracion2: '돌아올 땐 토마토 2킬로에, 반값 어제 빵, 그리고 아무도 부탁하지 않은 꽃다발까지 들려 있었다.',
  },
  ru: {
    proyecto: 'Воскресенье на рынке',
    titulo: 'Воскресенье на рынке',
    subtitulo: 'Пять прилавков и один список',
    cierre: 'В следующий раз — с большой сумкой',
    narracion1: 'Мы вышли в девять со списком в руках и твёрдым намерением ничего лишнего не покупать.',
    narracion2: 'Вернулись с двумя килограммами помидоров, вчерашним хлебом по полцены и букетом, который никто не заказывал.',
  },
  hi: {
    proyecto: 'इतवार का बाज़ार',
    titulo: 'इतवार का बाज़ार',
    subtitulo: 'पाँच दुकानें और एक लिस्ट',
    cierre: 'अगली बार, बड़ा थैला लेकर',
    narracion1: 'हम नौ बजे निकलीं — हाथ में लिखी लिस्ट थी और इरादा था कि और कुछ नहीं खरीदेंगे।',
    narracion2: 'हम दो किलो टमाटर, कल की आधी कीमत वाली रोटी और एक ऐसा गुलदस्ता लेकर लौटीं, जो किसी ने माँगा ही नहीं था।',
  },
  tr: {
    proyecto: 'Pazar pazarı',
    titulo: 'Pazar pazarı',
    subtitulo: 'Beş tezgah ve bir liste',
    cierre: 'Bir dahaki sefere, büyük çantayla',
    narracion1: 'Saat dokuzda, elimizde yazılı liste ve başka bir şey almama niyetiyle çıktık.',
    narracion2: 'İki kilo domates, dünden yarı fiyatına ekmek ve kimsenin istemediği bir demet çiçekle döndük.',
  },
  id: {
    proyecto: 'Minggu di pasar',
    titulo: 'Minggu di pasar',
    subtitulo: 'Lima lapak dan satu daftar',
    cierre: 'Lain kali, bawa tas besar',
    narracion1: 'Kami berangkat jam sembilan dengan daftar belanja di tangan dan niat untuk tidak beli apa-apa lagi.',
    narracion2: 'Kami pulang bawa dua kilo tomat, roti kemarin setengah harga, dan seikat bunga yang tidak ada yang minta.',
  },
  pl: {
    proyecto: 'Niedziela na targu',
    titulo: 'Niedziela na targu',
    subtitulo: 'Pięć straganów i jedna lista',
    cierre: 'Następnym razem — z dużą torbą',
    narracion1: 'Wyszłyśmy o dziewiątej z listą w ręku i mocnym postanowieniem, że nic więcej nie kupimy.',
    narracion2: 'Wróciłyśmy z dwoma kilogramami pomidorów, wczorajszym chlebem za pół ceny i bukietem, o który nikt nie prosił.',
  },
  ar: {
    proyecto: 'سوق الأحد',
    titulo: 'سوق الأحد',
    subtitulo: 'خمسة أكشاك ولائحة واحدة',
    cierre: 'في المرة القادمة، بالحقيبة الكبيرة',
    narracion1: 'خرجنا الساعة التاسعة، واللائحة مكتوبة بأيدينا، وكلّنا عازمات على ألا نشتري شيئاً آخر.',
    narracion2: 'عدنا بكيلوين من الطماطم، وخبز الأمس بنصف السعر، وباقة ورد لم يطلبها أحد.',
  },
  nl: {
    proyecto: 'Zondagmarkt',
    titulo: 'Zondagmarkt',
    subtitulo: 'Vijf kraampjes en een lijstje',
    cierre: 'Volgende keer met de grote tas',
    narracion1: 'We vertrokken om negen uur met het lijstje in de hand en het vaste voornemen niets anders te kopen.',
    narracion2: 'We kwamen terug met twee kilo tomaten, brood van gisteren voor de halve prijs en een bos bloemen die niemand had besteld.',
  },
}
