// GENERADO por marketing/promo/empaquetar-studio.mjs — no editar a mano.
//
// El anuncio de MPH montado para el Studio de video, resuelto por idioma: las
// tomas en orden con su duración (el sobrante de la voz ya repartido), dónde
// entra cada línea de voz y cada rótulo, y los textos. Los binarios viven en
// `public/promo/`; `rooms/video/promo.ts` los siembra como un proyecto normal.
import type { PorIdioma } from '../../core/i18n/porIdioma'

/** `sfx`: sonido de fábrica (clave de `sonidos.ts`) que suena con el corte de la toma. */
export type TomaPromo =
  | { tipo: 'clip'; clip: string; seg: number; sfx?: string }
  /** Un calendario en otro idioma (la ráfaga «16 idiomas»). */
  | { tipo: 'rafaga'; idioma: string; seg: number; sfx?: string }
  | { tipo: 'escritorio'; seg: number; sfx?: string }
  | { tipo: 'cierre'; seg: number; sfx?: string }

export interface PlanPromo {
  nombre: string
  /** Carpeta de clips de la app en ese idioma (`public/promo/clips/<clips>/`); la captura de escritorio va igual. */
  clips: 'es' | 'en'
  lineas: Record<string, string>
  titulares: Record<string, string>
  cierre: string[]
  gratis: string
  tomas: TomaPromo[]
  voces: { linea: string; desde: number; seg: number }[]
  rotulos: { clave: string; desde: number; hasta: number }[]
  /** Sonidos de fábrica que van DESPUÉS de una línea de voz (se cortan si entra la siguiente). */
  efectos: { clave: string; desde: number }[]
}

/** Duraciones (s) y tamaños de lo que hay en `public/promo/`. */
export const PROMO_MEDIOS: {
  clips: Record<'es' | 'en', Record<string, number>>
  /** El calendario de cada idioma grabado (la ráfaga). */
  calendarios: Record<string, number>
  escritorio: Record<'es' | 'en', { ancho: number; alto: number }>
  musica: number | null
} = {
  clips: {
    es: {
      "01-avatar": 4.1,
      "02-casa-gira": 2.67,
      "03-app-cocina": 1.07,
      "03-app-ejercicio": 1.27,
      "03-app-finanzas": 1.07,
      "03-app-metas": 1.07,
      "03-app-studio": 1.67,
      "04-mosaico": 2.27,
      "04-editor": 2.47,
      "04-temas": 3.27,
      "05-calendario": 1.97,
      "05-misiones": 1.97,
      "05-cronograma": 2.07,
      "06-avatar-asistente": 1.97,
      "06-chat": 2.27,
      "06-fotos": 1.77,
      "06-diagrama": 2.27,
      "06-formulas": 2.07,
      "06-grafica": 2.27,
      "07-sisifo": 3.47,
      "07-wrapped": 2.87,
      "07-baile": 5.5,
      "07-panel-ia": 2.9,
      "09-atardecer": 3.47
    },
    en: {
      "01-avatar": 5.03,
      "02-casa-gira": 2.67,
      "03-app-cocina": 1.07,
      "03-app-ejercicio": 1.27,
      "03-app-finanzas": 1.07,
      "03-app-metas": 1.07,
      "03-app-studio": 2.87,
      "04-mosaico": 2.27,
      "04-editor": 2.47,
      "04-temas": 4.67,
      "05-calendario": 1.97,
      "05-misiones": 1.97,
      "05-cronograma": 2.07,
      "06-avatar-asistente": 2.7,
      "06-chat": 2.27,
      "06-fotos": 1.77,
      "06-diagrama": 2.27,
      "06-formulas": 2.07,
      "06-grafica": 2.27,
      "07-sisifo": 4.37,
      "07-wrapped": 4,
      "07-baile": 5.5,
      "07-panel-ia": 3.87,
      "09-atardecer": 4.03
    }
  },
  calendarios: {
    es: 1.97,
    en: 1.97,
    pt: 0.7,
    fr: 0.7,
    de: 0.7,
    it: 0.7,
    ja: 0.7,
    zh: 0.7,
    ko: 0.7,
    ru: 0.7,
    hi: 0.7,
    tr: 0.7,
    id: 0.7,
    pl: 0.7,
    nl: 0.7,
    ar: 0.7
  },
  escritorio: {
    es: { ancho: 1280, alto: 720 },
    en: { ancho: 1280, alto: 720 }
  },
  musica: null
}

export const PROMO_NOMBRES: Record<'es' | 'en', Record<string, string>> = {
  es: {
    "01-avatar": 'Avatar en primer plano',
    "02-casa-gira": 'La casa gira',
    "03-app-cocina": 'App Cocina',
    "03-app-ejercicio": 'App Ejercicio',
    "03-app-finanzas": 'App Finanzas',
    "03-app-metas": 'App Metas',
    "03-app-studio": 'App Studio',
    "04-mosaico": 'Mosaico de apps',
    "04-editor": 'Editor de la casa',
    "04-temas": 'Temas de la casa',
    "05-calendario": 'Calendario',
    "05-misiones": 'Misiones',
    "05-cronograma": 'Cronograma',
    "06-avatar-asistente": 'Avatar y asistente',
    "06-chat": 'Chat con el asistente',
    "06-fotos": 'Anecdotario',
    "06-ideas": 'Ideas',
    "06-diagrama": 'Diagrama de decisión',
    "06-formulas": 'Formulario de fórmulas',
    "06-grafica": 'Superficie 3D',
    "07-sisifo": 'Sísifo',
    "07-wrapped": 'Resumen',
    "07-baile": 'Baile',
    "07-panel-ia": 'Panel de IA',
    "09-atardecer": 'Atardecer',
    escritorio: 'MPH en escritorio',
    musica: 'Música del anuncio'
  },
  en: {
    "01-avatar": 'Avatar close-up',
    "02-casa-gira": 'The house spins',
    "03-app-cocina": 'Kitchen app',
    "03-app-ejercicio": 'Workout app',
    "03-app-finanzas": 'Finances app',
    "03-app-metas": 'Goals app',
    "03-app-studio": 'Studio app',
    "04-mosaico": 'App mosaic',
    "04-editor": 'House editor',
    "04-temas": 'House themes',
    "05-calendario": 'Calendar',
    "05-misiones": 'Missions',
    "05-cronograma": 'Schedule',
    "06-avatar-asistente": 'Avatar and assistant',
    "06-chat": 'Chat with the assistant',
    "06-fotos": 'Journal',
    "06-ideas": 'Ideas',
    "06-diagrama": 'Decision diagram',
    "06-formulas": 'Formula book',
    "06-grafica": '3D surface',
    "07-sisifo": 'Sisyphus',
    "07-wrapped": 'Recap',
    "07-baile": 'Dance',
    "07-panel-ia": 'AI panel',
    "09-atardecer": 'Sunset',
    escritorio: 'MPH on desktop',
    musica: 'Ad music'
  }
}

export const PROMO: PorIdioma<PlanPromo> = {
  es: {
    nombre: 'Anuncio de MPH',
    clips: 'es',
    lineas: {
      gancho: '¿Y si el tamagotchi… fueras tú?',
      casa: 'MPH es una casa 3D donde cada cuarto es una app: cocina, ejercicio, finanzas, metas, música…',
      disena: 'Diseña tu casa y decide qué app va en cada cuarto: tu centro de entretenimiento, estudio, creatividad y cuidado.',
      metas: 'Tu agenda, tu calendario, tu bitácora y un asistente personal para cumplir tus metas en la vida real.',
      ia: 'Conversa con tus asistentes como con ChatGPT, Gemini o Claude: registran tu día y crean imágenes, recursos y modelos 3D.',
      cerebro: 'Las redes fragmentan tu atención y la tecnología piensa por ti. MPH es la forma más completa y divertida de usar tu cerebro y ver progresar los hábitos que tú eliges.',
      idiomas: 'En 16 idiomas. Web, escritorio y móvil. Con créditos de IA, con modelos locales gratis… o sin IA.',
      cta: 'Pruébala gratis. O hazla tuya con un solo pago.',
      eslogan: 'Construye tu personaje construyendo tus hábitos. Diseña tu casa, diseñando tu futuro.'
    },
    titulares: {
      gancho: '¿Qué pasaría si fueras un tamagotchi?',
      apps: '21 apps · 1 casa',
      disena: 'Tu casa, tus apps',
      metas: 'Metas reales',
      ia: 'IA opcional',
      progreso: 'Tu progreso, visible',
      idiomas: '16 idiomas',
      plataformas: 'Web · PC · Móvil',
      conSinIa: 'Con IA… o sin IA',
      personaliza: 'Personaliza tu casa'
    },
    cierre: [
      'Construye a tu personaje, construyendo tus hábitos.',
      'Diseña tu casa, diseñando tu futuro.',
      'Conquista los objetivos de los cuartos, conquistando tus pendientes.'
    ],
    gratis: 'Pruébala gratis',
    tomas: [
      { tipo: 'clip', clip: '01-avatar', seg: 3.85 },
      { tipo: 'clip', clip: '02-casa-gira', seg: 2.4, sfx: 'click' },
      { tipo: 'clip', clip: '03-app-cocina', seg: 0.8, sfx: 'click' },
      { tipo: 'clip', clip: '03-app-ejercicio', seg: 1, sfx: 'click' },
      { tipo: 'clip', clip: '03-app-finanzas', seg: 0.8, sfx: 'click' },
      { tipo: 'clip', clip: '03-app-metas', seg: 0.8, sfx: 'click' },
      { tipo: 'clip', clip: '03-app-studio', seg: 1.4, sfx: 'click' },
      { tipo: 'clip', clip: '04-mosaico', seg: 2, sfx: 'click' },
      { tipo: 'clip', clip: '04-editor', seg: 2.2, sfx: 'click' },
      { tipo: 'clip', clip: '04-temas', seg: 3, sfx: 'wow' },
      { tipo: 'clip', clip: '05-calendario', seg: 1.7, sfx: 'click' },
      { tipo: 'clip', clip: '05-misiones', seg: 1.7, sfx: 'click' },
      { tipo: 'clip', clip: '05-cronograma', seg: 1.8, sfx: 'click' },
      { tipo: 'clip', clip: '06-avatar-asistente', seg: 1.7, sfx: 'click' },
      { tipo: 'clip', clip: '06-chat', seg: 2, sfx: 'click' },
      { tipo: 'clip', clip: '06-fotos', seg: 1.5, sfx: 'click' },
      { tipo: 'clip', clip: '06-diagrama', seg: 2, sfx: 'click' },
      { tipo: 'clip', clip: '06-formulas', seg: 1.8, sfx: 'click' },
      { tipo: 'clip', clip: '06-grafica', seg: 2, sfx: 'click' },
      { tipo: 'clip', clip: '07-sisifo', seg: 3.2, sfx: 'click' },
      { tipo: 'clip', clip: '07-wrapped', seg: 2.6, sfx: 'nice' },
      { tipo: 'clip', clip: '07-baile', seg: 5.38, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'ja', seg: 0.45, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'ar', seg: 0.45, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'hi', seg: 0.45, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'ko', seg: 0.45, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'ru', seg: 0.45, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'zh', seg: 0.45, sfx: 'click' },
      { tipo: 'escritorio', seg: 1.9, sfx: 'click' },
      { tipo: 'clip', clip: '07-panel-ia', seg: 2.64, sfx: 'click' },
      { tipo: 'clip', clip: '09-atardecer', seg: 3.2, sfx: 'click' },
      { tipo: 'cierre', seg: 6.5, sfx: 'golpe' },
      { tipo: 'clip', clip: '01-avatar', seg: 0.8 }
    ],
    voces: [
      { linea: 'gancho', desde: 0.1, seg: 1.85 },
      { linea: 'casa', desde: 3.95, seg: 6.51 },
      { linea: 'disena', desde: 11.15, seg: 6.18 },
      { linea: 'metas', desde: 18.35, seg: 5.39 },
      { linea: 'ia', desde: 25.25, seg: 7.36 },
      { linea: 'cerebro', desde: 34.55, seg: 8.78 },
      { linea: 'idiomas', desde: 45.73, seg: 6.99 },
      { linea: 'cta', desde: 52.97, seg: 2.93 },
      { linea: 'eslogan', desde: 56.17, seg: 5.03 }
    ],
    rotulos: [
      { clave: 'gancho', desde: 0.25, hasta: 3.85 },
      { clave: 'apps', desde: 6.25, hasta: 11.05 },
      { clave: 'disena', desde: 11.35, hasta: 15.05 },
      { clave: 'personaliza', desde: 15.45, hasta: 18.25 },
      { clave: 'metas', desde: 18.55, hasta: 23.45 },
      { clave: 'ia', desde: 25.45, hasta: 29.95 },
      { clave: 'progreso', desde: 37.85, hasta: 43.05 },
      { clave: 'idiomas', desde: 45.73, hasta: 48.23 },
      { clave: 'plataformas', desde: 48.43, hasta: 50.13 },
      { clave: 'conSinIa', desde: 50.33, hasta: 52.87 }
    ],
    efectos: [
      { clave: 'faa', desde: 2.05 },
      { clave: 'aaa', desde: 43.43 }
    ]
  },
  en: {
    nombre: 'MPH ad',
    clips: 'en',
    lineas: {
      gancho: 'What if the Tamagotchi… were you?',
      casa: 'MPH is a 3D house where every room is an app: kitchen, workouts, finances, goals, music…',
      disena: 'Design your house and choose which app goes in each room: your hub for entertainment, study, creativity and self-care.',
      metas: 'Your agenda, your calendar, your journal and a personal assistant to hit your goals in real life.',
      ia: 'Talk to your assistants like you would with ChatGPT, Gemini or Claude: they log your day and create images, resources and 3D models.',
      cerebro: 'Social media fragments your attention and technology thinks for you. MPH is the most complete and fun way to use your brain and watch the habits you choose grow.',
      idiomas: 'In 16 languages. Web, desktop and mobile. With AI credits, with free local models… or with no AI at all.',
      cta: 'Try it for free. Or make it yours with a single payment.',
      eslogan: 'Build your character by building your habits. Design your house, designing your future.'
    },
    titulares: {
      gancho: 'What if you were a Tamagotchi?',
      apps: '21 apps · 1 house',
      disena: 'Your house, your apps',
      metas: 'Real goals',
      ia: 'Optional AI',
      progreso: 'Your progress, visible',
      idiomas: '16 languages',
      plataformas: 'Web · PC · Mobile',
      conSinIa: 'With AI… or without',
      personaliza: 'Customize your house'
    },
    cierre: [
      'Build your character, building your habits.',
      'Design your house, designing your future.',
      'Conquer the goals of each room, conquering your to-dos.'
    ],
    gratis: 'Try it for free',
    tomas: [
      { tipo: 'clip', clip: '01-avatar', seg: 3.4 },
      { tipo: 'clip', clip: '02-casa-gira', seg: 2.4, sfx: 'click' },
      { tipo: 'clip', clip: '03-app-cocina', seg: 0.8, sfx: 'click' },
      { tipo: 'clip', clip: '03-app-ejercicio', seg: 1, sfx: 'click' },
      { tipo: 'clip', clip: '03-app-finanzas', seg: 0.8, sfx: 'click' },
      { tipo: 'clip', clip: '03-app-metas', seg: 0.8, sfx: 'click' },
      { tipo: 'clip', clip: '03-app-studio', seg: 1.4, sfx: 'click' },
      { tipo: 'clip', clip: '04-mosaico', seg: 2, sfx: 'click' },
      { tipo: 'clip', clip: '04-editor', seg: 2.2, sfx: 'click' },
      { tipo: 'clip', clip: '04-temas', seg: 3, sfx: 'wow' },
      { tipo: 'clip', clip: '05-calendario', seg: 1.7, sfx: 'click' },
      { tipo: 'clip', clip: '05-misiones', seg: 1.7, sfx: 'click' },
      { tipo: 'clip', clip: '05-cronograma', seg: 1.8, sfx: 'click' },
      { tipo: 'clip', clip: '06-avatar-asistente', seg: 1.7, sfx: 'click' },
      { tipo: 'clip', clip: '06-chat', seg: 2, sfx: 'click' },
      { tipo: 'clip', clip: '06-fotos', seg: 1.5, sfx: 'click' },
      { tipo: 'clip', clip: '06-diagrama', seg: 2, sfx: 'click' },
      { tipo: 'clip', clip: '06-formulas', seg: 1.8, sfx: 'click' },
      { tipo: 'clip', clip: '06-grafica', seg: 2, sfx: 'click' },
      { tipo: 'clip', clip: '07-sisifo', seg: 3.2, sfx: 'click' },
      { tipo: 'clip', clip: '07-wrapped', seg: 2.6, sfx: 'nice' },
      { tipo: 'clip', clip: '07-baile', seg: 5.08, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'ja', seg: 0.45, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'ar', seg: 0.45, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'hi', seg: 0.45, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'ko', seg: 0.45, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'ru', seg: 0.45, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'zh', seg: 0.45, sfx: 'click' },
      { tipo: 'escritorio', seg: 1.9, sfx: 'click' },
      { tipo: 'clip', clip: '07-panel-ia', seg: 2.6, sfx: 'click' },
      { tipo: 'clip', clip: '09-atardecer', seg: 3.2, sfx: 'click' },
      { tipo: 'cierre', seg: 6.5, sfx: 'golpe' },
      { tipo: 'clip', clip: '01-avatar', seg: 0.8 }
    ],
    voces: [
      { linea: 'gancho', desde: 0.1, seg: 1.4 },
      { linea: 'casa', desde: 3.5, seg: 6.74 },
      { linea: 'disena', desde: 10.7, seg: 6.74 },
      { linea: 'metas', desde: 17.9, seg: 5.04 },
      { linea: 'ia', desde: 24.8, seg: 7.92 },
      { linea: 'cerebro', desde: 34.1, seg: 8.48 },
      { linea: 'idiomas', desde: 44.98, seg: 6.9 },
      { linea: 'cta', desde: 52.18, seg: 2.45 },
      { linea: 'eslogan', desde: 55.38, seg: 4.26 }
    ],
    rotulos: [
      { clave: 'gancho', desde: 0.25, hasta: 3.4 },
      { clave: 'apps', desde: 5.8, hasta: 10.6 },
      { clave: 'disena', desde: 10.9, hasta: 14.6 },
      { clave: 'personaliza', desde: 15, hasta: 17.8 },
      { clave: 'metas', desde: 18.1, hasta: 23 },
      { clave: 'ia', desde: 25, hasta: 29.5 },
      { clave: 'progreso', desde: 37.4, hasta: 42.6 },
      { clave: 'idiomas', desde: 44.98, hasta: 47.48 },
      { clave: 'plataformas', desde: 47.68, hasta: 49.38 },
      { clave: 'conSinIa', desde: 49.58, hasta: 52.08 }
    ],
    efectos: [
      { clave: 'faa', desde: 1.6 },
      { clave: 'aaa', desde: 42.68 }
    ]
  },
  pt: {
    nombre: 'Anúncio do MPH',
    clips: 'en',
    lineas: {
      gancho: 'E se o Tamagotchi… fosse você?',
      casa: 'O MPH é uma casa 3D em que cada cômodo é um app: cozinha, exercícios, finanças, metas, música…',
      disena: 'Projete sua casa e escolha qual app vai em cada cômodo: seu centro de entretenimento, estudo, criatividade e cuidado.',
      metas: 'Sua agenda, seu calendário, seu diário de bordo e um assistente pessoal para cumprir suas metas na vida real.',
      ia: 'Converse com seus assistentes como faria com o ChatGPT, o Gemini ou o Claude: eles registram seu dia e criam imagens, recursos e modelos 3D.',
      cerebro: 'As redes sociais fragmentam sua atenção e a tecnologia pensa por você. O MPH é a forma mais completa e divertida de usar seu cérebro e ver progredir os hábitos que você escolhe.',
      idiomas: 'Em 16 idiomas. Web, desktop e celular. Com créditos de IA, com modelos locais gratuitos… ou sem IA.',
      cta: 'Experimente grátis. Ou faça dele seu com um pagamento único.',
      eslogan: 'Construa seu personagem construindo seus hábitos. Projete sua casa, projetando seu futuro.'
    },
    titulares: {
      gancho: 'E se você fosse um Tamagotchi?',
      apps: '21 apps · 1 casa',
      disena: 'Sua casa, seus apps',
      metas: 'Metas de verdade',
      ia: 'IA opcional',
      progreso: 'Seu progresso, visível',
      idiomas: '16 idiomas',
      plataformas: 'Web · PC · Celular',
      conSinIa: 'Com IA… ou sem IA',
      personaliza: 'Personalize sua casa'
    },
    cierre: [
      'Construa seu personagem, construindo seus hábitos.',
      'Projete sua casa, projetando seu futuro.',
      'Conquiste os objetivos dos cômodos, conquistando suas pendências.'
    ],
    gratis: 'Experimente grátis',
    tomas: [
      { tipo: 'clip', clip: '01-avatar', seg: 3.86 },
      { tipo: 'clip', clip: '02-casa-gira', seg: 2.4, sfx: 'click' },
      { tipo: 'clip', clip: '03-app-cocina', seg: 0.8, sfx: 'click' },
      { tipo: 'clip', clip: '03-app-ejercicio', seg: 1, sfx: 'click' },
      { tipo: 'clip', clip: '03-app-finanzas', seg: 0.8, sfx: 'click' },
      { tipo: 'clip', clip: '03-app-metas', seg: 0.8, sfx: 'click' },
      { tipo: 'clip', clip: '03-app-studio', seg: 1.4, sfx: 'click' },
      { tipo: 'clip', clip: '04-mosaico', seg: 2, sfx: 'click' },
      { tipo: 'clip', clip: '04-editor', seg: 2.2, sfx: 'click' },
      { tipo: 'clip', clip: '04-temas', seg: 3, sfx: 'wow' },
      { tipo: 'clip', clip: '05-calendario', seg: 1.7, sfx: 'click' },
      { tipo: 'clip', clip: '05-misiones', seg: 1.7, sfx: 'click' },
      { tipo: 'clip', clip: '05-cronograma', seg: 1.8, sfx: 'click' },
      { tipo: 'clip', clip: '06-avatar-asistente', seg: 1.7, sfx: 'click' },
      { tipo: 'clip', clip: '06-chat', seg: 2, sfx: 'click' },
      { tipo: 'clip', clip: '06-fotos', seg: 1.5, sfx: 'click' },
      { tipo: 'clip', clip: '06-diagrama', seg: 2, sfx: 'click' },
      { tipo: 'clip', clip: '06-formulas', seg: 1.8, sfx: 'click' },
      { tipo: 'clip', clip: '06-grafica', seg: 2, sfx: 'click' },
      { tipo: 'clip', clip: '07-sisifo', seg: 3.2, sfx: 'click' },
      { tipo: 'clip', clip: '07-wrapped', seg: 3.13, sfx: 'nice' },
      { tipo: 'clip', clip: '07-baile', seg: 5.45, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'ja', seg: 0.45, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'ar', seg: 0.45, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'hi', seg: 0.45, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'ko', seg: 0.45, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'ru', seg: 0.45, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'zh', seg: 0.45, sfx: 'click' },
      { tipo: 'escritorio', seg: 1.9, sfx: 'click' },
      { tipo: 'clip', clip: '07-panel-ia', seg: 3.54, sfx: 'click' },
      { tipo: 'clip', clip: '09-atardecer', seg: 3.4, sfx: 'click' },
      { tipo: 'cierre', seg: 6.5, sfx: 'golpe' },
      { tipo: 'clip', clip: '01-avatar', seg: 0.8 }
    ],
    voces: [
      { linea: 'gancho', desde: 0.1, seg: 1.86 },
      { linea: 'casa', desde: 3.96, seg: 6.74 },
      { linea: 'disena', desde: 11.16, seg: 6.42 },
      { linea: 'metas', desde: 18.36, seg: 5.78 },
      { linea: 'ia', desde: 25.26, seg: 8.19 },
      { linea: 'cerebro', desde: 34.56, seg: 9.38 },
      { linea: 'idiomas', desde: 46.34, seg: 7.89 },
      { linea: 'cta', desde: 54.48, seg: 3.15 },
      { linea: 'eslogan', desde: 57.88, seg: 5.3 }
    ],
    rotulos: [
      { clave: 'gancho', desde: 0.25, hasta: 3.86 },
      { clave: 'apps', desde: 6.26, hasta: 11.06 },
      { clave: 'disena', desde: 11.36, hasta: 15.06 },
      { clave: 'personaliza', desde: 15.46, hasta: 18.26 },
      { clave: 'metas', desde: 18.56, hasta: 23.46 },
      { clave: 'ia', desde: 25.46, hasta: 29.96 },
      { clave: 'progreso', desde: 37.86, hasta: 43.06 },
      { clave: 'idiomas', desde: 46.34, hasta: 48.84 },
      { clave: 'plataformas', desde: 49.04, hasta: 50.74 },
      { clave: 'conSinIa', desde: 50.94, hasta: 54.38 }
    ],
    efectos: [
      { clave: 'faa', desde: 2.06 },
      { clave: 'aaa', desde: 44.04 }
    ]
  },
  fr: {
    nombre: 'Pub de MPH',
    clips: 'en',
    lineas: {
      gancho: 'Et si le Tamagotchi… c\'était toi ?',
      casa: 'MPH est une maison 3D où chaque pièce est une app : cuisine, sport, finances, objectifs, musique…',
      disena: 'Conçois ta maison et choisis quelle app va dans chaque pièce : ton centre de divertissement, d\'étude, de créativité et de bien-être.',
      metas: 'Ton agenda, ton calendrier, ton journal de bord et un assistant personnel pour atteindre tes objectifs dans la vraie vie.',
      ia: 'Discute avec tes assistants comme avec ChatGPT, Gemini ou Claude : ils notent ta journée et créent des images, des ressources et des modèles 3D.',
      cerebro: 'Les réseaux sociaux fragmentent ton attention et la technologie pense à ta place. MPH est la façon la plus complète et la plus amusante d\'utiliser ton cerveau et de voir progresser les habitudes que tu choisis.',
      idiomas: 'En 16 langues. Web, ordinateur et mobile. Avec des crédits d\'IA, avec des modèles locaux gratuits… ou sans IA.',
      cta: 'Essaie-la gratuitement. Ou fais-la tienne en un seul paiement.',
      eslogan: 'Construis ton personnage en construisant tes habitudes. Conçois ta maison en concevant ton avenir.'
    },
    titulares: {
      gancho: 'Et si tu étais un Tamagotchi ?',
      apps: '21 apps · 1 maison',
      disena: 'Ta maison, tes apps',
      metas: 'De vrais objectifs',
      ia: 'IA en option',
      progreso: 'Tes progrès, visibles',
      idiomas: '16 langues',
      plataformas: 'Web · PC · Mobile',
      conSinIa: 'Avec IA… ou sans',
      personaliza: 'Personnalise ta maison'
    },
    cierre: [
      'Construis ton personnage, en construisant tes habitudes.',
      'Conçois ta maison, en concevant ton avenir.',
      'Conquiers les objectifs de chaque pièce, en venant à bout de tes tâches.'
    ],
    gratis: 'Essayer gratuitement',
    tomas: [
      { tipo: 'clip', clip: '01-avatar', seg: 3.8 },
      { tipo: 'clip', clip: '02-casa-gira', seg: 2.4, sfx: 'click' },
      { tipo: 'clip', clip: '03-app-cocina', seg: 0.8, sfx: 'click' },
      { tipo: 'clip', clip: '03-app-ejercicio', seg: 1, sfx: 'click' },
      { tipo: 'clip', clip: '03-app-finanzas', seg: 0.8, sfx: 'click' },
      { tipo: 'clip', clip: '03-app-metas', seg: 0.8, sfx: 'click' },
      { tipo: 'clip', clip: '03-app-studio', seg: 1.4, sfx: 'click' },
      { tipo: 'clip', clip: '04-mosaico', seg: 2, sfx: 'click' },
      { tipo: 'clip', clip: '04-editor', seg: 2.2, sfx: 'click' },
      { tipo: 'clip', clip: '04-temas', seg: 3, sfx: 'wow' },
      { tipo: 'clip', clip: '05-calendario', seg: 1.7, sfx: 'click' },
      { tipo: 'clip', clip: '05-misiones', seg: 1.7, sfx: 'click' },
      { tipo: 'clip', clip: '05-cronograma', seg: 1.8, sfx: 'click' },
      { tipo: 'clip', clip: '06-avatar-asistente', seg: 1.7, sfx: 'click' },
      { tipo: 'clip', clip: '06-chat', seg: 2, sfx: 'click' },
      { tipo: 'clip', clip: '06-fotos', seg: 1.5, sfx: 'click' },
      { tipo: 'clip', clip: '06-diagrama', seg: 2, sfx: 'click' },
      { tipo: 'clip', clip: '06-formulas', seg: 1.8, sfx: 'click' },
      { tipo: 'clip', clip: '06-grafica', seg: 2, sfx: 'click' },
      { tipo: 'clip', clip: '07-sisifo', seg: 3.2, sfx: 'click' },
      { tipo: 'clip', clip: '07-wrapped', seg: 2.6, sfx: 'nice' },
      { tipo: 'clip', clip: '07-baile', seg: 5.28, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'ja', seg: 0.45, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'ar', seg: 0.45, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'hi', seg: 0.45, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'ko', seg: 0.45, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'ru', seg: 0.45, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'zh', seg: 0.45, sfx: 'click' },
      { tipo: 'escritorio', seg: 1.9, sfx: 'click' },
      { tipo: 'clip', clip: '07-panel-ia', seg: 2.6, sfx: 'click' },
      { tipo: 'clip', clip: '09-atardecer', seg: 3.2, sfx: 'click' },
      { tipo: 'cierre', seg: 6.5, sfx: 'golpe' },
      { tipo: 'clip', clip: '01-avatar', seg: 0.8 }
    ],
    voces: [
      { linea: 'gancho', desde: 0.1, seg: 1.8 },
      { linea: 'casa', desde: 3.9, seg: 5.46 },
      { linea: 'disena', desde: 11.1, seg: 5.73 },
      { linea: 'metas', desde: 18.3, seg: 5.28 },
      { linea: 'ia', desde: 25.2, seg: 6.57 },
      { linea: 'cerebro', desde: 34.5, seg: 8.68 },
      { linea: 'idiomas', desde: 45.58, seg: 6.16 },
      { linea: 'cta', desde: 52.78, seg: 2.73 },
      { linea: 'eslogan', desde: 55.98, seg: 4.46 }
    ],
    rotulos: [
      { clave: 'gancho', desde: 0.25, hasta: 3.8 },
      { clave: 'apps', desde: 6.2, hasta: 11 },
      { clave: 'disena', desde: 11.3, hasta: 15 },
      { clave: 'personaliza', desde: 15.4, hasta: 18.2 },
      { clave: 'metas', desde: 18.5, hasta: 23.4 },
      { clave: 'ia', desde: 25.4, hasta: 29.9 },
      { clave: 'progreso', desde: 37.8, hasta: 43 },
      { clave: 'idiomas', desde: 45.58, hasta: 48.08 },
      { clave: 'plataformas', desde: 48.28, hasta: 49.98 },
      { clave: 'conSinIa', desde: 50.18, hasta: 52.68 }
    ],
    efectos: [
      { clave: 'faa', desde: 2 },
      { clave: 'aaa', desde: 43.28 }
    ]
  },
  de: {
    nombre: 'MPH-Werbespot',
    clips: 'en',
    lineas: {
      gancho: 'Und wenn das Tamagotchi… du wärst?',
      casa: 'MPH ist ein 3D-Haus, in dem jeder Raum eine App ist: Küche, Training, Finanzen, Ziele, Musik…',
      disena: 'Gestalte dein Haus und entscheide, welche App in welchen Raum kommt: dein Zentrum für Unterhaltung, Lernen, Kreativität und Selbstfürsorge.',
      metas: 'Dein Terminplaner, dein Kalender, dein Logbuch und ein persönlicher Assistent, damit du deine Ziele im echten Leben erreichst.',
      ia: 'Sprich mit deinen Assistenten wie mit ChatGPT, Gemini oder Claude: Sie halten deinen Tag fest und erstellen Bilder, Ressourcen und 3D-Modelle.',
      cerebro: 'Soziale Netzwerke zersplittern deine Aufmerksamkeit, und die Technik denkt für dich. MPH ist der vollständigste und unterhaltsamste Weg, dein Gehirn zu nutzen und die Gewohnheiten wachsen zu sehen, die du selbst wählst.',
      idiomas: 'In 16 Sprachen. Web, Desktop und Handy. Mit KI-Guthaben, mit kostenlosen lokalen Modellen… oder ganz ohne KI.',
      cta: 'Probier es gratis. Oder mach es mit einer einzigen Zahlung zu deinem.',
      eslogan: 'Baue deine Figur, indem du deine Gewohnheiten aufbaust. Gestalte dein Haus und gestalte deine Zukunft.'
    },
    titulares: {
      gancho: 'Was wäre, wenn du ein Tamagotchi wärst?',
      apps: '21 Apps · 1 Haus',
      disena: 'Dein Haus, deine Apps',
      metas: 'Echte Ziele',
      ia: 'KI optional',
      progreso: 'Dein Fortschritt, sichtbar',
      idiomas: '16 Sprachen',
      plataformas: 'Web · PC · Handy',
      conSinIa: 'Mit KI… oder ohne',
      personaliza: 'Gestalte dein Haus'
    },
    cierre: [
      'Baue deine Figur, indem du deine Gewohnheiten aufbaust.',
      'Gestalte dein Haus, und gestalte deine Zukunft.',
      'Erobere die Ziele der Räume, und erledige deine Aufgaben.'
    ],
    gratis: 'Gratis ausprobieren',
    tomas: [
      { tipo: 'clip', clip: '01-avatar', seg: 4.1 },
      { tipo: 'clip', clip: '02-casa-gira', seg: 2.4, sfx: 'click' },
      { tipo: 'clip', clip: '03-app-cocina', seg: 0.8, sfx: 'click' },
      { tipo: 'clip', clip: '03-app-ejercicio', seg: 1, sfx: 'click' },
      { tipo: 'clip', clip: '03-app-finanzas', seg: 0.8, sfx: 'click' },
      { tipo: 'clip', clip: '03-app-metas', seg: 0.8, sfx: 'click' },
      { tipo: 'clip', clip: '03-app-studio', seg: 1.4, sfx: 'click' },
      { tipo: 'clip', clip: '04-mosaico', seg: 2, sfx: 'click' },
      { tipo: 'clip', clip: '04-editor', seg: 2.2, sfx: 'click' },
      { tipo: 'clip', clip: '04-temas', seg: 3.43, sfx: 'wow' },
      { tipo: 'clip', clip: '05-calendario', seg: 1.7, sfx: 'click' },
      { tipo: 'clip', clip: '05-misiones', seg: 1.7, sfx: 'click' },
      { tipo: 'clip', clip: '05-cronograma', seg: 1.8, sfx: 'click' },
      { tipo: 'clip', clip: '06-avatar-asistente', seg: 1.7, sfx: 'click' },
      { tipo: 'clip', clip: '06-chat', seg: 2, sfx: 'click' },
      { tipo: 'clip', clip: '06-fotos', seg: 1.5, sfx: 'click' },
      { tipo: 'clip', clip: '06-diagrama', seg: 2, sfx: 'click' },
      { tipo: 'clip', clip: '06-formulas', seg: 1.8, sfx: 'click' },
      { tipo: 'clip', clip: '06-grafica', seg: 2, sfx: 'click' },
      { tipo: 'clip', clip: '07-sisifo', seg: 4.11, sfx: 'click' },
      { tipo: 'clip', clip: '07-wrapped', seg: 3.95, sfx: 'nice' },
      { tipo: 'clip', clip: '07-baile', seg: 5.45, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'ja', seg: 0.45, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'ar', seg: 0.45, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'hi', seg: 0.45, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'ko', seg: 0.45, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'ru', seg: 0.45, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'zh', seg: 0.45, sfx: 'click' },
      { tipo: 'escritorio', seg: 1.9, sfx: 'click' },
      { tipo: 'clip', clip: '07-panel-ia', seg: 2.98, sfx: 'click' },
      { tipo: 'clip', clip: '09-atardecer', seg: 3.45, sfx: 'click' },
      { tipo: 'cierre', seg: 6.5, sfx: 'golpe' },
      { tipo: 'clip', clip: '01-avatar', seg: 0.8 }
    ],
    voces: [
      { linea: 'gancho', desde: 0.1, seg: 2.1 },
      { linea: 'casa', desde: 4.2, seg: 6.26 },
      { linea: 'disena', desde: 11.4, seg: 7.38 },
      { linea: 'metas', desde: 19.03, seg: 6.61 },
      { linea: 'ia', desde: 25.93, seg: 7.64 },
      { linea: 'cerebro', desde: 35.23, seg: 11.11 },
      { linea: 'idiomas', desde: 48.74, seg: 7.33 },
      { linea: 'cta', desde: 56.32, seg: 3.2 },
      { linea: 'eslogan', desde: 59.77, seg: 5.5 }
    ],
    rotulos: [
      { clave: 'gancho', desde: 0.25, hasta: 4.1 },
      { clave: 'apps', desde: 6.5, hasta: 11.3 },
      { clave: 'disena', desde: 11.6, hasta: 15.3 },
      { clave: 'personaliza', desde: 15.7, hasta: 18.93 },
      { clave: 'metas', desde: 19.23, hasta: 24.13 },
      { clave: 'ia', desde: 26.13, hasta: 30.63 },
      { clave: 'progreso', desde: 38.53, hasta: 43.73 },
      { clave: 'idiomas', desde: 48.74, hasta: 51.24 },
      { clave: 'plataformas', desde: 51.44, hasta: 53.14 },
      { clave: 'conSinIa', desde: 53.34, hasta: 56.22 }
    ],
    efectos: [
      { clave: 'faa', desde: 2.3 },
      { clave: 'aaa', desde: 46.44 }
    ]
  },
  it: {
    nombre: 'Spot di MPH',
    clips: 'en',
    lineas: {
      gancho: 'E se il Tamagotchi… fossi tu?',
      casa: 'MPH è una casa 3D in cui ogni stanza è un\'app: cucina, allenamento, finanze, obiettivi, musica…',
      disena: 'Progetta la tua casa e decidi quale app va in ogni stanza: il tuo centro di intrattenimento, studio, creatività e cura di te.',
      metas: 'La tua agenda, il tuo calendario, il tuo diario di bordo e un assistente personale per raggiungere i tuoi obiettivi nella vita reale.',
      ia: 'Parla con i tuoi assistenti come faresti con ChatGPT, Gemini o Claude: registrano la tua giornata e creano immagini, risorse e modelli 3D.',
      cerebro: 'I social frammentano la tua attenzione e la tecnologia pensa al posto tuo. MPH è il modo più completo e divertente di usare il cervello e vedere crescere le abitudini che scegli tu.',
      idiomas: 'In 16 lingue. Web, desktop e mobile. Con crediti IA, con modelli locali gratuiti… o senza IA.',
      cta: 'Provala gratis. Oppure falla tua con un solo pagamento.',
      eslogan: 'Costruisci il tuo personaggio costruendo le tue abitudini. Progetta la tua casa, progettando il tuo futuro.'
    },
    titulares: {
      gancho: 'E se tu fossi un Tamagotchi?',
      apps: '21 app · 1 casa',
      disena: 'La tua casa, le tue app',
      metas: 'Obiettivi veri',
      ia: 'IA opzionale',
      progreso: 'I tuoi progressi, visibili',
      idiomas: '16 lingue',
      plataformas: 'Web · PC · Mobile',
      conSinIa: 'Con IA… o senza',
      personaliza: 'Personalizza la tua casa'
    },
    cierre: [
      'Costruisci il tuo personaggio, costruendo le tue abitudini.',
      'Progetta la tua casa, progettando il tuo futuro.',
      'Conquista gli obiettivi delle stanze, conquistando le tue cose da fare.'
    ],
    gratis: 'Provala gratis',
    tomas: [
      { tipo: 'clip', clip: '01-avatar', seg: 4 },
      { tipo: 'clip', clip: '02-casa-gira', seg: 2.4, sfx: 'click' },
      { tipo: 'clip', clip: '03-app-cocina', seg: 0.8, sfx: 'click' },
      { tipo: 'clip', clip: '03-app-ejercicio', seg: 1, sfx: 'click' },
      { tipo: 'clip', clip: '03-app-finanzas', seg: 0.8, sfx: 'click' },
      { tipo: 'clip', clip: '03-app-metas', seg: 0.8, sfx: 'click' },
      { tipo: 'clip', clip: '03-app-studio', seg: 1.64, sfx: 'click' },
      { tipo: 'clip', clip: '04-mosaico', seg: 2, sfx: 'click' },
      { tipo: 'clip', clip: '04-editor', seg: 2.2, sfx: 'click' },
      { tipo: 'clip', clip: '04-temas', seg: 3.13, sfx: 'wow' },
      { tipo: 'clip', clip: '05-calendario', seg: 1.7, sfx: 'click' },
      { tipo: 'clip', clip: '05-misiones', seg: 1.7, sfx: 'click' },
      { tipo: 'clip', clip: '05-cronograma', seg: 1.8, sfx: 'click' },
      { tipo: 'clip', clip: '06-avatar-asistente', seg: 2.44, sfx: 'click' },
      { tipo: 'clip', clip: '06-chat', seg: 2, sfx: 'click' },
      { tipo: 'clip', clip: '06-fotos', seg: 1.5, sfx: 'click' },
      { tipo: 'clip', clip: '06-diagrama', seg: 2, sfx: 'click' },
      { tipo: 'clip', clip: '06-formulas', seg: 1.8, sfx: 'click' },
      { tipo: 'clip', clip: '06-grafica', seg: 2, sfx: 'click' },
      { tipo: 'clip', clip: '07-sisifo', seg: 3.2, sfx: 'click' },
      { tipo: 'clip', clip: '07-wrapped', seg: 3.43, sfx: 'nice' },
      { tipo: 'clip', clip: '07-baile', seg: 5.45, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'ja', seg: 0.45, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'ar', seg: 0.45, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'hi', seg: 0.45, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'ko', seg: 0.45, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'ru', seg: 0.45, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'zh', seg: 0.45, sfx: 'click' },
      { tipo: 'escritorio', seg: 1.9, sfx: 'click' },
      { tipo: 'clip', clip: '07-panel-ia', seg: 2.93, sfx: 'click' },
      { tipo: 'clip', clip: '09-atardecer', seg: 3.42, sfx: 'click' },
      { tipo: 'cierre', seg: 6.5, sfx: 'golpe' },
      { tipo: 'clip', clip: '01-avatar', seg: 0.8 }
    ],
    voces: [
      { linea: 'gancho', desde: 0.1, seg: 2 },
      { linea: 'casa', desde: 4.1, seg: 7.19 },
      { linea: 'disena', desde: 11.54, seg: 7.08 },
      { linea: 'metas', desde: 18.87, seg: 7.39 },
      { linea: 'ia', desde: 26.51, seg: 8.21 },
      { linea: 'cerebro', desde: 35.81, seg: 9.68 },
      { linea: 'idiomas', desde: 47.89, seg: 7.28 },
      { linea: 'cta', desde: 55.42, seg: 3.17 },
      { linea: 'eslogan', desde: 58.84, seg: 6.06 }
    ],
    rotulos: [
      { clave: 'gancho', desde: 0.25, hasta: 4 },
      { clave: 'apps', desde: 6.4, hasta: 11.44 },
      { clave: 'disena', desde: 11.74, hasta: 15.44 },
      { clave: 'personaliza', desde: 15.84, hasta: 18.77 },
      { clave: 'metas', desde: 19.07, hasta: 23.97 },
      { clave: 'ia', desde: 26.71, hasta: 31.21 },
      { clave: 'progreso', desde: 39.11, hasta: 44.31 },
      { clave: 'idiomas', desde: 47.89, hasta: 50.39 },
      { clave: 'plataformas', desde: 50.59, hasta: 52.29 },
      { clave: 'conSinIa', desde: 52.49, hasta: 55.32 }
    ],
    efectos: [
      { clave: 'faa', desde: 2.2 },
      { clave: 'aaa', desde: 45.59 }
    ]
  },
  ja: {
    nombre: 'MPHの広告',
    clips: 'en',
    lineas: {
      gancho: 'もし、たまごっちが…あなた自身だったら？',
      casa: 'MPHは、部屋ひとつひとつがアプリになった3Dの家。キッチン、運動、家計、目標、音楽…',
      disena: '家をデザインして、どの部屋にどのアプリを置くか決めよう。娯楽、勉強、創作、そして心と体のケアの拠点に。',
      metas: '手帳、カレンダー、日誌、そして現実の目標を叶えるためのパーソナルアシスタント。',
      ia: 'ChatGPTやGemini、Claudeと話すように、アシスタントと会話しよう。毎日を記録し、画像や素材、3Dモデルまで作ってくれる。',
      cerebro: 'SNSは集中力を細切れにし、テクノロジーはあなたの代わりに考える。MPHは、脳を使い、自分で選んだ習慣の成長を実感できる、いちばん充実して楽しい方法。',
      idiomas: '16言語対応。Web、デスクトップ、スマホで。AIクレジットでも、無料のローカルモデルでも…AIなしでも。',
      cta: '無料で試そう。気に入ったら、一回払いで自分のものに。',
      eslogan: '習慣を育てて、キャラクターを育てる。家をデザインして、未来をデザインする。'
    },
    titulares: {
      gancho: 'もしあなたがたまごっちだったら？',
      apps: '21のアプリ · 1つの家',
      disena: 'あなたの家、あなたのアプリ',
      metas: '本物の目標',
      ia: 'AIは任意',
      progreso: '成長が、見える',
      idiomas: '16言語',
      plataformas: 'Web · PC · スマホ',
      conSinIa: 'AIあり…でも、なしでも',
      personaliza: '家を自分好みに'
    },
    cierre: [
      '習慣を育てて、キャラクターを育てる。',
      '家をデザインして、未来をデザインする。',
      '部屋の目標を制覇して、やることを制覇する。'
    ],
    gratis: '無料で試す',
    tomas: [
      { tipo: 'clip', clip: '01-avatar', seg: 4.67 },
      { tipo: 'clip', clip: '02-casa-gira', seg: 2.4, sfx: 'click' },
      { tipo: 'clip', clip: '03-app-cocina', seg: 0.8, sfx: 'click' },
      { tipo: 'clip', clip: '03-app-ejercicio', seg: 1, sfx: 'click' },
      { tipo: 'clip', clip: '03-app-finanzas', seg: 0.8, sfx: 'click' },
      { tipo: 'clip', clip: '03-app-metas', seg: 0.8, sfx: 'click' },
      { tipo: 'clip', clip: '03-app-studio', seg: 1.71, sfx: 'click' },
      { tipo: 'clip', clip: '04-mosaico', seg: 2, sfx: 'click' },
      { tipo: 'clip', clip: '04-editor', seg: 2.2, sfx: 'click' },
      { tipo: 'clip', clip: '04-temas', seg: 3.91, sfx: 'wow' },
      { tipo: 'clip', clip: '05-calendario', seg: 1.7, sfx: 'click' },
      { tipo: 'clip', clip: '05-misiones', seg: 1.7, sfx: 'click' },
      { tipo: 'clip', clip: '05-cronograma', seg: 1.8, sfx: 'click' },
      { tipo: 'clip', clip: '06-avatar-asistente', seg: 1.7, sfx: 'click' },
      { tipo: 'clip', clip: '06-chat', seg: 2, sfx: 'click' },
      { tipo: 'clip', clip: '06-fotos', seg: 1.5, sfx: 'click' },
      { tipo: 'clip', clip: '06-diagrama', seg: 2, sfx: 'click' },
      { tipo: 'clip', clip: '06-formulas', seg: 1.8, sfx: 'click' },
      { tipo: 'clip', clip: '06-grafica', seg: 2, sfx: 'click' },
      { tipo: 'clip', clip: '07-sisifo', seg: 3.68, sfx: 'click' },
      { tipo: 'clip', clip: '07-wrapped', seg: 3.95, sfx: 'nice' },
      { tipo: 'clip', clip: '07-baile', seg: 5.45, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'ar', seg: 0.45, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'hi', seg: 0.45, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'ko', seg: 0.45, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'ru', seg: 0.45, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'zh', seg: 0.45, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'de', seg: 0.45, sfx: 'click' },
      { tipo: 'escritorio', seg: 1.9, sfx: 'click' },
      { tipo: 'clip', clip: '07-panel-ia', seg: 2.96, sfx: 'click' },
      { tipo: 'clip', clip: '09-atardecer', seg: 3.58, sfx: 'click' },
      { tipo: 'cierre', seg: 6.5, sfx: 'golpe' },
      { tipo: 'clip', clip: '01-avatar', seg: 0.8 }
    ],
    voces: [
      { linea: 'gancho', desde: 0.1, seg: 2.67 },
      { linea: 'casa', desde: 4.77, seg: 7.26 },
      { linea: 'disena', desde: 12.28, seg: 7.86 },
      { linea: 'metas', desde: 20.39, seg: 5.46 },
      { linea: 'ia', desde: 27.29, seg: 9.01 },
      { linea: 'cerebro', desde: 36.59, seg: 10.68 },
      { linea: 'idiomas', desde: 49.67, seg: 7.31 },
      { linea: 'cta', desde: 57.23, seg: 3.33 },
      { linea: 'eslogan', desde: 60.81, seg: 5.13 }
    ],
    rotulos: [
      { clave: 'gancho', desde: 0.25, hasta: 4.67 },
      { clave: 'apps', desde: 7.07, hasta: 12.18 },
      { clave: 'disena', desde: 12.48, hasta: 16.18 },
      { clave: 'personaliza', desde: 16.58, hasta: 20.29 },
      { clave: 'metas', desde: 20.59, hasta: 25.49 },
      { clave: 'ia', desde: 27.49, hasta: 31.99 },
      { clave: 'progreso', desde: 39.89, hasta: 45.09 },
      { clave: 'idiomas', desde: 49.67, hasta: 52.17 },
      { clave: 'plataformas', desde: 52.37, hasta: 54.07 },
      { clave: 'conSinIa', desde: 54.27, hasta: 57.13 }
    ],
    efectos: [
      { clave: 'faa', desde: 2.87 },
      { clave: 'aaa', desde: 47.37 }
    ]
  },
  zh: {
    nombre: 'MPH 广告',
    clips: 'en',
    lineas: {
      gancho: '如果那只电子宠物……就是你自己呢？',
      casa: 'MPH 是一座 3D 的家，每个房间都是一个应用：厨房、健身、理财、目标、音乐……',
      disena: '设计你的家，决定每个房间放哪个应用：你的娱乐、学习、创作和身心照护中心。',
      metas: '你的日程、日历、日志，还有一位私人助手，帮你在现实生活中达成目标。',
      ia: '像和 ChatGPT、Gemini 或 Claude 聊天一样和助手交谈：他们记录你的每一天，还能生成图片、素材和 3D 模型。',
      cerebro: '社交媒体切碎了你的注意力，科技替你思考。MPH 是最完整、最有趣的方式，让你用脑，看见自己选择的习惯一点点进步。',
      idiomas: '支持 16 种语言。网页、桌面和手机。可以用 AI 点数，可以用免费的本地模型……也可以完全不用 AI。',
      cta: '免费试用。喜欢的话，一次付费，永久拥有。',
      eslogan: '养成习惯，养成你的角色。设计你的家，设计你的未来。'
    },
    titulares: {
      gancho: '如果你是电子宠物呢？',
      apps: '21 个应用 · 1 座家',
      disena: '你的家，你的应用',
      metas: '真实的目标',
      ia: 'AI 可选',
      progreso: '进步，看得见',
      idiomas: '16 种语言',
      plataformas: '网页 · 电脑 · 手机',
      conSinIa: '有 AI……没有也行',
      personaliza: '定制你的家'
    },
    cierre: [
      '养成习惯，养成你的角色。',
      '设计你的家，设计你的未来。',
      '攻克每个房间的目标，攻克你的待办。'
    ],
    gratis: '免费试用',
    tomas: [
      { tipo: 'clip', clip: '01-avatar', seg: 4.65 },
      { tipo: 'clip', clip: '02-casa-gira', seg: 2.4, sfx: 'click' },
      { tipo: 'clip', clip: '03-app-cocina', seg: 0.8, sfx: 'click' },
      { tipo: 'clip', clip: '03-app-ejercicio', seg: 1, sfx: 'click' },
      { tipo: 'clip', clip: '03-app-finanzas', seg: 0.8, sfx: 'click' },
      { tipo: 'clip', clip: '03-app-metas', seg: 0.8, sfx: 'click' },
      { tipo: 'clip', clip: '03-app-studio', seg: 1.81, sfx: 'click' },
      { tipo: 'clip', clip: '04-mosaico', seg: 2, sfx: 'click' },
      { tipo: 'clip', clip: '04-editor', seg: 2.2, sfx: 'click' },
      { tipo: 'clip', clip: '04-temas', seg: 3, sfx: 'wow' },
      { tipo: 'clip', clip: '05-calendario', seg: 1.7, sfx: 'click' },
      { tipo: 'clip', clip: '05-misiones', seg: 1.7, sfx: 'click' },
      { tipo: 'clip', clip: '05-cronograma', seg: 1.8, sfx: 'click' },
      { tipo: 'clip', clip: '06-avatar-asistente', seg: 1.7, sfx: 'click' },
      { tipo: 'clip', clip: '06-chat', seg: 2, sfx: 'click' },
      { tipo: 'clip', clip: '06-fotos', seg: 1.5, sfx: 'click' },
      { tipo: 'clip', clip: '06-diagrama', seg: 2, sfx: 'click' },
      { tipo: 'clip', clip: '06-formulas', seg: 1.8, sfx: 'click' },
      { tipo: 'clip', clip: '06-grafica', seg: 2, sfx: 'click' },
      { tipo: 'clip', clip: '07-sisifo', seg: 3.2, sfx: 'click' },
      { tipo: 'clip', clip: '07-wrapped', seg: 2.9, sfx: 'nice' },
      { tipo: 'clip', clip: '07-baile', seg: 5.45, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'ja', seg: 0.45, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'ar', seg: 0.45, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'hi', seg: 0.45, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'ko', seg: 0.45, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'ru', seg: 0.45, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'de', seg: 0.45, sfx: 'click' },
      { tipo: 'escritorio', seg: 1.9, sfx: 'click' },
      { tipo: 'clip', clip: '07-panel-ia', seg: 3.59, sfx: 'click' },
      { tipo: 'clip', clip: '09-atardecer', seg: 3.69, sfx: 'click' },
      { tipo: 'cierre', seg: 6.5, sfx: 'golpe' },
      { tipo: 'clip', clip: '01-avatar', seg: 0.8 }
    ],
    voces: [
      { linea: 'gancho', desde: 0.1, seg: 2.65 },
      { linea: 'casa', desde: 4.75, seg: 7.36 },
      { linea: 'disena', desde: 12.36, seg: 6.25 },
      { linea: 'metas', desde: 19.56, seg: 5.57 },
      { linea: 'ia', desde: 26.46, seg: 8.71 },
      { linea: 'cerebro', desde: 35.76, seg: 9.15 },
      { linea: 'idiomas', desde: 47.31, seg: 7.94 },
      { linea: 'cta', desde: 55.5, seg: 3.44 },
      { linea: 'eslogan', desde: 59.19, seg: 4.47 }
    ],
    rotulos: [
      { clave: 'gancho', desde: 0.25, hasta: 4.65 },
      { clave: 'apps', desde: 7.05, hasta: 12.26 },
      { clave: 'disena', desde: 12.56, hasta: 16.26 },
      { clave: 'personaliza', desde: 16.66, hasta: 19.46 },
      { clave: 'metas', desde: 19.76, hasta: 24.66 },
      { clave: 'ia', desde: 26.66, hasta: 31.16 },
      { clave: 'progreso', desde: 39.06, hasta: 44.26 },
      { clave: 'idiomas', desde: 47.31, hasta: 49.81 },
      { clave: 'plataformas', desde: 50.01, hasta: 51.71 },
      { clave: 'conSinIa', desde: 51.91, hasta: 55.4 }
    ],
    efectos: [
      { clave: 'faa', desde: 2.85 },
      { clave: 'aaa', desde: 45.01 }
    ]
  },
  ko: {
    nombre: 'MPH 광고',
    clips: 'en',
    lineas: {
      gancho: '만약 그 다마고치가… 바로 당신이라면?',
      casa: 'MPH는 방 하나하나가 앱인 3D 집이에요. 주방, 운동, 재정, 목표, 음악…',
      disena: '집을 디자인하고 어떤 방에 어떤 앱을 둘지 정하세요. 즐거움, 공부, 창작, 몸과 마음 돌봄의 중심이 됩니다.',
      metas: '일정, 달력, 일지, 그리고 현실의 목표를 이루도록 돕는 개인 비서까지.',
      ia: 'ChatGPT, Gemini, Claude와 이야기하듯 비서와 대화하세요. 하루를 기록하고 이미지, 자료, 3D 모델까지 만들어 줍니다.',
      cerebro: 'SNS는 집중력을 조각내고, 기술은 당신 대신 생각합니다. MPH는 뇌를 쓰고, 스스로 고른 습관이 자라는 걸 지켜보는 가장 완전하고 재미있는 방법이에요.',
      idiomas: '16개 언어. 웹, 데스크톱, 모바일. AI 크레딧으로, 무료 로컬 모델로… 아니면 AI 없이도.',
      cta: '무료로 써 보세요. 마음에 들면 한 번 결제로 내 것으로.',
      eslogan: '습관을 쌓아 캐릭터를 키우고, 집을 디자인하며 미래를 디자인하세요.'
    },
    titulares: {
      gancho: '당신이 다마고치라면?',
      apps: '앱 21개 · 집 1채',
      disena: '당신의 집, 당신의 앱',
      metas: '진짜 목표',
      ia: 'AI는 선택',
      progreso: '성장이 보인다',
      idiomas: '16개 언어',
      plataformas: '웹 · PC · 모바일',
      conSinIa: 'AI와 함께… 또는 없이',
      personaliza: '집을 내 취향대로'
    },
    cierre: [
      '습관을 쌓아, 캐릭터를 키우세요.',
      '집을 디자인하며, 미래를 디자인하세요.',
      '방의 목표를 정복하며, 할 일을 정복하세요.'
    ],
    gratis: '무료로 써 보기',
    tomas: [
      { tipo: 'clip', clip: '01-avatar', seg: 4.5 },
      { tipo: 'clip', clip: '02-casa-gira', seg: 2.4, sfx: 'click' },
      { tipo: 'clip', clip: '03-app-cocina', seg: 0.8, sfx: 'click' },
      { tipo: 'clip', clip: '03-app-ejercicio', seg: 1, sfx: 'click' },
      { tipo: 'clip', clip: '03-app-finanzas', seg: 0.8, sfx: 'click' },
      { tipo: 'clip', clip: '03-app-metas', seg: 0.8, sfx: 'click' },
      { tipo: 'clip', clip: '03-app-studio', seg: 1.4, sfx: 'click' },
      { tipo: 'clip', clip: '04-mosaico', seg: 2, sfx: 'click' },
      { tipo: 'clip', clip: '04-editor', seg: 2.2, sfx: 'click' },
      { tipo: 'clip', clip: '04-temas', seg: 3.57, sfx: 'wow' },
      { tipo: 'clip', clip: '05-calendario', seg: 1.7, sfx: 'click' },
      { tipo: 'clip', clip: '05-misiones', seg: 1.7, sfx: 'click' },
      { tipo: 'clip', clip: '05-cronograma', seg: 1.8, sfx: 'click' },
      { tipo: 'clip', clip: '06-avatar-asistente', seg: 1.7, sfx: 'click' },
      { tipo: 'clip', clip: '06-chat', seg: 2, sfx: 'click' },
      { tipo: 'clip', clip: '06-fotos', seg: 1.5, sfx: 'click' },
      { tipo: 'clip', clip: '06-diagrama', seg: 2, sfx: 'click' },
      { tipo: 'clip', clip: '06-formulas', seg: 1.8, sfx: 'click' },
      { tipo: 'clip', clip: '06-grafica', seg: 2, sfx: 'click' },
      { tipo: 'clip', clip: '07-sisifo', seg: 3.2, sfx: 'click' },
      { tipo: 'clip', clip: '07-wrapped', seg: 3.77, sfx: 'nice' },
      { tipo: 'clip', clip: '07-baile', seg: 5.45, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'ja', seg: 0.45, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'ar', seg: 0.45, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'hi', seg: 0.45, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'ru', seg: 0.45, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'zh', seg: 0.45, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'de', seg: 0.45, sfx: 'click' },
      { tipo: 'escritorio', seg: 1.9, sfx: 'click' },
      { tipo: 'clip', clip: '07-panel-ia', seg: 2.6, sfx: 'click' },
      { tipo: 'clip', clip: '09-atardecer', seg: 3.46, sfx: 'click' },
      { tipo: 'cierre', seg: 6.5, sfx: 'golpe' },
      { tipo: 'clip', clip: '01-avatar', seg: 0.8 }
    ],
    voces: [
      { linea: 'gancho', desde: 0.1, seg: 2.5 },
      { linea: 'casa', desde: 4.6, seg: 6.54 },
      { linea: 'disena', desde: 11.8, seg: 7.52 },
      { linea: 'metas', desde: 19.57, seg: 5.44 },
      { linea: 'ia', desde: 26.47, seg: 7.99 },
      { linea: 'cerebro', desde: 35.77, seg: 10.02 },
      { linea: 'idiomas', desde: 48.19, seg: 6.8 },
      { linea: 'cta', desde: 55.39, seg: 3.21 },
      { linea: 'eslogan', desde: 58.85, seg: 4.37 }
    ],
    rotulos: [
      { clave: 'gancho', desde: 0.25, hasta: 4.5 },
      { clave: 'apps', desde: 6.9, hasta: 11.7 },
      { clave: 'disena', desde: 12, hasta: 15.7 },
      { clave: 'personaliza', desde: 16.1, hasta: 19.47 },
      { clave: 'metas', desde: 19.77, hasta: 24.67 },
      { clave: 'ia', desde: 26.67, hasta: 31.17 },
      { clave: 'progreso', desde: 39.07, hasta: 44.27 },
      { clave: 'idiomas', desde: 48.19, hasta: 50.69 },
      { clave: 'plataformas', desde: 50.89, hasta: 52.59 },
      { clave: 'conSinIa', desde: 52.79, hasta: 55.29 }
    ],
    efectos: [
      { clave: 'faa', desde: 2.7 },
      { clave: 'aaa', desde: 45.89 }
    ]
  },
  ru: {
    nombre: 'Реклама MPH',
    clips: 'en',
    lineas: {
      gancho: 'А если бы тамагочи… был ты?',
      casa: 'MPH — это 3D-дом, где каждая комната — приложение: кухня, тренировки, финансы, цели, музыка…',
      disena: 'Спроектируй свой дом и реши, какое приложение будет в каждой комнате: твой центр развлечений, учёбы, творчества и заботы о себе.',
      metas: 'Твой ежедневник, календарь, бортовой журнал и личный ассистент, чтобы достигать целей в реальной жизни.',
      ia: 'Общайся с ассистентами, как с ChatGPT, Gemini или Claude: они записывают твой день и создают изображения, материалы и 3D-модели.',
      cerebro: 'Соцсети дробят твоё внимание, а технологии думают за тебя. MPH — самый полный и увлекательный способ использовать мозг и видеть, как растут привычки, которые выбираешь ты сам.',
      idiomas: 'На 16 языках. Веб, компьютер и телефон. С кредитами ИИ, с бесплатными локальными моделями… или вовсе без ИИ.',
      cta: 'Попробуй бесплатно. Или сделай своим за один платёж.',
      eslogan: 'Строй персонажа, выстраивая привычки. Проектируй дом — проектируй будущее.'
    },
    titulares: {
      gancho: 'А если бы ты был тамагочи?',
      apps: '21 приложение · 1 дом',
      disena: 'Твой дом, твои приложения',
      metas: 'Настоящие цели',
      ia: 'ИИ по желанию',
      progreso: 'Прогресс на виду',
      idiomas: '16 языков',
      plataformas: 'Веб · ПК · Телефон',
      conSinIa: 'С ИИ… или без',
      personaliza: 'Обустрой свой дом'
    },
    cierre: [
      'Строй персонажа, выстраивая привычки.',
      'Проектируй дом, проектируя будущее.',
      'Покоряй цели комнат, разбираясь с делами.'
    ],
    gratis: 'Попробовать бесплатно',
    tomas: [
      { tipo: 'clip', clip: '01-avatar', seg: 3.88 },
      { tipo: 'clip', clip: '02-casa-gira', seg: 2.4, sfx: 'click' },
      { tipo: 'clip', clip: '03-app-cocina', seg: 0.8, sfx: 'click' },
      { tipo: 'clip', clip: '03-app-ejercicio', seg: 1, sfx: 'click' },
      { tipo: 'clip', clip: '03-app-finanzas', seg: 0.8, sfx: 'click' },
      { tipo: 'clip', clip: '03-app-metas', seg: 0.8, sfx: 'click' },
      { tipo: 'clip', clip: '03-app-studio', seg: 1.4, sfx: 'click' },
      { tipo: 'clip', clip: '04-mosaico', seg: 2, sfx: 'click' },
      { tipo: 'clip', clip: '04-editor', seg: 2.2, sfx: 'click' },
      { tipo: 'clip', clip: '04-temas', seg: 3.1, sfx: 'wow' },
      { tipo: 'clip', clip: '05-calendario', seg: 1.7, sfx: 'click' },
      { tipo: 'clip', clip: '05-misiones', seg: 1.7, sfx: 'click' },
      { tipo: 'clip', clip: '05-cronograma', seg: 1.8, sfx: 'click' },
      { tipo: 'clip', clip: '06-avatar-asistente', seg: 1.7, sfx: 'click' },
      { tipo: 'clip', clip: '06-chat', seg: 2, sfx: 'click' },
      { tipo: 'clip', clip: '06-fotos', seg: 1.5, sfx: 'click' },
      { tipo: 'clip', clip: '06-diagrama', seg: 2, sfx: 'click' },
      { tipo: 'clip', clip: '06-formulas', seg: 1.8, sfx: 'click' },
      { tipo: 'clip', clip: '06-grafica', seg: 2, sfx: 'click' },
      { tipo: 'clip', clip: '07-sisifo', seg: 3.2, sfx: 'click' },
      { tipo: 'clip', clip: '07-wrapped', seg: 3.57, sfx: 'nice' },
      { tipo: 'clip', clip: '07-baile', seg: 5.45, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'ja', seg: 0.45, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'ar', seg: 0.45, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'hi', seg: 0.45, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'ko', seg: 0.45, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'zh', seg: 0.45, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'de', seg: 0.45, sfx: 'click' },
      { tipo: 'escritorio', seg: 1.9, sfx: 'click' },
      { tipo: 'clip', clip: '07-panel-ia', seg: 2.65, sfx: 'click' },
      { tipo: 'clip', clip: '09-atardecer', seg: 3.24, sfx: 'click' },
      { tipo: 'cierre', seg: 6.5, sfx: 'golpe' },
      { tipo: 'clip', clip: '01-avatar', seg: 0.8 }
    ],
    voces: [
      { linea: 'gancho', desde: 0.1, seg: 1.88 },
      { linea: 'casa', desde: 3.98, seg: 6.95 },
      { linea: 'disena', desde: 11.18, seg: 7.05 },
      { linea: 'metas', desde: 18.48, seg: 5.35 },
      { linea: 'ia', desde: 25.38, seg: 7.09 },
      { linea: 'cerebro', desde: 34.68, seg: 9.82 },
      { linea: 'idiomas', desde: 46.9, seg: 7 },
      { linea: 'cta', desde: 54.15, seg: 2.99 },
      { linea: 'eslogan', desde: 57.39, seg: 4.73 }
    ],
    rotulos: [
      { clave: 'gancho', desde: 0.25, hasta: 3.88 },
      { clave: 'apps', desde: 6.28, hasta: 11.08 },
      { clave: 'disena', desde: 11.38, hasta: 15.08 },
      { clave: 'personaliza', desde: 15.48, hasta: 18.38 },
      { clave: 'metas', desde: 18.68, hasta: 23.58 },
      { clave: 'ia', desde: 25.58, hasta: 30.08 },
      { clave: 'progreso', desde: 37.98, hasta: 43.18 },
      { clave: 'idiomas', desde: 46.9, hasta: 49.4 },
      { clave: 'plataformas', desde: 49.6, hasta: 51.3 },
      { clave: 'conSinIa', desde: 51.5, hasta: 54.05 }
    ],
    efectos: [
      { clave: 'faa', desde: 2.08 },
      { clave: 'aaa', desde: 44.6 }
    ]
  },
  hi: {
    nombre: 'MPH का विज्ञापन',
    clips: 'en',
    lineas: {
      gancho: 'और अगर वो तमागोची… तुम ही होते?',
      casa: 'MPH एक 3D घर है, जहाँ हर कमरा एक ऐप है: रसोई, कसरत, पैसे, लक्ष्य, संगीत…',
      disena: 'अपना घर डिज़ाइन करो और तय करो कि किस कमरे में कौन-सा ऐप रहेगा: मनोरंजन, पढ़ाई, रचनात्मकता और अपनी देखभाल का केंद्र।',
      metas: 'तुम्हारा एजेंडा, कैलेंडर, डायरी और एक निजी सहायक, ताकि असली ज़िंदगी में लक्ष्य पूरे हों।',
      ia: 'अपने सहायकों से वैसे ही बात करो जैसे ChatGPT, Gemini या Claude से: वे तुम्हारा दिन दर्ज करते हैं और तस्वीरें, सामग्री और 3D मॉडल बनाते हैं।',
      cerebro: 'सोशल मीडिया तुम्हारा ध्यान बिखेरता है और तकनीक तुम्हारी जगह सोचती है। MPH दिमाग़ इस्तेमाल करने और अपनी चुनी हुई आदतों को बढ़ते देखने का सबसे संपूर्ण और मज़ेदार तरीका है।',
      idiomas: '16 भाषाओं में। वेब, डेस्कटॉप और मोबाइल पर। AI क्रेडिट के साथ, मुफ़्त लोकल मॉडल के साथ… या बिना AI के।',
      cta: 'मुफ़्त में आज़माओ। या एक ही भुगतान में इसे अपना बना लो।',
      eslogan: 'आदतें बनाते हुए अपना किरदार बनाओ। घर डिज़ाइन करते हुए अपना भविष्य डिज़ाइन करो।'
    },
    titulares: {
      gancho: 'अगर तुम एक तमागोची होते तो?',
      apps: '21 ऐप · 1 घर',
      disena: 'तुम्हारा घर, तुम्हारे ऐप',
      metas: 'असली लक्ष्य',
      ia: 'AI वैकल्पिक',
      progreso: 'तुम्हारी प्रगति, सामने',
      idiomas: '16 भाषाएँ',
      plataformas: 'वेब · PC · मोबाइल',
      conSinIa: 'AI के साथ… या बिना',
      personaliza: 'अपना घर सजाओ'
    },
    cierre: [
      'आदतें बनाते हुए, अपना किरदार बनाओ।',
      'घर डिज़ाइन करते हुए, अपना भविष्य डिज़ाइन करो।',
      'कमरों के लक्ष्य जीतते हुए, अपने काम निपटाओ।'
    ],
    gratis: 'मुफ़्त में आज़माओ',
    tomas: [
      { tipo: 'clip', clip: '01-avatar', seg: 4.62 },
      { tipo: 'clip', clip: '02-casa-gira', seg: 2.4, sfx: 'click' },
      { tipo: 'clip', clip: '03-app-cocina', seg: 0.8, sfx: 'click' },
      { tipo: 'clip', clip: '03-app-ejercicio', seg: 1, sfx: 'click' },
      { tipo: 'clip', clip: '03-app-finanzas', seg: 0.8, sfx: 'click' },
      { tipo: 'clip', clip: '03-app-metas', seg: 0.8, sfx: 'click' },
      { tipo: 'clip', clip: '03-app-studio', seg: 1.4, sfx: 'click' },
      { tipo: 'clip', clip: '04-mosaico', seg: 2, sfx: 'click' },
      { tipo: 'clip', clip: '04-editor', seg: 2.2, sfx: 'click' },
      { tipo: 'clip', clip: '04-temas', seg: 4.41, sfx: 'wow' },
      { tipo: 'clip', clip: '05-calendario', seg: 1.7, sfx: 'click' },
      { tipo: 'clip', clip: '05-misiones', seg: 1.7, sfx: 'click' },
      { tipo: 'clip', clip: '05-cronograma', seg: 1.8, sfx: 'click' },
      { tipo: 'clip', clip: '06-avatar-asistente', seg: 1.7, sfx: 'click' },
      { tipo: 'clip', clip: '06-chat', seg: 2, sfx: 'click' },
      { tipo: 'clip', clip: '06-fotos', seg: 1.5, sfx: 'click' },
      { tipo: 'clip', clip: '06-diagrama', seg: 2, sfx: 'click' },
      { tipo: 'clip', clip: '06-formulas', seg: 1.8, sfx: 'click' },
      { tipo: 'clip', clip: '06-grafica', seg: 2, sfx: 'click' },
      { tipo: 'clip', clip: '07-sisifo', seg: 3.49, sfx: 'click' },
      { tipo: 'clip', clip: '07-wrapped', seg: 3.95, sfx: 'nice' },
      { tipo: 'clip', clip: '07-baile', seg: 5.45, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'ja', seg: 0.45, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'ar', seg: 0.45, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'ko', seg: 0.45, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'ru', seg: 0.45, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'zh', seg: 0.45, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'de', seg: 0.45, sfx: 'click' },
      { tipo: 'escritorio', seg: 1.9, sfx: 'click' },
      { tipo: 'clip', clip: '07-panel-ia', seg: 2.9, sfx: 'click' },
      { tipo: 'clip', clip: '09-atardecer', seg: 3.77, sfx: 'click' },
      { tipo: 'cierre', seg: 6.5, sfx: 'golpe' },
      { tipo: 'clip', clip: '01-avatar', seg: 0.8 }
    ],
    voces: [
      { linea: 'gancho', desde: 0.1, seg: 2.62 },
      { linea: 'casa', desde: 4.72, seg: 6.55 },
      { linea: 'disena', desde: 11.92, seg: 8.36 },
      { linea: 'metas', desde: 20.53, seg: 6.07 },
      { linea: 'ia', desde: 27.43, seg: 8.45 },
      { linea: 'cerebro', desde: 36.73, seg: 10.49 },
      { linea: 'idiomas', desde: 49.62, seg: 7.25 },
      { linea: 'cta', desde: 57.12, seg: 3.52 },
      { linea: 'eslogan', desde: 60.89, seg: 5.5 }
    ],
    rotulos: [
      { clave: 'gancho', desde: 0.25, hasta: 4.62 },
      { clave: 'apps', desde: 7.02, hasta: 11.82 },
      { clave: 'disena', desde: 12.12, hasta: 15.82 },
      { clave: 'personaliza', desde: 16.22, hasta: 20.43 },
      { clave: 'metas', desde: 20.73, hasta: 25.63 },
      { clave: 'ia', desde: 27.63, hasta: 32.13 },
      { clave: 'progreso', desde: 40.03, hasta: 45.23 },
      { clave: 'idiomas', desde: 49.62, hasta: 52.12 },
      { clave: 'plataformas', desde: 52.32, hasta: 54.02 },
      { clave: 'conSinIa', desde: 54.22, hasta: 57.02 }
    ],
    efectos: [
      { clave: 'faa', desde: 2.82 },
      { clave: 'aaa', desde: 47.32 }
    ]
  },
  tr: {
    nombre: 'MPH reklamı',
    clips: 'en',
    lineas: {
      gancho: 'Ya o Tamagotchi… sen olsaydın?',
      casa: 'MPH, her odası bir uygulama olan 3D bir ev: mutfak, egzersiz, finans, hedefler, müzik…',
      disena: 'Evini tasarla ve her odaya hangi uygulamanın gireceğine karar ver: eğlence, ders, yaratıcılık ve kendine bakım merkezin.',
      metas: 'Ajandan, takvimin, seyir defterin ve gerçek hayattaki hedeflerine ulaşman için kişisel bir asistan.',
      ia: 'Asistanlarınla ChatGPT, Gemini ya da Claude ile konuşur gibi konuş: gününü kaydeder; görseller, kaynaklar ve 3D modeller üretir.',
      cerebro: 'Sosyal medya dikkatini parçalıyor, teknoloji senin yerine düşünüyor. MPH, beynini kullanmanın ve kendi seçtiğin alışkanlıkların büyüdüğünü görmenin en eksiksiz ve en eğlenceli yolu.',
      idiomas: '16 dilde. Web, masaüstü ve mobil. Yapay zekâ kredisiyle, ücretsiz yerel modellerle… ya da hiç yapay zekâ olmadan.',
      cta: 'Ücretsiz dene. Ya da tek ödemeyle senin olsun.',
      eslogan: 'Alışkanlıklarını kurarak karakterini kur. Evini tasarlarken geleceğini tasarla.'
    },
    titulares: {
      gancho: 'Ya sen bir Tamagotchi olsaydın?',
      apps: '21 uygulama · 1 ev',
      disena: 'Senin evin, senin uygulamaların',
      metas: 'Gerçek hedefler',
      ia: 'Yapay zekâ isteğe bağlı',
      progreso: 'İlerlemen, görünür',
      idiomas: '16 dil',
      plataformas: 'Web · PC · Mobil',
      conSinIa: 'Yapay zekâ ile… ya da onsuz',
      personaliza: 'Evini kişiselleştir'
    },
    cierre: [
      'Alışkanlıklarını kurarak, karakterini kur.',
      'Evini tasarlarken, geleceğini tasarla.',
      'Odaların hedeflerini fethederken, yapılacaklarını bitir.'
    ],
    gratis: 'Ücretsiz dene',
    tomas: [
      { tipo: 'clip', clip: '01-avatar', seg: 3.98 },
      { tipo: 'clip', clip: '02-casa-gira', seg: 2.4, sfx: 'click' },
      { tipo: 'clip', clip: '03-app-cocina', seg: 0.8, sfx: 'click' },
      { tipo: 'clip', clip: '03-app-ejercicio', seg: 1, sfx: 'click' },
      { tipo: 'clip', clip: '03-app-finanzas', seg: 0.8, sfx: 'click' },
      { tipo: 'clip', clip: '03-app-metas', seg: 0.8, sfx: 'click' },
      { tipo: 'clip', clip: '03-app-studio', seg: 1.4, sfx: 'click' },
      { tipo: 'clip', clip: '04-mosaico', seg: 2, sfx: 'click' },
      { tipo: 'clip', clip: '04-editor', seg: 2.2, sfx: 'click' },
      { tipo: 'clip', clip: '04-temas', seg: 3, sfx: 'wow' },
      { tipo: 'clip', clip: '05-calendario', seg: 1.7, sfx: 'click' },
      { tipo: 'clip', clip: '05-misiones', seg: 1.7, sfx: 'click' },
      { tipo: 'clip', clip: '05-cronograma', seg: 1.8, sfx: 'click' },
      { tipo: 'clip', clip: '06-avatar-asistente', seg: 1.7, sfx: 'click' },
      { tipo: 'clip', clip: '06-chat', seg: 2, sfx: 'click' },
      { tipo: 'clip', clip: '06-fotos', seg: 1.5, sfx: 'click' },
      { tipo: 'clip', clip: '06-diagrama', seg: 2, sfx: 'click' },
      { tipo: 'clip', clip: '06-formulas', seg: 1.8, sfx: 'click' },
      { tipo: 'clip', clip: '06-grafica', seg: 2, sfx: 'click' },
      { tipo: 'clip', clip: '07-sisifo', seg: 3.2, sfx: 'click' },
      { tipo: 'clip', clip: '07-wrapped', seg: 3.42, sfx: 'nice' },
      { tipo: 'clip', clip: '07-baile', seg: 5.45, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'ja', seg: 0.45, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'ar', seg: 0.45, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'hi', seg: 0.45, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'ko', seg: 0.45, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'ru', seg: 0.45, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'zh', seg: 0.45, sfx: 'click' },
      { tipo: 'escritorio', seg: 1.9, sfx: 'click' },
      { tipo: 'clip', clip: '07-panel-ia', seg: 2.76, sfx: 'click' },
      { tipo: 'clip', clip: '09-atardecer', seg: 3.2, sfx: 'click' },
      { tipo: 'cierre', seg: 6.5, sfx: 'golpe' },
      { tipo: 'clip', clip: '01-avatar', seg: 0.8 }
    ],
    voces: [
      { linea: 'gancho', desde: 0.1, seg: 1.98 },
      { linea: 'casa', desde: 4.08, seg: 5.8 },
      { linea: 'disena', desde: 11.28, seg: 6.42 },
      { linea: 'metas', desde: 18.48, seg: 5.34 },
      { linea: 'ia', desde: 25.38, seg: 7.44 },
      { linea: 'cerebro', desde: 34.68, seg: 9.67 },
      { linea: 'idiomas', desde: 46.75, seg: 7.11 },
      { linea: 'cta', desde: 54.11, seg: 2.66 },
      { linea: 'eslogan', desde: 57.31, seg: 4.41 }
    ],
    rotulos: [
      { clave: 'gancho', desde: 0.25, hasta: 3.98 },
      { clave: 'apps', desde: 6.38, hasta: 11.18 },
      { clave: 'disena', desde: 11.48, hasta: 15.18 },
      { clave: 'personaliza', desde: 15.58, hasta: 18.38 },
      { clave: 'metas', desde: 18.68, hasta: 23.58 },
      { clave: 'ia', desde: 25.58, hasta: 30.08 },
      { clave: 'progreso', desde: 37.98, hasta: 43.18 },
      { clave: 'idiomas', desde: 46.75, hasta: 49.25 },
      { clave: 'plataformas', desde: 49.45, hasta: 51.15 },
      { clave: 'conSinIa', desde: 51.35, hasta: 54.01 }
    ],
    efectos: [
      { clave: 'faa', desde: 2.18 },
      { clave: 'aaa', desde: 44.45 }
    ]
  },
  id: {
    nombre: 'Iklan MPH',
    clips: 'en',
    lineas: {
      gancho: 'Bagaimana kalau Tamagotchi itu… adalah kamu?',
      casa: 'MPH adalah rumah 3D yang setiap ruangannya adalah aplikasi: dapur, olahraga, keuangan, target, musik…',
      disena: 'Rancang rumahmu dan tentukan aplikasi apa di tiap ruangan: pusat hiburan, belajar, kreativitas, dan perawatan dirimu.',
      metas: 'Agendamu, kalendermu, jurnal harianmu, dan asisten pribadi untuk mencapai targetmu di kehidupan nyata.',
      ia: 'Ngobrol dengan asistenmu seperti dengan ChatGPT, Gemini, atau Claude: mereka mencatat harimu dan membuat gambar, materi, dan model 3D.',
      cerebro: 'Media sosial memecah perhatianmu dan teknologi berpikir untukmu. MPH adalah cara paling lengkap dan seru untuk memakai otakmu dan melihat kebiasaan pilihanmu tumbuh.',
      idiomas: 'Dalam 16 bahasa. Web, desktop, dan ponsel. Dengan kredit AI, dengan model lokal gratis… atau tanpa AI sama sekali.',
      cta: 'Coba gratis. Atau miliki selamanya dengan sekali bayar.',
      eslogan: 'Bangun karaktermu dengan membangun kebiasaanmu. Rancang rumahmu, rancang masa depanmu.'
    },
    titulares: {
      gancho: 'Bagaimana kalau kamu adalah Tamagotchi?',
      apps: '21 aplikasi · 1 rumah',
      disena: 'Rumahmu, aplikasimu',
      metas: 'Target nyata',
      ia: 'AI opsional',
      progreso: 'Kemajuanmu, terlihat',
      idiomas: '16 bahasa',
      plataformas: 'Web · PC · Ponsel',
      conSinIa: 'Dengan AI… atau tanpa',
      personaliza: 'Sesuaikan rumahmu'
    },
    cierre: [
      'Bangun karaktermu, dengan membangun kebiasaanmu.',
      'Rancang rumahmu, sambil merancang masa depanmu.',
      'Taklukkan target tiap ruangan, sambil menuntaskan tugasmu.'
    ],
    gratis: 'Coba gratis',
    tomas: [
      { tipo: 'clip', clip: '01-avatar', seg: 4.57 },
      { tipo: 'clip', clip: '02-casa-gira', seg: 2.4, sfx: 'click' },
      { tipo: 'clip', clip: '03-app-cocina', seg: 0.8, sfx: 'click' },
      { tipo: 'clip', clip: '03-app-ejercicio', seg: 1, sfx: 'click' },
      { tipo: 'clip', clip: '03-app-finanzas', seg: 0.8, sfx: 'click' },
      { tipo: 'clip', clip: '03-app-metas', seg: 0.8, sfx: 'click' },
      { tipo: 'clip', clip: '03-app-studio', seg: 1.4, sfx: 'click' },
      { tipo: 'clip', clip: '04-mosaico', seg: 2, sfx: 'click' },
      { tipo: 'clip', clip: '04-editor', seg: 2.2, sfx: 'click' },
      { tipo: 'clip', clip: '04-temas', seg: 3, sfx: 'wow' },
      { tipo: 'clip', clip: '05-calendario', seg: 1.7, sfx: 'click' },
      { tipo: 'clip', clip: '05-misiones', seg: 1.7, sfx: 'click' },
      { tipo: 'clip', clip: '05-cronograma', seg: 1.8, sfx: 'click' },
      { tipo: 'clip', clip: '06-avatar-asistente', seg: 1.7, sfx: 'click' },
      { tipo: 'clip', clip: '06-chat', seg: 2, sfx: 'click' },
      { tipo: 'clip', clip: '06-fotos', seg: 1.5, sfx: 'click' },
      { tipo: 'clip', clip: '06-diagrama', seg: 2, sfx: 'click' },
      { tipo: 'clip', clip: '06-formulas', seg: 1.8, sfx: 'click' },
      { tipo: 'clip', clip: '06-grafica', seg: 2, sfx: 'click' },
      { tipo: 'clip', clip: '07-sisifo', seg: 3.2, sfx: 'click' },
      { tipo: 'clip', clip: '07-wrapped', seg: 2.6, sfx: 'nice' },
      { tipo: 'clip', clip: '07-baile', seg: 4.1, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'ja', seg: 0.45, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'ar', seg: 0.45, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'hi', seg: 0.45, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'ko', seg: 0.45, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'ru', seg: 0.45, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'zh', seg: 0.45, sfx: 'click' },
      { tipo: 'escritorio', seg: 1.9, sfx: 'click' },
      { tipo: 'clip', clip: '07-panel-ia', seg: 3.01, sfx: 'click' },
      { tipo: 'clip', clip: '09-atardecer', seg: 3.2, sfx: 'click' },
      { tipo: 'cierre', seg: 6.5, sfx: 'golpe' },
      { tipo: 'clip', clip: '01-avatar', seg: 0.8 }
    ],
    voces: [
      { linea: 'gancho', desde: 0.1, seg: 2.57 },
      { linea: 'casa', desde: 4.67, seg: 6.62 },
      { linea: 'disena', desde: 11.87, seg: 6.53 },
      { linea: 'metas', desde: 19.07, seg: 5.82 },
      { linea: 'ia', desde: 25.97, seg: 8 },
      { linea: 'cerebro', desde: 35.27, seg: 7.5 },
      { linea: 'idiomas', desde: 45.17, seg: 7.36 },
      { linea: 'cta', desde: 52.78, seg: 2.94 },
      { linea: 'eslogan', desde: 55.98, seg: 4.67 }
    ],
    rotulos: [
      { clave: 'gancho', desde: 0.25, hasta: 4.57 },
      { clave: 'apps', desde: 6.97, hasta: 11.77 },
      { clave: 'disena', desde: 12.07, hasta: 15.77 },
      { clave: 'personaliza', desde: 16.17, hasta: 18.97 },
      { clave: 'metas', desde: 19.27, hasta: 24.17 },
      { clave: 'ia', desde: 26.17, hasta: 30.67 },
      { clave: 'progreso', desde: 38.57, hasta: 43.77 },
      { clave: 'idiomas', desde: 45.17, hasta: 47.67 },
      { clave: 'plataformas', desde: 47.87, hasta: 49.57 },
      { clave: 'conSinIa', desde: 49.77, hasta: 52.68 }
    ],
    efectos: [
      { clave: 'faa', desde: 2.77 },
      { clave: 'aaa', desde: 42.87 }
    ]
  },
  pl: {
    nombre: 'Reklama MPH',
    clips: 'en',
    lineas: {
      gancho: 'A gdyby tamagotchi… było tobą?',
      casa: 'MPH to dom 3D, w którym każdy pokój jest aplikacją: kuchnia, trening, finanse, cele, muzyka…',
      disena: 'Zaprojektuj swój dom i zdecyduj, która aplikacja trafi do którego pokoju: twoje centrum rozrywki, nauki, kreatywności i dbania o siebie.',
      metas: 'Twój terminarz, kalendarz, dziennik pokładowy i osobisty asystent, żebyś realizował swoje cele w prawdziwym życiu.',
      ia: 'Rozmawiaj z asystentami jak z ChatGPT, Gemini czy Claude: zapisują twój dzień i tworzą obrazy, materiały i modele 3D.',
      cerebro: 'Media społecznościowe rozpraszają twoją uwagę, a technologia myśli za ciebie. MPH to najpełniejszy i najfajniejszy sposób, żeby używać mózgu i widzieć, jak rosną nawyki, które sam wybierasz.',
      idiomas: 'W 16 językach. Web, komputer i telefon. Z kredytami AI, z darmowymi modelami lokalnymi… albo zupełnie bez AI.',
      cta: 'Wypróbuj za darmo. Albo zdobądź na własność za jedną opłatą.',
      eslogan: 'Buduj postać, budując nawyki. Projektuj dom, projektując swoją przyszłość.'
    },
    titulares: {
      gancho: 'A gdybyś to ty był tamagotchi?',
      apps: '21 aplikacji · 1 dom',
      disena: 'Twój dom, twoje aplikacje',
      metas: 'Prawdziwe cele',
      ia: 'AI opcjonalnie',
      progreso: 'Twoje postępy, na widoku',
      idiomas: '16 języków',
      plataformas: 'Web · PC · Telefon',
      conSinIa: 'Z AI… albo bez',
      personaliza: 'Urządź swój dom'
    },
    cierre: [
      'Buduj postać, budując nawyki.',
      'Projektuj dom, projektując przyszłość.',
      'Zdobywaj cele pokoi, rozprawiając się z zadaniami.'
    ],
    gratis: 'Wypróbuj za darmo',
    tomas: [
      { tipo: 'clip', clip: '01-avatar', seg: 3.99 },
      { tipo: 'clip', clip: '02-casa-gira', seg: 2.4, sfx: 'click' },
      { tipo: 'clip', clip: '03-app-cocina', seg: 0.8, sfx: 'click' },
      { tipo: 'clip', clip: '03-app-ejercicio', seg: 1, sfx: 'click' },
      { tipo: 'clip', clip: '03-app-finanzas', seg: 0.8, sfx: 'click' },
      { tipo: 'clip', clip: '03-app-metas', seg: 0.8, sfx: 'click' },
      { tipo: 'clip', clip: '03-app-studio', seg: 1.4, sfx: 'click' },
      { tipo: 'clip', clip: '04-mosaico', seg: 2, sfx: 'click' },
      { tipo: 'clip', clip: '04-editor', seg: 2.2, sfx: 'click' },
      { tipo: 'clip', clip: '04-temas', seg: 3.36, sfx: 'wow' },
      { tipo: 'clip', clip: '05-calendario', seg: 1.7, sfx: 'click' },
      { tipo: 'clip', clip: '05-misiones', seg: 1.7, sfx: 'click' },
      { tipo: 'clip', clip: '05-cronograma', seg: 1.8, sfx: 'click' },
      { tipo: 'clip', clip: '06-avatar-asistente', seg: 1.7, sfx: 'click' },
      { tipo: 'clip', clip: '06-chat', seg: 2, sfx: 'click' },
      { tipo: 'clip', clip: '06-fotos', seg: 1.5, sfx: 'click' },
      { tipo: 'clip', clip: '06-diagrama', seg: 2, sfx: 'click' },
      { tipo: 'clip', clip: '06-formulas', seg: 1.8, sfx: 'click' },
      { tipo: 'clip', clip: '06-grafica', seg: 2, sfx: 'click' },
      { tipo: 'clip', clip: '07-sisifo', seg: 3.2, sfx: 'click' },
      { tipo: 'clip', clip: '07-wrapped', seg: 3.39, sfx: 'nice' },
      { tipo: 'clip', clip: '07-baile', seg: 5.45, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'ja', seg: 0.45, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'ar', seg: 0.45, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'hi', seg: 0.45, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'ko', seg: 0.45, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'ru', seg: 0.45, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'zh', seg: 0.45, sfx: 'click' },
      { tipo: 'escritorio', seg: 1.9, sfx: 'click' },
      { tipo: 'clip', clip: '07-panel-ia', seg: 3.12, sfx: 'click' },
      { tipo: 'clip', clip: '09-atardecer', seg: 3.42, sfx: 'click' },
      { tipo: 'cierre', seg: 6.5, sfx: 'golpe' },
      { tipo: 'clip', clip: '01-avatar', seg: 0.8 }
    ],
    voces: [
      { linea: 'gancho', desde: 0.1, seg: 1.99 },
      { linea: 'casa', desde: 4.09, seg: 6.41 },
      { linea: 'disena', desde: 11.29, seg: 7.31 },
      { linea: 'metas', desde: 18.85, seg: 5.76 },
      { linea: 'ia', desde: 25.75, seg: 6.44 },
      { linea: 'cerebro', desde: 35.05, seg: 9.64 },
      { linea: 'idiomas', desde: 47.09, seg: 7.47 },
      { linea: 'cta', desde: 54.81, seg: 3.17 },
      { linea: 'eslogan', desde: 58.23, seg: 4.65 }
    ],
    rotulos: [
      { clave: 'gancho', desde: 0.25, hasta: 3.99 },
      { clave: 'apps', desde: 6.39, hasta: 11.19 },
      { clave: 'disena', desde: 11.49, hasta: 15.19 },
      { clave: 'personaliza', desde: 15.59, hasta: 18.75 },
      { clave: 'metas', desde: 19.05, hasta: 23.95 },
      { clave: 'ia', desde: 25.95, hasta: 30.45 },
      { clave: 'progreso', desde: 38.35, hasta: 43.55 },
      { clave: 'idiomas', desde: 47.09, hasta: 49.59 },
      { clave: 'plataformas', desde: 49.79, hasta: 51.49 },
      { clave: 'conSinIa', desde: 51.69, hasta: 54.71 }
    ],
    efectos: [
      { clave: 'faa', desde: 2.19 },
      { clave: 'aaa', desde: 44.79 }
    ]
  },
  nl: {
    nombre: 'MPH-advertentie',
    clips: 'en',
    lineas: {
      gancho: 'En als de Tamagotchi… jij was?',
      casa: 'MPH is een 3D-huis waarin elke kamer een app is: keuken, sport, financiën, doelen, muziek…',
      disena: 'Ontwerp je huis en kies welke app in welke kamer komt: jouw plek voor ontspanning, studie, creativiteit en zelfzorg.',
      metas: 'Je agenda, je kalender, je logboek en een persoonlijke assistent om je doelen in het echte leven te halen.',
      ia: 'Praat met je assistenten zoals met ChatGPT, Gemini of Claude: ze leggen je dag vast en maken afbeeldingen, materiaal en 3D-modellen.',
      cerebro: 'Sociale media versnipperen je aandacht en technologie denkt voor je. MPH is de meest complete en leukste manier om je brein te gebruiken en de gewoontes die jij kiest te zien groeien.',
      idiomas: 'In 16 talen. Web, desktop en mobiel. Met AI-credits, met gratis lokale modellen… of helemaal zonder AI.',
      cta: 'Probeer het gratis. Of maak het van jou met één betaling.',
      eslogan: 'Bouw je personage door je gewoontes op te bouwen. Ontwerp je huis, en ontwerp je toekomst.'
    },
    titulares: {
      gancho: 'Wat als jij een Tamagotchi was?',
      apps: '21 apps · 1 huis',
      disena: 'Jouw huis, jouw apps',
      metas: 'Echte doelen',
      ia: 'AI optioneel',
      progreso: 'Je vooruitgang, zichtbaar',
      idiomas: '16 talen',
      plataformas: 'Web · PC · Mobiel',
      conSinIa: 'Met AI… of zonder',
      personaliza: 'Maak je huis eigen'
    },
    cierre: [
      'Bouw je personage, door je gewoontes op te bouwen.',
      'Ontwerp je huis, en ontwerp je toekomst.',
      'Verover de doelen van elke kamer, en werk je taken weg.'
    ],
    gratis: 'Gratis proberen',
    tomas: [
      { tipo: 'clip', clip: '01-avatar', seg: 3.93 },
      { tipo: 'clip', clip: '02-casa-gira', seg: 2.4, sfx: 'click' },
      { tipo: 'clip', clip: '03-app-cocina', seg: 0.8, sfx: 'click' },
      { tipo: 'clip', clip: '03-app-ejercicio', seg: 1, sfx: 'click' },
      { tipo: 'clip', clip: '03-app-finanzas', seg: 0.8, sfx: 'click' },
      { tipo: 'clip', clip: '03-app-metas', seg: 0.8, sfx: 'click' },
      { tipo: 'clip', clip: '03-app-studio', seg: 1.4, sfx: 'click' },
      { tipo: 'clip', clip: '04-mosaico', seg: 2, sfx: 'click' },
      { tipo: 'clip', clip: '04-editor', seg: 2.2, sfx: 'click' },
      { tipo: 'clip', clip: '04-temas', seg: 3, sfx: 'wow' },
      { tipo: 'clip', clip: '05-calendario', seg: 1.7, sfx: 'click' },
      { tipo: 'clip', clip: '05-misiones', seg: 1.7, sfx: 'click' },
      { tipo: 'clip', clip: '05-cronograma', seg: 1.8, sfx: 'click' },
      { tipo: 'clip', clip: '06-avatar-asistente', seg: 1.7, sfx: 'click' },
      { tipo: 'clip', clip: '06-chat', seg: 2, sfx: 'click' },
      { tipo: 'clip', clip: '06-fotos', seg: 1.5, sfx: 'click' },
      { tipo: 'clip', clip: '06-diagrama', seg: 2, sfx: 'click' },
      { tipo: 'clip', clip: '06-formulas', seg: 1.8, sfx: 'click' },
      { tipo: 'clip', clip: '06-grafica', seg: 2, sfx: 'click' },
      { tipo: 'clip', clip: '07-sisifo', seg: 3.2, sfx: 'click' },
      { tipo: 'clip', clip: '07-wrapped', seg: 2.6, sfx: 'nice' },
      { tipo: 'clip', clip: '07-baile', seg: 4.97, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'ja', seg: 0.45, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'ar', seg: 0.45, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'hi', seg: 0.45, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'ko', seg: 0.45, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'ru', seg: 0.45, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'zh', seg: 0.45, sfx: 'click' },
      { tipo: 'escritorio', seg: 1.9, sfx: 'click' },
      { tipo: 'clip', clip: '07-panel-ia', seg: 2.72, sfx: 'click' },
      { tipo: 'clip', clip: '09-atardecer', seg: 3.34, sfx: 'click' },
      { tipo: 'cierre', seg: 6.5, sfx: 'golpe' },
      { tipo: 'clip', clip: '01-avatar', seg: 0.8 }
    ],
    voces: [
      { linea: 'gancho', desde: 0.1, seg: 1.93 },
      { linea: 'casa', desde: 4.03, seg: 5.88 },
      { linea: 'disena', desde: 11.23, seg: 5.99 },
      { linea: 'metas', desde: 18.43, seg: 4.63 },
      { linea: 'ia', desde: 25.33, seg: 7.09 },
      { linea: 'cerebro', desde: 34.63, seg: 8.37 },
      { linea: 'idiomas', desde: 45.4, seg: 7.07 },
      { linea: 'cta', desde: 52.72, seg: 3.09 },
      { linea: 'eslogan', desde: 56.06, seg: 5.15 }
    ],
    rotulos: [
      { clave: 'gancho', desde: 0.25, hasta: 3.93 },
      { clave: 'apps', desde: 6.33, hasta: 11.13 },
      { clave: 'disena', desde: 11.43, hasta: 15.13 },
      { clave: 'personaliza', desde: 15.53, hasta: 18.33 },
      { clave: 'metas', desde: 18.63, hasta: 23.53 },
      { clave: 'ia', desde: 25.53, hasta: 30.03 },
      { clave: 'progreso', desde: 37.93, hasta: 43.13 },
      { clave: 'idiomas', desde: 45.4, hasta: 47.9 },
      { clave: 'plataformas', desde: 48.1, hasta: 49.8 },
      { clave: 'conSinIa', desde: 50, hasta: 52.62 }
    ],
    efectos: [
      { clave: 'faa', desde: 2.13 },
      { clave: 'aaa', desde: 43.1 }
    ]
  },
  ar: {
    nombre: 'إعلان MPH',
    clips: 'en',
    lineas: {
      gancho: 'ماذا لو كان التاماغوتشي… هو أنت؟',
      casa: 'MPH بيت ثلاثي الأبعاد كل غرفة فيه تطبيق: المطبخ، التمارين، المال، الأهداف، الموسيقى…',
      disena: 'صمّم بيتك وقرّر أي تطبيق يذهب إلى كل غرفة: مركزك للترفيه والدراسة والإبداع والعناية بنفسك.',
      metas: 'مفكرتك وتقويمك ويومياتك ومساعد شخصي يعينك على تحقيق أهدافك في الحياة الحقيقية.',
      ia: 'تحدّث مع مساعديك كما تفعل مع ChatGPT أو Gemini أو Claude: يسجّلون يومك ويصنعون الصور والموارد والنماذج ثلاثية الأبعاد.',
      cerebro: 'تشتّت الشبكات الاجتماعية انتباهك، والتقنية تفكّر بدلًا عنك. MPH هو الطريقة الأكمل والأمتع لاستخدام عقلك ورؤية العادات التي تختارها وهي تنمو.',
      idiomas: 'بـ16 لغة. ويب وحاسوب وهاتف. برصيد ذكاء اصطناعي، أو بنماذج محلية مجانية… أو من دونه.',
      cta: 'جرّبه مجانًا. أو اجعله ملكك بدفعة واحدة.',
      eslogan: 'ابنِ شخصيتك ببناء عاداتك. صمّم بيتك، وأنت تصمّم مستقبلك.'
    },
    titulares: {
      gancho: 'ماذا لو كنتَ أنت التاماغوتشي؟',
      apps: '21 تطبيقًا · بيت واحد',
      disena: 'بيتك، تطبيقاتك',
      metas: 'أهداف حقيقية',
      ia: 'ذكاء اصطناعي اختياري',
      progreso: 'تقدّمك، ظاهر',
      idiomas: '16 لغة',
      plataformas: 'ويب · حاسوب · هاتف',
      conSinIa: 'بذكاء اصطناعي… أو من دونه',
      personaliza: 'خصّص بيتك'
    },
    cierre: [
      'ابنِ شخصيتك، ببناء عاداتك.',
      'صمّم بيتك، وأنت تصمّم مستقبلك.',
      'افتح أهداف الغرف، وأنت تنجز مهامك.'
    ],
    gratis: 'جرّبه مجانًا',
    tomas: [
      { tipo: 'clip', clip: '01-avatar', seg: 4.79 },
      { tipo: 'clip', clip: '02-casa-gira', seg: 2.4, sfx: 'click' },
      { tipo: 'clip', clip: '03-app-cocina', seg: 0.8, sfx: 'click' },
      { tipo: 'clip', clip: '03-app-ejercicio', seg: 1, sfx: 'click' },
      { tipo: 'clip', clip: '03-app-finanzas', seg: 0.8, sfx: 'click' },
      { tipo: 'clip', clip: '03-app-metas', seg: 0.8, sfx: 'click' },
      { tipo: 'clip', clip: '03-app-studio', seg: 2.59, sfx: 'click' },
      { tipo: 'clip', clip: '04-mosaico', seg: 2, sfx: 'click' },
      { tipo: 'clip', clip: '04-editor', seg: 2.2, sfx: 'click' },
      { tipo: 'clip', clip: '04-temas', seg: 3.26, sfx: 'wow' },
      { tipo: 'clip', clip: '05-calendario', seg: 1.7, sfx: 'click' },
      { tipo: 'clip', clip: '05-misiones', seg: 1.7, sfx: 'click' },
      { tipo: 'clip', clip: '05-cronograma', seg: 1.8, sfx: 'click' },
      { tipo: 'clip', clip: '06-avatar-asistente', seg: 1.7, sfx: 'click' },
      { tipo: 'clip', clip: '06-chat', seg: 2, sfx: 'click' },
      { tipo: 'clip', clip: '06-fotos', seg: 1.5, sfx: 'click' },
      { tipo: 'clip', clip: '06-diagrama', seg: 2, sfx: 'click' },
      { tipo: 'clip', clip: '06-formulas', seg: 1.8, sfx: 'click' },
      { tipo: 'clip', clip: '06-grafica', seg: 2, sfx: 'click' },
      { tipo: 'clip', clip: '07-sisifo', seg: 3.58, sfx: 'click' },
      { tipo: 'clip', clip: '07-wrapped', seg: 3.95, sfx: 'nice' },
      { tipo: 'clip', clip: '07-baile', seg: 5.45, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'ja', seg: 0.45, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'hi', seg: 0.45, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'ko', seg: 0.45, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'ru', seg: 0.45, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'zh', seg: 0.45, sfx: 'click' },
      { tipo: 'rafaga', idioma: 'de', seg: 0.45, sfx: 'click' },
      { tipo: 'escritorio', seg: 1.9, sfx: 'click' },
      { tipo: 'clip', clip: '07-panel-ia', seg: 3.03, sfx: 'click' },
      { tipo: 'clip', clip: '09-atardecer', seg: 3.63, sfx: 'click' },
      { tipo: 'cierre', seg: 6.5, sfx: 'golpe' },
      { tipo: 'clip', clip: '01-avatar', seg: 0.8 }
    ],
    voces: [
      { linea: 'gancho', desde: 0.1, seg: 2.79 },
      { linea: 'casa', desde: 4.89, seg: 8.14 },
      { linea: 'disena', desde: 13.28, seg: 7.21 },
      { linea: 'metas', desde: 20.74, seg: 6.53 },
      { linea: 'ia', desde: 27.64, seg: 8.93 },
      { linea: 'cerebro', desde: 36.94, seg: 10.58 },
      { linea: 'idiomas', desde: 49.92, seg: 7.38 },
      { linea: 'cta', desde: 57.55, seg: 3.38 },
      { linea: 'eslogan', desde: 61.18, seg: 5.31 }
    ],
    rotulos: [
      { clave: 'gancho', desde: 0.25, hasta: 4.79 },
      { clave: 'apps', desde: 7.19, hasta: 13.18 },
      { clave: 'disena', desde: 13.48, hasta: 17.18 },
      { clave: 'personaliza', desde: 17.58, hasta: 20.64 },
      { clave: 'metas', desde: 20.94, hasta: 25.84 },
      { clave: 'ia', desde: 27.84, hasta: 32.34 },
      { clave: 'progreso', desde: 40.24, hasta: 45.44 },
      { clave: 'idiomas', desde: 49.92, hasta: 52.42 },
      { clave: 'plataformas', desde: 52.62, hasta: 54.32 },
      { clave: 'conSinIa', desde: 54.52, hasta: 57.45 }
    ],
    efectos: [
      { clave: 'faa', desde: 2.99 },
      { clave: 'aaa', desde: 47.62 }
    ]
  }
}
