/**
 * Ilustraciones que la app ya trae de fábrica, por nombre normalizado del
 * ejercicio (`normalizarEjercicio`). Los archivos viven en `public/ejercicios/`.
 *
 * GENERADO por `scripts/generar-imagenes-ejercicios.mjs` — no lo edites a mano.
 */
import { normalizarEjercicio } from './stats'

const PRESET: Record<string, string> = {
  "abducción de cadera": 'abduccion-de-cadera',
  "abducción lateral de cadera": 'abduccion-lateral-de-cadera',
  "agarre activo y pasivo": 'agarre-activo-y-pasivo',
  "ángeles de pared (wall angels)": 'angeles-de-pared-wall-angels',
  "apertura de cadera": 'apertura-de-cadera',
  "apertura de pecho": 'apertura-de-pecho',
  "aperturas con mancuernas": 'aperturas-con-mancuernas',
  "aqua aeróbicos": 'aqua-aerobicos',
  "baile": 'baile',
  "balanceo dinámico de piernas": 'balanceo-dinamico-de-piernas',
  "básquetbol": 'basquetbol',
  "bicicleta estática": 'bicicleta-estatica',
  "boxeo": 'boxeo',
  "burpees": 'burpees',
  "caminadora": 'caminadora',
  "caminata": 'caminata',
  "caminata inclinada": 'caminata-inclinada',
  "caminata rápida": 'caminata-rapida',
  "carrera": 'carrera',
  "ciclismo": 'ciclismo',
  "circuito metabólico": 'circuito-metabolico',
  "círculos de hombros": 'circulos-de-hombros',
  "círculos de muñecas": 'circulos-de-munecas',
  "círculos de tobillo": 'circulos-de-tobillo',
  "cruce en polea": 'cruce-en-polea',
  "crunch abdominal": 'crunch-abdominal',
  "curl con barra": 'curl-con-barra',
  "curl con mancuernas": 'curl-con-mancuernas',
  "curl concentrado": 'curl-concentrado',
  "curl femoral": 'curl-femoral',
  "curl martillo": 'curl-martillo',
  "curl predicador": 'curl-predicador',
  "dislocaciones con goma (o palo)": 'dislocaciones-con-goma-o-palo',
  "dominadas": 'dominadas',
  "el gato y la mesa": 'el-gato-y-la-mesa',
  "el puente (glute bridge)": 'el-puente-glute-bridge',
  "elevación de piernas": 'elevacion-de-piernas',
  "elevación de talones": 'elevacion-de-talones',
  "elevación de talones unipodal": 'elevacion-de-talones-unipodal',
  "elevaciones frontales": 'elevaciones-frontales',
  "elevaciones laterales": 'elevaciones-laterales',
  "elíptica": 'eliptica',
  "encogimientos": 'encogimientos',
  "equilibrio unipodal (single leg balance)": 'equilibrio-unipodal-single-leg-balance',
  "escaladora": 'escaladora',
  "escaladores": 'escaladores',
  "esfinge": 'esfinge',
  "estiramiento de aductores": 'estiramiento-de-aductores',
  "estiramiento de cuádriceps": 'estiramiento-de-cuadriceps',
  "estiramiento de dorsales": 'estiramiento-de-dorsales',
  "estiramiento de dorsiflexión": 'estiramiento-de-dorsiflexion',
  "estiramiento de flexores": 'estiramiento-de-flexores',
  "estiramiento de flexores de cadera": 'estiramiento-de-flexores-de-cadera',
  "estiramiento de flexores en estocada": 'estiramiento-de-flexores-en-estocada',
  "estiramiento de gemelos": 'estiramiento-de-gemelos',
  "estiramiento de hombros": 'estiramiento-de-hombros',
  "estiramiento de isquiotibiales": 'estiramiento-de-isquiotibiales',
  "estiramiento de pecho/pectoral": 'estiramiento-de-pecho-pectoral',
  "estiramiento de trapecio superior": 'estiramiento-de-trapecio-superior',
  "estiramiento de tríceps": 'estiramiento-de-triceps',
  "estiramiento dinámico de isquiotibiales": 'estiramiento-dinamico-de-isquiotibiales',
  "estiramiento dorsal en pared": 'estiramiento-dorsal-en-pared',
  "estiramiento general": 'estiramiento-general',
  "estiramiento lumbar (boca abajo)": 'estiramiento-lumbar-boca-abajo',
  "estocadas (lunges)": 'estocadas-lunges',
  "extensión de cuádriceps": 'extension-de-cuadriceps',
  "extensión sobre cabeza": 'extension-sobre-cabeza',
  "extensión tríceps en polea": 'extension-triceps-en-polea',
  "face pull": 'face-pull',
  "figura 4": 'figura-4',
  "flexión de pie": 'flexion-de-pie',
  "flexión y extensión de muñeca": 'flexion-y-extension-de-muneca',
  "flexión y extensión en descarga": 'flexion-y-extension-en-descarga',
  "flexiones": 'flexiones',
  "foam roller": 'foam-roller',
  "fondos en paralelas": 'fondos-en-paralelas',
  "fondos entre bancos": 'fondos-entre-bancos',
  "fútbol": 'futbol',
  "gato-vaca": 'postura-gato-vaca',
  "guerrero i": 'guerrero-i',
  "guerrero ii": 'guerrero-ii',
  "hiit": 'hiit',
  "hilo y aguja": 'hilo-y-aguja',
  "hip thrust": 'hip-thrust',
  "hiperextensiones": 'hiperextensiones',
  "inclinación lateral de cuello": 'inclinacion-lateral-de-cuello',
  "isométricos cervicales": 'isometricos-cervicales',
  "jalón al pecho": 'jalon-al-pecho',
  "liberación miofascial con pelota": 'liberacion-miofascial-con-pelota',
  "lunge con apertura de pectoral": 'lunge-con-apertura-de-pectoral',
  "mariposa": 'mariposa',
  "mariposa reclinada": 'mariposa-reclinada',
  "movilidad 90/90": 'movilidad-90-90',
  "movilidad cervical": 'movilidad-cervical',
  "movilidad matutina": 'movilidad-matutina',
  "natación": 'natacion',
  "pádel": 'padel',
  "pájaros": 'pajaros',
  "patada de glúteo en polea": 'patada-de-gluteo-en-polea',
  "patada de tríceps": 'patada-de-triceps',
  "perro boca abajo": 'perro-boca-abajo',
  "peso muerto": 'peso-muerto',
  "peso muerto rumano": 'peso-muerto-rumano',
  "piernas en la pared": 'piernas-en-la-pared',
  "plancha": 'plancha',
  "plancha de muñecas": 'plancha-de-munecas',
  "plancha frontal (isométricos)": 'plancha-frontal-isometricos',
  "plancha lateral": 'plancha-lateral',
  "pointer (bird-dog)": 'pointer-bird-dog',
  "postura de la cobra": 'postura-de-la-cobra',
  "postura de la guirnalda": 'postura-de-la-guirnalda',
  "postura de la paloma": 'postura-de-la-paloma',
  "postura del niño": 'postura-del-nino',
  "postura del niño apoyada": 'postura-del-nino-apoyada',
  "postura gato-vaca": 'postura-gato-vaca',
  "prensa de pierna": 'prensa-de-pierna',
  "press arnold": 'press-arnold',
  "press banca": 'press-banca',
  "press con mancuernas": 'press-con-mancuernas',
  "press francés": 'press-frances',
  "press inclinado": 'press-inclinado',
  "press militar": 'press-militar',
  "puente de glúteo": 'puente-de-gluteo',
  "pull-over": 'pull-over',
  "rana": 'rana',
  "recogida de toalla con dedos": 'recogida-de-toalla-con-dedos',
  "remo (máquina)": 'remo-maquina',
  "remo con barra": 'remo-con-barra',
  "remo con mancuerna": 'remo-con-mancuerna',
  "remo en polea baja": 'remo-en-polea-baja',
  "respiración profunda": 'respiracion-profunda',
  "retracción de barbilla": 'retracciones-de-barbilla-chin-tucks',
  "retracción escapular": 'retraccion-escapular',
  "retracciones de barbilla (chin tucks)": 'retracciones-de-barbilla-chin-tucks',
  "roll down (curl jefferson)": 'roll-down-curl-jefferson',
  "rotación externa con banda": 'rotacion-externa-con-banda',
  "rotación torácica": 'rotacion-toracica',
  "rotaciones cervicales con nodding": 'rotaciones-cervicales-con-nodding',
  "rotaciones de columna": 'rotaciones-de-columna',
  "rotaciones y medios círculos": 'rotaciones-y-medios-circulos',
  "rueda abdominal": 'rueda-abdominal',
  "russian twist": 'russian-twist',
  "saltar cuerda": 'saltar-cuerda',
  "saludo al sol": 'saludo-al-sol',
  "savasana": 'savasana',
  "senderismo": 'senderismo',
  "sentadilla": 'sentadilla',
  "sentadilla búlgara": 'sentadilla-bulgara',
  "sentadilla frontal": 'sentadilla-frontal',
  "sentadilla isométrica (wall squat)": 'sentadilla-isometrica-wall-squat',
  "sentadilla profunda con apertura": 'sentadilla-profunda-con-apertura',
  "sentadillas del arquero": 'sentadillas-del-arquero',
  "sprints": 'sprints',
  "tenis": 'tenis',
  "thread the needle (enhebrar aguja)": 'thread-the-needle-enhebrar-aguja',
  "torsión espinal": 'torsion-espinal',
  "torsión reclinada": 'torsion-reclinada',
  "torsiones lumbares suaves": 'torsiones-lumbares-suaves',
  "trail running": 'trail-running',
  "triángulo": 'triangulo',
  "trote suave": 'trote-suave',
  "yoga flow": 'yoga-flow',
  "zancada baja": 'zancada-baja',
  "zancadas": 'zancadas',
}

/** URL de la ilustración preguardada del ejercicio, o null si no trae. */
export function urlImagenPreset(nombre: string): string | null {
  const slug = PRESET[normalizarEjercicio(nombre)]
  return slug ? `${import.meta.env.BASE_URL}ejercicios/${slug}.webp` : null
}
