// Generado por `npm run ejemplos:texto` — no lo edites a mano.
// Contenido del ejemplo de fábrica de sala, en los dos idiomas. Vive aparte
// de `dict.ts` a propósito: en cuanto se crea es dato del usuario, no interfaz.

export const TEXTOS_SALA = {
  es: {
    lugarPendiente: 'Oporto',
    paisPendiente: 'Portugal',
    notaPendiente: 'Quiero cruzar el puente Luis I al atardecer. Mi tía me habla del mercado de Bolhão desde que yo era chica.',
    dia1Destino: 'Oporto, la Ribeira',
    dia1Actividades: 'Bajar a la Ribeira, cruzar el puente a pie y cenar bacalao junto al río.',
    dia1Hospedaje: 'Pensión familiar en la Baixa',
    dia2Destino: 'Vila Nova de Gaia',
    dia2Actividades: 'Cruzar en barco rabelo, ver las bodegas y subir al mirador de la Serra do Pilar.',
    dia3Destino: 'Valle del Duero, en tren',
    dia3Actividades: 'Tomar la línea del Duero hasta Pinhão y caminar entre los viñedos en terrazas.',
    lugarVisitado: 'Burdeos',
    paisVisitado: 'Francia',
    recuerdo: 'Llegué a Burdeos con lluvia y acabé pedaleando por la orilla del Garona. Comí canelés tibios en una placita con soportales. Volví con el cuaderno lleno de bocetos de tejados.',
    ruta: 'Ruta atlántica: Burdeos a Oporto',
  },
  en: {
    lugarPendiente: 'Porto',
    paisPendiente: 'Portugal',
    notaPendiente: 'I want to walk the Dom Luis bridge at sunset. My aunt has talked about the Bolhao market since I was a kid.',
    dia1Destino: 'Porto, Ribeira district',
    dia1Actividades: 'Wander the Ribeira, walk across the bridge and have salt cod by the river.',
    dia1Hospedaje: 'Family-run guesthouse downtown',
    dia2Destino: 'Vila Nova de Gaia',
    dia2Actividades: 'Cross on a rabelo boat, tour the cellars, climb to the Serra do Pilar lookout.',
    dia3Destino: 'Douro Valley by train',
    dia3Actividades: 'Take the Douro line out to Pinhao and walk the terraced vineyards before dusk.',
    lugarVisitado: 'Bordeaux',
    paisVisitado: 'France',
    recuerdo: 'I got to Bordeaux in the rain and ended up biking along the Garonne anyway. I ate warm caneles in a small arcaded square. I came home with a sketchbook full of rooftops.',
    ruta: 'Atlantic run: Bordeaux to Porto',
  },
  pt: {
    lugarPendiente: 'Porto',
    paisPendiente: 'Portugal',
    notaPendiente: 'Quero atravessar a ponte Dom Luís I ao entardecer. Minha tia fala do mercado do Bolhão desde que eu era pequena.',
    dia1Destino: 'Porto, a Ribeira',
    dia1Actividades: 'Descer até a Ribeira, atravessar a ponte a pé e jantar bacalhau à beira-rio.',
    dia1Hospedaje: 'Pensão familiar na Baixa',
    dia2Destino: 'Vila Nova de Gaia',
    dia2Actividades: 'Atravessar de barco rabelo, visitar as caves e subir ao mirante da Serra do Pilar.',
    dia3Destino: 'Vale do Douro, de trem',
    dia3Actividades: 'Pegar a linha do Douro até Pinhão e caminhar entre os vinhedos em socalcos.',
    lugarVisitado: 'Bordéus',
    paisVisitado: 'França',
    recuerdo: 'Cheguei a Bordéus com chuva e acabei pedalando pela margem do Garona. Comi canelés mornos numa pracinha com arcadas. Voltei com o caderno cheio de esboços de telhados.',
    ruta: 'Rota atlântica: Bordéus a Porto',
  },
  fr: {
    lugarPendiente: 'Porto',
    paisPendiente: 'Portugal',
    notaPendiente: 'Je veux traverser le pont Dom Luís au coucher du soleil. Ma tante me parle du marché du Bolhão depuis que je suis toute petite.',
    dia1Destino: 'Porto, le quartier de la Ribeira',
    dia1Actividades: 'Flâner dans la Ribeira, traverser le pont à pied et dîner de morue au bord du fleuve.',
    dia1Hospedaje: 'Pension familiale dans la Baixa',
    dia2Destino: 'Vila Nova de Gaia',
    dia2Actividades: 'Traverser en bateau rabelo, visiter les caves et monter au belvédère de la Serra do Pilar.',
    dia3Destino: 'Vallée du Douro, en train',
    dia3Actividades: 'Prendre la ligne du Douro jusqu\'à Pinhão et marcher parmi les vignes en terrasses.',
    lugarVisitado: 'Bordeaux',
    paisVisitado: 'France',
    recuerdo: 'Je suis arrivée à Bordeaux sous la pluie et j\'ai fini par pédaler le long de la Garonne. J\'ai mangé des canelés tièdes sur une petite place à arcades. Je suis rentrée avec le carnet plein de croquis de toits.',
    ruta: 'Route atlantique: Bordeaux–Porto',
  },
  de: {
    lugarPendiente: 'Porto',
    paisPendiente: 'Portugal',
    notaPendiente: 'Ich möchte bei Sonnenuntergang über die Dom-Luís-Brücke gehen. Meine Tante erzählt mir schon seit meiner Kindheit vom Bolhão-Markt.',
    dia1Destino: 'Porto, das Ribeira-Viertel',
    dia1Actividades: 'Durch die Ribeira schlendern, die Brücke zu Fuß überqueren und Kabeljau am Fluss essen.',
    dia1Hospedaje: 'Familienpension in der Baixa',
    dia2Destino: 'Vila Nova de Gaia',
    dia2Actividades: 'Mit dem Rabelo-Boot übersetzen, die Weinkeller besichtigen und zum Aussichtspunkt der Serra do Pilar hinaufsteigen.',
    dia3Destino: 'Douro-Tal, mit dem Zug',
    dia3Actividades: 'Die Douro-Linie bis Pinhão nehmen und zwischen den Terrassen-Weinbergen spazieren.',
    lugarVisitado: 'Bordeaux',
    paisVisitado: 'Frankreich',
    recuerdo: 'Ich kam bei Regen in Bordeaux an und bin am Ende am Ufer der Garonne entlanggeradelt. Ich habe warme Canelés auf einem kleinen Platz mit Arkaden gegessen. Ich kam mit dem Notizbuch voller Dachskizzen zurück.',
    ruta: 'Atlantikroute: Bordeaux–Porto',
  },
  it: {
    lugarPendiente: 'Porto',
    paisPendiente: 'Portogallo',
    notaPendiente: 'Voglio attraversare il ponte Dom Luís al tramonto. Mia zia mi parla del mercato del Bolhão da quando ero piccola.',
    dia1Destino: 'Porto, la Ribeira',
    dia1Actividades: 'Scendere alla Ribeira, attraversare il ponte a piedi e cenare a base di baccalà lungo il fiume.',
    dia1Hospedaje: 'Pensione familiare nella Baixa',
    dia2Destino: 'Vila Nova de Gaia',
    dia2Actividades: 'Attraversare in barca rabelo, visitare le cantine e salire al belvedere della Serra do Pilar.',
    dia3Destino: 'Valle del Douro, in treno',
    dia3Actividades: 'Prendere la linea del Douro fino a Pinhão e camminare tra i vigneti terrazzati.',
    lugarVisitado: 'Bordeaux',
    paisVisitado: 'Francia',
    recuerdo: 'Sono arrivata a Bordeaux sotto la pioggia e ho finito per pedalare lungo la Garonna. Ho mangiato canelé tiepidi in una piazzetta porticata. Sono tornata con il quaderno pieno di schizzi di tetti.',
    ruta: 'Rotta atlantica: Bordeaux-Porto',
  },
  ja: {
    lugarPendiente: 'ポルト',
    paisPendiente: 'ポルトガル',
    notaPendiente: '夕暮れ時にドン・ルイス1世橋を渡ってみたいです。ボルハン市場の話は子どもの頃からずっと叔母に聞かされています。',
    dia1Destino: 'ポルト、リベイラ地区',
    dia1Actividades: 'リベイラまで下り、橋を歩いて渡り、川沿いでバカリャウ(干し鱈)の夕食。',
    dia1Hospedaje: 'バイシャ地区の家族経営の宿',
    dia2Destino: 'ヴィラ・ノヴァ・デ・ガイア',
    dia2Actividades: 'ラベロ船で対岸へ渡り、ワイナリーを見学、セーラ・ド・ピラールの展望台へ。',
    dia3Destino: 'ドウロ渓谷、列車で',
    dia3Actividades: 'ドウロ線でピニャオンまで行き、段々畑のぶどう畑を歩く。',
    lugarVisitado: 'ボルドー',
    paisVisitado: 'フランス',
    recuerdo: '雨の中ボルドーに着いて、結局ガロンヌ川沿いを自転車で走りました。アーケードのある小さな広場で温かいカヌレを食べました。屋根のスケッチでいっぱいのノートを持って帰りました。',
    ruta: '大西洋ルート:ボルドーからポルトへ',
  },
  zh: {
    lugarPendiente: '波尔图',
    paisPendiente: '葡萄牙',
    notaPendiente: '想在傍晚走过路易一世大桥。姑姑从我小时候起就一直跟我说博良市场的事。',
    dia1Destino: '波尔图,里贝拉区',
    dia1Actividades: '走到里贝拉,步行过桥,在河边吃鳕鱼晚餐。',
    dia1Hospedaje: '拜沙区的家庭旅馆',
    dia2Destino: '加亚新城',
    dia2Actividades: '乘拉贝洛船过河,参观酒窖,再登上皮拉尔山观景台。',
    dia3Destino: '杜罗河谷,坐火车',
    dia3Actividades: '搭杜罗线到皮尼昂,走在梯田葡萄园之间。',
    lugarVisitado: '波尔多',
    paisVisitado: '法国',
    recuerdo: '冒雨到达波尔多,最后沿着加龙河骑车。在一个有拱廊的小广场吃了温热的可露丽。回来时笔记本里画满了屋顶的速写。',
    ruta: '大西洋路线:波尔多到波尔图',
  },
  ko: {
    lugarPendiente: '포르투',
    paisPendiente: '포르투갈',
    notaPendiente: '해 질 무렵에 동 루이스 1세 다리를 건너보고 싶어요. 이모가 어릴 때부터 볼량 시장 이야기를 해주셨어요.',
    dia1Destino: '포르투, 리베이라 지구',
    dia1Actividades: '리베이라까지 내려가서 다리를 걸어서 건너고, 강가에서 대구 요리로 저녁 먹기.',
    dia1Hospedaje: '바이샤 지구의 가족 운영 게스트하우스',
    dia2Destino: '빌라 노바 드 가이아',
    dia2Actividades: '하벨루 배로 강을 건너 와이너리를 둘러보고 세하 두 필라르 전망대까지 올라가기.',
    dia3Destino: '도루 계곡, 기차로',
    dia3Actividades: '도루 노선을 타고 피녕오까지 가서 계단식 포도밭 사이를 걷기.',
    lugarVisitado: '보르도',
    paisVisitado: '프랑스',
    recuerdo: '비 오는 보르도에 도착했는데 결국 가론강변을 따라 자전거를 탔어요. 아케이드가 있는 작은 광장에서 따뜻한 카늘레를 먹었어요. 지붕 스케치로 가득 찬 노트를 들고 돌아왔어요.',
    ruta: '대서양 루트: 보르도에서 포르투까지',
  },
  ru: {
    lugarPendiente: 'Порту',
    paisPendiente: 'Португалия',
    notaPendiente: 'Хочется перейти мост Дона Луиша I на закате. Тётя с детства рассказывает про рынок Болан.',
    dia1Destino: 'Порту, квартал Рибейра',
    dia1Actividades: 'Спуститься в Рибейру, перейти мост пешком и поужинать треской у реки.',
    dia1Hospedaje: 'Семейный пансион в квартале Байша',
    dia2Destino: 'Вила-Нова-ди-Гая',
    dia2Actividades: 'Переправиться на лодке рабело, посмотреть винные погреба и подняться на смотровую площадку Серра-ду-Пилар.',
    dia3Destino: 'Долина Дору на поезде',
    dia3Actividades: 'Проехать по линии Дору до Пиньяна и пройтись между террасными виноградниками.',
    lugarVisitado: 'Бордо',
    paisVisitado: 'Франция',
    recuerdo: 'Приезд в Бордо пришёлся на дождь, и в итоге весь день прошёл за велопрогулкой вдоль Гаронны. Тёплые канеле нашлись на маленькой площади с аркадами. Домой вернулся блокнот, полный набросков крыш.',
    ruta: 'Атлантический маршрут: Бордо — Порту',
  },
  hi: {
    lugarPendiente: 'पोर्तो',
    paisPendiente: 'पुर्तगाल',
    notaPendiente: 'शाम ढलते वक़्त डॉम लुइस प्रथम पुल पार करने का मन है। बचपन से बुआ बोलहाँव बाज़ार की बातें सुनाती आई हैं।',
    dia1Destino: 'पोर्तो, रिबेरा इलाक़ा',
    dia1Actividades: 'रिबेरा तक उतरना, पैदल पुल पार करना और नदी किनारे कॉड मछली का डिनर।',
    dia1Hospedaje: 'बाइशा इलाक़े में पारिवारिक गेस्टहाउस',
    dia2Destino: 'विला नोवा दे गाया',
    dia2Actividades: 'रबेलो नाव से पार जाना, वाइनरी देखना और सेरा दो पिलार व्यूपॉइंट तक चढ़ना।',
    dia3Destino: 'दॉरो घाटी, ट्रेन से',
    dia3Actividades: 'दॉरो लाइन से पिन्याओं तक जाना और सीढ़ीदार अंगूर के बाग़ों के बीच टहलना।',
    lugarVisitado: 'बोर्दो',
    paisVisitado: 'फ़्रांस',
    recuerdo: 'बोर्दो पहुँचते ही बारिश शुरू हो गई और आख़िर में गारोन नदी किनारे साइकिल चलाना हो गया। मेहराबों वाले एक छोटे चौक में गरम कानेले मिले। छतों के स्केच से भरी नोटबुक साथ लेकर वापसी हुई।',
    ruta: 'अटलांटिक मार्ग: बोर्दो से पोर्तो',
  },
  tr: {
    lugarPendiente: 'Porto',
    paisPendiente: 'Portekiz',
    notaPendiente: 'Gün batımında Dom Luís Köprüsü\'nü yürüyerek geçmek istiyorum. Teyzem küçüklüğümden beri bana Bolhão pazarından bahsediyor.',
    dia1Destino: 'Porto, Ribeira',
    dia1Actividades: 'Ribeira\'ya inmek, köprüyü yürüyerek geçmek ve nehir kenarında bakalyaro yemek.',
    dia1Hospedaje: 'Baixa\'da aile işletmesi bir pansiyon',
    dia2Destino: 'Vila Nova de Gaia',
    dia2Actividades: 'Rabelo teknesiyle karşıya geçmek, şarap mahzenlerini gezmek ve Serra do Pilar seyir terasına çıkmak.',
    dia3Destino: 'Douro Vadisi, trenle',
    dia3Actividades: 'Douro hattıyla Pinhão\'ya gitmek ve teraslı bağların arasında yürümek.',
    lugarVisitado: 'Bordeaux',
    paisVisitado: 'Fransa',
    recuerdo: 'Bordeaux\'ya yağmurla vardım ve sonunda Garonne kıyısında bisiklet sürdüm. Kemerli küçük bir meydanda ılık kanelé yedim. Defterim çatı eskizleriyle dolu döndüm.',
    ruta: 'Atlantik rotası: Bordeaux\'dan Porto\'ya',
  },
  id: {
    lugarPendiente: 'Porto',
    paisPendiente: 'Portugal',
    notaPendiente: 'Ingin menyeberangi Jembatan Dom Luís I saat matahari terbenam. Bibi selalu cerita soal pasar Bolhão sejak aku masih kecil.',
    dia1Destino: 'Porto, distrik Ribeira',
    dia1Actividades: 'Turun ke Ribeira, menyeberangi jembatan dengan jalan kaki, dan makan malam ikan kod di tepi sungai.',
    dia1Hospedaje: 'Penginapan keluarga di Baixa',
    dia2Destino: 'Vila Nova de Gaia',
    dia2Actividades: 'Menyeberang dengan perahu rabelo, melihat gudang anggur, dan naik ke titik pandang Serra do Pilar.',
    dia3Destino: 'Lembah Douro, naik kereta',
    dia3Actividades: 'Naik jalur Douro sampai Pinhão dan jalan-jalan di antara kebun anggur bertingkat.',
    lugarVisitado: 'Bordeaux',
    paisVisitado: 'Prancis',
    recuerdo: 'Sampai di Bordeaux saat hujan dan akhirnya malah gowes di tepi Sungai Garonne. Makan canelé hangat di alun-alun kecil beratap lengkung. Pulang dengan buku sketsa penuh gambar atap rumah.',
    ruta: 'Rute Atlantik: Bordeaux ke Porto',
  },
  pl: {
    lugarPendiente: 'Porto',
    paisPendiente: 'Portugalia',
    notaPendiente: 'Chęć przejścia przez most Dom Luís I o zachodzie słońca. Ciocia opowiada o targu Bolhão, odkąd sięgam pamięcią.',
    dia1Destino: 'Porto, dzielnica Ribeira',
    dia1Actividades: 'Zejście do Ribeiry, przejście przez most na piechotę i kolacja z dorszem nad rzeką.',
    dia1Hospedaje: 'Rodzinny pensjonat w dzielnicy Baixa',
    dia2Destino: 'Vila Nova de Gaia',
    dia2Actividades: 'Przeprawa łodzią rabelo, zwiedzanie piwnic winnych i wejście na punkt widokowy Serra do Pilar.',
    dia3Destino: 'Dolina Douro, pociągiem',
    dia3Actividades: 'Linia Douro aż do Pinhão i spacer między tarasowymi winnicami.',
    lugarVisitado: 'Bordeaux',
    paisVisitado: 'Francja',
    recuerdo: 'Przyjazd do Bordeaux w deszczu i ostatecznie przejażdżka rowerem wzdłuż Garonny. Ciepłe canelé na małym placyku z arkadami. Powrót z notatnikiem pełnym szkiców dachów.',
    ruta: 'Trasa atlantycka: Bordeaux–Porto',
  },
  ar: {
    lugarPendiente: 'بورتو',
    paisPendiente: 'البرتغال',
    notaPendiente: 'أريد عبور جسر دوم لويس الأول عند الغروب. تتحدث خالتي عن سوق بولهاو منذ الصغر.',
    dia1Destino: 'بورتو، حي ريبيرا',
    dia1Actividades: 'النزول إلى ريبيرا، وعبور الجسر سيرًا، وتناول عشاء من سمك القد على ضفة النهر.',
    dia1Hospedaje: 'نُزل عائلي في حي بايشا',
    dia2Destino: 'فيلا نوفا دي غايا',
    dia2Actividades: 'العبور بقارب رابيلو، ومشاهدة مخازن النبيذ، والصعود إلى مطل سييرا دو بيلار.',
    dia3Destino: 'وادي دورو، بالقطار',
    dia3Actividades: 'ركوب خط دورو حتى بينهاو والمشي بين كروم العنب المدرّجة.',
    lugarVisitado: 'بوردو',
    paisVisitado: 'فرنسا',
    recuerdo: 'وصلتُ إلى بوردو تحت المطر وانتهى بي الأمر أركب الدراجة على ضفة نهر الغارون. تناولتُ كانيليه دافئًا في ساحة صغيرة ذات أروقة. عدتُ ودفتري مليء برسومات الأسطح.',
    ruta: 'الطريق الأطلسي: من بوردو إلى بورتو',
  },
  nl: {
    lugarPendiente: 'Porto',
    paisPendiente: 'Portugal',
    notaPendiente: 'Wil bij zonsondergang de Dom Luísbrug oversteken. Mijn tante praat al over de Bolhão-markt sinds ik klein was.',
    dia1Destino: 'Porto, de Ribeira',
    dia1Actividades: 'Afdalen naar de Ribeira, te voet de brug oversteken en kabeljauw eten aan de rivier.',
    dia1Hospedaje: 'Familiepension in de Baixa',
    dia2Destino: 'Vila Nova de Gaia',
    dia2Actividades: 'Oversteken met een rabeloboot, de wijnkelders bezoeken en naar het uitzichtpunt van de Serra do Pilar klimmen.',
    dia3Destino: 'Douro-vallei, met de trein',
    dia3Actividades: 'De Douro-lijn nemen tot Pinhão en tussen de terrasvormige wijngaarden lopen.',
    lugarVisitado: 'Bordeaux',
    paisVisitado: 'Frankrijk',
    recuerdo: 'Aankomst in Bordeaux in de regen en uiteindelijk toch fietsen langs de oever van de Garonne. Warme canelés gegeten op een pleintje met arcades. Teruggekomen met een schetsboek vol daken.',
    ruta: 'Atlantische route: Bordeaux naar Porto',
  },
}
